language-name-aa = আফাৰ
language-name-ab = আবখাজিয়ান
language-name-ace = আচিনিজ
language-name-ada = আদাংমে
language-name-ady = আদিগে
language-name-af = আফ্ৰিকানছ্
language-name-agq = আঘেম
language-name-ain = আইনু
language-name-ak = আকান
language-name-ale = আলেউট
language-name-alt = দাক্ষিণাত্য আল্টাই
language-name-am = আমহাৰিক
language-name-an = আৰ্গোনিজ
language-name-anp = আঙ্গিকা
language-name-ar = আৰবী
language-name-ar_001 = আধুনিক মানক আৰবী
language-name-arn = মাপুচে
language-name-arp = আৰাপাহো
language-name-as = অসমীয়া
language-name-asa = আছু
language-name-ast = এষ্টুৰীয়
language-name-av = আভেৰিক
language-name-awa = আৱাধি
language-name-ay = আয়মাৰা
language-name-az = আজেৰবাইজানী
language-name-ba = বাছখিৰ
language-name-ban = বালিনীজ
language-name-bas = বাছা
language-name-be = বেলাৰুছীয়
language-name-bem = বেম্বা
language-name-bez = বেনা
language-name-bg = বুলগেৰীয়
language-name-bho = ভোজপুৰী
language-name-bi = বিছলামা
language-name-bin = বিনি
language-name-bla = ছিক্সিকা
language-name-bm = বামবাৰা
language-name-bn = বাংলা
language-name-bo = তিব্বতী
language-name-br = ব্ৰেটন
language-name-brx = বড়ো
language-name-bs = বছনীয়
language-name-bug = বগিনীজ
language-name-byn = ব্লিন
language-name-ca = কাতালান
language-name-ce = চেচেন
language-name-ceb = চিবুৱানো
language-name-cgg = চিগা
language-name-ch = চামোৰো
language-name-chk = চুকিজ
language-name-chm = মাৰি
language-name-cho = চোক্টাউ
language-name-chr = চেৰোকি
language-name-chy = চাইয়েন
language-name-ckb = চেণ্ট্ৰেল কুৰ্ডিচ
language-name-co = কোৰ্ছিকান
language-name-crs = ছেছেলৱা ক্ৰিওল ফ্ৰেন্স
language-name-cs = চেক
language-name-cu = চাৰ্চ শ্লেভিক
language-name-cv = চুভাচ
language-name-cy = ৱেলচ
language-name-da = ডেনিচ
language-name-dak = ডাকোটা
language-name-dar = দাৰ্গৱা
language-name-dav = তেইতা
language-name-de = জাৰ্মান
language-name-de_AT = অষ্ট্ৰেলিয়ান জাৰ্মান
language-name-de_CH = ছুইচ হাই জাৰ্মান
language-name-dgr = ডোগ্ৰিব
language-name-dje = ঝাৰ্মা
language-name-dsb = ল’ৱাৰ ছোৰ্বিয়ান
language-name-dua = ডুৱালা
language-name-dv = দিবেহি
language-name-dyo = জোলা-ফ’নি
language-name-dz = জোংখা
language-name-dzg = দাজাগা
language-name-ebu = এম্বু
language-name-ee = ইৱে
language-name-efi = এফিক
language-name-eka = একাজুক
language-name-el = গ্ৰীক
language-name-en = ইংৰাজী
language-name-en_AU = অষ্ট্ৰেলিয়ান ইংৰাজী
language-name-en_CA = কানাডিয়ান ইংৰাজী
language-name-en_GB = ব্ৰিটিছ ইংৰাজী
language-name-en_US = আমেৰিকান ইংৰাজী
language-name-eo = এস্পেৰান্তো
language-name-es = স্পেনিচ
language-name-es_419 = লেটিন আমেৰিকান স্পেনিচ
language-name-es_ES = ইউৰোপীয়ান স্পেনিচ
language-name-es_MX = মেক্সিকান স্পেনিচ
language-name-et = এষ্টোনিয়
language-name-eu = বাস্ক
language-name-ewo = ইওন্দো
language-name-fa = ফাৰ্ছী
language-name-ff = ফুলাহ
language-name-fi = ফিনিচ
language-name-fil = ফিলিপিনো
language-name-fj = ফিজিয়ান
language-name-fo = ফাৰোইজ
language-name-fon = ফ’ন
language-name-fr = ফ্ৰেন্স
language-name-fr_CA = কানাডিয়ান ফ্ৰেন্স
language-name-fr_CH = ছুইচ ফ্ৰেন্স
language-name-fur = ফ্ৰিউলিয়ান
language-name-fy = ৱেষ্টাৰ্ণ ফ্ৰিছিয়ান
language-name-ga = আইৰিচ
language-name-gaa = গা
language-name-gd = স্কটিচ গেইলিক
language-name-gez = গীজ
language-name-gil = গিলবাৰ্টিছ
language-name-gl = গেলিচিয়ান
language-name-gn = গুৱাৰাণী
language-name-gor = গোৰোন্তালো
language-name-gsw = ছুইচ জাৰ্মান
language-name-gu = গুজৰাটী
language-name-guz = গুছি
language-name-gv = মেংক্স
language-name-gwi = জিউইচিন
language-name-ha = হাউছা
language-name-haw = হাৱাই
language-name-he = হিব্ৰু
language-name-hi = হিন্দী
language-name-hil = হিলিগায়নোন
language-name-hmn = হমং
language-name-hr = ক্ৰোৱেচিয়ান
language-name-hsb = আপাৰ ছোৰ্বিয়ান
language-name-ht = হেইটিয়ান ক্ৰিয়ল
language-name-hu = হাঙ্গেৰিয়ান
language-name-hup = হুপা
language-name-hy = আৰ্মেনীয়
language-name-hz = হেৰেৰো
language-name-ia = ইণ্টাৰলিংগুৱা
language-name-iba = ইবান
language-name-ibb = ইবিবিও
language-name-id = ইণ্ডোনেচিয়
language-name-ig = ইগ্বো
language-name-ii = ছিচুৱান ই
language-name-ilo = ইলোকো
language-name-inh = ইংগুচ
language-name-io = ইডো
language-name-is = আইচলেণ্ডিক
language-name-it = ইটালিয়ান
language-name-iu = ইনুক্টিটুট
language-name-ja = জাপানী
language-name-jbo = লোজ্বান
language-name-jgo = নগোম্বা
language-name-jmc = মেকহেম
language-name-jv = জাভানী
language-name-ka = জৰ্জিয়ান
language-name-kab = কাবাইল
language-name-kac = কাচিন
language-name-kaj = জজু
language-name-kam = কাম্বা
language-name-kbd = কাবাৰ্ডিয়ান
language-name-kcg = ত্যাপ
language-name-kde = মাকোণ্ড
language-name-kea = কাবুভেৰ্ডিয়ানু
language-name-kfo = কোৰো
language-name-kha = খাচি
language-name-khq = কোয়াৰ চিনি
language-name-ki = কিকুয়ু
language-name-kj = কুয়ানিয়ামা
language-name-kk = কাজাখ
language-name-kkj = কাকো
language-name-kl = কালালিছুট
language-name-kln = কালেনজিন
language-name-km = খমেৰ
language-name-kmb = কিম্বুন্দু
language-name-kn = কানাড়া
language-name-ko = কোৰিয়ান
language-name-kok = কোংকণী
language-name-kpe = কেপেল
language-name-kr = কানুৰি
language-name-krc = কাৰাচে-বাল্কাৰ
language-name-krl = কেৰেলিয়ান
language-name-kru = কুৰুখ
language-name-ks = কাশ্মিৰী
language-name-ksb = চাম্বালা
language-name-ksf = বাফিয়া
language-name-ksh = কোলোগনিয়ান
language-name-ku = কুৰ্ডিচ
language-name-kum = কুমিক
language-name-kv = কোমি
language-name-kw = কোৰ্নিচ
language-name-ky = কিৰ্গিজ
language-name-la = লেটিন
language-name-lad = লাডিনো
language-name-lag = লাংগি
language-name-lb = লাক্সেমবাৰ্গিচ
language-name-lez = লেজঘিয়ান
language-name-lg = গান্দা
language-name-li = লিম্বুৰ্গিচ
language-name-lkt = লাকোটা
language-name-ln = লিংগালা
language-name-lo = লাও
language-name-loz = লোজি
language-name-lrc = উদীচ্য লুৰি
language-name-lt = লিথুৱানিয়ান
language-name-lu = লুবা-কাটাংগা
language-name-lua = লুবা-লুলুৱা
language-name-lun = লুণ্ডা
language-name-luo = লুও
language-name-lus = মিজো
language-name-luy = লুইয়া
language-name-lv = লাটভিয়ান
language-name-mad = মাদুৰেছে
language-name-mag = মাগাহি
language-name-mai = মৈথিলী
language-name-mak = মাকাছাৰ
language-name-mas = মাছাই
language-name-mdf = মোক্সা
language-name-men = মেণ্ডে
language-name-mer = মেৰু
language-name-mfe = মৰিছিয়ান
language-name-mg = মালাগাছী
language-name-mgh = মাখুৱা-মিট্টো
language-name-mgo = মেটা
language-name-mh = মাৰ্চলিজ
language-name-mi = মাওৰি
language-name-mic = মিকমেক
language-name-min = মিনাংকাবাউ
language-name-mk = মেচিডোনীয়
language-name-ml = মালায়ালম
language-name-mn = মংগোলীয়
language-name-mni = মণিপুৰী
language-name-moh = মোহোক
language-name-mos = মোছি
language-name-mr = মাৰাঠী
language-name-ms = মালয়
language-name-mt = মাল্টিজ
language-name-mua = মুণ্ডাং
language-name-mul = একাধিক ভাষা
language-name-mus = ক্ৰীক
language-name-mwl = মিৰাণ্ডিজ
language-name-my = বাৰ্মীজ
language-name-myv = এৰজিয়া
language-name-mzn = মাজেন্দাৰানি
language-name-na = নাউৰু
language-name-nap = নিয়াপোলিটেন
language-name-naq = নামা
language-name-nb = নৰৱেজিয়ান বোকমাল
language-name-nd = উত্তৰ নিবেবেলে
language-name-ne = নেপালী
language-name-new = নেৱাৰি
language-name-ng = এন্দোঙ্গা
language-name-nia = নিয়াছ
language-name-niu = নিয়ুৱান
language-name-nl = ডাচ
language-name-nl_BE = ফ্লেমিচ
language-name-nmg = কোৱাছিঅ’
language-name-nn = নৰৱেজিয়ান নায়নোৰ্স্ক
language-name-nnh = নিয়েম্বোন
language-name-nog = নোগাই
language-name-nqo = এন্কো
language-name-nr = দক্ষিণ দেবেল
language-name-nso = উদীচ্য ছোথো
language-name-nus = নুয়েৰ
language-name-nv = নাভাজো
language-name-ny = ন্যাঞ্জা
language-name-nyn = ন্যানকোল
language-name-oc = অ’চিটান
language-name-om = ওৰোমো
language-name-or = ওড়িয়া
language-name-os = ওছেটিক
language-name-pa = পাঞ্জাবী
language-name-pag = পংগাছিনান
language-name-pam = পাম্পান্গা
language-name-pap = পাপিয়ামেণ্টো
language-name-pau = পালাউৱান
language-name-pcm = নাইজেৰিয়ান পিজিন
language-name-pl = প’লিচ
language-name-prg = প্ৰুছিয়ান
language-name-ps = পুস্ত
language-name-pt = পৰ্তুগীজ
language-name-pt_BR = ব্ৰাজিলিয়ান পৰ্তুগীজ
language-name-pt_PT = ইউৰোপীয়ান পৰ্তুগীজ
language-name-qu = কুৱেচুৱা
language-name-quc = কিচিয়ে
language-name-rap = ৰাপানুই
language-name-rar = ৰাৰোতোঙ্গন
language-name-rm = ৰোমানচ
language-name-rn = ৰুন্দি
language-name-ro = ৰোমানীয়
language-name-ro_MD = মোল্ডাভিয়ান
language-name-rof = ৰোম্বো
language-name-root = ৰুট
language-name-ru = ৰাছিয়ান
language-name-rup = আৰোমানীয়
language-name-rw = কিনয়াৰোৱাণ্ডা
language-name-rwk = ৰৱা
language-name-sa = সংস্কৃত
language-name-sad = ছান্দাৱে
language-name-sah = ছাখা
language-name-saq = ছাম্বুৰু
language-name-sat = চাওতালি
language-name-sba = নাংম্বে
language-name-sbp = ছাঙ্গু
language-name-sc = ছাৰ্ডিনিয়ান
language-name-scn = ছিচিলিয়ান
language-name-sco = স্কটছ
language-name-sd = সিন্ধি
language-name-se = উদীচ্য ছামি
language-name-seh = ছেনা
language-name-ses = কোইৰাবোৰো চেন্নি
language-name-sg = ছাঙ্গো
language-name-shi = তাচেলহিট
language-name-shn = চান
language-name-si = সিংহলা
language-name-sk = শ্লোভাক
language-name-sl = শ্লোভেনিয়ান
language-name-sm = ছামোন
language-name-sma = দাক্ষিণাত্য ছামি
language-name-smj = লুলে ছামি
language-name-smn = ইনাৰি ছামি
language-name-sms = স্কোল্ট ছামি
language-name-sn = চোনা
language-name-snk = ছোনিনকে
language-name-so = ছোমালি
language-name-sq = আলবেনীয়
language-name-sr = ছাৰ্বিয়ান
language-name-srn = স্ৰানান টোঙ্গো
language-name-ss = স্বাতি
language-name-ssy = ছাহো
language-name-st = দাক্ষিণাত্য ছোথো
language-name-su = ছুণ্ডানীজ
language-name-suk = ছুকুমা
language-name-sv = ছুইডিচ
language-name-sw = স্বাহিলি
language-name-sw_CD = কঙ্গো স্বাহিলি
language-name-swb = কোমোৰিয়ান
language-name-syr = চিৰিয়াক
language-name-ta = তামিল
language-name-te = তেলুগু
language-name-tem = টিম্নে
language-name-teo = তেছো
language-name-tet = তেতুম
language-name-tg = তাজিক
language-name-th = থাই
language-name-ti = টিগৰিনিয়া
language-name-tig = তাইগ্ৰে
language-name-tk = তুৰ্কমেন
language-name-tlh = ক্লিংগন
language-name-tn = ছোৱানা
language-name-to = টোঙ্গান
language-name-tpi = টোক পিছিন
language-name-tr = তুৰ্কী
language-name-trv = তাৰোকো
language-name-ts = ছোঙ্গা
language-name-tt = তাতাৰ
language-name-tum = তুম্বুকা
language-name-tvl = টুভালু
language-name-twq = টাছাৱাক
language-name-ty = তাহিতিয়ান
language-name-tyv = তুভিনিয়ান
language-name-tzm = চেণ্ট্ৰেল এটলাছ টামাজাইট
language-name-udm = উদমুৰ্ত
language-name-ug = উইঘুৰ
language-name-uk = ইউক্ৰেইনীয়
language-name-umb = উম্বুন্দু
language-name-und = অজ্ঞাত ভাষা
language-name-ur = উৰ্দু
language-name-uz = উজবেক
language-name-vai = ভাই
language-name-ve = ভেণ্ডা
language-name-vi = ভিয়েটনামী
language-name-vo = ভোলাপুক
language-name-vun = ভুঞ্জু
language-name-wa = ৱালুন
language-name-wae = ৱালছেৰ
language-name-wal = ওলেইটা
language-name-war = ৱাৰে
language-name-wo = ৱোলাফ
language-name-xal = কাল্মিক
language-name-xh = হোছা
language-name-xog = ছোগা
language-name-yav = য়াংবেন
language-name-ybb = য়েম্বা
language-name-yi = ইদ্দিছ
language-name-yo = ইউৰুবা
language-name-yue = কেণ্টোনীজ
language-name-zgh = ষ্টেণ্ডাৰ্ড মোৰোক্কান তামাজাইট
language-name-zh = চীনা
language-name-zh_Hans = সৰলীকৃত চীনা
language-name-zh_Hant = পৰম্পৰাগত চীনা
language-name-zu = ঝুলু
language-name-zun = ঝুনি
language-name-zxx = কোনো ভাষা সমল নাই
language-name-zza = ঝাঝা
