language-name-ace = acehnés
language-name-arp = arapaho
language-name-bas = basa
language-name-bax = bamun
language-name-bho = bhojpuri
language-name-bla = siksika
language-name-dum = neerlandés medieval
language-name-enm = inglés medieval
language-name-eu = euskera
language-name-frm = francés medieval
language-name-gmh = alemán de la alta edad media
language-name-grc = griego antiguo
language-name-kbd = kabardiano
language-name-krc = karachay-balkar
language-name-lo = lao
language-name-lus = lushai
language-name-mga = irlandés medieval
language-name-nr = ndebele meridional
language-name-nso = sotho septentrional
language-name-pa = punyabí
language-name-pcm = pcm
language-name-rn = kiroundi
language-name-shu = árabe chadiano
language-name-ss = siswati
language-name-st = sesotho meridional
language-name-sw = suajili
language-name-sw_CD = suajili del Congo
language-name-syr = siriaco
language-name-tet = tetún
language-name-tn = setswana
language-name-tyv = tuviniano
language-name-wo = wolof
language-name-wuu = wuu
language-name-xal = kalmyk
language-name-zgh = tamazight marroquí estándar
