language-name-aa = афарийн
language-name-ab = абхазхойн
language-name-ace = ачехийн
language-name-ada = адангме
language-name-ady = адигейн
language-name-af = африкаанс
language-name-agq = агхӀем
language-name-ain = айнийн
language-name-ak = акан
language-name-ale = алеутийн
language-name-alt = къилба алтайн
language-name-am = амхаройн
language-name-an = арагонойн
language-name-anp = ангика
language-name-ar = Ӏаьрбийн
language-name-ar_001 = ХӀинца болу стандартан Ӏаьрбийн
language-name-arn = арауканхойн
language-name-arp = арапахо
language-name-as = ассамийн
language-name-asa = асу
language-name-ast = астурийн
language-name-av = суьйлийн
language-name-awa = авадхи
language-name-ay = аймара
language-name-az = азербайджанийн
language-name-ba = башкирийн
language-name-ban = балийн
language-name-bas = баса
language-name-be = белорусийн
language-name-bem = бемба
language-name-bez = бена
language-name-bg = болгарийн
language-name-bgn = малхбузен-белуджийн
language-name-bho = бходжпури
language-name-bi = бислама
language-name-bin = бини
language-name-bla = сиксика
language-name-bm = бамбара
language-name-bn = бенгалийн
language-name-bo = тибетхойн
language-name-br = бретонийн
language-name-brx = бодо
language-name-bs = боснийн
language-name-bug = бугийн
language-name-byn = билийн
language-name-ca = каталонийн
language-name-ce = нохчийн
language-name-ceb = себуано
language-name-cgg = чига
language-name-ch = чаморро
language-name-chk = чукчийн
language-name-chm = марийн
language-name-cho = чоктавийн
language-name-chr = чероки
language-name-chy = шайенийн
language-name-ckb = юккъерчу курдийн
language-name-co = корсиканийн
language-name-crs = сейшелийн креолийн
language-name-cs = чехийн
language-name-cu = килсславянийн
language-name-cv = чувашийн
language-name-cy = валлийн
language-name-da = датхойн
language-name-dak = дакота
language-name-dar = даьргӀойн
language-name-dav = таита
language-name-de = немцойн
language-name-de_AT = австрин немцойн
language-name-de_CH = швейцарин литературин немцойн
language-name-dgr = догриб
language-name-dje = зарма
language-name-dsb = сорбийн
language-name-dua = дуала
language-name-dv = мальдивийн
language-name-dyo = дьола-фоньи
language-name-dz = дзонг-кэ
language-name-dzg = даза
language-name-ebu = эмбу
language-name-ee = эве
language-name-efi = эфик
language-name-eka = экаджук
language-name-el = грекийн
language-name-en = ингалсан
language-name-en_AU = Австралин ингалсан
language-name-en_CA = канадан ингалсан
language-name-en_GB = британин ингалсан
language-name-en_US = американ ингалсан
language-name-eo = эсперанто
language-name-es = испанхойн
language-name-es_419 = латинан американ испанхойн
language-name-es_ES = европан испанхойн
language-name-es_MX = мексикан испанхойн
language-name-et = эстонийн
language-name-eu = баскийн
language-name-ewo = эвондо
language-name-fa = гӀажарийн
language-name-ff = фулах
language-name-fi = финнийн
language-name-fil = филиппинийн
language-name-fj = фиджи
language-name-fo = фарерийн
language-name-fon = фон
language-name-fr = французийн
language-name-fr_CA = канадан французийн
language-name-fr_CH = швейцарин французийн
language-name-fur = фриулийн
language-name-fy = малхбузен-фризийн
language-name-ga = ирландхойн
language-name-gaa = га
language-name-gag = гагаузийн
language-name-gd = гэлийн
language-name-gez = геэз
language-name-gil = гильбертийн
language-name-gl = галисийн
language-name-gn = гуарани
language-name-gor = горонтало
language-name-gsw = швейцарин немцойн
language-name-gu = гуджарати
language-name-guz = гусии
language-name-gv = мэнийн
language-name-gwi = гвичин
language-name-ha = хауса
language-name-haw = гавайн
language-name-he = жугтийн
language-name-hi = хӀинди
language-name-hil = хилигайнон
language-name-hmn = хмонг
language-name-hr = хорватийн
language-name-hsb = лакхара сербийн
language-name-ht = гаитийн
language-name-hu = венгрийн
language-name-hup = хупа
language-name-hy = эрмалойн
language-name-hz = гереро
language-name-ia = интерлингва
language-name-iba = ибанийн
language-name-ibb = ибибио
language-name-id = индонезихойн
language-name-ig = игбо
language-name-ii = сычуань
language-name-ilo = илоко
language-name-inh = гӀалгӀайн
language-name-io = идо
language-name-is = исландхойн
language-name-it = итальянийн
language-name-iu = инуктитут
language-name-ja = японийн
language-name-jbo = ложбан
language-name-jgo = нгомба
language-name-jmc = мачаме
language-name-jv = яванийн
language-name-ka = гуьржийн
language-name-kab = кабилийн
language-name-kac = качинийн
language-name-kaj = каджи
language-name-kam = камба
language-name-kbd = гӀебартойн
language-name-kcg = тьяп
language-name-kde = маконде
language-name-kea = кабувердьяну
language-name-kfo = коро
language-name-kha = кхаси
language-name-khq = койра чиини
language-name-ki = кикуйю
language-name-kj = кунама
language-name-kk = кхазакхийн
language-name-kkj = како
language-name-kl = гренландхойн
language-name-kln = календжин
language-name-km = кхмерийн
language-name-kmb = кимбунду
language-name-kn = каннада
language-name-ko = корейн
language-name-koi = коми-пермякийн
language-name-kok = конкани
language-name-kpe = кпелле
language-name-kr = канури
language-name-krc = кхарачойн-балкхаройн
language-name-krl = карелийн
language-name-kru = курух
language-name-ks = кашмири
language-name-ksb = шамбала
language-name-ksf = бафиа
language-name-ksh = коьлнийн
language-name-ku = курдийн
language-name-kum = гӀумкийн
language-name-kv = комийн
language-name-kw = корнуоллийн
language-name-ky = гӀиргӀизойн
language-name-la = латинан
language-name-lad = ладино
language-name-lag = ланги
language-name-lb = люксембургхойн
language-name-lez = лаьзгийн
language-name-lg = ганда
language-name-li = лимбургийн
language-name-lkt = лакота
language-name-ln = лингала
language-name-lo = лаоссийн
language-name-loz = лози
language-name-lrc = къилбаседа лури
language-name-lt = литвахойн
language-name-lu = луба-катанга
language-name-lua = луба-лулуа
language-name-lun = лунда
language-name-lus = лушей
language-name-luy = лухья
language-name-lv = латышийн
language-name-mad = мадурийн
language-name-mag = магахи
language-name-mai = майтхили
language-name-mak = макасарийн
language-name-mas = масаи
language-name-mdf = мокшанойн
language-name-men = менде
language-name-mer = меру
language-name-mfe = маврикин креолийн
language-name-mg = малагасийн
language-name-mgh = макуа-меетто
language-name-mgo = мета
language-name-mh = маршаллийн
language-name-mi = маори
language-name-mic = микмак
language-name-min = минангкабау
language-name-mk = македонхойн
language-name-ml = малаялам
language-name-mn = монголийн
language-name-mni = манипурийн
language-name-moh = мохаук
language-name-mos = моси
language-name-mr = маратхи
language-name-ms = малайн
language-name-mt = мальтойн
language-name-mua = мунданг
language-name-mul = тайп-тайпа доьзалан меттанаш
language-name-mus = крик
language-name-mwl = мирандойн
language-name-my = бирманийн
language-name-myv = эрзянийн
language-name-mzn = мазандеранхойн
language-name-na = науру
language-name-nap = неаполитанойн
language-name-naq = нама
language-name-nb = норвегийн букмол
language-name-nd = къилбаседа ндебели
language-name-nds = лахара германхойн
language-name-nds_NL = лахара саксонийн
language-name-ne = непалхойн
language-name-new = неваройн
language-name-ng = ндонга
language-name-nia = ниас
language-name-niu = ниуэ
language-name-nl = голландхойн
language-name-nl_BE = фламандийн
language-name-nmg = квасио
language-name-nn = норвегийн нюнорск
language-name-nnh = нгиембунд
language-name-nog = ногӀийн
language-name-nqo = нко
language-name-nr = къилба ндебеле
language-name-nso = къилбаседа сото
language-name-nus = нуэр
language-name-nv = навахо
language-name-ny = ньянджа
language-name-nyn = ньянколе
language-name-oc = окситанойн
language-name-om = оромо
language-name-or = ори
language-name-os = хӀирийн
language-name-pa = панджаби
language-name-pag = пангасинан
language-name-pam = пампанга
language-name-pap = папьяменто
language-name-pau = палау
language-name-pcm = нигерийн-креолийн
language-name-pl = полякийн
language-name-prg = пруссийн
language-name-ps = пушту
language-name-pt = португалихойн
language-name-pt_BR = бразилин португалихойн
language-name-pt_PT = европан португалихойн
language-name-qu = кечуа
language-name-quc = киче
language-name-rap = рапануйн
language-name-rar = раротонга
language-name-rm = романшийн
language-name-rn = рунди
language-name-ro = румынийн
language-name-ro_MD = молдавийн
language-name-rof = ромбо
language-name-root = ораман мотт
language-name-ru = оьрсийн
language-name-rup = аруминийн
language-name-rw = киньяруанда
language-name-rwk = руанда
language-name-sa = санскрит
language-name-sad = сандаве
language-name-sah = якутийн
language-name-saq = самбуру
language-name-sat = сантали
language-name-sba = нгамбайн
language-name-sbp = сангу
language-name-sc = сардинийн
language-name-scn = сицилийн
language-name-sco = шотландхойн
language-name-sd = синдхи
language-name-se = къилбаседа саамийн
language-name-seh = сена
language-name-ses = койраборо сенни
language-name-sg = санго
language-name-shi = тахелхит
language-name-shn = шанойн
language-name-si = сингалхойн
language-name-sk = словакийн
language-name-sl = словенийн
language-name-sm = самоанойн
language-name-smj = луле-саамийн
language-name-smn = инари-саамийн
language-name-sms = скольт-саамийн
language-name-sn = шона
language-name-snk = сонинке
language-name-so = сомали
language-name-sq = албанойн
language-name-sr = сербийн
language-name-srn = сранан-тонго
language-name-ss = свази
language-name-ssy = сахо
language-name-st = къилба сото
language-name-su = сунданхойн
language-name-suk = сукума
language-name-sv = шведийн
language-name-sw = суахили
language-name-swb = коморийн
language-name-syr = шемахойн
language-name-ta = тамилхойн
language-name-te = телугу
language-name-tem = темне
language-name-teo = тесо
language-name-tet = тетум
language-name-tg = таджикийн
language-name-th = тайн
language-name-ti = тигринья
language-name-tig = тигре
language-name-tk = туркменийн
language-name-tlh = клингонин
language-name-tn = тсвана
language-name-to = тонганийн
language-name-tpi = ток-писин
language-name-tr = туркойн
language-name-trv = седекойн
language-name-ts = тсонга
language-name-tt = гӀезалойн
language-name-tum = тумбука
language-name-tvl = тувалу
language-name-twq = тасавак
language-name-ty = таитянойн
language-name-tyv = тувинийн
language-name-tzm = тамазигхтийн
language-name-udm = удмуртийн
language-name-ug = уйгурийн
language-name-uk = украинийн
language-name-umb = умбунду
language-name-und = боьвзуш боцу мотт
language-name-ur = урду
language-name-uz = узбекийн
language-name-vai = ваи
language-name-ve = венда
language-name-vi = вьетнамхойн
language-name-vo = волапюк
language-name-vun = вунджо
language-name-wa = валлонойн
language-name-wae = валлисийн
language-name-wal = воламо
language-name-war = варай
language-name-wbp = варлпири
language-name-wo = волоф
language-name-xal = гӀалмакхойн
language-name-xh = коса
language-name-xog = сога
language-name-yav = янгбен
language-name-ybb = йемба
language-name-yi = идиш
language-name-yo = йоруба
language-name-yue = кантонийн
language-name-zgh = мороккон стандартан тамазигхтийн
language-name-zh = цийн
language-name-zh_Hans = атта цийн
language-name-zh_Hant = ламастан цийн
language-name-zu = зулу
language-name-zun = зуньи
language-name-zxx = меттан чулацам боцуш
language-name-zza = заза
