language-name-aa = afar
language-name-ab = abcazian
language-name-ae = avestan
language-name-af = afrikaans
language-name-am = amaric
language-name-an = aragonês
language-name-ang = vieri inglês
language-name-ar = arap
language-name-arc = aramaic
language-name-as = assamês
language-name-ast = asturian
language-name-av = avar
language-name-ay = aymarà
language-name-az = azerbaijani
language-name-be = bielorùs
language-name-bg = bulgar
language-name-bn = bengalês
language-name-bo = tibetan
language-name-br = breton
language-name-bs = bosniac
language-name-ca = catalan
language-name-ce = cecen
language-name-ch = chamorro
language-name-co = cors
language-name-cop = coptic
language-name-cr = cree
language-name-cs = cec
language-name-cu = sclâf de glesie
language-name-cy = galês
language-name-da = danês
language-name-de = todesc
language-name-de_AT = todesc de Austrie
language-name-de_CH = alt todesc de Svuizare
language-name-den = sclâf
language-name-egy = vieri egjizian
language-name-el = grêc
language-name-en = inglês
language-name-en_AU = inglês australian
language-name-en_CA = inglês canadês
language-name-en_GB = inglês britanic
language-name-en_US = ingles merecan
language-name-eo = esperanto
language-name-es = spagnûl
language-name-es_419 = spagnûl de Americhe Latine
language-name-es_ES = spagnûl iberic
language-name-et = eston
language-name-eu = basc
language-name-fa = persian
language-name-ff = fulah
language-name-fi = finlandês
language-name-fil = filipin
language-name-fj = fizian
language-name-fo = faroês
language-name-fr = francês
language-name-fr_CA = francês dal Canade
language-name-fr_CH = francês de Svuizare
language-name-fro = vieri francês
language-name-fur = furlan
language-name-fy = frisian
language-name-ga = gaelic irlandês
language-name-gd = gaelic scozês
language-name-gl = galizian
language-name-gn = guaranì
language-name-got = gotic
language-name-grc = vieri grêc
language-name-gu = gujarati
language-name-gv = manx
language-name-he = ebraic
language-name-hi = hindi
language-name-hr = cravuat
language-name-ht = haitian
language-name-hu = ongjarês
language-name-hy = armen
language-name-id = indonesian
language-name-ig = igbo
language-name-ik = inupiaq
language-name-io = ido
language-name-is = islandês
language-name-it = talian
language-name-iu = inuktitut
language-name-ja = gjaponês
language-name-ka = gjeorgjian
language-name-kk = kazac
language-name-kl = kalaallisut
language-name-km = khmer
language-name-kn = kannada
language-name-ko = corean
language-name-ku = curd
language-name-kw = cornualiês
language-name-la = latin
language-name-lad = ladin
language-name-lb = lussemburghês
language-name-li = limburghês
language-name-ln = lingala
language-name-lo = lao
language-name-lt = lituan
language-name-lv = leton
language-name-mg = malagasy
language-name-mi = maori
language-name-mk = macedon
language-name-ml = malayalam
language-name-mn = mongul
language-name-mr = marathi
language-name-ms = malês
language-name-mt = maltês
language-name-mul = lenghis multiplis
language-name-mwl = mirandês
language-name-nap = napoletan
language-name-nb = norvegjês bokmål
language-name-nd = ndebele setentrionâl
language-name-nds = bas todesc
language-name-ne = nepalês
language-name-nl = olandês
language-name-nl_BE = flamant
language-name-nn = norvegjês nynorsk
language-name-no = norvegjês
language-name-non = vieri norvegjês
language-name-nso = sotho setentrionâl
language-name-nv = navajo
language-name-oc = ocitan
language-name-or = oriya
language-name-os = osetic
language-name-ota = turc otoman
language-name-pa = punjabi
language-name-pap = papiamento
language-name-peo = vieri persian
language-name-pl = polac
language-name-pro = vieri provenzâl
language-name-ps = pashto
language-name-pt = portughês
language-name-pt_BR = portughês brasilian
language-name-pt_PT = portughês iberic
language-name-qu = quechua
language-name-rm = rumanç
language-name-ro = romen
language-name-ro_MD = moldâf
language-name-ru = rus
language-name-sa = sanscrit
language-name-sc = sardegnûl
language-name-scn = sicilian
language-name-sco = scozês
language-name-sd = sindhi
language-name-se = sami setentrionâl
language-name-sg = sango
language-name-sga = vieri irlandês
language-name-si = sinalês
language-name-sk = slovac
language-name-sl = sloven
language-name-sm = samoan
language-name-so = somal
language-name-sq = albanês
language-name-sr = serp
language-name-ss = swati
language-name-st = sotho meridionâl
language-name-su = sundanês
language-name-sux = sumeric
language-name-sv = svedês
language-name-sw = swahili
language-name-ta = tamil
language-name-te = telegu
language-name-tet = tetum
language-name-tg = tagic
language-name-th = thai
language-name-tk = turcmen
language-name-tl = tagalog
language-name-tr = turc
language-name-tt = tartar
language-name-ty = tahitian
language-name-ug = uigur
language-name-uk = ucrain
language-name-und = indeterminade
language-name-ur = urdu
language-name-uz = uzbec
language-name-ve = venda
language-name-vi = vietnamite
language-name-wa = valon
language-name-wo = wolof
language-name-xh = xhosa
language-name-yi = yiddish
language-name-yo = yoruba
language-name-zh = cinês
language-name-zh_Hans = cinês semplificât
language-name-zh_Hant = cinês tradizionâl
language-name-zu = zulu
