language-name-ak = Akan
language-name-am = Amarik
language-name-ar = Arabik
language-name-be = Belarus kasa
language-name-bg = Bɔlgeria kasa
language-name-bn = Bengali kasa
language-name-cs = Kyɛk kasa
language-name-de = Gyaaman
language-name-el = Greek kasa
language-name-en = Borɔfo
language-name-es = Spain kasa
language-name-fa = Pɛɛhyia kasa
language-name-fr = Frɛnkye
language-name-ha = Hausa
language-name-hi = Hindi
language-name-hu = Hangri kasa
language-name-id = Indonihyia kasa
language-name-ig = Igbo
language-name-it = Italy kasa
language-name-ja = Gyapan kasa
language-name-jv = Gyabanis kasa
language-name-km = Kambodia kasa
language-name-ko = Korea kasa
language-name-ms = Malay kasa
language-name-my = Bɛɛmis kasa
language-name-ne = Nɛpal kasa
language-name-nl = Dɛɛkye
language-name-pa = Pungyabi kasa
language-name-pl = Pɔland kasa
language-name-pt = Pɔɔtugal kasa
language-name-ro = Romenia kasa
language-name-ru = Rahyia kasa
language-name-rw = Rewanda kasa
language-name-so = Somalia kasa
language-name-sv = Sweden kasa
language-name-ta = Tamil kasa
language-name-th = Taeland kasa
language-name-tr = Tɛɛki kasa
language-name-uk = Ukren kasa
language-name-ur = Urdu kasa
language-name-vi = Viɛtnam kasa
language-name-yo = Yoruba
language-name-zh = Kyaena kasa
language-name-zu = Zulu
