language-name-aa = אפארית
language-name-ab = אבחזית
language-name-ace = אכינזית
language-name-ach = אקצ׳ולי
language-name-ada = אדנמה
language-name-ady = אדיגית
language-name-ae = אבסטן
language-name-af = אפריקאנס
language-name-afh = אפריהילי
language-name-agq = אע׳ם
language-name-ain = אינו
language-name-ak = אקאן
language-name-akk = אכדית
language-name-ale = אלאוט
language-name-alt = אלטאי דרומית
language-name-am = אמהרית
language-name-an = אראגונית
language-name-ang = אנגלית עתיקה
language-name-anp = אנג׳יקה
language-name-ar = ערבית
language-name-ar_001 = ערבית ספרותית
language-name-arc = ארמית
language-name-arn = אראוקנית
language-name-arp = אראפהו
language-name-ars = ערבית - נג׳ד
language-name-arw = ארוואק
language-name-as = אסאמית
language-name-asa = אסו
language-name-ast = אסטורית
language-name-av = אווארית
language-name-awa = אוואדית
language-name-ay = איימארית
language-name-az = אזרית
language-name-ba = בשקירית
language-name-bal = באלוצ׳י
language-name-ban = בלינזית
language-name-bar = בווארית
language-name-bas = בסאא
language-name-bax = במום
language-name-bbj = גומאלה
language-name-be = בלארוסית
language-name-bej = בז׳ה
language-name-bem = במבה
language-name-bez = בנה
language-name-bfd = באפוט
language-name-bg = בולגרית
language-name-bgn = באלוצ׳י מערבית
language-name-bho = בוג׳פורי
language-name-bi = ביסלמה
language-name-bik = ביקול
language-name-bin = ביני
language-name-bkm = קום
language-name-bla = סיקסיקה
language-name-bm = במבארה
language-name-bn = בנגלית
language-name-bo = טיבטית
language-name-br = ברטונית
language-name-bra = בראג׳
language-name-brx = בודו
language-name-bs = בוסנית
language-name-bss = אקוסה
language-name-bua = בוריאט
language-name-bug = בוגינזית
language-name-bum = בולו
language-name-byn = בלין
language-name-byv = מדומבה
language-name-ca = קטלאנית
language-name-cad = קאדו
language-name-car = קאריב
language-name-cay = קאיוגה
language-name-cch = אטסם
language-name-ce = צ׳צ׳נית
language-name-ceb = סבואנו
language-name-cgg = צ׳יגה
language-name-ch = צ׳מורו
language-name-chb = צ׳יבצ׳ה
language-name-chg = צ׳אגאטאי
language-name-chk = צ׳וקסה
language-name-chm = מארי
language-name-chn = ניב צ׳ינוק
language-name-cho = צ׳וקטאו
language-name-chp = צ׳יפוויאן
language-name-chr = צ׳רוקי
language-name-chy = שאיין
language-name-ckb = כורדית סוראנית
language-name-co = קורסיקנית
language-name-cop = קופטית
language-name-cr = קרי
language-name-crh = טטרית של קרים
language-name-cs = צ׳כית
language-name-csb = קשובית
language-name-cu = סלאבית כנסייתית עתיקה
language-name-cv = צ׳ובאש
language-name-cy = וולשית
language-name-da = דנית
language-name-dak = דקוטה
language-name-dar = דרגווה
language-name-dav = טאיטה
language-name-de = גרמנית
language-name-del = דלאוור
language-name-den = סלאבית
language-name-dgr = דוגריב
language-name-din = דינקה
language-name-dje = זארמה
language-name-doi = דוגרי
language-name-dsb = סורבית תחתית
language-name-dua = דואלה
language-name-dum = הולנדית תיכונה
language-name-dv = דיבהי
language-name-dyo = ג׳ולה פונית
language-name-dyu = דיולה
language-name-dz = דזונקה
language-name-dzg = דזאנגה
language-name-ebu = אמבו
language-name-ee = אווה
language-name-efi = אפיק
language-name-egy = מצרית עתיקה
language-name-eka = אקיוק
language-name-el = יוונית
language-name-elx = עילמית
language-name-en = אנגלית
language-name-enm = אנגלית תיכונה
language-name-eo = אספרנטו
language-name-es = ספרדית
language-name-et = אסטונית
language-name-eu = בסקית
language-name-ewo = אוונדו
language-name-fa = פרסית
language-name-fan = פנג
language-name-fat = פאנטי
language-name-ff = פולה
language-name-fi = פינית
language-name-fil = פיליפינית
language-name-fj = פיג׳ית
language-name-fo = פארואזית
language-name-fon = פון
language-name-fr = צרפתית
language-name-frc = צרפתית קייג׳ונית
language-name-frm = צרפתית תיכונה
language-name-fro = צרפתית עתיקה
language-name-frr = פריזית צפונית
language-name-frs = פריזית מזרחית
language-name-fur = פריולית
language-name-fy = פריזית מערבית
language-name-ga = אירית
language-name-gaa = גא
language-name-gag = גגאוזית
language-name-gan = סינית גאן
language-name-gay = גאיו
language-name-gba = גבאיה
language-name-gd = גאלית סקוטית
language-name-gez = געז
language-name-gil = קיריבטית
language-name-gl = גליציאנית
language-name-gmh = גרמנית בינונית-גבוהה
language-name-gn = גוארני
language-name-goh = גרמנית עתיקה גבוהה
language-name-gon = גונדי
language-name-gor = גורונטאלו
language-name-got = גותית
language-name-grb = גרבו
language-name-grc = יוונית עתיקה
language-name-gsw = גרמנית שוויצרית
language-name-gu = גוג׳ארטי
language-name-guz = גוסי
language-name-gv = מאנית
language-name-gwi = גוויצ׳ן
language-name-ha = האוסה
language-name-hai = האידה
language-name-hak = סינית האקה
language-name-haw = הוואית
language-name-he = עברית
language-name-hi = הינדי
language-name-hil = היליגאינון
language-name-hit = חתית
language-name-hmn = המונג
language-name-ho = הירי מוטו
language-name-hr = קרואטית
language-name-hsb = סורבית גבוהה
language-name-hsn = סינית שיאנג
language-name-hu = הונגרית
language-name-hup = הופה
language-name-hy = ארמנית
language-name-hz = הררו
language-name-ia = ‏אינטרלינגואה
language-name-iba = איבאן
language-name-ibb = איביביו
language-name-id = אינדונזית
language-name-ie = אינטרלינגה
language-name-ig = איגבו
language-name-ii = סצ׳ואן יי
language-name-ik = אינופיאק
language-name-ilo = אילוקו
language-name-inh = אינגושית
language-name-io = אידו
language-name-is = איסלנדית
language-name-it = איטלקית
language-name-iu = אינוקטיטוט
language-name-ja = יפנית
language-name-jbo = לוז׳באן
language-name-jgo = נגומבה
language-name-jmc = מאקאמה
language-name-jpr = פרסית יהודית
language-name-jrb = ערבית יהודית
language-name-jv = יאוואית
language-name-ka = גאורגית
language-name-kaa = קארא-קלפאק
language-name-kab = קבילה
language-name-kac = קצ׳ין
language-name-kaj = ג׳ו
language-name-kam = קמבה
language-name-kaw = קאווי
language-name-kbd = קברדית
language-name-kbl = קנמבו
language-name-kcg = טיאפ
language-name-kde = מקונדה
language-name-kea = קאבוורדיאנו
language-name-kfo = קורו
language-name-kg = קונגו
language-name-kha = קהאסי
language-name-kho = קוטאנזית
language-name-khq = קוירה צ׳יני
language-name-ki = קיקויו
language-name-kj = קואניאמה
language-name-kk = קזחית
language-name-kkj = קאקו
language-name-kl = גרינלנדית
language-name-kln = קלנג׳ין
language-name-km = חמרית
language-name-kmb = קימבונדו
language-name-kn = קנאדה
language-name-ko = קוריאנית
language-name-koi = קומי-פרמיאקית
language-name-kok = קונקאני
language-name-kos = קוסראיאן
language-name-kpe = קפלה
language-name-kr = קאנורי
language-name-krc = קראצ׳י-בלקר
language-name-krl = קארלית
language-name-kru = קורוק
language-name-ks = קשמירית
language-name-ksb = שמבאלה
language-name-ksf = באפיה
language-name-ksh = קולוניאן
language-name-ku = כורדית
language-name-kum = קומיקית
language-name-kut = קוטנאי
language-name-kv = קומי
language-name-kw = קורנית
language-name-ky = קירגיזית
language-name-la = לטינית
language-name-lad = לדינו
language-name-lag = לאנגי
language-name-lah = לנדה
language-name-lam = למבה
language-name-lb = לוקסמבורגית
language-name-lez = לזגית
language-name-lg = גאנדה
language-name-li = לימבורגית
language-name-lkt = לקוטה
language-name-ln = לינגלה
language-name-lo = לאו
language-name-lol = מונגו
language-name-lou = קריאולית לואיזיאנית
language-name-loz = לוזית
language-name-lrc = לורית צפונית
language-name-lt = ליטאית
language-name-lu = לובה-קטנגה
language-name-lua = לובה-לולואה
language-name-lui = לויסנו
language-name-lun = לונדה
language-name-luo = לואו
language-name-lus = מיזו
language-name-luy = לויה
language-name-lv = לטבית
language-name-mad = מדורזית
language-name-maf = מאפאה
language-name-mag = מאגאהית
language-name-mai = מאיטילית
language-name-mak = מקסאר
language-name-man = מנדינגו
language-name-mas = מסאית
language-name-mde = מאבא
language-name-mdf = מוקשה
language-name-mdr = מנדאר
language-name-men = מנדה
language-name-mer = מרו
language-name-mfe = קריאולית מאוריציאנית
language-name-mg = מלגשית
language-name-mga = אירית תיכונה
language-name-mgh = מאקוואה מטו
language-name-mgo = מטא
language-name-mh = מרשלית
language-name-mi = מאורית
language-name-mic = מיקמק
language-name-min = מיננגקבאו
language-name-mk = מקדונית
language-name-ml = מליאלאם
language-name-mn = מונגולית
language-name-mnc = מנצ׳ו
language-name-mni = מניפורית
language-name-moh = מוהוק
language-name-mos = מוסי
language-name-mr = מראטהי
language-name-ms = מלאית
language-name-mt = מלטית
language-name-mua = מונדאנג
language-name-mul = מספר שפות
language-name-mus = קריק
language-name-mwl = מירנדזית
language-name-mwr = מרווארי
language-name-my = בורמזית
language-name-mye = מאיין
language-name-myv = ארזיה
language-name-mzn = מאזאנדראני
language-name-na = נאורית
language-name-nan = סינית מין נאן
language-name-nap = נפוליטנית
language-name-naq = נאמה
language-name-nb = נורווגית ספרותית
language-name-nd = נדבלה צפונית
language-name-nds = גרמנית תחתית
language-name-nds_NL = סקסונית תחתית
language-name-ne = נפאלית
language-name-new = נווארי
language-name-ng = נדונגה
language-name-nia = ניאס
language-name-niu = ניואן
language-name-nl = הולנדית
language-name-nl_BE = פלמית
language-name-nmg = קוואסיו
language-name-nn = נורווגית חדשה
language-name-nnh = נגיאמבון
language-name-no = נורווגית
language-name-nog = נוגאי
language-name-non = ‏נורדית עתיקה
language-name-nqo = נ׳קו
language-name-nr = נדבלה דרומית
language-name-nso = סותו צפונית
language-name-nus = נואר
language-name-nv = נאוואחו
language-name-nwc = נווארית קלאסית
language-name-ny = ניאנג׳ה
language-name-nym = ניאמווזי
language-name-nyn = ניאנקולה
language-name-nyo = ניורו
language-name-nzi = נזימה
language-name-oc = אוקסיטנית
language-name-oj = אוג׳יבווה
language-name-om = אורומו
language-name-or = אורייה
language-name-os = אוסטית
language-name-osa = אוסג׳
language-name-ota = טורקית עות׳מנית
language-name-pa = פנג׳אבי
language-name-pag = פנגסינאן
language-name-pal = פלאבי
language-name-pam = פמפאניה
language-name-pap = פפיאמנטו
language-name-pau = פלוואן
language-name-pcm = ניגרית פידג׳ית
language-name-peo = פרסית עתיקה
language-name-phn = פיניקית
language-name-pi = פאלי
language-name-pl = פולנית
language-name-pon = פונפיאן
language-name-prg = פרוסית
language-name-pro = פרובנסאל עתיקה
language-name-ps = פאשטו
language-name-pt = פורטוגזית
language-name-qu = קצ׳ואה
language-name-quc = קיצ׳ה
language-name-raj = ראג׳סטאני
language-name-rap = רפאנוי
language-name-rar = ררוטונגאן
language-name-rm = רומאנש
language-name-rn = קירונדי
language-name-ro = רומנית
language-name-ro_MD = מולדבית
language-name-rof = רומבו
language-name-rom = רומאני
language-name-root = רוט
language-name-ru = רוסית
language-name-rup = ארומנית
language-name-rw = קנירואנדית
language-name-rwk = ראווה
language-name-sa = סנסקריט
language-name-sad = סנדאווה
language-name-sah = סאחה
language-name-sam = ארמית שומרונית
language-name-saq = סמבורו
language-name-sas = סאסק
language-name-sat = סאנטאלי
language-name-sba = נגמבאי
language-name-sbp = סאנגו
language-name-sc = סרדינית
language-name-scn = סיציליאנית
language-name-sco = סקוטית
language-name-sd = סינדהית
language-name-sdh = כורדית דרומית
language-name-se = סמי צפונית
language-name-see = סנקה
language-name-seh = סנה
language-name-sel = סלקופ
language-name-ses = קויראבורו סני
language-name-sg = סנגו
language-name-sga = אירית עתיקה
language-name-sh = סרבו-קרואטית
language-name-shi = שילה
language-name-shn = שאן
language-name-shu = ערבית צ׳אדית
language-name-si = סינהלה
language-name-sid = סידאמו
language-name-sk = סלובקית
language-name-sl = סלובנית
language-name-sm = סמואית
language-name-sma = סאמי דרומית
language-name-smj = לולה סאמי
language-name-smn = אינארי סאמי
language-name-sms = סקולט סאמי
language-name-sn = שונה
language-name-snk = סונינקה
language-name-so = סומלית
language-name-sog = סוגדיאן
language-name-sq = אלבנית
language-name-sr = סרבית
language-name-srn = סרנאן טונגו
language-name-srr = סרר
language-name-ss = סאווזי
language-name-ssy = סאהו
language-name-st = סותו דרומית
language-name-su = סונדנזית
language-name-suk = סוקומה
language-name-sus = סוסו
language-name-sux = שומרית
language-name-sv = שוודית
language-name-sw = סווהילי
language-name-sw_CD = סווהילי קונגו
language-name-swb = קומורית
language-name-syc = סירית קלאסית
language-name-syr = סורית
language-name-ta = טמילית
language-name-te = טלוגו
language-name-tem = טימנה
language-name-teo = טסו
language-name-ter = טרנו
language-name-tet = טטום
language-name-tg = טג׳יקית
language-name-th = תאית
language-name-ti = תיגרינית
language-name-tig = טיגרית
language-name-tiv = טיב
language-name-tk = טורקמנית
language-name-tkl = טוקלאו
language-name-tl = טאגאלוג
language-name-tlh = קלינגון
language-name-tli = טלינגיט
language-name-tmh = טמאשק
language-name-tn = סוואנה
language-name-to = טונגאית
language-name-tog = ניאסה טונגה
language-name-tpi = טוק פיסין
language-name-tr = טורקית
language-name-trv = טרוקו
language-name-ts = טסונגה
language-name-tsi = טסימשיאן
language-name-tt = טטרית
language-name-tum = טומבוקה
language-name-tvl = טובאלו
language-name-tw = טווי
language-name-twq = טסוואק
language-name-ty = טהיטית
language-name-tyv = טובינית
language-name-tzm = תמאזיגת של מרכז מרוקו
language-name-udm = אודמורט
language-name-ug = אויגור
language-name-uga = אוגריתית
language-name-uk = אוקראינית
language-name-umb = אומבונדו
language-name-und = שפה לא ידועה
language-name-ur = אורדו
language-name-uz = אוזבקית
language-name-vai = וואי
language-name-ve = וונדה
language-name-vi = ויאטנמית
language-name-vo = ‏וולאפיק
language-name-vot = ווטיק
language-name-vun = וונג׳ו
language-name-wa = ולונית
language-name-wae = וואלסר
language-name-wal = ווליאטה
language-name-war = ווראי
language-name-was = וואשו
language-name-wbp = וורלפירי
language-name-wo = וולוף
language-name-wuu = סינית וו
language-name-xal = קלמיקית
language-name-xh = קוסה
language-name-xog = סוגה
language-name-yao = יאו
language-name-yap = יאפזית
language-name-yav = יאנגבן
language-name-ybb = ימבה
language-name-yi = יידיש
language-name-yo = יורובה
language-name-yue = קנטונזית
language-name-za = זואנג
language-name-zap = זאפוטק
language-name-zbl = בליסימבולס
language-name-zen = זנאגה
language-name-zgh = תמזיע׳ת מרוקאית תקנית
language-name-zh = סינית
language-name-zh_Hans = סינית פשוטה
language-name-zh_Hant = סינית מסורתית
language-name-zu = זולו
language-name-zun = זוני
language-name-zxx = ללא תוכן לשוני
language-name-zza = זאזא
