language-name-aa = Afáiris
language-name-ab = Abcáisis
language-name-ace = ace
language-name-ada = ada
language-name-ady = Adaigéis
language-name-ae = Aivéistis
language-name-af = Afracáinis
language-name-agq = agq
language-name-ain = Aidhniúis
language-name-ak = Acáinis
language-name-akk = Acáidis
language-name-ale = ale
language-name-alt = alt
language-name-am = Amáiris
language-name-an = Aragóinis
language-name-ang = Sean-Bhéarla
language-name-anp = anp
language-name-ar = Araibis
language-name-ar_001 = Araibis Chaighdeánach
language-name-arc = Aramais
language-name-arn = Mapúitsis
language-name-arp = arp
language-name-as = Asaimis
language-name-asa = asa
language-name-ast = Astúiris
language-name-av = Aváiris
language-name-awa = awa
language-name-ay = Aidhmiris
language-name-az = Asarbaiseáinis
language-name-ba = Baiscíris
language-name-ban = Bailís
language-name-bar = Baváiris
language-name-bas = bas
language-name-be = Bealarúisis
language-name-bem = Beimbis
language-name-bez = bez
language-name-bg = Bulgáiris
language-name-bho = bho
language-name-bi = Bioslaimis
language-name-bin = bin
language-name-bla = bla
language-name-bm = bm
language-name-bn = Beangáilis
language-name-bo = Tibéidis
language-name-br = Briotáinis
language-name-brx = brx
language-name-bs = Boisnis
language-name-bua = Buiriáitis
language-name-bug = Buiginis
language-name-byn = byn
language-name-ca = Catalóinis
language-name-ce = Seisnis
language-name-ceb = Seabúáinis
language-name-cgg = cgg
language-name-ch = Seamóiris
language-name-chk = chk
language-name-chm = Mairis
language-name-cho = cho
language-name-chr = Seiricis
language-name-chy = chy
language-name-ckb = Coirdis Lárnach
language-name-co = Corsaicis
language-name-cop = Coptais
language-name-cr = Craís
language-name-crs = Criól Fraincise Seselwa
language-name-cs = Seicis
language-name-csb = Caisiúibis
language-name-cu = Slavais na hEaglaise
language-name-cv = Suvaisis
language-name-cy = Breatnais
language-name-da = Danmhairgis
language-name-dak = dak
language-name-dar = dar
language-name-dav = Taita
language-name-de = Gearmáinis
language-name-de_AT = Gearmáinis Ostarach
language-name-de_CH = Ard-Ghearmáinis Eilvéiseach
language-name-dgr = dgr
language-name-dje = Zarmais
language-name-dsb = Sorbais Íochtarach
language-name-dua = dua
language-name-dum = Meán-Ollainnis
language-name-dv = Divéihis
language-name-dyo = dyo
language-name-dz = Seoinicis
language-name-dzg = dzg
language-name-ebu = ebu
language-name-ee = ee
language-name-efi = efi
language-name-egy = Sean-Éigiptis
language-name-eka = eka
language-name-el = Gréigis
language-name-en = Béarla
language-name-en_AU = Béarla Astrálach
language-name-en_CA = Béarla Ceanadach
language-name-en_GB = Béarla Briotanach
language-name-en_US = Béarla Meiriceánach
language-name-enm = Meán-Bhéarla
language-name-eo = Esperanto
language-name-es = Spáinnis
language-name-es_419 = Spáinnis Mheiriceá Laidinigh
language-name-es_ES = Spáinnis Eorpach
language-name-es_MX = Spáinnis Mheicsiceach
language-name-et = Eastóinis
language-name-eu = Bascais
language-name-ewo = ewo
language-name-fa = Peirsis
language-name-ff = Fuláinis
language-name-fi = Fionlainnis
language-name-fil = Filipínis
language-name-fj = Fidsis
language-name-fo = Faróis
language-name-fon = fon
language-name-fr = Fraincis
language-name-fr_CA = Fraincis Cheanadach
language-name-fr_CH = Fraincis Eilvéiseach
language-name-frm = Meán-Fhraincis
language-name-fro = Sean-Fhraincis
language-name-frr = Freaslainnis an Tuaiscirt
language-name-fur = Friúilis
language-name-fy = Freaslainnis Iartharach
language-name-ga = Gaeilge
language-name-gaa = gaa
language-name-gan = Sínis Gan
language-name-gd = Gaeilge na hAlban
language-name-gez = Aetóipis
language-name-gil = Cireabaitis
language-name-gl = Gailísis
language-name-gmh = Meán-Ard-Ghearmáinis
language-name-gn = Guaráinis
language-name-goh = Sean-Ard-Ghearmáinis
language-name-gor = gor
language-name-grc = Sean-Ghréigis
language-name-gsw = Gearmáinis Eilvéiseach
language-name-gu = Gúisearáitis
language-name-guc = Uaúis
language-name-guz = guz
language-name-gv = Manainnis
language-name-gwi = gwi
language-name-ha = Hásais
language-name-hak = Haicéis
language-name-haw = Haváis
language-name-he = Eabhrais
language-name-hi = Hiondúis
language-name-hif = Hiondúis Fhidsí
language-name-hil = Hilgeanóinis
language-name-hit = Hitis
language-name-hmn = Mongais
language-name-ho = Motúis Hírí
language-name-hr = Cróitis
language-name-hsb = Sorbais Uachtarach
language-name-hsn = Sínis Xiang
language-name-ht = Criól Háítíoch
language-name-hu = Ungáiris
language-name-hup = Húipis
language-name-hy = Airméinis
language-name-hz = Heiréiris
language-name-ia = Interlingua
language-name-iba = iba
language-name-ibb = Ibibis
language-name-id = Indinéisis
language-name-ie = Interlingue
language-name-ig = Íogbóis
language-name-ii = ii
language-name-ik = Iniúipiaicis
language-name-ilo = ilo
language-name-inh = Iongúis
language-name-io = Ido
language-name-is = Íoslainnis
language-name-it = Iodáilis
language-name-iu = Ionúitis
language-name-ja = Seapáinis
language-name-jbo = Lojban
language-name-jgo = jgo
language-name-jmc = jmc
language-name-jut = Iútlainnis
language-name-jv = Iáivis
language-name-ka = Seoirsis
language-name-kaa = Cara-Chalpáis
language-name-kab = kab
language-name-kac = kac
language-name-kaj = kaj
language-name-kam = kam
language-name-kbd = kbd
language-name-kcg = kcg
language-name-kde = kde
language-name-kea = Kabuverdianu
language-name-kfo = kfo
language-name-kg = Congóis
language-name-kha = kha
language-name-khq = khq
language-name-ki = Ciocúis
language-name-kj = Cuainiáimis
language-name-kk = Casaicis
language-name-kkj = kkj
language-name-kl = Kalaallisut
language-name-kln = kln
language-name-km = Ciméiris
language-name-kmb = kmb
language-name-kn = Cannadais
language-name-ko = Cóiréis
language-name-kok = Concáinis
language-name-kpe = kpe
language-name-kr = Canúiris
language-name-krc = krc
language-name-krl = Cairéilis
language-name-kru = Curúicis
language-name-ks = Caismíris
language-name-ksb = ksb
language-name-ksf = ksf
language-name-ksh = ksh
language-name-ku = Coirdis
language-name-kum = kum
language-name-kv = Coimis
language-name-kw = Coirnis
language-name-ky = Cirgisis
language-name-la = Laidin
language-name-lad = Laidínis
language-name-lag = lag
language-name-lah = Puinseáibis Iartharach
language-name-lb = Lucsambuirgis
language-name-lez = lez
language-name-lg = Lugandais
language-name-li = Liombuirgis
language-name-lij = Liogúiris
language-name-liv = Liovóinis
language-name-lkt = lkt
language-name-lmo = Lombairdis
language-name-ln = Liongáilis
language-name-lo = Laoisis
language-name-loz = loz
language-name-lrc = lrc
language-name-lt = Liotuáinis
language-name-lu = Lúba-Cataingis
language-name-lua = lua
language-name-lun = lun
language-name-luo = luo
language-name-lus = lus
language-name-luy = luy
language-name-lv = Laitvis
language-name-mad = mad
language-name-mag = mag
language-name-mai = mai
language-name-mak = mak
language-name-mas = mas
language-name-mdf = mdf
language-name-men = Meindis
language-name-mer = mer
language-name-mfe = mfe
language-name-mg = Malagáisis
language-name-mga = Meán-Ghaeilge
language-name-mgh = mgh
language-name-mgo = mgo
language-name-mh = Mairsillis
language-name-mi = Maorais
language-name-mic = mic
language-name-min = min
language-name-mk = Macadóinis
language-name-ml = Mailéalaimis
language-name-mn = Mongóilis
language-name-mni = Manapúiris
language-name-moh = Móháicis
language-name-mos = mos
language-name-mr = Maraitis
language-name-mrj = Mairis Iartharach
language-name-ms = Malaeis
language-name-mt = Máltais
language-name-mua = mua
language-name-mul = Ilteangacha
language-name-mus = mus
language-name-mwl = Mioraindéis
language-name-mwr = Marmhairis
language-name-my = Burmais
language-name-myv = myv
language-name-mzn = mzn
language-name-na = Nárúis
language-name-nan = Sínis Min Nan
language-name-nap = Napóilis
language-name-naq = naq
language-name-nb = Ioruais Bokmål
language-name-nd = Ndeibéilis an Tuaiscirt
language-name-nds = Gearmáinis Íochtarach
language-name-nds_NL = Sacsainis Íochtarach
language-name-ne = Neipeailis
language-name-new = new
language-name-ng = Ndongais
language-name-nia = nia
language-name-niu = Níobhais
language-name-nl = Ollainnis
language-name-nl_BE = Pléimeannais
language-name-nmg = nmg
language-name-nn = Nua-Ioruais
language-name-nnh = nnh
language-name-no = Ioruais
language-name-nog = nog
language-name-non = Sean-Lochlainnis
language-name-nqo = nqo
language-name-nr = Ndeibéilis an Deiscirt
language-name-nso = Sútúis an Tuaiscirt
language-name-nus = nus
language-name-nv = Navachóis
language-name-ny = Siséivis
language-name-nyn = nyn
language-name-oc = Ocsatáinis
language-name-oj = Óisibis
language-name-om = Oraimis
language-name-or = Oirísis
language-name-os = Oiséitis
language-name-pa = Puinseáibis
language-name-pag = pag
language-name-pam = pam
language-name-pap = pap
language-name-pau = pau
language-name-pcm = pcm
language-name-peo = Sean-Pheirsis
language-name-pi = Páilis
language-name-pl = Polainnis
language-name-prg = Prúisis
language-name-ps = Paistis
language-name-pt = Portaingéilis
language-name-pt_BR = Portaingéilis Bhrasaíleach
language-name-pt_PT = Portaingéilis Ibéarach
language-name-qu = Ceatsuais
language-name-quc = Cuitséis
language-name-rap = rap
language-name-rar = rar
language-name-rm = Rómainis
language-name-rn = Rúindis
language-name-ro = Rómáinis
language-name-ro_MD = Moldáivis
language-name-rof = rof
language-name-rom = Romainis
language-name-root = root
language-name-ru = Rúisis
language-name-rup = Arómáinis
language-name-rw = Ciniaruaindis
language-name-rwk = rwk
language-name-sa = Sanscrait
language-name-sad = sad
language-name-sah = Sachais
language-name-sam = Aramais Shamárach
language-name-saq = saq
language-name-sat = Santáilis
language-name-sba = sba
language-name-sbp = sbp
language-name-sc = Sairdínis
language-name-scn = Sicilis
language-name-sco = Albainis
language-name-sd = Sindis
language-name-se = Sáimis Thuaidh
language-name-seh = seh
language-name-ses = ses
language-name-sg = Sangóis
language-name-sga = Sean-Ghaeilge
language-name-sh = Seirbea-Chróitis
language-name-shi = Tachelhit
language-name-shn = shn
language-name-si = Siolóinis
language-name-sk = Slóvaicis
language-name-sl = Slóivéinis
language-name-sm = Samóis
language-name-sma = Sáimis Theas
language-name-smj = Sáimis Lule
language-name-smn = Sáimis Inari
language-name-sms = Sáimis Skolt
language-name-sn = Seoinis
language-name-snk = snk
language-name-so = Somáilis
language-name-sog = Sogdánais
language-name-sq = Albáinis
language-name-sr = Seirbis
language-name-srn = srn
language-name-ss = Suaisis
language-name-ssy = ssy
language-name-st = Seasóitis
language-name-su = Sundais
language-name-suk = suk
language-name-sux = Suiméiris
language-name-sv = Sualainnis
language-name-sw = Svahaílis
language-name-sw_CD = Svahaílis an Chongó
language-name-swb = Comóiris
language-name-syr = Siricis
language-name-szl = Siléisis
language-name-ta = Tamailis
language-name-te = Teileagúis
language-name-tem = tem
language-name-teo = teo
language-name-tet = tet
language-name-tg = Táidsícis
language-name-th = Téalainnis
language-name-ti = Tigrinis
language-name-tig = tig
language-name-tk = Tuircméinis
language-name-tl = Tagálaigis
language-name-tlh = Klingon
language-name-tn = Suáinis
language-name-to = Tongais
language-name-tpi = Tok Pisin
language-name-tr = Tuircis
language-name-trv = trv
language-name-ts = Songais
language-name-tt = Tatairis
language-name-tum = tum
language-name-tvl = tvl
language-name-tw = Tíbhis
language-name-twq = twq
language-name-ty = Taihítis
language-name-tyv = tyv
language-name-tzm = Tamazight Atlais Láir
language-name-udm = Udmairtis
language-name-ug = Uigiúiris
language-name-uk = Úcráinis
language-name-umb = umb
language-name-und = Teanga Anaithnid
language-name-ur = Urdúis
language-name-uz = Úisbéiceastáinis
language-name-vai = vai
language-name-ve = Veindis
language-name-vec = Veinéisis
language-name-vi = Vítneaimis
language-name-vls = Pléimeannais Iartharach
language-name-vo = Volapük
language-name-vun = vun
language-name-wa = Vallúnais
language-name-wae = wae
language-name-wal = wal
language-name-war = war
language-name-wo = Volaifis
language-name-wuu = wuu
language-name-xal = Cailmícis
language-name-xh = Cóisis
language-name-xog = xog
language-name-yav = yav
language-name-ybb = ybb
language-name-yi = Giúdais
language-name-yo = Iarúibis
language-name-yue = Cantainis
language-name-za = Siuáingis
language-name-zea = Séalainnis
language-name-zgh = Tamazight Caighdeánach Mharacó
language-name-zh = Sínis
language-name-zh_Hans = Sínis Shimplithe
language-name-zh_Hant = Sínis Thraidisiúnta
language-name-zu = Súlúis
language-name-zun = Zúinis
language-name-zxx = Gan ábhar teangeolaíoch
language-name-zza = zza
