language-name-af = africanês
language-name-ang = inglês antigo
language-name-ar_001 = árabe moderno padrão
language-name-arn = mapuche
language-name-ars = árabe do Négede
language-name-av = avaric
language-name-bax = bamun
language-name-bbj = ghomala
language-name-bua = buriat
language-name-chk = chuquês
language-name-chn = jargão chinook
language-name-chy = cheyenne
language-name-ckb = sorani curdo
language-name-co = córsico
language-name-crs = francês crioulo seselwa
language-name-cs = checo
language-name-cv = chuvash
language-name-de_AT = alemão austríaco
language-name-de_CH = alto alemão suíço
language-name-ee = ewe
language-name-efi = efik
language-name-egy = egípcio clássico
language-name-en_AU = inglês australiano
language-name-en_CA = inglês canadiano
language-name-en_GB = inglês britânico
language-name-en_US = inglês americano
language-name-es_419 = espanhol latino-americano
language-name-es_ES = espanhol europeu
language-name-es_MX = espanhol mexicano
language-name-et = estónio
language-name-fon = fon
language-name-fr_CA = francês canadiano
language-name-fr_CH = francês suíço
language-name-fro = francês antigo
language-name-frs = frísio oriental
language-name-fy = frísico ocidental
language-name-gez = geʼez
language-name-goh = alemão alto antigo
language-name-grc = grego clássico
language-name-gsw = alemão suíço
language-name-ha = haúça
language-name-hi = hindi
language-name-hy = arménio
language-name-kbd = cabardiano
language-name-kea = crioulo cabo-verdiano
language-name-krc = carachaio-bálcaro
language-name-lez = lezghiano
language-name-lg = ganda
language-name-lou = crioulo de Louisiana
language-name-lrc = luri do norte
language-name-luo = luo
language-name-mak = makassarês
language-name-mk = macedónio
language-name-moh = mohawk
language-name-mr = marata
language-name-mul = vários idiomas
language-name-nb = norueguês bokmål
language-name-nds = baixo-alemão
language-name-nds_NL = baixo-saxão
language-name-ne = nepali
language-name-nn = norueguês nynorsk
language-name-non = nórdico antigo
language-name-oc = occitano
language-name-or = oriya
language-name-os = ossético
language-name-pag = língua pangasinesa
language-name-pam = pampango
language-name-peo = persa antigo
language-name-pl = polaco
language-name-pon = língua pohnpeica
language-name-pro = provençal antigo
language-name-ps = pastó
language-name-pt_BR = português do Brasil
language-name-pt_PT = português europeu
language-name-raj = rajastanês
language-name-root = root
language-name-se = sami do norte
language-name-sga = irlandês antigo
language-name-shu = árabe do Chade
language-name-smn = inari sami
language-name-sn = shona
language-name-te = telugu
language-name-tem = temne
language-name-tg = tajique
language-name-tk = turcomano
language-name-to = tonga
language-name-tt = tatar
language-name-tzm = tamazight do Atlas Central
language-name-uz = usbeque
language-name-vai = vai
language-name-wo = uólofe
language-name-xh = xosa
language-name-xog = soga
language-name-yo = ioruba
language-name-zgh = tamazight marroquino padrão
language-name-zun = zuni
language-name-zza = zaza
