language-name-aa = afar
language-name-ab = abkhasiskt
language-name-ace = achinese
language-name-ada = adangme
language-name-ady = adyghe
language-name-af = afrikaans
language-name-agq = aghem
language-name-ain = ainu
language-name-ak = akan
language-name-ale = aleut
language-name-alt = suður altai
language-name-am = amhariskt
language-name-an = aragoniskt
language-name-anp = angika
language-name-ar = arabiskt
language-name-ar_001 = nútíðar vanligt arabiskt
language-name-arn = mapuche
language-name-arp = arapaho
language-name-as = assamesiskt
language-name-asa = asu
language-name-ast = asturianskt
language-name-av = avariskt
language-name-awa = awadhi
language-name-ay = aymara
language-name-az = aserbajdsjanskt
language-name-ba = bashkir
language-name-ban = balinesiskt
language-name-bas = basaa
language-name-be = hvitarussiskt
language-name-bem = bemba
language-name-bez = bena
language-name-bg = bulgarskt
language-name-bgn = vestur balochi
language-name-bho = bhojpuri
language-name-bi = bislama
language-name-bin = bini
language-name-bla = siksika
language-name-bm = bambara
language-name-bn = bangla
language-name-bo = tibetskt
language-name-br = bretonskt
language-name-brx = bodo
language-name-bs = bosniskt
language-name-bss = bakossi
language-name-bug = buginesiskt
language-name-byn = blin
language-name-ca = katalani
language-name-ce = tjetjenskt
language-name-ceb = cebuano
language-name-cgg = chiga
language-name-ch = chamorro
language-name-chk = chuukese
language-name-chm = mari
language-name-cho = choctaw
language-name-chr = cherokee
language-name-chy = cheyenne
language-name-ckb = miðkurdiskt
language-name-co = korsikanskt
language-name-crs = seselwa creole franskt
language-name-cs = kekkiskt
language-name-cu = kirkju sláviskt
language-name-cv = chuvash
language-name-cy = walisiskt
language-name-da = danskt
language-name-dak = dakota
language-name-dar = dargwa
language-name-dav = taita
language-name-de = týskt
language-name-dgr = dogrib
language-name-dje = sarma
language-name-dsb = lágt sorbian
language-name-dua = duala
language-name-dv = divehi
language-name-dyo = jola-fonyi
language-name-dz = dzongkha
language-name-dzg = dazaga
language-name-ebu = embu
language-name-ee = ewe
language-name-efi = efik
language-name-eka = ekajuk
language-name-el = grikskt
language-name-en = enskt
language-name-eo = esperanto
language-name-es = spanskt
language-name-et = estiskt
language-name-eu = baskiskt
language-name-ewo = ewondo
language-name-fa = persiskt
language-name-ff = fulah
language-name-fi = finskt
language-name-fil = filipiniskt
language-name-fj = fijimál
language-name-fo = føroyskt
language-name-fon = fon
language-name-fr = franskt
language-name-fur = friuliskt
language-name-fy = vestur frísiskt
language-name-ga = írskt
language-name-gaa = ga
language-name-gag = gagauz
language-name-gan = gan kinesiskt
language-name-gd = skotskt gæliskt
language-name-gez = geez
language-name-gil = kiribatiskt
language-name-gl = galisiskt
language-name-gn = guarani
language-name-gor = gorontalo
language-name-gu = gujarati
language-name-guz = gusii
language-name-gv = manx
language-name-gwi = gwich’in
language-name-ha = hausa
language-name-hak = hakka kinesiskt
language-name-haw = hawaiianskt
language-name-he = hebraiskt
language-name-hi = hindi
language-name-hil = hiligaynon
language-name-hmn = hmong
language-name-hr = kroatiskt
language-name-hsb = ovara sorbian
language-name-hsn = xiang kinesiskt
language-name-ht = haitiskt creole
language-name-hu = ungarskt
language-name-hup = hupa
language-name-hy = armenskt
language-name-hz = herero
language-name-ia = interlingua
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indonesiskt
language-name-ie = interlingue
language-name-ig = igbo
language-name-ii = sichuan yi
language-name-ilo = iloko
language-name-inh = inguish
language-name-io = ido
language-name-is = íslendskt
language-name-it = italskt
language-name-iu = inuktitut
language-name-ja = japanskt
language-name-jbo = lojban
language-name-jgo = ngomba
language-name-jmc = machame
language-name-jv = javanskt
language-name-ka = georgiskt
language-name-kab = kabyle
language-name-kac = kachin
language-name-kaj = jju
language-name-kam = kamba
language-name-kbd = kabardinskt
language-name-kcg = tyap
language-name-kde = makonde
language-name-kea = grønhøvdaoyggjarskt
language-name-kfo = koro
language-name-kha = khasi
language-name-khq = koyra chiini
language-name-ki = kikuyu
language-name-kj = kuanyama
language-name-kk = kazakh
language-name-kkj = kako
language-name-kl = kalaallisut
language-name-kln = kalenjin
language-name-km = khmer
language-name-kmb = kimbundu
language-name-kn = kannada
language-name-ko = koreanskt
language-name-koi = komi-permyak
language-name-kok = konkani
language-name-kpe = kpelle
language-name-kr = kanuri
language-name-krc = karachay-balkar
language-name-krl = karelskt
language-name-kru = kurukh
language-name-ks = kashmiri
language-name-ksb = shambala
language-name-ksf = bafia
language-name-ksh = kølnskt
language-name-ku = kurdiskt
language-name-kum = kumyk
language-name-kv = komi
language-name-kw = corniskt
language-name-ky = kyrgyz
language-name-la = latín
language-name-lad = ladino
language-name-lag = langi
language-name-lah = lahnda
language-name-lb = luksemborgskt
language-name-lez = lezghian
language-name-lg = ganda
language-name-li = limburgiskt
language-name-lkt = lakota
language-name-ln = lingala
language-name-lo = laoskt
language-name-loz = lozi
language-name-lrc = norður luri
language-name-lt = litaviskt
language-name-lu = luba-katanga
language-name-lua = luba-lulua
language-name-lun = lunda
language-name-luo = luo
language-name-lus = mizo
language-name-luy = luyia
language-name-lv = lettiskt
language-name-mad = maduresiskt
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = makasar
language-name-mas = masai
language-name-mdf = moksha
language-name-men = mende
language-name-mer = meru
language-name-mfe = morisyen
language-name-mg = malagassiskt
language-name-mgh = makhuwa-meetto
language-name-mgo = metaʼ
language-name-mh = marshallesiskt
language-name-mi = maori
language-name-mic = micmac
language-name-min = minangkabau
language-name-mk = makedónskt
language-name-ml = malayalam
language-name-mn = mongolskt
language-name-mni = manupuri
language-name-moh = mohawk
language-name-mos = mossi
language-name-mr = marathi
language-name-ms = malaiiskt
language-name-mt = maltiskt
language-name-mua = mundang
language-name-mul = ymisk mál
language-name-mus = creek
language-name-mwl = mirandesiskt
language-name-my = burmesiskt
language-name-myv = erzya
language-name-mzn = mazanderani
language-name-na = nauru
language-name-nan = min nan kinesiskt
language-name-nap = napolitanskt
language-name-naq = nama
language-name-nb = norskt bókmál
language-name-nd = norður ndebele
language-name-nds = lágt týskt
language-name-nds_NL = lágt saksiskt
language-name-ne = nepalskt
language-name-new = newari
language-name-ng = ndonga
language-name-nia = nias
language-name-niu = niuean
language-name-nl = hálendskt
language-name-nl_BE = flamskt
language-name-nmg = kwasio
language-name-nn = nýnorskt
language-name-nnh = ngiemboon
language-name-no = norskt
language-name-nog = nogai
language-name-nqo = nʼko
language-name-nr = suður ndebele
language-name-nso = norður sotho
language-name-nus = nuer
language-name-nv = navajo
language-name-ny = nyanja
language-name-nyn = nyankole
language-name-oc = occitanskt
language-name-om = oromo
language-name-or = odia
language-name-os = ossetiskt
language-name-pa = punjabi
language-name-pag = pangasinan
language-name-pam = pampanga
language-name-pap = papiamento
language-name-pau = palauan
language-name-pcm = nigeriskt pidgin
language-name-pl = pólskt
language-name-prg = prusslanskt
language-name-ps = pashto
language-name-pt = portugiskiskt
language-name-qu = quechua
language-name-quc = kʼicheʼ
language-name-rap = rapanui
language-name-rar = rarotongiskt
language-name-rm = retoromanskt
language-name-rn = rundi
language-name-ro = rumenskt
language-name-ro_MD = moldaviskt
language-name-rof = rombo
language-name-root = root
language-name-ru = russiskt
language-name-rup = aromenskt
language-name-rw = kinyarwanda
language-name-rwk = rwa
language-name-sa = sanskrit
language-name-sad = sandawe
language-name-sah = sakha
language-name-saq = samburu
language-name-sat = santali
language-name-sba = ngambay
language-name-sbp = sangu
language-name-sc = sardiskt
language-name-scn = sisilanskt
language-name-sco = skotskt
language-name-sd = sindhi
language-name-sdh = suður kurdiskt
language-name-se = norður sámiskt
language-name-seh = sena
language-name-ses = koyraboro senni
language-name-sg = sango
language-name-sh = serbokroatiskt
language-name-shi = tachelhit
language-name-shn = shan
language-name-si = singalesiskt
language-name-sk = slovakiskt
language-name-sl = slovenskt
language-name-sm = sámoiskt
language-name-sma = suður sámiskt
language-name-smj = lule sámiskt
language-name-smn = inari sami
language-name-sms = skolt sámiskt
language-name-sn = shona
language-name-snk = soninke
language-name-so = somaliskt
language-name-sq = albanskt
language-name-sr = serbiskt
language-name-srn = sranan tongo
language-name-ss = swatiskt
language-name-ssy = saho
language-name-st = sesotho
language-name-su = sundanesiskt
language-name-suk = sukuma
language-name-sv = svenskt
language-name-sw = swahili
language-name-sw_CD = kongo svahili
language-name-swb = komoriskt
language-name-syr = syriac
language-name-ta = tamilskt
language-name-te = telugu
language-name-tem = timne
language-name-teo = teso
language-name-tet = tetum
language-name-tg = tajik
language-name-th = tailendskt
language-name-ti = tigrinya
language-name-tig = tigre
language-name-tk = turkmenskt
language-name-tl = tagalog
language-name-tlh = klingonskt
language-name-tn = tswana
language-name-to = tonganskt
language-name-tpi = tok pisin
language-name-tr = turkiskt
language-name-trv = taroko
language-name-ts = tsonga
language-name-tt = tatar
language-name-tum = tumbuka
language-name-tvl = tuvalu
language-name-tw = twi
language-name-twq = tasawaq
language-name-ty = tahitiskt
language-name-tyv = tuvinian
language-name-tzm = miðatlasfjøll tamazight
language-name-udm = udmurt
language-name-ug = uyghur
language-name-uk = ukrainskt
language-name-umb = umbundu
language-name-und = ókent mál
language-name-ur = urdu
language-name-uz = usbekiskt
language-name-vai = vai
language-name-ve = venda
language-name-vi = vjetnamesiskt
language-name-vo = volapykk
language-name-vun = vunjo
language-name-wa = walloon
language-name-wae = walser
language-name-wal = wolaytta
language-name-war = waray
language-name-wbp = warlpiri
language-name-wo = wolof
language-name-wuu = wu kinesiskt
language-name-xal = kalmyk
language-name-xh = xhosa
language-name-xog = soga
language-name-yav = yangben
language-name-ybb = yemba
language-name-yi = jiddiskt
language-name-yo = yoruba
language-name-yue = kantonesiskt
language-name-zgh = vanligt marokanskt tamazight
language-name-zh = kinesiskt
language-name-zh_Hans = einkult kinesiskt
language-name-zh_Hant = vanligt kinesiskt
language-name-zu = sulu
language-name-zun = zuni
language-name-zxx = einki málsligt innihald
language-name-zza = zaza
