language-name-ace = achenés
language-name-ady = adigeo
language-name-alt = altái del sur
language-name-arp = arapajó
language-name-ars = árabe de Néyed
language-name-bla = siksiká
language-name-eu = vasco
language-name-fon = fon
language-name-goh = alemán de la alta edad antigua
language-name-grc = griego clásico
language-name-gu = gujarati
language-name-ht = haitiano
language-name-kbd = cabardiano
language-name-lo = laosiano
language-name-luo = luo
language-name-nr = ndebele del sur
language-name-prg = prusiano antiguo
language-name-rm = retorrománico
language-name-sma = sami del sur
language-name-st = sesotho del sur
language-name-sw = swahili
language-name-syr = siríaco
language-name-tet = tetun
language-name-tzm = tamazight del Marruecos Central
language-name-vai = vai
language-name-wal = walamo
language-name-wuu = wu
language-name-zun = zuni
