language-name-bm = бамананкан
language-name-bn = бангла
language-name-ff = фулах
language-name-gsw = швајцарски немачки
language-name-ht = хаићански креолски
language-name-lo = лаошки
language-name-moh = мохок
language-name-nqo = н’ко
language-name-shi = јужни шилха
language-name-si = синхалски
language-name-tzm = централноатласки тамашек
language-name-xh = исикоса
language-name-zgh = стандардни марокански тамашек
language-name-zu = исизулу
