language-name-aa = Afahresch
language-name-ab = Abchahsesch
language-name-ace = Aschenehsesch
language-name-ada = Adangmesch
language-name-ady = Adygehjsch
language-name-ae = Avästahnesch
language-name-aeb = Tonehsesch Arahbesch
language-name-af = Afrikaans
language-name-afh = Afrehihlesch
language-name-agq = Aghehmesch
language-name-ain = Aijnu
language-name-ak = Akahnesch
language-name-akk = Akahdesch
language-name-ale = Ale’uhtesch
language-name-am = Amhahresch
language-name-an = Arrajonehsesch
language-name-ang = Ahl Änglesch
language-name-anp = Anjikahnesch
language-name-ar = Arahbesch
language-name-ar_001 = Schtandatt Arahbesch
language-name-arp = Arrappaho
language-name-arq = Aljehresch Arahbesch
language-name-ary = Marokahnesch Arahbesch
language-name-arz = Äjiptesch Arahbesch
language-name-as = Aßamehsesch
language-name-asa = Pare
language-name-ase = Amärrekahnesche Blendeschprohch
language-name-ast = Astuhrejahnesch
language-name-av = Avahresch
language-name-awa = Awahdesch
language-name-ay = Aimahresch
language-name-az = Asserbaidschahnesch
language-name-az_Arab = Södasserbaidschahnesch
language-name-ba = Baschkihresch
language-name-bal = Beluhtschesch
language-name-ban = Balinehsesch
language-name-bar = Bairesch
language-name-bas = Basaa-Schprohche
language-name-be = Wiißrußesch
language-name-bem = Bemba
language-name-bez = Bena
language-name-bg = Bulljahresch
language-name-bho = Bhohdschpuresch
language-name-bi = Bislahmesch
language-name-bin = Edo
language-name-bm = Bambara
language-name-bn = Bängjahlesch
language-name-bo = Tibehtesch
language-name-bpy = Bischnuprejahnesch
language-name-br = Bettohnesch
language-name-bra = Brahjesch
language-name-brh = Brahuijesch
language-name-brx = Boddo
language-name-bs = Boßnesch
language-name-bua = Burejahtesch
language-name-bug = Bujinehsesch
language-name-byn = Bilihnesch
language-name-ca = Kattalahnesch
language-name-ce = Tschätschehnesch
language-name-ceb = Zebuwahnesch
language-name-cgg = Kihja-Schprohch
language-name-ch = Chamorru
language-name-chk = Trukehsesch
language-name-chm = Mahresch
language-name-cho = Tschoktoh
language-name-chr = Tschärrokeh
language-name-chy = Tschäjänn
language-name-ckb = Zäntrahl-Kurrdesch
language-name-co = Korsesch
language-name-cop = Koptesch
language-name-cs = Tschäschesch
language-name-csb = Kaschuhbesch
language-name-cu = Kerscheßlahwesch
language-name-cv = Tschowaschesch
language-name-cy = Wallihsesch
language-name-da = Dähnesch
language-name-dak = Dakohtesch
language-name-dar = Darjihnesch
language-name-dav = Dawedahnesch
language-name-de = Deutsch
language-name-de_AT = Deutsch uß Öhßterich
language-name-de_CH = Deutsch uß de Schweijz
language-name-dgr = Dohjribesch
language-name-dje = Djerma
language-name-dsb = Niddersorbesch
language-name-dua = Du’ala
language-name-dum = Meddelnehderlängsch
language-name-dv = Divehjesch
language-name-dyo = Jola-Fonyisch
language-name-dz = Butahnesch
language-name-dzg = Dassajahnesch
language-name-ebu = Kîembu
language-name-ee = Ewe
language-name-efi = Äffiksch
language-name-egl = Emilijahnesch
language-name-egy = Ahl Äjiptesch
language-name-eka = Ekajukesch
language-name-el = Jrihschesch
language-name-en = Änglesch
language-name-en_AU = Änglesch uß Außtrahlije
language-name-en_CA = Änglesch uß Kanada
language-name-en_GB = Änglesch uß Jruhßbrettannije
language-name-en_US = Amärrekahnesch Änglesch
language-name-enm = Meddelänglesch
language-name-eo = Esperanto
language-name-es = Schpahnesch
language-name-es_419 = Schpahnesch uß Latting-Ammärrika
language-name-es_ES = Schpahnesch en Schpahneje
language-name-es_MX = Schpahnesch en Mäxikoh
language-name-esu = Zäntrahl-Juppik
language-name-et = Äßnesch
language-name-eu = Baskesch
language-name-ewo = Ewonndo
language-name-fa = Pärsesch
language-name-ff = Fulfulde
language-name-fi = Finnesch
language-name-fil = Fillipihnesch
language-name-fj = Fihdschesch
language-name-fo = Färröhresch
language-name-fon = Fohnesch
language-name-fr = Franzühsesch
language-name-fr_CA = Franzühsesch uß Kanada
language-name-fr_CH = Franzühsesch uß de Schweijz
language-name-fur = Frijauhlesch
language-name-fy = Wäßfrihsesch
language-name-ga = Ihresch
language-name-gaa = Jah
language-name-gez = Ji’is-Ahl-Ättejohpesch
language-name-gil = Jillbättehsesch
language-name-gl = Jallihzesch
language-name-gn = Juwarahnesch
language-name-gor = Jorontalohsch
language-name-gsw = Schwitzerdütsch
language-name-gu = Gutscharatesch
language-name-gv = Mangx
language-name-ha = Haußa
language-name-haw = Hauajahnesch
language-name-he = Hebrähjesch
language-name-hi = Hinndi
language-name-hil = Hiligaynon
language-name-hmn = Hmong
language-name-hr = Krowatesch
language-name-hsb = Bovversorrbesch
language-name-ht = Ha’iihtesch
language-name-hu = Unnjarresch
language-name-hup = Hupa
language-name-hy = Armehnesch
language-name-hz = Herrehro
language-name-ia = de Interlingua
language-name-iba = Ibahnesch
language-name-ibb = Ibibio
language-name-id = Indonehsesch
language-name-ig = Igbo
language-name-ilo = Ilokahnesch
language-name-inh = Engjuschesch
language-name-io = Ihdo
language-name-is = Ißlänndesch
language-name-it = Etalljähnesch
language-name-iu = Inuktitut
language-name-izh = Ingjrijahnesch
language-name-ja = Japahnesch
language-name-jam = Jamaikahnesch-Änglesch
language-name-jbo = Lodschbahn
language-name-jgo = Njomba
language-name-jpr = Jühdesch-Pärsesch
language-name-jut = Jüttesch
language-name-jv = Javahnesch
language-name-ka = Je’orjesch
language-name-kab = Kabyhlesch
language-name-kam = Kamba vun Kehnija
language-name-kbd = Kabadihnesch
language-name-kde = Chimakonde
language-name-kea = Kapvärdesch
language-name-kfo = Koro vun de Älfebeijnköß
language-name-kha = Khasi
language-name-khq = Kojra Tschihni
language-name-ki = Rekohjo
language-name-kj = Oschivambo
language-name-kk = Kassakkesch
language-name-kkj = Kako
language-name-kl = Jröhnländesch
language-name-kln = Kaländjihnesch
language-name-km = Khmer
language-name-kmb = Kimbundu
language-name-kn = Kannada
language-name-ko = Korrejaanesch
language-name-kok = Kon’kahnesch
language-name-kpe = Kpäle
language-name-kr = Kanuhresch
language-name-krc = Karatschaj-Balkahresch-Törkesch
language-name-krl = Karehlesch
language-name-kru = Korochesch
language-name-ks = Kaschmihresch
language-name-ksf = Bafijahnesch
language-name-ksh = Kölsch
language-name-ku = Kurrdesch
language-name-kum = Kumykesch
language-name-kv = Kohmesch
language-name-kw = Kornesch
language-name-ky = Kirjihsesch
language-name-la = Lateijnesch
language-name-lad = Ladihnesch
language-name-lag = Lango
language-name-lah = de Landa-Schprooche
language-name-lb = Luxemborjesch
language-name-lez = Lesjesch
language-name-lg = Lugannda
language-name-li = Lemburjesch
language-name-lkt = Lakota
language-name-ln = Lingjalla
language-name-lo = Lahootesch
language-name-loz = Silohzi
language-name-lrc = Nood-Luhresch
language-name-lt = Littouesch
language-name-lu = Kiluba
language-name-lua = Tschiluba
language-name-lun = Schilunnda
language-name-luo = Luo
language-name-luy = Luhjesch
language-name-lv = Lättesch
language-name-mdf = Mokschah
language-name-mg = Madajaßkesch
language-name-mh = Maschallehsesch
language-name-mi = Ma’ohresch
language-name-mk = Mazedohnesch
language-name-ml = Mallajalam
language-name-mn = Mongjohlesch
language-name-mni = Meitei-Manipuhresch
language-name-mr = Marrahtesch
language-name-ms = Mallaijesch
language-name-mt = Maltehsesch
language-name-mua = Mundang
language-name-mul = -ongerscheidlijje Schprohche-
language-name-mus = Krihk
language-name-mwl = Mirandehsesch
language-name-my = Burmehsesch
language-name-myv = Ärsjahnesch
language-name-na = Nauruhesch
language-name-nap = Napolletahnesch
language-name-nb = Norrwehjesch Bokmål
language-name-nd = Nood-Ndebele
language-name-nds_NL = Nehdersaksesch en de Nederläng
language-name-ne = Nepallehsesch
language-name-new = Newahresch
language-name-ng = Ndongjahnesch
language-name-nl = Holländesch
language-name-nl_BE = Flähmesch
language-name-nmg = Gyele
language-name-nn = Neu Norrwehjesch
language-name-nnh = Njijembohn
language-name-no = Norrwehjesch
language-name-nog = Nojal
language-name-nso = Nood-Sohto
language-name-nv = Navvacho
language-name-ny = Schi-Schewa
language-name-or = Oriija
language-name-os = Oßeetesch
language-name-pa = Panschaabesch
language-name-pl = Pollnesch
language-name-ps = Paschtuunesch
language-name-pt = Pochtojesesch
language-name-pt_BR = Brasilljaanesch Pochtojesesch
language-name-pt_PT = Pochtojesesch uß Pochtojall
language-name-qu = Kättschowa
language-name-quc = K’ische’
language-name-rm = Rätoromaanesch
language-name-rn = K-Rundesch
language-name-ro = Rumänesch
language-name-rof = Kirombo
language-name-ru = Rußßesch
language-name-rup = Arromahnesch
language-name-rw = Kinja-Ruandesch
language-name-sa = Sanskrit
language-name-sah = Jackutesch
language-name-sba = Njambaij
language-name-sd = Sinndi
language-name-se = Nood-Lappländesch
language-name-ses = Kojraboro Senni
language-name-sg = Sangjo
language-name-sh = Särbokowatesch
language-name-shi = Taschelhittesch
language-name-si = Singjaleesesch
language-name-sk = ẞlovakesch
language-name-sl = ẞloveenesch
language-name-sm = Sammohanesch
language-name-smj = Lule-Läppländesch
language-name-smn = Inahri Lappländesch
language-name-sn = Schi-Schona
language-name-so = Somahlesch
language-name-sq = Albahnesch
language-name-sr = Särbesch
language-name-ss = Si-Swatesch
language-name-st = Söd-Sooto
language-name-su = Sindanehsesch
language-name-sv = Schwehdesch
language-name-sw = Suahehlesch
language-name-swb = Kommohresch
language-name-syr = Sührejakkesch
language-name-ta = Tamihlesch
language-name-te = Telluhju
language-name-tet = Tetumsch
language-name-tg = Tadschihkesch
language-name-th = Tailändesch
language-name-ti = Tijrenejahnesch
language-name-tig = Tigre
language-name-tk = Törkmehnesch
language-name-tl = Tajalloch
language-name-tlh = Klingjohnesch
language-name-tn = Se-Zwahnesch
language-name-to = Tongjahnesch
language-name-tpi = Tok Pisin
language-name-tr = Törkesch
language-name-ts = Xi-Zongjahnesch
language-name-tt = Tattahresch
language-name-twq = Tasawaq
language-name-ty = Tahihtesch
language-name-tyv = Tuvinijahnesch
language-name-tzm = Tamasicht ussem meddlere Atlas
language-name-udm = Udmuchtesch
language-name-ug = Uj’juhresch
language-name-uk = Ukrainesch
language-name-umb = Umbundesch
language-name-und = -onbikannte-Schprooch-
language-name-uz = Ußbehkesch
language-name-ve = Wenda
language-name-vi = Vijätnammehsesch
language-name-vo = Volapük
language-name-wa = Walohnesch
language-name-wae = Walserdütsch
language-name-wal = Welahmo
language-name-war = Waray-Waray
language-name-wo = Woloff
language-name-xal = Kalmükkesch
language-name-xh = Isi-Khohsa
language-name-ybb = Jämmbah
language-name-yi = Jiddesch
language-name-yo = Joruhba
language-name-yue = Kanton-Schinehsesch
language-name-zu = Suhlu
language-name-zun = Suhñi
language-name-zxx = kein Schprooch
language-name-zza = Sahsajesch
