language-name-aa = afarščina
language-name-ab = abhaščina
language-name-ace = ačejščina
language-name-ach = ačolijščina
language-name-ada = adangmejščina
language-name-ady = adigejščina
language-name-ae = avestijščina
language-name-af = afrikanščina
language-name-afh = afrihili
language-name-agq = aghemščina
language-name-ain = ainujščina
language-name-ak = akanščina
language-name-akk = akadščina
language-name-ale = aleutščina
language-name-alt = južna altajščina
language-name-am = amharščina
language-name-an = aragonščina
language-name-ang = stara angleščina
language-name-anp = angikaščina
language-name-ar = arabščina
language-name-ar_001 = sodobna standardna arabščina
language-name-arc = aramejščina
language-name-arn = mapudungunščina
language-name-arp = arapaščina
language-name-arw = aravaščina
language-name-as = asamščina
language-name-asa = asujščina
language-name-ast = asturijščina
language-name-av = avarščina
language-name-awa = avadščina
language-name-ay = ajmarščina
language-name-az = azerbajdžanščina
language-name-ba = baškirščina
language-name-bal = beludžijščina
language-name-ban = balijščina
language-name-bas = basa
language-name-be = beloruščina
language-name-bej = bedža
language-name-bem = bemba
language-name-bez = benajščina
language-name-bg = bolgarščina
language-name-bgn = zahodnobalučijščina
language-name-bho = bodžpuri
language-name-bi = bislamščina
language-name-bik = bikolski jezik
language-name-bin = edo
language-name-bla = siksika
language-name-bm = bambarščina
language-name-bn = bengalščina
language-name-bo = tibetanščina
language-name-br = bretonščina
language-name-bra = bradžbakanščina
language-name-brx = bodojščina
language-name-bs = bosanščina
language-name-bua = burjatščina
language-name-bug = buginščina
language-name-byn = blinščina
language-name-ca = katalonščina
language-name-cad = kadoščina
language-name-car = karibski jezik
language-name-ce = čečenščina
language-name-ceb = sebuanščina
language-name-cgg = čigajščina
language-name-ch = čamorščina
language-name-chb = čibčevščina
language-name-chg = čagatajščina
language-name-chk = trukeščina
language-name-chm = marijščina
language-name-chn = činuški žargon
language-name-cho = čoktavščina
language-name-chp = čipevščina
language-name-chr = čerokeščina
language-name-chy = čejenščina
language-name-ckb = soranska kurdščina
language-name-co = korziščina
language-name-cop = koptščina
language-name-cr = krijščina
language-name-crh = krimska tatarščina
language-name-crs = sejšelska francoska kreolščina
language-name-cs = češčina
language-name-csb = kašubščina
language-name-cu = stara cerkvena slovanščina
language-name-cv = čuvaščina
language-name-cy = valižanščina
language-name-da = danščina
language-name-dak = dakotščina
language-name-dar = darginščina
language-name-dav = taitajščina
language-name-de = nemščina
language-name-de_AT = avstrijska nemščina
language-name-del = delavarščina
language-name-den = slavejščina
language-name-dgr = dogrib
language-name-din = dinka
language-name-dje = zarmajščina
language-name-doi = dogri
language-name-dsb = dolnja lužiška srbščina
language-name-dua = duala
language-name-dum = srednja nizozemščina
language-name-dv = diveščina
language-name-dyo = jola-fonjiščina
language-name-dyu = diula
language-name-dz = dzonka
language-name-dzg = dazaga
language-name-ebu = embujščina
language-name-ee = evenščina
language-name-efi = efiščina
language-name-egy = stara egipčanščina
language-name-eka = ekajuk
language-name-el = grščina
language-name-elx = elamščina
language-name-en = angleščina
language-name-en_AU = avstralska angleščina
language-name-en_CA = kanadska angleščina
language-name-enm = srednja angleščina
language-name-eo = esperanto
language-name-es = španščina
language-name-es_419 = latinskoameriška španščina
language-name-es_ES = evropska španščina
language-name-et = estonščina
language-name-eu = baskovščina
language-name-ewo = evondovščina
language-name-fa = perzijščina
language-name-fan = fangijščina
language-name-fat = fantijščina
language-name-ff = fulščina
language-name-fi = finščina
language-name-fil = filipinščina
language-name-fj = fidžijščina
language-name-fo = ferščina
language-name-fon = fonščina
language-name-fr = francoščina
language-name-fr_CA = kanadska francoščina
language-name-fr_CH = švicarska francoščina
language-name-frc = cajunska francoščina
language-name-frm = srednja francoščina
language-name-fro = stara francoščina
language-name-frr = severna frizijščina
language-name-frs = vzhodna frizijščina
language-name-fur = furlanščina
language-name-fy = zahodna frizijščina
language-name-ga = irščina
language-name-gaa = ga
language-name-gag = gagavščina
language-name-gay = gajščina
language-name-gba = gbajščina
language-name-gd = škotska gelščina
language-name-gez = etiopščina
language-name-gil = kiribatščina
language-name-gl = galicijščina
language-name-gmh = srednja visoka nemščina
language-name-gn = gvaranijščina
language-name-goh = stara visoka nemščina
language-name-gon = gondi
language-name-gor = gorontalščina
language-name-got = gotščina
language-name-grb = grebščina
language-name-grc = stara grščina
language-name-gu = gudžaratščina
language-name-guz = gusijščina
language-name-gv = manščina
language-name-gwi = gvičin
language-name-ha = havščina
language-name-hai = haidščina
language-name-haw = havajščina
language-name-he = hebrejščina
language-name-hi = hindujščina
language-name-hil = hiligajnonščina
language-name-hit = hetitščina
language-name-hmn = hmonščina
language-name-ho = hiri motu
language-name-hr = hrvaščina
language-name-hsb = gornja lužiška srbščina
language-name-ht = haitijska kreolščina
language-name-hu = madžarščina
language-name-hup = hupa
language-name-hy = armenščina
language-name-hz = herero
language-name-ia = interlingva
language-name-iba = ibanščina
language-name-ibb = ibibijščina
language-name-id = indonezijščina
language-name-ie = interlingve
language-name-ig = igboščina
language-name-ii = sečuanska jiščina
language-name-ik = inupiaščina
language-name-ilo = ilokanščina
language-name-inh = inguščina
language-name-io = ido
language-name-is = islandščina
language-name-it = italijanščina
language-name-iu = inuktitutščina
language-name-ja = japonščina
language-name-jbo = lojban
language-name-jgo = ngomba
language-name-jmc = mačamejščina
language-name-jpr = judovska perzijščina
language-name-jrb = judovska arabščina
language-name-jv = javanščina
language-name-ka = gruzijščina
language-name-kaa = karakalpaščina
language-name-kab = kabilščina
language-name-kac = kačinščina
language-name-kaj = jju
language-name-kam = kambaščina
language-name-kaw = kavi
language-name-kbd = kabardinščina
language-name-kcg = tjapska nigerijščina
language-name-kde = makondščina
language-name-kea = zelenortskootoška kreolščina
language-name-kfo = koro
language-name-kg = kongovščina
language-name-kha = kasi
language-name-kho = kotanščina
language-name-khq = koyra chiini
language-name-ki = kikujščina
language-name-kj = kvanjama
language-name-kk = kazaščina
language-name-kkj = kako
language-name-kl = grenlandščina
language-name-kln = kalenjinščina
language-name-km = kmerščina
language-name-kmb = kimbundu
language-name-kn = kanareščina
language-name-ko = korejščina
language-name-koi = komi-permjaščina
language-name-kok = konkanščina
language-name-kos = kosrajščina
language-name-kpe = kpelejščina
language-name-kr = kanurščina
language-name-krc = karačaj-balkarščina
language-name-krl = karelščina
language-name-kru = kuruk
language-name-ks = kašmirščina
language-name-ksb = šambala
language-name-ksf = bafia
language-name-ksh = kölnsko narečje
language-name-ku = kurdščina
language-name-kum = kumiščina
language-name-kut = kutenajščina
language-name-kv = komijščina
language-name-kw = kornijščina
language-name-ky = kirgiščina
language-name-la = latinščina
language-name-lad = ladinščina
language-name-lag = langijščina
language-name-lah = landa
language-name-lam = lamba
language-name-lb = luksemburščina
language-name-lez = lezginščina
language-name-lg = ganda
language-name-li = limburščina
language-name-lkt = lakotščina
language-name-ln = lingala
language-name-lo = laoščina
language-name-lol = mongo
language-name-lou = louisianska kreolščina
language-name-loz = lozi
language-name-lrc = severna lurijščina
language-name-lt = litovščina
language-name-lu = luba-katanga
language-name-lua = luba-lulua
language-name-lui = luisenščina
language-name-lun = lunda
language-name-luo = luo
language-name-lus = mizojščina
language-name-luy = luhijščina
language-name-lv = latvijščina
language-name-mad = madurščina
language-name-mag = magadščina
language-name-mai = maitili
language-name-mak = makasarščina
language-name-man = mandingo
language-name-mas = masajščina
language-name-mdf = mokšavščina
language-name-mdr = mandarščina
language-name-men = mende
language-name-mer = meru
language-name-mfe = morisjenščina
language-name-mg = malagaščina
language-name-mga = srednja irščina
language-name-mgh = makuva-meto
language-name-mgo = meta
language-name-mh = marshallovščina
language-name-mi = maorščina
language-name-mic = mikmaščina
language-name-min = minangkabau
language-name-mk = makedonščina
language-name-ml = malajalamščina
language-name-mn = mongolščina
language-name-mnc = mandžurščina
language-name-mni = manipurščina
language-name-moh = mohoščina
language-name-mos = mosijščina
language-name-mr = maratščina
language-name-ms = malajščina
language-name-mt = malteščina
language-name-mua = mundang
language-name-mul = več jezikov
language-name-mus = creekovščina
language-name-mwl = mirandeščina
language-name-mwr = marvarščina
language-name-my = burmanščina
language-name-myv = erzjanščina
language-name-mzn = mazanderanščina
language-name-na = naurujščina
language-name-nan = min nan kitajščina
language-name-nap = napolitanščina
language-name-naq = khoekhoe
language-name-nb = knjižna norveščina
language-name-nd = severna ndebelščina
language-name-nds = nizka nemščina
language-name-nds_NL = nizka saščina
language-name-ne = nepalščina
language-name-new = nevarščina
language-name-ng = ndonga
language-name-nia = niaščina
language-name-niu = niuejščina
language-name-nl = nizozemščina
language-name-nl_BE = flamščina
language-name-nmg = kwasio
language-name-nn = novonorveščina
language-name-nnh = ngiemboonščina
language-name-no = norveščina
language-name-nog = nogajščina
language-name-non = stara nordijščina
language-name-nqo = n’ko
language-name-nr = južna ndebelščina
language-name-nso = severna sotščina
language-name-nus = nuerščina
language-name-nv = navajščina
language-name-nwc = klasična nevarščina
language-name-ny = njanščina
language-name-nym = njamveščina
language-name-nyn = njankole
language-name-nyo = njoro
language-name-nzi = nzima
language-name-oc = okcitanščina
language-name-oj = anašinabščina
language-name-om = oromo
language-name-or = odijščina
language-name-os = osetinščina
language-name-osa = osage
language-name-ota = otomanska turščina
language-name-pa = pandžabščina
language-name-pag = pangasinanščina
language-name-pam = pampanščina
language-name-pap = papiamentu
language-name-pau = palavanščina
language-name-pcm = nigerijski pidžin
language-name-peo = stara perzijščina
language-name-phn = feničanščina
language-name-pi = palijščina
language-name-pl = poljščina
language-name-pon = ponpejščina
language-name-prg = stara pruščina
language-name-pro = stara provansalščina
language-name-ps = paštunščina
language-name-pt = portugalščina
language-name-pt_BR = brazilska portugalščina
language-name-pt_PT = evropska portugalščina
language-name-qu = kečuanščina
language-name-quc = quiche
language-name-raj = radžastanščina
language-name-rap = rapanujščina
language-name-rar = rarotongščina
language-name-rm = retoromanščina
language-name-rn = rundščina
language-name-ro = romunščina
language-name-ro_MD = moldavščina
language-name-rof = rombo
language-name-rom = romščina
language-name-root = rootščina
language-name-ru = ruščina
language-name-rup = aromunščina
language-name-rw = ruandščina
language-name-rwk = rwa
language-name-sa = sanskrt
language-name-sad = sandavščina
language-name-sah = jakutščina
language-name-sam = samaritanska aramejščina
language-name-saq = samburščina
language-name-sas = sasaščina
language-name-sat = santalščina
language-name-sba = ngambajščina
language-name-sbp = sangujščina
language-name-sc = sardinščina
language-name-scn = sicilijanščina
language-name-sco = škotščina
language-name-sd = sindščina
language-name-sdh = južna kurdščina
language-name-se = severna samijščina
language-name-seh = sena
language-name-sel = selkupščina
language-name-ses = koyraboro senni
language-name-sg = sango
language-name-sga = stara irščina
language-name-sh = srbohrvaščina
language-name-shi = tahelitska berberščina
language-name-shn = šanščina
language-name-si = sinhalščina
language-name-sid = sidamščina
language-name-sk = slovaščina
language-name-sl = slovenščina
language-name-sm = samoanščina
language-name-sma = južna samijščina
language-name-smj = luleška samijščina
language-name-smn = inarska samijščina
language-name-sms = samijščina Skolt
language-name-sn = šonščina
language-name-snk = soninke
language-name-so = somalščina
language-name-sq = albanščina
language-name-sr = srbščina
language-name-srn = surinamska kreolščina
language-name-srr = sererščina
language-name-ss = svazijščina
language-name-ssy = saho
language-name-st = sesoto
language-name-su = sundanščina
language-name-suk = sukuma
language-name-sus = susujščina
language-name-sux = sumerščina
language-name-sv = švedščina
language-name-sw = svahili
language-name-swb = šikomor
language-name-syc = klasična sirščina
language-name-syr = sirščina
language-name-ta = tamilščina
language-name-te = telugijščina
language-name-tem = temnejščina
language-name-teo = teso
language-name-tet = tetumščina
language-name-tg = tadžiščina
language-name-th = tajščina
language-name-ti = tigrajščina
language-name-tig = tigrejščina
language-name-tiv = tivščina
language-name-tk = turkmenščina
language-name-tkl = tokelavščina
language-name-tl = tagalogščina
language-name-tlh = klingonščina
language-name-tli = tlingitščina
language-name-tmh = tamajaščina
language-name-tn = cvanščina
language-name-to = tongščina
language-name-tog = malavijska tongščina
language-name-tpi = tok pisin
language-name-tr = turščina
language-name-trv = taroko
language-name-ts = congščina
language-name-tsi = tsimščina
language-name-tt = tatarščina
language-name-tum = tumbukščina
language-name-tvl = tuvalujščina
language-name-tw = tvi
language-name-twq = tasawaq
language-name-ty = tahitščina
language-name-tyv = tuvinščina
language-name-udm = udmurtščina
language-name-ug = ujgurščina
language-name-uga = ugaritski jezik
language-name-uk = ukrajinščina
language-name-umb = umbundščina
language-name-und = neznan jezik
language-name-ur = urdujščina
language-name-uz = uzbeščina
language-name-vai = vajščina
language-name-ve = venda
language-name-vi = vietnamščina
language-name-vo = volapuk
language-name-vot = votjaščina
language-name-vun = vunjo
language-name-wa = valonščina
language-name-wae = walser
language-name-wal = valamščina
language-name-war = varajščina
language-name-was = vašajščina
language-name-wbp = varlpirščina
language-name-wo = volofščina
language-name-xal = kalmiščina
language-name-xh = koščina
language-name-xog = sogščina
language-name-yao = jaojščina
language-name-yap = japščina
language-name-yav = jangben
language-name-ybb = jembajščina
language-name-yi = jidiš
language-name-yo = jorubščina
language-name-yue = kantonščina
language-name-zap = zapoteščina
language-name-zbl = znakovni jezik Bliss
language-name-zen = zenaščina
language-name-zgh = standardni maroški tamazig
language-name-zh = kitajščina
language-name-zh_Hans = poenostavljena kitajščina
language-name-zh_Hant = tradicionalna kitajščina
language-name-zu = zulujščina
language-name-zun = zunijščina
language-name-zxx = brez jezikoslovne vsebine
language-name-zza = zazajščina
