language-name-ar = ʻAlapia
language-name-cy = Wale
language-name-da = Kenemaka
language-name-de = Kelemānia
language-name-el = Helene
language-name-en = Pelekānia
language-name-en_AU = Pelekāne Nū Hōlani
language-name-en_CA = Pelekāne Kanakā
language-name-en_GB = Pelekānia Pekekāne
language-name-en_US = Pelekānia ʻAmelika
language-name-es = Paniolo
language-name-fj = Pīkī
language-name-fr = Palani
language-name-fr_CA = Palani Kanakā
language-name-fr_CH = Kuikilani
language-name-ga = ʻAiliki
language-name-gsw = Kuikilani Kelemānia
language-name-haw = ʻŌlelo Hawaiʻi
language-name-he = Hebera
language-name-it = ʻĪkālia
language-name-ja = Kepanī
language-name-ko = Kōlea
language-name-la = Lākina
language-name-mi = Māori
language-name-nl = Hōlani
language-name-pt = Pukikī
language-name-pt_BR = Pukikī Palakila
language-name-ru = Lūkia
language-name-sm = Kāmoa
language-name-sv = Kuekene
language-name-to = Tonga
language-name-ty = Polapola
language-name-und = ʻIke ʻole ‘ia a kūpono ʻole paha ka ʻōlelo
language-name-vi = Wiekanama
language-name-zh = Pākē
language-name-zh_Hans = Pākē Hoʻomaʻalahi ʻia
language-name-zh_Hant = Pākē Kuʻuna
