language-name-aa = афар
language-name-ab = абхаз
language-name-ace = ачин
language-name-ada = адангмэ
language-name-ady = адигэ
language-name-af = африк
language-name-agq = агем
language-name-ain = айну
language-name-ak = акан
language-name-ale = алют
language-name-alt = өмнөд алтай
language-name-am = амхар
language-name-an = арагон
language-name-anp = ангик
language-name-ar = араб
language-name-ar_001 = стандарт араб
language-name-arn = мапүчи
language-name-arp = арапаго
language-name-as = ассам
language-name-asa = асу
language-name-ast = астури
language-name-av = авар
language-name-awa = авадхи
language-name-ay = аймара
language-name-az = азербайжан
language-name-ba = башкир
language-name-ban = бали
language-name-bas = басаа
language-name-be = беларусь
language-name-bem = бемба
language-name-bez = бена
language-name-bg = болгар
language-name-bho = божпури
language-name-bi = бислам
language-name-bin = бини
language-name-bla = сиксика
language-name-bm = бамбара
language-name-bn = бенгал
language-name-bo = төвд
language-name-br = бретон
language-name-brx = бодо
language-name-bs = босни
language-name-bug = буги
language-name-byn = блин
language-name-ca = каталан
language-name-ce = чечень
language-name-ceb = себуано
language-name-cgg = чига
language-name-ch = чаморро
language-name-chk = чуук
language-name-chm = мари хэл
language-name-cho = чоктау
language-name-chr = чироки
language-name-chy = чэенн
language-name-ckb = төв курд
language-name-co = корсик
language-name-crs = сеселва креолын франц
language-name-cs = чех
language-name-cu = сүмийн славян
language-name-cv = чуваш
language-name-cy = уэльс
language-name-da = дани
language-name-dak = дакота
language-name-dar = даргва
language-name-dav = тайта
language-name-de = герман
language-name-de_AT = австри-герман
language-name-de_CH = швейцари дээр герман
language-name-dgr = догриб
language-name-dje = зарма
language-name-dsb = доод сорби
language-name-dua = дуала
language-name-dv = дивехи
language-name-dyo = жола-фони
language-name-dz = зонха
language-name-dzg = дазага
language-name-ebu = эмбу
language-name-ee = эвэ
language-name-efi = эфик
language-name-eka = экажук
language-name-el = грек
language-name-en = англи
language-name-en_AU = австрали-англи
language-name-en_CA = канад-англи
language-name-en_GB = британи-англи
language-name-en_US = америк-англи
language-name-eo = эсперанто
language-name-es = испани
language-name-et = эстони
language-name-eu = баск
language-name-ewo = эвондо
language-name-fa = перс
language-name-ff = фула
language-name-fi = финлянд
language-name-fil = филиппин
language-name-fj = фижи
language-name-fo = фарер
language-name-fon = фон
language-name-fr = франц
language-name-fr_CA = канад-франц
language-name-fr_CH = швейцари-франц
language-name-fur = фриулан
language-name-fy = баруун фриз
language-name-ga = ирланд
language-name-gaa = га
language-name-gag = гагуз
language-name-gd = шотландын гел
language-name-gez = гийз
language-name-gil = гилберт
language-name-gl = галего
language-name-gn = гуарани
language-name-gor = горонтало
language-name-gsw = швейцари-герман
language-name-gu = гужарати
language-name-guz = гузы
language-name-gv = манкс
language-name-gwi = гвичин
language-name-ha = хауса
language-name-haw = хавай
language-name-he = еврей
language-name-hi = хинди
language-name-hil = хилигайнон
language-name-hmn = хмонг
language-name-hr = хорват
language-name-hsb = дээд сорби
language-name-ht = гаитийн креол
language-name-hu = унгар
language-name-hup = хупа
language-name-hy = армен
language-name-hz = хереро
language-name-ia = интерлингво
language-name-iba = ибан
language-name-ibb = ибибио
language-name-id = индонези
language-name-ie = нэгдмэл хэл
language-name-ig = игбо
language-name-ii = сычуань и
language-name-ilo = илоко
language-name-inh = ингуш
language-name-io = идо
language-name-is = исланд
language-name-it = итали
language-name-iu = инуктитут
language-name-ja = япон
language-name-jbo = ложбан
language-name-jgo = нгомба
language-name-jmc = мачамэ
language-name-jv = ява
language-name-ka = гүрж
language-name-kab = кабиле
language-name-kac = качин
language-name-kaj = жжу
language-name-kam = камба
language-name-kbd = кабардин
language-name-kcg = тяп
language-name-kde = маконде
language-name-kea = кабүвердиану
language-name-kfo = коро
language-name-kha = каси
language-name-khq = койра чини
language-name-ki = кикуюү
language-name-kj = куаньяма
language-name-kk = хасаг
language-name-kkj = како
language-name-kl = калалисут
language-name-kln = каленжин
language-name-km = кхмер
language-name-kmb = кимбунду
language-name-kn = каннада
language-name-ko = солонгос
language-name-koi = коми-пермяк
language-name-kok = конкани
language-name-kpe = кпелле
language-name-kr = канури
language-name-krc = карачай-балкар
language-name-krl = карель
language-name-kru = курук
language-name-ks = кашмир
language-name-ksb = шамбала
language-name-ksf = бафиа
language-name-ksh = кёльш
language-name-ku = курд
language-name-kum = кумук
language-name-kv = коми
language-name-kw = корн
language-name-ky = киргиз
language-name-la = латин
language-name-lad = ладин
language-name-lag = ланги
language-name-lb = люксембург
language-name-lez = лезги
language-name-lg = ганда
language-name-li = лимбург
language-name-lkt = лакота
language-name-ln = лингала
language-name-lo = лаос
language-name-loz = лози
language-name-lrc = хойд лури
language-name-lt = литва
language-name-lu = луба-катанга
language-name-lua = луба-лулуа
language-name-lun = лунда
language-name-luo = луо
language-name-lus = мизо
language-name-luy = луяа
language-name-lv = латви
language-name-mad = мадури хэл
language-name-mag = магахи
language-name-mai = май
language-name-mak = макасар
language-name-mas = масай
language-name-mdf = мокша
language-name-men = менде
language-name-mer = меру
language-name-mfe = морисен
language-name-mg = малагаси
language-name-mgh = макува-мито
language-name-mgo = мета
language-name-mh = маршалл
language-name-mi = маори
language-name-mic = микмак
language-name-min = минангкабау
language-name-mk = македон
language-name-ml = малаялам
language-name-mn = монгол
language-name-mni = манипури
language-name-moh = мохаук
language-name-mos = мосси
language-name-mr = марати
language-name-ms = малай
language-name-mt = малта
language-name-mua = мунданг
language-name-mul = олон хэл
language-name-mus = крик
language-name-mwl = меранди
language-name-my = бирм
language-name-myv = эрзя
language-name-mzn = мазандерани
language-name-na = науру
language-name-nap = неаполитан
language-name-naq = нама
language-name-nb = норвегийн букмол
language-name-nd = хойд ндебеле
language-name-nds_NL = бага саксон
language-name-ne = балба
language-name-new = невари
language-name-ng = ндонга
language-name-nia = ниас хэл
language-name-niu = ниуэ
language-name-nl = нидерланд
language-name-nl_BE = фламанд
language-name-nmg = квазио
language-name-nn = норвегийн нинорск
language-name-nnh = нгиембүүн
language-name-no = норвеги
language-name-nog = ногаи
language-name-nqo = нко
language-name-nr = өмнөд ндебеле
language-name-nso = хойд сото
language-name-nus = нуер
language-name-nv = навахо
language-name-ny = нянжа
language-name-nyn = нянколе
language-name-oc = окситан
language-name-om = оромо
language-name-or = ория
language-name-os = оссетин
language-name-pa = панжаби
language-name-pag = пангасин
language-name-pam = пампанга
language-name-pap = папьяменто
language-name-pau = палау
language-name-pcm = нигерийн пиджин
language-name-pl = польш
language-name-prg = прусс
language-name-ps = пашто
language-name-pt = португал
language-name-qu = кечуа
language-name-quc = киче
language-name-rap = рапануи
language-name-rar = раротонг
language-name-rm = романш
language-name-rn = рунди
language-name-ro = румын
language-name-ro_MD = молдав
language-name-rof = ромбо
language-name-root = рут
language-name-ru = орос
language-name-rup = ароманы
language-name-rw = киньяруанда
language-name-rwk = рва
language-name-sa = санскрит
language-name-sad = сандавэ
language-name-sah = саха
language-name-saq = самбүрү
language-name-sat = сантали
language-name-sba = нгамбай
language-name-sbp = сангү
language-name-sc = сардин
language-name-scn = сицил
language-name-sco = шотланд
language-name-sd = синдхи
language-name-se = хойд сами
language-name-seh = сена
language-name-ses = кёраборо сени
language-name-sg = санго
language-name-sh = хорватын серб
language-name-shi = тачелхит
language-name-shn = шань
language-name-si = синхала
language-name-sk = словак
language-name-sl = словени
language-name-sm = самоа
language-name-sma = өмнөд сами
language-name-smj = люле сами
language-name-smn = инари сами
language-name-sms = сколт сами
language-name-sn = шона
language-name-snk = сонинке
language-name-so = сомали
language-name-sq = албани
language-name-sr = серб
language-name-srn = сранан тонго
language-name-ss = свати
language-name-ssy = сахо
language-name-st = сесото
language-name-su = сундан
language-name-suk = сукума
language-name-sv = швед
language-name-sw = свахили
language-name-sw_CD = конгогийн свахили
language-name-swb = комори
language-name-syr = сири
language-name-ta = тамил
language-name-te = тэлүгү
language-name-tem = тимн
language-name-teo = тэсо
language-name-tet = тетум
language-name-tg = тажик
language-name-th = тай
language-name-ti = тигринья
language-name-tig = тигр
language-name-tk = туркмен
language-name-tlh = клингон
language-name-tn = цвана
language-name-to = тонга
language-name-tpi = ток писин
language-name-tr = турк
language-name-trv = тароко
language-name-ts = цонга
language-name-tt = татар
language-name-tum = тумбула
language-name-tvl = тувалу
language-name-tw = тви
language-name-twq = тасавак
language-name-ty = таити
language-name-tyv = тува
language-name-tzm = төв атласын тамазайт
language-name-udm = удмурт
language-name-ug = уйгур
language-name-uk = украин
language-name-umb = умбунду
language-name-und = Үл мэдэгдэх хэл
language-name-ur = урду
language-name-uz = узбек
language-name-vai = вай
language-name-ve = венда
language-name-vi = вьетнам
language-name-vo = волапюк
language-name-vun = вунжо
language-name-wa = уоллун
language-name-wae = уолсэр
language-name-wal = уоллайтта
language-name-war = варай
language-name-wo = волоф
language-name-xal = халимаг
language-name-xh = хоса
language-name-xog = сога
language-name-yav = янгбен
language-name-ybb = емба
language-name-yi = иддиш
language-name-yo = ёруба
language-name-yue = кантон
language-name-zgh = тамазит
language-name-zh = хятад
language-name-zh_Hans = хялбаршуулсан хятад
language-name-zh_Hant = уламжлалт хятад
language-name-zu = зулу
language-name-zun = зуни
language-name-zxx = хэл зүйн агуулгагүй
language-name-zza = заза
