language-name-aa = 아파르어
language-name-ab = 압카즈어
language-name-ace = 아체어
language-name-ach = 아콜리어
language-name-ada = 아당메어
language-name-ady = 아디게어
language-name-ae = 아베스타어
language-name-aeb = 튀니지 아랍어
language-name-af = 아프리칸스어
language-name-afh = 아프리힐리어
language-name-agq = 아그햄어
language-name-ain = 아이누어
language-name-ak = 아칸어
language-name-akk = 아카드어
language-name-ale = 알류트어
language-name-alt = 남부 알타이어
language-name-am = 암하라어
language-name-an = 아라곤어
language-name-ang = 고대 영어
language-name-anp = 앙가어
language-name-ar = 아랍어
language-name-ar_001 = 현대 표준 아랍어
language-name-arc = 아람어
language-name-arn = 마푸둔군어
language-name-arp = 아라파호어
language-name-arq = 알제리 아랍어
language-name-ars = 나즈디 아랍어
language-name-arw = 아라와크어
language-name-ary = 모로코 아랍어
language-name-arz = 이집트 아랍어
language-name-as = 아삼어
language-name-asa = 아수어
language-name-ast = 아스투리아어
language-name-av = 아바릭어
language-name-awa = 아와히어
language-name-ay = 아이마라어
language-name-az = 아제르바이잔어
language-name-ba = 바슈키르어
language-name-bal = 발루치어
language-name-ban = 발리어
language-name-bas = 바사어
language-name-bax = 바문어
language-name-bbj = 고말라어
language-name-be = 벨라루스어
language-name-bej = 베자어
language-name-bem = 벰바어
language-name-bez = 베나어
language-name-bfd = 바푸트어
language-name-bg = 불가리아어
language-name-bgn = 서부 발로치어
language-name-bho = 호즈푸리어
language-name-bi = 비슬라마어
language-name-bik = 비콜어
language-name-bin = 비니어
language-name-bkm = 콤어
language-name-bla = 식시카어
language-name-bm = 밤바라어
language-name-bn = 벵골어
language-name-bo = 티베트어
language-name-br = 브르타뉴어
language-name-bra = 브라지어
language-name-brh = 브라후이어
language-name-brx = 보도어
language-name-bs = 보스니아어
language-name-bss = 아쿠즈어
language-name-bua = 부리아타
language-name-bug = 부기어
language-name-bum = 불루어
language-name-byn = 브린어
language-name-byv = 메둠바어
language-name-ca = 카탈로니아어
language-name-cad = 카도어
language-name-car = 카리브어
language-name-cay = 카유가어
language-name-cch = 앗삼어
language-name-ce = 체첸어
language-name-ceb = 세부아노어
language-name-cgg = 치가어
language-name-ch = 차모로어
language-name-chb = 치브차어
language-name-chg = 차가타이어
language-name-chk = 추크어
language-name-chm = 마리어
language-name-chn = 치누크 자곤
language-name-cho = 촉토어
language-name-chp = 치페우얀
language-name-chr = 체로키어
language-name-chy = 샤이엔어
language-name-ckb = 소라니 쿠르드어
language-name-co = 코르시카어
language-name-cop = 콥트어
language-name-cr = 크리어
language-name-crh = 크리민 터키어; 크리민 타타르어
language-name-crs = 세이셸 크리올 프랑스어
language-name-cs = 체코어
language-name-csb = 카슈비아어
language-name-cu = 교회 슬라브어
language-name-cv = 추바시어
language-name-cy = 웨일스어
language-name-da = 덴마크어
language-name-dak = 다코타어
language-name-dar = 다르그와어
language-name-dav = 타이타어
language-name-de = 독일어
language-name-del = 델라웨어어
language-name-den = 슬라브어
language-name-dgr = 도그리브어
language-name-din = 딩카어
language-name-dje = 자르마어
language-name-doi = 도그리어
language-name-dsb = 저지 소르비아어
language-name-dua = 두알라어
language-name-dum = 중세 네덜란드어
language-name-dv = 디베히어
language-name-dyo = 졸라 포니어
language-name-dyu = 드율라어
language-name-dz = 종카어
language-name-dzg = 다장가어
language-name-ebu = 엠부어
language-name-ee = 에웨어
language-name-efi = 이픽어
language-name-egy = 고대 이집트어
language-name-eka = 이카죽어
language-name-el = 그리스어
language-name-elx = 엘람어
language-name-en = 영어
language-name-enm = 중세 영어
language-name-eo = 에스페란토어
language-name-es = 스페인어
language-name-et = 에스토니아어
language-name-eu = 바스크어
language-name-ewo = 이원도어
language-name-fa = 페르시아어
language-name-fan = 팡그어
language-name-fat = 판티어
language-name-ff = 풀라어
language-name-fi = 핀란드어
language-name-fil = 필리핀어
language-name-fj = 피지어
language-name-fo = 페로어
language-name-fon = 폰어
language-name-fr = 프랑스어
language-name-frc = 케이준 프랑스어
language-name-frm = 중세 프랑스어
language-name-fro = 고대 프랑스어
language-name-frr = 북부 프리지아어
language-name-frs = 동부 프리슬란드어
language-name-fur = 프리울리어
language-name-fy = 서부 프리지아어
language-name-ga = 아일랜드어
language-name-gaa = 가어
language-name-gag = 가가우스어
language-name-gan = 간어
language-name-gay = 가요어
language-name-gba = 그바야어
language-name-gbz = 조로아스터 다리어
language-name-gd = 스코틀랜드 게일어
language-name-gez = 게이즈어
language-name-gil = 키리바시어
language-name-gl = 갈리시아어
language-name-glk = 길라키어
language-name-gmh = 중세 고지 독일어
language-name-gn = 과라니어
language-name-goh = 고대 고지 독일어
language-name-gom = 고아 콘칸어
language-name-gon = 곤디어
language-name-gor = 고론탈로어
language-name-got = 고트어
language-name-grb = 게르보어
language-name-grc = 고대 그리스어
language-name-gu = 구자라트어
language-name-guz = 구시어
language-name-gv = 맹크스어
language-name-gwi = 그위친어
language-name-ha = 하우사어
language-name-hai = 하이다어
language-name-hak = 하카어
language-name-haw = 하와이어
language-name-he = 히브리어
language-name-hi = 힌디어
language-name-hif = 피지 힌디어
language-name-hil = 헤리가뇬어
language-name-hit = 하타이트어
language-name-hmn = 히몸어
language-name-ho = 히리 모투어
language-name-hr = 크로아티아어
language-name-hsb = 고지 소르비아어
language-name-hsn = 샹어
language-name-ht = 아이티어
language-name-hu = 헝가리어
language-name-hup = 후파어
language-name-hy = 아르메니아어
language-name-hz = 헤레로어
language-name-ia = 인터링구아
language-name-iba = 이반어
language-name-ibb = 이비비오어
language-name-id = 인도네시아어
language-name-ie = 인테르링구에
language-name-ig = 이그보어
language-name-ii = 쓰촨 이어
language-name-ik = 이누피아크어
language-name-ilo = 이로코어
language-name-inh = 인귀시어
language-name-io = 이도어
language-name-is = 아이슬란드어
language-name-it = 이탈리아어
language-name-iu = 이눅티투트어
language-name-ja = 일본어
language-name-jbo = 로반어
language-name-jgo = 응곰바어
language-name-jmc = 마차메어
language-name-jpr = 유대-페르시아어
language-name-jrb = 유대-아라비아어
language-name-jv = 자바어
language-name-ka = 조지아어
language-name-kaa = 카라칼파크어
language-name-kab = 커바일어
language-name-kac = 카친어
language-name-kaj = 까꼬토끄어
language-name-kam = 캄바어
language-name-kaw = 카위어
language-name-kbd = 카바르디어
language-name-kbl = 카넴부어
language-name-kcg = 티얍어
language-name-kde = 마콘데어
language-name-kea = 크리올어
language-name-kfo = 코로어
language-name-kg = 콩고어
language-name-kha = 카시어
language-name-kho = 호탄어
language-name-khq = 코이라 친니어
language-name-khw = 코와르어
language-name-ki = 키쿠유어
language-name-kj = 쿠안야마어
language-name-kk = 카자흐어
language-name-kkj = 카코어
language-name-kl = 그린란드어
language-name-kln = 칼렌진어
language-name-km = 크메르어
language-name-kmb = 킴분두어
language-name-kn = 칸나다어
language-name-ko = 한국어
language-name-koi = 코미페르먀크어
language-name-kok = 코카니어
language-name-kos = 코스라이엔어
language-name-kpe = 크펠레어
language-name-kr = 칸누리어
language-name-krc = 카라챠이-발카르어
language-name-krl = 카렐리야어
language-name-kru = 쿠르크어
language-name-ks = 카슈미르어
language-name-ksb = 샴발라어
language-name-ksf = 바피아어
language-name-ksh = 콜로그니안어
language-name-ku = 쿠르드어
language-name-kum = 쿠믹어
language-name-kut = 쿠테네어
language-name-kv = 코미어
language-name-kw = 콘월어
language-name-ky = 키르기스어
language-name-la = 라틴어
language-name-lad = 라디노어
language-name-lag = 랑기어
language-name-lah = 라한다어
language-name-lam = 람바어
language-name-lb = 룩셈부르크어
language-name-lez = 레즈기안어
language-name-lfn = 링구아 프랑카 노바
language-name-lg = 간다어
language-name-li = 림버거어
language-name-lkt = 라코타어
language-name-ln = 링갈라어
language-name-lo = 라오어
language-name-lol = 몽고어
language-name-lou = 루이지애나 크리올어
language-name-loz = 로지어
language-name-lrc = 북부 루리어
language-name-lt = 리투아니아어
language-name-lu = 루바-카탄가어
language-name-lua = 루바-룰루아어
language-name-lui = 루이세노어
language-name-lun = 룬다어
language-name-luo = 루오어
language-name-lus = 루샤이어
language-name-luy = 루야어
language-name-lv = 라트비아어
language-name-mad = 마두라어
language-name-maf = 마파어
language-name-mag = 마가히어
language-name-mai = 마이틸리어
language-name-mak = 마카사어
language-name-man = 만딩고어
language-name-mas = 마사이어
language-name-mde = 마바어
language-name-mdf = 모크샤어
language-name-mdr = 만다르어
language-name-men = 멘데어
language-name-mer = 메루어
language-name-mfe = 모리스얀어
language-name-mg = 말라가시어
language-name-mga = 중세 아일랜드어
language-name-mgh = 마크후와-메토어
language-name-mgo = 메타어
language-name-mh = 마셜어
language-name-mi = 마오리어
language-name-mic = 미크맥어
language-name-min = 미낭카바우어
language-name-mk = 마케도니아어
language-name-ml = 말라얄람어
language-name-mn = 몽골어
language-name-mnc = 만주어
language-name-mni = 마니푸리어
language-name-moh = 모호크어
language-name-mos = 모시어
language-name-mr = 마라티어
language-name-mrj = 서부 마리어
language-name-ms = 말레이어
language-name-mt = 몰타어
language-name-mua = 문당어
language-name-mul = 다중 언어
language-name-mus = 크리크어
language-name-mwl = 미란데어
language-name-mwr = 마르와리어
language-name-my = 버마어
language-name-mye = 미예네어
language-name-myv = 엘즈야어
language-name-mzn = 마잔데라니어
language-name-na = 나우루어
language-name-nan = 민난어
language-name-nap = 나폴리어
language-name-naq = 나마어
language-name-nd = 북부 은데벨레어
language-name-nds = 저지 독일어
language-name-nds_NL = 저지 색슨어
language-name-ne = 네팔어
language-name-new = 네와르어
language-name-ng = 느동가어
language-name-nia = 니아스어
language-name-niu = 니웨언어
language-name-nl = 네덜란드어
language-name-nl_BE = 플라망어
language-name-nmg = 크와시오어
language-name-nnh = 느기엠본어
language-name-no = 노르웨이어
language-name-nog = 노가이어
language-name-non = 고대 노르웨이어
language-name-nqo = 응코어
language-name-nr = 남부 은데벨레어
language-name-nso = 북부 소토어
language-name-nus = 누에르어
language-name-nv = 나바호어
language-name-nwc = 고전 네와르어
language-name-ny = 냔자어
language-name-nym = 니암웨지어
language-name-nyn = 니안콜어
language-name-nyo = 뉴로어
language-name-nzi = 느지마어
language-name-oc = 오크어
language-name-oj = 오지브와어
language-name-om = 오로모어
language-name-or = 오리야어
language-name-os = 오세트어
language-name-osa = 오세이지어
language-name-ota = 오스만 터키어
language-name-pa = 펀잡어
language-name-pag = 판가시난어
language-name-pal = 팔레비어
language-name-pam = 팜팡가어
language-name-pap = 파피아먼토어
language-name-pau = 팔라우어
language-name-pcm = 나이지리아 피진어
language-name-peo = 고대 페르시아어
language-name-phn = 페니키아어
language-name-pi = 팔리어
language-name-pl = 폴란드어
language-name-pnt = 폰틱어
language-name-pon = 폼페이어
language-name-prg = 프러시아어
language-name-pro = 고대 프로방스어
language-name-ps = 파슈토어
language-name-pt = 포르투갈어
language-name-qu = 케추아어
language-name-quc = 키체어
language-name-raj = 라자스탄어
language-name-rap = 라파뉴이
language-name-rar = 라로통가어
language-name-rm = 로만시어
language-name-rn = 룬디어
language-name-ro = 루마니아어
language-name-ro_MD = 몰도바어
language-name-rof = 롬보어
language-name-rom = 집시어
language-name-root = 어근
language-name-ru = 러시아어
language-name-rue = 루신어
language-name-rup = 아로마니아어
language-name-rw = 르완다어
language-name-rwk = 르와어
language-name-sa = 산스크리트어
language-name-sad = 산다웨어
language-name-sah = 야쿠트어
language-name-sam = 사마리아 아랍어
language-name-saq = 삼부루어
language-name-sas = 사사크어
language-name-sat = 산탈리어
language-name-sba = 느감바이어
language-name-sbp = 상구어
language-name-sc = 사르디니아어
language-name-scn = 시칠리아어
language-name-sco = 스코틀랜드어
language-name-sd = 신디어
language-name-sdh = 남부 쿠르드어
language-name-se = 북부 사미어
language-name-see = 세네카어
language-name-seh = 세나어
language-name-sel = 셀쿠프어
language-name-ses = 코이야보로 세니어
language-name-sg = 산고어
language-name-sga = 고대 아일랜드어
language-name-sh = 세르비아-크로아티아어
language-name-shi = 타셸히트어
language-name-shn = 샨어
language-name-shu = 차디언 아라비아어
language-name-si = 스리랑카어
language-name-sid = 시다모어
language-name-sk = 슬로바키아어
language-name-sl = 슬로베니아어
language-name-sm = 사모아어
language-name-sma = 남부 사미어
language-name-smj = 룰레 사미어
language-name-smn = 이나리 사미어
language-name-sms = 스콜트 사미어
language-name-sn = 쇼나어
language-name-snk = 소닌케어
language-name-so = 소말리아어
language-name-sog = 소그디엔어
language-name-sq = 알바니아어
language-name-sr = 세르비아어
language-name-srn = 스라난 통가어
language-name-srr = 세레르어
language-name-ss = 시스와티어
language-name-ssy = 사호어
language-name-st = 남부 소토어
language-name-su = 순다어
language-name-suk = 수쿠마어
language-name-sus = 수수어
language-name-sux = 수메르어
language-name-sv = 스웨덴어
language-name-sw = 스와힐리어
language-name-sw_CD = 콩고 스와힐리어
language-name-swb = 코모로어
language-name-syc = 고전 시리아어
language-name-syr = 시리아어
language-name-ta = 타밀어
language-name-te = 텔루구어
language-name-tem = 팀니어
language-name-teo = 테조어
language-name-ter = 테레노어
language-name-tet = 테툼어
language-name-tg = 타지크어
language-name-th = 태국어
language-name-ti = 티그리냐어
language-name-tig = 티그레어
language-name-tiv = 티브어
language-name-tk = 투르크멘어
language-name-tkl = 토켈라우제도어
language-name-tkr = 차후르어
language-name-tl = 타갈로그어
language-name-tlh = 클링온어
language-name-tli = 틀링깃족어
language-name-tly = 탈리쉬어
language-name-tmh = 타마섹어
language-name-tn = 츠와나어
language-name-to = 통가어
language-name-tog = 니아사 통가어
language-name-tpi = 토크 피신어
language-name-tr = 터키어
language-name-trv = 타로코어
language-name-ts = 총가어
language-name-tsi = 트심시안어
language-name-tt = 타타르어
language-name-tum = 툼부카어
language-name-tvl = 투발루어
language-name-tw = 트위어
language-name-twq = 타사와크어
language-name-ty = 타히티어
language-name-tyv = 투비니안어
language-name-tzm = 중앙 모로코 타마지트어
language-name-udm = 우드말트어
language-name-ug = 위구르어
language-name-uga = 유가리틱어
language-name-uk = 우크라이나어
language-name-umb = 움분두어
language-name-und = 알 수 없는 언어
language-name-ur = 우르두어
language-name-uz = 우즈베크어
language-name-vai = 바이어
language-name-ve = 벤다어
language-name-vi = 베트남어
language-name-vo = 볼라퓌크어
language-name-vot = 보틱어
language-name-vun = 분조어
language-name-wa = 왈론어
language-name-wae = 월저어
language-name-wal = 월라이타어
language-name-war = 와라이어
language-name-was = 와쇼어
language-name-wbp = 왈피리어
language-name-wo = 월로프어
language-name-wuu = 우어
language-name-xal = 칼미크어
language-name-xh = 코사어
language-name-xog = 소가어
language-name-yao = 야오족어
language-name-yap = 얍페세어
language-name-yav = 양본어
language-name-ybb = 옘바어
language-name-yi = 이디시어
language-name-yo = 요루바어
language-name-yue = 광둥어
language-name-za = 주앙어
language-name-zap = 사포테크어
language-name-zbl = 블리스 심볼
language-name-zen = 제나가어
language-name-zgh = 표준 모로코 타마지트어
language-name-zh = 중국어
language-name-zu = 줄루어
language-name-zun = 주니어
language-name-zxx = 언어 관련 내용 없음
language-name-zza = 자자어
