language-name-aa = अफ़ार
language-name-ab = अब्ख़ाज़ियन
language-name-ace = अचाइनीस
language-name-ach = अकोली
language-name-ada = अदान्गमे
language-name-ady = अदिघे
language-name-ae = अवस्ताई
language-name-af = अफ़्रीकी
language-name-afh = अफ्रिहिली
language-name-agq = अग्हेम
language-name-ain = ऐनू
language-name-ak = अकन
language-name-akk = अक्कादी
language-name-ale = अलेउत
language-name-alt = दक्षिणी अल्ताई
language-name-am = अम्हेरी
language-name-an = अर्गोनी
language-name-ang = पुरानी अंग्रेज़ी
language-name-anp = अंगिका
language-name-ar = अरबी
language-name-ar_001 = आधुनिक मानक अरबी
language-name-arc = ऐरेमेक
language-name-arn = मापूचे
language-name-arp = अरापाहो
language-name-ars = नज्दी अरबी
language-name-arw = अरावक
language-name-as = असमिया
language-name-asa = असु
language-name-ast = अस्तुरियन
language-name-av = अवेरिक
language-name-awa = अवधी
language-name-ay = आयमारा
language-name-az = अज़रबैजानी
language-name-ba = बशख़िर
language-name-bal = बलूची
language-name-ban = बालिनीस
language-name-bas = बसा
language-name-be = बेलारूसी
language-name-bej = बेजा
language-name-bem = बेम्बा
language-name-bez = बेना
language-name-bg = बुल्गारियाई
language-name-bgn = पश्चिमी बलोची
language-name-bho = भोजपुरी
language-name-bi = बिस्लामा
language-name-bik = बिकोल
language-name-bin = बिनी
language-name-bla = सिक्सिका
language-name-bm = बाम्बारा
language-name-bn = बंगाली
language-name-bo = तिब्बती
language-name-br = ब्रेटन
language-name-bra = ब्रज
language-name-brx = बोडो
language-name-bs = बोस्नियाई
language-name-bua = बुरियात
language-name-bug = बगिनीस
language-name-byn = ब्लिन
language-name-ca = कातालान
language-name-cad = कैड्डो
language-name-car = कैरिब
language-name-cch = अत्सम
language-name-ce = चेचन
language-name-ceb = सिबुआनो
language-name-cgg = शिगा
language-name-ch = कमोरो
language-name-chb = चिब्चा
language-name-chg = छगाताई
language-name-chk = चूकीस
language-name-chm = मारी
language-name-chn = चिनूक जारगॉन
language-name-cho = चोक्तौ
language-name-chp = शिपेव्यान
language-name-chr = चेरोकी
language-name-chy = शेयेन्न
language-name-ckb = सोरानी कुर्दिश
language-name-co = कोर्सीकन
language-name-cop = कॉप्टिक
language-name-cr = क्री
language-name-crh = क्रीमीन तुर्की
language-name-crs = सेसेल्वा क्रिओल फ्रेंच
language-name-cs = चेक
language-name-csb = काशुबियन
language-name-cu = चर्च साल्विक
language-name-cv = चूवाश
language-name-cy = वेल्श
language-name-da = डेनिश
language-name-dak = दाकोता
language-name-dar = दार्गवा
language-name-dav = तैता
language-name-de = जर्मन
language-name-de_AT = ऑस्ट्रियाई जर्मन
language-name-de_CH = स्विस उच्च जर्मन
language-name-del = डिलैवेयर
language-name-den = स्लेव
language-name-dgr = डोग्रिब
language-name-din = दिन्का
language-name-dje = झार्मा
language-name-doi = डोग्री
language-name-dsb = निचला सॉर्बियन
language-name-dua = दुआला
language-name-dum = मध्यकालीन पुर्तगाली
language-name-dv = दिवेही
language-name-dyo = जोला-फोंई
language-name-dyu = ड्युला
language-name-dz = ज़ोन्गखा
language-name-dzg = दज़ागा
language-name-ebu = एम्बु
language-name-ee = ईवे
language-name-efi = एफिक
language-name-egy = प्राचीन मिस्री
language-name-eka = एकाजुक
language-name-el = यूनानी
language-name-elx = एलामाइट
language-name-en = अंग्रेज़ी
language-name-en_AU = ऑस्ट्रेलियाई अंग्रेज़ी
language-name-en_CA = कनाडाई अंग्रेज़ी
language-name-en_GB = ब्रिटिश अंग्रेज़ी
language-name-en_US = अमेरिकी अंग्रेज़ी
language-name-enm = मध्यकालीन अंग्रेज़ी
language-name-eo = एस्पेरेंतो
language-name-es = स्पेनी
language-name-es_419 = लैटिन अमेरिकी स्पेनिश
language-name-es_ES = यूरोपीय स्पेनिश
language-name-es_MX = मैक्सिकन स्पेनिश
language-name-et = एस्टोनियाई
language-name-eu = बास्क
language-name-ewo = इवोन्डो
language-name-fa = फ़ारसी
language-name-fan = फैन्ग
language-name-fat = फन्टी
language-name-ff = फुलाह
language-name-fi = फ़िनिश
language-name-fil = फ़िलिपीनो
language-name-fj = फिजियन
language-name-fo = फ़ैरोइज़
language-name-fon = फॉन
language-name-fr = फ़्रेंच
language-name-fr_CA = कनाडाई फ़्रेंच
language-name-fr_CH = स्विस फ़्रेंच
language-name-frc = केजन फ़्रेंच
language-name-frm = मध्यकालीन फ़्रांसीसी
language-name-fro = पुरातन फ़्रांसीसी
language-name-frr = उत्तरी फ़्रीसियाई
language-name-frs = पूर्वी फ़्रीसियाई
language-name-fur = फ्रीयुलीयान
language-name-fy = पश्चिमी फ़्रिसियाई
language-name-ga = आइरिश
language-name-gaa = गा
language-name-gag = गागौज़
language-name-gay = गायो
language-name-gba = ग्बाया
language-name-gd = स्कॉटिश गाएलिक
language-name-gez = गीज़
language-name-gil = गिल्बरतीस
language-name-gl = गैलिशियन
language-name-gmh = मध्यकालीन हाइ जर्मन
language-name-gn = गुआरानी
language-name-goh = पुरातन हाइ जर्मन
language-name-gon = गाँडी
language-name-gor = गोरोन्तालो
language-name-got = गॉथिक
language-name-grb = ग्रेबो
language-name-grc = प्राचीन यूनानी
language-name-gsw = स्विस जर्मन
language-name-gu = गुजराती
language-name-guz = गुसी
language-name-gv = मैंक्स
language-name-gwi = ग्विचइन
language-name-ha = हौसा
language-name-hai = हैडा
language-name-haw = हवाई
language-name-he = हिब्रू
language-name-hi = हिन्दी
language-name-hil = हिलिगेनन
language-name-hit = हिताइत
language-name-hmn = ह्मॉंग
language-name-ho = हिरी मोटू
language-name-hr = क्रोएशियाई
language-name-hsb = ऊपरी सॉर्बियन
language-name-ht = हैतियाई
language-name-hu = हंगेरियाई
language-name-hup = हूपा
language-name-hy = आर्मेनियाई
language-name-hz = हरैरो
language-name-ia = इंटरलिंगुआ
language-name-iba = इबान
language-name-ibb = इबिबियो
language-name-id = इंडोनेशियाई
language-name-ie = ईन्टरलिंगुइ
language-name-ig = ईग्बो
language-name-ii = सिचुआन यी
language-name-ik = इनुपियाक्
language-name-ilo = इलोको
language-name-inh = इंगुश
language-name-io = इडौ
language-name-is = आइसलैंडिक
language-name-it = इतालवी
language-name-iu = इनूकीटूत्
language-name-ja = जापानी
language-name-jbo = लोज्बान
language-name-jgo = नगोंबा
language-name-jmc = मैकहैमे
language-name-jpr = जुदेओ-पर्शियन
language-name-jrb = जुदेओ-अरेबिक
language-name-jv = जावानीज़
language-name-ka = जॉर्जियाई
language-name-kaa = कारा-कल्पक
language-name-kab = कबाइल
language-name-kac = काचिन
language-name-kaj = ज्जु
language-name-kam = कम्बा
language-name-kaw = कावी
language-name-kbd = कबार्डियन
language-name-kcg = त्याप
language-name-kde = मैकोंड
language-name-kea = काबुवेर्दियानु
language-name-kfo = कोरो
language-name-kg = कोंगो
language-name-kha = खासी
language-name-kho = खोतानीस
language-name-khq = कोयरा चीनी
language-name-ki = किकुयू
language-name-kj = क्वान्यामा
language-name-kk = कज़ाख़
language-name-kkj = काको
language-name-kl = कलालीसुत
language-name-kln = कलेंजिन
language-name-km = खमेर
language-name-kmb = किम्बन्दु
language-name-kn = कन्नड़
language-name-ko = कोरियाई
language-name-koi = कोमी-पर्मयाक
language-name-kok = कोंकणी
language-name-kos = कोसरैन
language-name-kpe = क्पेल
language-name-kr = कनुरी
language-name-krc = कराचय-बल्कार
language-name-krl = करेलियन
language-name-kru = कुरूख
language-name-ks = कश्मीरी
language-name-ksb = शम्बाला
language-name-ksf = बफिआ
language-name-ksh = कोलोनियाई
language-name-ku = कुर्दिश
language-name-kum = कुमीक
language-name-kut = क्यूतनाई
language-name-kv = कोमी
language-name-kw = कोर्निश
language-name-ky = किर्गीज़
language-name-la = लैटिन
language-name-lad = लादीनो
language-name-lag = लांगि
language-name-lah = लाह्न्डा
language-name-lam = लाम्बा
language-name-lb = लग्ज़मबर्गी
language-name-lez = लेज़्घीयन
language-name-lg = गांडा
language-name-li = लिंबर्गिश
language-name-lkt = लैकोटा
language-name-ln = लिंगाला
language-name-lo = लाओ
language-name-lol = मोंगो
language-name-lou = लुईज़ियाना क्रियोल
language-name-loz = लोज़ी
language-name-lrc = उत्तरी लूरी
language-name-lt = लिथुआनियाई
language-name-lu = ल्यूबा-कटांगा
language-name-lua = ल्यूबा-लुलुआ
language-name-lui = लुइसेनो
language-name-lun = लुन्डा
language-name-luo = ल्युओ
language-name-lus = मिज़ो
language-name-luy = ल्युईआ
language-name-lv = लातवियाई
language-name-mad = मादुरीस
language-name-mag = मगही
language-name-mai = मैथिली
language-name-mak = मकासर
language-name-man = मन्डिन्गो
language-name-mas = मसाई
language-name-mdf = मोक्ष
language-name-mdr = मंदार
language-name-men = मेन्डे
language-name-mer = मेरु
language-name-mfe = मोरीस्येन
language-name-mg = मालागासी
language-name-mga = मध्यकालीन आइरिश
language-name-mgh = मैखुवा-मीट्टो
language-name-mgo = मेटा
language-name-mh = मार्शलीज़
language-name-mi = माओरी
language-name-mic = मिकमैक
language-name-min = मिनांग्काबाउ
language-name-mk = मकदूनियाई
language-name-ml = मलयालम
language-name-mn = मंगोलियाई
language-name-mnc = मन्चु
language-name-mni = मणिपुरी
language-name-moh = मोहौक
language-name-mos = मोस्सी
language-name-mr = मराठी
language-name-ms = मलय
language-name-mt = माल्टीज़
language-name-mua = मुंडैंग
language-name-mul = एकाधिक भाषाएँ
language-name-mus = क्रीक
language-name-mwl = मिरांडी
language-name-mwr = मारवाड़ी
language-name-my = बर्मीज़
language-name-myv = एर्ज़या
language-name-mzn = माज़न्देरानी
language-name-na = नाउरू
language-name-nan = nan
language-name-nap = नीपोलिटन
language-name-naq = नामा
language-name-nb = नॉर्वेजियाई बोकमाल
language-name-nd = उत्तरी देबेल
language-name-nds = निचला जर्मन
language-name-nds_NL = निचली सैक्सन
language-name-ne = नेपाली
language-name-new = नेवाड़ी
language-name-ng = डोन्गा
language-name-nia = नियास
language-name-niu = नियुआन
language-name-nl = डच
language-name-nl_BE = फ़्लेमिश
language-name-nmg = क्वासिओ
language-name-nn = नॉर्वेजियाई नॉयनॉर्स्क
language-name-nnh = गैम्बू
language-name-no = नॉर्वेजियाई
language-name-nog = नोगाई
language-name-non = पुराना नॉर्स
language-name-nqo = एन्को
language-name-nr = दक्षिण देबेल
language-name-nso = उत्तरी सोथो
language-name-nus = नुएर
language-name-nv = नावाजो
language-name-nwc = पारम्परिक नेवारी
language-name-ny = न्यानजा
language-name-nym = न्यामवेज़ी
language-name-nyn = न्यानकोल
language-name-nyo = न्योरो
language-name-nzi = न्ज़ीमा
language-name-oc = ओसीटान
language-name-oj = ओजिब्वा
language-name-om = ओरोमो
language-name-or = उड़िया
language-name-os = ओस्सेटिक
language-name-osa = ओसेज
language-name-ota = ओटोमान तुर्किश
language-name-pa = पंजाबी
language-name-pag = पंगासीनान
language-name-pal = पाह्लावी
language-name-pam = पाम्पान्गा
language-name-pap = पापियामेन्टो
language-name-pau = पलोउआन
language-name-pcm = नाइजीरियाई पिडगिन
language-name-peo = पुरानी फारसी
language-name-phn = फोएनिशियन
language-name-pi = पाली
language-name-pl = पोलिश
language-name-pon = पोह्नपिएन
language-name-prg = प्रुशियाई
language-name-pro = पुरानी प्रोवेन्सल
language-name-ps = पश्तो
language-name-pt = पुर्तगाली
language-name-pt_BR = ब्राज़ीली पुर्तगाली
language-name-pt_PT = यूरोपीय पुर्तगाली
language-name-qu = क्वेचुआ
language-name-quc = किश
language-name-raj = राजस्थानी
language-name-rap = रापानुई
language-name-rar = रारोतोंगन
language-name-rm = रोमान्श
language-name-rn = रुन्दी
language-name-ro = रोमानियाई
language-name-ro_MD = मोलडावियन
language-name-rof = रोम्बो
language-name-rom = रोमानी
language-name-root = रूट
language-name-ru = रूसी
language-name-rup = अरोमानियन
language-name-rw = किन्यारवांडा
language-name-rwk = रवा
language-name-sa = संस्कृत
language-name-sad = सन्डावे
language-name-sah = याकूत
language-name-sam = सामैरिटन अरैमिक
language-name-saq = सैम्बुरु
language-name-sas = सासाक
language-name-sat = संथाली
language-name-sba = न्गाम्बे
language-name-sbp = सैंगु
language-name-sc = सार्दिनियन
language-name-scn = सिसिलियन
language-name-sco = स्कॉट्स
language-name-sd = सिंधी
language-name-sdh = दक्षिणी कार्डिश
language-name-se = नॉर्दन सामी
language-name-seh = सेना
language-name-sel = सेल्कप
language-name-ses = कोयराबोरो सेन्नी
language-name-sg = सांगो
language-name-sga = पुरानी आइरिश
language-name-sh = सेर्बो-क्रोएशियाई
language-name-shi = तैचेल्हित
language-name-shn = शैन
language-name-si = सिंहली
language-name-sid = सिदामो
language-name-sk = स्लोवाक
language-name-sl = स्लोवेनियाई
language-name-sm = सामोन
language-name-sma = दक्षिणी सामी
language-name-smj = ल्युल सामी
language-name-smn = इनारी सामी
language-name-sms = स्कोल्ट सामी
language-name-sn = शोणा
language-name-snk = सोनिन्के
language-name-so = सोमाली
language-name-sog = सोग्डिएन
language-name-sq = अल्बानियाई
language-name-sr = सर्बियाई
language-name-srn = स्रानान टॉन्गो
language-name-srr = सेरेर
language-name-ss = स्वाती
language-name-ssy = साहो
language-name-st = दक्षिणी सेसेथो
language-name-su = सुंडानी
language-name-suk = सुकुमा
language-name-sus = सुसु
language-name-sux = सुमेरियन
language-name-sv = स्वीडिश
language-name-sw = स्वाहिली
language-name-sw_CD = कांगो स्वाहिली
language-name-swb = कोमोरियन
language-name-syc = क्लासिकल सिरिएक
language-name-syr = सिरिएक
language-name-ta = तमिल
language-name-te = तेलुगू
language-name-tem = टिम्ने
language-name-teo = टेसो
language-name-ter = तेरेनो
language-name-tet = तेतुम
language-name-tg = ताजिक
language-name-th = थाई
language-name-ti = तिग्रीन्या
language-name-tig = टाइग्रे
language-name-tiv = तिव
language-name-tk = तुर्कमेन
language-name-tkl = तोकेलाऊ
language-name-tl = टैगलॉग
language-name-tlh = क्लिंगन
language-name-tli = त्लिंगित
language-name-tmh = तामाशेक
language-name-tn = सेत्स्वाना
language-name-to = टोंगन
language-name-tog = न्यासा टोन्गा
language-name-tpi = टोक पिसिन
language-name-tr = तुर्की
language-name-trv = तारोको
language-name-ts = सोंगा
language-name-tsi = त्सिमीशियन
language-name-tt = तातार
language-name-tum = तम्बूका
language-name-tvl = तुवालु
language-name-tw = ट्वी
language-name-twq = टासवाक
language-name-ty = ताहितियन
language-name-tyv = तुवीनियन
language-name-tzm = मध्य एटलस तमाज़ित
language-name-udm = उदमुर्त
language-name-ug = विघुर
language-name-uga = युगैरिटिक
language-name-uk = यूक्रेनियाई
language-name-umb = उम्बुन्डु
language-name-und = अज्ञात भाषा
language-name-ur = उर्दू
language-name-uz = उज़्बेक
language-name-vai = वाई
language-name-ve = वेन्दा
language-name-vi = वियतनामी
language-name-vo = वोलापुक
language-name-vot = वॉटिक
language-name-vun = वुंजो
language-name-wa = वाल्लून
language-name-wae = वाल्सर
language-name-wal = वलामो
language-name-war = वारै
language-name-was = वाशो
language-name-wbp = वॉल्पेरी
language-name-wo = वोलोफ़
language-name-wuu = वू चीनी
language-name-xal = काल्मिक
language-name-xh = ख़ोसा
language-name-xog = सोगा
language-name-yao = याओ
language-name-yap = यापीस
language-name-yav = यांगबेन
language-name-ybb = येंबा
language-name-yi = यहूदी
language-name-yo = योरूबा
language-name-yue = कैंटोनीज़
language-name-za = ज़ुआंग
language-name-zap = ज़ेपोटेक
language-name-zbl = ब्लिसिम्बॉल्स
language-name-zen = ज़ेनान्गा
language-name-zgh = मानक मोरक्कन तामाज़ाइट
language-name-zh = चीनी
language-name-zh_Hans = सरलीकृत चीनी
language-name-zh_Hant = पारंपरिक चीनी
language-name-zu = ज़ुलू
language-name-zun = ज़ूनी
language-name-zxx = कोई भाषा सामग्री नहीं
language-name-zza = ज़ाज़ा
