language-name-aa = Afar
language-name-ab = Abkhazian
language-name-ace = Achinese
language-name-ach = Acoli
language-name-ada = Adangme
language-name-ady = Adyghe
language-name-af = Afrikaans
language-name-agq = Aghem
language-name-ain = Ainu
language-name-ak = Akan
language-name-ale = Aleut
language-name-alt = Southern Altai
language-name-am = Amharic
language-name-an = Aragonese
language-name-anp = Angika
language-name-ar = Arabic
language-name-ar_001 = Modernong Karaniwang Arabic
language-name-arn = Mapuche
language-name-arp = Arapaho
language-name-as = Assamese
language-name-asa = Asu
language-name-ast = Asturian
language-name-av = Avaric
language-name-awa = Awadhi
language-name-ay = Aymara
language-name-az = Azerbaijani
language-name-ba = Bashkir
language-name-ban = Balinese
language-name-bas = Basaa
language-name-be = Belarusian
language-name-bem = Bemba
language-name-bez = Bena
language-name-bg = Bulgarian
language-name-bgn = Kanlurang Balochi
language-name-bho = Bhojpuri
language-name-bi = Bislama
language-name-bin = Bini
language-name-bla = Siksika
language-name-bm = Bambara
language-name-bn = Bangla
language-name-bo = Tibetan
language-name-br = Breton
language-name-brx = Bodo
language-name-bs = Bosnian
language-name-bug = Buginese
language-name-byn = Blin
language-name-ca = Catalan
language-name-ce = Chechen
language-name-ceb = Cebuano
language-name-cgg = Chiga
language-name-ch = Chamorro
language-name-chk = Chuukese
language-name-chm = Mari
language-name-cho = Choctaw
language-name-chr = Cherokee
language-name-chy = Cheyenne
language-name-ckb = Central Kurdish
language-name-co = Corsican
language-name-crs = Seselwa Creole French
language-name-cs = Czech
language-name-cu = Church Slavic
language-name-cv = Chuvash
language-name-cy = Welsh
language-name-da = Danish
language-name-dak = Dakota
language-name-dar = Dargwa
language-name-dav = Taita
language-name-de = German
language-name-de_AT = Austrian German
language-name-de_CH = Swiss High German
language-name-dgr = Dogrib
language-name-dje = Zarma
language-name-dsb = Lower Sorbian
language-name-dua = Duala
language-name-dv = Divehi
language-name-dyo = Jola-Fonyi
language-name-dz = Dzongkha
language-name-dzg = Dazaga
language-name-ebu = Embu
language-name-ee = Ewe
language-name-efi = Efik
language-name-eka = Ekajuk
language-name-el = Greek
language-name-en = Ingles
language-name-en_AU = Ingles ng Australya
language-name-en_CA = Ingles sa Canada
language-name-en_GB = Ingles na British
language-name-en_US = Ingles na American
language-name-eo = Esperanto
language-name-es = Spanish
language-name-es_419 = Latin American na Espanyol
language-name-es_ES = European Spanish
language-name-es_MX = Mexican na Espanyol
language-name-et = Estonian
language-name-eu = Basque
language-name-ewo = Ewondo
language-name-fa = Persian
language-name-ff = Fulah
language-name-fi = Finnish
language-name-fil = Filipino
language-name-fj = Fijian
language-name-fo = Faroese
language-name-fon = Fon
language-name-fr = French
language-name-fr_CA = French sa Canada
language-name-fr_CH = Swiss na French
language-name-frc = Cajun French
language-name-fur = Friulian
language-name-fy = Kanlurang Frisian
language-name-ga = Irish
language-name-gaa = Ga
language-name-gag = Gagauz
language-name-gd = Scottish Gaelic
language-name-gez = Geez
language-name-gil = Gilbertese
language-name-gl = Galician
language-name-gn = Guarani
language-name-gor = Gorontalo
language-name-gsw = Swiss German
language-name-gu = Gujarati
language-name-guz = Gusii
language-name-gv = Manx
language-name-gwi = Gwichʼin
language-name-ha = Hausa
language-name-haw = Hawaiian
language-name-he = Hebrew
language-name-hi = Hindi
language-name-hil = Hiligaynon
language-name-hmn = Hmong
language-name-hr = Croatian
language-name-hsb = Upper Sorbian
language-name-ht = Haitian
language-name-hu = Hungarian
language-name-hup = Hupa
language-name-hy = Armenian
language-name-hz = Herero
language-name-ia = Interlingua
language-name-iba = Iban
language-name-ibb = Ibibio
language-name-id = Indonesian
language-name-ie = Interlingue
language-name-ig = Igbo
language-name-ii = Sichuan Yi
language-name-ilo = Iloko
language-name-inh = Ingush
language-name-io = Ido
language-name-is = Icelandic
language-name-it = Italian
language-name-iu = Inuktitut
language-name-ja = Japanese
language-name-jbo = Lojban
language-name-jgo = Ngomba
language-name-jmc = Machame
language-name-jv = Javanese
language-name-ka = Georgian
language-name-kab = Kabyle
language-name-kac = Kachin
language-name-kaj = Jju
language-name-kam = Kamba
language-name-kbd = Kabardian
language-name-kcg = Tyap
language-name-kde = Makonde
language-name-kea = Kabuverdianu
language-name-kfo = Koro
language-name-kg = Kongo
language-name-kha = Khasi
language-name-khq = Koyra Chiini
language-name-ki = Kikuyu
language-name-kj = Kuanyama
language-name-kk = Kazakh
language-name-kkj = Kako
language-name-kl = Kalaallisut
language-name-kln = Kalenjin
language-name-km = Khmer
language-name-kmb = Kimbundu
language-name-kn = Kannada
language-name-ko = Korean
language-name-koi = Komi-Permyak
language-name-kok = Konkani
language-name-kpe = Kpelle
language-name-kr = Kanuri
language-name-krc = Karachay-Balkar
language-name-krl = Karelian
language-name-kru = Kurukh
language-name-ks = Kashmiri
language-name-ksb = Shambala
language-name-ksf = Bafia
language-name-ksh = Colognian
language-name-ku = Kurdish
language-name-kum = Kumyk
language-name-kv = Komi
language-name-kw = Cornish
language-name-ky = Kirghiz
language-name-la = Latin
language-name-lad = Ladino
language-name-lag = Langi
language-name-lb = Luxembourgish
language-name-lez = Lezghian
language-name-lg = Ganda
language-name-li = Limburgish
language-name-lkt = Lakota
language-name-ln = Lingala
language-name-lo = Lao
language-name-lou = Louisiana Creole
language-name-loz = Lozi
language-name-lrc = Hilagang Luri
language-name-lt = Lithuanian
language-name-lu = Luba-Katanga
language-name-lua = Luba-Lulua
language-name-lun = Lunda
language-name-luo = Luo
language-name-lus = Mizo
language-name-luy = Luyia
language-name-lv = Latvian
language-name-mad = Madurese
language-name-mag = Magahi
language-name-mai = Maithili
language-name-mak = Makasar
language-name-mas = Masai
language-name-mdf = Moksha
language-name-men = Mende
language-name-mer = Meru
language-name-mfe = Morisyen
language-name-mg = Malagasy
language-name-mgh = Makhuwa-Meetto
language-name-mgo = Meta’
language-name-mh = Marshallese
language-name-mi = Maori
language-name-mic = Micmac
language-name-min = Minangkabau
language-name-mk = Macedonian
language-name-ml = Malayalam
language-name-mn = Mongolian
language-name-mni = Manipuri
language-name-moh = Mohawk
language-name-mos = Mossi
language-name-mr = Marathi
language-name-ms = Malay
language-name-mt = Maltese
language-name-mua = Mundang
language-name-mul = Maramihang Wika
language-name-mus = Creek
language-name-mwl = Mirandese
language-name-my = Burmese
language-name-myv = Erzya
language-name-mzn = Mazanderani
language-name-na = Nauru
language-name-nap = Neapolitan
language-name-naq = Nama
language-name-nb = Norwegian Bokmål
language-name-nd = Hilagang Ndebele
language-name-nds = Low German
language-name-nds_NL = Low Saxon
language-name-ne = Nepali
language-name-new = Newari
language-name-ng = Ndonga
language-name-nia = Nias
language-name-niu = Niuean
language-name-nl = Dutch
language-name-nl_BE = Flemish
language-name-nmg = Kwasio
language-name-nn = Norwegian Nynorsk
language-name-nnh = Ngiemboon
language-name-no = Norwegian
language-name-nog = Nogai
language-name-nqo = N’Ko
language-name-nr = South Ndebele
language-name-nso = Hilagang Sotho
language-name-nus = Nuer
language-name-nv = Navajo
language-name-ny = Nyanja
language-name-nyn = Nyankole
language-name-oc = Occitan
language-name-om = Oromo
language-name-or = Odia
language-name-os = Ossetic
language-name-pa = Punjabi
language-name-pag = Pangasinan
language-name-pam = Pampanga
language-name-pap = Papiamento
language-name-pau = Palauan
language-name-pcm = Nigerian Pidgin
language-name-pl = Polish
language-name-prg = Prussian
language-name-ps = Pashto
language-name-pt = Portuguese
language-name-pt_BR = Portuges ng Brasil
language-name-pt_PT = European Portuguese
language-name-qu = Quechua
language-name-quc = Kʼicheʼ
language-name-rap = Rapanui
language-name-rar = Rarotongan
language-name-rm = Romansh
language-name-rn = Rundi
language-name-ro = Romanian
language-name-ro_MD = Moldavian
language-name-rof = Rombo
language-name-root = Root
language-name-ru = Russian
language-name-rup = Aromanian
language-name-rw = Kinyarwanda
language-name-rwk = Rwa
language-name-sa = Sanskrit
language-name-sad = Sandawe
language-name-sah = Sakha
language-name-saq = Samburu
language-name-sat = Santali
language-name-sba = Ngambay
language-name-sbp = Sangu
language-name-sc = Sardinian
language-name-scn = Sicilian
language-name-sco = Scots
language-name-sd = Sindhi
language-name-sdh = Katimugang Kurdish
language-name-se = Hilagang Sami
language-name-seh = Sena
language-name-ses = Koyraboro Senni
language-name-sg = Sango
language-name-sh = Serbo-Croatian
language-name-shi = Tachelhit
language-name-shn = Shan
language-name-si = Sinhala
language-name-sk = Slovak
language-name-sl = Slovenian
language-name-sm = Samoan
language-name-sma = Katimugang Sami
language-name-smj = Lule Sami
language-name-smn = Inari Sami
language-name-sms = Skolt Sami
language-name-sn = Shona
language-name-snk = Soninke
language-name-so = Somali
language-name-sq = Albanian
language-name-sr = Serbian
language-name-srn = Sranan Tongo
language-name-ss = Swati
language-name-ssy = Saho
language-name-st = Katimugang Sotho
language-name-su = Sundanese
language-name-suk = Sukuma
language-name-sv = Swedish
language-name-sw = Swahili
language-name-sw_CD = Congo Swahili
language-name-swb = Comorian
language-name-syr = Syriac
language-name-ta = Tamil
language-name-te = Telugu
language-name-tem = Timne
language-name-teo = Teso
language-name-tet = Tetum
language-name-tg = Tajik
language-name-th = Thai
language-name-ti = Tigrinya
language-name-tig = Tigre
language-name-tk = Turkmen
language-name-tl = Tagalog
language-name-tlh = Klingon
language-name-tn = Tswana
language-name-to = Tongan
language-name-tpi = Tok Pisin
language-name-tr = Turkish
language-name-trv = Taroko
language-name-ts = Tsonga
language-name-tt = Tatar
language-name-tum = Tumbuka
language-name-tvl = Tuvalu
language-name-tw = Twi
language-name-twq = Tasawaq
language-name-ty = Tahitian
language-name-tyv = Tuvinian
language-name-tzm = Central Atlas Tamazight
language-name-udm = Udmurt
language-name-ug = Uyghur
language-name-uk = Ukranian
language-name-umb = Umbundu
language-name-und = Hindi Kilalang Wika
language-name-ur = Urdu
language-name-uz = Uzbek
language-name-vai = Vai
language-name-ve = Venda
language-name-vi = Vietnamese
language-name-vo = Volapük
language-name-vun = Vunjo
language-name-wa = Walloon
language-name-wae = Walser
language-name-wal = Wolaytta
language-name-war = Waray
language-name-wbp = Warlpiri
language-name-wo = Wolof
language-name-xal = Kalmyk
language-name-xh = Xhosa
language-name-xog = Soga
language-name-yav = Yangben
language-name-ybb = Yemba
language-name-yi = Yiddish
language-name-yo = Yoruba
language-name-yue = Cantonese
language-name-zgh = Standard Moroccan Tamazight
language-name-zh = Chinese
language-name-zh_Hans = Pinasimpleng Chinese
language-name-zh_Hant = Tradisyonal na Chinese
language-name-zu = Zulu
language-name-zun = Zuni
language-name-zxx = Walang nilalaman na ukol sa wika
language-name-zza = Zaza
