language-name-frp = franco-provençal
language-name-goh = ancien haut-allemand
language-name-got = gotique
language-name-gu = gujarati
language-name-njo = ao
language-name-se = same du Nord
language-name-sma = same du Sud
language-name-smj = same de Lule
language-name-smn = same d’Inari
language-name-sms = same skolt
