language-name-aa = afarisht
language-name-ab = abkazisht
language-name-ace = akinezisht
language-name-ada = andangmeisht
language-name-ady = adigisht
language-name-af = afrikanisht
language-name-agq = agemisht
language-name-ain = ajnuisht
language-name-ak = akanisht
language-name-ale = aleutisht
language-name-alt = altaishte jugore
language-name-am = amarisht
language-name-an = aragonezisht
language-name-anp = angikisht
language-name-ar = arabisht
language-name-ar_001 = arabishte standarde moderne
language-name-arn = mapuçisht
language-name-arp = arapahoisht
language-name-as = asamezisht
language-name-asa = asuisht
language-name-ast = asturisht
language-name-av = avarikisht
language-name-awa = auadhisht
language-name-ay = ajmarisht
language-name-az = azerbajxhanisht
language-name-ba = bashkirisht
language-name-ban = balinezisht
language-name-bas = basaisht
language-name-be = bjellorusisht
language-name-bem = bembaisht
language-name-bez = benaisht
language-name-bg = bullgarisht
language-name-bgn = balokishte perëndimore
language-name-bho = boxhpurisht
language-name-bi = bislamisht
language-name-bin = binisht
language-name-bla = siksikaisht
language-name-bm = bambarisht
language-name-bn = bengalisht
language-name-bo = tibetisht
language-name-br = bretonisht
language-name-brx = bodoisht
language-name-bs = boshnjakisht
language-name-bug = buginezisht
language-name-byn = blinisht
language-name-ca = katalonisht
language-name-ce = çeçenisht
language-name-ceb = sebuanisht
language-name-cgg = çigisht
language-name-ch = kamoroisht
language-name-chk = çukezisht
language-name-chm = marisht
language-name-cho = çoktauisht
language-name-chr = çerokisht
language-name-chy = çejenisht
language-name-ckb = kurdishte qendrore
language-name-co = korsikisht
language-name-crs = frëngjishte kreole seselve
language-name-cs = çekisht
language-name-cu = sllavishte kishtare
language-name-cv = çuvashisht
language-name-cy = uellsisht
language-name-da = danisht
language-name-dak = dakotisht
language-name-dar = darguaisht
language-name-dav = tajtaisht
language-name-de = gjermanisht
language-name-de_AT = gjermanishte austriake
language-name-dgr = dogribisht
language-name-dje = zarmaisht
language-name-dsb = sorbishte e poshtme
language-name-dua = dualaisht
language-name-dv = divehisht
language-name-dyo = xhulafonjisht
language-name-dz = xhongaisht
language-name-dzg = dazagauisht
language-name-ebu = embuisht
language-name-ee = eveisht
language-name-efi = efikisht
language-name-eka = ekajukisht
language-name-el = greqisht
language-name-en = anglisht
language-name-en_AU = anglishte australiane
language-name-en_CA = anglishte kanadeze
language-name-en_GB = anglishte britanike
language-name-en_US = anglishte amerikane
language-name-eo = esperanto
language-name-es = spanjisht
language-name-es_419 = spanjishte amerikano-latine
language-name-es_ES = spanjishte evropiane
language-name-es_MX = spanjishte meksikane
language-name-et = estonisht
language-name-eu = baskisht
language-name-ewo = euondoisht
language-name-fa = persisht
language-name-ff = fulaisht
language-name-fi = finlandisht
language-name-fil = filipinisht
language-name-fj = fixhianisht
language-name-fo = faroisht
language-name-fon = fonisht
language-name-fr = frëngjisht
language-name-fr_CA = frëngjishte kanadeze
language-name-fr_CH = frëngjishte zvicerane
language-name-fur = friulianisht
language-name-fy = frizianishte perëndimore
language-name-ga = irlandisht
language-name-gaa = gaisht
language-name-gag = gagauzisht
language-name-gd = galishte skoceze
language-name-gez = gizisht
language-name-gil = gilbertazisht
language-name-gl = galicisht
language-name-gn = guaranisht
language-name-gor = gorontaloisht
language-name-gsw = gjermanishte zvicerane
language-name-gu = guxharatisht
language-name-guz = gusisht
language-name-gv = manksisht
language-name-gwi = guiçinisht
language-name-ha = hausisht
language-name-haw = havaisht
language-name-he = hebraisht
language-name-hi = indisht
language-name-hil = hiligajnonisht
language-name-hmn = hmongisht
language-name-hr = kroatisht
language-name-hsb = sorbishte e sipërme
language-name-ht = haitisht
language-name-hu = hungarisht
language-name-hup = hupaisht
language-name-hy = armenisht
language-name-hz = hereroisht
language-name-ia = interlingua
language-name-iba = ibanisht
language-name-ibb = ibibioisht
language-name-id = indonezisht
language-name-ie = gjuha oksidentale
language-name-ig = igboisht
language-name-ii = sishuanisht
language-name-ilo = ilokoisht
language-name-inh = ingushisht
language-name-io = idoisht
language-name-is = islandisht
language-name-it = italisht
language-name-iu = inuktitutisht
language-name-ja = japonisht
language-name-jbo = lojbanisht
language-name-jgo = ngombisht
language-name-jmc = maçamisht
language-name-jv = javanisht
language-name-ka = gjeorgjisht
language-name-kab = kabilisht
language-name-kac = kaçinisht
language-name-kaj = kajeisht
language-name-kam = kambaisht
language-name-kbd = kabardianisht
language-name-kcg = tjapisht
language-name-kde = makondisht
language-name-kea = kreolishte e Kepit të Gjelbër
language-name-kfo = koroisht
language-name-kha = kasisht
language-name-khq = kojraçinisht
language-name-ki = kikujuisht
language-name-kj = kuanjamaisht
language-name-kk = kazakisht
language-name-kkj = kakoisht
language-name-kl = kalalisutisht
language-name-kln = kalenxhinisht
language-name-km = kmerisht
language-name-kmb = kimbunduisht
language-name-kn = kanadisht
language-name-ko = koreanisht
language-name-koi = komi-parmjakisht
language-name-kok = konkanisht
language-name-kpe = kpeleisht
language-name-kr = kanurisht
language-name-krc = karaçaj-balkarisht
language-name-krl = karelianisht
language-name-kru = kurukisht
language-name-ks = kashmirisht
language-name-ksb = shambalisht
language-name-ksf = bafianisht
language-name-ksh = këlnisht
language-name-ku = kurdisht
language-name-kum = kumikisht
language-name-kv = komisht
language-name-kw = kornisht
language-name-ky = kirgizisht
language-name-la = latinisht
language-name-lad = ladinoisht
language-name-lag = langisht
language-name-lb = luksemburgisht
language-name-lez = lezgianisht
language-name-lg = gandaisht
language-name-li = limburgisht
language-name-lkt = lakotisht
language-name-ln = lingalisht
language-name-lo = laosisht
language-name-loz = lozisht
language-name-lrc = lurishte veriore
language-name-lt = lituanisht
language-name-lu = luba-katangaisht
language-name-lua = luba-luluaisht
language-name-lun = lundaisht
language-name-luo = luoisht
language-name-lus = mizoisht
language-name-luy = lujaisht
language-name-lv = letonisht
language-name-mad = madurezisht
language-name-mag = magaisht
language-name-mai = maitilisht
language-name-mak = makasarisht
language-name-mas = masaisht
language-name-mdf = mokshaisht
language-name-men = mendisht
language-name-mer = meruisht
language-name-mfe = morisjenisht
language-name-mg = madagaskarisht
language-name-mgh = makua-mitoisht
language-name-mgo = metaisht
language-name-mh = marshallisht
language-name-mi = maorisht
language-name-mic = mikmakisht
language-name-min = minangkabauisht
language-name-mk = maqedonisht
language-name-ml = malajalamisht
language-name-mn = mongolisht
language-name-mni = manipurisht
language-name-moh = mohokisht
language-name-mos = mosisht
language-name-mr = maratisht
language-name-ms = malajisht
language-name-mt = maltisht
language-name-mua = mundangisht
language-name-mul = gjuhë të shumëfishta
language-name-mus = krikisht
language-name-mwl = mirandisht
language-name-my = birmanisht
language-name-myv = erzjaisht
language-name-mzn = mazanderanisht
language-name-na = nauruisht
language-name-nap = napoletanisht
language-name-naq = namaisht
language-name-nb = norvegjishte letrare
language-name-nd = ndebelishte veriore
language-name-nds = gjermanishte e vendeve të ulëta
language-name-nds_NL = gjermanishte saksone e vendeve të ulëta
language-name-ne = nepalisht
language-name-new = neuarisht
language-name-ng = ndongaisht
language-name-nia = niasisht
language-name-niu = niueanisht
language-name-nl = holandisht
language-name-nl_BE = flamandisht
language-name-nmg = kuasisht
language-name-nn = norvegjishte nynorsk
language-name-nnh = ngiembunisht
language-name-no = norvegjisht
language-name-nog = nogajisht
language-name-nqo = nkoisht
language-name-nr = ndebelishte jugore
language-name-nso = sotoishte veriore
language-name-nus = nuerisht
language-name-nv = navahoisht
language-name-ny = nianjisht
language-name-nyn = niankolisht
language-name-oc = oksitanisht
language-name-om = oromoisht
language-name-or = odisht
language-name-os = osetisht
language-name-pa = punxhabisht
language-name-pag = pangasinanisht
language-name-pam = pampangaisht
language-name-pap = papiamentisht
language-name-pau = paluanisht
language-name-pcm = pixhinishte nigeriane
language-name-pl = polonisht
language-name-prg = prusisht
language-name-ps = pashtoisht
language-name-pt = portugalisht
language-name-pt_BR = portugalishte braziliane
language-name-pt_PT = portugalishte evropiane
language-name-qu = keçuaisht
language-name-quc = kiçeisht
language-name-rap = rapanuisht
language-name-rar = rarontonganisht
language-name-rm = retoromanisht
language-name-rn = rundisht
language-name-ro = rumanisht
language-name-ro_MD = moldavisht
language-name-rof = romboisht
language-name-root = rutisht
language-name-ru = rusisht
language-name-rup = vllahisht
language-name-rw = kiniaruandisht
language-name-rwk = ruaisht
language-name-sa = sanskritisht
language-name-sad = sandauisht
language-name-sah = sakaisht
language-name-saq = samburisht
language-name-sat = santalisht
language-name-sba = ngambajisht
language-name-sbp = sanguisht
language-name-sc = sardenjisht
language-name-scn = siçilianisht
language-name-sco = skotisht
language-name-sd = sindisht
language-name-sdh = kurdishte jugore
language-name-se = samishte veriore
language-name-seh = senaisht
language-name-ses = senishte kojrabore
language-name-sg = sangoisht
language-name-sh = serbo-kroatisht
language-name-shi = taçelitisht
language-name-shn = shanisht
language-name-si = sinhalisht
language-name-sk = sllovakisht
language-name-sl = sllovenisht
language-name-sm = samoanisht
language-name-sma = samishte jugore
language-name-smj = samishte lule
language-name-smn = samishte inari
language-name-sms = samishte skolti
language-name-sn = shonisht
language-name-snk = soninkisht
language-name-so = somalisht
language-name-sq = shqip
language-name-sr = serbisht
language-name-ss = suatisht
language-name-ssy = sahoisht
language-name-st = sotoishte jugore
language-name-su = sundanisht
language-name-suk = sukumaisht
language-name-sv = suedisht
language-name-sw = suahilisht
language-name-sw_CD = suahilishte kongoleze
language-name-swb = kamorianisht
language-name-syr = siriakisht
language-name-ta = tamilisht
language-name-te = teluguisht
language-name-tem = timneisht
language-name-teo = tesoisht
language-name-tet = tetumisht
language-name-tg = taxhikisht
language-name-th = tajlandisht
language-name-ti = tigrinjaisht
language-name-tig = tigreisht
language-name-tk = turkmenisht
language-name-tlh = klingonisht
language-name-tn = cuanaisht
language-name-to = tonganisht
language-name-tpi = pisinishte toku
language-name-tr = turqisht
language-name-trv = torokoisht
language-name-ts = congaisht
language-name-tt = tatarisht
language-name-tum = tumbukaisht
language-name-tvl = tuvaluisht
language-name-tw = tuisht
language-name-twq = tasavakisht
language-name-ty = tahitisht
language-name-tyv = tuvinianisht
language-name-tzm = tamazajtisht e Atlasit Qendror
language-name-udm = udmurtisht
language-name-ug = ujgurisht
language-name-uk = ukrainisht
language-name-umb = umbunduisht
language-name-und = E panjohur
language-name-ur = urduisht
language-name-uz = uzbekisht
language-name-vai = vaisht
language-name-ve = vendaisht
language-name-vi = vietnamisht
language-name-vo = volapykisht
language-name-vun = vunxhoisht
language-name-wa = ualunisht
language-name-wae = ualserisht
language-name-wal = ulajtaisht
language-name-war = uarajisht
language-name-wbp = uarlpirisht
language-name-wo = uolofisht
language-name-xal = kalmikisht
language-name-xh = xhosaisht
language-name-xog = sogisht
language-name-yav = jangbenisht
language-name-ybb = jembaisht
language-name-yi = jidisht
language-name-yo = jorubaisht
language-name-yue = kantonezisht
language-name-zgh = tamaziatishte standarde marokene
language-name-zh = kinezisht
language-name-zu = zuluisht
language-name-zun = zunisht
language-name-zxx = nuk ka përmbajtje gjuhësore
language-name-zza = zazaisht
