language-name-aa = afarčina
language-name-ab = abcházčina
language-name-ace = acehčina
language-name-ach = ačoli
language-name-ada = adangme
language-name-ady = adygejčina
language-name-ae = avestčina
language-name-af = afrikánčina
language-name-afh = afrihili
language-name-agq = aghem
language-name-ain = ainčina
language-name-ak = akančina
language-name-akk = akkadčina
language-name-ale = aleutčina
language-name-alt = južná altajčina
language-name-am = amharčina
language-name-an = aragónčina
language-name-ang = stará angličtina
language-name-anp = angika
language-name-ar = arabčina
language-name-arc = aramejčina
language-name-arn = mapudungun
language-name-arp = arapažština
language-name-ars = arabčina – nadžd
language-name-arw = arawačtina
language-name-as = ásamčina
language-name-asa = asu
language-name-ast = astúrčina
language-name-av = avarčina
language-name-awa = awadhi
language-name-ay = aymarčina
language-name-az = azerbajdžančina
language-name-ba = baškirčina
language-name-bal = balúčtina
language-name-ban = balijčina
language-name-bas = basa
language-name-bax = bamun
language-name-bbj = ghomala
language-name-be = bieloruština
language-name-bej = bedža
language-name-bem = bemba
language-name-bez = bena
language-name-bfd = bafut
language-name-bg = bulharčina
language-name-bgn = západná balúčtina
language-name-bho = bhódžpurčina
language-name-bi = bislama
language-name-bik = bikolčina
language-name-bin = bini
language-name-bkm = kom
language-name-bla = siksika
language-name-bm = bambarčina
language-name-bn = bengálčina
language-name-bo = tibetčina
language-name-br = bretónčina
language-name-bra = bradžčina
language-name-brx = bodo
language-name-bs = bosniačtina
language-name-bss = akoose
language-name-bua = buriatčina
language-name-bug = bugiština
language-name-bum = bulu
language-name-byn = blin
language-name-byv = medumba
language-name-ca = katalánčina
language-name-cad = kaddo
language-name-car = karibčina
language-name-cay = kajugčina
language-name-cch = atsam
language-name-ce = čečenčina
language-name-ceb = cebuánčina
language-name-cgg = kiga
language-name-ch = čamorčina
language-name-chb = čibča
language-name-chg = čagatajčina
language-name-chk = chuuk
language-name-chm = marijčina
language-name-chn = činucký žargón
language-name-cho = čoktčina
language-name-chp = čipevajčina
language-name-chr = čerokí
language-name-chy = čejenčina
language-name-co = korzičtina
language-name-cop = koptčina
language-name-cr = krí
language-name-crh = krymská tatárčina
language-name-crs = seychelská kreolčina
language-name-cs = čeština
language-name-csb = kašubčina
language-name-cu = cirkevná slovančina
language-name-cv = čuvaština
language-name-cy = waleština
language-name-da = dánčina
language-name-dak = dakotčina
language-name-dar = darginčina
language-name-dav = taita
language-name-de = nemčina
language-name-del = delawarčina
language-name-den = slavé
language-name-dgr = dogribčina
language-name-din = dinkčina
language-name-dje = zarma
language-name-doi = dógrí
language-name-dsb = dolnolužická srbčina
language-name-dua = duala
language-name-dum = stredná holandčina
language-name-dv = maldivčina
language-name-dyo = jola-fonyi
language-name-dyu = ďula
language-name-dz = dzongkha
language-name-dzg = dazaga
language-name-ebu = embu
language-name-ee = eweština
language-name-efi = efik
language-name-egy = staroegyptčina
language-name-eka = ekadžuk
language-name-el = gréčtina
language-name-elx = elamčina
language-name-en = angličtina
language-name-enm = stredná angličtina
language-name-eo = esperanto
language-name-es = španielčina
language-name-et = estónčina
language-name-eu = baskičtina
language-name-ewo = ewondo
language-name-fa = perzština
language-name-fan = fangčina
language-name-fat = fanti
language-name-ff = fulbčina
language-name-fi = fínčina
language-name-fil = filipínčina
language-name-fj = fidžijčina
language-name-fo = faerčina
language-name-fon = fončina
language-name-fr = francúzština
language-name-frm = stredná francúzština
language-name-fro = stará francúzština
language-name-frr = severná frízština
language-name-frs = východofrízština
language-name-fur = friulčina
language-name-fy = západná frízština
language-name-ga = írčina
language-name-gaa = ga
language-name-gag = gagauzština
language-name-gay = gayo
language-name-gba = gbaja
language-name-gd = škótska gaelčina
language-name-gez = etiópčina
language-name-gil = kiribatčina
language-name-gl = galícijčina
language-name-gmh = stredná horná nemčina
language-name-gn = guaraníjčina
language-name-goh = stará horná nemčina
language-name-gon = góndčina
language-name-gor = gorontalo
language-name-got = gótčina
language-name-grb = grebo
language-name-grc = starogréčtina
language-name-gu = gudžarátčina
language-name-guz = gusii
language-name-gv = mančina
language-name-gwi = kučinčina
language-name-ha = hauština
language-name-hai = haida
language-name-haw = havajčina
language-name-he = hebrejčina
language-name-hi = hindčina
language-name-hil = hiligajnončina
language-name-hit = chetitčina
language-name-hmn = hmongčina
language-name-ho = hiri motu
language-name-hr = chorvátčina
language-name-hsb = hornolužická srbčina
language-name-ht = haitská kreolčina
language-name-hu = maďarčina
language-name-hup = hupčina
language-name-hy = arménčina
language-name-hz = herero
language-name-ia = interlingua
language-name-iba = ibančina
language-name-ibb = ibibio
language-name-id = indonézština
language-name-ie = interlingue
language-name-ig = igboština
language-name-ii = s’čchuanská iovčina
language-name-ik = inupik
language-name-ilo = ilokánčina
language-name-inh = inguština
language-name-io = ido
language-name-is = islandčina
language-name-it = taliančina
language-name-iu = inuktitut
language-name-ja = japončina
language-name-jbo = lojban
language-name-jgo = ngomba
language-name-jmc = mašame
language-name-jpr = židovská perzština
language-name-jrb = židovská arabčina
language-name-jv = jávčina
language-name-ka = gruzínčina
language-name-kaa = karakalpačtina
language-name-kab = kabylčina
language-name-kac = kačjinčina
language-name-kaj = jju
language-name-kam = kamba
language-name-kaw = kawi
language-name-kbd = kabardčina
language-name-kbl = kanembu
language-name-kcg = tyap
language-name-kde = makonde
language-name-kea = kapverdčina
language-name-kfo = koro
language-name-kg = kongčina
language-name-kha = khasijčina
language-name-kho = chotančina
language-name-khq = západná songhajčina
language-name-ki = kikujčina
language-name-kj = kuaňama
language-name-kk = kazaština
language-name-kkj = kako
language-name-kl = grónčina
language-name-kln = kalendžin
language-name-km = khmérčina
language-name-kmb = kimbundu
language-name-kn = kannadčina
language-name-ko = kórejčina
language-name-koi = komi-permiačtina
language-name-kok = konkánčina
language-name-kos = kusaie
language-name-kpe = kpelle
language-name-kr = kanurijčina
language-name-krc = karačajevsko-balkarčina
language-name-krl = karelčina
language-name-kru = kuruchčina
language-name-ks = kašmírčina
language-name-ksb = šambala
language-name-ksf = bafia
language-name-ksh = kolínčina
language-name-ku = kurdčina
language-name-kum = kumyčtina
language-name-kut = kutenajčina
language-name-kv = komijčina
language-name-kw = kornčina
language-name-ky = kirgizština
language-name-la = latinčina
language-name-lad = židovská španielčina
language-name-lag = langi
language-name-lah = lahandčina
language-name-lam = lamba
language-name-lb = luxemburčina
language-name-lez = lezginčina
language-name-lg = gandčina
language-name-li = limburčina
language-name-lkt = lakotčina
language-name-ln = lingalčina
language-name-lo = laoština
language-name-lol = mongo
language-name-loz = lozi
language-name-lrc = severné luri
language-name-lt = litovčina
language-name-lui = luiseňo
language-name-lun = lunda
language-name-luo = luo
language-name-lus = mizorámčina
language-name-luy = luhja
language-name-lv = lotyština
language-name-mad = madurčina
language-name-maf = mafa
language-name-mag = magadhčina
language-name-mai = maithilčina
language-name-mak = makasarčina
language-name-man = mandingo
language-name-mas = masajčina
language-name-mde = maba
language-name-mdf = mokšiančina
language-name-mdr = mandarčina
language-name-men = mendejčina
language-name-mer = meru
language-name-mfe = maurícijská kreolčina
language-name-mg = malgaština
language-name-mga = stredná írčina
language-name-mgh = makua-meetto
language-name-mgo = meta’
language-name-mh = marshallčina
language-name-mi = maorijčina
language-name-mic = mikmakčina
language-name-min = minangkabaučina
language-name-mk = macedónčina
language-name-ml = malajálamčina
language-name-mn = mongolčina
language-name-mnc = mandžuština
language-name-mni = manípurčina
language-name-moh = mohawkčina
language-name-mos = mossi
language-name-mr = maráthčina
language-name-ms = malajčina
language-name-mt = maltčina
language-name-mua = mundang
language-name-mul = viaceré jazyky
language-name-mus = kríkčina
language-name-mwl = mirandčina
language-name-mwr = marwari
language-name-my = barmčina
language-name-mye = myene
language-name-myv = erzjančina
language-name-mzn = mázandaránčina
language-name-na = nauruština
language-name-nap = neapolčina
language-name-naq = nama
language-name-nd = severná ndebelčina
language-name-nds = dolná nemčina
language-name-nds_NL = dolná saština
language-name-ne = nepálčina
language-name-new = nevárčina
language-name-ng = ndonga
language-name-nia = niasánčina
language-name-niu = niueština
language-name-nl = holandčina
language-name-nl_BE = flámčina
language-name-nmg = kwasio
language-name-nnh = ngiemboon
language-name-no = nórčina
language-name-nog = nogajčina
language-name-non = stará nórčina
language-name-nqo = n’ko
language-name-nr = južná ndebelčina
language-name-nso = severná sothčina
language-name-nus = nuer
language-name-nv = navaho
language-name-nwc = klasická nevárčina
language-name-ny = ňandža
language-name-nym = ňamwezi
language-name-nyn = ňankole
language-name-nyo = ňoro
language-name-nzi = nzima
language-name-oc = okcitánčina
language-name-oj = odžibva
language-name-om = oromčina
language-name-or = uríjčina
language-name-os = osetčina
language-name-osa = osedžština
language-name-ota = osmanská turečtina
language-name-pa = pandžábčina
language-name-pag = pangasinančina
language-name-pal = pahlaví
language-name-pam = kapampangančina
language-name-pap = papiamento
language-name-pau = palaučina
language-name-pcm = nigerijský pidžin
language-name-peo = stará perzština
language-name-phn = feničtina
language-name-pi = pálí
language-name-pl = poľština
language-name-pon = pohnpeiština
language-name-prg = pruština
language-name-pro = stará okcitánčina
language-name-ps = paštčina
language-name-pt = portugalčina
language-name-qu = kečuánčina
language-name-quc = quiché
language-name-raj = radžastančina
language-name-rap = rapanujčina
language-name-rar = rarotongská maorijčina
language-name-rm = rétorománčina
language-name-rn = rundčina
language-name-ro = rumunčina
language-name-ro_MD = moldavčina
language-name-rof = rombo
language-name-rom = rómčina
language-name-root = koreň
language-name-ru = ruština
language-name-rup = arumunčina
language-name-rw = rwandčina
language-name-rwk = rwa
language-name-sa = sanskrit
language-name-sad = sandaweština
language-name-sah = jakutčina
language-name-sam = samaritánska aramejčina
language-name-saq = samburu
language-name-sas = sasačtina
language-name-sat = santalčina
language-name-sba = ngambay
language-name-sbp = sangu
language-name-sc = sardínčina
language-name-scn = sicílčina
language-name-sco = škótčina
language-name-sd = sindhčina
language-name-sdh = južná kurdčina
language-name-se = severná saamčina
language-name-see = senekčina
language-name-seh = sena
language-name-sel = selkupčina
language-name-ses = koyraboro senni
language-name-sg = sango
language-name-sga = stará írčina
language-name-sh = srbochorvátčina
language-name-shi = tachelhit
language-name-shn = šančina
language-name-shu = čadská arabčina
language-name-si = sinhalčina
language-name-sid = sidamo
language-name-sk = slovenčina
language-name-sl = slovinčina
language-name-sm = samojčina
language-name-sma = južná saamčina
language-name-smj = lulská saamčina
language-name-smn = inarijská saamčina
language-name-sms = skoltská saamčina
language-name-sn = šončina
language-name-snk = soninke
language-name-so = somálčina
language-name-sog = sogdijčina
language-name-sq = albánčina
language-name-sr = srbčina
language-name-srn = surinamčina
language-name-srr = sererčina
language-name-ss = svazijčina
language-name-ssy = saho
language-name-st = južná sothčina
language-name-su = sundčina
language-name-suk = sukuma
language-name-sus = susu
language-name-sux = sumerčina
language-name-sv = švédčina
language-name-sw = swahilčina
language-name-swb = komorčina
language-name-syr = sýrčina
language-name-ta = tamilčina
language-name-te = telugčina
language-name-tem = temne
language-name-teo = teso
language-name-ter = terêna
language-name-tet = tetumčina
language-name-tg = tadžičtina
language-name-th = thajčina
language-name-ti = tigriňa
language-name-tig = tigrejčina
language-name-tiv = tiv
language-name-tk = turkménčina
language-name-tkl = tokelauština
language-name-tl = tagalčina
language-name-tlh = klingónčina
language-name-tli = tlingitčina
language-name-tmh = tuaregčina
language-name-tn = tswančina
language-name-to = tongčina
language-name-tog = ňasa tonga
language-name-tpi = novoguinejský pidžin
language-name-tr = turečtina
language-name-trv = taroko
language-name-ts = tsongčina
language-name-tsi = cimšjančina
language-name-tt = tatárčina
language-name-tum = tumbuka
language-name-tvl = tuvalčina
language-name-tw = twi
language-name-twq = tasawaq
language-name-ty = tahitčina
language-name-tyv = tuviančina
language-name-tzm = stredomarocká tuaregčina
language-name-udm = udmurtčina
language-name-ug = ujgurčina
language-name-uga = ugaritčina
language-name-uk = ukrajinčina
language-name-umb = umbundu
language-name-und = neznámy jazyk
language-name-ur = urdčina
language-name-uz = uzbečtina
language-name-vai = vai
language-name-ve = vendčina
language-name-vi = vietnamčina
language-name-vo = volapük
language-name-vot = vodčina
language-name-vun = vunjo
language-name-wa = valónčina
language-name-wae = walserčina
language-name-wal = walamčina
language-name-war = waray
language-name-was = washo
language-name-wbp = warlpiri
language-name-wo = wolofčina
language-name-xal = kalmyčtina
language-name-xh = xhoština
language-name-xog = soga
language-name-yao = jao
language-name-yap = japčina
language-name-yav = jangben
language-name-ybb = yemba
language-name-yi = jidiš
language-name-yo = jorubčina
language-name-yue = kantončina
language-name-za = čuangčina
language-name-zap = zapotéčtina
language-name-zbl = systém Bliss
language-name-zen = zenaga
language-name-zh = čínština
language-name-zu = zuluština
language-name-zun = zuniština
language-name-zxx = bez jazykového obsahu
language-name-zza = zaza
