language-name-af = Afrikoota
language-name-am = Afaan Sidaamaa
language-name-ar = Arabiffaa
language-name-az = Afaan Azerbaijani
language-name-be = Afaan Belarusia
language-name-bg = Afaan Bulgariya
language-name-bn = Afaan Baangladeshi
language-name-bs = Afaan Bosniyaa
language-name-ca = Afaan Katalaa
language-name-cs = Afaan Czech
language-name-cy = Welishiffaa
language-name-da = Afaan Deenmaark
language-name-de = Afaan Jarmanii
language-name-el = Afaan Giriiki
language-name-en = Ingliffa
language-name-eo = Afaan Esperantoo
language-name-es = Afaan Ispeen
language-name-et = Afaan Istooniya
language-name-eu = Afaan Baskuu
language-name-fa = Afaan Persia
language-name-fi = Afaan Fiilaandi
language-name-fil = Afaan Filippinii
language-name-fo = Afaan Faroese
language-name-fr = Afaan Faransaayii
language-name-fy = Afaan Firisiyaani
language-name-ga = Afaan Ayirishii
language-name-gd = Scots Gaelic
language-name-gl = Afaan Galishii
language-name-gn = Afaan Guarani
language-name-gu = Afaan Gujarati
language-name-he = Afaan Hebrew
language-name-hi = Afaan Hindii
language-name-hr = Afaan Croatian
language-name-hu = Afaan Hangaari
language-name-ia = Interlingua
language-name-id = Afaan Indoneziya
language-name-is = Ayiislandiffaa
language-name-it = Afaan Xaaliyaani
language-name-ja = Afaan Japanii
language-name-jv = Afaan Java
language-name-ka = Afaan Georgian
language-name-kn = Afaan Kannada
language-name-ko = Afaan Korea
language-name-la = Afaan Laatini
language-name-lt = Afaan Liituniyaa
language-name-lv = Afaan Lativiyaa
language-name-mk = Afaan Macedooniyaa
language-name-ml = Malayaalamiffaa
language-name-mr = Afaan Maratii
language-name-ms = Malaayiffaa
language-name-mt = Afaan Maltesii
language-name-ne = Afaan Nepalii
language-name-nl = Afaan Dachii
language-name-nn = Afaan Norwegian
language-name-no = Afaan Norweyii
language-name-oc = Afaan Occit
language-name-om = Oromoo
language-name-pa = Afaan Punjabii
language-name-pl = Afaan Polandii
language-name-pt = Afaan Porchugaal
language-name-pt_PT = Afaan Protuguese
language-name-ro = Afaan Romaniyaa
language-name-ru = Afaan Rushiyaa
language-name-si = Afaan Sinhalese
language-name-sk = Afaan Slovak
language-name-sl = Afaan Islovaniyaa
language-name-sq = Afaan Albaniyaa
language-name-sr = Afaan Serbiya
language-name-su = Afaan Sudaanii
language-name-sv = Afaan Suwidiin
language-name-sw = Suwahilii
language-name-ta = Afaan Tamilii
language-name-te = Afaan Telugu
language-name-th = Afaan Tayii
language-name-ti = Afaan Tigiree
language-name-tk = Lammii Turkii
language-name-tlh = Afaan Kilingon
language-name-tr = Afaan Turkii
language-name-uk = Afaan Ukreenii
language-name-ur = Afaan Urdu
language-name-uz = Afaan Uzbek
language-name-vi = Afaan Veetinam
language-name-xh = Afaan Xhosa
language-name-zh = Chinese
language-name-zu = Afaan Zuulu
