language-name-aa = afar
language-name-ab = abkhazo
language-name-ace = achinés
language-name-ach = acholí
language-name-ada = adangme
language-name-ady = adigueo
language-name-af = afrikaans
language-name-agq = aghem
language-name-ain = ainu
language-name-ak = akan
language-name-ale = aleutiano
language-name-alt = altai meridional
language-name-am = amhárico
language-name-an = aragonés
language-name-anp = angika
language-name-ar = árabe
language-name-ar_001 = árabe estándar moderno
language-name-arc = arameo
language-name-arn = mapuche
language-name-arp = arapaho
language-name-as = assamés
language-name-asa = asu
language-name-ast = asturiano
language-name-av = avar
language-name-awa = awadhi
language-name-ay = aimará
language-name-az = acerbaixano
language-name-ba = baskir
language-name-ban = balinés
language-name-bas = basaa
language-name-be = bielorruso
language-name-bem = bemba
language-name-bez = bena
language-name-bg = búlgaro
language-name-bgn = baluchi occidental
language-name-bho = bhojpuri
language-name-bi = bislama
language-name-bin = bini
language-name-bla = siksiká
language-name-bm = bambaro
language-name-bn = bengalí
language-name-bo = tibetano
language-name-br = bretón
language-name-brx = bodo
language-name-bs = bosníaco
language-name-bug = buginés
language-name-byn = blin
language-name-ca = catalán
language-name-ce = checheno
language-name-ceb = cebuano
language-name-cgg = kiga
language-name-ch = chamorro
language-name-chk = chuukese
language-name-chm = mari
language-name-cho = choctaw
language-name-chr = cherokee
language-name-chy = cheyenne
language-name-ckb = kurdo soraní
language-name-co = corso
language-name-cs = checo
language-name-cu = eslavo eclesiástico
language-name-cv = chuvaxo
language-name-cy = galés
language-name-da = dinamarqués
language-name-dak = dakota
language-name-dar = dargwa
language-name-dav = taita
language-name-de = alemán
language-name-de_AT = alemán austríaco
language-name-de_CH = alto alemán suízo
language-name-dgr = dogrib
language-name-dje = zarma
language-name-dsb = baixo sorbio
language-name-dua = duala
language-name-dv = divehi
language-name-dyo = jola-fonyi
language-name-dz = dzongkha
language-name-dzg = dazaga
language-name-ebu = embu
language-name-ee = ewe
language-name-efi = efik
language-name-egy = exipcio antigo
language-name-eka = ekajuk
language-name-el = grego
language-name-en = inglés
language-name-en_AU = inglés australiano
language-name-en_CA = inglés canadense
language-name-en_GB = inglés británico
language-name-en_US = inglés estadounidense
language-name-eo = esperanto
language-name-es = español
language-name-es_419 = español de América
language-name-es_ES = español de España
language-name-es_MX = español de México
language-name-et = estoniano
language-name-eu = éuscaro
language-name-ewo = ewondo
language-name-fa = persa
language-name-ff = fula
language-name-fi = finés
language-name-fil = filipino
language-name-fj = fidxiano
language-name-fo = feroés
language-name-fon = fon
language-name-fr = francés
language-name-fr_CA = francés canadense
language-name-fr_CH = francés suízo
language-name-fur = friulano
language-name-fy = frisón occidental
language-name-ga = irlandés
language-name-gaa = ga
language-name-gag = gagauz
language-name-gd = gaélico escocés
language-name-gez = ge’ez
language-name-gil = kiribatiano
language-name-gl = galego
language-name-gn = guaraní
language-name-gor = gorontalo
language-name-grc = grego antigo
language-name-gsw = alemán suízo
language-name-gu = guxaratí
language-name-guz = gusii
language-name-gv = manx
language-name-gwi = gwichʼin
language-name-ha = hausa
language-name-haw = hawaiano
language-name-he = hebreo
language-name-hi = hindi
language-name-hil = hiligaynon
language-name-hmn = hmong
language-name-hr = croata
language-name-hsb = alto sorbio
language-name-ht = crioulo haitiano
language-name-hu = húngaro
language-name-hup = hupa
language-name-hy = armenio
language-name-hz = herero
language-name-ia = interlingua
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indonesio
language-name-ig = ibo
language-name-ii = yi sichuanés
language-name-ilo = ilocano
language-name-inh = inguxo
language-name-io = ido
language-name-is = islandés
language-name-it = italiano
language-name-iu = inuktitut
language-name-ja = xaponés
language-name-jbo = lojban
language-name-jgo = ngomba
language-name-jmc = machame
language-name-jv = xavanés
language-name-ka = xeorxiano
language-name-kab = cabila
language-name-kac = kachin
language-name-kaj = jju
language-name-kam = kamba
language-name-kbd = cabardiano
language-name-kcg = tyap
language-name-kde = makonde
language-name-kea = caboverdiano
language-name-kfo = koro
language-name-kg = kongo
language-name-kha = khasi
language-name-khq = koyra chiini
language-name-ki = kikuyu
language-name-kj = kuanyama
language-name-kk = casaco
language-name-kkj = kako
language-name-kl = groenlandés
language-name-kln = kalenjin
language-name-km = khmer
language-name-kmb = kimbundu
language-name-kn = canarés
language-name-ko = coreano
language-name-koi = komi permio
language-name-kok = konkani
language-name-kpe = kpelle
language-name-kr = canuri
language-name-krc = carachaio-bálcara
language-name-krl = carelio
language-name-kru = kurukh
language-name-ks = cachemir
language-name-ksb = shambala
language-name-ksf = bafia
language-name-ksh = kölsch
language-name-ku = kurdo
language-name-kum = kumyk
language-name-kv = komi
language-name-kw = córnico
language-name-ky = kirguiz
language-name-la = latín
language-name-lad = ladino
language-name-lag = langi
language-name-lb = luxemburgués
language-name-lez = lezguio
language-name-lg = ganda
language-name-li = limburgués
language-name-lkt = lakota
language-name-ln = lingala
language-name-lo = laosiano
language-name-loz = lozi
language-name-lrc = luri setentrional
language-name-lt = lituano
language-name-lu = luba-katanga
language-name-lua = luba-lulua
language-name-lun = lunda
language-name-luo = luo
language-name-lus = mizo
language-name-luy = luyia
language-name-lv = letón
language-name-mad = madurés
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = makasar
language-name-mas = masai
language-name-mdf = moksha
language-name-men = mende
language-name-mer = meru
language-name-mfe = crioulo mauriciano
language-name-mg = malgaxe
language-name-mgh = makhuwa-meetto
language-name-mgo = meta’
language-name-mh = marshalés
language-name-mi = maorí
language-name-mic = micmac
language-name-min = minangkabau
language-name-mk = macedonio
language-name-ml = malabar
language-name-mn = mongol
language-name-mni = manipuri
language-name-moh = mohawk
language-name-mos = mossi
language-name-mr = marathi
language-name-ms = malaio
language-name-mt = maltés
language-name-mua = mundang
language-name-mul = varias linguas
language-name-mus = creek
language-name-mwl = mirandés
language-name-my = birmano
language-name-myv = erzya
language-name-mzn = mazandaraní
language-name-na = nauruano
language-name-nap = napolitano
language-name-naq = nama
language-name-nb = noruegués bokmål
language-name-nd = ndebele setentrional
language-name-nds = baixo alemán
language-name-nds_NL = baixo saxón
language-name-ne = nepalí
language-name-new = newari
language-name-ng = ndonga
language-name-nia = nias
language-name-niu = niueano
language-name-nl = neerlandés
language-name-nl_BE = flamengo
language-name-nmg = kwasio
language-name-nn = noruegués nynorsk
language-name-nnh = ngiemboon
language-name-no = noruegués
language-name-nog = nogai
language-name-nqo = n’ko
language-name-nr = ndebele meridional
language-name-nso = sesotho sa leboa
language-name-nus = nuer
language-name-nv = navajo
language-name-ny = nyanja
language-name-nyn = nyankole
language-name-oc = occitano
language-name-om = oromo
language-name-or = oriya
language-name-os = ossetio
language-name-pa = panxabiano
language-name-pag = pangasinan
language-name-pam = pampanga
language-name-pap = papiamento
language-name-pau = palauano
language-name-pcm = pidgin nixeriano
language-name-pl = polaco
language-name-prg = prusiano
language-name-ps = paxto
language-name-pt = portugués
language-name-pt_BR = portugués do Brasil
language-name-pt_PT = portugués de Portugal
language-name-qu = quechua
language-name-quc = quiché
language-name-rap = rapanui
language-name-rar = rarotongano
language-name-rm = romanche
language-name-rn = rundi
language-name-ro = romanés
language-name-ro_MD = moldavo
language-name-rof = rombo
language-name-root = raíz
language-name-ru = ruso
language-name-rup = aromanés
language-name-rw = ruandés
language-name-rwk = rwa
language-name-sa = sánscrito
language-name-sad = sandawe
language-name-sah = sakha
language-name-saq = samburu
language-name-sat = santali
language-name-sba = ngambay
language-name-sbp = sangu
language-name-sc = sardo
language-name-scn = siciliano
language-name-sco = escocés
language-name-sd = sindhi
language-name-sdh = kurdo meridional
language-name-se = saami setentrional
language-name-seh = sena
language-name-ses = koyraboro senni
language-name-sg = sango
language-name-sh = serbocroata
language-name-shi = tachelhit
language-name-shn = shan
language-name-si = cingalés
language-name-sk = eslovaco
language-name-sl = esloveno
language-name-sm = samoano
language-name-sma = saami meridional
language-name-smj = saami de Lule
language-name-smn = saami de Inari
language-name-sms = saami skolt
language-name-sn = shona
language-name-snk = soninke
language-name-so = somalí
language-name-sq = albanés
language-name-sr = serbio
language-name-srn = sranan tongo
language-name-ss = swazi
language-name-ssy = saho
language-name-st = sesotho
language-name-su = sundanés
language-name-suk = sukuma
language-name-sv = sueco
language-name-sw = suahili
language-name-sw_CD = suahili congolés
language-name-swb = comoriano
language-name-syr = siríaco
language-name-ta = támil
language-name-te = telugu
language-name-tem = temne
language-name-teo = teso
language-name-tet = tetun
language-name-tg = taxico
language-name-th = tailandés
language-name-ti = tigriña
language-name-tig = tigré
language-name-tk = turcomán
language-name-tl = tagalo
language-name-tlh = klingon
language-name-tn = tswana
language-name-to = tongano
language-name-tpi = tok pisin
language-name-tr = turco
language-name-trv = taroko
language-name-ts = tsonga
language-name-tt = tártaro
language-name-tum = tumbuka
language-name-tvl = tuvaluano
language-name-tw = twi
language-name-twq = tasawaq
language-name-ty = tahitiano
language-name-tyv = tuvaniano
language-name-tzm = tamazight de Marrocos central
language-name-udm = udmurto
language-name-ug = uigur
language-name-uk = ucraíno
language-name-umb = umbundu
language-name-und = lingua descoñecida
language-name-ur = urdú
language-name-uz = uzbeco
language-name-vai = vai
language-name-ve = venda
language-name-vi = vietnamita
language-name-vo = volapuk
language-name-vun = vunjo
language-name-wa = valón
language-name-wae = walser
language-name-wal = wolaytta
language-name-war = waray-waray
language-name-wbp = walrpiri
language-name-wo = wólof
language-name-xal = calmuco
language-name-xh = xosa
language-name-xog = soga
language-name-yav = yangben
language-name-ybb = yemba
language-name-yi = yiddish
language-name-yo = yoruba
language-name-yue = cantonés
language-name-zgh = tamazight marroquí estándar
language-name-zh = chinés
language-name-zh_Hans = chinés simplificado
language-name-zh_Hant = chinés tradicional
language-name-zu = zulú
language-name-zun = zuni
language-name-zxx = sen contido lingüístico
language-name-zza = zazaki
