language-name-ak = Kiakan
language-name-ar_001 = Kiarabu cha Dunia Kilichosanifishwa
language-name-arq = Kiarabu cha Aljeria
language-name-az = Kiazabajani
language-name-bug = Kibugini
language-name-gv = Kimanksi
language-name-gwi = Kigwichiin
language-name-hup = Kihupa
language-name-jbo = Kilojban
language-name-kac = Kikachin
language-name-khq = Kikoyra Chiini
language-name-kkj = Kikako
language-name-koi = Kikomipermyak
language-name-kru = Kikurukh
language-name-kum = Kikumyk
language-name-ky = Kikirigizi
language-name-lam = Kilamba
language-name-li = Kilimburgi
language-name-mak = mak
language-name-mdf = Kimoksha
language-name-mic = Kimikmaki
language-name-mk = Kimasedonia
language-name-moh = Kimohoki
language-name-mos = Kimossi
language-name-nnh = Kingiemboon
language-name-nqo = Kiinko
language-name-pcm = Pijini ya Nijeria
language-name-quc = Kikiiche
language-name-root = Kiroot
language-name-shu = Kiarabu cha Chadi
language-name-srn = Kitongo cha Sranan
language-name-swb = Kikomoro
language-name-syr = Kisiria
language-name-udm = Kiudumurti
language-name-wae = Kiwalser
language-name-yi = Kiyidi
