language-name-aa = afarski
language-name-ab = abhaski
language-name-ace = ačinski
language-name-ach = ačoli
language-name-ada = adangme
language-name-ady = adigejski
language-name-ae = avestički
language-name-af = afrikaans
language-name-afh = afrihili
language-name-agq = aghem
language-name-ain = ainuski
language-name-ak = akanski
language-name-akk = akadski
language-name-ale = aleutski
language-name-alt = južni altai
language-name-am = amharski
language-name-an = aragonski
language-name-ang = staroengleski
language-name-anp = angika
language-name-ar = arapski
language-name-ar_001 = moderni standardni arapski
language-name-arc = aramejski
language-name-arn = mapuche
language-name-arp = arapaho
language-name-ars = najdi arapski
language-name-arw = aravački
language-name-as = asamski
language-name-asa = asu
language-name-ast = asturijski
language-name-av = avarski
language-name-awa = awadhi
language-name-ay = ajmarski
language-name-az = azerbajdžanski
language-name-az_Arab = južnoazerbajdžanski
language-name-ba = baškirski
language-name-bal = belučki
language-name-ban = balijski
language-name-bas = basa
language-name-bax = bamunski
language-name-bbj = ghomala
language-name-be = bjeloruski
language-name-bej = beja
language-name-bem = bemba
language-name-bez = bena
language-name-bfd = bafut
language-name-bg = bugarski
language-name-bgn = zapadnobaludžijski
language-name-bho = bhojpuri
language-name-bi = bislama
language-name-bik = bikolski
language-name-bin = bini
language-name-bkm = kom
language-name-bla = siksika
language-name-bm = bambara
language-name-bn = bangla
language-name-bo = tibetski
language-name-br = bretonski
language-name-bra = braj
language-name-brx = bodo
language-name-bs = bosanski
language-name-bss = akoose
language-name-bua = burjatski
language-name-bug = buginski
language-name-bum = bulu
language-name-byn = blin
language-name-byv = medumba
language-name-ca = katalonski
language-name-cad = caddo
language-name-car = karipski
language-name-cay = cayuga
language-name-cch = atsam
language-name-ce = čečenski
language-name-ceb = cebuano
language-name-cgg = chiga
language-name-ch = chamorro
language-name-chb = čibča
language-name-chg = čagatajski
language-name-chk = chuukese
language-name-chm = marijski
language-name-chn = chinook žargon
language-name-cho = choctaw
language-name-chp = chipewyan
language-name-chr = čerokijski
language-name-chy = čejenski
language-name-ckb = soranski kurdski
language-name-co = korzički
language-name-cop = koptski
language-name-cr = cree
language-name-crh = krimski turski
language-name-crs = sejšelski kreolski
language-name-cs = češki
language-name-csb = kašupski
language-name-cu = crkvenoslavenski
language-name-cv = čuvaški
language-name-cy = velški
language-name-da = danski
language-name-dak = dakota jezik
language-name-dar = dargwa
language-name-dav = taita
language-name-de = njemački
language-name-de_AT = austrijski njemački
language-name-del = delavarski
language-name-den = slave
language-name-dgr = dogrib
language-name-din = dinka
language-name-dje = zarma
language-name-doi = dogri
language-name-dsb = donjolužički
language-name-dua = duala
language-name-dum = srednjonizozemski
language-name-dv = divehi
language-name-dyo = jola-fonyi
language-name-dyu = dyula
language-name-dz = dzongkha
language-name-dzg = dazaga
language-name-ebu = embu
language-name-ee = ewe
language-name-efi = efik
language-name-egy = staroegipatski
language-name-eka = ekajuk
language-name-el = grčki
language-name-elx = elamitski
language-name-en = engleski
language-name-en_AU = australski engleski
language-name-en_CA = kanadski engleski
language-name-en_GB = britanski engleski
language-name-en_US = američki engleski
language-name-enm = srednjoengleski
language-name-eo = esperanto
language-name-es = španjolski
language-name-es_419 = latinoamerički španjolski
language-name-es_ES = europski španjolski
language-name-es_MX = meksički španjolski
language-name-et = estonski
language-name-eu = baskijski
language-name-ewo = ewondo
language-name-fa = perzijski
language-name-fan = fang
language-name-fat = fanti
language-name-ff = fula
language-name-fi = finski
language-name-fil = filipinski
language-name-fj = fidžijski
language-name-fo = ferojski
language-name-fon = fon
language-name-fr = francuski
language-name-fr_CA = kanadski francuski
language-name-fr_CH = švicarski francuski
language-name-frc = kajunski francuski
language-name-frm = srednjofrancuski
language-name-fro = starofrancuski
language-name-frr = sjevernofrizijski
language-name-frs = istočnofrizijski
language-name-fur = furlanski
language-name-fy = zapadnofrizijski
language-name-ga = irski
language-name-gaa = ga
language-name-gag = gagauski
language-name-gan = gan kineski
language-name-gay = gayo
language-name-gba = gbaya
language-name-gd = škotski gaelski
language-name-gez = geez
language-name-gil = gilbertski
language-name-gl = galicijski
language-name-gmh = srednjogornjonjemački
language-name-gn = gvaranski
language-name-goh = starovisokonjemački
language-name-gon = gondi
language-name-gor = gorontalo
language-name-got = gotski
language-name-grb = grebo
language-name-grc = starogrčki
language-name-gsw = švicarski njemački
language-name-gu = gudžaratski
language-name-guz = gusii
language-name-gv = manski
language-name-gwi = gwich’in
language-name-ha = hausa
language-name-hai = haidi
language-name-hak = hakka kineski
language-name-haw = havajski
language-name-he = hebrejski
language-name-hi = hindski
language-name-hil = hiligaynonski
language-name-hit = hetitski
language-name-hmn = hmong
language-name-ho = hiri motu
language-name-hr = hrvatski
language-name-hsb = gornjolužički
language-name-hsn = xiang kineski
language-name-ht = haićanski kreolski
language-name-hu = mađarski
language-name-hup = hupa
language-name-hy = armenski
language-name-hz = herero
language-name-ia = interlingua
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indonezijski
language-name-ie = interligua
language-name-ig = igbo
language-name-ii = sichuan ji
language-name-ik = inupiaq
language-name-ilo = iloko
language-name-inh = ingušetski
language-name-io = ido
language-name-is = islandski
language-name-it = talijanski
language-name-iu = inuktitut
language-name-ja = japanski
language-name-jbo = lojban
language-name-jgo = ngomba
language-name-jmc = machame
language-name-jpr = judejsko-perzijski
language-name-jrb = judejsko-arapski
language-name-jv = javanski
language-name-ka = gruzijski
language-name-kaa = kara-kalpak
language-name-kab = kabilski
language-name-kac = kačinski
language-name-kaj = kaje
language-name-kam = kamba
language-name-kaw = kawi
language-name-kbd = kabardinski
language-name-kbl = kanembu
language-name-kcg = tyap
language-name-kde = makonde
language-name-kea = zelenortski
language-name-kfo = koro
language-name-kg = kongo
language-name-kha = khasi
language-name-kho = khotanese
language-name-khq = koyra chiini
language-name-ki = kikuyu
language-name-kj = kuanyama
language-name-kk = kazaški
language-name-kkj = kako
language-name-kl = kalaallisut
language-name-kln = kalenjin
language-name-km = kmerski
language-name-kmb = kimbundu
language-name-kn = karnatački
language-name-ko = korejski
language-name-koi = komi-permski
language-name-kok = konkani
language-name-kos = naurski
language-name-kpe = kpelle
language-name-kr = kanuri
language-name-krc = karachay-balkar
language-name-krl = karelijski
language-name-kru = kuruški
language-name-ks = kašmirski
language-name-ksb = shambala
language-name-ksf = bafia
language-name-ksh = kelnski
language-name-ku = kurdski
language-name-kum = kumyk
language-name-kut = kutenai
language-name-kv = komi
language-name-kw = kornski
language-name-ky = kirgiski
language-name-la = latinski
language-name-lad = ladino
language-name-lag = langi
language-name-lah = lahnda
language-name-lam = lamba
language-name-lb = luksemburški
language-name-lez = lezgiški
language-name-lg = ganda
language-name-li = limburški
language-name-lkt = lakota
language-name-ln = lingala
language-name-lo = laoski
language-name-lol = mongo
language-name-lou = lujzijanski kreolski
language-name-loz = lozi
language-name-lrc = sjevernolurski
language-name-lt = litavski
language-name-lu = luba-katanga
language-name-lua = luba-lulua
language-name-lui = luiseno
language-name-lun = lunda
language-name-luo = luo
language-name-lus = lushai
language-name-luy = luyia
language-name-lv = latvijski
language-name-mad = madurski
language-name-maf = mafa
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = makasar
language-name-man = mandingo
language-name-mas = masajski
language-name-mde = maba
language-name-mdf = moksha
language-name-mdr = mandar
language-name-men = mende
language-name-mer = meru
language-name-mfe = mauricijski kreolski
language-name-mg = malgaški
language-name-mga = srednjoirski
language-name-mgh = makhuwa-meetto
language-name-mgo = meta’
language-name-mh = maršalski
language-name-mi = maorski
language-name-mic = micmac
language-name-min = minangkabau
language-name-mk = makedonski
language-name-ml = malajalamski
language-name-mn = mongolski
language-name-mnc = mandžurski
language-name-mni = manipurski
language-name-moh = mohok
language-name-mos = mossi
language-name-mr = marathski
language-name-ms = malajski
language-name-mt = malteški
language-name-mua = mundang
language-name-mul = više jezika
language-name-mus = creek
language-name-mwl = mirandski
language-name-mwr = marwari
language-name-my = burmanski
language-name-mye = myene
language-name-myv = mordvinski
language-name-mzn = mazanderanski
language-name-na = nauru
language-name-nan = min nan kineski
language-name-nap = napolitanski
language-name-naq = nama
language-name-nb = norveški bokmål
language-name-nd = sjeverni ndebele
language-name-nds = donjonjemački
language-name-nds_NL = donjosaksonski
language-name-ne = nepalski
language-name-new = newari
language-name-ng = ndonga
language-name-nia = nias
language-name-niu = niujski
language-name-nl = nizozemski
language-name-nl_BE = flamanski
language-name-nmg = kwasio
language-name-nn = norveški nynorsk
language-name-nnh = ngiemboon
language-name-no = norveški
language-name-nog = nogajski
language-name-non = staronorveški
language-name-nqo = n’ko
language-name-nr = južni ndebele
language-name-nso = sjeverni sotski
language-name-nus = nuerski
language-name-nv = navajo
language-name-nwc = klasični newari
language-name-ny = njandža
language-name-nym = nyamwezi
language-name-nyn = nyankole
language-name-nyo = nyoro
language-name-nzi = nzima
language-name-oc = okcitanski
language-name-oj = ojibwa
language-name-om = oromski
language-name-or = orijski
language-name-os = osetski
language-name-osa = osage
language-name-ota = turski - otomanski
language-name-pa = pandžapski
language-name-pag = pangasinan
language-name-pal = pahlavi
language-name-pam = pampanga
language-name-pap = papiamento
language-name-pau = palauanski
language-name-pcm = nigerijski pidžin
language-name-peo = staroperzijski
language-name-phn = fenički
language-name-pi = pali
language-name-pl = poljski
language-name-pon = pohnpeian
language-name-prg = pruski
language-name-pro = staroprovansalski
language-name-ps = paštunski
language-name-pt = portugalski
language-name-pt_BR = brazilski portugalski
language-name-pt_PT = europski portugalski
language-name-qu = kečuanski
language-name-quc = kiče
language-name-raj = rajasthani
language-name-rap = rapa nui
language-name-rar = rarotonški
language-name-rm = retoromanski
language-name-rn = rundi
language-name-ro = rumunjski
language-name-ro_MD = moldavski
language-name-rof = rombo
language-name-rom = romski
language-name-root = korijenski
language-name-ru = ruski
language-name-rup = aromunski
language-name-rw = kinyarwanda
language-name-rwk = rwa
language-name-sa = sanskrtski
language-name-sad = sandawe
language-name-sah = jakutski
language-name-sam = samarijanski aramejski
language-name-saq = samburu
language-name-sas = sasak
language-name-sat = santalski
language-name-sba = ngambay
language-name-sbp = sangu
language-name-sc = sardski
language-name-scn = sicilijski
language-name-sco = škotski
language-name-sd = sindski
language-name-sdh = južnokurdski
language-name-se = sjeverni sami
language-name-see = seneca
language-name-seh = sena
language-name-sel = selkupski
language-name-ses = koyraboro senni
language-name-sg = sango
language-name-sga = staroirski
language-name-sh = srpsko-hrvatski
language-name-shi = tachelhit
language-name-shn = shan
language-name-shu = čadski arapski
language-name-si = sinhaleški
language-name-sid = sidamo
language-name-sk = slovački
language-name-sl = slovenski
language-name-sm = samoanski
language-name-sma = južni sami
language-name-smj = lule sami
language-name-smn = inari sami
language-name-sms = skolt sami
language-name-sn = shona
language-name-snk = soninke
language-name-so = somalski
language-name-sog = sogdien
language-name-sq = albanski
language-name-sr = srpski
language-name-srn = sranan tongo
language-name-srr = serer
language-name-ss = svati
language-name-ssy = saho
language-name-st = sesotski
language-name-su = sundanski
language-name-suk = sukuma
language-name-sus = susu
language-name-sux = sumerski
language-name-sv = švedski
language-name-sw = svahili
language-name-sw_CD = kongoanski svahili
language-name-swb = komorski
language-name-syc = klasični sirski
language-name-syr = sirijski
language-name-ta = tamilski
language-name-te = teluški
language-name-tem = temne
language-name-teo = teso
language-name-ter = tereno
language-name-tet = tetum
language-name-tg = tadžički
language-name-th = tajlandski
language-name-ti = tigrinja
language-name-tig = tigriški
language-name-tiv = tiv
language-name-tk = turkmenski
language-name-tkl = tokelaunski
language-name-tl = tagalog
language-name-tlh = klingonski
language-name-tli = tlingit
language-name-tmh = tamašečki
language-name-tn = cvana
language-name-to = tonganski
language-name-tog = nyasa tonga
language-name-tpi = tok pisin
language-name-tr = turski
language-name-trv = taroko
language-name-ts = tsonga
language-name-tsi = tsimshian
language-name-tt = tatarski
language-name-tum = tumbuka
language-name-tvl = tuvaluanski
language-name-tw = twi
language-name-twq = tasawaq
language-name-ty = tahićanski
language-name-tyv = tuvinski
language-name-udm = udmurtski
language-name-ug = ujgurski
language-name-uga = ugaritski
language-name-uk = ukrajinski
language-name-umb = umbundu
language-name-und = nepoznati jezik
language-name-ur = urdski
language-name-uz = uzbečki
language-name-vai = vai
language-name-ve = venda
language-name-vi = vijetnamski
language-name-vo = volapük
language-name-vot = votski
language-name-vun = vunjo
language-name-wa = valonski
language-name-wae = walserski
language-name-wal = walamo
language-name-war = waray
language-name-was = washo
language-name-wbp = warlpiri
language-name-wo = volof
language-name-wuu = wu kineski
language-name-xal = kalmyk
language-name-xh = xhosa
language-name-xog = soga
language-name-yao = yao
language-name-yap = japski
language-name-yav = yangben
language-name-ybb = yemba
language-name-yi = jidiš
language-name-yo = jorupski
language-name-yue = kantonski
language-name-za = zhuang
language-name-zap = zapotečki
language-name-zbl = Blissovi simboli
language-name-zen = zenaga
language-name-zgh = standardni marokanski tamašek
language-name-zh = kineski
language-name-zu = zulu
language-name-zun = zuni
language-name-zxx = bez jezičnog sadržaja
language-name-zza = zazaki
