language-name-aa = Tiếng Afar
language-name-ab = Tiếng Abkhazia
language-name-ace = Tiếng Achinese
language-name-ach = Tiếng Acoli
language-name-ada = Tiếng Adangme
language-name-ady = Tiếng Adyghe
language-name-ae = Tiếng Avestan
language-name-af = Tiếng Afrikaans
language-name-afh = Tiếng Afrihili
language-name-agq = Tiếng Aghem
language-name-ain = Tiếng Ainu
language-name-ak = Tiếng Akan
language-name-akk = Tiếng Akkadia
language-name-akz = Tiếng Alabama
language-name-ale = Tiếng Aleut
language-name-aln = Tiếng Gheg Albani
language-name-alt = Tiếng Altai Miền Nam
language-name-am = Tiếng Amharic
language-name-an = Tiếng Aragon
language-name-ang = Tiếng Anh cổ
language-name-anp = Tiếng Angika
language-name-ar = Tiếng Ả Rập
language-name-ar_001 = Tiếng Ả Rập Hiện đại
language-name-arc = Tiếng Aramaic
language-name-arn = Tiếng Mapuche
language-name-aro = Tiếng Araona
language-name-arp = Tiếng Arapaho
language-name-arq = Tiếng Ả Rập Algeria
language-name-ars = Tiếng Ả Rập Najdi
language-name-arw = Tiếng Arawak
language-name-arz = Tiếng Ả Rập Ai Cập
language-name-as = Tiếng Assam
language-name-asa = Tiếng Asu
language-name-ase = Ngôn ngữ Ký hiệu Mỹ
language-name-ast = Tiếng Asturias
language-name-av = Tiếng Avaric
language-name-awa = Tiếng Awadhi
language-name-ay = Tiếng Aymara
language-name-az = Tiếng Azerbaijan
language-name-ba = Tiếng Bashkir
language-name-bal = Tiếng Baluchi
language-name-ban = Tiếng Bali
language-name-bar = Tiếng Bavaria
language-name-bas = Tiếng Basaa
language-name-bax = Tiếng Bamun
language-name-bbc = Tiếng Batak Toba
language-name-bbj = Tiếng Ghomala
language-name-be = Tiếng Belarus
language-name-bej = Tiếng Beja
language-name-bem = Tiếng Bemba
language-name-bew = Tiếng Betawi
language-name-bez = Tiếng Bena
language-name-bfd = Tiếng Bafut
language-name-bfq = Tiếng Badaga
language-name-bg = Tiếng Bulgaria
language-name-bgn = Tiếng Tây Balochi
language-name-bho = Tiếng Bhojpuri
language-name-bi = Tiếng Bislama
language-name-bik = Tiếng Bikol
language-name-bin = Tiếng Bini
language-name-bjn = Tiếng Banjar
language-name-bkm = Tiếng Kom
language-name-bla = Tiếng Siksika
language-name-bm = Tiếng Bambara
language-name-bn = Tiếng Bangla
language-name-bo = Tiếng Tây Tạng
language-name-bpy = Tiếng Bishnupriya
language-name-bqi = Tiếng Bakhtiari
language-name-br = Tiếng Breton
language-name-bra = Tiếng Braj
language-name-brh = Tiếng Brahui
language-name-brx = Tiếng Bodo
language-name-bs = Tiếng Bosnia
language-name-bss = Tiếng Akoose
language-name-bua = Tiếng Buriat
language-name-bug = Tiếng Bugin
language-name-bum = Tiếng Bulu
language-name-byn = Tiếng Blin
language-name-byv = Tiếng Medumba
language-name-ca = Tiếng Catalan
language-name-cad = Tiếng Caddo
language-name-car = Tiếng Carib
language-name-cay = Tiếng Cayuga
language-name-cch = Tiếng Atsam
language-name-ce = Tiếng Chechen
language-name-ceb = Tiếng Cebuano
language-name-cgg = Tiếng Chiga
language-name-ch = Tiếng Chamorro
language-name-chb = Tiếng Chibcha
language-name-chg = Tiếng Chagatai
language-name-chk = Tiếng Chuuk
language-name-chm = Tiếng Mari
language-name-chn = Biệt ngữ Chinook
language-name-cho = Tiếng Choctaw
language-name-chp = Tiếng Chipewyan
language-name-chr = Tiếng Cherokee
language-name-chy = Tiếng Cheyenne
language-name-ckb = Tiếng Kurd Miền Trung
language-name-co = Tiếng Corsica
language-name-cop = Tiếng Coptic
language-name-cps = Tiếng Capiznon
language-name-cr = Tiếng Cree
language-name-crh = Tiếng Thổ Nhĩ Kỳ Crimean
language-name-crs = Tiếng Pháp Seselwa Creole
language-name-cs = Tiếng Séc
language-name-csb = Tiếng Kashubia
language-name-cu = Tiếng Slavơ Nhà thờ
language-name-cv = Tiếng Chuvash
language-name-cy = Tiếng Wales
language-name-da = Tiếng Đan Mạch
language-name-dak = Tiếng Dakota
language-name-dar = Tiếng Dargwa
language-name-dav = Tiếng Taita
language-name-de = Tiếng Đức
language-name-del = Tiếng Delaware
language-name-den = Tiếng Slave
language-name-dgr = Tiếng Dogrib
language-name-din = Tiếng Dinka
language-name-dje = Tiếng Zarma
language-name-doi = Tiếng Dogri
language-name-dsb = Tiếng Hạ Sorbia
language-name-dtp = Tiếng Dusun Miền Trung
language-name-dua = Tiếng Duala
language-name-dum = Tiếng Hà Lan Trung cổ
language-name-dv = Tiếng Divehi
language-name-dyo = Tiếng Jola-Fonyi
language-name-dyu = Tiếng Dyula
language-name-dz = Tiếng Dzongkha
language-name-dzg = Tiếng Dazaga
language-name-ebu = Tiếng Embu
language-name-ee = Tiếng Ewe
language-name-efi = Tiếng Efik
language-name-egl = Tiếng Emilia
language-name-egy = Tiếng Ai Cập cổ
language-name-eka = Tiếng Ekajuk
language-name-el = Tiếng Hy Lạp
language-name-elx = Tiếng Elamite
language-name-en = Tiếng Anh
language-name-enm = Tiếng Anh Trung cổ
language-name-eo = Tiếng Quốc Tế Ngữ
language-name-es = Tiếng Tây Ban Nha
language-name-esu = Tiếng Yupik Miền Trung
language-name-et = Tiếng Estonia
language-name-eu = Tiếng Basque
language-name-ewo = Tiếng Ewondo
language-name-ext = Tiếng Extremadura
language-name-fa = Tiếng Ba Tư
language-name-fan = Tiếng Fang
language-name-fat = Tiếng Fanti
language-name-ff = Tiếng Fulah
language-name-fi = Tiếng Phần Lan
language-name-fil = Tiếng Philippines
language-name-fj = Tiếng Fiji
language-name-fo = Tiếng Faroe
language-name-fon = Tiếng Fon
language-name-fr = Tiếng Pháp
language-name-frc = Tiếng Pháp Cajun
language-name-frm = Tiếng Pháp Trung cổ
language-name-fro = Tiếng Pháp cổ
language-name-frp = Tiếng Arpitan
language-name-frr = Tiếng Frisia Miền Bắc
language-name-frs = Tiếng Frisian Miền Đông
language-name-fur = Tiếng Friulian
language-name-fy = Tiếng Frisia
language-name-ga = Tiếng Ireland
language-name-gaa = Tiếng Ga
language-name-gag = Tiếng Gagauz
language-name-gan = Tiếng Cám
language-name-gay = Tiếng Gayo
language-name-gba = Tiếng Gbaya
language-name-gd = Tiếng Gael Scotland
language-name-gez = Tiếng Geez
language-name-gil = Tiếng Gilbert
language-name-gl = Tiếng Galician
language-name-glk = Tiếng Gilaki
language-name-gmh = Tiếng Thượng Giéc-man Trung cổ
language-name-gn = Tiếng Guarani
language-name-goh = Tiếng Thượng Giéc-man cổ
language-name-gom = Tiếng Goan Konkani
language-name-gon = Tiếng Gondi
language-name-gor = Tiếng Gorontalo
language-name-got = Tiếng Gô-tích
language-name-grb = Tiếng Grebo
language-name-grc = Tiếng Hy Lạp cổ
language-name-gu = Tiếng Gujarati
language-name-gur = Tiếng Frafra
language-name-guz = Tiếng Gusii
language-name-gv = Tiếng Manx
language-name-gwi = Tiếng Gwichʼin
language-name-ha = Tiếng Hausa
language-name-hai = Tiếng Haida
language-name-hak = Tiếng Khách Gia
language-name-haw = Tiếng Hawaii
language-name-he = Tiếng Do Thái
language-name-hi = Tiếng Hindi
language-name-hif = Tiếng Fiji Hindi
language-name-hil = Tiếng Hiligaynon
language-name-hit = Tiếng Hittite
language-name-hmn = Tiếng Hmông
language-name-ho = Tiếng Hiri Motu
language-name-hr = Tiếng Croatia
language-name-hsb = Tiếng Thượng Sorbia
language-name-hsn = Tiếng Tương
language-name-ht = Tiếng Haiti
language-name-hu = Tiếng Hungary
language-name-hup = Tiếng Hupa
language-name-hy = Tiếng Armenia
language-name-hz = Tiếng Herero
language-name-ia = Tiếng Khoa Học Quốc Tế
language-name-iba = Tiếng Iban
language-name-ibb = Tiếng Ibibio
language-name-id = Tiếng Indonesia
language-name-ie = Tiếng Interlingue
language-name-ig = Tiếng Igbo
language-name-ii = Tiếng Di Tứ Xuyên
language-name-ik = Tiếng Inupiaq
language-name-ilo = Tiếng Iloko
language-name-inh = Tiếng Ingush
language-name-io = Tiếng Ido
language-name-is = Tiếng Iceland
language-name-it = Tiếng Italy
language-name-iu = Tiếng Inuktitut
language-name-izh = Tiếng Ingria
language-name-ja = Tiếng Nhật
language-name-jam = Tiếng Anh Jamaica Creole
language-name-jbo = Tiếng Lojban
language-name-jgo = Tiếng Ngomba
language-name-jmc = Tiếng Machame
language-name-jpr = Tiếng Judeo-Ba Tư
language-name-jrb = Tiếng Judeo-Ả Rập
language-name-jut = Tiếng Jutish
language-name-jv = Tiếng Java
language-name-ka = Tiếng Georgia
language-name-kaa = Tiếng Kara-Kalpak
language-name-kab = Tiếng Kabyle
language-name-kac = Tiếng Kachin
language-name-kaj = Tiếng Jju
language-name-kam = Tiếng Kamba
language-name-kaw = Tiếng Kawi
language-name-kbd = Tiếng Kabardian
language-name-kbl = Tiếng Kanembu
language-name-kcg = Tiếng Tyap
language-name-kde = Tiếng Makonde
language-name-kea = Tiếng Kabuverdianu
language-name-kfo = Tiếng Koro
language-name-kg = Tiếng Kongo
language-name-kha = Tiếng Khasi
language-name-kho = Tiếng Khotan
language-name-khq = Tiếng Koyra Chiini
language-name-ki = Tiếng Kikuyu
language-name-kj = Tiếng Kuanyama
language-name-kk = Tiếng Kazakh
language-name-kkj = Tiếng Kako
language-name-kl = Tiếng Kalaallisut
language-name-kln = Tiếng Kalenjin
language-name-km = Tiếng Khmer
language-name-kmb = Tiếng Kimbundu
language-name-kn = Tiếng Kannada
language-name-ko = Tiếng Hàn
language-name-koi = Tiếng Komi-Permyak
language-name-kok = Tiếng Konkani
language-name-kos = Tiếng Kosrae
language-name-kpe = Tiếng Kpelle
language-name-kr = Tiếng Kanuri
language-name-krc = Tiếng Karachay-Balkar
language-name-krl = Tiếng Karelian
language-name-kru = Tiếng Kurukh
language-name-ks = Tiếng Kashmir
language-name-ksb = Tiếng Shambala
language-name-ksf = Tiếng Bafia
language-name-ksh = Tiếng Cologne
language-name-ku = Tiếng Kurd
language-name-kum = Tiếng Kumyk
language-name-kut = Tiếng Kutenai
language-name-kv = Tiếng Komi
language-name-kw = Tiếng Cornwall
language-name-ky = Tiếng Kyrgyz
language-name-la = Tiếng La-tinh
language-name-lad = Tiếng Ladino
language-name-lag = Tiếng Langi
language-name-lah = Tiếng Lahnda
language-name-lam = Tiếng Lamba
language-name-lb = Tiếng Luxembourg
language-name-lez = Tiếng Lezghian
language-name-lg = Tiếng Ganda
language-name-li = Tiếng Limburg
language-name-lkt = Tiếng Lakota
language-name-ln = Tiếng Lingala
language-name-lo = Tiếng Lào
language-name-lol = Tiếng Mongo
language-name-lou = Tiếng Creole Louisiana
language-name-loz = Tiếng Lozi
language-name-lrc = Tiếng Bắc Luri
language-name-lt = Tiếng Litva
language-name-lu = Tiếng Luba-Katanga
language-name-lua = Tiếng Luba-Lulua
language-name-lui = Tiếng Luiseno
language-name-lun = Tiếng Lunda
language-name-luo = Tiếng Luo
language-name-lus = Tiếng Lushai
language-name-luy = Tiếng Luyia
language-name-lv = Tiếng Latvia
language-name-mad = Tiếng Madura
language-name-maf = Tiếng Mafa
language-name-mag = Tiếng Magahi
language-name-mai = Tiếng Maithili
language-name-mak = Tiếng Makasar
language-name-man = Tiếng Mandingo
language-name-mas = Tiếng Masai
language-name-mde = Tiếng Maba
language-name-mdf = Tiếng Moksha
language-name-mdr = Tiếng Mandar
language-name-men = Tiếng Mende
language-name-mer = Tiếng Meru
language-name-mfe = Tiếng Morisyen
language-name-mg = Tiếng Malagasy
language-name-mga = Tiếng Ai-len Trung cổ
language-name-mgh = Tiếng Makhuwa-Meetto
language-name-mgo = Tiếng Meta’
language-name-mh = Tiếng Marshall
language-name-mi = Tiếng Maori
language-name-mic = Tiếng Micmac
language-name-min = Tiếng Minangkabau
language-name-mk = Tiếng Macedonia
language-name-ml = Tiếng Malayalam
language-name-mn = Tiếng Mông Cổ
language-name-mnc = Tiếng Mãn Châu
language-name-mni = Tiếng Manipuri
language-name-moh = Tiếng Mohawk
language-name-mos = Tiếng Mossi
language-name-mr = Tiếng Marathi
language-name-ms = Tiếng Mã Lai
language-name-mt = Tiếng Malta
language-name-mua = Tiếng Mundang
language-name-mul = Nhiều Ngôn ngữ
language-name-mus = Tiếng Creek
language-name-mwl = Tiếng Miranda
language-name-mwr = Tiếng Marwari
language-name-my = Tiếng Miến Điện
language-name-mye = Tiếng Myene
language-name-myv = Tiếng Erzya
language-name-mzn = Tiếng Mazanderani
language-name-na = Tiếng Nauru
language-name-nan = Tiếng Mân Nam
language-name-nap = Tiếng Napoli
language-name-naq = Tiếng Nama
language-name-nd = Tiếng Ndebele Miền Bắc
language-name-nds = Tiếng Hạ Giéc-man
language-name-nds_NL = Tiếng Hạ Saxon
language-name-ne = Tiếng Nepal
language-name-new = Tiếng Newari
language-name-ng = Tiếng Ndonga
language-name-nia = Tiếng Nias
language-name-niu = Tiếng Niuean
language-name-njo = Tiếng Ao Naga
language-name-nl = Tiếng Hà Lan
language-name-nl_BE = Tiếng Flemish
language-name-nmg = Tiếng Kwasio
language-name-nnh = Tiếng Ngiemboon
language-name-no = Tiếng Na Uy
language-name-nog = Tiếng Nogai
language-name-non = Tiếng Na Uy cổ
language-name-nqo = Tiếng N’Ko
language-name-nr = Tiếng Ndebele Miền Nam
language-name-nso = Tiếng Sotho Miền Bắc
language-name-nus = Tiếng Nuer
language-name-nv = Tiếng Navajo
language-name-nwc = Tiếng Newari cổ
language-name-ny = Tiếng Nyanja
language-name-nym = Tiếng Nyamwezi
language-name-nyn = Tiếng Nyankole
language-name-nyo = Tiếng Nyoro
language-name-nzi = Tiếng Nzima
language-name-oc = Tiếng Occitan
language-name-oj = Tiếng Ojibwa
language-name-om = Tiếng Oromo
language-name-or = Tiếng Odia
language-name-os = Tiếng Ossetic
language-name-osa = Tiếng Osage
language-name-ota = Tiếng Thổ Nhĩ Kỳ Ottoman
language-name-pa = Tiếng Punjab
language-name-pag = Tiếng Pangasinan
language-name-pal = Tiếng Pahlavi
language-name-pam = Tiếng Pampanga
language-name-pap = Tiếng Papiamento
language-name-pau = Tiếng Palauan
language-name-pcm = Tiếng Nigeria Pidgin
language-name-peo = Tiếng Ba Tư cổ
language-name-phn = Tiếng Phoenicia
language-name-pi = Tiếng Pali
language-name-pl = Tiếng Ba Lan
language-name-pon = Tiếng Pohnpeian
language-name-prg = Tiếng Prussia
language-name-pro = Tiếng Provençal cổ
language-name-ps = Tiếng Pashto
language-name-pt = Tiếng Bồ Đào Nha
language-name-qu = Tiếng Quechua
language-name-quc = Tiếng Kʼicheʼ
language-name-qug = Tiếng Quechua ở Cao nguyên Chimborazo
language-name-raj = Tiếng Rajasthani
language-name-rap = Tiếng Rapanui
language-name-rar = Tiếng Rarotongan
language-name-rm = Tiếng Romansh
language-name-rn = Tiếng Rundi
language-name-ro = Tiếng Romania
language-name-ro_MD = Tiếng Moldova
language-name-rof = Tiếng Rombo
language-name-rom = Tiếng Romany
language-name-root = Tiếng Root
language-name-ru = Tiếng Nga
language-name-rup = Tiếng Aromania
language-name-rw = Tiếng Kinyarwanda
language-name-rwk = Tiếng Rwa
language-name-sa = Tiếng Phạn
language-name-sad = Tiếng Sandawe
language-name-sah = Tiếng Sakha
language-name-sam = Tiếng Samaritan Aramaic
language-name-saq = Tiếng Samburu
language-name-sas = Tiếng Sasak
language-name-sat = Tiếng Santali
language-name-sba = Tiếng Ngambay
language-name-sbp = Tiếng Sangu
language-name-sc = Tiếng Sardinia
language-name-scn = Tiếng Sicilia
language-name-sco = Tiếng Scots
language-name-sd = Tiếng Sindhi
language-name-sdh = Tiếng Kurd Miền Nam
language-name-se = Tiếng Sami Miền Bắc
language-name-see = Tiếng Seneca
language-name-seh = Tiếng Sena
language-name-sel = Tiếng Selkup
language-name-ses = Tiếng Koyraboro Senni
language-name-sg = Tiếng Sango
language-name-sga = Tiếng Ai-len cổ
language-name-sh = Tiếng Serbo-Croatia
language-name-shi = Tiếng Tachelhit
language-name-shn = Tiếng Shan
language-name-shu = Tiếng Ả-Rập Chad
language-name-si = Tiếng Sinhala
language-name-sid = Tiếng Sidamo
language-name-sk = Tiếng Slovak
language-name-sl = Tiếng Slovenia
language-name-sm = Tiếng Samoa
language-name-sma = Tiếng Sami Miền Nam
language-name-smj = Tiếng Lule Sami
language-name-smn = Tiếng Inari Sami
language-name-sms = Tiếng Skolt Sami
language-name-sn = Tiếng Shona
language-name-snk = Tiếng Soninke
language-name-so = Tiếng Somali
language-name-sog = Tiếng Sogdien
language-name-sq = Tiếng Albania
language-name-sr = Tiếng Serbia
language-name-srn = Tiếng Sranan Tongo
language-name-srr = Tiếng Serer
language-name-ss = Tiếng Swati
language-name-ssy = Tiếng Saho
language-name-st = Tiếng Sotho Miền Nam
language-name-su = Tiếng Sunda
language-name-suk = Tiếng Sukuma
language-name-sus = Tiếng Susu
language-name-sux = Tiếng Sumeria
language-name-sv = Tiếng Thụy Điển
language-name-sw = Tiếng Swahili
language-name-sw_CD = Tiếng Swahili Congo
language-name-swb = Tiếng Cômo
language-name-syc = Tiếng Syriac cổ
language-name-syr = Tiếng Syriac
language-name-ta = Tiếng Tamil
language-name-te = Tiếng Telugu
language-name-tem = Tiếng Timne
language-name-teo = Tiếng Teso
language-name-ter = Tiếng Tereno
language-name-tet = Tiếng Tetum
language-name-tg = Tiếng Tajik
language-name-th = Tiếng Thái
language-name-ti = Tiếng Tigrinya
language-name-tig = Tiếng Tigre
language-name-tiv = Tiếng Tiv
language-name-tk = Tiếng Turkmen
language-name-tkl = Tiếng Tokelau
language-name-tl = Tiếng Tagalog
language-name-tlh = Tiếng Klingon
language-name-tli = Tiếng Tlingit
language-name-tmh = Tiếng Tamashek
language-name-tn = Tiếng Tswana
language-name-to = Tiếng Tonga
language-name-tog = Tiếng Nyasa Tonga
language-name-tpi = Tiếng Tok Pisin
language-name-tr = Tiếng Thổ Nhĩ Kỳ
language-name-trv = Tiếng Taroko
language-name-ts = Tiếng Tsonga
language-name-tsi = Tiếng Tsimshian
language-name-tt = Tiếng Tatar
language-name-tum = Tiếng Tumbuka
language-name-tvl = Tiếng Tuvalu
language-name-tw = Tiếng Twi
language-name-twq = Tiếng Tasawaq
language-name-ty = Tiếng Tahiti
language-name-tyv = Tiếng Tuvinian
language-name-tzm = Tiếng Tamazight Miền Trung Ma-rốc
language-name-udm = Tiếng Udmurt
language-name-ug = Tiếng Uyghur
language-name-uga = Tiếng Ugaritic
language-name-uk = Tiếng Ucraina
language-name-umb = Tiếng Umbundu
language-name-und = Ngôn ngữ không xác định
language-name-ur = Tiếng Urdu
language-name-uz = Tiếng Uzbek
language-name-vai = Tiếng Vai
language-name-ve = Tiếng Venda
language-name-vi = Tiếng Việt
language-name-vo = Tiếng Volapük
language-name-vot = Tiếng Votic
language-name-vun = Tiếng Vunjo
language-name-wa = Tiếng Walloon
language-name-wae = Tiếng Walser
language-name-wal = Tiếng Walamo
language-name-war = Tiếng Waray
language-name-was = Tiếng Washo
language-name-wbp = Tiếng Warlpiri
language-name-wo = Tiếng Wolof
language-name-wuu = Tiếng Ngô
language-name-xal = Tiếng Kalmyk
language-name-xh = Tiếng Xhosa
language-name-xog = Tiếng Soga
language-name-yao = Tiếng Yao
language-name-yap = Tiếng Yap
language-name-yav = Tiếng Yangben
language-name-ybb = Tiếng Yemba
language-name-yi = Tiếng Yiddish
language-name-yo = Tiếng Yoruba
language-name-yue = Tiếng Quảng Đông
language-name-za = Tiếng Choang
language-name-zap = Tiếng Zapotec
language-name-zbl = Ký hiệu Blissymbols
language-name-zen = Tiếng Zenaga
language-name-zgh = Tiếng Tamazight Chuẩn của Ma-rốc
language-name-zh = Tiếng Trung
language-name-zu = Tiếng Zulu
language-name-zun = Tiếng Zuni
language-name-zxx = Không có nội dung ngôn ngữ
language-name-zza = Tiếng Zaza
