language-name-aa = اَفار
language-name-ab = اَبخازِیان
language-name-ace = اَچَےنیٖز
language-name-ach = اَکولی
language-name-ada = اَدَنٛگمیے
language-name-ady = اَدَیٖگیے
language-name-ae = اَویستَن
language-name-af = اَفریٖکانٛز
language-name-afh = اَفرِہِلی
language-name-ain = اینوٗ
language-name-ak = اَکان
language-name-akk = اَکادِیَن
language-name-ale = اَلویتی
language-name-alt = جنوٗبی اَلتایی
language-name-am = اَمہاری
language-name-an = اَراگونی
language-name-ang = پرون اَنٛگریٖزی
language-name-anp = اَنٛگِکا
language-name-ar = عربی
language-name-arc = اَرَمیک
language-name-arn = ایرو کونِیَن
language-name-arp = اَراپاہو
language-name-arw = اَراوَک
language-name-as = اسٲمۍ
language-name-ast = ایسٹوٗریَن
language-name-av = اَوارِک
language-name-awa = اَوَدی
language-name-ay = ایمارا
language-name-az = اَزَربیجانی
language-name-ba = بَشکیٖر
language-name-bal = بَلوٗچی
language-name-ban = بالِنیٖز
language-name-bas = باسا
language-name-be = بیلَروٗشیَن
language-name-bej = بیجا
language-name-bem = بیٚمبا
language-name-bg = بینا
language-name-bho = بوجپوٗری
language-name-bi = بِسلاما
language-name-bik = بِکول
language-name-bin = بِنی
language-name-bla = سِکسِکا
language-name-bm = بَمبارا
language-name-bn = بَنٛگٲلۍ
language-name-bo = تِبتی
language-name-br = بریٹَن
language-name-bra = برٛج
language-name-bs = بوسنِیَن
language-name-bua = بُرِیَت
language-name-bug = بَگنیٖز
language-name-byn = بٕلِن
language-name-ca = کَتلان
language-name-cad = کاڈو
language-name-car = کارِب
language-name-cch = اتسَم
language-name-ce = چیچَن
language-name-ceb = سیباونو
language-name-ch = کَمورو
language-name-chb = چیٖبچا
language-name-chg = چھَگتاے
language-name-chk = چُکیٖز
language-name-chm = ماری
language-name-chn = چِنوٗک جارگَن
language-name-cho = چوکتَو
language-name-chp = شیپویان
language-name-chr = چیٚروکی
language-name-chy = شییون
language-name-co = کارسِکَن
language-name-cop = کاپٹِک
language-name-cr = کری
language-name-crh = کرٕمیٖن تُرکی
language-name-cs = چیٚک
language-name-csb = کَشوٗبِیَن
language-name-cu = چٔرچ سلاوِک
language-name-cv = چُواش
language-name-cy = ویٚلش
language-name-da = ڈینِش
language-name-dak = ڈکوٹا
language-name-dar = دَرگوا
language-name-de = جٔرمَن
language-name-de_AT = آسٹرِیَن جٔرمَن
language-name-de_CH = سٕوِس ہاےجٔرمَن
language-name-del = ڈیٚلوییَر
language-name-den = سلیو
language-name-dgr = ڈاگرِب
language-name-din = ڈِنکا
language-name-doi = ڈوگری
language-name-dsb = بوٚنِم ساربِیَن
language-name-dua = دُوالا
language-name-dum = وَستی پُرتُگالی
language-name-dv = دِویہی
language-name-dyu = ڈِیوٗلا
language-name-dz = زونٛگکھا
language-name-ee = ایٖو
language-name-efi = ایٚفِک
language-name-egy = قدیٖمی مِصری
language-name-eka = ایٚکاجُک
language-name-el = یوٗنٲنی
language-name-elx = ایٚلامایِٹ
language-name-en = اَنٛگیٖزۍ
language-name-en_AU = آسٹریلیَن اَنٛگریٖزۍ
language-name-en_CA = کینَڈِیٲیی اَنٛگریٖزۍ
language-name-en_GB = بَرطانوی اَنٛگریٖزۍ
language-name-en_US = یوٗ ایٚس اَنٛگریٖزۍ
language-name-enm = وَسطی اَنٛگریٖزۍ
language-name-eo = ایٚسپَرینٹو
language-name-es = سپینِش
language-name-es_419 = لیٹٕن امریٖکی سپینِش
language-name-es_ES = لِبیریَن سپینِش
language-name-et = ایٚسٹونیَن
language-name-eu = باسک
language-name-ewo = ایٚوونڈو
language-name-fa = فارسی
language-name-fan = فینٛگ
language-name-fat = فانٹی
language-name-ff = فُلاہ
language-name-fi = فِنِش
language-name-fil = فِلِپیٖنو
language-name-fj = فِجیَن
language-name-fo = فَروس
language-name-fon = فون
language-name-fr = فریٚنچ
language-name-fr_CA = کَنیڈیَن فریٚنچ
language-name-fr_CH = سٕوٕس فریٚنچ
language-name-frm = وسطی فریٚنچ
language-name-fro = پرون فریٚنچ
language-name-frr = شُمٲلی فرِشیَن
language-name-frs = مشرِقی فرِشیَن
language-name-fur = فروٗلِیَن
language-name-fy = مغربی فرِشیَن
language-name-ga = اَیرِش
language-name-gaa = گا
language-name-gay = گیےیو
language-name-gba = گبایا
language-name-gd = سکوٹِش گیےلِک
language-name-gez = گیٖز
language-name-gil = گِلبٔرٹیٖز
language-name-gl = گیلِشِیَن
language-name-gmh = وَسطی ہاے جٔرمَن
language-name-gn = گُوارَنی
language-name-goh = پرون ہاے جٔرمَن
language-name-gon = گوندی
language-name-gor = گورینٹیلو
language-name-got = گوتھِک
language-name-grb = گرِبو
language-name-grc = قدیٖم یوٗنٲنی
language-name-gsw = سٕوِس جٔرمَن
language-name-gu = گُجرٲتی
language-name-gv = مینٛکس
language-name-gwi = گُوِچ اِن
language-name-ha = ہاوسا
language-name-hai = ہَیدا
language-name-haw = ہوایِیَن
language-name-he = عبرٲنۍ
language-name-hi = ہِندی
language-name-hil = ہِلیٖگینَن
language-name-hit = ہِتایِت
language-name-hmn = ہمونٛگ
language-name-ho = ہِری موتوٗ
language-name-hr = کروشِیَن
language-name-hsb = ہیٚرِم ساربِیَن
language-name-ht = ہیتِیاں
language-name-hu = ہَنٛگیریَن
language-name-hup = ہُپا
language-name-hy = اَرمینیَن
language-name-hz = ہیٚریٖرو
language-name-ia = اِنٹَرلِنٛگوا
language-name-iba = اِبان
language-name-id = اِنڈونیشیا
language-name-ie = اِنٹَر لِنٛنگویے
language-name-ig = اِگبو
language-name-ii = سِچوان یٖی
language-name-ik = اِنُپِیاک
language-name-ilo = اِلوکو
language-name-inh = اِنٛگُش
language-name-io = اِڈو
language-name-is = آیِسلینڈِک
language-name-it = اِٹیلیَن
language-name-iu = اِنُکتِتوٗ
language-name-ja = جاپٲنۍ
language-name-jbo = لوجبان
language-name-jpr = جوڈیو فارسی
language-name-jrb = جوڈیو عربی
language-name-jv = جَوَنیٖز
language-name-ka = جارجِیَن
language-name-kaa = کارا کَلپَک
language-name-kab = کَبایِل
language-name-kac = کاچِن
language-name-kaj = جُوٗ
language-name-kam = کامبا
language-name-kaw = کَوی
language-name-kbd = کَبارڈِیَن
language-name-kcg = تَیَپ
language-name-kfo = کورو
language-name-kg = کونٛگو
language-name-kha = کھاسی
language-name-kho = کھوتَنیٖز
language-name-ki = کِکُیوٗ
language-name-kj = کُوانیاما
language-name-kk = کازَخ
language-name-kl = کَلالِسُت
language-name-km = خَمیر
language-name-kmb = کِمبُندوٗ
language-name-kn = کَنَڑ
language-name-ko = کوریَن
language-name-kok = کونکَنی
language-name-kos = کوسرییَن
language-name-kpe = کَپیلی
language-name-kr = کَنوٗری
language-name-krc = کراچیے بَلکار
language-name-krl = کَریلِیَن
language-name-kru = کُرُکھ
language-name-ks = کٲشُر
language-name-ku = کُردِش
language-name-kum = کُمِک
language-name-kut = کُتینَے
language-name-kv = کومی
language-name-kw = کورنِش
language-name-ky = کِرگِز
language-name-la = لاتیٖنی
language-name-lad = لیڈِنو
language-name-lah = لَہَندا
language-name-lam = لَمبا
language-name-lb = لُکھزیمبورگِش
language-name-lez = لیزگِیَن
language-name-lg = گاندا
language-name-li = لِمبٔرگِش
language-name-ln = لِنگالا
language-name-lo = لاو
language-name-lol = مونٛگو
language-name-loz = لوزی
language-name-lt = لِتھوانِیَن
language-name-lu = لوُبا کَتَنٛگا
language-name-lua = لوٗبا لوٗلُوا
language-name-lui = لویِسینو
language-name-lun = لُندا
language-name-luo = لُوو
language-name-lus = لُسہاے
language-name-lv = لَتوِیَن
language-name-mad = مَدُریٖز
language-name-mag = مَگاے
language-name-mai = میتَھلی
language-name-mak = مَکَسار
language-name-man = مَندِنٛگو
language-name-mas = مَساے
language-name-mdf = موکشا
language-name-mdr = مَندَر
language-name-men = میندیے
language-name-mg = مَلاگَسی
language-name-mga = وَستی ایرِش
language-name-mh = مارشَلیٖز
language-name-mi = ماوری
language-name-mic = مِکمیک
language-name-min = مِنَنٛگکَباو
language-name-mk = میکَڈونیَن
language-name-ml = مٔلیالَم
language-name-mn = مَنٛگولی
language-name-mnc = مانٛچوٗ
language-name-mni = مَنیپوٗری
language-name-moh = موہاک
language-name-mos = موسی
language-name-mr = مَرٲٹھۍ
language-name-ms = مَلَے
language-name-mt = مَلتیٖس
language-name-mul = واریاہ زبان
language-name-mus = کریٖک
language-name-mwl = مِراندیٖز
language-name-mwr = مارواڑی
language-name-my = بٔمیٖز
language-name-myv = ایٚرزِیا
language-name-na = ناورُ
language-name-nap = نیٖپالیٹَن
language-name-nb = ناروییَن بوکمال
language-name-nd = شُمال ڈَبیل
language-name-nds = بوٚنِم جٔرمَن
language-name-ne = نیٚپٲلۍ
language-name-new = نیٚواری
language-name-ng = ڈونٛگا
language-name-nia = نِیاس
language-name-niu = نِیویَن
language-name-nl = ڈَچ
language-name-nl_BE = فلیٚمِش
language-name-nn = ناروییَن نَے نورسک
language-name-no = ناروییَن
language-name-nog = نوگاے
language-name-non = پرون نارسی
language-name-nqo = ایٚن کو
language-name-nr = جنوب ڈیٚبیل
language-name-nso = شمالی ستھو
language-name-nv = نَواجو
language-name-nwc = کلاسِکَل نیواری
language-name-ny = نِیَنجا
language-name-nym = نِیَمویٚزی
language-name-nyn = نِیَنکول
language-name-nyo = نِیورو
language-name-nzi = نَظیٖما
language-name-oc = اوکسیٖٹَن
language-name-oj = اوجِبوا
language-name-om = اوٚرومو
language-name-or = اوٚرِیا
language-name-os = اوٚسیٚٹِک
language-name-osa = اوٚسیج
language-name-ota = اوٹومَن تُرکِش
language-name-pa = پَنجٲبۍ
language-name-pag = پَنٛگاسِنَن
language-name-pal = پَہلَوی
language-name-pam = پَمپَنٛگا
language-name-pap = پَپِیامیٚنٹو
language-name-pau = پَلااُواں
language-name-peo = پرون فارسی
language-name-phn = فونیٖشیَن
language-name-pi = پالی
language-name-pl = پالِش
language-name-pon = پانپیٚیَن
language-name-pro = پرون پروویٚنچَل
language-name-ps = پَشتوٗ
language-name-pt = پُرتَگیٖز
language-name-pt_BR = برازیٖلی پُتَگیٖز
language-name-pt_PT = لِبیریَن پُرتَگیٖز
language-name-qu = کُویشُوا
language-name-raj = راجِستھٲنۍ
language-name-rap = رَپانوی
language-name-rar = رَروٹونٛگَن
language-name-rm = رومانش
language-name-rn = رُندی
language-name-ro = رومٲنی
language-name-ro_MD = مولداوِیَن
language-name-rom = رومَنی
language-name-root = روٗٹ
language-name-ru = روٗسی
language-name-rup = اَرومانی
language-name-rw = کِنیاوِندا
language-name-sa = سَنسکرٕت
language-name-sad = سَندَویے
language-name-sah = یاکُت
language-name-sam = سَمارِتَن اَرامیک
language-name-sas = سَسَک
language-name-sat = سَنتالی
language-name-sc = سراڈیٖنی
language-name-scn = سِچِلِیَن
language-name-sco = سکاٹس
language-name-sd = سِندی
language-name-se = شُمٲلی سَمی
language-name-sel = سیٚلکُپ
language-name-sg = سَنگو
language-name-sga = پرون ایرِش
language-name-sh = سیٚربو کروشِیَن
language-name-shn = شان
language-name-si = سِنہالا
language-name-sid = سِدامو
language-name-sk = سلووَک
language-name-sl = سلووینیَن
language-name-sm = سَمواَن
language-name-sma = جنوٗبی سَمی
language-name-smj = لولیے سَمی
language-name-smn = اِناری سَمی
language-name-sms = سکولٹ سَمی
language-name-sn = شونا
language-name-snk = سونِنکیے
language-name-so = سومٲلی
language-name-sog = سوگڈِیَن
language-name-sq = البانِیَن
language-name-sr = سٔربِیَن
language-name-srn = سرٛانَن ٹونٛگو
language-name-srr = سیٚریر
language-name-ss = سواتی
language-name-st = جنوبی ستھو
language-name-su = سَنڈَنیٖز
language-name-suk = سُکُما
language-name-sus = سُسوٗ
language-name-sux = سُمیریَن
language-name-sv = سویٖڈِش
language-name-sw = سواہِلی
language-name-syr = سیٖریٲیی
language-name-ta = تَمِل
language-name-te = تیلگوٗ
language-name-tem = ٹِمنیے
language-name-ter = ٹیٚریٚنو
language-name-tet = ٹیٹَم
language-name-tg = تاجِک
language-name-th = تھاے
language-name-ti = ٹِگرِنیا
language-name-tig = ٹاےگریے
language-name-tiv = تیٖو
language-name-tk = تُرکمین
language-name-tkl = ٹوکیٖلاو
language-name-tl = تَماشیک
language-name-tlh = کِلِنگون
language-name-tli = ٹِلِنگِت
language-name-tmh = تاماشیک
language-name-tn = سوانا
language-name-to = ٹونٛگا
language-name-tog = نیاسا ٹونٛگا
language-name-tpi = ٹاک پِسِن
language-name-tr = تُرکِش
language-name-ts = ژونٛگا
language-name-tsi = ژھِمشِیان
language-name-tt = تَتار
language-name-tum = تُمبُکا
language-name-tvl = تُوالوٗ
language-name-tw = توی
language-name-ty = تاہیشِیَن
language-name-tyv = تُویٖنیَن
language-name-udm = اُدمُرت
language-name-uga = اُگارتِک
language-name-uk = یوٗکرینیٲیی
language-name-umb = یُمبُندوٗ
language-name-und = اَنزٲنۍ یا نَہ لَگہٕہار زبان
language-name-ur = اُردوٗ
language-name-uz = اُزبیک
language-name-vai = واے
language-name-ve = ویندا
language-name-vi = وِیَتنَمیٖز
language-name-vo = وولَپُک
language-name-vot = ووتِک
language-name-wa = وَلوٗن
language-name-wal = والامو
language-name-war = وَریے
language-name-was = واشو
language-name-wo = وولوف
language-name-xal = کالمِک
language-name-xh = کھوسا
language-name-yao = یاو
language-name-yap = یَپیٖز
language-name-yi = یِدِش
language-name-yo = یورُبا
language-name-za = زُہانٛگ
language-name-zap = زَپوتیٚک
language-name-zen = زیناگا
language-name-zh = چیٖنی
language-name-zh_Hans = سیٚود چیٖنی
language-name-zh_Hant = رِوٲجی چیٖنی
language-name-zu = زُلوٗ
language-name-zun = زوٗنی
language-name-zxx = کانٛہہ تہِ لِسانیاتی مواد نہٕ
language-name-zza = زازا
