language-name-af = африкаанс
language-name-am = амҳарӣ
language-name-ar = арабӣ
language-name-as = ассомӣ
language-name-az = озарбойҷонӣ
language-name-ba = бошқирдӣ
language-name-ban = балинӣ
language-name-be = белорусӣ
language-name-bem = бемба
language-name-bg = булғорӣ
language-name-bn = бинғолӣ
language-name-bo = тибетӣ
language-name-br = бретонӣ
language-name-bs = босниягӣ
language-name-ca = каталонӣ
language-name-ceb = себуано
language-name-chm = марӣ
language-name-chr = черокӣ
language-name-ckb = курдии марказӣ
language-name-co = корсиканӣ
language-name-cs = чехӣ
language-name-cy = валлӣ
language-name-da = даниягӣ
language-name-de = немисӣ
language-name-dsb = сербии поёнӣ
language-name-dv = дивеҳӣ
language-name-dz = дзонгха
language-name-el = юнонӣ
language-name-en = англисӣ
language-name-eo = эсперанто
language-name-es = испанӣ
language-name-et = эстонӣ
language-name-eu = баскӣ
language-name-fa = форсӣ
language-name-ff = фулаҳ
language-name-fi = финӣ
language-name-fil = филиппинӣ
language-name-fo = фарерӣ
language-name-fr = франсузӣ
language-name-fy = фризии ғарбӣ
language-name-ga = ирландӣ
language-name-gd = шотландии гэлӣ
language-name-gl = галисиягӣ
language-name-gn = гуаранӣ
language-name-gu = гуҷаротӣ
language-name-ha = ҳауса
language-name-haw = ҳавайӣ
language-name-he = ибронӣ
language-name-hi = ҳиндӣ
language-name-hil = ҳилигайнон
language-name-hr = хорватӣ
language-name-hsb = сербии болоӣ
language-name-ht = гаитии креолӣ
language-name-hu = маҷорӣ
language-name-hy = арманӣ
language-name-hz = ҳереро
language-name-ibb = ибибио
language-name-id = индонезӣ
language-name-ig = игбо
language-name-is = исландӣ
language-name-it = италиявӣ
language-name-iu = инуктитутӣ
language-name-ja = японӣ
language-name-ka = гурҷӣ
language-name-kk = қазоқӣ
language-name-km = кхмерӣ
language-name-kn = каннада
language-name-ko = кореягӣ
language-name-kok = конканӣ
language-name-kr = канурӣ
language-name-kru = курукс
language-name-ks = кашмирӣ
language-name-ku = курдӣ
language-name-ky = қирғизӣ
language-name-la = лотинӣ
language-name-lb = люксембургӣ
language-name-lo = лаосӣ
language-name-lt = литвонӣ
language-name-lv = латишӣ
language-name-men = менде
language-name-mg = малагасӣ
language-name-mi = маорӣ
language-name-mk = мақдунӣ
language-name-ml = малаяламӣ
language-name-mn = муғулӣ
language-name-mni = манипурӣ
language-name-moh = моҳок
language-name-mr = маратҳӣ
language-name-ms = малайӣ
language-name-mt = малтӣ
language-name-my = бирманӣ
language-name-ne = непалӣ
language-name-niu = ниуэӣ
language-name-nl = голландӣ
language-name-no = норвегӣ
language-name-ny = нянҷа
language-name-oc = окситанӣ
language-name-om = оромо
language-name-or = одия
language-name-pa = панҷобӣ
language-name-pap = папиаменто
language-name-pl = лаҳистонӣ
language-name-ps = пушту
language-name-pt = португалӣ
language-name-qu = кечуа
language-name-quc = киче
language-name-rm = ретороманӣ
language-name-ro = руминӣ
language-name-ru = русӣ
language-name-rw = киняруанда
language-name-sa = санскрит
language-name-sah = саха
language-name-sat = санталӣ
language-name-sd = синдӣ
language-name-se = самии шимолӣ
language-name-si = сингалӣ
language-name-sk = словакӣ
language-name-sl = словенӣ
language-name-sma = самии ҷанубӣ
language-name-smj = луле самӣ
language-name-smn = инари самӣ
language-name-sms = сколти самӣ
language-name-so = сомалӣ
language-name-sq = албанӣ
language-name-sr = сербӣ
language-name-sv = шведӣ
language-name-syr = суриёнӣ
language-name-ta = тамилӣ
language-name-te = телугу
language-name-tg = тоҷикӣ
language-name-th = тайӣ
language-name-ti = тигриня
language-name-tk = туркманӣ
language-name-to = тонганӣ
language-name-tr = туркӣ
language-name-tt = тоторӣ
language-name-tzm = тамазайти атласи марказӣ
language-name-ug = ӯйғурӣ
language-name-uk = украинӣ
language-name-und = забони номаълум
language-name-ur = урду
language-name-uz = ӯзбекӣ
language-name-ve = венда
language-name-vi = ветнамӣ
language-name-wo = волоф
language-name-yi = идиш
language-name-yo = йоруба
language-name-zh = хитоӣ
language-name-zh_Hans = хитоии осонфаҳм
language-name-zh_Hant = хитоии анъанавӣ
