language-name-aa = અફાર
language-name-ab = અબખાજિયન
language-name-ace = અચીની
language-name-ach = એકોલી
language-name-ada = અદાંગ્મી
language-name-ady = અદિઘે
language-name-ae = અવેસ્તન
language-name-af = આફ્રિકન્સ
language-name-afh = અફ્રિહિલી
language-name-agq = અઘેમ
language-name-ain = ઐનુ
language-name-ak = અકાન
language-name-akk = અક્કાદીયાન
language-name-ale = અલેઉત
language-name-alt = દક્ષિણ અલ્તાઇ
language-name-am = એમ્હારિક
language-name-an = અર્ગોનીઝ
language-name-ang = જુની અંગ્રેજી
language-name-anp = અંગીકા
language-name-ar = અરબી
language-name-ar_001 = મોડર્ન સ્ટાન્ડર્ડ અરબી
language-name-arc = એરમૈક
language-name-arn = મેપુચે
language-name-arp = અરાપાહો
language-name-arq = આલ્જેરિયન અરબી
language-name-arw = અરાવક
language-name-ary = મોરોક્કન અરબી
language-name-arz = ઈજિપ્શિયન અરબી
language-name-as = આસામી
language-name-asa = અસુ
language-name-ast = અસ્તુરિયન
language-name-av = અવેરિક
language-name-awa = અવધી
language-name-ay = આયમારા
language-name-az = અઝરબૈજાની
language-name-ba = બશ્કીર
language-name-bal = બલૂચી
language-name-ban = બાલિનીસ
language-name-bas = બસા
language-name-bax = બામન
language-name-be = બેલારુશિયન
language-name-bej = બેજા
language-name-bem = બેમ્બા
language-name-bez = બેના
language-name-bg = બલ્ગેરિયન
language-name-bgn = પશ્ચિમી બાલોચી
language-name-bho = ભોજપુરી
language-name-bi = બિસ્લામા
language-name-bik = બિકોલ
language-name-bin = બિની
language-name-bla = સિક્સિકા
language-name-bm = બામ્બારા
language-name-bn = બાંગ્લા
language-name-bo = તિબેટીયન
language-name-bpy = બિષ્નુપ્રિયા
language-name-br = બ્રેટોન
language-name-bra = વ્રજ
language-name-brh = બ્રાહુઈ
language-name-brx = બોડો
language-name-bs = બોસ્નિયન
language-name-bua = બુરિયાત
language-name-bug = બુગિનીસ
language-name-byn = બ્લિન
language-name-ca = કતલાન
language-name-cad = કડ્ડો
language-name-car = કરિબ
language-name-cch = અત્સમ
language-name-ce = ચેચન
language-name-ceb = સિબુઆનો
language-name-cgg = ચિગા
language-name-ch = કેમોરો
language-name-chb = ચિબ્ચા
language-name-chg = છગાતાઇ
language-name-chk = ચૂકીસ
language-name-chm = મારી
language-name-chn = ચિનૂક જાર્ગન
language-name-cho = ચોક્તૌ
language-name-chp = શિપેવ્યાન
language-name-chr = શેરોકી
language-name-chy = શેયેન્ન
language-name-ckb = સેન્ટ્રલ કુર્દિશ
language-name-co = કોર્સિકન
language-name-cop = કોપ્ટિક
language-name-cr = ક્રી
language-name-crh = ક્રિમિયન તુર્કી
language-name-crs = સેસેલ્વા ક્રેઓલે ફ્રેન્ચ
language-name-cs = ચેક
language-name-csb = કાશુબિયન
language-name-cu = ચર્ચ સ્લાવિક
language-name-cv = ચૂવાશ
language-name-cy = વેલ્શ
language-name-da = ડેનિશ
language-name-dak = દાકોતા
language-name-dar = દાર્ગવા
language-name-dav = તૈતા
language-name-de = જર્મન
language-name-de_AT = ઓસ્ટ્રિઅન જર્મન
language-name-de_CH = સ્વિસ હાય જર્મન
language-name-del = દેલવેર
language-name-den = સ્લેવ
language-name-dgr = ડોગ્રિબ
language-name-din = દિન્કા
language-name-dje = ઝર્મા
language-name-doi = ડોગ્રી
language-name-dsb = લોઅર સોર્બિયન
language-name-dua = દુઆલા
language-name-dum = મધ્ય ડચ
language-name-dv = દિવેહી
language-name-dyo = જોલા-ફોન્યી
language-name-dyu = ડ્યુલા
language-name-dz = ડ્ઝોંગ્ખા
language-name-dzg = દાઝાગા
language-name-ebu = ઍમ્બુ
language-name-ee = ઈવ
language-name-efi = એફિક
language-name-egy = પ્રાચીન ઇજીપ્શિયન
language-name-eka = એકાજુક
language-name-el = ગ્રીક
language-name-elx = એલામાઇટ
language-name-en = અંગ્રેજી
language-name-en_AU = ઓસ્ટ્રેલિયન અંગ્રેજી
language-name-en_CA = કેનેડિયન અંગ્રેજી
language-name-en_GB = બ્રિટિશ અંગ્રેજી
language-name-en_US = અમેરિકન અંગ્રેજી
language-name-enm = મિડિલ અંગ્રેજી
language-name-eo = એસ્પેરાન્ટો
language-name-es = સ્પેનિશ
language-name-es_419 = લેટિન અમેરિકન સ્પેનિશ
language-name-es_ES = યુરોપિયન સ્પેનિશ
language-name-es_MX = મેક્સિકન સ્પેનિશ
language-name-et = એસ્ટોનિયન
language-name-eu = બાસ્ક
language-name-ewo = ઇવોન્ડો
language-name-fa = ફારસી
language-name-fan = ફેંગ
language-name-fat = ફન્ટી
language-name-ff = ફુલાહ
language-name-fi = ફિનિશ
language-name-fil = ફિલિપિનો
language-name-fj = ફીજીયન
language-name-fo = ફોરિસ્ત
language-name-fon = ફોન
language-name-fr = ફ્રેન્ચ
language-name-fr_CA = કેનેડિયન ફ્રેંચ
language-name-fr_CH = સ્વિસ ફ્રેંચ
language-name-frc = કાજૂન ફ્રેન્ચ
language-name-frm = મિડિલ ફ્રેંચ
language-name-fro = જૂની ફ્રેંચ
language-name-frr = ઉત્તરીય ફ્રિશિયન
language-name-frs = પૂર્વ ફ્રિશિયન
language-name-fur = ફ્રિયુલિયાન
language-name-fy = પશ્ચિમી ફ્રિસિયન
language-name-ga = આઇરિશ
language-name-gaa = ગા
language-name-gag = ગાગાઝ
language-name-gan = gan
language-name-gay = ગાયો
language-name-gba = બાયા
language-name-gbz = ઝોરોસ્ટ્રિઅન દારી
language-name-gd = સ્કોટીસ ગેલિક
language-name-gez = ગીઝ
language-name-gil = જિલ્બરટીઝ
language-name-gl = ગેલિશિયન
language-name-gmh = મધ્ય હાઇ જર્મન
language-name-gn = ગુઆરાની
language-name-goh = જૂની હાઇ જર્મન
language-name-gom = ગોઅન કોંકણી
language-name-gon = ગોંડી
language-name-gor = ગોરોન્તાલો
language-name-got = ગોથિક
language-name-grb = ગ્રેબો
language-name-grc = પ્રાચીન ગ્રીક
language-name-gsw = સ્વિસ જર્મન
language-name-gu = ગુજરાતી
language-name-guz = ગુસી
language-name-gv = માંક્સ
language-name-gwi = ગ્વિચ’ઇન
language-name-ha = હૌસા
language-name-hai = હૈડા
language-name-hak = hak
language-name-haw = હવાઇયન
language-name-he = હીબ્રુ
language-name-hi = હિન્દી
language-name-hif = ફીજી હિંદી
language-name-hil = હિલિગેનોન
language-name-hit = હિટ્ટિતે
language-name-hmn = હમોંગ
language-name-ho = હિરી મોટૂ
language-name-hr = ક્રોએશિયન
language-name-hsb = અપર સોર્બિયન
language-name-hsn = hsn
language-name-ht = હૈતિઅન ક્રેઓલે
language-name-hu = હંગેરિયન
language-name-hup = હૂપા
language-name-hy = આર્મેનિયન
language-name-hz = હેરેરો
language-name-ia = ઇંટરલિંગુઆ
language-name-iba = ઇબાન
language-name-ibb = ઇબિબિઓ
language-name-id = ઇન્ડોનેશિયન
language-name-ie = ઇંટરલિંગ
language-name-ig = ઇગ્બો
language-name-ii = સિચુઆન યી
language-name-ik = ઇનુપિયાક
language-name-ilo = ઇલોકો
language-name-inh = ઇંગુશ
language-name-io = ઈડો
language-name-is = આઇસલેન્ડિક
language-name-it = ઇટાલિયન
language-name-iu = ઇનુકિટૂટ
language-name-ja = જાપાનીઝ
language-name-jbo = લોજ્બાન
language-name-jgo = નગોમ્બા
language-name-jmc = મકામે
language-name-jpr = જુદેઓ-પર્શિયન
language-name-jrb = જુદેઓ-અરબી
language-name-jv = જાવાનીસ
language-name-ka = જ્યોર્જિયન
language-name-kaa = કારા-કલ્પક
language-name-kab = કબાઇલ
language-name-kac = કાચિન
language-name-kaj = જ્જુ
language-name-kam = કમ્બા
language-name-kaw = કાવી
language-name-kbd = કબાર્ડિયન
language-name-kcg = ત્યાપ
language-name-kde = મકોન્ડે
language-name-kea = કાબુવર્ડિઆનુ
language-name-kfo = કોરો
language-name-kg = કોંગો
language-name-kha = ખાસી
language-name-kho = ખોતાનીસ
language-name-khq = કોયરા ચિનિ
language-name-ki = કિકુયૂ
language-name-kj = ક્વાન્યામા
language-name-kk = કઝાખ
language-name-kkj = કાકો
language-name-kl = કલાલ્લિસુત
language-name-kln = કલેજિન
language-name-km = ખ્મેર
language-name-kmb = કિમ્બન્દુ
language-name-kn = કન્નડ
language-name-ko = કોરિયન
language-name-koi = કોમી-પર્મ્યાક
language-name-kok = કોંકણી
language-name-kos = કોસરિયન
language-name-kpe = ક્પેલ્લે
language-name-kr = કનુરી
language-name-krc = કરાચય-બલ્કાર
language-name-krl = કરેલિયન
language-name-kru = કુરૂખ
language-name-ks = કાશ્મીરી
language-name-ksb = શમ્બાલા
language-name-ksf = બફિયા
language-name-ksh = કોલોગ્નિયન
language-name-ku = કુર્દિશ
language-name-kum = કુમીક
language-name-kut = કુતેનાઇ
language-name-kv = કોમી
language-name-kw = કોર્નિશ
language-name-ky = કિર્ગીઝ
language-name-la = લેટિન
language-name-lad = લાદીનો
language-name-lag = લંગી
language-name-lah = લાહન્ડા
language-name-lam = લામ્બા
language-name-lb = લક્ઝેમબર્ગિશ
language-name-lez = લેઝધીયન
language-name-lfn = લિંગ્વા ફેન્કા નોવા
language-name-lg = ગાંડા
language-name-li = લિંબૂર્ગિશ
language-name-lkt = લાકોટા
language-name-ln = લિંગાલા
language-name-lo = લાઓ
language-name-lol = મોંગો
language-name-lou = લ્યુઇસિયાના ક્રેઓલ
language-name-loz = લોઝી
language-name-lrc = ઉત્તરી લુરી
language-name-lt = લિથુઆનિયન
language-name-lu = લૂબા-કટાંગા
language-name-lua = લૂબા-લુલુઆ
language-name-lui = લુઇસેનો
language-name-lun = લુન્ડા
language-name-luo = લ્યુઓ
language-name-lus = મિઝો
language-name-luy = લુઈયા
language-name-lv = લાતવિયન
language-name-mad = માદુરીસ
language-name-mag = મગહી
language-name-mai = મૈથિલી
language-name-mak = મકાસર
language-name-man = મન્ડિન્ગો
language-name-mas = મસાઇ
language-name-mdf = મોક્ષ
language-name-mdr = મંદાર
language-name-men = મેન્ડે
language-name-mer = મેરુ
language-name-mfe = મોરીસ્યેન
language-name-mg = મલાગસી
language-name-mga = મધ્ય આઈરિશ
language-name-mgh = માખુવા-મીટ્ટુ
language-name-mgo = મેતા
language-name-mh = માર્શલીઝ
language-name-mi = માઓરી
language-name-mic = મિકમેક
language-name-min = મિનાંગ્કાબાઉ
language-name-mk = મેસેડોનિયન
language-name-ml = મલયાલમ
language-name-mn = મોંગોલિયન
language-name-mnc = માન્ચુ
language-name-mni = મણિપુરી
language-name-moh = મોહૌક
language-name-mos = મોસ્સી
language-name-mr = મરાઠી
language-name-mrj = પશ્ચિમી મારી
language-name-ms = મલય
language-name-mt = માલ્ટિઝ
language-name-mua = મુનડાન્ગ
language-name-mul = બહુવિધ ભાષાઓ
language-name-mus = ક્રિક
language-name-mwl = મિરાંડી
language-name-mwr = મારવાડી
language-name-my = બર્મીઝ
language-name-myv = એર્ઝયા
language-name-mzn = મઝાન્દેરાની
language-name-na = નાઉરૂ
language-name-nan = nan
language-name-nap = નેપોલિટાન
language-name-naq = નમા
language-name-nb = નોર્વેજિયન બોકમાલ
language-name-nd = ઉત્તર દેબેલ
language-name-nds = લો જર્મન
language-name-nds_NL = લો સેક્સોન
language-name-ne = નેપાળી
language-name-new = નેવારી
language-name-ng = ડોન્ગા
language-name-nia = નિયાસ
language-name-niu = નિયુઆન
language-name-nl = ડચ
language-name-nl_BE = ફ્લેમિશ
language-name-nmg = ક્વાસિઓ
language-name-nn = નોર્વેજિયન નાયનૉર્સ્ક
language-name-nnh = નીએમબુન
language-name-no = નૉર્વેજીયન
language-name-nog = નોગાઇ
language-name-non = જૂની નોર્સ
language-name-nqo = એન’કો
language-name-nr = દક્ષિણ દેબેલ
language-name-nso = ઉત્તરી સોથો
language-name-nus = નુએર
language-name-nv = નાવાજો
language-name-nwc = પરંપરાગત નેવારી
language-name-ny = ન્યાન્જા
language-name-nym = ન્યામવેઝી
language-name-nyn = ન્યાનકોલ
language-name-nyo = ન્યોરો
language-name-nzi = ન્ઝિમા
language-name-oc = ઓક્સિટન
language-name-oj = ઓજિબ્વા
language-name-om = ઓરોમો
language-name-or = ઉડિયા
language-name-os = ઓસ્સેટિક
language-name-osa = ઓસેજ
language-name-ota = ઓટોમાન તુર્કિશ
language-name-pa = પંજાબી
language-name-pag = પંગાસીનાન
language-name-pal = પહલવી
language-name-pam = પમ્પાન્ગા
language-name-pap = પાપિયામેન્ટો
language-name-pau = પલાઉઆન
language-name-pcm = નાઇજેરિયન પીજીન
language-name-peo = જૂની ફારસી
language-name-phn = ફોનિશિયન
language-name-pi = પાલી
language-name-pl = પોલીશ
language-name-pon = પોહપિએન
language-name-prg = પ્રુસ્સીયન
language-name-pro = જુની પ્રોવેન્સલ
language-name-ps = પશ્તો
language-name-pt = પોર્ટુગીઝ
language-name-pt_BR = બ્રાઝિલીયન પોર્ટુગીઝ
language-name-pt_PT = યુરોપિયન પોર્ટુગીઝ
language-name-qu = ક્વેચુઆ
language-name-quc = કિચે
language-name-raj = રાજસ્થાની
language-name-rap = રાપાનુઇ
language-name-rar = રારોટોંગન
language-name-rm = રોમાન્શ
language-name-rn = રૂન્દી
language-name-ro = રોમાનિયન
language-name-ro_MD = મોલડાવિયન
language-name-rof = રોમ્બો
language-name-rom = રોમાની
language-name-root = રૂટ
language-name-ru = રશિયન
language-name-rup = અરોમેનિયન
language-name-rw = કિન્યારવાન્ડા
language-name-rwk = રવા
language-name-sa = સંસ્કૃત
language-name-sad = સોંડવે
language-name-sah = સખા
language-name-sam = સામરિટાન અરેમિક
language-name-saq = સમ્બુરુ
language-name-sas = સાસાક
language-name-sat = સંતાલી
language-name-sba = ન્ગામ્બેય
language-name-sbp = સાંગુ
language-name-sc = સાર્દિનિયન
language-name-scn = સિસિલિયાન
language-name-sco = સ્કોટ્સ
language-name-sd = સિંધી
language-name-sdh = સર્ઘન કુર્દીશ
language-name-se = ઉત્તરી સામી
language-name-seh = સેના
language-name-sel = સેલ્કપ
language-name-ses = કોયરાબોરો સેન્ની
language-name-sg = સાંગો
language-name-sga = જૂની આયરિશ
language-name-sh = સર્બો-ક્રોએશિયન
language-name-shi = તેશીલહિટ
language-name-shn = શેન
language-name-si = સિંહાલી
language-name-sid = સિદામો
language-name-sk = સ્લોવૅક
language-name-sl = સ્લોવેનિયન
language-name-sm = સામોન
language-name-sma = દક્ષિણ સામી
language-name-smj = લુલે સામી
language-name-smn = ઇનારી સામી
language-name-sms = સ્કોલ્ટ સામી
language-name-sn = શોના
language-name-snk = સોનિન્કે
language-name-so = સોમાલી
language-name-sog = સોગ્ડિએન
language-name-sq = અલ્બેનિયન
language-name-sr = સર્બિયન
language-name-srn = સ્રાનન ટોન્ગો
language-name-srr = સેરેર
language-name-ss = સ્વાતી
language-name-ssy = સાહો
language-name-st = દક્ષિણ સોથો
language-name-su = સંડેનીઝ
language-name-suk = સુકુમા
language-name-sus = સુસુ
language-name-sux = સુમેરિયન
language-name-sv = સ્વીડિશ
language-name-sw = સ્વાહિલી
language-name-sw_CD = કોંગો સ્વાહિલી
language-name-swb = કોમોરિયન
language-name-syc = પરંપરાગત સિરિએક
language-name-syr = સિરિએક
language-name-ta = તમિલ
language-name-tcy = તુલુ
language-name-te = તેલુગુ
language-name-tem = ટિમ્ને
language-name-teo = તેસો
language-name-ter = તેરેનો
language-name-tet = તેતુમ
language-name-tg = તાજીક
language-name-th = થાઈ
language-name-ti = ટાઇગ્રિનિયા
language-name-tig = ટાઇગ્રે
language-name-tiv = તિવ
language-name-tk = તુર્કમેન
language-name-tkl = તોકેલાઉ
language-name-tl = ટાગાલોગ
language-name-tlh = ક્લિન્ગોન
language-name-tli = ક્લીન્ગકિટ
language-name-tmh = તામાશેખ
language-name-tn = ત્સ્વાના
language-name-to = ટોંગાન
language-name-tog = ન્યાસા ટોન્ગા
language-name-tpi = ટોક પિસિન
language-name-tr = ટર્કિશ
language-name-trv = ટારોકો
language-name-ts = સોંગા
language-name-tsi = સિમ્શિયન
language-name-tt = તતાર
language-name-ttt = મુસ્લિમ તાટ
language-name-tum = તુમ્બુકા
language-name-tvl = તુવાલુ
language-name-tw = ટ્વાઇ
language-name-twq = તસાવાક
language-name-ty = તાહિતિયન
language-name-tyv = ટુવીનિયન
language-name-tzm = સેન્ટ્રલ એટલાસ તામાઝિટ
language-name-udm = ઉદમુર્ત
language-name-ug = ઉઇગુર
language-name-uga = યુગેરિટિક
language-name-uk = યુક્રેનિયન
language-name-umb = ઉમ્બુન્ડૂ
language-name-und = અજ્ઞાત ભાષા
language-name-ur = ઉર્દૂ
language-name-uz = ઉઝ્બેક
language-name-vai = વાઇ
language-name-ve = વેન્દા
language-name-vi = વિયેતનામીસ
language-name-vo = વોલાપુક
language-name-vot = વોટિક
language-name-vun = વુન્જો
language-name-wa = વાલૂન
language-name-wae = વેલ્સેર
language-name-wal = વોલાયટ્ટા
language-name-war = વારેય
language-name-was = વાશો
language-name-wbp = વાર્લ્પીરી
language-name-wo = વોલોફ
language-name-wuu = wuu
language-name-xal = કાલ્મિક
language-name-xh = ખોસા
language-name-xog = સોગા
language-name-yao = યાઓ
language-name-yap = યાપીસ
language-name-yav = યાન્ગબેન
language-name-ybb = યેમ્બા
language-name-yi = યિદ્દિશ
language-name-yo = યોરૂબા
language-name-yue = કેંટોનીઝ
language-name-za = ઝુઆગ
language-name-zap = ઝેપોટેક
language-name-zbl = બ્લિસિમ્બોલ્સ
language-name-zen = ઝેનાગા
language-name-zgh = માનક મોરોક્કન તામાઝિટ
language-name-zh = ચાઇનીઝ
language-name-zh_Hans = સરળીકૃત ચાઇનીઝ
language-name-zh_Hant = પારંપરિક ચાઇનીઝ
language-name-zu = ઝુલુ
language-name-zun = ઝૂની
language-name-zxx = કોઇ ભાષાશાસ્ત્રીય સામગ્રી નથી
language-name-zza = ઝાઝા
