language-name-aa = अफार
language-name-ab = अबखेज़ियन
language-name-ace = अचायनीज
language-name-ada = अडांग्मे
language-name-ady = अडिघे
language-name-af = अफ्रिकान्स
language-name-agq = अघेम
language-name-ain = आयनू
language-name-ak = अकान
language-name-ale = आलिट
language-name-alt = दक्षिणी अल्टाय
language-name-am = अमहारिक्
language-name-an = आरागोनिस
language-name-anp = अंगिका
language-name-ar = अरेबिक
language-name-ar_001 = आधुनिक प्रमाणित अरेबिक
language-name-arn = मापुचे
language-name-arp = अरापाहो
language-name-as = आसामी
language-name-asa = असु
language-name-ast = अस्टुरियान
language-name-av = अवारिक
language-name-awa = अवधी
language-name-ay = ऐमरा
language-name-az = अज़रबैजानी
language-name-ba = बष्किर
language-name-ban = बालिनिस
language-name-bas = बस्सा
language-name-be = बैलोरुसियन्
language-name-bem = बेम्बा
language-name-bez = बेना
language-name-bg = बल्गेरियन
language-name-bho = भोजपुरी
language-name-bi = बिसलमा
language-name-bin = बिनी
language-name-bla = सिकसिका
language-name-bm = बंबारा
language-name-bn = बांग्ला
language-name-bo = तिबेतियन
language-name-br = ब्रेटन
language-name-brx = बोडो
language-name-bs = बोस्नियन
language-name-bug = बगिनिस
language-name-byn = ब्लीन
language-name-ca = कटलान
language-name-ce = चिचेन
language-name-ceb = सिबौना
language-name-cgg = चिगा
language-name-ch = चामोर्रो
language-name-chk = छुनिस
language-name-chm = मारी
language-name-cho = चोताव
language-name-chr = चिरोकी
language-name-chy = चेयनी
language-name-ckb = मध्य खुर्दीश
language-name-co = कोर्शियन
language-name-crs = सेसेल्वा क्रयॉल फ्रेन्च
language-name-cs = चेक
language-name-cu = चर्च स्लेव्हीक
language-name-cv = छुवास
language-name-cy = वेळ्ष्
language-name-da = डॅनिश
language-name-dak = डाकोटा
language-name-dar = दार्ग्वा
language-name-dav = तायता
language-name-de = जर्मन
language-name-de_AT = ऑस्ट्रियन जर्मन
language-name-de_CH = स्वीझ म्हान जर्मन
language-name-dgr = डोगरीब
language-name-dje = झर्मा
language-name-dsb = लोवर सोर्बियन
language-name-dua = डौल
language-name-dv = दिवेही
language-name-dyo = जोला-फोनी
language-name-dz = झोंग्खा
language-name-dzg = डाझागा
language-name-ebu = एम्बु
language-name-ee = एव
language-name-efi = एफीक
language-name-eka = एकाजुक
language-name-el = ग्रीक्
language-name-en = इंग्लीश
language-name-en_AU = ऑस्ट्रेलियन इंग्लीश
language-name-en_CA = कॅनाडीयन इंग्लीश
language-name-en_GB = ब्रिटीश इंग्लीश
language-name-en_US = अमेरिकन इंग्लीश
language-name-eo = इस्परान्टो
language-name-es = स्पॅनिश
language-name-es_419 = लॅटिन अमेरिकन स्पॅनिश
language-name-es_ES = युरोपियन स्पॅनिश
language-name-es_MX = मेक्सिकन स्पॅनिश
language-name-et = इस्टोनियन्
language-name-eu = बास्क
language-name-ewo = एवोंडो
language-name-fa = पर्षियन्
language-name-ff = फुला
language-name-fi = फिन्निष्
language-name-fil = फिलिपिनो
language-name-fj = फिजी
language-name-fo = फेरोस्
language-name-fon = फोन
language-name-fr = फ्रेन्च
language-name-fr_CA = कॅनाडीयन फ्रेन्च
language-name-fr_CH = स्वीझ फ्रेन्च
language-name-fur = फ्रिलियन
language-name-fy = पश्चिमी फ्रिशियन
language-name-ga = ऐरिष
language-name-gaa = गा
language-name-gd = स्काटस् गेलिक्
language-name-gez = गेझ
language-name-gil = गिलबर्टीस
language-name-gl = गेलीशियन
language-name-gn = गौरानी
language-name-gor = गोरोंटालो
language-name-gsw = स्विज जर्मन
language-name-gu = गुजराती
language-name-guz = गुसी
language-name-gv = मॅन्स
language-name-gwi = ग्विच
language-name-ha = हौसा
language-name-haw = हवायियान
language-name-he = हिब्रू
language-name-hi = हिन्दी
language-name-hil = हिलीगायनॉन
language-name-hmn = मोंग
language-name-hr = क्रोयेषियन्
language-name-hsb = अपर सोर्बियन
language-name-ht = हैतियन क्रेयॉल
language-name-hu = हंगेरियन्
language-name-hup = हुपा
language-name-hy = आर्मेनियन
language-name-hz = हिरिरो
language-name-ia = इन्टरलिंग्वा
language-name-iba = आयबन
language-name-ibb = ईबिबियो
language-name-id = इंडोनेशियन
language-name-ie = इन्टरलिंग्
language-name-ig = इग्बो
language-name-ii = सिच्युआन यी
language-name-ik = इनूपेयाक्
language-name-ilo = लोको
language-name-inh = इंगूश
language-name-io = इदो
language-name-is = आईस्लान्डिक
language-name-it = इटालियन
language-name-iu = इन्युकट्ट
language-name-ja = जपानी
language-name-jbo = लोबजान
language-name-jgo = न्गोंबा
language-name-jmc = मचामे
language-name-jv = जावनीस्
language-name-ka = जार्जियन्
language-name-kab = काबायले
language-name-kac = काचीन
language-name-kaj = जु
language-name-kam = कंबा
language-name-kbd = काबार्डियन
language-name-kcg = त्याप
language-name-kde = माकोंडे
language-name-kea = काबुवर्डियनु
language-name-kfo = कोरो
language-name-kha = खासी
language-name-khq = कोयरा छिनी
language-name-ki = किकुयु
language-name-kj = कुयांमा
language-name-kk = कज़ख्
language-name-kkj = काको
language-name-kl = कालाल्लिसुट
language-name-kln = कालेंजीन
language-name-km = कंबोडियन
language-name-kmb = किंबुंडु
language-name-kn = कन्नडा
language-name-ko = कोरियन्
language-name-kok = कोंकणी
language-name-kpe = पेल्ले
language-name-kr = कानुरी
language-name-krc = कराची-बाल्कर
language-name-krl = कारेलियन
language-name-kru = कुरुख
language-name-ks = कश्मीरी
language-name-ksb = शंबाला
language-name-ksf = बाफिया
language-name-ksh = कोलोनियन
language-name-ku = कुर्दिष
language-name-kum = कुमयक
language-name-kv = कोमी
language-name-kw = कोर्निश
language-name-ky = किर्गिज़
language-name-la = लाटिन
language-name-lad = लाडिनो
language-name-lag = लांगी
language-name-lb = लक्सेमबर्गीश
language-name-lez = लेझघियान
language-name-lg = गांडा
language-name-li = लिंबुर्ग
language-name-lkt = लाकोटा
language-name-ln = लिंगाला
language-name-lo = लाअो
language-name-loz = लोझीं
language-name-lrc = उत्तरीय लुरी
language-name-lt = लिथुआनियन्
language-name-lu = लुबा-काटांगा
language-name-lua = लुबा-लुलुआ
language-name-lun = लुंडा
language-name-luo = लुओ
language-name-lus = मिझो
language-name-luy = लुय
language-name-mad = मादुरेसे
language-name-mag = मगाही
language-name-mai = मैथिली
language-name-mak = माक
language-name-mas = मसाई
language-name-mdf = मोक्ष
language-name-men = मेंडे
language-name-mer = मेरू
language-name-mfe = मोरिसेन
language-name-mg = मलागसी
language-name-mgh = माखुवा-मिट्टो
language-name-mgo = मेटा
language-name-mh = मार्शली
language-name-mi = मुरी
language-name-mic = मिक्माक
language-name-min = मिनाग्काबौ
language-name-mk = मसीडोनियन्
language-name-ml = मळियाळम
language-name-mn = मंगोलियन्
language-name-mni = मणिपुरी
language-name-moh = मोहाक
language-name-mos = मोस्सी
language-name-mr = मराठी
language-name-ms = मलय
language-name-mt = मालतीस्
language-name-mua = मुडांग
language-name-mul = साबार भाशा
language-name-mus = क्रिक
language-name-mwl = मिरांडीस
language-name-my = बर्मीज़्
language-name-myv = एरझिया
language-name-mzn = मझांडेराणी
language-name-na = नौरो
language-name-nap = नेपोलिटन
language-name-naq = नामा
language-name-nb = नोर्वेजियन बोकमाल
language-name-nd = उत्तर न्डेबेले
language-name-ne = नेपाळी
language-name-new = नेवरी
language-name-ng = डोंगा
language-name-nia = नियास
language-name-niu = नियुन
language-name-nl = डच्
language-name-nl_BE = फ्लेमिश
language-name-nmg = ख्वासी
language-name-nn = नोर्वोजियन नायनोर्स्क
language-name-nnh = न्गेबून
language-name-no = नोर्वेजियन
language-name-nog = नोगाय
language-name-nqo = नको
language-name-nr = दक्षिण डेबेले
language-name-nso = उत्तरीय सोथो
language-name-nus = न्युयर
language-name-nv = नावाजो
language-name-ny = नांन्जा
language-name-nyn = नानकोले
language-name-oc = ओसिटान्
language-name-om = ओरोमो
language-name-or = ओरिया
language-name-os = ओसेटिक
language-name-pa = पंजाबी
language-name-pag = पांगासियान
language-name-pam = पांपान्गा
language-name-pap = पापिमेंटो
language-name-pau = पालुयान
language-name-pcm = नायझेरियन पिडगीन
language-name-pl = पोलिष
language-name-prg = प्रुसियन
language-name-pt = पोर्तुगिज
language-name-pt_BR = ब्राझिलियन पोर्तुगिज
language-name-pt_PT = युरोपियन पोर्तुगिज
language-name-qu = क्वेच्वा
language-name-quc = किचे
language-name-rap = रापान्यु
language-name-rar = रारोटोंगान
language-name-rm = रहटो-रोमान्स्
language-name-rn = रुंदी
language-name-ro = रोमानियन्
language-name-ro_MD = मोल्डावियन्
language-name-rof = रोम्बो
language-name-root = रूट
language-name-ru = रशियन
language-name-rup = आरोमेनियन
language-name-rw = किन्यार्वान्डा
language-name-rwk = रवा
language-name-sa = संस्कृत
language-name-sad = संडावे
language-name-sah = सखा
language-name-saq = सांबारु
language-name-sat = संथाली
language-name-sba = गांबे
language-name-sbp = सांगू
language-name-sc = सार्डिनियान
language-name-scn = सिसिलियान
language-name-sco = स्कॉट्स
language-name-sd = सिंधी
language-name-se = उत्तरीय सामी
language-name-seh = सेना
language-name-ses = कोयराबोरो सेन्नी
language-name-sg = सांग्रो
language-name-sh = सेर्बो-क्रोयेषियन्
language-name-shi = ताछेहीट
language-name-shn = शान
language-name-si = सिन्हलीस्
language-name-sk = स्लोवाक
language-name-sl = स्लोवेनियन्
language-name-sm = समोन
language-name-sma = दक्षिणी सामी
language-name-smj = लुले सामी
language-name-smn = ईनारी सामी
language-name-sms = स्कोल्ट सामी
language-name-sn = शोना
language-name-snk = सोनिके
language-name-so = सोमाली
language-name-sq = आल्बेनियन्
language-name-sr = सर्बियन
language-name-srn = श्रानन टोंगो
language-name-ss = स्वाती
language-name-ssy = साहो
language-name-st = सेसोथो
language-name-su = सुंदनीस
language-name-suk = सुकुमा
language-name-sv = स्वीदीष
language-name-sw = स्वाहिली
language-name-sw_CD = काँगो स्वाहिली
language-name-swb = कोमोरियन
language-name-syr = सिरियाक
language-name-ta = तमिळ
language-name-te = तेलुगू
language-name-tem = तिम्ने
language-name-teo = तेसो
language-name-tet = तेतम
language-name-tg = तजिक
language-name-th = थाई
language-name-ti = तिग्रिन्या
language-name-tig = टिग्रे
language-name-tk = तुर्कमन
language-name-tl = तगालोग
language-name-tlh = लिंगॉन
language-name-tn = सेत्स्वाना
language-name-to = तोंगा
language-name-tpi = तोक पिसीन
language-name-tr = तुर्किष
language-name-trv = तारोको
language-name-ts = त्सोगा
language-name-tt = तटार
language-name-tum = तुंबुका
language-name-tvl = तुवालू
language-name-tw = त्वि
language-name-twq = तासावाक
language-name-ty = ताहीशियन
language-name-tyv = तुविनियन
language-name-tzm = केंद्रीय अटलास तामाझायट
language-name-udm = उडमुर्त
language-name-ug = उयघूर
language-name-uk = युक्रेनियन्
language-name-umb = यमबुंडु
language-name-und = अज्ञात भाशा
language-name-ur = उर्दू
language-name-uz = उज़बेक
language-name-vai = वाई
language-name-ve = वेंदा
language-name-vi = वियत्नामीज़
language-name-vo = ओलापुक
language-name-vun = वुंजो
language-name-wa = वालून
language-name-wae = वाल्सर
language-name-wal = वोलायटा
language-name-war = वरय
language-name-wo = उलोफ़
language-name-xal = कालमायक
language-name-xh = झ़ौसा
language-name-xog = सोगा
language-name-yav = यांगबेन
language-name-ybb = येम्बा
language-name-yi = इद्दिष्
language-name-yo = यूरुबा
language-name-yue = कांटोसी
language-name-za = झ्हुन्ग
language-name-zgh = प्रमाणित मोरोक्कन तामाझायट
language-name-zh = चिनी
language-name-zh_Hans = सोंपी चिनी
language-name-zh_Hant = पारंपारीक चिनी
language-name-zu = जुलू
language-name-zun = झून
language-name-zxx = अणकार सामुग्री ना
language-name-zza = झाझा
