language-name-aa = ᎠᏩᎳ
language-name-ab = ᎠᏆᏏᎠᏂ
language-name-ace = ᎠᏥᏂᏏ
language-name-ada = ᎠᏓᎾᎦᎺ
language-name-ady = ᎠᏗᎨ
language-name-af = ᎠᎬᎿᎨᏍᏛ
language-name-agq = ᎠᎨᎹ
language-name-ain = ᎠᏱᏄ
language-name-ak = ᎠᎧᎾ
language-name-ale = ᎠᎵᎤᏘ
language-name-alt = ᏧᎦᎾᏮ ᏗᏜ ᎠᎵᏔᎢ
language-name-am = ᎠᎹᎭᎵᎩ
language-name-an = ᎠᏩᎪᏂᏏ
language-name-anp = ᎠᎾᎩᎧ
language-name-ar = ᎡᎳᏈ
language-name-ar_001 = ᎪᎯᏊ ᎢᎬᏥᎩ ᎠᏟᎶᏍᏗ ᎡᎳᏈ
language-name-arn = ᎹᏊᏤ
language-name-arp = ᎠᏩᏈᎰ
language-name-as = ᎠᏌᎻᏏ
language-name-asa = ᎠᏑ
language-name-ast = ᎠᏍᏚᎵᎠᏂ
language-name-av = ᎠᏩᎵᎧ
language-name-awa = ᎠᏩᏗ
language-name-ay = ᎠᏱᎹᎳ
language-name-az = ᎠᏎᏆᏣᏂ
language-name-ba = ᏆᏍᎯᎩᎠ
language-name-ban = ᏆᎵᏁᏏ
language-name-bas = ᏆᏌᎠ
language-name-be = ᏇᎳᎷᏏ
language-name-bem = ᏇᎹᏆ
language-name-bez = ᏇᎾ
language-name-bg = ᏊᎵᎨᎵᎠᏂ
language-name-bho = ᏉᏣᏊᎵ
language-name-bi = ᏈᏍᎳᎹ
language-name-bin = ᏈᏂ
language-name-bla = ᏏᎩᏏᎧ
language-name-bm = ᏆᎻᏆᎳ
language-name-bn = ᏇᏂᎦᎳ
language-name-bo = ᏘᏇᏔᏂ
language-name-br = ᏇᏙᏂ
language-name-brx = ᏉᏙ
language-name-bs = ᏆᏍᏂᎠᏂ
language-name-bug = ᏈᎥᎩᏂᏍ
language-name-byn = ᏟᏂ
language-name-ca = ᎨᏔᎳᏂ
language-name-cay = ᎧᏳᎦ
language-name-ce = ᏤᏤᏂ
language-name-ceb = ᏎᏆᏃ
language-name-cgg = ᏥᎦ
language-name-ch = ᏣᎼᎶ
language-name-chk = ᏧᎨᏎ
language-name-chm = ᎹᎵ
language-name-cho = ᎠᏣᏓ
language-name-chr = ᏣᎳᎩ
language-name-chy = ᏣᏰᏂ
language-name-ckb = ᎠᏰᏟ ᎫᏗᏏ
language-name-co = ᎪᎵᏍᎢᎧᏂ
language-name-crs = ᏎᏎᎵᏩ ᏟᏲᎵ ᎠᏂᎦᎸ
language-name-cs = ᏤᎩ
language-name-cu = ᏧᏂᎳᏫᏍᏗ ᏍᎳᏫᎪ
language-name-cv = ᏧᏩᏏ
language-name-cy = ᏪᎵᏏ
language-name-da = ᏕᏂᏍ
language-name-dak = ᏓᎪᏔ
language-name-dar = ᏓᎳᏆ
language-name-dav = ᏔᎢᏔ
language-name-de = ᏙᎢᏥ
language-name-de_AT = ᎠᏟᏯᏂ ᎠᏂᏓᏥ
language-name-de_CH = ᏍᏫᏏ ᎦᎸᎳᏗ ᎠᏂᏓᏥ
language-name-dgr = ᎩᏟ ᎤᏄᎳᏥ
language-name-dje = ᏌᎹ
language-name-dsb = ᎡᎳᏗ ᏐᏈᎠᏂ
language-name-dua = ᏚᎠᎳ
language-name-dv = ᏗᏪᎯ
language-name-dyo = ᏦᎳ-ᏬᏱ
language-name-dz = ᏓᏐᏅᎧ
language-name-dzg = ᏓᏌᎦ
language-name-ebu = ᎡᎻᏊ
language-name-ee = ᎡᏪ
language-name-efi = ᎡᏫᎩ
language-name-eka = ᎨᎧᏧᎧ
language-name-el = ᎠᏂᎪᎢ
language-name-en = ᎩᎵᏏ
language-name-en_AU = ᎡᎳᏗᏜ ᎩᎵᏏ
language-name-en_CA = ᎨᎾᏓ ᎩᎵᏏ
language-name-en_GB = ᎩᎵᏏᏲ ᎩᎵᏏ
language-name-en_US = ᎠᎹᏰᏟ ᎩᎵᏏ
language-name-eo = ᎡᏍᏇᎳᏂᏙ
language-name-es = ᏍᏆᏂ
language-name-es_419 = ᏔᏘᏂ ᎠᎹᏰᏟ ᏍᏆᏂ
language-name-es_ES = ᎠᏂᏍᏆᏂᏱ ᏍᏆᏂ
language-name-es_MX = ᏍᏆᏂᏱ ᏍᏆᏂ
language-name-et = ᎡᏍᏙᏂᎠᏂ
language-name-eu = ᏆᏍᎨ
language-name-ewo = ᎡᏬᏂᏙ
language-name-fa = ᏇᏏᎠᏂ
language-name-ff = ᏊᎳᏂ
language-name-fi = ᏈᏂᏍ
language-name-fil = ᎠᏈᎵᎩ
language-name-fj = ᏫᏥᎠᏂ
language-name-fo = ᏇᎶᎡᏍ
language-name-fon = ᏠᏂ
language-name-fr = ᎦᎸᏥ
language-name-fr_CA = ᎨᎾᏓ ᎦᎸᏥ
language-name-fr_CH = ᏍᏫᏏ ᎦᎸᏥ
language-name-fur = ᏞᎤᎵᎠᏂ
language-name-fy = ᏭᏕᎵᎬ ᏗᏜ ᏟᏏᎠᏂ
language-name-ga = ᎨᎵᎩ
language-name-gaa = Ꭶ
language-name-gd = ᏍᎦᏗ ᎨᎵᎩ
language-name-gez = ᎩᏏ
language-name-gil = ᎩᏇᏘᏏ
language-name-gl = ᎦᎵᏏᎠᏂ
language-name-gn = ᏆᎳᏂ
language-name-gor = ᎪᎶᏂᏔᏃ
language-name-gsw = ᏍᏫᏏ ᎠᏂᏓᏥ
language-name-gu = ᎫᏣᎳᏘ
language-name-guz = ᎫᏏ
language-name-gv = ᎹᎾᎧᏏ
language-name-gwi = ᏈᏥᏂ
language-name-ha = ᎭᎤᏌ
language-name-haw = ᎭᏩᎼ
language-name-he = ᎠᏂᏈᎷ
language-name-hi = ᎯᏂᏗ
language-name-hil = ᎯᎵᎨᎾᏂ
language-name-hmn = ᎭᎼᏂᎩ
language-name-hr = ᎧᎶᎡᏏᏂ
language-name-hsb = ᎦᎸᎳᏗᎨ ᏐᏈᎠᏂ
language-name-ht = ᎮᏏᎠᏂ ᏟᏲᎵ
language-name-hu = ᎲᏂᎦᎵᎠᏂ
language-name-hup = ᎠᏂᎱᏆ
language-name-hy = ᎠᎳᎻᎠᏂ
language-name-hz = ᎮᎴᎶ
language-name-ia = ᎠᏰᏟ ᎦᏬᏂᎯᏍᏗ
language-name-iba = ᎢᏆᏂ
language-name-ibb = ᎢᏈᏈᎣ
language-name-id = ᎢᏂᏙᏂᏏᎠ
language-name-ig = ᎢᎦᎪ
language-name-ii = ᏏᏧᏩᏂ Ᏹ
language-name-ilo = ᎢᎶᎪ
language-name-inh = ᎢᏂᎫᏏ
language-name-io = ᎢᏙ
language-name-is = ᏧᏁᏍᏓᎸᎯᎢᎩ
language-name-it = ᎬᏩᎵᏲᏥᎢ
language-name-iu = ᎢᏄᎦᏘᏚ
language-name-ja = ᏣᏩᏂᏏ
language-name-jbo = ᎶᏣᏆᏂ
language-name-jgo = ᎾᎪᏆ
language-name-jmc = ᎹᏣᎺ
language-name-jv = ᏆᏌ ᏣᏩ
language-name-ka = ᏦᏥᎠᏂ
language-name-kab = ᎧᏈᎴ
language-name-kac = ᎧᏥᏂ
language-name-kaj = ᏥᏧ
language-name-kam = ᎧᎻᏆ
language-name-kbd = ᎧᏆᏗᎠᏂ
language-name-kcg = ᏔᏯᏆ
language-name-kde = ᎹᎪᏕ
language-name-kea = ᎧᏊᏪᏗᎠᏄ
language-name-kfo = ᎪᎶ
language-name-kha = ᎧᏏ
language-name-khq = ᎪᏱᎳ ᏥᏂ
language-name-ki = ᎩᎫᏳ
language-name-kj = ᎫᏩᏂᎠᎹ
language-name-kk = ᎧᏌᎧ
language-name-kkj = ᎧᎪ
language-name-kl = ᎧᎳᎵᏑᏘ
language-name-kln = ᎧᎴᏂᏥᏂ
language-name-km = ᎩᎻᎷ
language-name-kmb = ᎩᎻᏊᏚ
language-name-kn = ᎧᎾᏓ
language-name-ko = ᎪᎵᎠᏂ
language-name-kok = ᎧᏂᎧᏂ
language-name-kpe = ᏇᎴ
language-name-kr = ᎧᏄᎵ
language-name-krc = ᎧᎳᏣᏱ-ᏆᎵᎧᎵ
language-name-krl = ᎧᎴᎵᎠᏂ
language-name-kru = ᎫᎷᎩ
language-name-ks = ᎧᏏᎻᎵ
language-name-ksb = ᏝᎻᏆᎸ
language-name-ksf = ᏆᏫᎠ
language-name-ksh = ᎪᎶᏂᎠᏂ
language-name-ku = ᎫᏗᏏ
language-name-kum = ᎫᎻᎧ
language-name-kv = ᎪᎻ
language-name-kw = ᏎᎷᎭ
language-name-ky = ᎩᎵᏣᎢᏍ
language-name-la = ᎳᏘᏂ
language-name-lad = ᎳᏗᏃ
language-name-lag = ᎳᏂᎩ
language-name-lb = ᎸᎦᏏᎻᏋᎢᏍ
language-name-lez = ᎴᏏᎦᏂ
language-name-lg = ᎦᏂᏓ
language-name-li = ᎴᎹᏊᎵᏏ
language-name-lkt = ᎳᎪᏓ
language-name-ln = ᎵᏂᎦᎳ
language-name-lo = ᎳᎣ
language-name-loz = ᎶᏏ
language-name-lrc = ᏧᏴᏢ ᏗᏜ ᎷᎵ
language-name-lt = ᎵᏚᏩᏂᎠᏂ
language-name-lu = ᎷᏆ-ᎧᏔᎦ
language-name-lua = ᎷᏆ-ᎷᎷᎠ
language-name-lun = ᎷᎾᏓ
language-name-luo = ᎷᎣ
language-name-lus = ᎻᏐ
language-name-luy = ᎷᏱᎠ
language-name-lv = ᎳᏘᏫᎠᏂ
language-name-mad = ᎹᏚᎴᏏ
language-name-mag = ᎹᎦᎯ
language-name-mai = ᎹᏟᎵ
language-name-mak = ᎹᎧᏌ
language-name-mas = ᎹᏌᏱ
language-name-mdf = ᎼᎧᏌ
language-name-men = ᎺᎾᏕ
language-name-mer = ᎺᎷ
language-name-mfe = ᎼᎵᏏᎡᏂ
language-name-mg = ᎹᎳᎦᏏ
language-name-mgh = ᎹᎫᏩ-ᎻᏙ
language-name-mgo = ᎺᎳ’
language-name-mh = ᎹᏌᎵᏏ
language-name-mi = ᎹᏫ
language-name-mic = ᎻᎧᎹᎩ
language-name-min = ᎻᎾᎧᏆᎤ
language-name-mk = ᎹᏎᏙᏂᎠᏂ
language-name-ml = ᎹᎳᏯᎳᎻ
language-name-mn = ᎹᏂᎪᎵᎠᏂ
language-name-mni = ᎺᏂᏉᎵ
language-name-moh = ᎼᎭᎩ
language-name-mos = ᎼᏍᏏ
language-name-mr = ᎹᎳᏘ
language-name-ms = ᎹᎴ
language-name-mt = ᎹᎵᏘᏍ
language-name-mua = ᎽᏂᏓᎩ
language-name-mul = ᏧᏈᏍᏗ ᏗᎦᏬᏂᎯᏍᏗ
language-name-mus = ᎠᎫᏌ
language-name-mwl = ᎻᎳᏕᏏ
language-name-my = ᏋᎻᏍ
language-name-myv = ᎡᏏᏯ
language-name-mzn = ᎹᏌᏕᎳᏂ
language-name-na = ᏃᎤᎷ
language-name-nap = ᏂᏯᏆᎵᏔᏂ
language-name-naq = ᎾᎹ
language-name-nb = ᏃᎵᏪᏥᏂ ᏉᎧᎹᎵ
language-name-nd = ᏧᏴᏢ ᏂᏕᏇᎴ
language-name-nds_NL = ᎡᎳᏗ ᏁᏛᎳᏂ
language-name-ne = ᏁᏆᎵ
language-name-new = ᏁᏩᎵ
language-name-ng = ᎾᏙᎦ
language-name-nia = ᏂᎠᏏ
language-name-niu = ᏂᏳᏫᏯᏂ
language-name-nl = ᏛᏥ
language-name-nl_BE = ᏊᎵᏥᎥᎻ ᏛᏥ
language-name-nmg = ᏆᏏᏲ
language-name-nn = ᏃᎵᏪᏥᏂ ᎾᎵᏍᎩ
language-name-nnh = ᎾᏥᏰᎹᏊᏂ
language-name-nog = ᏃᎦᏱ
language-name-nqo = ᎾᎪ
language-name-nr = ᏧᎦᎾᏮ ᏂᏕᏇᎴ
language-name-nso = ᏧᏴᏢ ᏗᏜ ᏐᏠ
language-name-nus = ᏄᏪᎵ
language-name-nv = ᎾᏩᎰ
language-name-ny = ᏂᏯᏂᏣ
language-name-nyn = ᏂᏯᎾᎪᎴ
language-name-oc = ᎠᏏᏔᏂ
language-name-om = ᎣᎶᎼ
language-name-or = ᎣᏗᎠ
language-name-os = ᎣᏎᏘᎧ
language-name-pa = ᏡᏂᏣᏈ
language-name-pag = ᏇᎦᏏᎠᏂ
language-name-pam = ᏆᎹᏆᎾᎦ
language-name-pap = ᏆᏈᏯᎺᎾᏙ
language-name-pau = ᏆᎳᎤᏩᏂ
language-name-pcm = ᎾᎩᎵᎠᏂ ᏈᏥᏂ
language-name-pl = ᏉᎵᏍ
language-name-prg = ᏡᏏᎠᏂ
language-name-ps = ᏆᏍᏙ
language-name-pt = ᏉᏧᎩᏍ
language-name-pt_BR = ᏆᏏᎵᎢ ᏉᏧᎩᏍ
language-name-pt_PT = ᏉᏥᎦᎳ ᏉᏧᎩᏍ
language-name-qu = ᎨᏧᏩ
language-name-quc = ᎩᏤ
language-name-rap = ᎳᏆᏄᏫ
language-name-rar = ᎳᎶᏙᎾᎦᏂ
language-name-rm = ᎠᏂᎶᎺᏂ
language-name-rn = ᎷᏂᏗ
language-name-ro = ᎶᎹᏂᎠᏂ
language-name-ro_MD = ᎹᎵᏙᏫᎠ ᏣᎹᏂᎠᏂ
language-name-rof = ᎶᎹᏉ
language-name-root = ᎤᎾᏍᎦᎸ
language-name-ru = ᏲᏅᎯ
language-name-rup = ᎠᏬᎹᏂᎠᏂ
language-name-rw = ᎩᏂᏯᏩᏂᏓ
language-name-rwk = Ꮖ
language-name-sa = ᏍᏂᏍᎩᏗ
language-name-sad = ᏌᏅᏓᏫ
language-name-sah = ᏌᎧᎾ
language-name-saq = ᏌᎹᏊᎷ
language-name-sat = ᏌᏂᏔᎵ
language-name-sba = ᎾᎦᎹᏇ
language-name-sbp = ᏌᏁᎫ
language-name-sc = ᏌᏗᏂᎠᏂ
language-name-scn = ᏏᏏᎵᎠᏂ
language-name-sco = ᏍᎦᏗ
language-name-sd = ᏏᏂᏗ
language-name-se = ᏧᏴᏢ ᏗᏜ ᏌᎻ
language-name-see = ᏏᏂᎦ
language-name-seh = ᏎᎾ
language-name-ses = ᎪᏱᎳᏈᎶ ᏎᏂ
language-name-sg = ᏌᏂᎪ
language-name-shi = ᏔᏤᎵᎯᏘ
language-name-shn = ᏝᏂ
language-name-si = ᏏᎾᎭᎳ
language-name-sk = ᏍᎶᏩᎩ
language-name-sl = ᏍᎶᏫᏂᎠᏂ
language-name-sm = ᏌᎼᏯᏂ
language-name-sma = ᏧᎦᎾᏮ ᏗᏜ ᏌᎻ
language-name-smj = ᎷᎴ ᏌᎻ
language-name-smn = ᎢᎾᎵ ᏌᎻ
language-name-sms = ᏍᎪᎵᏘ ᏌᎻ
language-name-sn = ᏠᎾ
language-name-snk = ᏐᏂᏂᎨ
language-name-so = ᏐᎹᎵ
language-name-sq = ᎠᎵᏇᏂ
language-name-sr = ᏒᏈᎠᏂ
language-name-srn = ᏏᎳᎾᏂ ᏙᏃᎪ
language-name-ss = ᏍᏩᏘ
language-name-ssy = ᏌᎰ
language-name-st = ᏧᎦᎾᏮ ᏗᏜ ᏐᏠ
language-name-su = ᏑᏂᏓᏂᏏ
language-name-suk = ᏑᎫᎹ
language-name-sv = ᏍᏫᏗᏏ
language-name-sw = ᏍᏩᎯᎵ
language-name-sw_CD = ᎧᏂᎪ ᏍᏩᎯᎵ
language-name-swb = ᎪᎼᎵᎠᏂ
language-name-syr = ᏏᎵᎠᎩ
language-name-ta = ᏔᎻᎵ
language-name-te = ᏖᎷᎦ
language-name-tem = ᏘᎹᏁ
language-name-teo = ᏖᏐ
language-name-tet = ᏖᏚᎼ
language-name-tg = ᏔᏥᎩ
language-name-th = ᏔᏱ
language-name-ti = ᏘᎩᎵᏂᎠ
language-name-tig = ᏢᏓᏥ
language-name-tk = ᎠᏂᎬᎾ
language-name-tlh = ᏟᎦᎾ
language-name-tn = ᏧᏩᎾ
language-name-to = ᏙᎾᎦᏂ
language-name-tpi = ᏙᎩ ᏈᏏᏂ
language-name-tr = ᎠᎬᎾ
language-name-trv = ᏔᎶᎪ
language-name-ts = ᏦᎾᎦ
language-name-tt = ᏔᏔ
language-name-tum = ᏛᎹᏊᎧ
language-name-tvl = ᏚᏩᎷ
language-name-twq = ᏔᏌᏩᎩ
language-name-ty = ᏔᎯᏘᎠᏂ
language-name-tyv = ᏚᏫᏂᎠᏂ
language-name-tzm = ᎠᏰᏟ ᎡᎶᎯ ᏓᏟᎶᏍᏗᏓᏅᎢ ᏔᎹᏏᏘ
language-name-udm = ᎤᏚᎷᏘ
language-name-ug = ᏫᎦ
language-name-uk = ᏳᎧᎴᏂᎠᏂ
language-name-umb = ᎤᎹᏊᏅᏚ
language-name-und = ᏄᏬᎵᏍᏛᎾ ᎦᏬᏂᎯᏍᏗ
language-name-ur = ᎤᎵᏚ
language-name-uz = ᎤᏍᏇᎩ
language-name-vai = ᏩᏱ
language-name-ve = ᏫᏂᏓ
language-name-vi = ᏫᎡᏘᎾᎻᏍ
language-name-vo = ᏬᎳᏊᎩ
language-name-vun = ᏭᎾᏦ
language-name-wa = ᏩᎷᎾ
language-name-wae = ᏩᎵᏎᎵ
language-name-wal = ᏬᎳᏱᏔ
language-name-war = ᏩᎴ
language-name-wo = ᏬᎶᏫ
language-name-xal = ᎧᎳᎻᎧ
language-name-xh = ᏠᏌ
language-name-xog = ᏐᎦ
language-name-yav = ᏰᎾᎦᏇᏂ
language-name-ybb = ᏰᎹᏋ
language-name-yi = ᏱᏗᏍ
language-name-yo = ᏲᏄᏆ
language-name-yue = ᎨᎾᏙᏂᏏ
language-name-zgh = ᎠᏟᎶᏍᏗ ᎼᎶᎪ ᏔᎹᏏᏘ
language-name-zh = ᏓᎶᏂᎨ
language-name-zh_Hans = ᎠᎯᏗᎨ ᏓᎶᏂᎨ
language-name-zh_Hant = ᎤᏦᏍᏗ ᏓᎶᏂᎨ
language-name-zu = ᏑᎷ
language-name-zun = ᏑᏂ
language-name-zxx = Ꮭ ᎦᏬᏂᎯᏍᏗ ᎦᎸᏛᎢ ᏱᎩ
language-name-zza = ᏌᏌ
