language-name-ain = Ainu
language-name-ar_001 = Kiarabu cha Sasa Kilichosanifishwa
language-name-arq = Kiarabu cha Aljeria
language-name-az = Kiazabajani
language-name-bug = Kibugini
language-name-ckb = Kikurdi cha Kati
language-name-dsb = Kisorbian cha Chini
language-name-grc = Kigiriki cha Kale
language-name-hsb = Kisorbia cha Juu
language-name-inh = Kingushi
language-name-jbo = Kilojbani
language-name-kac = Kikachin
language-name-khq = Kikoyra Chiini
language-name-kkj = Kikako
language-name-koi = Kikomipermyak
language-name-kru = Kikurukh
language-name-lam = Kilamba
language-name-li = Kilimbugish
language-name-mdf = Kimoksha
language-name-mic = Kimicmac
language-name-mk = Kimasedonia
language-name-moh = Kimohoki
language-name-nnh = Kiingiemboon
language-name-nqo = Kiin’ko
language-name-or = Kiodia
language-name-pcm = Pijini ya Nijeria
language-name-root = Kiroot
language-name-sco = sco
language-name-ses = Kikoyraboro Senni
language-name-shu = Kiarabu cha Chadi
language-name-srn = Kiscran Tongo
language-name-swb = Kicomoro
language-name-syr = Kisyria
language-name-tw = Kitwi
language-name-tzm = Lugha ya Central Atlas Tamazight
language-name-udm = Kiudumurti
language-name-wa = Kiwaloon
language-name-wae = Kiwalser
language-name-zgh = Tamazight Sanifu ya Moroko
