language-name-aa = афар тілі
language-name-ab = абхаз тілі
language-name-ace = ачех тілі
language-name-ada = адангме тілі
language-name-ady = адыгей тілі
language-name-af = африкаанс тілі
language-name-agq = агхем тілі
language-name-ain = айну тілі
language-name-ak = акан тілі
language-name-ale = алеут тілі
language-name-alt = оңтүстік алтай тілі
language-name-am = амхар тілі
language-name-an = арагон тілі
language-name-anp = ангика тілі
language-name-ar = араб тілі
language-name-ar_001 = қазіргі стандартты араб тілі
language-name-arn = мапуче тілі
language-name-arp = арапахо тілі
language-name-as = ассам тілі
language-name-asa = асу тілі
language-name-ast = астурия тілі
language-name-av = авар тілі
language-name-awa = авадхи тілі
language-name-ay = аймара тілі
language-name-az = әзірбайжан тілі
language-name-ba = башқұрт тілі
language-name-ban = бали тілі
language-name-bas = баса тілі
language-name-be = беларусь тілі
language-name-bem = бемба тілі
language-name-bez = бена тілі
language-name-bg = болгар тілі
language-name-bgn = батыс балучи тілі
language-name-bho = бходжпури тілі
language-name-bi = бислама тілі
language-name-bin = бини тілі
language-name-bla = сиксика тілі
language-name-bm = бамбара тілі
language-name-bn = бенгал тілі
language-name-bo = тибет тілі
language-name-br = бретон тілі
language-name-brx = бодо тілі
language-name-bs = босния тілі
language-name-bug = бугис тілі
language-name-byn = блин тілі
language-name-ca = каталан тілі
language-name-ce = шешен тілі
language-name-ceb = себуано тілі
language-name-cgg = кига тілі
language-name-ch = чаморро тілі
language-name-chk = чуук тілі
language-name-chm = мари тілі
language-name-cho = чокто тілі
language-name-chr = чероки тілі
language-name-chy = шайен тілі
language-name-ckb = сорани тілі
language-name-co = корсика тілі
language-name-crs = сейшельдік креол тілі
language-name-cs = чех тілі
language-name-cu = шіркеулік славян тілі
language-name-cv = чуваш тілі
language-name-cy = валлий тілі
language-name-da = дат тілі
language-name-dak = дакота тілі
language-name-dar = даргин тілі
language-name-dav = таита тілі
language-name-de = неміс тілі
language-name-de_AT = австриялық неміс тілі
language-name-de_CH = швейцариялық әдеби неміс тілі
language-name-dgr = догриб тілі
language-name-dje = зарма тілі
language-name-dsb = төменгі лужица тілі
language-name-dua = дуала тілі
language-name-dv = дивехи тілі
language-name-dyo = диола тілі
language-name-dz = дзонг-кэ тілі
language-name-dzg = дазага тілі
language-name-ebu = эмбу тілі
language-name-ee = эве тілі
language-name-efi = эфик тілі
language-name-eka = экаджук тілі
language-name-el = грек тілі
language-name-en = ағылшын тілі
language-name-en_AU = австралиялық ағылшын тілі
language-name-en_CA = канадалық ағылшын тілі
language-name-en_GB = британиялық ағылшын тілі
language-name-en_US = америкалық ағылшын тілі
language-name-eo = эсперанто тілі
language-name-es = испан тілі
language-name-es_419 = латынамерикалық испан тілі
language-name-es_ES = еуропалық испан тілі
language-name-es_MX = мексикалық испан тілі
language-name-et = эстон тілі
language-name-eu = баск тілі
language-name-ewo = эвондо тілі
language-name-fa = парсы тілі
language-name-ff = фула тілі
language-name-fi = фин тілі
language-name-fil = филиппин тілі
language-name-fj = фиджи тілі
language-name-fo = фарер тілі
language-name-fon = фон тілі
language-name-fr = француз тілі
language-name-fr_CA = канадалық француз тілі
language-name-fr_CH = швейцариялық француз тілі
language-name-fur = фриуль тілі
language-name-fy = батыс фриз тілі
language-name-ga = ирланд тілі
language-name-gaa = га тілі
language-name-gag = гагауз тілі
language-name-gd = шотландиялық гэль тілі
language-name-gez = геэз тілі
language-name-gil = гильберт тілі
language-name-gl = галисия тілі
language-name-gn = гуарани тілі
language-name-gor = горонтало тілі
language-name-gsw = швейцариялық неміс тілі
language-name-gu = гуджарати тілі
language-name-guz = гусии тілі
language-name-gv = мэн тілі
language-name-gwi = гвичин тілі
language-name-ha = хауса тілі
language-name-haw = гавайи тілі
language-name-he = иврит тілі
language-name-hi = хинди тілі
language-name-hil = хилигайнон тілі
language-name-hmn = хмонг тілі
language-name-hr = хорват тілі
language-name-hsb = жоғарғы лужица тілі
language-name-ht = гаити тілі
language-name-hu = венгр тілі
language-name-hup = хупа тілі
language-name-hy = армян тілі
language-name-hz = гереро тілі
language-name-ia = интерлингва тілі
language-name-iba = ибан тілі
language-name-ibb = ибибио тілі
language-name-id = индонезия тілі
language-name-ie = интерлингве тілі
language-name-ig = игбо тілі
language-name-ii = сычуан и тілі
language-name-ilo = илоко тілі
language-name-inh = ингуш тілі
language-name-io = идо тілі
language-name-is = исланд тілі
language-name-it = итальян тілі
language-name-iu = инуктитут тілі
language-name-ja = жапон тілі
language-name-jbo = ложбан тілі
language-name-jgo = нгомба тілі
language-name-jmc = мачаме тілі
language-name-jv = ява тілі
language-name-ka = грузин тілі
language-name-kab = кабил тілі
language-name-kac = качин тілі
language-name-kaj = каджи тілі
language-name-kam = камба тілі
language-name-kbd = кабардин тілі
language-name-kcg = тьяп тілі
language-name-kde = маконде тілі
language-name-kea = кабувердьяну тілі
language-name-kfo = коро тілі
language-name-kha = кхаси тілі
language-name-khq = койра чини тілі
language-name-ki = кикуйю тілі
language-name-kj = кваньяма тілі
language-name-kk = қазақ тілі
language-name-kkj = како тілі
language-name-kl = калаалисут тілі
language-name-kln = каленжин тілі
language-name-km = кхмер тілі
language-name-kmb = кимбунду тілі
language-name-kn = каннада тілі
language-name-ko = корей тілі
language-name-koi = коми-пермяк тілі
language-name-kok = конкани тілі
language-name-kpe = кпелле тілі
language-name-kr = канури тілі
language-name-krc = қарашай-балқар тілі
language-name-krl = карель тілі
language-name-kru = курух тілі
language-name-ks = кашмир тілі
language-name-ksb = шамбала тілі
language-name-ksf = бафиа тілі
language-name-ksh = кёльн тілі
language-name-ku = күрд тілі
language-name-kum = құмық тілі
language-name-kv = коми тілі
language-name-kw = корн тілі
language-name-ky = қырғыз тілі
language-name-la = латын тілі
language-name-lad = ладино тілі
language-name-lag = ланги тілі
language-name-lb = люксембург тілі
language-name-lez = лезгин тілі
language-name-lg = ганда тілі
language-name-li = лимбург тілі
language-name-lkt = лакота тілі
language-name-ln = лингала тілі
language-name-lo = лаос тілі
language-name-loz = лози тілі
language-name-lrc = солтүстік люри тілі
language-name-lt = литва тілі
language-name-lu = луба-катанга тілі
language-name-lua = луба-лулуа тілі
language-name-lun = лунда тілі
language-name-luo = луо тілі
language-name-lus = мизо тілі
language-name-luy = лухиа тілі
language-name-lv = латыш тілі
language-name-mad = мадур тілі
language-name-mag = магахи тілі
language-name-mai = майтхили тілі
language-name-mak = макасар тілі
language-name-mas = масай тілі
language-name-mdf = мокша тілі
language-name-men = менде тілі
language-name-mer = меру тілі
language-name-mfe = морисиен тілі
language-name-mg = малагаси тілі
language-name-mgh = макуа-меетто тілі
language-name-mgo = мета тілі
language-name-mh = маршалл тілі
language-name-mi = маори тілі
language-name-mic = микмак тілі
language-name-min = минангкабау тілі
language-name-mk = македон тілі
language-name-ml = малаялам тілі
language-name-mn = моңғол тілі
language-name-mni = манипури тілі
language-name-moh = могавк тілі
language-name-mos = мосси тілі
language-name-mr = маратхи тілі
language-name-ms = малай тілі
language-name-mt = мальта тілі
language-name-mua = мунданг тілі
language-name-mul = бірнеше тіл
language-name-mus = крик тілі
language-name-mwl = миранд тілі
language-name-my = бирма тілі
language-name-myv = эрзян тілі
language-name-mzn = мазандеран тілі
language-name-na = науру тілі
language-name-nap = неаполитан тілі
language-name-naq = нама тілі
language-name-nb = норвегиялық букмол тілі
language-name-nd = солтүстік ндебеле тілі
language-name-nds = төменгі неміс тілі
language-name-nds_NL = төменгі саксон тілі
language-name-ne = непал тілі
language-name-new = невар тілі
language-name-ng = ндонга тілі
language-name-nia = ниас тілі
language-name-niu = ниуэ тілі
language-name-nl = нидерланд тілі
language-name-nl_BE = фламанд тілі
language-name-nmg = квасио тілі
language-name-nn = норвегиялық нюнорск тілі
language-name-nnh = нгиембун тілі
language-name-no = норвег тілі
language-name-nog = ноғай тілі
language-name-nqo = нко тілі
language-name-nr = оңтүстік ндебеле тілі
language-name-nso = солтүстік сото тілі
language-name-nus = нуэр тілі
language-name-nv = навахо тілі
language-name-ny = ньянджа тілі
language-name-nyn = нианколе тілі
language-name-oc = окситан тілі
language-name-om = оромо тілі
language-name-or = ория тілі
language-name-os = осетин тілі
language-name-pa = пенджаб тілі
language-name-pag = пангасинан тілі
language-name-pam = пампанга тілі
language-name-pap = папьяменто тілі
language-name-pau = палау тілі
language-name-pcm = нигериялық пиджин тілі
language-name-pl = поляк тілі
language-name-prg = пруссия тілі
language-name-ps = пушту тілі
language-name-pt = португал тілі
language-name-pt_BR = бразилиялық португал тілі
language-name-pt_PT = еуропалық португал тілі
language-name-qu = кечуа тілі
language-name-quc = киче тілі
language-name-rap = рапануй тілі
language-name-rar = раротонган тілі
language-name-rm = романш тілі
language-name-rn = рунди тілі
language-name-ro = румын тілі
language-name-ro_MD = молдован тілі
language-name-rof = ромбо тілі
language-name-root = ата тіл
language-name-ru = орыс тілі
language-name-rup = арумын тілі
language-name-rw = киньяруанда тілі
language-name-rwk = руа тілі
language-name-sa = санскрит тілі
language-name-sad = сандаве тілі
language-name-sah = якут тілі
language-name-saq = самбуру тілі
language-name-sat = сантали тілі
language-name-sba = нгамбай тілі
language-name-sbp = сангу тілі
language-name-sc = сардин тілі
language-name-scn = сицилия тілі
language-name-sco = шотланд тілі
language-name-sd = синдхи тілі
language-name-sdh = оңтүстік күрд тілі
language-name-se = солтүстік саам тілі
language-name-seh = сена тілі
language-name-ses = койраборо сенни тілі
language-name-sg = санго тілі
language-name-sh = серб-хорват тілі
language-name-shi = ташелхит тілі
language-name-shn = шан тілі
language-name-si = сингал тілі
language-name-sk = словак тілі
language-name-sl = словен тілі
language-name-sm = самоа тілі
language-name-sma = оңтүстік саам тілі
language-name-smj = луле саам тілі
language-name-smn = инари саам тілі
language-name-sms = колтта саам тілі
language-name-sn = шона тілі
language-name-snk = сонинке тілі
language-name-so = сомали тілі
language-name-sq = албан тілі
language-name-sr = серб тілі
language-name-srn = сранан тонго тілі
language-name-ss = свати тілі
language-name-ssy = сахо тілі
language-name-st = сесото тілі
language-name-su = сундан тілі
language-name-suk = сукума тілі
language-name-sv = швед тілі
language-name-sw = суахили тілі
language-name-sw_CD = конго суахили тілі
language-name-swb = комор тілі
language-name-syr = сирия тілі
language-name-ta = тамил тілі
language-name-te = телугу тілі
language-name-tem = темне тілі
language-name-teo = тесо тілі
language-name-tet = тетум тілі
language-name-tg = тәжік тілі
language-name-th = тай тілі
language-name-ti = тигринья тілі
language-name-tig = тигре тілі
language-name-tk = түрікмен тілі
language-name-tlh = клингон тілі
language-name-tn = тсвана тілі
language-name-to = тонган тілі
language-name-tpi = ток-писин тілі
language-name-tr = түрік тілі
language-name-trv = тароко тілі
language-name-ts = тсонга тілі
language-name-tt = татар тілі
language-name-tum = тумбука тілі
language-name-tvl = тувалу тілі
language-name-tw = тви тілі
language-name-twq = тасавак тілі
language-name-ty = таити тілі
language-name-tyv = тувин тілі
language-name-tzm = орталық атлас тамазигхт тілі
language-name-udm = удмурт тілі
language-name-ug = ұйғыр тілі
language-name-uk = украин тілі
language-name-umb = умбунду тілі
language-name-und = белгісіз тіл
language-name-ur = урду тілі
language-name-uz = өзбек тілі
language-name-vai = вай тілі
language-name-ve = венда тілі
language-name-vi = вьетнам тілі
language-name-vo = волапюк тілі
language-name-vun = вунджо тілі
language-name-wa = валлон тілі
language-name-wae = вальзер тілі
language-name-wal = волайта тілі
language-name-war = варай тілі
language-name-wbp = вальбири тілі
language-name-wo = волоф тілі
language-name-xal = қалмақ тілі
language-name-xh = кхоса тілі
language-name-xog = сога тілі
language-name-yav = янгбен тілі
language-name-ybb = йемба тілі
language-name-yi = идиш тілі
language-name-yo = йоруба тілі
language-name-yue = кантон тілі
language-name-zgh = марокколық стандартты тамазигхт тілі
language-name-zh = қытай тілі
language-name-zh_Hans = жеңілдетілген қытай тілі
language-name-zh_Hant = дәстүрлі қытай тілі
language-name-zu = зулу тілі
language-name-zun = зуни тілі
language-name-zxx = тілдік мазмұны жоқ
language-name-zza = заза тілі
