language-name-aa = آفاری
language-name-ab = آبخازی
language-name-ace = آچئی
language-name-ach = آچولیایی
language-name-ada = آدانگمه‌ای
language-name-ady = آدیجیایی
language-name-ae = اوستایی
language-name-aeb = عربی تونسی
language-name-af = آفریکانس
language-name-afh = آفریهیلی
language-name-agq = آگیم
language-name-ain = آینویی
language-name-ak = آکان
language-name-akk = اکدی
language-name-akz = آلابامایی
language-name-ale = آلئوتی
language-name-alt = آلتایی جنوبی
language-name-am = امهری
language-name-an = آراگونی
language-name-ang = انگلیسی باستان
language-name-anp = آنگیکا
language-name-ar = عربی
language-name-ar_001 = عربی رسمی
language-name-arc = آرامی
language-name-arn = ماپوچه‌ای
language-name-arp = آراپاهویی
language-name-arq = عربی الجزایری
language-name-arw = آراواکی
language-name-ary = عربی مراکشی
language-name-arz = عربی مصری
language-name-as = آسامی
language-name-asa = آسو
language-name-ast = آستوری
language-name-av = آواری
language-name-awa = اودهی
language-name-ay = آیمارایی
language-name-az = ترکی آذربایجانی
language-name-az_Arab = ترکی آذری جنوبی
language-name-ba = باشغیری
language-name-bal = بلوچی
language-name-ban = بالیایی
language-name-bar = باواریایی
language-name-bas = باسایی
language-name-bax = بمونی
language-name-be = بلاروسی
language-name-bej = بجایی
language-name-bem = بمبایی
language-name-bez = بنایی
language-name-bg = بلغاری
language-name-bgn = بلوچی غربی
language-name-bho = بوجپوری
language-name-bi = بیسلاما
language-name-bik = بیکولی
language-name-bin = بینی
language-name-bla = سیکسیکا
language-name-bm = بامبارایی
language-name-bn = بنگالی
language-name-bo = تبتی
language-name-bqi = لری بختیاری
language-name-br = برتون
language-name-bra = براج
language-name-brh = براهویی
language-name-brx = بودویی
language-name-bs = بوسنیایی
language-name-bua = بوریاتی
language-name-bug = بوگیایی
language-name-byn = بلین
language-name-ca = کاتالان
language-name-cad = کادویی
language-name-car = کاریبی
language-name-ce = چچنی
language-name-ceb = سبویی
language-name-cgg = چیگا
language-name-ch = چامورویی
language-name-chb = چیبچا
language-name-chg = جغتایی
language-name-chk = چوکی
language-name-chm = ماریایی
language-name-cho = چوکتویی
language-name-chp = چیپه‌ویه‌ای
language-name-chr = چروکیایی
language-name-chy = شایانی
language-name-ckb = کردی مرکزی
language-name-co = کورسی
language-name-cop = قبطی
language-name-cr = کریایی
language-name-crh = ترکی کریمه
language-name-crs = سیشل آمیختهٔ فرانسوی
language-name-cs = چکی
language-name-csb = کاشوبی
language-name-cu = اسلاوی کلیسایی
language-name-cv = چوواشی
language-name-cy = ولزی
language-name-da = دانمارکی
language-name-dak = داکوتایی
language-name-dar = دارقینی
language-name-dav = تایتا
language-name-de = آلمانی
language-name-de_AT = آلمانی اتریش
language-name-de_CH = آلمانی معیار سوئیس
language-name-del = دلاواری
language-name-dgr = دوگریب
language-name-din = دینکایی
language-name-dje = زرما
language-name-doi = دوگری
language-name-dsb = صُربی سفلی
language-name-dua = دوآلایی
language-name-dum = هلندی میانه
language-name-dv = دیوهی
language-name-dyo = دیولا فونی
language-name-dyu = دایولایی
language-name-dz = جونخایی
language-name-dzg = دازاگایی
language-name-ebu = امبو
language-name-ee = اوه‌ای
language-name-efi = افیکی
language-name-egy = مصری کهن
language-name-eka = اکاجوک
language-name-el = یونانی
language-name-elx = عیلامی
language-name-en = انگلیسی
language-name-en_AU = انگلیسی استرالیا
language-name-en_CA = انگلیسی کانادا
language-name-en_GB = انگلیسی بریتانیا
language-name-en_US = انگلیسی امریکا
language-name-enm = انگلیسی میانه
language-name-eo = اسپرانتو
language-name-es = اسپانیایی
language-name-es_419 = اسپانیایی امریکای لاتین
language-name-es_ES = اسپانیایی اروپا
language-name-es_MX = اسپانیایی مکزیک
language-name-et = استونیایی
language-name-eu = باسکی
language-name-ewo = اواندو
language-name-fa = فارسی
language-name-fa_AF = دری
language-name-fan = فانگی
language-name-fat = فانتیایی
language-name-ff = فولایی
language-name-fi = فنلاندی
language-name-fil = فیلیپینی
language-name-fj = فیجیایی
language-name-fo = فارویی
language-name-fon = فونی
language-name-fr = فرانسوی
language-name-fr_CA = فرانسوی کانادا
language-name-fr_CH = فرانسوی سوئیس
language-name-frc = فرانسوی کادین
language-name-frm = فرانسوی میانه
language-name-fro = فرانسوی باستان
language-name-frr = فریزی شمالی
language-name-frs = فریزی شرقی
language-name-fur = فریولیایی
language-name-fy = فریزی غربی
language-name-ga = ایرلندی
language-name-gaa = گایی
language-name-gag = گاگائوزیایی
language-name-gay = گایویی
language-name-gba = گبایایی
language-name-gbz = دری زرتشتی
language-name-gd = گیلی اسکاتلندی
language-name-gez = گی‌ئزی
language-name-gil = گیلبرتی
language-name-gl = گالیسیایی
language-name-glk = گیلکی
language-name-gmh = آلمانی معیار میانه
language-name-gn = گوارانی
language-name-goh = آلمانی علیای باستان
language-name-gon = گوندی
language-name-gor = گورونتالو
language-name-got = گوتی
language-name-grb = گریبویی
language-name-grc = یونانی کهن
language-name-gsw = آلمانی سوئیسی
language-name-gu = گجراتی
language-name-guz = گوسی
language-name-gv = مانی
language-name-gwi = گویچ این
language-name-ha = هوسیایی
language-name-hai = هایدایی
language-name-haw = هاوائیایی
language-name-he = عبری
language-name-hi = هندی
language-name-hif = هندی فیجیایی
language-name-hil = هیلی‌گاینونی
language-name-hit = هیتی
language-name-hmn = همونگ
language-name-ho = موتویی هیری
language-name-hr = کروات
language-name-hsb = صُربی علیا
language-name-ht = هائیتیایی
language-name-hu = مجاری
language-name-hup = هوپا
language-name-hy = ارمنی
language-name-hz = هریرویی
language-name-ia = میان‌زبان
language-name-iba = ایبانی
language-name-ibb = ایبیبیو
language-name-id = اندونزیایی
language-name-ie = اکسیدنتال
language-name-ig = ایگبویی
language-name-ii = یی سیچوان
language-name-ik = اینوپیک
language-name-ilo = ایلوکویی
language-name-inh = اینگوشی
language-name-io = ایدو
language-name-is = ایسلندی
language-name-it = ایتالیایی
language-name-iu = اینوکتیتوت
language-name-ja = ژاپنی
language-name-jbo = لوجبان
language-name-jgo = نگومبا
language-name-jmc = ماچامه‌ای
language-name-jpr = فارسی یهودی
language-name-jrb = عربی یهودی
language-name-jv = جاوه‌ای
language-name-ka = گرجی
language-name-kaa = قره‌قالپاقی
language-name-kab = قبایلی
language-name-kac = کاچینی
language-name-kaj = جو
language-name-kam = کامبایی
language-name-kaw = کاویایی
language-name-kbd = کاباردینی
language-name-kcg = تیاپی
language-name-kde = ماکونده
language-name-kea = کابووردیانو
language-name-kfo = کورو
language-name-kg = کنگویی
language-name-kha = خاسیایی
language-name-kho = ختنی
language-name-khq = کوجراچینی
language-name-khw = کهوار
language-name-ki = کیکویویی
language-name-kiu = کرمانجی
language-name-kj = کوانیاما
language-name-kk = قزاقی
language-name-kkj = کاکایی
language-name-kl = گرینلندی
language-name-kln = کالنجین
language-name-km = خمری
language-name-kmb = کیمبوندویی
language-name-kn = کانارا
language-name-ko = کره‌ای
language-name-koi = کومی پرمیاک
language-name-kok = کنکانی
language-name-kpe = کپله‌ای
language-name-kr = کانوریایی
language-name-krc = قره‌چایی‐بالکاری
language-name-krl = کاریلیانی
language-name-kru = کوروخی
language-name-ks = کشمیری
language-name-ksb = شامبالا
language-name-ksf = بافیایی
language-name-ksh = ریپواری
language-name-ku = کردی
language-name-kum = کومیکی
language-name-kut = کوتنی
language-name-kv = کومیایی
language-name-kw = کرنوالی
language-name-ky = قرقیزی
language-name-la = لاتین
language-name-lad = لادینو
language-name-lag = لانگی
language-name-lah = لاهندا
language-name-lam = لامبا
language-name-lb = لوگزامبورگی
language-name-lez = لزگی
language-name-lg = گاندایی
language-name-li = لیمبورگی
language-name-lkt = لاکوتا
language-name-ln = لینگالا
language-name-lo = لائوسی
language-name-lol = مونگویی
language-name-lou = زبان آمیختهٔ مادری لوئیزیانا
language-name-loz = لوزیایی
language-name-lrc = لری شمالی
language-name-lt = لیتوانیایی
language-name-lu = لوبایی‐کاتانگا
language-name-lua = لوبایی‐لولوا
language-name-lui = لویسنو
language-name-lun = لوندایی
language-name-luo = لوئویی
language-name-lus = لوشه‌ای
language-name-luy = لویا
language-name-lv = لتونیایی
language-name-lzh = چینی ادبی
language-name-mad = مادورایی
language-name-mag = ماگاهیایی
language-name-mai = مایدیلی
language-name-mak = ماکاسار
language-name-man = ماندینگویی
language-name-mas = ماسایی
language-name-mdf = مکشایی
language-name-mdr = ماندار
language-name-men = منده‌ای
language-name-mer = مرویی
language-name-mfe = موریسین
language-name-mg = مالاگاسیایی
language-name-mga = ایرلندی میانه
language-name-mgh = ماکوا متو
language-name-mgo = متایی
language-name-mh = مارشالی
language-name-mi = مائوریایی
language-name-mic = میکماکی
language-name-min = مینانگ‌کابویی
language-name-mk = مقدونی
language-name-ml = مالایالامی
language-name-mn = مغولی
language-name-mnc = مانچویی
language-name-mni = میته‌ای
language-name-moh = موهاکی
language-name-mos = ماسیایی
language-name-mr = مراتی
language-name-ms = مالایی
language-name-mt = مالتی
language-name-mua = ماندانگی
language-name-mul = چندین زبان
language-name-mus = کریکی
language-name-mwl = میراندی
language-name-mwr = مارواری
language-name-my = برمه‌ای
language-name-myv = ارزیایی
language-name-mzn = مازندرانی
language-name-na = نائورویی
language-name-nap = ناپلی
language-name-naq = نامایی
language-name-nb = نروژی بوک‌مُل
language-name-nd = انده‌بله‌ای شمالی
language-name-nds = آلمانی سفلی
language-name-nds_NL = ساکسونی سفلی
language-name-ne = نپالی
language-name-new = نواریایی
language-name-ng = اندونگایی
language-name-nia = نیاسی
language-name-niu = نیویی
language-name-nl = هلندی
language-name-nl_BE = فلمنگی
language-name-nmg = کوازیو
language-name-nn = نروژی نی‌نُشک
language-name-nnh = انگیمبونی
language-name-no = نروژی
language-name-nog = نغایی
language-name-non = نرس باستان
language-name-nqo = نکو
language-name-nr = انده‌بله‌ای جنوبی
language-name-nso = سوتویی شمالی
language-name-nus = نویر
language-name-nv = ناواهویی
language-name-nwc = نواریایی کلاسیک
language-name-ny = نیانجایی
language-name-nym = نیام‌وزیایی
language-name-nyn = نیانکوله‌ای
language-name-nyo = نیورویی
language-name-nzi = نزیمایی
language-name-oc = اوکیتایی
language-name-oj = اوجیبوایی
language-name-om = اورومویی
language-name-or = اوریه‌ای
language-name-os = آسی
language-name-osa = اوسیجی
language-name-ota = ترکی عثمانی
language-name-pa = پنجابی
language-name-pag = پانگاسینانی
language-name-pal = پهلوی
language-name-pam = پامپانگایی
language-name-pap = پاپیامنتو
language-name-pau = پالائویی
language-name-pcm = نیم‌زبان نیجریه‌ای
language-name-pdc = آلمانی پنسیلوانیایی
language-name-peo = فارسی باستان
language-name-phn = فنیقی
language-name-pi = پالی
language-name-pl = لهستانی
language-name-pon = پانپیی
language-name-prg = پروسی
language-name-pro = پرووانسی باستان
language-name-ps = پشتو
language-name-pt = پرتغالی
language-name-pt_BR = پرتغالی برزیل
language-name-pt_PT = پرتغالی اروپا
language-name-qu = کچوایی
language-name-quc = کیچه‌
language-name-raj = راجستانی
language-name-rap = راپانویی
language-name-rar = راروتونگایی
language-name-rm = رومانش
language-name-rn = روندیایی
language-name-ro = رومانیایی
language-name-ro_MD = مولداویایی
language-name-rof = رومبویی
language-name-rom = رومانویی
language-name-root = ریشه
language-name-ru = روسی
language-name-rup = آرومانی
language-name-rw = کینیارواندایی
language-name-rwk = روایی
language-name-sa = سانسکریت
language-name-sad = سانداوه‌ای
language-name-sah = یاقوتی
language-name-sam = آرامی سامری
language-name-saq = سامبورو
language-name-sas = ساساکی
language-name-sat = سانتالی
language-name-sba = انگامبایی
language-name-sbp = سانگویی
language-name-sc = ساردینیایی
language-name-scn = سیسیلی
language-name-sco = اسکاتلندی
language-name-sd = سندی
language-name-sdh = کردی جنوبی
language-name-se = سامی شمالی
language-name-seh = سنا
language-name-sel = سلکوپی
language-name-ses = کویرابورا سنی
language-name-sg = سانگو
language-name-sga = ایرلندی باستان
language-name-sh = صرب و کرواتی
language-name-shi = تاچل‌هیت
language-name-shn = شانی
language-name-shu = عربی چادی
language-name-si = سینهالی
language-name-sid = سیدامویی
language-name-sk = اسلواکی
language-name-sl = اسلوونیایی
language-name-sli = سیلزیایی سفلی
language-name-sm = ساموآیی
language-name-sma = سامی جنوبی
language-name-smj = لوله سامی
language-name-smn = ایناری سامی
language-name-sms = اسکولت سامی
language-name-sn = شونایی
language-name-snk = سونینکه‌ای
language-name-so = سومالیایی
language-name-sog = سغدی
language-name-sq = آلبانیایی
language-name-sr = صربی
language-name-srn = تاکی‌تاکی
language-name-srr = سریری
language-name-ss = سوازیایی
language-name-ssy = ساهو
language-name-st = سوتویی جنوبی
language-name-su = سوندایی
language-name-suk = سوکومایی
language-name-sus = سوسویی
language-name-sux = سومری
language-name-sv = سوئدی
language-name-sw = سواحیلی
language-name-sw_CD = سواحیلی کنگو
language-name-swb = کوموری
language-name-syc = سریانی کلاسیک
language-name-syr = سریانی
language-name-szl = سیلزیایی
language-name-ta = تامیلی
language-name-te = تلوگویی
language-name-tem = تمنه‌ای
language-name-teo = تسویی
language-name-ter = ترنو
language-name-tet = تتومی
language-name-tg = تاجیکی
language-name-th = تایلندی
language-name-ti = تیگرینیایی
language-name-tig = تیگره‌ای
language-name-tiv = تیوی
language-name-tk = ترکمنی
language-name-tl = تاگالوگی
language-name-tlh = کلینگون
language-name-tli = تلین‌گیتی
language-name-tmh = تاماشقی
language-name-tn = تسوانایی
language-name-to = تونگایی
language-name-tog = تونگایی نیاسا
language-name-tpi = توک‌پیسینی
language-name-tr = ترکی استانبولی
language-name-trv = تاروکویی
language-name-ts = تسونگایی
language-name-tsi = تسیم‌شیانی
language-name-tt = تاتاری
language-name-tum = تومبوکایی
language-name-tvl = تووالویی
language-name-tw = توی‌یایی
language-name-twq = تسواکی
language-name-ty = تاهیتیایی
language-name-tyv = تووایی
language-name-tzm = آمازیغی اطلس مرکزی
language-name-udm = اودمورتی
language-name-ug = اویغوری
language-name-uga = اوگاریتی
language-name-uk = اوکراینی
language-name-umb = امبوندویی
language-name-und = زبان نامشخص
language-name-ur = اردو
language-name-uz = ازبکی
language-name-vai = ویایی
language-name-ve = وندایی
language-name-vi = ویتنامی
language-name-vo = ولاپوک
language-name-vot = وتی
language-name-vun = ونجو
language-name-wa = والونی
language-name-wae = والسر
language-name-wal = والامو
language-name-war = وارایی
language-name-was = واشویی
language-name-wbp = وارلپیری
language-name-wo = ولوفی
language-name-xal = قلموقی
language-name-xh = خوسایی
language-name-xog = سوگایی
language-name-yao = یائویی
language-name-yap = یاپی
language-name-yav = یانگبنی
language-name-ybb = یمبایی
language-name-yi = یدی
language-name-yo = یوروبایی
language-name-yue = کانتونی
language-name-za = چوانگی
language-name-zap = زاپوتکی
language-name-zen = زناگا
language-name-zgh = آمازیغی معیار مراکش
language-name-zh = چینی
language-name-zh_Hans = چینی ساده‌شده
language-name-zh_Hant = چینی سنتی
language-name-zu = زولویی
language-name-zun = زونیایی
language-name-zxx = بدون محتوای زبانی
language-name-zza = زازایی
