language-name-aa = afar
language-name-ab = abjasio
language-name-ace = acehnés
language-name-ach = acoli
language-name-ada = adangme
language-name-ady = adigué
language-name-ae = avéstico
language-name-af = afrikáans
language-name-afh = afrihili
language-name-agq = aghem
language-name-ain = ainu
language-name-ak = akan
language-name-akk = acadio
language-name-ale = aleutiano
language-name-alt = altái meridional
language-name-am = amárico
language-name-an = aragonés
language-name-ang = inglés antiguo
language-name-anp = angika
language-name-ar = árabe
language-name-ar_001 = árabe estándar moderno
language-name-arc = arameo
language-name-arn = mapuche
language-name-arp = arapaho
language-name-ars = árabe najdí
language-name-arw = arahuaco
language-name-as = asamés
language-name-asa = asu
language-name-ast = asturiano
language-name-av = avar
language-name-awa = avadhi
language-name-ay = aimara
language-name-az = azerbaiyano
language-name-ba = baskir
language-name-bal = baluchi
language-name-ban = balinés
language-name-bas = basaa
language-name-bax = bamún
language-name-bbj = ghomala
language-name-be = bielorruso
language-name-bej = beja
language-name-bem = bemba
language-name-bez = bena
language-name-bfd = bafut
language-name-bg = búlgaro
language-name-bgn = baluchi occidental
language-name-bho = bhoyapurí
language-name-bi = bislama
language-name-bik = bicol
language-name-bin = bini
language-name-bkm = kom
language-name-bla = siksika
language-name-bm = bambara
language-name-bn = bengalí
language-name-bo = tibetano
language-name-br = bretón
language-name-bra = braj
language-name-brx = bodo
language-name-bs = bosnio
language-name-bss = akoose
language-name-bua = buriato
language-name-bug = buginés
language-name-bum = bulu
language-name-byn = blin
language-name-byv = medumba
language-name-ca = catalán
language-name-cad = caddo
language-name-car = caribe
language-name-cay = cayuga
language-name-cch = atsam
language-name-ce = checheno
language-name-ceb = cebuano
language-name-cgg = chiga
language-name-ch = chamorro
language-name-chb = chibcha
language-name-chg = chagatái
language-name-chk = trukés
language-name-chm = marí
language-name-chn = jerga chinuk
language-name-cho = choctaw
language-name-chp = chipewyan
language-name-chr = cheroqui
language-name-chy = cheyene
language-name-ckb = kurdo sorani
language-name-co = corso
language-name-cop = copto
language-name-cr = cree
language-name-crh = tártaro de Crimea
language-name-crs = criollo seychelense
language-name-cs = checo
language-name-csb = casubio
language-name-cu = eslavo eclesiástico
language-name-cv = chuvasio
language-name-cy = galés
language-name-da = danés
language-name-dak = dakota
language-name-dar = dargva
language-name-dav = taita
language-name-de = alemán
language-name-de_AT = alemán austríaco
language-name-de_CH = alto alemán suizo
language-name-del = delaware
language-name-den = slave
language-name-dgr = dogrib
language-name-din = dinka
language-name-dje = zarma
language-name-doi = dogri
language-name-dsb = bajo sorbio
language-name-dua = duala
language-name-dum = neerlandés medio
language-name-dv = divehi
language-name-dyo = jola-fonyi
language-name-dyu = diula
language-name-dz = dzongkha
language-name-dzg = dazaga
language-name-ebu = embu
language-name-ee = ewé
language-name-efi = efik
language-name-egy = egipcio antiguo
language-name-eka = ekajuk
language-name-el = griego
language-name-elx = elamita
language-name-en = inglés
language-name-en_AU = inglés australiano
language-name-en_CA = inglés canadiense
language-name-en_GB = inglés británico
language-name-en_US = inglés estadounidense
language-name-enm = inglés medio
language-name-eo = esperanto
language-name-es = español
language-name-es_419 = español latinoamericano
language-name-es_ES = español de España
language-name-es_MX = español de México
language-name-et = estonio
language-name-eu = euskera
language-name-ewo = ewondo
language-name-fa = persa
language-name-fan = fang
language-name-fat = fanti
language-name-ff = fula
language-name-fi = finés
language-name-fil = filipino
language-name-fj = fiyiano
language-name-fo = feroés
language-name-fon = fon
language-name-fr = francés
language-name-fr_CA = francés canadiense
language-name-fr_CH = francés suizo
language-name-frc = francés cajún
language-name-frm = francés medio
language-name-fro = francés antiguo
language-name-frr = frisón septentrional
language-name-frs = frisón oriental
language-name-fur = friulano
language-name-fy = frisón occidental
language-name-ga = irlandés
language-name-gaa = ga
language-name-gag = gagauzo
language-name-gan = chino gan
language-name-gay = gayo
language-name-gba = gbaya
language-name-gd = gaélico escocés
language-name-gez = geez
language-name-gil = gilbertés
language-name-gl = gallego
language-name-gmh = alto alemán medio
language-name-gn = guaraní
language-name-goh = alto alemán antiguo
language-name-gon = gondi
language-name-gor = gorontalo
language-name-got = gótico
language-name-grb = grebo
language-name-grc = griego antiguo
language-name-gsw = alemán suizo
language-name-gu = guyaratí
language-name-guz = gusii
language-name-gv = manés
language-name-gwi = kutchin
language-name-ha = hausa
language-name-hai = haida
language-name-hak = chino hakka
language-name-haw = hawaiano
language-name-he = hebreo
language-name-hi = hindi
language-name-hil = hiligaynon
language-name-hit = hitita
language-name-hmn = hmong
language-name-ho = hiri motu
language-name-hr = croata
language-name-hsb = alto sorbio
language-name-hsn = chino xiang
language-name-ht = criollo haitiano
language-name-hu = húngaro
language-name-hup = hupa
language-name-hy = armenio
language-name-hz = herero
language-name-ia = interlingua
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indonesio
language-name-ie = interlingue
language-name-ig = igbo
language-name-ii = yi de Sichuán
language-name-ik = inupiaq
language-name-ilo = ilocano
language-name-inh = ingush
language-name-io = ido
language-name-is = islandés
language-name-it = italiano
language-name-iu = inuktitut
language-name-ja = japonés
language-name-jbo = lojban
language-name-jgo = ngomba
language-name-jmc = machame
language-name-jpr = judeo-persa
language-name-jrb = judeo-árabe
language-name-jv = javanés
language-name-ka = georgiano
language-name-kaa = karakalpako
language-name-kab = cabila
language-name-kac = kachin
language-name-kaj = jju
language-name-kam = kamba
language-name-kaw = kawi
language-name-kbd = kabardiano
language-name-kbl = kanembu
language-name-kcg = tyap
language-name-kde = makonde
language-name-kea = criollo caboverdiano
language-name-kfo = koro
language-name-kg = kongo
language-name-kha = khasi
language-name-kho = kotanés
language-name-khq = koyra chiini
language-name-ki = kikuyu
language-name-kj = kuanyama
language-name-kk = kazajo
language-name-kkj = kako
language-name-kl = groenlandés
language-name-kln = kalenjin
language-name-km = jemer
language-name-kmb = kimbundu
language-name-kn = canarés
language-name-ko = coreano
language-name-koi = komi permio
language-name-kok = konkaní
language-name-kos = kosraeano
language-name-kpe = kpelle
language-name-kr = kanuri
language-name-krc = karachay-balkar
language-name-krl = carelio
language-name-kru = kurukh
language-name-ks = cachemiro
language-name-ksb = shambala
language-name-ksf = bafia
language-name-ksh = kölsch
language-name-ku = kurdo
language-name-kum = kumyk
language-name-kut = kutenai
language-name-kv = komi
language-name-kw = córnico
language-name-ky = kirguís
language-name-la = latín
language-name-lad = ladino
language-name-lag = langi
language-name-lah = lahnda
language-name-lam = lamba
language-name-lb = luxemburgués
language-name-lez = lezgiano
language-name-lg = ganda
language-name-li = limburgués
language-name-lkt = lakota
language-name-ln = lingala
language-name-lo = lao
language-name-lol = mongo
language-name-lou = criollo de Luisiana
language-name-loz = lozi
language-name-lrc = lorí septentrional
language-name-lt = lituano
language-name-lu = luba-katanga
language-name-lua = luba-lulua
language-name-lui = luiseño
language-name-lun = lunda
language-name-luo = luo
language-name-lus = mizo
language-name-luy = luyia
language-name-lv = letón
language-name-mad = madurés
language-name-maf = mafa
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = macasar
language-name-man = mandingo
language-name-mas = masái
language-name-mde = maba
language-name-mdf = moksha
language-name-mdr = mandar
language-name-men = mende
language-name-mer = meru
language-name-mfe = criollo mauriciano
language-name-mg = malgache
language-name-mga = irlandés medio
language-name-mgh = makhuwa-meetto
language-name-mgo = meta’
language-name-mh = marshalés
language-name-mi = maorí
language-name-mic = micmac
language-name-min = minangkabau
language-name-mk = macedonio
language-name-ml = malayalam
language-name-mn = mongol
language-name-mnc = manchú
language-name-mni = manipuri
language-name-moh = mohawk
language-name-mos = mossi
language-name-mr = maratí
language-name-ms = malayo
language-name-mt = maltés
language-name-mua = mundang
language-name-mul = varios idiomas
language-name-mus = creek
language-name-mwl = mirandés
language-name-mwr = marwari
language-name-my = birmano
language-name-mye = myene
language-name-myv = erzya
language-name-mzn = mazandaraní
language-name-na = nauruano
language-name-nan = chino min nan
language-name-nap = napolitano
language-name-naq = nama
language-name-nb = noruego bokmal
language-name-nd = ndebele septentrional
language-name-nds = bajo alemán
language-name-nds_NL = bajo sajón
language-name-ne = nepalí
language-name-new = newari
language-name-ng = ndonga
language-name-nia = nias
language-name-niu = niueano
language-name-nl = neerlandés
language-name-nl_BE = flamenco
language-name-nmg = kwasio
language-name-nn = noruego nynorsk
language-name-nnh = ngiemboon
language-name-no = noruego
language-name-nog = nogai
language-name-non = nórdico antiguo
language-name-nqo = n’ko
language-name-nr = ndebele meridional
language-name-nso = sesotho septentrional
language-name-nus = nuer
language-name-nv = navajo
language-name-nwc = newari clásico
language-name-ny = nyanja
language-name-nym = nyamwezi
language-name-nyn = nyankole
language-name-nyo = nyoro
language-name-nzi = nzima
language-name-oc = occitano
language-name-oj = ojibwa
language-name-om = oromo
language-name-or = oriya
language-name-os = osético
language-name-osa = osage
language-name-ota = turco otomano
language-name-pa = panyabí
language-name-pag = pangasinán
language-name-pal = pahlavi
language-name-pam = pampanga
language-name-pap = papiamento
language-name-pau = palauano
language-name-pcm = pidgin de Nigeria
language-name-peo = persa antiguo
language-name-phn = fenicio
language-name-pi = pali
language-name-pl = polaco
language-name-pon = pohnpeiano
language-name-prg = prusiano
language-name-pro = provenzal antiguo
language-name-ps = pastún
language-name-pt = portugués
language-name-pt_BR = portugués de Brasil
language-name-pt_PT = portugués de Portugal
language-name-qu = quechua
language-name-quc = quiché
language-name-raj = rajasthani
language-name-rap = rapanui
language-name-rar = rarotongano
language-name-rm = romanche
language-name-rn = kirundi
language-name-ro = rumano
language-name-ro_MD = moldavo
language-name-rof = rombo
language-name-rom = romaní
language-name-root = raíz
language-name-ru = ruso
language-name-rup = arrumano
language-name-rw = kinyarwanda
language-name-rwk = rwa
language-name-sa = sánscrito
language-name-sad = sandawe
language-name-sah = sakha
language-name-sam = arameo samaritano
language-name-saq = samburu
language-name-sas = sasak
language-name-sat = santali
language-name-sba = ngambay
language-name-sbp = sangu
language-name-sc = sardo
language-name-scn = siciliano
language-name-sco = escocés
language-name-sd = sindhi
language-name-sdh = kurdo meridional
language-name-se = sami septentrional
language-name-see = seneca
language-name-seh = sena
language-name-sel = selkup
language-name-ses = koyraboro senni
language-name-sg = sango
language-name-sga = irlandés antiguo
language-name-sh = serbocroata
language-name-shi = tashelhit
language-name-shn = shan
language-name-shu = árabe chadiano
language-name-si = cingalés
language-name-sid = sidamo
language-name-sk = eslovaco
language-name-sl = esloveno
language-name-sm = samoano
language-name-sma = sami meridional
language-name-smj = sami lule
language-name-smn = sami inari
language-name-sms = sami skolt
language-name-sn = shona
language-name-snk = soninké
language-name-so = somalí
language-name-sog = sogdiano
language-name-sq = albanés
language-name-sr = serbio
language-name-srn = sranan tongo
language-name-srr = serer
language-name-ss = suazi
language-name-ssy = saho
language-name-st = sesotho meridional
language-name-su = sundanés
language-name-suk = sukuma
language-name-sus = susu
language-name-sux = sumerio
language-name-sv = sueco
language-name-sw = suajili
language-name-sw_CD = suajili del Congo
language-name-swb = comorense
language-name-syc = siríaco clásico
language-name-syr = siriaco
language-name-ta = tamil
language-name-te = telugu
language-name-tem = temne
language-name-teo = teso
language-name-ter = tereno
language-name-tet = tetún
language-name-tg = tayiko
language-name-th = tailandés
language-name-ti = tigriña
language-name-tig = tigré
language-name-tiv = tiv
language-name-tk = turcomano
language-name-tkl = tokelauano
language-name-tl = tagalo
language-name-tlh = klingon
language-name-tli = tlingit
language-name-tmh = tamashek
language-name-tn = setsuana
language-name-to = tongano
language-name-tog = tonga del Nyasa
language-name-tpi = tok pisin
language-name-tr = turco
language-name-trv = taroko
language-name-ts = tsonga
language-name-tsi = tsimshiano
language-name-tt = tártaro
language-name-tum = tumbuka
language-name-tvl = tuvaluano
language-name-tw = twi
language-name-twq = tasawaq
language-name-ty = tahitiano
language-name-tyv = tuviniano
language-name-tzm = tamazight del Atlas Central
language-name-udm = udmurt
language-name-ug = uigur
language-name-uga = ugarítico
language-name-uk = ucraniano
language-name-umb = umbundu
language-name-und = lengua desconocida
language-name-ur = urdu
language-name-uz = uzbeko
language-name-vai = vai
language-name-ve = venda
language-name-vi = vietnamita
language-name-vo = volapük
language-name-vot = vótico
language-name-vun = vunjo
language-name-wa = valón
language-name-wae = walser
language-name-wal = wolayta
language-name-war = waray
language-name-was = washo
language-name-wbp = warlpiri
language-name-wo = wólof
language-name-wuu = chino wu
language-name-xal = kalmyk
language-name-xh = xhosa
language-name-xog = soga
language-name-yao = yao
language-name-yap = yapés
language-name-yav = yangben
language-name-ybb = yemba
language-name-yi = yidis
language-name-yo = yoruba
language-name-yue = cantonés
language-name-za = zhuang
language-name-zap = zapoteco
language-name-zbl = símbolos Bliss
language-name-zen = zenaga
language-name-zgh = tamazight estándar marroquí
language-name-zh = chino
language-name-zh_Hans = chino simplificado
language-name-zh_Hant = chino tradicional
language-name-zu = zulú
language-name-zun = zuñi
language-name-zxx = sin contenido lingüístico
language-name-zza = zazaki
