language-name-ab = abkáziu
language-name-af = afrikaner
language-name-agq = aghem
language-name-ak = akan
language-name-am = amáriku
language-name-ar = árabi
language-name-ar_001 = árabi mudernu
language-name-arn = araukanu
language-name-as = asames
language-name-asa = asu
language-name-ay = aimara
language-name-az = azerbaijanu
language-name-ba = baxkir
language-name-be = bielorusu
language-name-bem = bemba
language-name-bez = bena
language-name-bg = búlgaru
language-name-bm = bambara
language-name-bn = bengali
language-name-bo = tibetanu
language-name-br = bretãu
language-name-brx = bodo
language-name-bs = bosniu
language-name-ca = katalãu
language-name-ce = txetxenu
language-name-cgg = xiga
language-name-chr = xeroki
language-name-ckb = kurdu sentral
language-name-co = kórsiku
language-name-cs = txeku
language-name-cv = txuvaxi
language-name-cy = gales
language-name-da = dinamarkes
language-name-dav = taita
language-name-de = alimãu
language-name-de_AT = alimãu austriaku
language-name-de_CH = altu alimãu suisu
language-name-dje = zarma
language-name-dsb = sórbiu baxu
language-name-dua = duala
language-name-dyo = jola-fonyi
language-name-dz = dzonka
language-name-ebu = embu
language-name-ee = eve
language-name-el = gregu
language-name-en = ingles
language-name-en_AU = ingles australianu
language-name-en_CA = ingles kanadianu
language-name-en_GB = ingles britaniku
language-name-en_US = ingles merkanu
language-name-eo = sperantu
language-name-es = spanhol
language-name-es_419 = spanhol latinu-merkanu
language-name-es_ES = spanhol europeu
language-name-es_MX = spanhol mexikanu
language-name-et = stonianu
language-name-eu = basku
language-name-fa = persa
language-name-fi = finlandes
language-name-fil = filipinu
language-name-fj = fijianu
language-name-fo = faroes
language-name-fr = franses
language-name-fr_CA = franses kanadianu
language-name-fr_CH = franses suisu
language-name-fy = fríziu osidental
language-name-ga = irlandes
language-name-gag = gagauz
language-name-gl = galegu
language-name-gn = guarani
language-name-gsw = alimãu suísu
language-name-gu = gujarati
language-name-guz = gusii
language-name-gv = manks
language-name-ha = auza
language-name-haw = avaianu
language-name-he = ebraiku
language-name-hi = indi
language-name-hr = kroata
language-name-hsb = sórbiu altu
language-name-ht = aitianu
language-name-hu = úngaru
language-name-hy = arméniu
language-name-id = indonéziu
language-name-ig = ibo
language-name-ii = nuosu
language-name-is = islandes
language-name-it = italianu
language-name-iu = inuktitut
language-name-ja = japones
language-name-jgo = ñomba
language-name-jmc = matxame
language-name-jv = javanes
language-name-ka = jorjianu
language-name-kab = kabila
language-name-kam = kamba
language-name-kea = kabuverdianu
language-name-khq = koira txiini
language-name-ki = kikuiu
language-name-kk = kazak
language-name-kl = groenlandes
language-name-kln = kalenjin
language-name-km = kmer
language-name-kn = kanares
language-name-ko = korianu
language-name-koi = komi-permiak
language-name-kok = konkani
language-name-ks = kaxmira
language-name-ksf = bafia
language-name-ku = kurdu
language-name-kw = kórniku
language-name-ky = kirgiz
language-name-la = latin
language-name-lb = luxemburges
language-name-lg = luganda
language-name-lo = lausianu
language-name-lt = lituanes
language-name-lv = letãu
language-name-mg = malgaxi
language-name-mi = maori
language-name-mk = masedóniu
language-name-ml = malaialam
language-name-mr = marati
language-name-ms = maláiu
language-name-mt = maltes
language-name-my = birmanes
language-name-nb = norueges bokmål
language-name-ne = nepales
language-name-nl = olandes
language-name-nl_BE = flamengu
language-name-nmg = kuazio
language-name-nn = norueges nynorsk
language-name-om = oromo
language-name-or = odía
language-name-pa = pandjabi
language-name-pl = pulaku
language-name-ps = paxto
language-name-pt = purtuges
language-name-pt_BR = purtuges brazileru
language-name-pt_PT = purtuges europeu
language-name-qu = kexua
language-name-quc = kitxe
language-name-rm = romanxi
language-name-ro = rumenu
language-name-ro_MD = rumenu moldáviku
language-name-ru = rusu
language-name-rw = kiniaruanda
language-name-sa = sánskritu
language-name-sd = sindi
language-name-ses = koiraboro seni
language-name-si = singales
language-name-sk = slovaku
language-name-sl = slovéniu
language-name-smn = inari sami
language-name-so = somali
language-name-sq = albanes
language-name-sr = sérviu
language-name-su = sundanes
language-name-sv = sueku
language-name-sw = suaíli
language-name-sw_CD = suaíli kongoles
language-name-ta = tamil
language-name-te = telugu
language-name-tg = tadjiki
language-name-th = tailandes
language-name-ti = tigrinia
language-name-tk = turkmenu
language-name-to = tonganes
language-name-tr = turku
language-name-tt = tatar
language-name-tzm = tamazait di Atlas Sentral
language-name-ug = uigur
language-name-uk = ukranianu
language-name-und = língua diskonxedu
language-name-ur = urdu
language-name-uz = uzbeki
language-name-vi = vietnamita
language-name-wo = uolof
language-name-xh = koza
language-name-yo = ioruba
language-name-zh = xines
language-name-zh_Hans = xines simplifikadu
language-name-zh_Hant = xines tradisional
language-name-zu = zulu
language-name-zxx = sen kontiudu linguístiku
