language-name-aa = අෆාර්
language-name-ab = ඇබ්කාසියානු
language-name-ace = අචයිනිස්
language-name-ada = අඩන්ග්මෙ
language-name-ady = අඩිඝෙ
language-name-aeb = ටියුනිසියනු අරාබි
language-name-af = අෆ්රිකාන්ස්
language-name-agq = ඇගම්
language-name-ain = අයිනු
language-name-ak = අකාන්
language-name-ale = ඇලුඑට්
language-name-alt = සතර්න් අල්ටය්
language-name-am = ඇම්හාරික්
language-name-an = ඇරගොනීස්
language-name-anp = අන්ගික
language-name-ar = අරාබි
language-name-ar_001 = නූතන සම්මත අරාබි
language-name-arn = මපුචෙ
language-name-arp = ඇරපහො
language-name-as = ඇසෑම්
language-name-asa = අසු
language-name-ast = ඇස්ටියුරියන්
language-name-av = ඇවරික්
language-name-awa = අවදි
language-name-ay = අයිමරා
language-name-az = අසර්බයිජාන්
language-name-ba = බාෂ්කිර්
language-name-ban = බැලිනීස්
language-name-bas = බසා
language-name-be = බෙලරුසියානු
language-name-bem = බෙම්බා
language-name-bez = බෙනා
language-name-bg = බල්ගේරියානු
language-name-bgn = බටහිර බලොචි
language-name-bho = බොජ්පුරි
language-name-bi = බිස්ලමා
language-name-bin = බිනි
language-name-bla = සික්සිකා
language-name-bm = බම්බරා
language-name-bn = බෙංගාලි
language-name-bo = ටිබෙට්
language-name-br = බ්‍රේටොන්
language-name-brx = බොඩො
language-name-bs = බොස්නියානු
language-name-bug = බුගිනීස්
language-name-byn = බ්ලින්
language-name-ca = කැටලන්
language-name-ce = චෙච්නියානු
language-name-ceb = සෙබුඅනො
language-name-cgg = චිගා
language-name-ch = චමොරො
language-name-chk = චූකීස්
language-name-chm = මරි
language-name-cho = චොක්ටොව්
language-name-chr = චෙරොකී
language-name-chy = චෙයෙන්නෙ
language-name-ckb = සොරානි කුර්දිෂ්
language-name-co = කෝසිකානු
language-name-crs = සෙසෙල්ව ක්‍රොල් ෆ්‍රෙන්ච්
language-name-cs = චෙක්
language-name-cu = චර්ච් ස්ලැවික්
language-name-cv = චවේෂ්
language-name-cy = වෙල්ෂ්
language-name-da = ඩැනිශ්
language-name-dak = ඩකොටා
language-name-dar = ඩාර්ග්වා
language-name-dav = ටයිටා
language-name-de = ජර්මන්
language-name-de_AT = ඔස්ට්‍රියානු ජර්මන්
language-name-de_CH = ස්විස් උසස් ජර්මන්
language-name-dgr = ඩොග්‍රිබ්
language-name-dje = සර්මා
language-name-dsb = පහළ සෝබියානු
language-name-dua = ඩුආලා
language-name-dv = ඩිවෙහි
language-name-dyo = ජොල-ෆෝනියි
language-name-dz = ඩිසොන්කා
language-name-dzg = ඩසාගා
language-name-ebu = එම්බු
language-name-ee = ඉව්
language-name-efi = එෆික්
language-name-eka = එකජුක්
language-name-el = ග්‍රීක
language-name-en = ඉංග්‍රීසි
language-name-en_AU = ඕස්ට්‍රේලියානු ඉංග්‍රීසි
language-name-en_CA = කැනේඩියානු ඉංග්‍රීසි
language-name-en_GB = බ්‍රිතාන්‍ය ඉංග්‍රීසි
language-name-en_US = ඇමෙරිකානු ඉංග්‍රීසි
language-name-eo = එස්පැරන්ටෝ
language-name-es = ස්පාඤ්ඤ
language-name-es_419 = ලතින් ඇමරිකානු ස්පාඤ්ඤ
language-name-es_ES = යුරෝපීය ස්පාඤ්ඤ
language-name-es_MX = මෙක්සිකානු ස්පාඤ්ඤ
language-name-et = එස්තෝනියානු
language-name-eu = බාස්ක්
language-name-ewo = එවොන්ඩො
language-name-fa = පර්සියානු
language-name-ff = ෆුලාහ්
language-name-fi = ෆින්ලන්ත
language-name-fil = පිලිපීන
language-name-fj = ෆීජි
language-name-fo = ෆාරෝස්
language-name-fon = ෆොන්
language-name-fr = ප්‍රංශ
language-name-fr_CA = කැනේඩියානු ප්‍රංශ
language-name-fr_CH = ස්විස් ප්‍රංශ
language-name-fur = ෆ්‍රියුලියන්
language-name-fy = බටහිර ෆ්‍රිසියානු
language-name-ga = අයර්ලන්ත
language-name-gaa = ගා
language-name-gag = ගගාස්
language-name-gan = ගැන් චයිනිස්
language-name-gd = ස්කොට්ටිශ් ගෙලික්
language-name-gez = ගීස්
language-name-gil = ගිල්බර්ටීස්
language-name-gl = ගැලීසියානු
language-name-gn = ගුවාරනි
language-name-gor = ගොරොන්ටාලො
language-name-gsw = ස්විස් ජර්මානු
language-name-gu = ගුජරාටි
language-name-guz = ගුසී
language-name-gv = මැන්ක්ස්
language-name-gwi = ග්විචින්
language-name-ha = හෝසා
language-name-hak = හකා චයිනිස්
language-name-haw = හවායි
language-name-he = හීබෲ
language-name-hi = හින්දි
language-name-hil = හිලිගෙනන්
language-name-hmn = මොන්ග්
language-name-hr = කෝඒෂියානු
language-name-hsb = ඉහළ සෝබියානු
language-name-hsn = සියැන් චීන
language-name-ht = හයිටි
language-name-hu = හන්ගේරියානු
language-name-hup = හුපා
language-name-hy = ආර්මේනියානු
language-name-hz = හෙරෙරො
language-name-ia = ඉන්ටලින්ගුආ
language-name-iba = ඉබන්
language-name-ibb = ඉබිබියො
language-name-id = ඉන්දුනීසියානු
language-name-ig = ඉග්බෝ
language-name-ii = සිචුආන් යී
language-name-ilo = ඉලොකො
language-name-inh = ඉන්ගුෂ්
language-name-io = ඉඩො
language-name-is = අයිස්ලන්ත
language-name-it = ඉතාලි
language-name-iu = ඉනුක්ටිටුට්
language-name-ja = ජපන්
language-name-jbo = ලොජ්බන්
language-name-jgo = නොම්බා
language-name-jmc = මැකාමී
language-name-jv = ජාවා
language-name-ka = ජෝර්ජියානු
language-name-kab = කාබිල්
language-name-kac = කචින්
language-name-kaj = ජ්ජු
language-name-kam = කැම්බා
language-name-kbd = කබාර්ඩියන්
language-name-kcg = ට්යප්
language-name-kde = මැකොන්ඩ්
language-name-kea = කබුවෙර්ඩියානු
language-name-kfo = කොරො
language-name-kha = ඛසි
language-name-khq = කොයිරා චිනි
language-name-ki = කිකුයු
language-name-kj = කුයන්යමා
language-name-kk = කසාඛ්
language-name-kkj = කකො
language-name-kl = කලාලිසට්
language-name-kln = කලෙන්ජන්
language-name-km = කමර්
language-name-kmb = කිම්බුන්ඩු
language-name-kn = කණ්ණඩ
language-name-ko = කොරියානු
language-name-koi = කොමි-පර්මියාක්
language-name-kok = කොන්කනි
language-name-kpe = ක්පෙලෙ
language-name-kr = කනුරි
language-name-krc = කරන්චි-බාකර්
language-name-krl = කැරෙලියන්
language-name-kru = කුරුඛ්
language-name-ks = කාෂ්මීර්
language-name-ksb = ශාම්බලා
language-name-ksf = බාෆියා
language-name-ksh = කොලොග්නියන්
language-name-ku = කුර්දි
language-name-kum = කුමික්
language-name-kv = කොමි
language-name-kw = කෝනීසියානු
language-name-ky = කිර්ගිස්
language-name-la = ලතින්
language-name-lad = ලඩිනො
language-name-lag = ලංගි
language-name-lb = ලක්සැම්බර්ග්
language-name-lez = ලෙස්ගියන්
language-name-lg = ගන්ඩා
language-name-li = ලිම්බර්ගිශ්
language-name-lkt = ලකොට
language-name-ln = ලින්ගලා
language-name-lo = ලාඕ
language-name-loz = ලොසි
language-name-lrc = උතුරු ලුරි
language-name-lt = ලිතුවේනියානු
language-name-lu = ලුබා-කටන්ගා
language-name-lua = ලුබ-ලුලුඅ
language-name-lun = ලුන්ඩ
language-name-luo = ලුඔ
language-name-lus = මිසො
language-name-luy = ලුයියා
language-name-lv = ලැට්වියානු
language-name-mad = මදුරීස්
language-name-mag = මඝහි
language-name-mai = මයිතිලි
language-name-mak = මකාසාර්
language-name-mas = මසායි
language-name-mdf = මොක්ශා
language-name-men = මෙන්ඩෙ
language-name-mer = මෙරු
language-name-mfe = මොරිස්යෙම්
language-name-mg = මලගාසි
language-name-mgh = මඛුවා-මීටෝ
language-name-mgo = මෙටා
language-name-mh = මාශලීස්
language-name-mi = මාවොරි
language-name-mic = මික්මැක්
language-name-min = මිනන්ග්කබාවු
language-name-mk = මැසිඩෝනියානු
language-name-ml = මලයාලම්
language-name-mn = මොංගෝලියානු
language-name-mni = මනිපුරි
language-name-moh = මොහොව්ක්
language-name-mos = මොස්සි
language-name-mr = මරාති
language-name-ms = මැලේ
language-name-mt = මොල්ටිස්
language-name-mua = මුන්ඩන්
language-name-mul = බහු භාෂා
language-name-mus = ක්‍රීක්
language-name-mwl = මිරන්ඩීස්
language-name-my = බුරුම
language-name-myv = එර්ස්යා
language-name-mzn = මැසන්ඩරනි
language-name-na = නෞරු
language-name-nan = මින් නන් චයිනිස්
language-name-nap = නියාපොලිටන්
language-name-naq = නාමා
language-name-nb = නෝර්වීජියානු බොක්මල්
language-name-nd = උතුරු එන්ඩිබෙලෙ
language-name-nds = පහළ ජර්මන්
language-name-nds_NL = පහළ සැක්සන්
language-name-ne = නේපාල
language-name-new = නෙවාරි
language-name-ng = න්ඩොන්ගා
language-name-nia = නියාස්
language-name-niu = නියුඑන්
language-name-nl = ලන්දේසි
language-name-nl_BE = ෆ්ලෙමිශ්
language-name-nmg = කුවාසිඔ
language-name-nn = නෝර්වීජියානු නයිනෝර්ස්ක්
language-name-nnh = න්ගියාම්බූන්
language-name-nog = නොගායි
language-name-nqo = එන්‘කෝ
language-name-nr = සෞත් ඩ්බේල්
language-name-nso = නොදර්න් සොතො
language-name-nus = නොයර්
language-name-nv = නවාජො
language-name-ny = න්යන්ජා
language-name-nyn = නයන්කෝලෙ
language-name-oc = ඔසිටාන්
language-name-om = ඔරොමෝ
language-name-or = ඔරියා
language-name-os = ඔසිටෙක්
language-name-pa = පන්ජාබි
language-name-pag = පන්ගසීනන්
language-name-pam = පන්පන්ග
language-name-pap = පපියමෙන්ටො
language-name-pau = පලවුවන්
language-name-pcm = නෛජීරියන් පෙන්ගින්
language-name-pl = පෝලන්ත
language-name-prg = පෘශියන්
language-name-ps = පෂ්ටො
language-name-pt = පෘතුගීසි
language-name-pt_BR = බ්‍රසීල පෘතුගීසි
language-name-pt_PT = යුරෝපීය පෘතුගීසි
language-name-qu = ක්වීචුවා
language-name-quc = කියිචේ
language-name-rap = රපනුයි
language-name-rar = රරොටොන්ගන්
language-name-rm = රොමෑන්ශ්
language-name-rn = රුන්ඩි
language-name-ro = රොමේනියානු
language-name-ro_MD = මොල්ඩවිආනු
language-name-rof = රෝම්බෝ
language-name-root = රූට්
language-name-ru = රුසියානු
language-name-rup = ඇරොමානියානු
language-name-rw = කින්යර්වන්ඩා
language-name-rwk = ර්වා
language-name-sa = සංස්කෘත
language-name-sad = සන්ඩවෙ
language-name-sah = සඛා
language-name-saq = සම්බුරු
language-name-sat = සෑන්ටලි
language-name-sba = න්ගම්බෙ
language-name-sbp = සංගු
language-name-sc = සාර්ඩිනිඅන්
language-name-scn = සිසිලියන්
language-name-sco = ස්කොට්ස්
language-name-sd = සින්ධි
language-name-sdh = දකුණු කුර්දි
language-name-se = උතුරු සාමි
language-name-seh = සෙනා
language-name-ses = කෝයිරාබොරො සෙන්නි
language-name-sg = සන්ග්‍රෝ
language-name-shi = ටචේල්හිට්
language-name-shn = ශාන්
language-name-si = සිංහල
language-name-sk = ස්ලෝවැක්
language-name-sl = ස්ලෝවේනියානු
language-name-sm = සෑමොඅන්
language-name-sma = දකුණු සාමි
language-name-smj = ලුලේ සාමි
language-name-smn = ඉනාරි සාමි
language-name-sms = ස්කොල්ට් සාමි
language-name-sn = ශෝනා
language-name-snk = සොනින්කෙ
language-name-so = සෝමාලි
language-name-sq = ඇල්බේනියානු
language-name-sr = සර්බියානු
language-name-srn = ස්‍රන් ටොන්ගො
language-name-ss = ස්වති
language-name-ssy = සහො
language-name-st = සතර්න් සොතො
language-name-su = සන්ඩනීසියානු
language-name-suk = සුකුමා
language-name-sv = ස්වීඩන්
language-name-sw = ස්වාහිලි
language-name-sw_CD = කොංගෝ ස්වාහිලි
language-name-swb = කොමොරියන්
language-name-syr = ස්‍රයෑක්
language-name-ta = දෙමළ
language-name-te = තෙළිඟු
language-name-tem = ටිම්නෙ
language-name-teo = ටෙසෝ
language-name-tet = ටේටම්
language-name-tg = ටජික්
language-name-th = තායි
language-name-ti = ටිග්‍රින්යා
language-name-tig = ටීග්‍රෙ
language-name-tk = ටර්ක්මෙන්
language-name-tlh = ක්ලින්ගොන්
language-name-tn = ස්වනා
language-name-to = ටොංගා
language-name-tpi = ටොක් පිසින්
language-name-tr = තුර්කි
language-name-trv = ටරොකො
language-name-ts = සොන්ග
language-name-tt = ටාටර්
language-name-tum = ටුම්බුකා
language-name-tvl = ටුවාලු
language-name-twq = ටසවාක්
language-name-ty = ටහිටියන්
language-name-tyv = ටුවිනියන්
language-name-tzm = මධ්‍යම ඇට්ලස් ටමසිට්
language-name-udm = අඩ්මර්ට්
language-name-ug = උයිගර්
language-name-uk = යුක්රේනියානු
language-name-umb = උබුන්ඩු
language-name-und = නොදන්නා භාෂාව
language-name-ur = උර්දු
language-name-uz = උස්බෙක්
language-name-vai = වයි
language-name-ve = වෙන්ඩා
language-name-vi = වියට්නාම්
language-name-vo = වොලපූක්
language-name-vun = වුන්ජෝ
language-name-wa = වෑලූන්
language-name-wae = වොල්සර්
language-name-wal = වොලෙට්ට
language-name-war = වොරෙය්
language-name-wbp = වොපිරි
language-name-wo = වොලොෆ්
language-name-wuu = වූ චයිනිස්
language-name-xal = කල්මික්
language-name-xh = ශෝසා
language-name-xog = සොගා
language-name-yav = යන්ග්බෙන්
language-name-ybb = යෙම්බා
language-name-yi = යිඩිශ්
language-name-yo = යොරූබා
language-name-yue = කැන්ටොනීස්
language-name-zgh = සම්මත මොරොක්කෝ ටමසිග්ත්
language-name-zh = චීන
language-name-zh_Hans = සරල චීන
language-name-zh_Hant = සාම්ප්‍රදායික චීන
language-name-zu = සුලු
language-name-zun = සුනි
language-name-zxx = වාග් විද්‍යා අන්තර්ගතයක් නැත
language-name-zza = සාසා
