language-name-ace = acehnés
language-name-alt = altái meridional
language-name-arp = arapaho
language-name-bas = basa
language-name-bax = bamun
language-name-bho = bhojpuri
language-name-bla = siksika
language-name-bua = buriat
language-name-dum = neerlandés medieval
language-name-enm = inglés medieval
language-name-frm = francés medieval
language-name-gmh = alemán de la alta edad media
language-name-grc = griego antiguo
language-name-gu = gurayatí
language-name-hak = hak
language-name-kbd = kabardiano
language-name-krc = karachay-balkar
language-name-lus = lushai
language-name-mga = irlandés medieval
language-name-nan = nan
language-name-nr = ndebele meridional
language-name-nso = sotho septentrional
language-name-pcm = pcm
language-name-rm = romanche
language-name-rn = kiroundi
language-name-shu = árabe chadiano
language-name-sma = sami meridional
language-name-ss = siswati
language-name-st = sesotho meridional
language-name-sw_CD = swahili del Congo
language-name-syr = siriaco
language-name-tet = tetún
language-name-tn = setchwana
language-name-tyv = tuviniano
language-name-wo = wolof
language-name-wuu = wuu
language-name-xal = kalmyk
