language-name-aa = afar
language-name-ab = abház
language-name-ace = achinéz
language-name-ach = akoli
language-name-ada = adangme
language-name-ady = adyghe
language-name-ae = avesztán
language-name-af = afrikaans
language-name-afh = afrihili
language-name-agq = agem
language-name-ain = ainu
language-name-ak = akan
language-name-akk = akkád
language-name-ale = aleut
language-name-alt = dél-altaji
language-name-am = amhara
language-name-an = aragonéz
language-name-ang = óangol
language-name-anp = angika
language-name-ar = arab
language-name-ar_001 = modern szabányos arab
language-name-arc = arámi
language-name-arn = mapucse
language-name-arp = arapaho
language-name-ars = nedzsdi arab
language-name-arw = aravak
language-name-as = asszámi
language-name-asa = asu
language-name-ast = asztúr
language-name-av = avar
language-name-awa = awádi
language-name-ay = ajmara
language-name-az = azerbajdzsáni
language-name-ba = baskír
language-name-bal = balucsi
language-name-ban = balinéz
language-name-bas = basza
language-name-bax = bamun
language-name-bbj = gomala
language-name-be = belarusz
language-name-bej = bedzsa
language-name-bem = bemba
language-name-bez = bena
language-name-bfd = bafut
language-name-bg = bolgár
language-name-bgn = nyugati beludzs
language-name-bho = bodzspuri
language-name-bi = bislama
language-name-bik = bikol
language-name-bin = bini
language-name-bkm = kom
language-name-bla = siksika
language-name-bm = bambara
language-name-bn = bangla
language-name-bo = tibeti
language-name-br = breton
language-name-bra = braj
language-name-brx = bodo
language-name-bs = bosnyák
language-name-bss = koszi
language-name-bua = burját
language-name-bug = buginéz
language-name-bum = bulu
language-name-byn = blin
language-name-byv = medumba
language-name-ca = katalán
language-name-cad = caddo
language-name-car = karib
language-name-cay = kajuga
language-name-cch = atszam
language-name-ce = csecsen
language-name-ceb = szebuano
language-name-cgg = kiga
language-name-ch = csamoró
language-name-chb = csibcsa
language-name-chg = csagatáj
language-name-chk = csukéz
language-name-chm = mari
language-name-chn = csinuk zsargon
language-name-cho = csoktó
language-name-chp = csipevé
language-name-chr = cseroki
language-name-chy = csejen
language-name-ckb = közép-ázsiai kurd
language-name-co = korzikai
language-name-cop = kopt
language-name-cr = krí
language-name-crh = krími tatár
language-name-crs = szeszelva kreol francia
language-name-cs = cseh
language-name-csb = kasub
language-name-cu = egyházi szláv
language-name-cv = csuvas
language-name-cy = walesi
language-name-da = dán
language-name-dak = dakota
language-name-dar = dargva
language-name-dav = taita
language-name-de = német
language-name-de_AT = osztrák német
language-name-de_CH = svájci felnémet
language-name-del = delavár
language-name-den = szlevi
language-name-dgr = dogrib
language-name-din = dinka
language-name-dje = zarma
language-name-doi = dogri
language-name-dsb = alsó-szorb
language-name-dua = duala
language-name-dum = közép holland
language-name-dv = divehi
language-name-dyo = jola-fonyi
language-name-dyu = diula
language-name-dz = dzsonga
language-name-dzg = dazaga
language-name-ebu = embu
language-name-ee = eve
language-name-efi = efik
language-name-egy = óegyiptomi
language-name-eka = ekadzsuk
language-name-el = görög
language-name-elx = elamit
language-name-en = angol
language-name-en_AU = ausztrál angol
language-name-en_CA = kanadai angol
language-name-en_GB = brit angol
language-name-en_US = amerikai angol
language-name-enm = közép angol
language-name-eo = eszperantó
language-name-es = spanyol
language-name-es_419 = latin-amerikai spanyol
language-name-es_ES = európai spanyol
language-name-et = észt
language-name-eu = baszk
language-name-ewo = evondo
language-name-fa = perzsa
language-name-fan = fang
language-name-fat = fanti
language-name-ff = fulani
language-name-fi = finn
language-name-fil = filippínó
language-name-fj = fidzsi
language-name-fo = feröeri
language-name-fon = fon
language-name-fr = francia
language-name-fr_CA = kanadai francia
language-name-fr_CH = svájci francia
language-name-frc = cajun francia
language-name-frm = közép francia
language-name-fro = ófrancia
language-name-frr = északi fríz
language-name-frs = keleti fríz
language-name-fur = friuli
language-name-fy = nyugati fríz
language-name-ga = ír
language-name-gaa = ga
language-name-gag = gagauz
language-name-gan = gan kínai
language-name-gay = gajo
language-name-gba = gbaja
language-name-gd = skóciai kelta
language-name-gez = geez
language-name-gil = ikiribati
language-name-gl = gallego
language-name-gmh = közép felső német
language-name-gn = guarani
language-name-goh = ófelső német
language-name-gon = gondi
language-name-gor = gorontalo
language-name-got = gót
language-name-grb = grebó
language-name-grc = ógörög
language-name-gsw = svájci német
language-name-gu = gudzsaráti
language-name-guz = guszii
language-name-gv = man-szigeti
language-name-gwi = gvicsin
language-name-ha = hausza
language-name-hai = haida
language-name-hak = hakka kínai
language-name-haw = hawaii
language-name-he = héber
language-name-hi = hindi
language-name-hil = ilokano
language-name-hit = hittite
language-name-hmn = hmong
language-name-ho = hiri motu
language-name-hr = horvát
language-name-hsb = felső-szorb
language-name-hsn = xiang kínai
language-name-ht = haiti kreol
language-name-hu = magyar
language-name-hup = hupa
language-name-hy = örmény
language-name-hz = herero
language-name-ia = interlingva
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indonéz
language-name-ie = interlingue
language-name-ig = igbó
language-name-ii = szecsuán ji
language-name-ik = inupiak
language-name-ilo = ilokó
language-name-inh = ingus
language-name-io = idó
language-name-is = izlandi
language-name-it = olasz
language-name-iu = inuktitut
language-name-ja = japán
language-name-jbo = lojban
language-name-jgo = ngomba
language-name-jmc = machame
language-name-jpr = zsidó-perzsa
language-name-jrb = zsidó-arab
language-name-jv = jávai
language-name-ka = grúz
language-name-kaa = kara-kalpak
language-name-kab = kabije
language-name-kac = kacsin
language-name-kaj = jju
language-name-kam = kamba
language-name-kaw = kawi
language-name-kbd = kabardi
language-name-kbl = kanembu
language-name-kcg = tyap
language-name-kde = makonde
language-name-kea = kabuverdianu
language-name-kfo = koro
language-name-kg = kongo
language-name-kha = kaszi
language-name-kho = kotanéz
language-name-khq = kojra-csíni
language-name-ki = kikuju
language-name-kj = kuanyama
language-name-kk = kazah
language-name-kkj = kakó
language-name-kl = grönlandi
language-name-kln = kalendzsin
language-name-km = khmer
language-name-kmb = kimbundu
language-name-kn = kannada
language-name-ko = koreai
language-name-koi = komi-permják
language-name-kok = konkani
language-name-kos = kosrei
language-name-kpe = kpelle
language-name-kr = kanuri
language-name-krc = karacsáj-balkár
language-name-krl = karelai
language-name-kru = kuruh
language-name-ks = kasmíri
language-name-ksb = sambala
language-name-ksf = bafia
language-name-ksh = kölsch
language-name-ku = kurd
language-name-kum = kumük
language-name-kut = kutenai
language-name-kv = komi
language-name-kw = korni
language-name-ky = kirgiz
language-name-la = latin
language-name-lad = ladino
language-name-lag = langi
language-name-lah = lahnda
language-name-lam = lamba
language-name-lb = luxemburgi
language-name-lez = lezg
language-name-lg = ganda
language-name-li = limburgi
language-name-lkt = lakota
language-name-ln = lingala
language-name-lo = lao
language-name-lol = mongó
language-name-lou = louisianai kreol
language-name-loz = lozi
language-name-lrc = északi luri
language-name-lt = litván
language-name-lu = luba-katanga
language-name-lua = luba-lulua
language-name-lui = luiseno
language-name-lun = lunda
language-name-luo = luo
language-name-lus = lushai
language-name-luy = lujia
language-name-lv = lett
language-name-mad = madurai
language-name-maf = mafa
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = makaszar
language-name-man = mandingó
language-name-mas = masai
language-name-mde = maba
language-name-mdf = moksán
language-name-mdr = mandar
language-name-men = mende
language-name-mer = meru
language-name-mfe = mauritiusi kreol
language-name-mg = malgas
language-name-mga = közép ír
language-name-mgh = makua-metó
language-name-mgo = meta’
language-name-mh = marshalli
language-name-mi = maori
language-name-mic = mikmak
language-name-min = minangkabau
language-name-mk = macedón
language-name-ml = malajálam
language-name-mn = mongol
language-name-mnc = mandzsu
language-name-mni = manipuri
language-name-moh = mohawk
language-name-mos = moszi
language-name-mr = maráthi
language-name-ms = maláj
language-name-mt = máltai
language-name-mua = mundang
language-name-mul = többszörös nyelvek
language-name-mus = krík
language-name-mwl = mirandéz
language-name-mwr = márvári
language-name-my = burmai
language-name-mye = myene
language-name-myv = erzjány
language-name-mzn = mázanderáni
language-name-na = naurui
language-name-nan = min nan kínai
language-name-nap = nápolyi
language-name-naq = nama
language-name-nd = északi ndebele
language-name-nds = alsónémet
language-name-nds_NL = alsószász
language-name-ne = nepáli
language-name-new = nevari
language-name-ng = ndonga
language-name-nia = nias
language-name-niu = niuei
language-name-nl = holland
language-name-nl_BE = flamand
language-name-nmg = ngumba
language-name-nnh = ngiemboon
language-name-no = norvég
language-name-nog = nogaj
language-name-non = óskandináv
language-name-nqo = n’kó
language-name-nr = déli ndebele
language-name-nso = északi szeszotó
language-name-nus = nuer
language-name-nv = navahó
language-name-nwc = klasszikus newari
language-name-ny = nyandzsa
language-name-nym = nyamvézi
language-name-nyn = nyankole
language-name-nyo = nyoró
language-name-nzi = nzima
language-name-oc = okszitán
language-name-oj = ojibva
language-name-om = oromo
language-name-or = odia
language-name-os = oszét
language-name-osa = osage
language-name-ota = ottomán török
language-name-pa = pandzsábi
language-name-pag = pangaszinan
language-name-pal = pahlavi
language-name-pam = pampangan
language-name-pap = papiamento
language-name-pau = palaui
language-name-pcm = nigériai pidgin
language-name-peo = óperzsa
language-name-phn = főniciai
language-name-pi = pali
language-name-pl = lengyel
language-name-pon = pohnpei
language-name-prg = porosz
language-name-pro = óprovánszi
language-name-ps = pastu
language-name-pt = portugál
language-name-pt_BR = brazíliai portugál
language-name-pt_PT = európai portugál
language-name-qu = kecsua
language-name-quc = kicse
language-name-raj = radzsasztáni
language-name-rap = rapanui
language-name-rar = rarotongai
language-name-rm = rétoromán
language-name-rn = kirundi
language-name-ro = román
language-name-ro_MD = moldvai
language-name-rof = rombo
language-name-rom = roma
language-name-root = ősi
language-name-ru = orosz
language-name-rup = aromán
language-name-rw = kinyarvanda
language-name-rwk = rwo
language-name-sa = szanszkrit
language-name-sad = szandave
language-name-sah = szaha
language-name-sam = szamaritánus arámi
language-name-saq = szamburu
language-name-sas = sasak
language-name-sat = szantáli
language-name-sba = ngambay
language-name-sbp = szangu
language-name-sc = szardíniai
language-name-scn = szicíliai
language-name-sco = skót
language-name-sd = szindhi
language-name-sdh = dél-kurd
language-name-se = északi számi
language-name-see = szeneka
language-name-seh = szena
language-name-sel = szölkup
language-name-ses = kojra-szenni
language-name-sg = szangó
language-name-sga = óír
language-name-sh = szerbhorvát
language-name-shi = tachelhit
language-name-shn = san
language-name-shu = csádi arab
language-name-si = szingaléz
language-name-sid = szidamó
language-name-sk = szlovák
language-name-sl = szlovén
language-name-sm = szamoai
language-name-sma = déli számi
language-name-smj = lulei számi
language-name-smn = inari számi
language-name-sms = kolta számi
language-name-sn = sona
language-name-snk = szoninke
language-name-so = szomáli
language-name-sog = sogdien
language-name-sq = albán
language-name-sr = szerb
language-name-srn = szranai tongó
language-name-srr = szerer
language-name-ss = sziszuati
language-name-ssy = szahó
language-name-st = déli szeszotó
language-name-su = szundanéz
language-name-suk = szukuma
language-name-sus = szuszu
language-name-sux = sumér
language-name-sv = svéd
language-name-sw = szuahéli
language-name-sw_CD = kongói szuahéli
language-name-swb = comorei
language-name-syc = klasszikus szír
language-name-syr = szír
language-name-ta = tamil
language-name-te = telugu
language-name-tem = temne
language-name-teo = teszó
language-name-ter = terenó
language-name-tet = tetum
language-name-tg = tadzsik
language-name-th = thai
language-name-ti = tigrinya
language-name-tig = tigré
language-name-tiv = tiv
language-name-tk = türkmén
language-name-tkl = tokelaui
language-name-tl = tagalog
language-name-tlh = klingon
language-name-tli = tlingit
language-name-tmh = tamasek
language-name-tn = szecsuáni
language-name-to = tongai
language-name-tog = nyugati nyasza
language-name-tpi = tok pisin
language-name-tr = török
language-name-trv = tarokó
language-name-ts = conga
language-name-tsi = csimsiáni
language-name-tt = tatár
language-name-tum = tumbuka
language-name-tvl = tuvalu
language-name-tw = twi
language-name-twq = szavák
language-name-ty = tahiti
language-name-tyv = tuvai
language-name-tzm = közép-atlaszi tamazigt
language-name-udm = udmurt
language-name-ug = ujgur
language-name-uga = ugariti
language-name-uk = ukrán
language-name-umb = umbundu
language-name-und = ismeretlen nyelv
language-name-ur = urdu
language-name-uz = üzbég
language-name-vai = vai
language-name-ve = venda
language-name-vi = vietnami
language-name-vo = volapük
language-name-vot = votják
language-name-vun = vunjo
language-name-wa = vallon
language-name-wae = walser
language-name-wal = valamo
language-name-war = varaó
language-name-was = vasó
language-name-wbp = warlpiri
language-name-wo = volof
language-name-wuu = wu kínai
language-name-xal = kalmük
language-name-xh = xhosza
language-name-xog = szoga
language-name-yao = jaó
language-name-yap = japi
language-name-yav = jangben
language-name-ybb = jemba
language-name-yi = jiddis
language-name-yo = joruba
language-name-yue = kantoni
language-name-za = zsuang
language-name-zap = zapoték
language-name-zbl = Bliss jelképrendszer
language-name-zen = zenaga
language-name-zgh = marokkói tamazight
language-name-zh = kínai
language-name-zh_Hans = egyszerűsített kínai
language-name-zh_Hant = hagyományos kínai
language-name-zu = zulu
language-name-zun = zuni
language-name-zxx = nincs nyelvészeti tartalom
language-name-zza = zaza
