language-name-aa = அஃபார்
language-name-ab = அப்காஜியான்
language-name-ace = ஆச்சினீஸ்
language-name-ach = அகோலி
language-name-ada = அதாங்மே
language-name-ady = அதகே
language-name-ae = அவெஸ்தான்
language-name-aeb = துனிசிய அரபு
language-name-af = ஆஃப்ரிகான்ஸ்
language-name-afh = அஃப்ரிஹிலி
language-name-agq = அகெம்
language-name-ain = ஐனு
language-name-ak = அகான்
language-name-akk = அக்கேதியன்
language-name-ale = அலூட்
language-name-alt = தெற்கு அல்தை
language-name-am = அம்ஹாரிக்
language-name-an = ஆர்கோனீஸ்
language-name-ang = பழைய ஆங்கிலம்
language-name-anp = அங்கிகா
language-name-ar = அரபிக்
language-name-ar_001 = நவீன நிலையான அரபிக்
language-name-arc = அராமைக்
language-name-arn = மபுச்சே
language-name-arp = அரபஹோ
language-name-arw = அராவாக்
language-name-as = அஸ்ஸாமீஸ்
language-name-asa = அசு
language-name-ast = அஸ்துரியன்
language-name-av = அவேரிக்
language-name-awa = அவதி
language-name-ay = அய்மரா
language-name-az = அஸர்பைஜானி
language-name-ba = பஷ்கிர்
language-name-bal = பலூச்சி
language-name-ban = பலினீஸ்
language-name-bas = பாஸா
language-name-be = பெலாருஷியன்
language-name-bej = பேஜா
language-name-bem = பெம்பா
language-name-bez = பெனா
language-name-bfq = படகா
language-name-bg = பல்கேரியன்
language-name-bgn = மேற்கு பலோச்சி
language-name-bho = போஜ்பூரி
language-name-bi = பிஸ்லாமா
language-name-bik = பிகோல்
language-name-bin = பினி
language-name-bla = சிக்சிகா
language-name-bm = பம்பாரா
language-name-bn = வங்காளம்
language-name-bo = திபெத்தியன்
language-name-bpy = பிஷ்ணுப்பிரியா
language-name-br = பிரெட்டன்
language-name-bra = ப்ராஜ்
language-name-brx = போடோ
language-name-bs = போஸ்னியன்
language-name-bua = புரியாத்
language-name-bug = புகினீஸ்
language-name-byn = ப்லின்
language-name-ca = கேட்டலான்
language-name-cad = கேடோ
language-name-car = கரீப்
language-name-cch = ஆட்சம்
language-name-ce = செச்சென்
language-name-ceb = செபுவானோ
language-name-cgg = சிகா
language-name-ch = சாமோரோ
language-name-chb = சிப்சா
language-name-chg = ஷகதை
language-name-chk = சூகிசே
language-name-chm = மாரி
language-name-chn = சினூக் ஜார்கான்
language-name-cho = சோக்தௌ
language-name-chp = சிபெவ்யான்
language-name-chr = செரோகீ
language-name-chy = செயேனி
language-name-ckb = மத்திய குர்திஷ்
language-name-co = கார்சிகன்
language-name-cop = காப்டிக்
language-name-cr = க்ரீ
language-name-crh = கிரிமியன் துர்க்கி
language-name-crs = செசெல்வா க்ரெயோல் பிரெஞ்சு
language-name-cs = செக்
language-name-csb = கஷுபியன்
language-name-cu = சர்ச் ஸ்லாவிக்
language-name-cv = சுவாஷ்
language-name-cy = வேல்ஷ்
language-name-da = டேனிஷ்
language-name-dak = டகோடா
language-name-dar = தார்குவா
language-name-dav = டைடா
language-name-de = ஜெர்மன்
language-name-de_AT = ஆஸ்திரிய ஜெர்மன்
language-name-de_CH = ஸ்விஸ் ஹை ஜெர்மன்
language-name-del = டெலாவர்
language-name-den = ஸ்லாவ்
language-name-dgr = டோக்ரிப்
language-name-din = டின்கா
language-name-dje = ஸார்மா
language-name-doi = டோக்ரி
language-name-dsb = லோயர் சோர்பியன்
language-name-dua = டுவாலா
language-name-dum = மிடில் டச்சு
language-name-dv = திவேஹி
language-name-dyo = ஜோலா-ஃபோன்யி
language-name-dyu = ட்யூலா
language-name-dz = பூடானி
language-name-dzg = டசாகா
language-name-ebu = எம்பு
language-name-ee = ஈவ்
language-name-efi = எஃபிக்
language-name-egy = பண்டைய எகிப்தியன்
language-name-eka = ஈகாஜுக்
language-name-el = கிரேக்கம்
language-name-elx = எலமைட்
language-name-en = ஆங்கிலம்
language-name-en_AU = ஆஸ்திரேலிய ஆங்கிலம்
language-name-en_CA = கனடிய ஆங்கிலம்
language-name-en_GB = பிரிட்டிஷ் ஆங்கிலம்
language-name-en_US = அமெரிக்க ஆங்கிலம்
language-name-enm = மிடில் ஆங்கிலம்
language-name-eo = எஸ்பரேன்டோ
language-name-es = ஸ்பானிஷ்
language-name-es_419 = லத்தின் அமெரிக்க ஸ்பானிஷ்
language-name-es_ES = ஐரோப்பிய ஸ்பானிஷ்
language-name-es_MX = மெக்ஸிகன் ஸ்பானிஷ்
language-name-et = எஸ்டோனியன்
language-name-eu = பாஸ்க்
language-name-ewo = எவோன்டோ
language-name-fa = பெர்ஷியன்
language-name-fan = ஃபேங்க்
language-name-fat = ஃபான்டி
language-name-ff = ஃபுலா
language-name-fi = ஃபின்னிஷ்
language-name-fil = ஃபிலிபினோ
language-name-fj = ஃபிஜியன்
language-name-fo = ஃபரோயிஸ்
language-name-fon = ஃபான்
language-name-fr = பிரெஞ்சு
language-name-fr_CA = கனடிய பிரெஞ்சு
language-name-fr_CH = ஸ்விஸ் பிரஞ்சு
language-name-frc = கஜுன் பிரெஞ்சு
language-name-frm = மிடில் பிரெஞ்சு
language-name-fro = பழைய பிரெஞ்சு
language-name-frr = வடக்கு ஃப்ரிஸியான்
language-name-frs = கிழக்கு ஃப்ரிஸியான்
language-name-fur = ஃப்ரியூலியன்
language-name-fy = மேற்கு ஃப்ரிஷியன்
language-name-ga = ஐரிஷ்
language-name-gaa = கா
language-name-gag = காகௌஸ்
language-name-gan = கன் சீனம்
language-name-gay = கயோ
language-name-gba = பயா
language-name-gd = ஸ்காட்ஸ் கேலிக்
language-name-gez = கீஜ்
language-name-gil = கில்பெர்டீஸ்
language-name-gl = காலிஸியன்
language-name-gmh = மிடில் ஹை ஜெர்மன்
language-name-gn = க்வாரனி
language-name-goh = பழைய ஹை ஜெர்மன்
language-name-gon = கோன்டி
language-name-gor = கோரோன்டலோ
language-name-got = கோதிக்
language-name-grb = க்ரேபோ
language-name-grc = பண்டைய கிரேக்கம்
language-name-gsw = ஸ்விஸ் ஜெர்மன்
language-name-gu = குஜராத்தி
language-name-guz = குஸி
language-name-gv = மேங்க்ஸ்
language-name-gwi = குவிசின்
language-name-ha = ஹௌஸா
language-name-hai = ஹைடா
language-name-hak = ஹக்கா சீனம்
language-name-haw = ஹவாயியன்
language-name-he = ஹீப்ரூ
language-name-hi = இந்தி
language-name-hif = ஃபிஜி இந்தி
language-name-hil = ஹிலிகாய்னான்
language-name-hit = ஹிட்டைட்
language-name-hmn = மாங்க்
language-name-ho = ஹிரி மோட்டு
language-name-hr = குரோஷியன்
language-name-hsb = அப்பர் சோர்பியான்
language-name-hsn = சியாங்க் சீனம்
language-name-ht = ஹைத்தியன் க்ரியோலி
language-name-hu = ஹங்கேரியன்
language-name-hup = ஹுபா
language-name-hy = ஆர்மேனியன்
language-name-hz = ஹெரேரோ
language-name-ia = இன்டர்லிங்வா
language-name-iba = இபான்
language-name-ibb = இபிபியோ
language-name-id = இந்தோனேஷியன்
language-name-ie = இன்டர்லிங்
language-name-ig = இக்போ
language-name-ii = சிசுவான் ஈ
language-name-ik = இனுபியாக்
language-name-ilo = இலோகோ
language-name-inh = இங்குஷ்
language-name-io = இடோ
language-name-is = ஐஸ்லேண்டிக்
language-name-it = இத்தாலியன்
language-name-iu = இனுகிடூட்
language-name-ja = ஜப்பானியம்
language-name-jbo = லோஜ்பன்
language-name-jgo = நகொம்பா
language-name-jmc = மாசெம்
language-name-jpr = ஜூதேயோ-பெர்ஷியன்
language-name-jrb = ஜூதேயோ-அராபிக்
language-name-jv = ஜாவனீஸ்
language-name-ka = ஜார்ஜியன்
language-name-kaa = காரா-கல்பாக்
language-name-kab = கபாய்ல்
language-name-kac = காசின்
language-name-kaj = ஜ்ஜூ
language-name-kam = கம்பா
language-name-kaw = காவி
language-name-kbd = கபார்டியன்
language-name-kcg = தையாப்
language-name-kde = மகொண்டே
language-name-kea = கபுவெர்தியானு
language-name-kfo = கோரோ
language-name-kg = காங்கோ
language-name-kha = காஸி
language-name-kho = கோதானீஸ்
language-name-khq = கொய்ரா சீனீ
language-name-ki = கிகுயூ
language-name-kj = குவான்யாமா
language-name-kk = கசாக்
language-name-kkj = ககோ
language-name-kl = கலாலிசூட்
language-name-kln = கலின்ஜின்
language-name-km = கெமெர்
language-name-kmb = கிம்புன்து
language-name-kn = கன்னடம்
language-name-ko = கொரியன்
language-name-koi = கொமி-பெர்ம்யாக்
language-name-kok = கொங்கணி
language-name-kos = கோஸ்ரைன்
language-name-kpe = க்பெல்லே
language-name-kr = கனுரி
language-name-krc = கராசே-பல்கார்
language-name-krl = கரேலியன்
language-name-kru = குருக்
language-name-ks = காஷ்மிரி
language-name-ksb = ஷம்பாலா
language-name-ksf = பாஃபியா
language-name-ksh = கொலோக்னியன்
language-name-ku = குர்திஷ்
language-name-kum = கும்இக்
language-name-kut = குடேனை
language-name-kv = கொமி
language-name-kw = கார்னிஷ்
language-name-ky = கிர்கிஸ்
language-name-la = லத்தின்
language-name-lad = லடினோ
language-name-lag = லங்கி
language-name-lah = லஹன்டா
language-name-lam = லம்பா
language-name-lb = லக்ஸம்போர்கிஷ்
language-name-lez = லெஜ்ஜியன்
language-name-lg = கான்டா
language-name-li = லிம்பர்கிஷ்
language-name-lkt = லகோடா
language-name-ln = லிங்காலா
language-name-lo = லாவோ
language-name-lol = மோங்கோ
language-name-lou = லூசியானா க்ரயோல்
language-name-loz = லோசி
language-name-lrc = வடக்கு லுரி
language-name-lt = லிதுவேனியன்
language-name-lu = லுபா-கடாங்கா
language-name-lua = லுபா-லுலுலா
language-name-lui = லுய்சேனோ
language-name-lun = லூன்டா
language-name-luo = லுயோ
language-name-lus = மிஸோ
language-name-luy = லுயியா
language-name-lv = லாட்வியன்
language-name-mad = மதுரீஸ்
language-name-mag = மகாஹி
language-name-mai = மைதிலி
language-name-mak = மகாசார்
language-name-man = மான்டிங்கோ
language-name-mas = மாசாய்
language-name-mdf = மோக்க்ஷா
language-name-mdr = மான்டார்
language-name-men = மென்டீ
language-name-mer = மெரு
language-name-mfe = மொரிசியன்
language-name-mg = மலகாஸி
language-name-mga = மிடில் ஐரிஷ்
language-name-mgh = மகுவா-மீட்டோ
language-name-mgo = மேடா
language-name-mh = மார்ஷெலீஸ்
language-name-mi = மௌரி
language-name-mic = மிக்மாக்
language-name-min = மின்னாங்கபௌ
language-name-mk = மாஸிடோனியன்
language-name-ml = மலையாளம்
language-name-mn = மங்கோலியன்
language-name-mnc = மன்சூ
language-name-mni = மணிப்புரி
language-name-moh = மொஹாக்
language-name-mos = மோஸ்ஸி
language-name-mr = மராத்தி
language-name-ms = மலாய்
language-name-mt = மால்டிஸ்
language-name-mua = முன்டாங்
language-name-mul = பல மொழிகள்
language-name-mus = க்ரீக்
language-name-mwl = மிரான்டீஸ்
language-name-mwr = மார்வாரி
language-name-my = பர்மீஸ்
language-name-myv = ஏர்ஜியா
language-name-mzn = மசந்தேரனி
language-name-na = நவ்ரூ
language-name-nan = மின் நான் சீனம்
language-name-nap = நியோபோலிடன்
language-name-naq = நாமா
language-name-nb = நார்வேஜியன் பொக்மால்
language-name-nd = வடக்கு தெபெலே
language-name-nds = லோ ஜெர்மன்
language-name-nds_NL = லோ சாக்ஸன்
language-name-ne = நேபாளி
language-name-new = நெவாரி
language-name-ng = தோங்கா
language-name-nia = நியாஸ்
language-name-niu = நியூவான்
language-name-nl = டச்சு
language-name-nl_BE = ஃப்லெமிஷ்
language-name-nmg = க்வாசியோ
language-name-nn = நார்வேஜியன் நியூநார்ஸ்க்
language-name-nnh = நெகெய்ம்பூன்
language-name-no = நார்வேஜியன்
language-name-nog = நோகை
language-name-non = பழைய நோர்ஸ்
language-name-nqo = என்‘கோ
language-name-nr = தெற்கு தெபெலே
language-name-nso = வடக்கு சோதோ
language-name-nus = நியூர்
language-name-nv = நவாஜோ
language-name-nwc = பாரம்பரிய நேவாரி
language-name-ny = நயன்ஜா
language-name-nym = நியாம்வேஜி
language-name-nyn = நியான்கோலே
language-name-nyo = நியோரோ
language-name-nzi = நிஜ்மா
language-name-oc = ஒக்கிடன்
language-name-oj = ஒஜிப்வா
language-name-om = ஒரோமோ
language-name-or = ஒடியா
language-name-os = ஒசெட்டிக்
language-name-osa = ஓசேஜ்
language-name-ota = ஓட்டோமான் துருக்கிஷ்
language-name-pa = பஞ்சாபி
language-name-pag = பன்காசினன்
language-name-pal = பாஹ்லவி
language-name-pam = பம்பாங்கா
language-name-pap = பபியாமென்டோ
language-name-pau = பலௌவன்
language-name-pcm = நைஜீரியன் பிட்கின்
language-name-pdc = பென்சில்வேனிய ஜெர்மன்
language-name-peo = பழைய பெர்ஷியன்
language-name-phn = ஃபொனிஷியன்
language-name-pi = பாலி
language-name-pl = போலிஷ்
language-name-pon = ஃபோன்பெயென்
language-name-prg = பிரஷ்யன்
language-name-pro = பழைய ப்ரோவென்சால்
language-name-ps = பஷ்தோ
language-name-pt = போர்ச்சுக்கீஸ்
language-name-pt_BR = பிரேசிலிய போர்ச்சுகீஸ்
language-name-pt_PT = ஐரோப்பிய போர்ச்சுகீஸ்
language-name-qu = க்வெச்சுவா
language-name-quc = கீசீ
language-name-raj = ராஜஸ்தானி
language-name-rap = ரபனுய்
language-name-rar = ரரோடோங்கன்
language-name-rm = ரோமான்ஷ்
language-name-rn = ருண்டி
language-name-ro = ரோமேனியன்
language-name-ro_MD = மோல்டாவியன்
language-name-rof = ரோம்போ
language-name-rom = ரோமானி
language-name-root = ரூட்
language-name-ru = ரஷியன்
language-name-rup = அரோமானியன்
language-name-rw = கின்யாருவான்டா
language-name-rwk = ருவா
language-name-sa = சமஸ்கிருதம்
language-name-sad = சான்டாவே
language-name-sah = சகா
language-name-sam = சமாரிடன் அராமைக்
language-name-saq = சம்புரு
language-name-sas = சாசாக்
language-name-sat = சான்டாலி
language-name-saz = சௌராஷ்டிரம்
language-name-sba = நெகாம்பே
language-name-sbp = சங்கு
language-name-sc = சார்தீனியன்
language-name-scn = சிசிலியன்
language-name-sco = ஸ்காட்ஸ்
language-name-sd = சிந்தி
language-name-sdh = தெற்கு குர்திஷ்
language-name-se = வடக்கு சமி
language-name-seh = செனா
language-name-sel = செல்குப்
language-name-ses = கொய்ராபோரோ சென்னி
language-name-sg = சாங்கோ
language-name-sga = பழைய ஐரிஷ்
language-name-sh = செர்போ-குரோஷியன்
language-name-shi = தசேஹித்
language-name-shn = ஷான்
language-name-si = சிங்களம்
language-name-sid = சிடாமோ
language-name-sk = ஸ்லோவாக்
language-name-sl = ஸ்லோவேனியன்
language-name-sm = சமோவான்
language-name-sma = தெற்கு சமி
language-name-smj = லுலே சமி
language-name-smn = இனாரி சமி
language-name-sms = ஸ்கோல்ட் சமி
language-name-sn = ஷோனா
language-name-snk = சோனின்கே
language-name-so = சோமாலி
language-name-sog = சோக்தியன்
language-name-sq = அல்பேனியன்
language-name-sr = செர்பியன்
language-name-srn = ஸ்ரானன் டோங்கோ
language-name-srr = செரெர்
language-name-ss = ஸ்வாடீ
language-name-ssy = சஹோ
language-name-st = தெற்கு ஸோதோ
language-name-su = சுண்டானீஸ்
language-name-suk = சுகுமா
language-name-sus = சுசு
language-name-sux = சுமேரியன்
language-name-sv = ஸ்வீடிஷ்
language-name-sw = ஸ்வாஹிலி
language-name-sw_CD = காங்கோ ஸ்வாஹிலி
language-name-swb = கொமோரியன்
language-name-syc = பாரம்பரிய சிரியாக்
language-name-syr = சிரியாக்
language-name-ta = தமிழ்
language-name-te = தெலுங்கு
language-name-tem = டிம்னே
language-name-teo = டெசோ
language-name-ter = டெரெனோ
language-name-tet = டெடும்
language-name-tg = தஜிக்
language-name-th = தாய்
language-name-ti = டிக்ரின்யா
language-name-tig = டைக்ரே
language-name-tiv = டிவ்
language-name-tk = துருக்மென்
language-name-tkl = டோகேலௌ
language-name-tl = டாகாலோக்
language-name-tlh = க்ளிங்கோன்
language-name-tli = லிங்கிட்
language-name-tmh = தமஷேக்
language-name-tn = ஸ்வானா
language-name-to = டோங்கான்
language-name-tog = நயாசா டோங்கா
language-name-tpi = டோக் பிஸின்
language-name-tr = துருக்கிஷ்
language-name-trv = தரோகோ
language-name-ts = ஸோங்கா
language-name-tsi = ட்ஸிம்ஷியன்
language-name-tt = டாடர்
language-name-tum = தும்புகா
language-name-tvl = டுவாலு
language-name-tw = ட்வி
language-name-twq = டசவாக்
language-name-ty = தஹிதியன்
language-name-tyv = டுவினியன்
language-name-tzm = மத்திய அட்லஸ் டமசைட்
language-name-udm = உட்முர்ட்
language-name-ug = உய்குர்
language-name-uga = உகாரிடிக்
language-name-uk = உக்ரைனியன்
language-name-umb = அம்பொண்டு
language-name-und = அறியப்படாத மொழி
language-name-ur = உருது
language-name-uz = உஸ்பெக்
language-name-vai = வை
language-name-ve = வென்டா
language-name-vi = வியட்நாமீஸ்
language-name-vo = ஒலாபூக்
language-name-vot = வோட்க்
language-name-vun = வுன்ஜோ
language-name-wa = ஒவாலூன்
language-name-wae = வால்சேர்
language-name-wal = வோலாய்ட்டா
language-name-war = வாரே
language-name-was = வாஷோ
language-name-wbp = வல்பிரி
language-name-wo = ஓலோஃப்
language-name-wuu = வூ சீனம்
language-name-xal = கல்மிக்
language-name-xh = ஹோசா
language-name-xog = சோகா
language-name-yao = யாவ்
language-name-yap = யாபேசே
language-name-yav = யாங்பென்
language-name-ybb = யெம்பா
language-name-yi = யெட்டிஷ்
language-name-yo = யோருபா
language-name-yue = காண்டோனீஸ்
language-name-za = ஜுவாங்
language-name-zap = ஜாபோடெக்
language-name-zbl = ப்லிஸ்ஸிம்பால்ஸ்
language-name-zen = ஜெனகா
language-name-zgh = ஸ்டாண்டர்ட் மொராக்கன் தமாசைட்
language-name-zh = சீனம்
language-name-zh_Hans = எளிதாக்கப்பட்ட சீனம்
language-name-zh_Hant = பாரம்பரிய சீனம்
language-name-zu = ஜுலு
language-name-zun = ஜூனி
language-name-zxx = மொழி உள்ளடக்கம் ஏதுமில்லை
language-name-zza = ஜாஜா
