language-name-ak = Akangowab
language-name-am = Amharicgowab
language-name-ar = Arabiǁî gowab
language-name-be = Belarusanǁî gowab
language-name-bg = Bulgariaǁî gowab
language-name-bn = Bengaliǁî gowab
language-name-cs = Czechǁî gowab
language-name-de = Duits
language-name-el = Xriks
language-name-en = Engels
language-name-es = Spaans
language-name-fa = Persiaǁî gowab
language-name-fr = Frans
language-name-ha = Hausagowab
language-name-hi = Hindigowab
language-name-hu = Hungariaǁî gowab
language-name-id = Indonesiaǁî gowab
language-name-ig = Igbogowab
language-name-it = Italians
language-name-ja = Japanees
language-name-jv = Javanese
language-name-km = Khmerǁî gowab, Central
language-name-ko = Koreaǁî gowab
language-name-ms = Malayǁî gowab
language-name-my = Burmesǁî gowab
language-name-naq = Khoekhoegowab
language-name-ne = Nepalǁî gowab
language-name-nl = Hollands
language-name-pa = Punjabigowab
language-name-pl = Poleǁî gowab
language-name-pt = Portugees
language-name-ro = Romaniaǁî gowab
language-name-ru = Russiaǁî gowab
language-name-rw = Rwandaǁî gowab
language-name-so = Somaliǁî gowab
language-name-sv = Swedeǁî gowab
language-name-ta = Tamilǁî gowab
language-name-th = Thaiǁî gowab
language-name-tr = Turkeǁî gowab
language-name-uk = Ukrainiaǁî gowab
language-name-ur = Urduǁî gowab
language-name-vi = Vietnamǁî gowab
language-name-yo = Yorubab
language-name-zh = Chineesǁî gowab, Mandarinni
language-name-zu = Zulub
