language-name-ak = Kiɛl akan
language-name-am = Kiɛl amaria
language-name-ar = Kiɛl b’árabe
language-name-be = Kiɛl belarussie
language-name-bg = Kiɛl bulgaria
language-name-bn = Kiɛl bengalia
language-name-cs = Kiɛl bó tchɛk
language-name-de = Jáman
language-name-el = Kiɛl bó grɛk
language-name-en = Ngɛ̄lɛ̄n
language-name-es = Paŋá
language-name-fa = Kiɛl pɛrsia
language-name-fr = Fala
language-name-ha = Kiɛl máwúsá
language-name-hi = Kiɛl b’indien
language-name-hu = Kiɛl b’ɔ́ngrois
language-name-id = Kiɛl indonesie
language-name-ig = Kiɛl ikbo
language-name-it = Kiɛl italia
language-name-ja = Kiɛl bó japonɛ̌
language-name-jv = Kiɛl bó javanɛ̌
language-name-km = Kiɛl bó mɛr
language-name-ko = Kiɛl koré
language-name-ms = Kiɛl Malɛ̌siā
language-name-my = Kiɛl birmania
language-name-ne = Kiɛl nepal
language-name-nl = Kiɛl bóllandais
language-name-pa = Kiɛl pɛndjabi
language-name-pl = Kiɛl pɔlɔŋe
language-name-pt = Kiɛl bó pɔ̄rtugɛ̂
language-name-ro = Kiɛl bó rumɛ̂n
language-name-ru = Kiɛl russia
language-name-rw = Kiɛl rwandā
language-name-so = Kiɛl somaliā
language-name-sv = Kiɛl bó suedois
language-name-ta = Kiɛl tamul
language-name-th = Kiɛl thaï
language-name-tr = Kiɛl bó turk
language-name-uk = Kiɛl b’ukrɛ̄nien
language-name-ur = Kiɛl úrdu
language-name-vi = Kiɛl viɛtnam
language-name-yo = Yorúbâ
language-name-zh = Kiɛl bó chinois
language-name-zu = Zulu
