language-name-aa = അഫാർ
language-name-ab = അബ്‌ഖാസിയൻ
language-name-ace = അചിനീസ്
language-name-ach = അകോലി
language-name-ada = അഡാങ്‌മി
language-name-ady = അഡൈഗേ
language-name-ae = അവസ്റ്റാൻ
language-name-af = ആഫ്രിക്കാൻസ്
language-name-afh = ആഫ്രിഹിലി
language-name-agq = ആഘേം
language-name-ain = ഐനു
language-name-ak = അകാൻ‌
language-name-akk = അക്കാഡിയൻ
language-name-ale = അലൂട്ട്
language-name-alt = തെക്കൻ അൾത്തായി
language-name-am = അംഹാരിക്
language-name-an = അരഗോണീസ്
language-name-ang = പഴയ ഇംഗ്ലീഷ്
language-name-anp = ആൻഗിക
language-name-ar = അറബിക്
language-name-ar_001 = ആധുനിക സ്റ്റാൻഡേർഡ് അറബിക്
language-name-arc = അരമായ
language-name-arn = മാപുചി
language-name-arp = അറാപഹോ
language-name-arw = അറാവക്
language-name-as = ആസ്സാമീസ്
language-name-asa = ആസു
language-name-ast = ഓസ്‌ട്രിയൻ
language-name-av = അവാരിക്
language-name-awa = അവാധി
language-name-ay = അയ്മാറ
language-name-az = അസർബൈജാനി
language-name-ba = ബഷ്ഖിർ
language-name-bal = ബലൂചി
language-name-ban = ബാലിനീസ്
language-name-bas = ബസ
language-name-bax = ബാമുൻ
language-name-bbj = ഘോമാല
language-name-be = ബെലാറുഷ്യൻ
language-name-bej = ബേജ
language-name-bem = ബേംബ
language-name-bez = ബെനാ
language-name-bfd = ബാഫട്ട്
language-name-bg = ബൾഗേറിയൻ
language-name-bgn = പശ്ചിമ ബലൂചി
language-name-bho = ഭോജ്‌പുരി
language-name-bi = ബിസ്‌ലാമ
language-name-bik = ബികോൽ
language-name-bin = ബിനി
language-name-bkm = കോം
language-name-bla = സിക്സിക
language-name-bm = ബംബാറ
language-name-bn = ബംഗാളി
language-name-bo = ടിബറ്റൻ
language-name-br = ബ്രെട്ടൺ
language-name-bra = ബ്രജ്
language-name-brx = ബോഡോ
language-name-bs = ബോസ്നിയൻ
language-name-bss = അക്കൂസ്
language-name-bua = ബുറിയത്ത്
language-name-bug = ബുഗിനീസ്
language-name-bum = ബുളു
language-name-byn = ബ്ലിൻ
language-name-byv = മെഡുംബ
language-name-ca = കറ്റാലാൻ
language-name-cad = കാഡോ
language-name-car = കാരിബ്
language-name-cay = കയൂഗ
language-name-cch = അറ്റ്സാം
language-name-ce = ചെചൻ
language-name-ceb = സെബുവാനോ
language-name-cgg = ചിഗ
language-name-ch = ചമോറോ
language-name-chb = ചിബ്ച
language-name-chg = ഷാഗതായ്
language-name-chk = ചൂകീസ്
language-name-chm = മാരി
language-name-chn = ചിനൂഗ് ജാർഗൺ
language-name-cho = ചോക്റ്റാവ്
language-name-chp = ചിപേവ്യൻ
language-name-chr = ഷെരോക്കി
language-name-chy = ഷായാൻ
language-name-ckb = സെൻട്രൽ കുർദിഷ്
language-name-co = കോർസിക്കൻ
language-name-cop = കോപ്റ്റിക്
language-name-cr = ക്രീ
language-name-crh = ക്രിമിയൻ ടർക്കിഷ്
language-name-crs = സെഷൽവ ക്രിയോൾ ഫ്രഞ്ച്
language-name-cs = ചെക്ക്
language-name-csb = കാഷുബിയാൻ
language-name-cu = ചർച്ച് സ്ലാവിക്
language-name-cv = ചുവാഷ്
language-name-cy = വെൽഷ്
language-name-da = ഡാനിഷ്
language-name-dak = ഡകോട്ട
language-name-dar = ഡർഗ്വാ
language-name-dav = തൈത
language-name-de = ജർമ്മൻ
language-name-de_AT = ഓസ്‌ട്രിയൻ ജർമൻ
language-name-de_CH = സ്വിസ് ഹൈ ജർമൻ
language-name-del = ദെലവേർ
language-name-den = സ്ലേവ്
language-name-dgr = ഡോഗ്രിബ്
language-name-din = ദിൻക
language-name-dje = സാർമ്മ
language-name-doi = ഡോഗ്രി
language-name-dsb = ലോവർ സോർബിയൻ
language-name-dua = ദ്വാല
language-name-dum = മദ്ധ്യ ഡച്ച്
language-name-dv = ദിവെഹി
language-name-dyo = യോല-ഫോന്യി
language-name-dyu = ദ്വൈല
language-name-dz = സോങ്ക
language-name-dzg = ഡാസാഗ
language-name-ebu = എംബു
language-name-ee = യൂവ്
language-name-efi = എഫിക്
language-name-egy = പ്രാചീന ഈജിപ്ഷ്യൻ
language-name-eka = എകാജുക്
language-name-el = ഗ്രീക്ക്
language-name-elx = എലാമൈറ്റ്
language-name-en = ഇംഗ്ലീഷ്
language-name-en_AU = ഓസ്‌ട്രേലിയൻ ഇംഗ്ലീഷ്
language-name-en_CA = കനേഡിയൻ ഇംഗ്ലീഷ്
language-name-en_GB = ബ്രിട്ടീഷ് ഇംഗ്ലീഷ്
language-name-en_US = അമേരിക്കൻ ഇംഗ്ലീഷ്
language-name-enm = മദ്ധ്യ ഇംഗ്ലീഷ്
language-name-eo = എസ്‌പരാന്റോ
language-name-es = സ്‌പാനിഷ്
language-name-es_419 = ലാറ്റിൻ അമേരിക്കൻ സ്‌പാനിഷ്
language-name-es_ES = യൂറോപ്യൻ സ്‌പാനിഷ്
language-name-es_MX = മെക്സിക്കൻ സ്പാനിഷ്
language-name-et = എസ്റ്റോണിയൻ
language-name-eu = ബാസ്‌ക്
language-name-ewo = എവോൻഡോ
language-name-fa = പേർഷ്യൻ
language-name-fan = ഫങ്
language-name-fat = ഫാന്റി
language-name-ff = ഫുല
language-name-fi = ഫിന്നിഷ്
language-name-fil = ഫിലിപ്പിനോ
language-name-fj = ഫിജിയൻ
language-name-fo = ഫാറോസ്
language-name-fon = ഫോൻ
language-name-fr = ഫ്രഞ്ച്
language-name-fr_CA = കനേഡിയൻ ഫ്രഞ്ച്
language-name-fr_CH = സ്വിസ് ഫ്രഞ്ച്
language-name-frc = കേജൺ ഫ്രഞ്ച്
language-name-frm = മദ്ധ്യ ഫ്രഞ്ച്
language-name-fro = പഴയ ഫ്രഞ്ച്
language-name-frr = നോർത്തേൻ ഫ്രിഷ്യൻ
language-name-frs = ഈസ്റ്റേൺ ഫ്രിഷ്യൻ
language-name-fur = ഫ്രിയുലിയാൻ
language-name-fy = പശ്ചിമ ഫ്രിഷിയൻ
language-name-ga = ഐറിഷ്
language-name-gaa = ഗാ
language-name-gag = ഗാഗൂസ്
language-name-gan = ഗാൻ ചൈനീസ്
language-name-gay = ഗയൊ
language-name-gba = ഗബ്യ
language-name-gd = സ്കോട്ടിഷ് ഗൈലിക്
language-name-gez = ഗീസ്
language-name-gil = ഗിൽബർട്ടീസ്
language-name-gl = ഗലീഷ്യൻ
language-name-gmh = മദ്ധ്യ ഉച്ച ജർമൻ
language-name-gn = ഗ്വരനീ
language-name-goh = ഓൾഡ് ഹൈ ജർമൻ
language-name-gon = ഗോണ്ഡി
language-name-gor = ഗൊറോന്റാലോ
language-name-got = ഗോഥിക്ക്
language-name-grb = ഗ്രബൊ
language-name-grc = പുരാതന ഗ്രീക്ക്
language-name-gsw = സ്വിസ് ജർമ്മൻ
language-name-gu = ഗുജറാത്തി
language-name-guz = ഗുസീ
language-name-gv = മാൻസ്
language-name-gwi = ഗ്വിച്ചിൻ
language-name-ha = ഹൗസ
language-name-hai = ഹൈഡ
language-name-hak = ഹാക്ക ചൈനീസ്
language-name-haw = ഹവായിയൻ
language-name-he = ഹീബ്രു
language-name-hi = ഹിന്ദി
language-name-hil = ഹിലിഗയ്നോൺ
language-name-hit = ഹിറ്റൈറ്റ്
language-name-hmn = മോങ്
language-name-ho = ഹിരി മോതു
language-name-hr = ക്രൊയേഷ്യൻ
language-name-hsb = അപ്പർ സോർബിയൻ
language-name-hsn = ഷ്യാങ് ചൈനീസ്
language-name-ht = ഹെയ്‌തിയൻ ക്രിയോൾ
language-name-hu = ഹംഗേറിയൻ
language-name-hup = ഹൂപ
language-name-hy = അർമേനിയൻ
language-name-hz = ഹെരേരൊ
language-name-ia = ഇന്റർലിംഗ്വ
language-name-iba = ഇബാൻ
language-name-ibb = ഇബീബിയോ
language-name-id = ഇന്തോനേഷ്യൻ
language-name-ie = ഇന്റർലിംഗ്വേ
language-name-ig = ഇഗ്ബോ
language-name-ii = ഷുവാൻയി
language-name-ik = ഇനുപിയാക്
language-name-ilo = ഇലോകോ
language-name-inh = ഇംഗ്വിഷ്
language-name-io = ഇഡോ
language-name-is = ഐസ്‌ലാൻഡിക്
language-name-it = ഇറ്റാലിയൻ
language-name-iu = ഇനുക്റ്റിറ്റട്ട്
language-name-ja = ജാപ്പനീസ്
language-name-jbo = ലോജ്ബാൻ
language-name-jgo = ഗോമ്പ
language-name-jmc = മചേം
language-name-jpr = ജൂഡിയോ-പേർഷ്യൻ
language-name-jrb = ജൂഡിയോ-അറബിക്
language-name-jv = ജാവാനീസ്
language-name-ka = ജോർജിയൻ
language-name-kaa = കര-കാൽപ്പക്
language-name-kab = കബൈൽ
language-name-kac = കാചിൻ
language-name-kaj = ജ്ജു
language-name-kam = കംബ
language-name-kaw = കാവി
language-name-kbd = കബർഡിയാൻ
language-name-kbl = കനെംബു
language-name-kcg = ട്യാപ്
language-name-kde = മക്കോണ്ടെ
language-name-kea = കബുവെർദിയാനു
language-name-kfo = കോറോ
language-name-kg = കോംഗോ
language-name-kha = ഘാസി
language-name-kho = ഘോറ്റാനേസേ
language-name-khq = കൊയ്റ ചീനി
language-name-ki = കികൂയു
language-name-kj = ക്വാന്യമ
language-name-kk = കസാഖ്
language-name-kkj = കാകോ
language-name-kl = കലാല്ലിസട്ട്
language-name-kln = കലെഞ്ഞിൻ
language-name-km = ഖമെർ
language-name-kmb = കിംബുണ്ടു
language-name-kn = കന്നഡ
language-name-ko = കൊറിയൻ
language-name-koi = കോമി-പെർമ്യാക്ക്
language-name-kok = കൊങ്കണി
language-name-kos = കൊസറേയൻ
language-name-kpe = കപെല്ലേ
language-name-kr = കനൂറി
language-name-krc = കരചൈ-ബാൽകർ
language-name-krl = കരീലിയൻ
language-name-kru = കുരുഖ്
language-name-ks = കാശ്‌മീരി
language-name-ksb = ഷംഭാള
language-name-ksf = ബാഫിയ
language-name-ksh = കൊളോണിയൻ
language-name-ku = കുർദ്ദിഷ്
language-name-kum = കുമൈക്
language-name-kut = കുതേനൈ
language-name-kv = കോമി
language-name-kw = കോർണിഷ്
language-name-ky = കിർഗിസ്
language-name-la = ലാറ്റിൻ
language-name-lad = ലാഡിനോ
language-name-lag = ലാംഗി
language-name-lah = ലഹ്‌ൻഡ
language-name-lam = ലംബ
language-name-lb = ലക്‌സംബർഗിഷ്
language-name-lez = ലഹ്ഗിയാൻ
language-name-lg = ഗാണ്ട
language-name-li = ലിംബർഗിഷ്
language-name-lkt = ലഗോത്ത
language-name-ln = ലിംഗാല
language-name-lo = ലാവോ
language-name-lol = മോങ്കോ
language-name-lou = ലൂസിയാന ക്രിയോൾ
language-name-loz = ലൊസി
language-name-lrc = വടക്കൻ ലൂറി
language-name-lt = ലിത്വാനിയൻ
language-name-lu = ലുബ-കറ്റംഗ
language-name-lua = ലൂബ-ലുലുവ
language-name-lui = ലൂയിസെനോ
language-name-lun = ലുൻഡ
language-name-luo = ലുവോ
language-name-lus = മിസോ
language-name-luy = ലുയിയ
language-name-lv = ലാറ്റ്വിയൻ
language-name-mad = മദുരേസേ
language-name-maf = മാഫ
language-name-mag = മഗാഹി
language-name-mai = മൈഥിലി
language-name-mak = മകാസർ
language-name-man = മണ്ഡിൻഗോ
language-name-mas = മസായ്
language-name-mde = മാബ
language-name-mdf = മോക്ഷ
language-name-mdr = മണ്ഡാർ
language-name-men = മെൻഡെ
language-name-mer = മേരു
language-name-mfe = മൊറിസിൻ
language-name-mg = മലഗാസി
language-name-mga = മദ്ധ്യ ഐറിഷ്
language-name-mgh = മാഖുവാ-മീത്തോ
language-name-mgo = മേത്താ
language-name-mh = മാർഷല്ലീസ്
language-name-mi = മവോറി
language-name-mic = മിക്മാക്
language-name-min = മിനാങ്കബൗ
language-name-mk = മാസിഡോണിയൻ
language-name-ml = മലയാളം
language-name-mn = മംഗോളിയൻ
language-name-mnc = മാൻ‌ചു
language-name-mni = മണിപ്പൂരി
language-name-moh = മോഹാക്
language-name-mos = മൊസ്സി
language-name-mr = മറാത്തി
language-name-ms = മലെയ്
language-name-mt = മാൾട്ടീസ്
language-name-mua = മുന്ദാംഗ്
language-name-mul = പലഭാഷകൾ
language-name-mus = ക്രീക്ക്
language-name-mwl = മിരാൻറസേ
language-name-mwr = മർവാരി
language-name-my = ബർമീസ്
language-name-mye = മയീൻ
language-name-myv = ഏഴ്സ്യ
language-name-mzn = മസന്ററാനി
language-name-na = നൗറു
language-name-nan = മിൻ നാൻ ചൈനീസ്
language-name-nap = നെപ്പോളിറ്റാൻ
language-name-naq = നാമ
language-name-nb = നോർവീജിയൻ ബുക്‌മൽ
language-name-nd = നോർത്ത് ഡെബിൾ
language-name-nds = ലോ ജർമൻ
language-name-nds_NL = ലോ സാക്സൺ
language-name-ne = നേപ്പാളി
language-name-new = നേവാരി
language-name-ng = ഡോങ്ക
language-name-nia = നിയാസ്
language-name-niu = ന്യുവാൻ
language-name-nl = ഡച്ച്
language-name-nl_BE = ഫ്ലമിഷ്
language-name-nmg = ക്വാസിയോ
language-name-nn = നോർവീജിയൻ നൈനോർക്‌സ്
language-name-nnh = ഗീംബൂൺ
language-name-no = നോർവീജിയൻ
language-name-nog = നോഗൈ
language-name-non = പഴയ നോഴ്‌സ്
language-name-nqo = ഇൻകോ
language-name-nr = ദക്ഷിണ നെഡിബിൾ
language-name-nso = നോർത്തേൻ സോതോ
language-name-nus = നുവേർ
language-name-nv = നവാജോ
language-name-nwc = ക്ലാസിക്കൽ നേവാരി
language-name-ny = ന്യൻജ
language-name-nym = ന്യാംവേസി
language-name-nyn = ന്യാൻകോൾ
language-name-nyo = ന്യോറോ
language-name-nzi = സിമ
language-name-oc = ഓക്‌സിറ്റൻ
language-name-oj = ഓജിബ്വാ
language-name-om = ഒറോമോ
language-name-or = ഒഡിയ
language-name-os = ഒസ്സെറ്റിക്
language-name-osa = ഒസേജ്
language-name-ota = ഓട്ടോമൻ തുർക്കിഷ്
language-name-pa = പഞ്ചാബി
language-name-pag = പങ്കാസിനൻ
language-name-pal = പാഹ്ലവി
language-name-pam = പാംപൻഗ
language-name-pap = പാപിയാമെന്റൊ
language-name-pau = പലാവുൻ
language-name-pcm = നൈജീരിയൻ പിഡ്‌ഗിൻ
language-name-peo = പഴയ പേർഷ്യൻ
language-name-phn = ഫീനിഷ്യൻ
language-name-pi = പാലി
language-name-pl = പോളിഷ്
language-name-pon = പൊൻപിയൻ
language-name-prg = പ്രഷ്യൻ
language-name-pro = പഴയ പ്രൊവൻഷ്ൽ
language-name-ps = പഷ്‌തോ
language-name-pt = പോർച്ചുഗീസ്
language-name-pt_BR = ബ്രസീലിയൻ പോർച്ചുഗീസ്
language-name-pt_PT = യൂറോപ്യൻ പോർച്ചുഗീസ്
language-name-qu = ക്വെച്ചുവ
language-name-quc = ക്വിച്ചെ
language-name-raj = രാജസ്ഥാനി
language-name-rap = രാപനൂയി
language-name-rar = രാരോടോങ്കൻ
language-name-rm = റൊമാഞ്ച്
language-name-rn = റുണ്ടി
language-name-ro = റൊമാനിയൻ
language-name-ro_MD = മോൾഡാവിയൻ
language-name-rof = റോംബോ
language-name-rom = റൊമാനി
language-name-root = മൂലഭാഷ
language-name-ru = റഷ്യൻ
language-name-rup = ആരോമാനിയൻ
language-name-rw = കിന്യാർവാണ്ട
language-name-rwk = റുവാ
language-name-sa = സംസ്‌കൃതം
language-name-sad = സാൻഡവേ
language-name-sah = സാഖ
language-name-sam = സമരിയാക്കാരുടെ അരമായ
language-name-saq = സംബുരു
language-name-sas = സസാക്
language-name-sat = സന്താലി
language-name-sba = ഗംബായ്
language-name-sbp = സംഗു
language-name-sc = സർഡിനിയാൻ
language-name-scn = സിസിലിയൻ
language-name-sco = സ്കോട്സ്
language-name-sd = സിന്ധി
language-name-sdh = തെക്കൻ കുർദ്ദിഷ്
language-name-se = വടക്കൻ സമി
language-name-see = സെനേക
language-name-seh = സേന
language-name-sel = സെൽകപ്
language-name-ses = കൊയ്റാബൊറോ സെന്നി
language-name-sg = സാംഗോ
language-name-sga = പഴയ ഐറിഷ്
language-name-sh = സെർബോ-ക്രൊയേഷ്യൻ
language-name-shi = താച്ചലിറ്റ്
language-name-shn = ഷാൻ
language-name-shu = ചാഡിയൻ അറബി
language-name-si = സിംഹള
language-name-sid = സിഡാമോ
language-name-sk = സ്ലോവാക്
language-name-sl = സ്ലോവേനിയൻ
language-name-sm = സമോവൻ
language-name-sma = തെക്കൻ സമി
language-name-smj = ലൂലീ സമി
language-name-smn = ഇനാരി സമി
language-name-sms = സ്കോൾട്ട് സമി
language-name-sn = ഷോണ
language-name-snk = സോണിൻകെ
language-name-so = സോമാലി
language-name-sog = സോജിഡിയൻ
language-name-sq = അൽബേനിയൻ
language-name-sr = സെർബിയൻ
language-name-srn = ശ്രാനൻ ഡോങ്കോ
language-name-srr = സെറർ
language-name-ss = സ്വാറ്റി
language-name-ssy = സാഹോ
language-name-st = തെക്കൻ സോതോ
language-name-su = സുണ്ടാനീസ്
language-name-suk = സുകുമ
language-name-sus = സുസു
language-name-sux = സുമേരിയൻ
language-name-sv = സ്വീഡിഷ്
language-name-sw = സ്വാഹിലി
language-name-sw_CD = കോംഗോ സ്വാഹിലി
language-name-swb = കൊമോറിയൻ
language-name-syc = പുരാതന സുറിയാനിഭാഷ
language-name-syr = സുറിയാനി
language-name-ta = തമിഴ്
language-name-te = തെലുങ്ക്
language-name-tem = ടിംനേ
language-name-teo = ടെസോ
language-name-ter = ടെറേനോ
language-name-tet = ടെറ്റും
language-name-tg = താജിക്
language-name-th = തായ്
language-name-ti = ടൈഗ്രിന്യ
language-name-tig = ടൈഗ്രി
language-name-tiv = ടിവ്
language-name-tk = തുർക്‌മെൻ
language-name-tkl = ടൊക്കേലൗ
language-name-tl = തഗാലോഗ്
language-name-tlh = ക്ലിംഗോൺ
language-name-tli = ലിംഗ്വിറ്റ്
language-name-tmh = ടമഷേക്
language-name-tn = സ്വാന
language-name-to = ടോംഗൻ
language-name-tog = ന്യാസാ ഡോങ്ക
language-name-tpi = ടോക് പിസിൻ
language-name-tr = ടർക്കിഷ്
language-name-trv = തരോക്കോ
language-name-ts = സോംഗ
language-name-tsi = സിംഷ്യൻ
language-name-tt = ടാട്ടർ
language-name-tum = ടുംബുക
language-name-tvl = ടുവാലു
language-name-tw = ട്വി
language-name-twq = ടസവാക്ക്
language-name-ty = താഹിതിയൻ
language-name-tyv = തുവിനിയൻ
language-name-tzm = മധ്യ അറ്റ്‌ലസ് ടമാസൈറ്റ്
language-name-udm = ഉഡ്മുർട്ട്
language-name-ug = ഉയ്ഘുർ
language-name-uga = ഉഗറിട്ടിക്
language-name-uk = ഉക്രേനിയൻ
language-name-umb = ഉംബുന്ദു
language-name-und = അജ്ഞാത ഭാഷ
language-name-ur = ഉറുദു
language-name-uz = ഉസ്‌ബെക്ക്
language-name-vai = വൈ
language-name-ve = വെന്ദ
language-name-vi = വിയറ്റ്നാമീസ്
language-name-vo = വോളാപുക്
language-name-vot = വോട്ടിക്
language-name-vun = വുൻജോ
language-name-wa = വല്ലൂൺ
language-name-wae = വാൾസർ
language-name-wal = വൊലൈറ്റ
language-name-war = വാരേയ്
language-name-was = വാഷൊ
language-name-wbp = വൂൾപിരി
language-name-wo = വൊളോഫ്
language-name-wuu = വു ചൈനീസ്
language-name-xal = കൽമൈക്
language-name-xh = ഖോസ
language-name-xog = സോഗോ
language-name-yao = യാവോ
language-name-yap = യെപ്പീസ്
language-name-yav = യാംഗ്ബെൻ
language-name-ybb = യംബ
language-name-yi = യിദ്ദിഷ്
language-name-yo = യൊറൂബാ
language-name-yue = കാന്റണീസ്
language-name-za = സ്വാംഗ്
language-name-zap = സാപ്പോടെക്
language-name-zbl = ബ്ലിസ്സിംബൽസ്
language-name-zen = സെനഗ
language-name-zgh = സ്റ്റാൻഡേർഡ് മൊറോക്കൻ റ്റാമസിയറ്റ്
language-name-zh = ചൈനീസ്
language-name-zh_Hans = ലളിതമാക്കിയ ചൈനീസ്
language-name-zh_Hant = പരമ്പരാഗത ചൈനീസ്
language-name-zu = സുലു
language-name-zun = സുനി
language-name-zxx = ഭാഷാപരമായ ഉള്ളടക്കമൊന്നുമില്ല
language-name-zza = സാസാ
