language-name-aa = afar
language-name-ab = abchaski
language-name-ace = aceh
language-name-ach = aczoli
language-name-ada = adangme
language-name-ady = adygejski
language-name-ae = awestyjski
language-name-aeb = tunezyjski arabski
language-name-af = afrikaans
language-name-afh = afrihili
language-name-agq = aghem
language-name-ain = ajnu
language-name-ak = akan
language-name-akk = akadyjski
language-name-akz = alabama
language-name-ale = aleucki
language-name-aln = albański gegijski
language-name-alt = południowoałtajski
language-name-am = amharski
language-name-an = aragoński
language-name-ang = staroangielski
language-name-anp = angika
language-name-ar = arabski
language-name-ar_001 = współczesny arabski
language-name-arc = aramejski
language-name-arn = mapudungun
language-name-aro = araona
language-name-arp = arapaho
language-name-arq = algierski arabski
language-name-ars = arabski nadżdyjski
language-name-arw = arawak
language-name-ary = marokański arabski
language-name-arz = egipski arabski
language-name-as = asamski
language-name-asa = asu
language-name-ase = amerykański język migowy
language-name-ast = asturyjski
language-name-av = awarski
language-name-avk = kotava
language-name-awa = awadhi
language-name-ay = ajmara
language-name-az = azerbejdżański
language-name-ba = baszkirski
language-name-bal = beludżi
language-name-ban = balijski
language-name-bar = bawarski
language-name-bas = basaa
language-name-bax = bamum
language-name-bbc = batak toba
language-name-bbj = ghomala
language-name-be = białoruski
language-name-bej = bedża
language-name-bem = bemba
language-name-bew = betawi
language-name-bez = bena
language-name-bfd = bafut
language-name-bfq = badaga
language-name-bg = bułgarski
language-name-bgn = beludżi północny
language-name-bho = bhodźpuri
language-name-bi = bislama
language-name-bik = bikol
language-name-bin = bini
language-name-bjn = banjar
language-name-bkm = kom
language-name-bla = siksika
language-name-bm = bambara
language-name-bn = bengalski
language-name-bo = tybetański
language-name-bpy = bisznuprija-manipuri
language-name-bqi = bachtiarski
language-name-br = bretoński
language-name-bra = bradź
language-name-brh = brahui
language-name-brx = bodo
language-name-bs = bośniacki
language-name-bss = akoose
language-name-bua = buriacki
language-name-bug = bugijski
language-name-bum = bulu
language-name-byn = blin
language-name-byv = medumba
language-name-ca = kataloński
language-name-cad = kaddo
language-name-car = karaibski
language-name-cay = kajuga
language-name-cch = atsam
language-name-ce = czeczeński
language-name-ceb = cebuano
language-name-cgg = chiga
language-name-ch = czamorro
language-name-chb = czibcza
language-name-chg = czagatajski
language-name-chk = chuuk
language-name-chm = maryjski
language-name-chn = żargon czinucki
language-name-cho = czoktawski
language-name-chp = czipewiański
language-name-chr = czirokeski
language-name-chy = czejeński
language-name-ckb = sorani
language-name-co = korsykański
language-name-cop = koptyjski
language-name-cps = capiznon
language-name-cr = kri
language-name-crh = krymskotatarski
language-name-crs = kreolski seszelski
language-name-cs = czeski
language-name-csb = kaszubski
language-name-cu = cerkiewnosłowiański
language-name-cv = czuwaski
language-name-cy = walijski
language-name-da = duński
language-name-dak = dakota
language-name-dar = dargwijski
language-name-dav = taita
language-name-de = niemiecki
language-name-de_AT = austriacki niemiecki
language-name-de_CH = szwajcarski wysokoniemiecki
language-name-del = delaware
language-name-den = slave
language-name-dgr = dogrib
language-name-din = dinka
language-name-dje = dżerma
language-name-doi = dogri
language-name-dsb = dolnołużycki
language-name-dtp = dusun centralny
language-name-dua = duala
language-name-dum = średniowieczny niderlandzki
language-name-dv = malediwski
language-name-dyo = diola
language-name-dyu = diula
language-name-dz = dzongkha
language-name-dzg = dazaga
language-name-ebu = embu
language-name-ee = ewe
language-name-efi = efik
language-name-egl = emilijski
language-name-egy = staroegipski
language-name-eka = ekajuk
language-name-el = grecki
language-name-elx = elamicki
language-name-en = angielski
language-name-en_AU = australijski angielski
language-name-en_CA = kanadyjski angielski
language-name-en_GB = brytyjski angielski
language-name-en_US = amerykański angielski
language-name-enm = średnioangielski
language-name-eo = esperanto
language-name-es = hiszpański
language-name-es_419 = amerykański hiszpański
language-name-es_ES = europejski hiszpański
language-name-es_MX = meksykański hiszpański
language-name-esu = yupik środkowosyberyjski
language-name-et = estoński
language-name-eu = baskijski
language-name-ewo = ewondo
language-name-ext = estremadurski
language-name-fa = perski
language-name-fan = fang
language-name-fat = fanti
language-name-ff = fulani
language-name-fi = fiński
language-name-fil = filipino
language-name-fit = meänkieli
language-name-fj = fidżijski
language-name-fo = farerski
language-name-fon = fon
language-name-fr = francuski
language-name-fr_CA = kanadyjski francuski
language-name-fr_CH = szwajcarski francuski
language-name-frc = cajuński
language-name-frm = średniofrancuski
language-name-fro = starofrancuski
language-name-frp = franko-prowansalski
language-name-frr = północnofryzyjski
language-name-frs = wschodniofryzyjski
language-name-fur = friulski
language-name-fy = zachodniofryzyjski
language-name-ga = irlandzki
language-name-gaa = ga
language-name-gag = gagauski
language-name-gan = gan
language-name-gay = gayo
language-name-gba = gbaya
language-name-gbz = zaratusztriański dari
language-name-gd = szkocki gaelicki
language-name-gez = gyyz
language-name-gil = gilbertański
language-name-gl = galicyjski
language-name-glk = giliański
language-name-gmh = średnio-wysoko-niemiecki
language-name-gn = guarani
language-name-goh = staro-wysoko-niemiecki
language-name-gon = gondi
language-name-gor = gorontalo
language-name-got = gocki
language-name-grb = grebo
language-name-grc = starogrecki
language-name-gsw = szwajcarski niemiecki
language-name-gu = gudżarati
language-name-guc = wayúu
language-name-gur = frafra
language-name-guz = gusii
language-name-gv = manx
language-name-gwi = gwichʼin
language-name-ha = hausa
language-name-hai = haida
language-name-hak = hakka
language-name-haw = hawajski
language-name-he = hebrajski
language-name-hi = hindi
language-name-hif = hindi fidżyjskie
language-name-hil = hiligaynon
language-name-hit = hetycki
language-name-hmn = hmong
language-name-ho = hiri motu
language-name-hr = chorwacki
language-name-hsb = górnołużycki
language-name-hsn = xiang
language-name-ht = kreolski haitański
language-name-hu = węgierski
language-name-hup = hupa
language-name-hy = ormiański
language-name-hz = herero
language-name-ia = interlingua
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indonezyjski
language-name-ie = interlingue
language-name-ig = igbo
language-name-ii = syczuański
language-name-ik = inupiak
language-name-ilo = ilokano
language-name-inh = inguski
language-name-io = ido
language-name-is = islandzki
language-name-it = włoski
language-name-iu = inuktitut
language-name-izh = ingryjski
language-name-ja = japoński
language-name-jam = jamajski
language-name-jbo = lojban
language-name-jgo = ngombe
language-name-jmc = machame
language-name-jpr = judeo-perski
language-name-jrb = judeoarabski
language-name-jut = jutlandzki
language-name-jv = jawajski
language-name-ka = gruziński
language-name-kaa = karakałpacki
language-name-kab = kabylski
language-name-kac = kaczin
language-name-kaj = jju
language-name-kam = kamba
language-name-kaw = kawi
language-name-kbd = kabardyjski
language-name-kbl = kanembu
language-name-kcg = tyap
language-name-kde = makonde
language-name-kea = kreolski Wysp Zielonego Przylądka
language-name-ken = kenyang
language-name-kfo = koro
language-name-kg = kongo
language-name-kgp = kaingang
language-name-kha = khasi
language-name-kho = chotański
language-name-khq = koyra chiini
language-name-khw = khowar
language-name-ki = kikuju
language-name-kiu = kirmandżki
language-name-kj = kwanyama
language-name-kk = kazachski
language-name-kkj = kako
language-name-kl = grenlandzki
language-name-kln = kalenjin
language-name-km = khmerski
language-name-kmb = kimbundu
language-name-kn = kannada
language-name-ko = koreański
language-name-koi = komi-permiacki
language-name-kok = konkani
language-name-kos = kosrae
language-name-kpe = kpelle
language-name-kr = kanuri
language-name-krc = karaczajsko-bałkarski
language-name-kri = krio
language-name-krj = kinaraya
language-name-krl = karelski
language-name-kru = kurukh
language-name-ks = kaszmirski
language-name-ksb = sambala
language-name-ksf = bafia
language-name-ksh = gwara kolońska
language-name-ku = kurdyjski
language-name-kum = kumycki
language-name-kut = kutenai
language-name-kv = komi
language-name-kw = kornijski
language-name-ky = kirgiski
language-name-la = łaciński
language-name-lad = ladyński
language-name-lag = langi
language-name-lah = lahnda
language-name-lam = lamba
language-name-lb = luksemburski
language-name-lez = lezgijski
language-name-lfn = Lingua Franca Nova
language-name-lg = ganda
language-name-li = limburski
language-name-lij = liguryjski
language-name-liv = liwski
language-name-lkt = lakota
language-name-lmo = lombardzki
language-name-ln = lingala
language-name-lo = laotański
language-name-lol = mongo
language-name-lou = kreolski luizjański
language-name-loz = lozi
language-name-lrc = luryjski północny
language-name-lt = litewski
language-name-ltg = łatgalski
language-name-lu = luba-katanga
language-name-lua = luba-lulua
language-name-lui = luiseno
language-name-lun = lunda
language-name-luo = luo
language-name-lus = mizo
language-name-luy = luhya
language-name-lv = łotewski
language-name-lzh = chiński klasyczny
language-name-lzz = lazyjski
language-name-mad = madurajski
language-name-maf = mafa
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = makasar
language-name-man = mandingo
language-name-mas = masajski
language-name-mde = maba
language-name-mdf = moksza
language-name-mdr = mandar
language-name-men = mende
language-name-mer = meru
language-name-mfe = kreolski Mauritiusa
language-name-mg = malgaski
language-name-mga = średnioirlandzki
language-name-mgh = makua
language-name-mgo = meta
language-name-mh = marszalski
language-name-mi = maoryjski
language-name-mic = mikmak
language-name-min = minangkabu
language-name-mk = macedoński
language-name-ml = malajalam
language-name-mn = mongolski
language-name-mnc = manchu
language-name-mni = manipuri
language-name-moh = mohawk
language-name-mos = mossi
language-name-mr = marathi
language-name-mrj = zachodniomaryjski
language-name-ms = malajski
language-name-mt = maltański
language-name-mua = mundang
language-name-mul = wiele języków
language-name-mus = krik
language-name-mwl = mirandyjski
language-name-mwr = marwari
language-name-mwv = mentawai
language-name-my = birmański
language-name-mye = myene
language-name-myv = erzja
language-name-mzn = mazanderański
language-name-na = nauru
language-name-nan = minnański
language-name-nap = neapolitański
language-name-naq = nama
language-name-nd = ndebele północny
language-name-nds = dolnoniemiecki
language-name-nds_NL = dolnosaksoński
language-name-ne = nepalski
language-name-new = newarski
language-name-ng = ndonga
language-name-nia = nias
language-name-niu = niue
language-name-njo = ao
language-name-nl = niderlandzki
language-name-nl_BE = flamandzki
language-name-nmg = ngumba
language-name-nnh = ngiemboon
language-name-no = norweski
language-name-nog = nogajski
language-name-non = staronordyjski
language-name-nov = novial
language-name-nqo = n’ko
language-name-nr = ndebele południowy
language-name-nso = sotho północny
language-name-nus = nuer
language-name-nv = nawaho
language-name-nwc = newarski klasyczny
language-name-ny = njandża
language-name-nym = niamwezi
language-name-nyn = nyankole
language-name-nyo = nyoro
language-name-nzi = nzema
language-name-oc = oksytański
language-name-oj = odżibwa
language-name-om = oromo
language-name-or = orija
language-name-os = osetyjski
language-name-osa = osage
language-name-ota = osmańsko-turecki
language-name-pa = pendżabski
language-name-pag = pangasino
language-name-pal = pahlavi
language-name-pam = pampango
language-name-pap = papiamento
language-name-pau = palau
language-name-pcd = pikardyjski
language-name-pcm = pidżyn nigeryjski
language-name-pdc = pensylwański
language-name-pdt = plautdietsch
language-name-peo = staroperski
language-name-pfl = palatynacki
language-name-phn = fenicki
language-name-pi = palijski
language-name-pl = polski
language-name-pms = piemoncki
language-name-pnt = pontyjski
language-name-pon = ponpejski
language-name-prg = pruski
language-name-pro = staroprowansalski
language-name-ps = paszto
language-name-pt = portugalski
language-name-pt_BR = brazylijski portugalski
language-name-pt_PT = europejski portugalski
language-name-qu = keczua
language-name-quc = kicze
language-name-raj = radźasthani
language-name-rap = rapanui
language-name-rar = rarotonga
language-name-rgn = romagnol
language-name-rif = tarifit
language-name-rm = retoromański
language-name-rn = rundi
language-name-ro = rumuński
language-name-ro_MD = mołdawski
language-name-rof = rombo
language-name-rom = cygański
language-name-root = język rdzenny
language-name-rtm = rotumański
language-name-ru = rosyjski
language-name-rue = rusiński
language-name-rug = roviana
language-name-rup = arumuński
language-name-rw = kinya-ruanda
language-name-rwk = rwa
language-name-sa = sanskryt
language-name-sad = sandawe
language-name-sah = jakucki
language-name-sam = samarytański aramejski
language-name-saq = samburu
language-name-sas = sasak
language-name-sat = santali
language-name-saz = saurasztryjski
language-name-sba = ngambay
language-name-sbp = sangu
language-name-sc = sardyński
language-name-scn = sycylijski
language-name-sco = scots
language-name-sd = sindhi
language-name-sdc = sassarski
language-name-sdh = południowokurdyjski
language-name-se = północnolapoński
language-name-see = seneka
language-name-seh = sena
language-name-sei = seri
language-name-sel = selkupski
language-name-ses = koyraboro senni
language-name-sg = sango
language-name-sga = staroirlandzki
language-name-sgs = żmudzki
language-name-sh = serbsko-chorwacki
language-name-shi = tashelhiyt
language-name-shn = szan
language-name-si = syngaleski
language-name-sid = sidamo
language-name-sk = słowacki
language-name-sl = słoweński
language-name-sli = dolnośląski
language-name-sly = selayar
language-name-sm = samoański
language-name-sma = południowolapoński
language-name-smj = lule
language-name-smn = inari
language-name-sms = skolt
language-name-sn = shona
language-name-snk = soninke
language-name-so = somalijski
language-name-sog = sogdyjski
language-name-sq = albański
language-name-sr = serbski
language-name-srn = sranan tongo
language-name-srr = serer
language-name-ss = suazi
language-name-ssy = saho
language-name-st = sotho południowy
language-name-stq = fryzyjski saterlandzki
language-name-su = sundajski
language-name-suk = sukuma
language-name-sus = susu
language-name-sux = sumeryjski
language-name-sv = szwedzki
language-name-sw = suahili
language-name-sw_CD = kongijski suahili
language-name-swb = komoryjski
language-name-syc = syriacki
language-name-syr = syryjski
language-name-szl = śląski
language-name-ta = tamilski
language-name-tcy = tulu
language-name-te = telugu
language-name-tem = temne
language-name-teo = ateso
language-name-ter = tereno
language-name-tet = tetum
language-name-tg = tadżycki
language-name-th = tajski
language-name-ti = tigrinia
language-name-tig = tigre
language-name-tiv = tiw
language-name-tk = turkmeński
language-name-tkl = tokelau
language-name-tkr = cachurski
language-name-tl = tagalski
language-name-tlh = klingoński
language-name-tli = tlingit
language-name-tly = tałyski
language-name-tmh = tamaszek
language-name-tn = setswana
language-name-to = tonga
language-name-tpi = tok pisin
language-name-tr = turecki
language-name-tru = turoyo
language-name-trv = taroko
language-name-ts = tsonga
language-name-tsd = cakoński
language-name-tsi = tsimshian
language-name-tt = tatarski
language-name-ttt = tacki
language-name-tum = tumbuka
language-name-tvl = tuvalu
language-name-tw = twi
language-name-twq = tasawaq
language-name-ty = tahitański
language-name-tyv = tuwiński
language-name-udm = udmurcki
language-name-ug = ujgurski
language-name-uga = ugarycki
language-name-uk = ukraiński
language-name-umb = umbundu
language-name-und = nieznany język
language-name-ur = urdu
language-name-uz = uzbecki
language-name-vai = wai
language-name-ve = venda
language-name-vec = wenecki
language-name-vep = wepski
language-name-vi = wietnamski
language-name-vls = zachodnioflamandzki
language-name-vmf = meński frankoński
language-name-vo = wolapik
language-name-vot = wotiacki
language-name-vro = võro
language-name-vun = vunjo
language-name-wa = waloński
language-name-wae = walser
language-name-wal = wolayta
language-name-war = waraj
language-name-was = washo
language-name-wbp = warlpiri
language-name-wo = wolof
language-name-wuu = wu
language-name-xal = kałmucki
language-name-xh = khosa
language-name-xmf = megrelski
language-name-xog = soga
language-name-yao = yao
language-name-yap = japski
language-name-yav = yangben
language-name-ybb = yemba
language-name-yi = jidysz
language-name-yo = joruba
language-name-yrl = nheengatu
language-name-yue = kantoński
language-name-za = czuang
language-name-zap = zapotecki
language-name-zbl = bliss
language-name-zea = zelandzki
language-name-zen = zenaga
language-name-zgh = standardowy marokański tamazight
language-name-zh = chiński
language-name-zh_Hans = chiński uproszczony
language-name-zh_Hant = chiński tradycyjny
language-name-zu = zulu
language-name-zun = zuni
language-name-zxx = brak treści o charakterze językowym
language-name-zza = zazaki
