language-name-aa = afar
language-name-ab = abcaso
language-name-ace = accinese
language-name-ach = acioli
language-name-ada = adangme
language-name-ady = adyghe
language-name-ae = avestan
language-name-aeb = arabo tunisino
language-name-af = afrikaans
language-name-afh = afrihili
language-name-agq = aghem
language-name-ain = ainu
language-name-ak = akan
language-name-akk = accado
language-name-akz = alabama
language-name-ale = aleuto
language-name-aln = albanese ghego
language-name-alt = altai meridionale
language-name-am = amarico
language-name-an = aragonese
language-name-ang = inglese antico
language-name-anp = angika
language-name-ar = arabo
language-name-ar_001 = arabo moderno standard
language-name-arc = aramaico
language-name-arn = mapudungun
language-name-aro = araona
language-name-arp = arapaho
language-name-arq = arabo algerino
language-name-ars = arabo, najd
language-name-arw = aruaco
language-name-ary = arabo marocchino
language-name-arz = arabo egiziano
language-name-as = assamese
language-name-asa = asu
language-name-ase = lingua dei segni americana
language-name-ast = asturiano
language-name-av = avaro
language-name-avk = kotava
language-name-awa = awadhi
language-name-ay = aymara
language-name-az = azerbaigiano
language-name-ba = baschiro
language-name-bal = beluci
language-name-ban = balinese
language-name-bar = bavarese
language-name-bas = basa
language-name-bax = bamun
language-name-bbc = batak toba
language-name-bbj = ghomala
language-name-be = bielorusso
language-name-bej = begia
language-name-bem = wemba
language-name-bew = betawi
language-name-bez = bena
language-name-bfd = bafut
language-name-bfq = badaga
language-name-bg = bulgaro
language-name-bgn = beluci occidentale
language-name-bho = bhojpuri
language-name-bi = bislama
language-name-bik = bicol
language-name-bin = bini
language-name-bjn = banjar
language-name-bkm = kom
language-name-bla = siksika
language-name-bm = bambara
language-name-bn = bengalese
language-name-bo = tibetano
language-name-bpy = bishnupriya
language-name-bqi = bakhtiari
language-name-br = bretone
language-name-bra = braj
language-name-brh = brahui
language-name-brx = bodo
language-name-bs = bosniaco
language-name-bss = akoose
language-name-bua = buriat
language-name-bug = bugi
language-name-bum = bulu
language-name-byn = blin
language-name-byv = medumba
language-name-ca = catalano
language-name-cad = caddo
language-name-car = caribico
language-name-cay = cayuga
language-name-cch = atsam
language-name-ce = ceceno
language-name-ceb = cebuano
language-name-cgg = chiga
language-name-ch = chamorro
language-name-chb = chibcha
language-name-chg = ciagataico
language-name-chk = chuukese
language-name-chm = mari
language-name-chn = gergo chinook
language-name-cho = choctaw
language-name-chp = chipewyan
language-name-chr = cherokee
language-name-chy = cheyenne
language-name-ckb = curdo sorani
language-name-co = corso
language-name-cop = copto
language-name-cps = capiznon
language-name-cr = cree
language-name-crh = turco crimeo
language-name-crs = creolo delle Seychelles
language-name-cs = ceco
language-name-csb = kashubian
language-name-cu = slavo della Chiesa
language-name-cv = ciuvascio
language-name-cy = gallese
language-name-da = danese
language-name-dak = dakota
language-name-dar = dargwa
language-name-dav = taita
language-name-de = tedesco
language-name-de_AT = tedesco austriaco
language-name-de_CH = alto tedesco svizzero
language-name-del = delaware
language-name-den = slave
language-name-dgr = dogrib
language-name-din = dinca
language-name-dje = zarma
language-name-doi = dogri
language-name-dsb = basso sorabo
language-name-dtp = dusun centrale
language-name-dua = duala
language-name-dum = olandese medio
language-name-dv = divehi
language-name-dyo = jola-fony
language-name-dyu = diula
language-name-dz = dzongkha
language-name-dzg = dazaga
language-name-ebu = embu
language-name-ee = ewe
language-name-efi = efik
language-name-egl = emiliano
language-name-egy = egiziano antico
language-name-eka = ekajuka
language-name-el = greco
language-name-elx = elamitico
language-name-en = inglese
language-name-en_AU = inglese australiano
language-name-en_CA = inglese canadese
language-name-en_GB = inglese britannico
language-name-en_US = inglese americano
language-name-enm = inglese medio
language-name-eo = esperanto
language-name-es = spagnolo
language-name-es_419 = spagnolo latinoamericano
language-name-es_ES = spagnolo europeo
language-name-es_MX = spagnolo messicano
language-name-esu = yupik centrale
language-name-et = estone
language-name-eu = basco
language-name-ewo = ewondo
language-name-ext = estremegno
language-name-fa = persiano
language-name-fan = fang
language-name-fat = fanti
language-name-ff = fulah
language-name-fi = finlandese
language-name-fil = filippino
language-name-fit = finlandese del Tornedalen
language-name-fj = figiano
language-name-fo = faroese
language-name-fon = fon
language-name-fr = francese
language-name-fr_CA = francese canadese
language-name-fr_CH = francese svizzero
language-name-frc = francese cajun
language-name-frm = francese medio
language-name-fro = francese antico
language-name-frp = francoprovenzale
language-name-frr = frisone settentrionale
language-name-frs = frisone orientale
language-name-fur = friulano
language-name-fy = frisone occidentale
language-name-ga = irlandese
language-name-gaa = ga
language-name-gag = gagauzo
language-name-gan = gan
language-name-gay = gayo
language-name-gba = gbaya
language-name-gbz = dari zoroastriano
language-name-gd = gaelico scozzese
language-name-gez = geez
language-name-gil = gilbertese
language-name-gl = galiziano
language-name-glk = gilaki
language-name-gmh = tedesco medio alto
language-name-gn = guaraní
language-name-goh = tedesco antico alto
language-name-gom = konkani goano
language-name-gon = gondi
language-name-gor = gorontalo
language-name-got = gotico
language-name-grb = grebo
language-name-grc = greco antico
language-name-gsw = tedesco svizzero
language-name-gu = gujarati
language-name-guc = wayuu
language-name-guz = gusii
language-name-gv = mannese
language-name-gwi = gwichʼin
language-name-ha = hausa
language-name-hai = haida
language-name-hak = hakka
language-name-haw = hawaiano
language-name-he = ebraico
language-name-hi = hindi
language-name-hif = hindi figiano
language-name-hil = ilongo
language-name-hit = hittite
language-name-hmn = hmong
language-name-ho = hiri motu
language-name-hr = croato
language-name-hsb = alto sorabo
language-name-hsn = xiang
language-name-ht = haitiano
language-name-hu = ungherese
language-name-hup = hupa
language-name-hy = armeno
language-name-hz = herero
language-name-ia = interlingua
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indonesiano
language-name-ie = interlingue
language-name-ig = igbo
language-name-ii = sichuan yi
language-name-ik = inupiak
language-name-ilo = ilocano
language-name-inh = ingush
language-name-io = ido
language-name-is = islandese
language-name-it = italiano
language-name-iu = inuktitut
language-name-izh = ingrico
language-name-ja = giapponese
language-name-jam = creolo giamaicano
language-name-jbo = lojban
language-name-jgo = ngamambo
language-name-jmc = machame
language-name-jpr = giudeo persiano
language-name-jrb = giudeo arabo
language-name-jut = jutlandico
language-name-jv = giavanese
language-name-ka = georgiano
language-name-kaa = kara-kalpak
language-name-kab = cabilo
language-name-kac = kachin
language-name-kaj = kai
language-name-kam = kamba
language-name-kaw = kawi
language-name-kbd = cabardino
language-name-kbl = kanembu
language-name-kcg = tyap
language-name-kde = makonde
language-name-kea = capoverdiano
language-name-kfo = koro
language-name-kg = kongo
language-name-kgp = kaingang
language-name-kha = khasi
language-name-kho = khotanese
language-name-khq = koyra chiini
language-name-khw = khowar
language-name-ki = kikuyu
language-name-kiu = kirmanjki
language-name-kj = kuanyama
language-name-kk = kazako
language-name-kkj = kako
language-name-kl = groenlandese
language-name-kln = kalenjin
language-name-km = khmer
language-name-kmb = kimbundu
language-name-kn = kannada
language-name-ko = coreano
language-name-koi = permiaco
language-name-kok = konkani
language-name-kos = kosraean
language-name-kpe = kpelle
language-name-kr = kanuri
language-name-krc = karachay-Balkar
language-name-krl = careliano
language-name-kru = kurukh
language-name-ks = kashmiri
language-name-ksb = shambala
language-name-ksf = bafia
language-name-ksh = coloniese
language-name-ku = curdo
language-name-kum = kumyk
language-name-kut = kutenai
language-name-kv = komi
language-name-kw = cornico
language-name-ky = chirghiso
language-name-la = latino
language-name-lad = giudeo-spagnolo
language-name-lag = langi
language-name-lah = lahnda
language-name-lam = lamba
language-name-lb = lussemburghese
language-name-lez = lesgo
language-name-lfn = Lingua Franca Nova
language-name-lg = ganda
language-name-li = limburghese
language-name-lij = ligure
language-name-liv = livone
language-name-lkt = lakota
language-name-lmo = lombardo
language-name-ln = lingala
language-name-lo = lao
language-name-lol = lolo bantu
language-name-lou = creolo della Louisiana
language-name-loz = lozi
language-name-lrc = luri settentrionale
language-name-lt = lituano
language-name-ltg = letgallo
language-name-lu = luba-katanga
language-name-lua = luba-lulua
language-name-lui = luiseno
language-name-lun = lunda
language-name-luo = luo
language-name-lus = lushai
language-name-luy = luyia
language-name-lv = lettone
language-name-lzh = cinese classico
language-name-lzz = laz
language-name-mad = madurese
language-name-maf = mafa
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = makasar
language-name-man = mandingo
language-name-mas = masai
language-name-mde = maba
language-name-mdf = moksha
language-name-mdr = mandar
language-name-men = mende
language-name-mer = meru
language-name-mfe = creolo mauriziano
language-name-mg = malgascio
language-name-mga = irlandese medio
language-name-mgh = makhuwa-meetto
language-name-mgo = meta’
language-name-mh = marshallese
language-name-mi = maori
language-name-mic = micmac
language-name-min = menangkabau
language-name-mk = macedone
language-name-ml = malayalam
language-name-mn = mongolo
language-name-mnc = manchu
language-name-mni = manipuri
language-name-moh = mohawk
language-name-mos = mossi
language-name-mr = marathi
language-name-mrj = mari occidentale
language-name-ms = malese
language-name-mt = maltese
language-name-mua = mundang
language-name-mul = multilingua
language-name-mus = creek
language-name-mwl = mirandese
language-name-mwr = marwari
language-name-mwv = mentawai
language-name-my = birmano
language-name-mye = myene
language-name-myv = erzya
language-name-mzn = mazandarani
language-name-na = nauru
language-name-nan = min nan
language-name-nap = napoletano
language-name-naq = nama
language-name-nb = norvegese bokmål
language-name-nd = ndebele del nord
language-name-nds = basso tedesco
language-name-nds_NL = basso tedesco olandese
language-name-ne = nepalese
language-name-new = newari
language-name-ng = ndonga
language-name-nia = nias
language-name-niu = niue
language-name-njo = ao
language-name-nl = olandese
language-name-nl_BE = fiammingo
language-name-nmg = kwasio
language-name-nn = norvegese nynorsk
language-name-nnh = ngiemboon
language-name-no = norvegese
language-name-nog = nogai
language-name-non = norse antico
language-name-nov = novial
language-name-nqo = n’ko
language-name-nr = ndebele del sud
language-name-nso = sotho del nord
language-name-nus = nuer
language-name-nv = navajo
language-name-nwc = newari classico
language-name-ny = nyanja
language-name-nym = nyamwezi
language-name-nyn = nyankole
language-name-nyo = nyoro
language-name-nzi = nzima
language-name-oc = occitano
language-name-oj = ojibwa
language-name-om = oromo
language-name-or = oriya
language-name-os = ossetico
language-name-osa = osage
language-name-ota = turco ottomano
language-name-pa = punjabi
language-name-pag = pangasinan
language-name-pal = pahlavi
language-name-pam = pampanga
language-name-pap = papiamento
language-name-pau = palau
language-name-pcd = piccardo
language-name-pcm = pidgin nigeriano
language-name-pdc = tedesco della Pennsylvania
language-name-peo = persiano antico
language-name-pfl = tedesco palatino
language-name-phn = fenicio
language-name-pi = pali
language-name-pl = polacco
language-name-pms = piemontese
language-name-pnt = pontico
language-name-pon = ponape
language-name-prg = prussiano
language-name-pro = provenzale antico
language-name-ps = pashto
language-name-pt = portoghese
language-name-pt_BR = portoghese brasiliano
language-name-pt_PT = portoghese europeo
language-name-qu = quechua
language-name-quc = k’iche’
language-name-qug = quechua dell’altopiano del Chimborazo
language-name-raj = rajasthani
language-name-rap = rapanui
language-name-rar = rarotonga
language-name-rgn = romagnolo
language-name-rif = tarifit
language-name-rm = romancio
language-name-rn = rundi
language-name-ro = rumeno
language-name-ro_MD = moldavo
language-name-rof = rombo
language-name-rom = romani
language-name-root = root
language-name-rtm = rotumano
language-name-ru = russo
language-name-rue = ruteno
language-name-rug = roviana
language-name-rup = arumeno
language-name-rw = kinyarwanda
language-name-rwk = rwa
language-name-sa = sanscrito
language-name-sad = sandawe
language-name-sah = yakut
language-name-sam = aramaico samaritano
language-name-saq = samburu
language-name-sas = sasak
language-name-sat = santali
language-name-saz = saurashtra
language-name-sba = ngambay
language-name-sbp = sangu
language-name-sc = sardo
language-name-scn = siciliano
language-name-sco = scozzese
language-name-sd = sindhi
language-name-sdc = sassarese
language-name-sdh = curdo meridionale
language-name-se = sami del nord
language-name-see = seneca
language-name-seh = sena
language-name-sei = seri
language-name-sel = selkup
language-name-ses = koyraboro senni
language-name-sg = sango
language-name-sga = irlandese antico
language-name-sgs = samogitico
language-name-sh = serbo-croato
language-name-shi = tashelhit
language-name-shn = shan
language-name-shu = arabo ciadiano
language-name-si = singalese
language-name-sid = sidamo
language-name-sk = slovacco
language-name-sl = sloveno
language-name-sli = tedesco slesiano
language-name-sly = selayar
language-name-sm = samoano
language-name-sma = sami del sud
language-name-smj = sami di Lule
language-name-smn = sami di Inari
language-name-sms = sami skolt
language-name-sn = shona
language-name-snk = soninke
language-name-so = somalo
language-name-sog = sogdiano
language-name-sq = albanese
language-name-sr = serbo
language-name-srn = sranan tongo
language-name-srr = serer
language-name-ss = swati
language-name-ssy = saho
language-name-st = sotho del sud
language-name-stq = saterfriesisch
language-name-su = sundanese
language-name-suk = sukuma
language-name-sus = susu
language-name-sux = sumero
language-name-sv = svedese
language-name-sw = swahili
language-name-sw_CD = swahili del Congo
language-name-swb = comoriano
language-name-syc = siriaco classico
language-name-syr = siriaco
language-name-szl = slesiano
language-name-ta = tamil
language-name-tcy = tulu
language-name-te = telugu
language-name-tem = temne
language-name-teo = teso
language-name-ter = tereno
language-name-tet = tetum
language-name-tg = tagico
language-name-th = thai
language-name-ti = tigrino
language-name-tig = tigre
language-name-tiv = tiv
language-name-tk = turcomanno
language-name-tkl = tokelau
language-name-tkr = tsakhur
language-name-tl = tagalog
language-name-tlh = klingon
language-name-tli = tlingit
language-name-tly = taliscio
language-name-tmh = tamashek
language-name-tn = tswana
language-name-to = tongano
language-name-tog = nyasa del Tonga
language-name-tpi = tok pisin
language-name-tr = turco
language-name-tru = turoyo
language-name-trv = taroko
language-name-ts = tsonga
language-name-tsd = zaconico
language-name-tsi = tsimshian
language-name-tt = tataro
language-name-ttt = tat islamico
language-name-tum = tumbuka
language-name-tvl = tuvalu
language-name-tw = ci
language-name-twq = tasawaq
language-name-ty = taitiano
language-name-tyv = tuvinian
language-name-tzm = tamazight
language-name-udm = udmurt
language-name-ug = uiguro
language-name-uga = ugaritico
language-name-uk = ucraino
language-name-umb = mbundu
language-name-und = lingua imprecisata
language-name-ur = urdu
language-name-uz = uzbeco
language-name-vai = vai
language-name-ve = venda
language-name-vec = veneto
language-name-vep = vepso
language-name-vi = vietnamita
language-name-vls = fiammingo occidentale
language-name-vo = volapük
language-name-vot = voto
language-name-vro = võro
language-name-vun = vunjo
language-name-wa = vallone
language-name-wae = walser
language-name-wal = walamo
language-name-war = waray
language-name-was = washo
language-name-wbp = warlpiri
language-name-wo = wolof
language-name-wuu = wu
language-name-xal = kalmyk
language-name-xh = xhosa
language-name-xmf = mengrelio
language-name-xog = soga
language-name-yap = yapese
language-name-yav = yangben
language-name-ybb = yemba
language-name-yi = yiddish
language-name-yo = yoruba
language-name-yrl = nheengatu
language-name-yue = cantonese
language-name-za = zhuang
language-name-zap = zapotec
language-name-zbl = blissymbol
language-name-zea = zelandese
language-name-zen = zenaga
language-name-zgh = tamazight del Marocco standard
language-name-zh = cinese
language-name-zh_Hans = cinese semplificato
language-name-zh_Hant = cinese tradizionale
language-name-zu = zulu
language-name-zun = zuni
language-name-zxx = nessun contenuto linguistico
language-name-zza = zaza
