language-name-aa = აფარი
language-name-ab = აფხაზური
language-name-ace = აჩეხური
language-name-ach = აჩოლი
language-name-ada = ადანგმე
language-name-ady = ადიღეური
language-name-ae = ავესტური
language-name-af = აფრიკაანსი
language-name-agq = აღემი
language-name-ain = აინუური
language-name-ak = აკანი
language-name-akk = აქადური
language-name-ale = ალეუტური
language-name-alt = სამხრეთ ალთაური
language-name-am = ამჰარული
language-name-an = არაგონული
language-name-ang = ძველი ინგლისური
language-name-anp = ანგიკა
language-name-ar = არაბული
language-name-ar_001 = თანამედროვე სტანდარტული არაბული
language-name-arc = არამეული
language-name-arn = მაპუდუნგუნი
language-name-arp = არაპაჰო
language-name-arw = არავაკი
language-name-as = ასამური
language-name-asa = ასუ
language-name-ast = ასტურიული
language-name-av = ხუნძური
language-name-awa = ავადი
language-name-ay = აიმარა
language-name-az = აზერბაიჯანული
language-name-ba = ბაშკირული
language-name-bal = ბელუჯი
language-name-ban = ბალინური
language-name-bas = ბასა
language-name-bax = ბამუნი
language-name-be = ბელორუსული
language-name-bej = ბეჯა
language-name-bem = ბემბა
language-name-bez = ბენა
language-name-bg = ბულგარული
language-name-bgn = დასავლეთ ბელუჯი
language-name-bho = ბოჯპური
language-name-bi = ბისლამა
language-name-bin = ბინი
language-name-bla = სიკსიკა
language-name-bm = ბამბარა
language-name-bn = ბენგალური
language-name-bo = ტიბეტური
language-name-br = ბრეტონული
language-name-bra = ბრაჯი
language-name-brx = ბოდო
language-name-bs = ბოსნიური
language-name-bua = ბურიატული
language-name-bug = ბუგინური
language-name-byn = ბილინი
language-name-ca = კატალანური
language-name-cay = კაიუგა
language-name-ce = ჩეჩნური
language-name-ceb = სებუანო
language-name-cgg = ჩიგა
language-name-ch = ჩამორო
language-name-chb = ჩიბჩა
language-name-chk = ჩუკოტკური
language-name-chm = მარიული
language-name-chn = ჩინუკის ჟარგონი
language-name-cho = ჩოკტო
language-name-chp = ჩიპევიანი
language-name-chr = ჩეროკი
language-name-chy = ჩეიენი
language-name-ckb = ცენტრალური ქურთული
language-name-co = კორსიკული
language-name-cop = კოპტური
language-name-cr = კრი
language-name-crh = ყირიმულ-თურქული
language-name-crs = სესელვა-კრეოლური ფრანგული
language-name-cs = ჩეხური
language-name-csb = კაშუბური
language-name-cu = საეკლესიო სლავური
language-name-cv = ჩუვაშური
language-name-cy = უელსური
language-name-da = დანიური
language-name-dak = დაკოტური
language-name-dar = დარგუული
language-name-dav = ტაიტა
language-name-de = გერმანული
language-name-de_AT = ავსტრიული გერმანული
language-name-de_CH = შვეიცარიული ზემოგერმანული
language-name-del = დელავერული
language-name-den = სლეივი
language-name-dgr = დოგრიბი
language-name-din = დინკა
language-name-dje = ზარმა
language-name-doi = დოგრი
language-name-dsb = ქვემოსორბული
language-name-dua = დუალა
language-name-dum = საშუალო ჰოლანდიური
language-name-dv = დივეჰი
language-name-dyo = დიოლა
language-name-dyu = დიულა
language-name-dz = ძონგკხა
language-name-dzg = დაზაგა
language-name-ebu = ემბუ
language-name-ee = ევე
language-name-efi = ეფიკი
language-name-egy = ძველეგვიპტური
language-name-eka = ეკაჯუკი
language-name-el = ბერძნული
language-name-en = ინგლისური
language-name-en_AU = ავსტრალიური ინგლისური
language-name-en_CA = კანადური ინგლისური
language-name-en_GB = ბრიტანული ინგლისური
language-name-en_US = ამერიკული ინგლისური
language-name-enm = საშუალო ინგლისური
language-name-eo = ესპერანტო
language-name-es = ესპანური
language-name-es_419 = ლათინურ ამერიკული ესპანური
language-name-es_ES = ევროპული ესპანური
language-name-es_MX = მექსიკური ესპანური
language-name-et = ესტონური
language-name-eu = ბასკური
language-name-ewo = ევონდო
language-name-fa = სპარსული
language-name-ff = ფულა
language-name-fi = ფინური
language-name-fil = ფილიპინური
language-name-fj = ფიჯი
language-name-fo = ფარერული
language-name-fon = ფონი
language-name-fr = ფრანგული
language-name-fr_CA = კანადური ფრანგული
language-name-fr_CH = შვეიცარიული ფრანგული
language-name-frm = საშუალო ფრანგული
language-name-fro = ძველი ფრანგული
language-name-frr = ჩრდილოფრიზიული
language-name-frs = აღმოსავლეთფრიზიული
language-name-fur = ფრიულური
language-name-fy = დასავლეთფრიზიული
language-name-ga = ირლანდიური
language-name-gaa = გა
language-name-gag = გაგაუზური
language-name-gba = გბაია
language-name-gd = შოტლანდიური გელური
language-name-gez = გეეზი
language-name-gil = გილბერტული
language-name-gl = გალისიური
language-name-gmh = საშუალო ზემოგერმანული
language-name-gn = გუარანი
language-name-goh = ძველი ზემოგერმანული
language-name-gon = გონდი
language-name-gor = გორონტალო
language-name-got = გოთური
language-name-grc = ძველი ბერძნული
language-name-gsw = შვეიცარიული გერმანული
language-name-gu = გუჯარათი
language-name-guz = გუსიი
language-name-gv = მენური
language-name-gwi = გვიჩინი
language-name-ha = ჰაუსა
language-name-haw = ჰავაიური
language-name-he = ებრაული
language-name-hi = ჰინდი
language-name-hil = ჰილიგაინონი
language-name-hit = ხეთური
language-name-hmn = ჰმონგი
language-name-hr = ხორვატული
language-name-hsb = ზემოსორბული
language-name-ht = ჰაიტიური კრეოლი
language-name-hu = უნგრული
language-name-hup = ჰუპა
language-name-hy = სომხური
language-name-hz = ჰერერო
language-name-ia = ინტერლინგუალური
language-name-iba = იბანი
language-name-ibb = იბიბიო
language-name-id = ინდონეზიური
language-name-ie = ინტერლინგი
language-name-ig = იგბო
language-name-ii = სიჩუანის ი
language-name-ilo = ილოკო
language-name-inh = ინგუშური
language-name-io = იდო
language-name-is = ისლანდიური
language-name-it = იტალიური
language-name-iu = ინუკტიტუტი
language-name-ja = იაპონური
language-name-jbo = ლოჟბანი
language-name-jgo = ნგომბა
language-name-jmc = კიმაშამი
language-name-jpr = იუდეო-სპარსული
language-name-jrb = იუდეო-არაბული
language-name-jv = იავური
language-name-ka = ქართული
language-name-kaa = ყარაყალფახური
language-name-kab = კაბილური
language-name-kac = კაჩინი
language-name-kaj = კაჯი
language-name-kam = კამბა
language-name-kbd = ყაბარდოული
language-name-kcg = ტიაპი
language-name-kde = მაკონდე
language-name-kea = კაბუვერდიანუ
language-name-kfo = კორო
language-name-kg = კონგო
language-name-kha = ხასი
language-name-khq = კოირა-ჩიინი
language-name-ki = კიკუიუ
language-name-kj = კუნამა
language-name-kk = ყაზახური
language-name-kkj = კაკო
language-name-kl = დასავლეთ გრენლანდიური
language-name-kln = კალენჯინი
language-name-km = ქმერული
language-name-kmb = კიმბუნდუ
language-name-kn = კანადა
language-name-ko = კორეული
language-name-koi = კომი-პერმიაკული
language-name-kok = კონკანი
language-name-kos = კუსაიე
language-name-kpe = კპელე
language-name-kr = კანური
language-name-krc = ყარაჩაულ-ბალყარული
language-name-krl = კარელიური
language-name-kru = კურუქი
language-name-ks = ქაშმირული
language-name-ksb = შამბალა
language-name-ksf = ბაფია
language-name-ksh = კიოლში
language-name-ku = ქურთული
language-name-kum = ყუმუხური
language-name-kut = კუტენაი
language-name-kv = კომი
language-name-kw = კორნული
language-name-ky = ყირგიზული
language-name-la = ლათინური
language-name-lad = ლადინო
language-name-lag = ლანგი
language-name-lah = ლანდა
language-name-lam = ლამბა
language-name-lb = ლუქსემბურგული
language-name-lez = ლეზგიური
language-name-lg = განდა
language-name-li = ლიმბურგული
language-name-lkt = ლაკოტა
language-name-ln = ლინგალა
language-name-lo = ლაოსური
language-name-lol = მონგო
language-name-loz = ლოზი
language-name-lrc = ჩრდილოეთ ლური
language-name-lt = ლიტვური
language-name-lu = ლუბა-კატანგა
language-name-lua = ლუბა-ლულუა
language-name-lui = ლუისენიო
language-name-lun = ლუნდა
language-name-luo = ლუო
language-name-lus = მიზო
language-name-luy = ლუჰია
language-name-lv = ლატვიური
language-name-mad = მადურული
language-name-maf = მაფა
language-name-mag = მაგაჰი
language-name-mai = მაითილი
language-name-mak = მაკასარი
language-name-mas = მასაი
language-name-mde = მაბა
language-name-mdf = მოქშა
language-name-men = მენდე
language-name-mer = მერუ
language-name-mfe = მორისიენი
language-name-mg = მალაგასიური
language-name-mga = საშუალო ირლანდიური
language-name-mgh = მაქუვა-მეეტო
language-name-mgo = მეტა-ენა
language-name-mh = მარშალური
language-name-mi = მაორი
language-name-mic = მიკმაკი
language-name-min = მინანგკაბაუ
language-name-mk = მაკედონური
language-name-ml = მალაიალამური
language-name-mn = მონღოლური
language-name-mnc = მანჯურიული
language-name-mni = მანიპური
language-name-moh = მოჰაუკური
language-name-mos = მოსი
language-name-mr = მარათჰი
language-name-ms = მალაიური
language-name-mt = მალტური
language-name-mua = მუნდანგი
language-name-mul = სხვადასხვა ენა
language-name-mus = კრიკი
language-name-mwl = მირანდული
language-name-mwr = მარვარი
language-name-my = ბირმული
language-name-mye = მიენე
language-name-myv = ერზია
language-name-mzn = მაზანდერანული
language-name-na = ნაურუ
language-name-nap = ნეაპოლიტანური
language-name-naq = ნამა
language-name-nb = ნორვეგიული ბუკმოლი
language-name-nd = ჩრდილოეთ ნდებელე
language-name-nds = ქვემოგერმანული
language-name-nds_NL = ქვემოსაქსონური
language-name-ne = ნეპალური
language-name-new = ნევარი
language-name-ng = ნდონგა
language-name-nia = ნიასი
language-name-niu = ნიუე
language-name-nl = ნიდერლანდური
language-name-nl_BE = ფლამანდიური
language-name-nmg = კვასიო
language-name-nn = ნორვეგიული ნიუნორსკი
language-name-nnh = ნგიმბუნი
language-name-no = ნორვეგიული
language-name-nog = ნოღაური
language-name-non = ძველსკანდინავიური
language-name-nqo = ნკო
language-name-nr = სამხრეთ ნდებელური
language-name-nso = ჩრდილოეთ სოთო
language-name-nus = ნუერი
language-name-nv = ნავახო
language-name-nwc = კლასიკური ნევარული
language-name-ny = ნიანჯა
language-name-nym = ნიამვეზი
language-name-nyn = ნიანკოლე
language-name-nyo = ნიორო
language-name-nzi = ნზიმა
language-name-oc = ოქსიტანური
language-name-oj = ოჯიბვე
language-name-om = ორომო
language-name-or = ორია
language-name-os = ოსური
language-name-pa = პენჯაბური
language-name-pag = პანგასინანი
language-name-pal = ფალაური
language-name-pam = პამპანგა
language-name-pap = პაპიამენტო
language-name-pau = ფალაუანი
language-name-pcm = ნიგერიული კრეოლური
language-name-peo = ძველი სპარსული
language-name-phn = ფინიკიური
language-name-pi = პალი
language-name-pl = პოლონური
language-name-prg = პრუსიული
language-name-pro = ძველი პროვანსული
language-name-ps = პუშტუ
language-name-pt = პორტუგალიური
language-name-pt_BR = ბრაზილიური პორტუგალიური
language-name-pt_PT = ევროპული პორტუგალიური
language-name-qu = კეჩუა
language-name-quc = კიჩე
language-name-raj = რაჯასთანი
language-name-rap = რაპანუი
language-name-rar = რაროტონგული
language-name-rm = რეტორომანული
language-name-rn = რუნდი
language-name-ro = რუმინული
language-name-ro_MD = მოლდავური
language-name-rof = რომბო
language-name-rom = ბოშური
language-name-root = ძირეული ენა
language-name-ru = რუსული
language-name-rup = არომანული
language-name-rw = კინიარუანდა
language-name-rwk = რუა
language-name-sa = სანსკრიტი
language-name-sad = სანდავე
language-name-sah = იაკუტური
language-name-sam = სამარიულ-არამეული
language-name-saq = სამბურუ
language-name-sat = სანტალი
language-name-sba = ნგამბაი
language-name-sbp = სანგუ
language-name-sc = სარდინიული
language-name-scn = სიცილიური
language-name-sco = შოტლანდიური
language-name-sd = სინდჰური
language-name-sdh = სამხრეთქურთული
language-name-se = ჩრდილოეთ საამური
language-name-see = სენეკა
language-name-seh = სენა
language-name-sel = სელკუპური
language-name-ses = კოირაბორო-სენი
language-name-sg = სანგო
language-name-sga = ძველი ირლანდიური
language-name-sh = სერბულ-ხორვატული
language-name-shi = შილჰა
language-name-shn = შანი
language-name-shu = ჩადური არაბული
language-name-si = სინჰალური
language-name-sk = სლოვაკური
language-name-sl = სლოვენური
language-name-sm = სამოა
language-name-sma = სამხრეთსამური
language-name-smj = ლულე-საამური
language-name-smn = ინარი-საამური
language-name-sms = სკოლტ-საამური
language-name-sn = შონა
language-name-snk = სონინკე
language-name-so = სომალიური
language-name-sq = ალბანური
language-name-sr = სერბული
language-name-srn = სრანან ტონგო
language-name-ss = სუატი
language-name-ssy = საჰო
language-name-st = სამხრეთ სოთოს ენა
language-name-su = სუნდური
language-name-suk = სუკუმა
language-name-sux = შუმერული
language-name-sv = შვედური
language-name-sw = სუაჰილი
language-name-sw_CD = კონგოს სუაჰილი
language-name-swb = კომორული
language-name-syc = კლასიკური სირიული
language-name-syr = სირიული
language-name-ta = ტამილური
language-name-te = ტელუგუ
language-name-tem = ტინმე
language-name-teo = ტესო
language-name-tet = ტეტუმი
language-name-tg = ტაჯიკური
language-name-th = ტაი
language-name-ti = ტიგრინია
language-name-tig = თიგრე
language-name-tk = თურქმენული
language-name-tlh = კლინგონი
language-name-tn = ტსვანა
language-name-to = ტონგანური
language-name-tpi = ტოკ-პისინი
language-name-tr = თურქული
language-name-trv = ტაროკო
language-name-ts = ტსონგა
language-name-tt = თათრული
language-name-tum = ტუმბუკა
language-name-tvl = ტუვალუ
language-name-tw = თუი
language-name-twq = ტასავაქი
language-name-ty = ტაიტური
language-name-tyv = ტუვა
language-name-tzm = ცენტრალური მოროკოს ტამაზიგხტი
language-name-udm = უდმურტული
language-name-ug = უიღურული
language-name-uga = უგარითული
language-name-uk = უკრაინული
language-name-umb = უმბუნდუ
language-name-und = უცნობი ენა
language-name-ur = ურდუ
language-name-uz = უზბეკური
language-name-vai = ვაი
language-name-ve = ვენდა
language-name-vi = ვიეტნამური
language-name-vo = ვოლაპუკი
language-name-vun = ვუნჯო
language-name-wa = ვალონური
language-name-wae = ვალსერი
language-name-wal = ველაითა
language-name-war = ვარაი
language-name-wbp = ვალპირი
language-name-wo = ვოლოფური
language-name-xal = ყალმუხური
language-name-xh = ქჰოსა
language-name-xog = სოგა
language-name-yav = იანგბენი
language-name-ybb = იემბა
language-name-yi = იდიში
language-name-yo = იორუბა
language-name-yue = კანტონური
language-name-zbl = ბლისსიმბოლოები
language-name-zen = ზენაგა
language-name-zgh = სტანდარტული მაროკოული ტამაზიგხტი
language-name-zh = ჩინური
language-name-zh_Hans = გამარტივებული ჩინური
language-name-zh_Hant = ტრადიციული ჩინური
language-name-zu = ზულუ
language-name-zun = ზუნი
language-name-zxx = ლინგვისტური შიგთავსი არ არის
language-name-zza = ზაზაკი
