language-name-aa = афарски
language-name-ab = апхаски
language-name-ace = ачешки
language-name-ach = аколи
language-name-ada = адангме
language-name-ady = адигејски
language-name-ae = авестански
language-name-aeb = туниски арапски
language-name-af = африканс
language-name-afh = африхили
language-name-agq = агемски
language-name-ain = ајну
language-name-ak = акански
language-name-akk = акадски
language-name-akz = алабамски
language-name-ale = алеутски
language-name-aln = гешки албански
language-name-alt = јужноалтајски
language-name-am = амхарски
language-name-an = арагонски
language-name-ang = староанглиски
language-name-anp = ангика
language-name-ar = арапски
language-name-ar_001 = литературен арапски
language-name-arc = арамејски
language-name-arn = мапучки
language-name-aro = араона
language-name-arp = арапахо
language-name-arq = алжирски арапски
language-name-arw = аравачки
language-name-ary = марокански арапски
language-name-arz = египетски арапски
language-name-as = асамски
language-name-asa = асу
language-name-ase = американски знаковен јазик
language-name-ast = астурски
language-name-av = аварски
language-name-avk = котава
language-name-awa = авади
language-name-ay = ајмарски
language-name-az = азербејџански
language-name-ba = башкирски
language-name-bal = белуџиски
language-name-ban = балиски
language-name-bar = баварски
language-name-bas = баса
language-name-bax = бамунски
language-name-bbc = тоба
language-name-bbj = гомала
language-name-be = белоруски
language-name-bej = беџа
language-name-bem = бемба
language-name-bew = бетавски
language-name-bez = бена
language-name-bfd = бафут
language-name-bfq = бадага
language-name-bg = бугарски
language-name-bgn = западен балочи
language-name-bho = боџпури
language-name-bi = бислама
language-name-bik = биколски
language-name-bin = бини
language-name-bjn = банџарски
language-name-bkm = ком
language-name-bla = сиксика
language-name-bm = бамбара
language-name-bn = бенгалски
language-name-bo = тибетски
language-name-bpy = бишнуприја
language-name-bqi = бахтијарски
language-name-br = бретонски
language-name-bra = брај
language-name-brh = брахујски
language-name-brx = бодо
language-name-bs = босански
language-name-bss = акосе
language-name-bua = бурјатски
language-name-bug = бугиски
language-name-bum = булу
language-name-byn = биленски
language-name-byv = медумба
language-name-ca = каталонски
language-name-cad = кадо
language-name-car = карипски
language-name-cay = кајуга
language-name-cch = ацам
language-name-ce = чеченски
language-name-ceb = себуански
language-name-cgg = чига
language-name-ch = чаморски
language-name-chb = чибча
language-name-chg = чагатајски
language-name-chk = чучки
language-name-chm = мариски
language-name-chn = чинучки жаргон
language-name-cho = чоктавски
language-name-chp = чипевјански
language-name-chr = черокиски
language-name-chy = чејенски
language-name-ckb = централнокурдски
language-name-co = корзикански
language-name-cop = коптски
language-name-cps = капизнон
language-name-cr = кри
language-name-crh = кримскотурски
language-name-cs = чешки
language-name-csb = кашупски
language-name-cu = црковнословенски
language-name-cv = чувашки
language-name-cy = велшки
language-name-da = дански
language-name-dak = дакота
language-name-dar = даргва
language-name-dav = таита
language-name-de = германски
language-name-de_AT = австриски германски
language-name-de_CH = швајцарски високо-германски
language-name-del = делавер
language-name-den = слејви
language-name-dgr = догрипски
language-name-din = динка
language-name-dje = зарма
language-name-doi = догри
language-name-dsb = долнолужички
language-name-dtp = дусунски
language-name-dua = дуала
language-name-dum = среднохоландски
language-name-dv = дивехи
language-name-dyo = јола-фоњи
language-name-dyu = џула
language-name-dz = ѕонгка
language-name-dzg = дазага
language-name-ebu = ембу
language-name-ee = еве
language-name-efi = ефик
language-name-egl = емилијански
language-name-egy = староегипетски
language-name-eka = екаџук
language-name-el = грчки
language-name-elx = еламски
language-name-en = англиски
language-name-en_AU = австралиски англиски
language-name-en_CA = канадски англиски
language-name-en_GB = британски англиски
language-name-en_US = американски англиски
language-name-enm = средноанглиски
language-name-eo = есперанто
language-name-es = шпански
language-name-es_419 = латиноамерикански шпански
language-name-es_MX = мексикански шпански
language-name-esu = централнојупички
language-name-et = естонски
language-name-eu = баскиски
language-name-ewo = евондо
language-name-ext = екстремадурски
language-name-fa = персиски
language-name-fan = фанг
language-name-fat = фанти
language-name-ff = фула
language-name-fi = фински
language-name-fil = филипински
language-name-fit = турнедаленски фински
language-name-fj = фиџиски
language-name-fo = фарски
language-name-fon = фон
language-name-fr = француски
language-name-fr_CA = канадски француски
language-name-fr_CH = швајцарски француски
language-name-frc = каџунски француски
language-name-frm = среднофранцуски
language-name-fro = старофранцуски
language-name-frp = франкопровансалски
language-name-frr = севернофризиски
language-name-frs = источнофризиски
language-name-fur = фурлански
language-name-fy = западнофризиски
language-name-ga = ирски
language-name-gaa = га
language-name-gag = гагауски
language-name-gan = ган
language-name-gay = гајо
language-name-gba = гбаја
language-name-gbz = зороастриски дари
language-name-gd = шкотски гелски
language-name-gez = гиз
language-name-gil = гилбертански
language-name-gl = галициски
language-name-glk = гилански
language-name-gmh = средногорногермански
language-name-gn = гварански
language-name-goh = старогорногермански
language-name-gom = гоански конкани
language-name-gon = гонди
language-name-gor = горонтало
language-name-got = готски
language-name-grb = гребо
language-name-grc = старогрчки
language-name-gsw = швајцарски германски
language-name-gu = гуџарати
language-name-guc = гвахиро
language-name-gur = фарефаре
language-name-guz = гуси
language-name-gv = манкс
language-name-gwi = гвичински
language-name-ha = хауса
language-name-hai = хајда
language-name-hak = хака
language-name-haw = хавајски
language-name-he = хебрејски
language-name-hi = хинди
language-name-hif = фиџиски хинди
language-name-hil = хилигајнонски
language-name-hit = хетитски
language-name-hmn = хмонг
language-name-ho = хири моту
language-name-hr = хрватски
language-name-hsb = горнолужички
language-name-hsn = сјанг
language-name-ht = хаитски
language-name-hu = унгарски
language-name-hup = хупа
language-name-hy = ерменски
language-name-hz = хереро
language-name-ia = интерлингва
language-name-iba = ибан
language-name-ibb = ибибио
language-name-id = индонезиски
language-name-ie = окцидентал
language-name-ig = игбо
language-name-ii = сичуан ји
language-name-ik = инупијачки
language-name-ilo = илокански
language-name-inh = ингушки
language-name-io = идо
language-name-is = исландски
language-name-it = италијански
language-name-iu = инуктитут
language-name-izh = ижорски
language-name-ja = јапонски
language-name-jam = јамајски креолски
language-name-jbo = ложбан
language-name-jgo = нгомба
language-name-jmc = мачаме
language-name-jpr = еврејскоперсиски
language-name-jrb = еврејскоарапски
language-name-jut = јитски
language-name-jv = јавански
language-name-ka = грузиски
language-name-kaa = каракалпачки
language-name-kab = кабилски
language-name-kac = качински
language-name-kaj = каџе
language-name-kam = камба
language-name-kaw = кави
language-name-kbd = кабардински
language-name-kbl = канембу
language-name-kcg = тјап
language-name-kde = маконде
language-name-kea = кабувердиану
language-name-ken = кењанг
language-name-kfo = коро
language-name-kg = конго
language-name-kgp = каинганшки
language-name-kha = каси
language-name-kho = хотански
language-name-khq = којра чиини
language-name-khw = коварски
language-name-ki = кикују
language-name-kiu = зазаки
language-name-kj = квањама
language-name-kk = казашки
language-name-kkj = како
language-name-kl = калалисут
language-name-kln = каленџин
language-name-km = кмерски
language-name-kmb = кимбунду
language-name-kn = каннада
language-name-ko = корејски
language-name-koi = коми-пермјачки
language-name-kok = конкани
language-name-kos = козрејски
language-name-kpe = кпеле
language-name-kr = канури
language-name-krc = карачаевско-балкарски
language-name-kri = крио
language-name-krj = кинарајски
language-name-krl = карелски
language-name-kru = курух
language-name-ks = кашмирски
language-name-ksb = шамбала
language-name-ksf = бафија
language-name-ksh = колоњски
language-name-ku = курдски
language-name-kum = кумички
language-name-kut = кутенајски
language-name-kv = коми
language-name-kw = корнски
language-name-ky = киргиски
language-name-la = латински
language-name-lad = ладино
language-name-lag = ланги
language-name-lah = ланда
language-name-lam = ламба
language-name-lb = луксембуршки
language-name-lez = лезгински
language-name-lfn = лингва франка нова
language-name-lg = ганда
language-name-li = лимбуршки
language-name-lij = лигурски
language-name-liv = ливонски
language-name-lkt = лакотски
language-name-lmo = ломбардиски
language-name-ln = лингала
language-name-lo = лаошки
language-name-lol = монго
language-name-lou = луизијански креолски
language-name-loz = лози
language-name-lrc = севернолуриски
language-name-lt = литвански
language-name-ltg = латгалски
language-name-lu = луба-катанга
language-name-lua = луба-лулуа
language-name-lui = лујсењски
language-name-lun = лунда
language-name-luo = луо
language-name-lus = мизо
language-name-luy = луја
language-name-lv = латвиски
language-name-lzh = книжевен кинески
language-name-lzz = ласки
language-name-mad = мадурски
language-name-maf = мафа
language-name-mag = магахи
language-name-mai = маитили
language-name-mak = макасарски
language-name-man = мандинго
language-name-mas = масајски
language-name-mde = маба
language-name-mdf = мокшански
language-name-mdr = мандарски
language-name-men = менде
language-name-mer = меру
language-name-mfe = морисјен
language-name-mg = малгашки
language-name-mga = средноирски
language-name-mgh = макува-мито
language-name-mgo = мета
language-name-mh = маршалски
language-name-mi = маорски
language-name-mic = микмак
language-name-min = минангкабау
language-name-mk = македонски
language-name-ml = малајамски
language-name-mn = монголски
language-name-mnc = манџурски
language-name-mni = манипурски
language-name-moh = мохавски
language-name-mos = моси
language-name-mr = марати
language-name-mrj = западномариски
language-name-ms = малајски
language-name-mt = малтешки
language-name-mua = мунданг
language-name-mul = повеќе јазици
language-name-mus = крик
language-name-mwl = мирандски
language-name-mwr = марвари
language-name-my = бурмански
language-name-mye = мјене
language-name-myv = ерзјански
language-name-mzn = мазендерански
language-name-na = науруански
language-name-nan = јужномински
language-name-nap = неаполски
language-name-naq = нама
language-name-nb = норвешки букмол
language-name-nd = северен ндебеле
language-name-nds = долногермански
language-name-nds_NL = долносаксонски
language-name-ne = непалски
language-name-new = неварски
language-name-ng = ндонга
language-name-nia = нијас
language-name-niu = ниујески
language-name-njo = ао нага
language-name-nl = холандски
language-name-nl_BE = фламански
language-name-nmg = квазио
language-name-nn = норвешки нинорск
language-name-nnh = нгиембун
language-name-no = норвешки
language-name-nog = ногајски
language-name-non = старонордиски
language-name-nov = новијал
language-name-nqo = нко
language-name-nr = јужен ндебеле
language-name-nso = северносотски
language-name-nus = нуер
language-name-nv = навахо
language-name-nwc = класичен неварски
language-name-ny = њанџа
language-name-nym = њамвези
language-name-nyn = њанколе
language-name-nyo = њоро
language-name-nzi = нзима
language-name-oc = окситански
language-name-oj = оџибва
language-name-om = оромо
language-name-or = одија
language-name-os = осетски
language-name-osa = осашки
language-name-ota = отомански турски
language-name-pa = пенџапски
language-name-pag = пангасинански
language-name-pal = средноперсиски
language-name-pam = пампанга
language-name-pap = папијаменто
language-name-pau = палауански
language-name-pcd = пикардски
language-name-pcm = нигериски пиџин
language-name-pdc = пенсилваниски германски
language-name-pdt = менонитски долногермански
language-name-peo = староперсиски
language-name-pfl = фалечкогермански
language-name-phn = феникиски
language-name-pi = пали
language-name-pl = полски
language-name-pms = пиемонтски
language-name-pnt = понтски
language-name-pon = понпејски
language-name-prg = пруски
language-name-pro = старопровансалски
language-name-ps = паштунски
language-name-pt = португалски
language-name-pt_BR = бразилски португалски
language-name-qu = кечуански
language-name-quc = киче
language-name-qug = кичвански
language-name-raj = раџастански
language-name-rap = рапанујски
language-name-rar = раротонгански
language-name-rgn = ромањолски
language-name-rif = рифски
language-name-rm = реторомански
language-name-rn = рунди
language-name-ro = романски
language-name-ro_MD = молдавски
language-name-rof = ромбо
language-name-rom = ромски
language-name-root = корен
language-name-rtm = ротумански
language-name-ru = руски
language-name-rue = русински
language-name-rug = ровијански
language-name-rup = влашки
language-name-rw = руандски
language-name-rwk = руа
language-name-sa = санскрит
language-name-sad = сандаве
language-name-sah = јакутски
language-name-sam = самарјански арамејски
language-name-saq = самбуру
language-name-sas = сасачки
language-name-sat = сантали
language-name-saz = саураштра
language-name-sba = нгембеј
language-name-sbp = сангу
language-name-sc = сардински
language-name-scn = сицилијански
language-name-sco = шкотски германски
language-name-sd = синди
language-name-sdc = сасарски сардински
language-name-sdh = јужнокурдски
language-name-se = северен сами
language-name-see = сенека
language-name-seh = сена
language-name-sei = сери
language-name-sel = селкупски
language-name-ses = којраборо сени
language-name-sg = санго
language-name-sga = староирски
language-name-sgs = самогитски
language-name-sh = српскохрватски
language-name-shi = тачелхит
language-name-shn = шан
language-name-shu = чадски арапски
language-name-si = синхалски
language-name-sid = сидамо
language-name-sk = словачки
language-name-sl = словенечки
language-name-sli = долношлезиски
language-name-sly = селајарски
language-name-sm = самоански
language-name-sma = јужен сами
language-name-smj = луле сами
language-name-smn = инари сами
language-name-sms = сколт сами
language-name-sn = шона
language-name-snk = сонинке
language-name-so = сомалиски
language-name-sog = зогдијански
language-name-sq = албански
language-name-sr = српски
language-name-srn = срански тонго
language-name-srr = серер
language-name-ss = свати
language-name-ssy = сахо
language-name-st = сесото
language-name-stq = затерландски фризиски
language-name-su = сундски
language-name-suk = сукума
language-name-sus = сусу
language-name-sux = сумерски
language-name-sv = шведски
language-name-sw = свахили
language-name-sw_CD = конгоански свахили
language-name-swb = коморијански
language-name-syc = класичен сириски
language-name-syr = сириски
language-name-szl = шлезиски
language-name-ta = тамилски
language-name-tcy = тулу
language-name-te = телугу
language-name-tem = тимне
language-name-teo = тесо
language-name-ter = терено
language-name-tet = тетум
language-name-tg = таџикистански
language-name-th = тајландски
language-name-ti = тигриња
language-name-tig = тигре
language-name-tiv = тив
language-name-tk = туркменски
language-name-tkl = токелауански
language-name-tkr = цахурски
language-name-tl = тагалог
language-name-tlh = клингонски
language-name-tli = тлингит
language-name-tly = талишки
language-name-tmh = тамашек
language-name-tn = цвана
language-name-to = тонгајски
language-name-tog = њаса тонга
language-name-tpi = ток писин
language-name-tr = турски
language-name-tru = туројо
language-name-trv = тароко
language-name-ts = цонга
language-name-tsd = цаконски
language-name-tsi = цимшијански
language-name-tt = татарски
language-name-ttt = татски
language-name-tum = тумбука
language-name-tvl = тувалуански
language-name-tw = тви
language-name-twq = тазавак
language-name-ty = тахитски
language-name-tyv = тувански
language-name-tzm = централноатлански тамазитски
language-name-udm = удмуртски
language-name-ug = ујгурски
language-name-uga = угаритски
language-name-uk = украински
language-name-umb = умбунду
language-name-und = непознат јазик
language-name-ur = урду
language-name-uz = узбечки
language-name-vai = вај
language-name-ve = венда
language-name-vec = венетски
language-name-vep = вепшки
language-name-vi = виетнамски
language-name-vls = западнофламански
language-name-vmf = мајнскофранконски
language-name-vo = волапик
language-name-vot = вотски
language-name-vro = виру
language-name-vun = вунџо
language-name-wa = валонски
language-name-wae = валсер
language-name-wal = воламо
language-name-war = варајски
language-name-was = вашо
language-name-wbp = варлпири
language-name-wo = волофски
language-name-wuu = ву
language-name-xal = калмички
language-name-xh = коса
language-name-xmf = мегрелски
language-name-xog = сога
language-name-yao = јао
language-name-yap = јапски
language-name-yav = јенгбен
language-name-ybb = јемба
language-name-yi = јидиш
language-name-yo = јорупски
language-name-yrl = њенгату
language-name-yue = кантонски
language-name-za = џуаншки
language-name-zap = запотечки
language-name-zbl = блиссимболи
language-name-zea = зеландски
language-name-zen = зенага
language-name-zgh = стандарден марокански тамазитски
language-name-zh = кинески
language-name-zh_Hans = поедноставен кинески
language-name-zh_Hant = традиционален кинески
language-name-zu = зулу
language-name-zun = зуни
language-name-zxx = без лингвистичка содржина
language-name-zza = заза
