language-name-aa = afaršćina
language-name-ab = abchazšćina
language-name-af = afrikans
language-name-agq = aghem
language-name-ak = akanšćina
language-name-am = amharšćina
language-name-an = aragonšćina
language-name-ang = anglosaksojšćina
language-name-ar = arabšćina
language-name-ar_001 = moderna wusokoarabšćina
language-name-arn = arawkašćina
language-name-as = asamšćina
language-name-asa = pare
language-name-ast = asturšćina
language-name-av = awaršćina
language-name-ay = aymaršćina
language-name-az = azerbajdžanšćina
language-name-ba = baškiršćina
language-name-be = běłorušćina
language-name-bem = bemba
language-name-bez = bena
language-name-bg = bulgaršćina
language-name-bi = bislamšćina
language-name-bm = bambara
language-name-bn = bengalšćina
language-name-bo = tibetšćina
language-name-br = bretonšćina
language-name-brx = bodo
language-name-bs = bosnišćina
language-name-bug = bugišćina
language-name-ca = katanlanšćina
language-name-cgg = chiga
language-name-ch = čamoršćina
language-name-cho = choctawšćina
language-name-chr = cherokee
language-name-ckb = sorani
language-name-co = korsišćina
language-name-cr = kri
language-name-cs = češćina
language-name-cy = walizišćina
language-name-da = danšćina
language-name-dav = taita
language-name-de = nimšćina
language-name-de_AT = awstriska nimšćina
language-name-de_CH = šwicarska wusokonimšćina
language-name-dje = zarma
language-name-dsb = dolnoserbšćina
language-name-dua = duala
language-name-dv = divehi
language-name-dyo = jola-fonyi
language-name-dz = dzongkha
language-name-ebu = embu
language-name-ee = ewe
language-name-el = grichišćina
language-name-en = engelšćina
language-name-en_AU = awstralska engelšćina
language-name-en_CA = kanadiska engelšćina
language-name-en_GB = britiska engelšćina
language-name-en_US = ameriska engelšćina
language-name-eo = esperanto
language-name-es = špańšćina
language-name-es_419 = łatyńskoamerikańska špańšćina
language-name-es_ES = europejska špańšćina
language-name-es_MX = mexikańska špańšćina
language-name-et = estišćina
language-name-eu = baskišćina
language-name-fa = persišćina
language-name-fi = finšćina
language-name-fil = filipinšćina
language-name-fj = fidžišćina
language-name-fo = ferejšćina
language-name-fr = francojšćina
language-name-fr_CA = kanadiska francojšćina
language-name-fr_CH = šwicarska francojšćina
language-name-fy = frizišćina
language-name-ga = iršćina
language-name-gag = gagauzšćina
language-name-gd = šotišćina
language-name-gl = galicišćina
language-name-gn = guarani
language-name-got = gotišćina
language-name-gsw = šwicarska nimšćina
language-name-gu = gudžaratšćina
language-name-guz = gusii
language-name-gv = manšćina
language-name-ha = hausa
language-name-haw = hawaiišćina
language-name-he = hebrejšćina
language-name-hi = hindišćina
language-name-hr = chorwatšćina
language-name-hsb = górnoserbšćina
language-name-ht = haitišćina
language-name-hu = hungoršćina
language-name-hy = armeńšćina
language-name-ia = interlingua
language-name-id = indonešćina
language-name-ig = igbo
language-name-ii = sichuan yi
language-name-ik = inupiak
language-name-io = ido
language-name-is = islandšćina
language-name-it = italšćina
language-name-iu = inuitšćina
language-name-ja = japańšćina
language-name-jgo = ngomba
language-name-jmc = machame
language-name-jv = javašćina
language-name-ka = georgišćina
language-name-kab = kabylšćina
language-name-kam = kamba
language-name-kde = makonde
language-name-kea = kapverdšćina
language-name-khq = koyra chiini
language-name-ki = kikuyu
language-name-kk = kazachšćina
language-name-kl = grönlandšćina
language-name-kln = kalenjin
language-name-km = kambodžanšćina
language-name-kn = kannadšćina
language-name-ko = korejańšćina
language-name-koi = komi-permyak
language-name-kok = konkani
language-name-ks = kašmiršćina
language-name-ksb = šambala
language-name-ksf = bafia
language-name-ku = kurdišćina
language-name-kw = kornišćina
language-name-ky = kirgišćina
language-name-la = łatyńšćina
language-name-lag = langi
language-name-lb = luxemburgšćina
language-name-lg = gandšćina
language-name-li = limburšćina
language-name-lkt = lakotšćina
language-name-ln = lingala
language-name-lo = laošćina
language-name-lt = litawšćina
language-name-lu = luba-katanga
language-name-luo = luo
language-name-luy = luhya
language-name-lv = letišćina
language-name-mas = masaišćina
language-name-mer = meru
language-name-mfe = mauriciska kreolšćina
language-name-mg = malgašćina
language-name-mgh = makhuwa-meetto
language-name-mgo = meta’
language-name-mi = maorišćina
language-name-mk = makedońšćina
language-name-ml = malajamšćina
language-name-mn = mongolšćina
language-name-moh = mohawkšćina
language-name-mr = maratišćina
language-name-ms = malajšćina
language-name-mt = maltašćina
language-name-mua = mundang
language-name-mus = krik
language-name-my = burmašćina
language-name-na = naurušćina
language-name-naq = nama
language-name-nb = norwegske bokmål
language-name-nd = pódpołnocne ndebele
language-name-nds = dolnonimšćina
language-name-ne = nepalšćina
language-name-nl = nižozemšćina
language-name-nl_BE = flamšćina
language-name-nmg = kwasio
language-name-nn = norwegske nynorsk
language-name-no = norwegšćina
language-name-nqo = n’ko
language-name-nus = nuer
language-name-nv = navaho
language-name-nyn = nyankole
language-name-oc = okcitanšćina
language-name-om = oromo
language-name-or = orojišćina
language-name-pa = pandžabšćina
language-name-pl = pólšćina
language-name-prg = prusčina
language-name-ps = paštunšćina
language-name-pt = portugalšćina
language-name-pt_BR = brazilska portugalšćina
language-name-pt_PT = europejska portugalšćina
language-name-qu = kečua
language-name-quc = kʼicheʼ
language-name-rm = retoromańšćina
language-name-rn = kirundišćina
language-name-ro = rumunšćina
language-name-ro_MD = moldawišćina
language-name-rof = rombo
language-name-ru = rušćina
language-name-rw = kinjarwanda
language-name-rwk = rwa
language-name-sa = sanskrit
language-name-saq = samburu
language-name-sbp = sangu
language-name-sc = sardinšćina
language-name-scn = sicilianišćina
language-name-sd = sindšćina
language-name-se = lapšćina
language-name-seh = sena
language-name-ses = koyra senni
language-name-sg = sango
language-name-sh = serbochorwatšćina
language-name-shi = tašelhit
language-name-si = singalšćina
language-name-sk = słowakšćina
language-name-sl = słowjeńšćina
language-name-sm = samošćina
language-name-sma = pódpołdnjowa samišćina
language-name-smj = lule-samišćina
language-name-smn = inari-samišćina
language-name-sms = skolt-samišćina
language-name-sn = šonšćina
language-name-so = somališćina
language-name-sq = albanšćina
language-name-sr = serbišćina
language-name-ss = siswati
language-name-stq = saterfrizišćina
language-name-su = sundanšćina
language-name-sv = šwedšćina
language-name-sw = swahilišćina
language-name-sw_CD = kongojska swahilišćina
language-name-ta = tamilšćina
language-name-te = telugšćina
language-name-teo = teso
language-name-tg = tadžikišćina
language-name-th = thailandšćina
language-name-ti = tigrinja
language-name-tk = turkmeńšćina
language-name-tl = tagalog
language-name-tn = tswana
language-name-to = tonganšćina
language-name-tr = turkojšćina
language-name-ts = tsonga
language-name-tt = tataršćina
language-name-tw = twi
language-name-twq = tasawaq
language-name-ty = tahitišćina
language-name-tzm = centralnoatlaski tamazight
language-name-ug = ujguršćina
language-name-uk = ukrainšćina
language-name-und = njeznata rěc
language-name-ur = urdušćina
language-name-uz = usbekšćina
language-name-vai = vai
language-name-vi = vietnamšćina
language-name-vo = volapük
language-name-vun = vunjo
language-name-wa = walonšćina
language-name-wo = wolof
language-name-xh = xhosa
language-name-xog = soga
language-name-yi = jidišćina
language-name-yo = jorubšćina
language-name-za = zhuang
language-name-zgh = standardny marokkański tamazight
language-name-zh = chinšćina
language-name-zu = zulu
language-name-zxx = žedno rěcne wopśimjeśe
