language-name-aa = ئافارچە
language-name-ab = ئابخازچە
language-name-ace = ئاتجېچە
language-name-ach = ئاچولىچە
language-name-ada = ئاداڭمېچە
language-name-ady = ئادىگېيچە
language-name-ae = ئاۋېستاچە
language-name-af = ئافرىكانچە
language-name-afh = ئافرىخىلىچە
language-name-agq = ئاگەمچە
language-name-ain = ئاينۇچە
language-name-ak = ئاكانچە
language-name-akk = ئاككادچە
language-name-ale = ئالېيۇتچە
language-name-alt = جەنۇبى ئالتاي تىللىرى
language-name-am = ئامھارچە
language-name-an = ئاراگونچە
language-name-ang = قەدىمكى ئىنگلىزچە
language-name-anp = ئانگىكاچە
language-name-ar = ئەرەبچە
language-name-ar_001 = ھازىرقى زامان ئۆلچەملىك ئەرەبچە
language-name-arc = ئارامۇچە
language-name-arn = ماپۇدۇنگۇنچە
language-name-arp = ئاراپاخوچە
language-name-arw = ئاراۋاكچە
language-name-as = ئاسامچە
language-name-asa = ئاسۇچە
language-name-ast = ئاستۇرىيەچە
language-name-av = ئاۋارچە
language-name-awa = ئاۋادىچە
language-name-ay = ئايماراچە
language-name-az = ئەزەربەيجانچە
language-name-ba = باشقىرتچە
language-name-bal = بېلۇجىچە
language-name-ban = بالىچە
language-name-bas = باساچە
language-name-bax = بامۇنچە
language-name-bbj = گومالاچە
language-name-be = بېلارۇسچە
language-name-bej = بېجاچە
language-name-bem = بېمباچە
language-name-bez = بېناچە
language-name-bfd = بافۇتچە
language-name-bg = بۇلغارچە
language-name-bho = بوجپۇرىچە
language-name-bi = بىسلاماچە
language-name-bik = بىكولچە
language-name-bin = بىنىچە
language-name-bkm = كومچە
language-name-bla = سىكسىكاچە
language-name-bm = بامباراچە
language-name-bn = بېنگالچە
language-name-bo = تىبەتچە
language-name-br = بىرېتونچە
language-name-bra = بىراجچە
language-name-brx = بودوچە
language-name-bs = بوسىنچە
language-name-bss = ئاكۇسچە
language-name-bua = بۇرىياتچە
language-name-bug = بۇگىچە
language-name-bum = بۇلۇچە
language-name-byn = بىلىنچە
language-name-byv = مېدۇمباچە
language-name-ca = كاتالانچە
language-name-cad = كاددوچە
language-name-car = كارىبچە
language-name-cay = كايۇگاچە
language-name-cch = ئاتسامچە
language-name-ce = چېچىنچە
language-name-ceb = سېبۇچە
language-name-cgg = چىگاچە
language-name-ch = چامورروچە
language-name-chb = چىبچاچە
language-name-chg = چاغاتايچە
language-name-chk = چۇكچە
language-name-chm = مارىچە
language-name-chn = چىنۇك-ژارگونچە
language-name-cho = چوكتاۋچە
language-name-chp = چىپېۋيانچە
language-name-chr = چېروكىچە
language-name-chy = چېيېنچە
language-name-ckb = مەركىزىي كۇردچە
language-name-co = كورسۇچە
language-name-cop = كوپتىكچە
language-name-cr = كرىچە
language-name-crh = قىرىم تۈركچە
language-name-cs = چېخچە
language-name-csb = كاسزۇبىچە
language-name-cu = قەدىمكى سلاۋيانچە
language-name-cv = چۇۋاشچە
language-name-cy = ۋېلشچە
language-name-da = دانىشچە
language-name-dak = داكوتاچە
language-name-dar = دارگىۋاچە
language-name-dav = تايتاچە
language-name-de = گېرمانچە
language-name-de_AT = ئاۋستىرىيە گېرمانچە
language-name-de_CH = شىۋىتسارىيە ئېگىزلىك گېرمانچە
language-name-del = دېلاۋارېچە
language-name-den = سلاۋچە
language-name-dgr = دوگرىبچە
language-name-din = دىنكاچە
language-name-dje = زارماچە
language-name-doi = دوگرىچە
language-name-dsb = تۆۋەن سوربچە
language-name-dua = دۇئالاچە
language-name-dum = ئوتتۇرا گوللاندىيەچە
language-name-dv = دىۋېخچە
language-name-dyo = جولاچە
language-name-dyu = دىيۇلاچە
language-name-dz = زوڭخاچە
language-name-dzg = دازاگاچە
language-name-ebu = ئېمبۇچە
language-name-ee = ئېۋېچە
language-name-efi = ئېفىكچە
language-name-egy = قەدىمكى مىسىرچە
language-name-eka = ئېكاجۇكچە
language-name-el = گىرېكچە
language-name-elx = ئېلامىتچە
language-name-en = ئىنگلىزچە
language-name-en_AU = ئاۋسترالىيە ئىنگلىزچە
language-name-en_CA = كانادا ئىنگلىزچە
language-name-en_GB = ئەنگلىيە ئىنگلىزچە
language-name-en_US = ئامېرىكا ئىنگلىزچە
language-name-enm = ئوتتۇرا ئەسىر ئىنگلىزچە
language-name-eo = ئېسپرانتوچە
language-name-es = ئىسپانچە
language-name-es_419 = لاتىن ئامېرىكا ئىسپانچە
language-name-es_ES = ياۋروپا ئىسپانچە
language-name-es_MX = مېكسىكا ئىسپانچە
language-name-et = ئېستونچە
language-name-eu = باسكىچە
language-name-ewo = ئېۋوندوچە
language-name-fa = پارسچە
language-name-fan = فاڭچە
language-name-fat = فانتىچە
language-name-ff = فۇلاھچە
language-name-fi = فىنچە
language-name-fil = فىلىپپىنچە
language-name-fj = فىجىچە
language-name-fo = فائېروچە
language-name-fon = فونچە
language-name-fr = فىرانسۇزچە
language-name-fr_CA = كانادا فىرانسۇزچە
language-name-fr_CH = شىۋىتسارىيە فىرانسۇزچە
language-name-frm = ئوتتۇرا ئەسىر فىرانسۇزچە
language-name-fro = قەدىمكى فىرانسۇزچە
language-name-frr = شىمالى فىرىزيەچە
language-name-frs = شەرقى فىرىزيەچە
language-name-fur = فىرىئۇلىچە
language-name-fy = غەربىي فىرسچە
language-name-ga = ئىرېلاندچە
language-name-gaa = گاچە
language-name-gay = گايوچە
language-name-gba = گىباياچە
language-name-gd = شوتلاندىيە گايلچىسى
language-name-gez = گىزچە
language-name-gil = گىلبېرتچە
language-name-gl = گالىچە
language-name-gmh = ئوتتۇرا ئەسىر ئېگىزلىك گېرمانچە
language-name-gn = گۇئارانىچە
language-name-goh = قەدىمكى ئېگىزلىك گېرمانچە
language-name-gon = گوندىچە
language-name-gor = گورونتالوچە
language-name-got = گوتچە
language-name-grb = گرېبوچە
language-name-grc = قەدىمكى گىرېكچە
language-name-gsw = گېرمانچە شىۋىتسارىيە
language-name-gu = گۇجاراتچە
language-name-guz = گۇسىچە
language-name-gv = مانچە
language-name-gwi = گىۋىچىنچە
language-name-ha = خائۇساچە
language-name-hai = ھەيدەچە
language-name-haw = ھاۋايچە
language-name-he = ئىبرانىيچە
language-name-hi = ھىندىچە
language-name-hil = خىلىگاينونچە
language-name-hit = خىتتىتچە
language-name-hmn = مۆڭچە
language-name-ho = ھىرى موتۇچە
language-name-hr = كىرودىچە
language-name-hsb = ئۈستۈن سوربچە
language-name-ht = ھايتىچە
language-name-hu = ۋېنگىرچە
language-name-hup = خۇپاچە
language-name-hy = ئەرمېنچە
language-name-hz = خېرېروچە
language-name-ia = ئارىلىق تىل
language-name-iba = ئىبانچە
language-name-ibb = ئىبىبىئوچە
language-name-id = ھىندونېزچە
language-name-ie = ئىنتىرلىڭچە
language-name-ig = ئىگبوچە
language-name-ik = ئىنۇپىكچە
language-name-ilo = ئىلوكانوچە
language-name-inh = ئىنگۇشچە
language-name-io = ئىدوچە
language-name-is = ئىسلاندچە
language-name-it = ئىتالىيانچە
language-name-iu = ئىنۇكتىتۇتچە
language-name-ja = ياپونچە
language-name-jbo = لوجبانچە
language-name-jgo = نگومباچە
language-name-jmc = ماچامچە
language-name-jpr = ئىبرانى پارسچە
language-name-jrb = ئىبرانى ئەرەبچە
language-name-jv = ياۋاچە
language-name-ka = گىرۇزچە
language-name-kaa = قارا-قالپاقچە
language-name-kab = كابىلېچە
language-name-kac = كاچىنچە
language-name-kaj = جۇچە
language-name-kam = كامباچە
language-name-kaw = كاۋىچە
language-name-kbd = كاباردەيچە
language-name-kbl = كانېمبۇچە
language-name-kcg = تياپچە
language-name-kde = ماكوندېچە
language-name-kea = كابۇۋېردىيانچە
language-name-kfo = كوروچە
language-name-kg = كونگوچە
language-name-kha = كاسىچە
language-name-kho = خوتەنچە
language-name-khq = كويرا چىنىچە
language-name-ki = كىكۇيۇچە
language-name-kj = كىۋانياماچە
language-name-kk = قازاقچە
language-name-kkj = كاكوچە
language-name-kl = گىرېنلاندچە
language-name-kln = كالېنجىنچە
language-name-km = كىمېرچە
language-name-kmb = كىمبۇندۇچە
language-name-kn = كانناداچە
language-name-ko = كورېيەچە
language-name-kok = كونكانچە
language-name-kos = كوسرايېچە
language-name-kpe = كىپەللېچە
language-name-kr = كانۇرچە
language-name-krc = قاراچاي-بالقارچە
language-name-krl = كارەلچە
language-name-kru = كۇرۇخچە
language-name-ks = كەشمىرچە
language-name-ksb = شامبالاچە
language-name-ksf = بافىياچە
language-name-ksh = كولىشچە
language-name-ku = كۇردچە
language-name-kum = قۇمۇقچە
language-name-kut = كۇتەنايچە
language-name-kv = كومىچە
language-name-kw = كورنىشچە
language-name-ky = قىرغىزچە
language-name-la = لاتىنچە
language-name-lad = لادىنوچە
language-name-lag = لانگىچە
language-name-lah = لانداچە
language-name-lam = لامباچە
language-name-lb = لىيۇكسېمبۇرگچە
language-name-lez = لېزگىنچە
language-name-lg = گانداچە
language-name-li = لىمبۇرگچە
language-name-ln = لىنگالاچە
language-name-lo = لائوسچە
language-name-lol = مونگوچە
language-name-loz = لوزىچە
language-name-lt = لىتۋانىچە
language-name-lu = لۇبا-كاتانگاچە
language-name-lua = لۇبا-لۇئاچە
language-name-lui = لۇيسېنگوچە
language-name-lun = لۇنداچە
language-name-luo = لۇئوچە
language-name-lus = مىزوچە
language-name-luy = لۇياچە
language-name-lv = لاتچە
language-name-mad = مادۇرېسچە
language-name-maf = مافاچە
language-name-mag = ماگاخىچە
language-name-mai = مايتىلىچە
language-name-mak = ماكاسارچە
language-name-man = ماندىنگوچە
language-name-mas = ماسايچە
language-name-mde = ماباچە
language-name-mdf = موكشاچە
language-name-mdr = ماندارچە
language-name-men = مېندېچە
language-name-mer = مېرۇچە
language-name-mfe = مورىسيېنچە
language-name-mg = مالاگاسچە
language-name-mga = ئوتتۇرا ئەسىر ئىرېلاندچە
language-name-mgh = ماكۇۋاچە
language-name-mgo = مېتاچە’
language-name-mh = مارشالچە
language-name-mi = ماۋرىچە
language-name-mic = مىكماكچە
language-name-min = مىناڭكابائۇچە
language-name-mk = ماكېدونچە
language-name-ml = مالايالامچە
language-name-mn = موڭغۇلچە
language-name-mnc = مانجۇچە
language-name-mni = مانىپۇرچە
language-name-moh = موخاۋكچە
language-name-mos = موسسىچە
language-name-mr = ماراتىچە
language-name-ms = مالايچە
language-name-mt = مالتاچە
language-name-mua = مۇنداڭچە
language-name-mul = كۆپ تىللار
language-name-mus = كىرىكچە
language-name-mwl = مىراندېسچە
language-name-mwr = مارۋارىچە
language-name-my = بىرماچە
language-name-mye = ميېنېچە
language-name-myv = ئېرزاچە
language-name-na = ناۋرۇچە
language-name-nap = ناپولىچە
language-name-naq = ناماچە
language-name-nb = نورۋىگىيە بوكمالچە
language-name-nd = شىمالى ندەبەلەچە
language-name-nds = تۆۋەن گېرمانچە
language-name-ne = نېپالچە
language-name-new = نېۋارىچە
language-name-ng = ندونگاچە
language-name-nia = نىئاسچە
language-name-niu = نيۇئېچە
language-name-nl = گوللاندچە
language-name-nmg = كۋاسىيوچە
language-name-nn = يېڭى نورۋېگچە
language-name-nnh = نگېمبۇنچە
language-name-no = نورۋېگچە
language-name-nog = نوغايچە
language-name-non = قەدىمكى نورۋېگچە
language-name-nqo = نىكوچە
language-name-nr = جەنۇبى ندەبەلەچە
language-name-nso = شىمالىي سوتوچە
language-name-nus = مۇئېرچە
language-name-nv = ناۋاخوچە
language-name-nwc = نېۋارچە
language-name-ny = نىيانجاچە
language-name-nym = نيامۋېزىچە
language-name-nyn = نىيانكولېچە
language-name-nyo = نىئوروچە
language-name-nzi = نىزەماچە
language-name-oc = ئوكسىتچە
language-name-oj = ئوجىبۋاچە
language-name-om = ئوروموچە
language-name-or = ئودىياچە
language-name-os = ئوسسېتچەچە
language-name-osa = ئوساگېلارچە
language-name-ota = ئوسمان تۈركچە
language-name-pa = پەنجابچە
language-name-pag = پانگاسىنانچە
language-name-pal = پەھلەۋىچە
language-name-pam = پامپانگاچە
language-name-pap = پاپىيامېنتوچە
language-name-pau = پالاۋچە
language-name-peo = قەدىمكى پارىسچە
language-name-phn = فىنىكىيەچە
language-name-pi = پالىچە
language-name-pl = پولەكچە
language-name-pon = پوناپېئانچە
language-name-pro = قەدىمكى پروۋېنچالچە
language-name-ps = پۇشتۇچە
language-name-pt = پورتۇگالچە
language-name-pt_BR = بىرازىلىيە پورتۇگالچە
language-name-pt_PT = ياۋروپا پورتۇگالچە
language-name-qu = كېچىۋاچە
language-name-raj = راجاستانچە
language-name-rap = راپانىيچە
language-name-rm = رومانسچە
language-name-rn = رۇندىچە
language-name-ro = رومىنچە
language-name-rof = رومبوچە
language-name-rom = سىگانچە
language-name-root = غول تىل
language-name-ru = رۇسچە
language-name-rup = ئارومانچە
language-name-rw = كېنىيەرىۋانداچە
language-name-rwk = رىۋاچە
language-name-sa = سانسكرىتچە
language-name-sad = سانداۋېچە
language-name-sah = ساخاچە
language-name-sam = سامارىتانچە
language-name-saq = سامبۇرۇچە
language-name-sas = ساساكچە
language-name-sat = سانتالچە
language-name-sba = نگامبايچە
language-name-sbp = سانگۇچە
language-name-sc = ساردىنىيەچە
language-name-scn = سىتسىلىيەچە
language-name-sco = شوتلاندىيەچە
language-name-sd = سىندىچە
language-name-se = شىمالىي سامىچە
language-name-see = سېكنېكاچە
language-name-seh = سېناچە
language-name-sel = سېلكاپچە
language-name-ses = شەرقىي سوڭخايچە
language-name-sg = سانگوچە
language-name-sga = قەدىمكى ئىرېلاندچە
language-name-sh = سېرب-كرودىيەچە
language-name-shi = شىلخاچە
language-name-shn = شانچە
language-name-shu = چاد ئەرەبچە
language-name-si = سىنگالچە
language-name-sid = سىداموچە
language-name-sk = سىلوۋاكچە
language-name-sl = سىلوۋېنچە
language-name-sm = ساموئاچە
language-name-sma = جەنۇبىي سامىچە
language-name-smj = لۇلې سامىچە
language-name-smn = ئىنارى سامىچە
language-name-sms = سكولت سامىچە
language-name-sn = شوناچە
language-name-snk = سونىنكەچە
language-name-so = سومالىچە
language-name-sog = سوغدىچە
language-name-sq = ئالبانچە
language-name-sr = سېربچە
language-name-srn = سىرانان-توڭوچە
language-name-srr = سېرېرچە
language-name-ss = سىۋاتىچە
language-name-ssy = ساخوچە
language-name-st = سوتوچە
language-name-su = سۇنداچە
language-name-suk = سۇكۇماچە
language-name-sus = سۇسۇچە
language-name-sux = سۈمەرچە
language-name-sv = شىۋېدچە
language-name-sw = سىۋاھىلچە
language-name-sw_CD = كونگو سىۋالىچە
language-name-swb = كومورىچە
language-name-syc = قەدىمىي سۇرىيەچە
language-name-syr = سۇرىيەچە
language-name-ta = تامىلچە
language-name-te = تېلۇگۇچە
language-name-tem = تېمنېچە
language-name-teo = تېسوچە
language-name-ter = تېرېناچە
language-name-tet = تېتۇمچە
language-name-tg = تاجىكچە
language-name-th = تايلاندچە
language-name-ti = تىگرىنياچە
language-name-tig = تىگرېچە
language-name-tiv = تىۋچە
language-name-tk = تۈركمەنچە
language-name-tkl = توكېلاۋچە
language-name-tl = تاگالوگچە
language-name-tlh = كىلىنگونچە
language-name-tli = تىلىنگىتچە
language-name-tmh = تاماشېكچە
language-name-tn = سىۋاناچە
language-name-to = تونگانچە
language-name-tog = نياسا توڭانچە
language-name-tpi = توك-پىسىنچە
language-name-tr = تۈركچە
language-name-trv = توروكوچە
language-name-ts = سونگاچە
language-name-tsi = سىمشيانچە
language-name-tt = تاتارچە
language-name-tum = تۇمبۇكاچە
language-name-tvl = تۇۋالۇچە
language-name-tw = تىۋىچە
language-name-twq = شىمالىي سوڭخايچە
language-name-ty = تاختىچە
language-name-tyv = توۋاچە
language-name-tzm = مەركىزىي ئاتلاس تامازايتچە
language-name-udm = ئۇدمۇرتچە
language-name-ug = ئۇيغۇرچە
language-name-uga = ئۇگارىتىكچە
language-name-uk = ئۇكرائىنچە
language-name-umb = ئۇمبۇندۇچە
language-name-und = يوچۇن تىل
language-name-ur = ئوردۇچە
language-name-uz = ئۆزبېكچە
language-name-vai = ۋايچە
language-name-ve = ۋېنداچە
language-name-vi = ۋىيېتنامچە
language-name-vo = ۋولاپۇكچە
language-name-vot = ۋوتېچە
language-name-vun = ۋۇنجوچە
language-name-wa = ۋاللۇنچە
language-name-wae = ۋالسېرچە
language-name-wal = ۋولايتاچە
language-name-war = ۋارايچە
language-name-was = ۋاشوچە
language-name-wo = ۋولوفچە
language-name-xal = قالماقچە
language-name-xh = خوساچە
language-name-xog = سوگاچە
language-name-yao = ياۋچە
language-name-yap = ياپچە
language-name-yav = ياڭبەنچە
language-name-ybb = يېمباچە
language-name-yi = يىددىشچە
language-name-yo = يورۇباچە
language-name-yue = گۇاڭدوڭچە
language-name-za = جۇاڭچە
language-name-zap = زاپوتېكچە
language-name-zbl = بىلىس بەلگىلىرى
language-name-zen = زېناگاچە
language-name-zgh = ئۆلچەملىك ماراكەش تامازىتچە
language-name-zh = خەنزۇچە
language-name-zh_Hans = ئاددىي خەنچە
language-name-zh_Hant = مۇرەككەپ خەنچە
language-name-zu = زۇلۇچە
language-name-zun = زۇنىچە
language-name-zxx = تىل مەزمۇنى يوق
language-name-zza = زازاچە
