language-name-aa = afar
language-name-ab = abchasian
language-name-ace = aceh
language-name-ach = acoli
language-name-ada = andangme
language-name-ady = adygai
language-name-ae = avestic
language-name-af = afrikaans
language-name-afh = afrihili
language-name-ain = ainu
language-name-ak = akan
language-name-akk = accadic
language-name-ale = aleutic
language-name-alt = altaic dal sid
language-name-am = amaric
language-name-an = aragonais
language-name-ang = englais vegl
language-name-anp = angika
language-name-ar = arab
language-name-arc = arameic
language-name-arn = araucanic
language-name-arp = arapaho
language-name-arw = arawak
language-name-as = assami
language-name-ast = asturian
language-name-av = avaric
language-name-awa = awadhi
language-name-ay = aymara
language-name-az = aserbeidschanic
language-name-ba = baschkir
language-name-bal = belutschi
language-name-ban = balinais
language-name-bas = basaa
language-name-be = bieloruss
language-name-bej = bedscha
language-name-bem = bemba
language-name-bg = bulgar
language-name-bho = bhojpuri
language-name-bi = bislama
language-name-bik = bikol
language-name-bin = bini
language-name-bla = siksika
language-name-bm = bambara
language-name-bn = bengal
language-name-bo = tibetan
language-name-br = breton
language-name-bra = braj
language-name-bs = bosniac
language-name-bua = buriat
language-name-bug = bugi
language-name-byn = blin
language-name-ca = catalan
language-name-cad = caddo
language-name-car = caribic
language-name-cch = atsam
language-name-ce = tschetschen
language-name-ceb = cebuano
language-name-ch = chamorro
language-name-chb = chibcha
language-name-chg = tschagataic
language-name-chk = chuukais
language-name-chm = mari
language-name-chn = patuà chinook
language-name-cho = choctaw
language-name-chp = chipewyan
language-name-chr = cherokee
language-name-chy = cheyenne
language-name-co = cors
language-name-cop = coptic
language-name-cr = cree
language-name-crh = tirc crimean
language-name-cs = tschec
language-name-csb = kaschubic
language-name-cu = slav da baselgia
language-name-cv = tschuvasch
language-name-cy = kimric
language-name-da = danais
language-name-dak = dakota
language-name-dar = dargwa
language-name-de = tudestg
language-name-de_AT = tudestg austriac
language-name-del = delaware
language-name-den = slavey
language-name-dgr = dogrib
language-name-din = dinka
language-name-doi = dogri
language-name-dsb = bass sorb
language-name-dua = duala
language-name-dum = ollandais mesaun
language-name-dv = maledivic
language-name-dyu = diula
language-name-dz = dzongkha
language-name-ee = ewe
language-name-efi = efik
language-name-egy = egipzian vegl
language-name-eka = ekajuk
language-name-el = grec
language-name-elx = elamitic
language-name-en = englais
language-name-en_AU = englais australian
language-name-en_CA = englais canadais
language-name-en_GB = englais britannic
language-name-en_US = englais american
language-name-enm = englais mesaun
language-name-eo = esperanto
language-name-es = spagnol
language-name-es_419 = spagnol latinamerican
language-name-es_ES = spagnol iberic
language-name-et = eston
language-name-eu = basc
language-name-ewo = ewondo
language-name-fa = persian
language-name-fan = fang
language-name-fat = fanti
language-name-ff = fulah
language-name-fi = finlandais
language-name-fil = filippino
language-name-fj = fidschian
language-name-fo = ferrais
language-name-fon = fon
language-name-fr = franzos
language-name-fr_CA = franzos canadais
language-name-fr_CH = franzos svizzer
language-name-frm = franzos mesaun
language-name-fro = franzos vegl
language-name-frr = fris dal nord
language-name-frs = fris da l’ost
language-name-fur = friulan
language-name-fy = fris
language-name-ga = irlandais
language-name-gaa = ga
language-name-gay = gayo
language-name-gba = gbaya
language-name-gd = gaelic scot
language-name-gez = geez
language-name-gil = gilbertais
language-name-gl = galician
language-name-gmh = tudestg mesaun
language-name-gn = guarani
language-name-goh = vegl tudestg da scrittira
language-name-gon = gondi
language-name-gor = gorontalo
language-name-got = gotic
language-name-grb = grebo
language-name-grc = grec vegl
language-name-gsw = tudestg svizzer
language-name-gu = gujarati
language-name-gv = manx
language-name-gwi = gwichʼin
language-name-ha = haussa
language-name-hai = haida
language-name-haw = hawaian
language-name-he = ebraic
language-name-hi = hindi
language-name-hil = hiligaynon
language-name-hit = ettitic
language-name-hmn = hmong
language-name-ho = hiri motu
language-name-hr = croat
language-name-hsb = aut sorb
language-name-ht = haitian
language-name-hu = ungarais
language-name-hup = hupa
language-name-hy = armen
language-name-hz = herero
language-name-ia = interlingua
language-name-iba = iban
language-name-id = indonais
language-name-ie = interlingue
language-name-ig = igbo
language-name-ii = sichuan yi
language-name-ik = inupiak
language-name-ilo = ilocano
language-name-inh = ingush
language-name-io = ido
language-name-is = islandais
language-name-it = talian
language-name-iu = inuktitut
language-name-ja = giapunais
language-name-jbo = lojban
language-name-jpr = giudaic-persian
language-name-jrb = giudaic-arab
language-name-jv = javanais
language-name-ka = georgian
language-name-kaa = karakalpak
language-name-kab = kabyle
language-name-kac = kachin
language-name-kaj = jju
language-name-kam = kamba
language-name-kaw = kawi
language-name-kbd = kabardic
language-name-kcg = tyap
language-name-kfo = koro
language-name-kg = kongo
language-name-kha = khasi
language-name-kho = khotanais
language-name-ki = kikuyu
language-name-kj = kuanyama
language-name-kk = casac
language-name-kl = grönlandais
language-name-km = cambodschan
language-name-kmb = kimbundu
language-name-kn = kannada
language-name-ko = corean
language-name-kok = konkani
language-name-kos = kosraean
language-name-kpe = kpelle
language-name-kr = kanuri
language-name-krc = karachay-balkar
language-name-krl = carelian
language-name-kru = kurukh
language-name-ks = kashmiri
language-name-ku = curd
language-name-kum = kumuk
language-name-kut = kutenai
language-name-kv = komi
language-name-kw = cornic
language-name-ky = kirghis
language-name-la = latin
language-name-lad = ladino
language-name-lah = lahnda
language-name-lam = lamba
language-name-lb = luxemburgais
language-name-lez = lezghian
language-name-lg = ganda
language-name-li = limburgais
language-name-ln = lingala
language-name-lo = laot
language-name-lol = lomongo
language-name-loz = lozi
language-name-lt = lituan
language-name-lu = luba-katanga
language-name-lua = luba-lulua
language-name-lui = luiseno
language-name-lun = lunda
language-name-luo = luo
language-name-lus = lushai
language-name-lv = letton
language-name-mad = madurais
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = makassar
language-name-man = mandingo
language-name-mas = masai
language-name-mdf = moksha
language-name-mdr = mandar
language-name-men = mende
language-name-mg = malagassi
language-name-mga = irlandais mesaun
language-name-mh = marschallais
language-name-mi = maori
language-name-mic = micmac
language-name-min = minangkabau
language-name-mk = macedon
language-name-ml = malayalam
language-name-mn = mongolic
language-name-mnc = manchu
language-name-mni = manipuri
language-name-moh = mohawk
language-name-mos = mossi
language-name-mr = marathi
language-name-ms = malaic
language-name-mt = maltais
language-name-mul = pluriling
language-name-mus = creek
language-name-mwl = mirandais
language-name-mwr = marwari
language-name-my = birman
language-name-myv = erzya
language-name-na = nauru
language-name-nap = neapolitan
language-name-nb = norvegais bokmål
language-name-nd = ndebele dal nord
language-name-nds = bass tudestg
language-name-ne = nepalais
language-name-new = newari
language-name-ng = ndonga
language-name-nia = nias
language-name-niu = niue
language-name-nl = ollandais
language-name-nl_BE = flam
language-name-nn = norvegiais nynorsk
language-name-no = norvegiais
language-name-nog = nogai
language-name-non = nordic vegl
language-name-nqo = n’ko
language-name-nr = ndebele dal sid
language-name-nso = sotho dal nord
language-name-nv = navajo
language-name-nwc = newari classic
language-name-ny = nyanja
language-name-nym = nyamwezi
language-name-nyn = nyankole
language-name-nyo = nyoro
language-name-nzi = nzima
language-name-oc = occitan
language-name-oj = ojibwa
language-name-om = oromo
language-name-or = oriya
language-name-os = ossetic
language-name-osa = osage
language-name-ota = tirc ottoman
language-name-pa = punjabi
language-name-pag = pangasinan
language-name-pal = pahlavi
language-name-pam = pampanga
language-name-pap = papiamento
language-name-pau = palau
language-name-peo = persian vegl
language-name-phn = fenizian
language-name-pi = pali
language-name-pl = polac
language-name-pon = ponapean
language-name-pro = provenzal vegl
language-name-ps = paschto
language-name-pt = portugais
language-name-pt_BR = portugais brasilian
language-name-pt_PT = portugais iberian
language-name-qu = quechua
language-name-raj = rajasthani
language-name-rap = rapanui
language-name-rar = rarotonga
language-name-rm = rumantsch
language-name-rn = rundi
language-name-ro = rumen
language-name-ro_MD = moldav
language-name-rom = romani
language-name-ru = russ
language-name-rup = aromunic
language-name-rw = kinyarwanda
language-name-sa = sanscrit
language-name-sad = sandawe
language-name-sah = jakut
language-name-sam = arameic samaritan
language-name-sas = sasak
language-name-sat = santali
language-name-sc = sard
language-name-scn = sicilian
language-name-sco = scot
language-name-sd = sindhi
language-name-se = sami dal nord
language-name-sel = selkup
language-name-sg = sango
language-name-sga = irlandais vegl
language-name-sh = serbo-croat
language-name-shn = shan
language-name-si = singalais
language-name-sid = sidamo
language-name-sk = slovac
language-name-sl = sloven
language-name-sm = samoan
language-name-sma = sami dal sid
language-name-smj = sami lule
language-name-smn = sami inari
language-name-sms = sami skolt
language-name-sn = shona
language-name-snk = soninke
language-name-so = somali
language-name-sog = sogdian
language-name-sq = albanais
language-name-sr = serb
language-name-srn = sranan tongo
language-name-srr = serer
language-name-ss = swazi
language-name-st = sotho dal sid
language-name-su = sundanais
language-name-suk = sukuma
language-name-sus = susu
language-name-sux = sumeric
language-name-sv = svedais
language-name-sw = suahili
language-name-syc = siric classic
language-name-syr = siric
language-name-ta = tamil
language-name-te = telugu
language-name-tem = temne
language-name-ter = tereno
language-name-tet = tetum
language-name-tg = tadjik
language-name-th = tailandais
language-name-ti = tigrinya
language-name-tig = tigre
language-name-tiv = tiv
language-name-tk = turkmen
language-name-tkl = tokelau
language-name-tl = tagalog
language-name-tlh = klingonic
language-name-tli = tlingit
language-name-tmh = tamasheq
language-name-tn = tswana
language-name-to = tonga
language-name-tog = lingua tsonga
language-name-tpi = tok pisin
language-name-tr = tirc
language-name-ts = tsonga
language-name-tsi = tsimshian
language-name-tt = tatar
language-name-tum = tumbuka
language-name-tvl = tuvalu
language-name-tw = twi
language-name-ty = tahitian
language-name-tyv = tuvinian
language-name-udm = udmurt
language-name-ug = uiguric
language-name-uga = ugaritic
language-name-uk = ucranais
language-name-umb = mbundu
language-name-und = linguas betg determinadas
language-name-ur = urdu
language-name-uz = usbec
language-name-vai = vai
language-name-ve = venda
language-name-vi = vietnamais
language-name-vo = volapuk
language-name-vot = votic
language-name-wa = vallon
language-name-wal = walamo
language-name-war = waray
language-name-was = washo
language-name-wo = wolof
language-name-xal = kalmuk
language-name-xh = xhosa
language-name-yao = yao
language-name-yap = yapais
language-name-yi = jiddic
language-name-yo = yoruba
language-name-za = zhuang
language-name-zap = zapotec
language-name-zbl = simbols da Bliss
language-name-zen = zenaga
language-name-zh = chinais
language-name-zh_Hans = chinais simplifitgà
language-name-zh_Hant = chinais tradiziunal
language-name-zu = zulu
language-name-zun = zuni
language-name-zxx = nagins cuntegns linguistics
language-name-zza = zaza
