language-name-aa = афар
language-name-ab = абхаз
language-name-ace = акин
language-name-ada = адангме
language-name-ady = адуҝе
language-name-af = африкаанс
language-name-agq = агһем
language-name-ain = ајну
language-name-ak = акан
language-name-ale = алеут
language-name-alt = ҹәнуби алтај
language-name-am = амһар
language-name-an = арагон
language-name-anp = анҝика
language-name-ar = әрәб
language-name-ar_001 = мүасир стандарт әрәб
language-name-arn = арауканҹа
language-name-arp = арапаһо
language-name-as = ассам
language-name-asa = асу
language-name-ast = астурија
language-name-av = авар
language-name-awa = авадһи
language-name-ay = ајмара
language-name-az = азәрбајҹан
language-name-ba = башгырд
language-name-ban = балли
language-name-bas = баса
language-name-be = беларус
language-name-bem = бемба
language-name-bez = бена
language-name-bg = булгар
language-name-bho = бхочпури
language-name-bi = бислама
language-name-bin = бини
language-name-bla = сиксикә
language-name-bm = бамбара
language-name-bn = бенгал
language-name-bo = тибет
language-name-br = бретон
language-name-brx = бодо
language-name-bs = босниак
language-name-bug = буҝин
language-name-byn = блин
language-name-ca = каталан
language-name-ce = чечен
language-name-ceb = себуан
language-name-cgg = чига
language-name-ch = чаморо
language-name-chk = чукиз
language-name-chm = мари
language-name-cho = чоктау
language-name-chr = чероки
language-name-chy = чејен
language-name-ckb = соран
language-name-co = корсика
language-name-crs = сејшел креолу
language-name-cs = чех
language-name-cu = славјан
language-name-cv = чуваш
language-name-cy = уелс
language-name-da = данимарка
language-name-dak = дакота
language-name-dar = даргва
language-name-dav = таита
language-name-de = алман
language-name-de_AT = Австрија алманҹасы
language-name-de_CH = Исвечрә јүксәк алманҹасы
language-name-dgr = догриб
language-name-dje = зарма
language-name-dsb = ашағы сорб
language-name-dua = дуала
language-name-dv = малдив
language-name-dyo = диола
language-name-dz = дзонга
language-name-dzg = дазага
language-name-ebu = ембу
language-name-ee = еве
language-name-efi = ефик
language-name-eka = екаҹук
language-name-el = јунан
language-name-en = инҝилис
language-name-en_AU = Австралија инҝилисҹәси
language-name-en_CA = Канада инҝилисҹәси
language-name-en_GB = Британија инҝилисҹәси
language-name-en_US = Америка инҝилисҹәси
language-name-eo = есперанто
language-name-es = испан
language-name-es_419 = Латын Америкасы испанҹасы
language-name-es_ES = Кастилија испанҹасы
language-name-es_MX = Мексика испанҹасы
language-name-et = естон
language-name-eu = баск
language-name-ewo = евондо
language-name-fa = фарс
language-name-ff = фула
language-name-fi = фин
language-name-fil = филиппин
language-name-fj = фиҹи
language-name-fo = фарер
language-name-fon = фон
language-name-fr = франсыз
language-name-fr_CA = Канада франсызҹасы
language-name-fr_CH = Исвечрә франсызҹасы
language-name-fur = фриул
language-name-fy = гәрби фриз
language-name-ga = ирланд
language-name-gaa = га
language-name-gd = шотланд келт
language-name-gez = гез
language-name-gil = гилберт
language-name-gl = галисија
language-name-gn = гуарани
language-name-gor = горонтало
language-name-gsw = Исвечрә алманҹасы
language-name-gu = гуҹарат
language-name-guz = гуси
language-name-gv = манкс
language-name-gwi = гвичин
language-name-ha = һауса
language-name-haw = һавај
language-name-he = иврит
language-name-hi = һинд
language-name-hil = һилигајнон
language-name-hmn = монг
language-name-hr = хорват
language-name-hsb = јухары сорб
language-name-ht = һаити креол
language-name-hu = маҹар
language-name-hup = һупа
language-name-hy = ермәни
language-name-hz = һереро
language-name-ia = интерлингве
language-name-iba = ибан
language-name-ibb = ибибио
language-name-id = индонезија
language-name-ig = игбо
language-name-ilo = илоко
language-name-inh = ингуш
language-name-io = идо
language-name-is = исланд
language-name-it = италјан
language-name-iu = инуктитут
language-name-ja = јапон
language-name-jbo = лоғбан
language-name-jgo = нгомба
language-name-jmc = мачам
language-name-jv = јава
language-name-ka = ҝүрҹү
language-name-kab = кабиле
language-name-kac = качин
language-name-kaj = жу
language-name-kam = камба
language-name-kbd = кабарда-чәркәз
language-name-kcg = тви
language-name-kde = маконде
language-name-kea = кабувердиан
language-name-kfo = коро
language-name-kha = хази
language-name-khq = којра чиини
language-name-ki = кикују
language-name-kj = куанјама
language-name-kk = газах
language-name-kkj = како
language-name-kl = калааллисут
language-name-kln = каленҹин
language-name-km = кхмер
language-name-kmb = кимбунду
language-name-kn = каннада
language-name-ko = кореја
language-name-kok = конкани
language-name-kpe = кпелле
language-name-kr = канури
language-name-krc = гарачај-балкар
language-name-krl = карел
language-name-kru = курух
language-name-ks = кәшмир
language-name-ksb = шамбала
language-name-ksf = бафиа
language-name-ksh = көлн
language-name-ku = күрд
language-name-kum = кумык
language-name-kv = коми
language-name-kw = корн
language-name-ky = гырғыз
language-name-la = латын
language-name-lad = сефард
language-name-lag = ланҝи
language-name-lb = лүксембург
language-name-lez = ләзҝи
language-name-lg = ганда
language-name-li = лимбург
language-name-lkt = лакота
language-name-ln = лингала
language-name-lo = лаос
language-name-loz = лози
language-name-lrc = шимали лури
language-name-lt = литва
language-name-lu = луба-катанга
language-name-lua = луба-лулуа
language-name-lun = лунда
language-name-luo = луо
language-name-lus = мизо
language-name-luy = лујиа
language-name-lv = латыш
language-name-mad = мадуриз
language-name-mag = магаһи
language-name-mai = маитили
language-name-mak = макасар
language-name-mas = масај
language-name-mdf = мокша
language-name-men = менде
language-name-mer = меру
language-name-mfe = морисиен
language-name-mg = малагас
language-name-mgh = махува-меетто
language-name-mgo = метаʼ
language-name-mh = маршал
language-name-mi = маори
language-name-mic = микмак
language-name-min = минангкабан
language-name-mk = македон
language-name-ml = малајалам
language-name-mn = монгол
language-name-mni = манипүри
language-name-moh = моһавк
language-name-mos = моси
language-name-mr = маратһи
language-name-ms = малај
language-name-mt = малта
language-name-mua = мунданг
language-name-mul = чохсајлы дилләр
language-name-mus = крик
language-name-mwl = миранд
language-name-my = бирман
language-name-myv = ерзја
language-name-mzn = мазандаран
language-name-na = науру
language-name-nap = неаполитан
language-name-naq = нама
language-name-nb = бокмал норвеч
language-name-nd = шимали ндебеле
language-name-nds_NL = ашағы саксон
language-name-ne = непал
language-name-new = невари
language-name-ng = ндонга
language-name-nia = ниас
language-name-niu = нијуан
language-name-nl = һолланд
language-name-nl_BE = фламанд
language-name-nmg = квасио
language-name-nn = нүнорск норвеч
language-name-nnh = нҝиембоон
language-name-nog = ногај
language-name-nqo = нго
language-name-nr = ҹәнуби ндебеле
language-name-nso = шимали сото
language-name-nus = нуер
language-name-nv = навајо
language-name-ny = нјанҹа
language-name-nyn = нјанкол
language-name-oc = окситан
language-name-om = оромо
language-name-or = одија
language-name-os = осетин
language-name-pa = пәнҹаб
language-name-pag = пангасинан
language-name-pam = пампанга
language-name-pap = папјаменто
language-name-pau = палајан
language-name-pcm = ниҝер креол
language-name-pl = полјак
language-name-prg = прусс
language-name-ps = пушту
language-name-pt = португал
language-name-pt_BR = Бразилија португалҹасы
language-name-pt_PT = Португалија португалҹасы
language-name-qu = кечуа
language-name-quc = киче
language-name-rap = рапануи
language-name-rar = раротонган
language-name-rm = романш
language-name-rn = рунди
language-name-ro = румын
language-name-rof = ромбо
language-name-root = рут
language-name-ru = рус
language-name-rup = ароман
language-name-rw = кинјарванда
language-name-rwk = руа
language-name-sa = санскрит
language-name-sad = сандаве
language-name-sah = саха
language-name-saq = самбуру
language-name-sat = сантал
language-name-sba = нгамбај
language-name-sbp = сангу
language-name-sc = сардин
language-name-scn = сиҹилија
language-name-sco = скотс
language-name-sd = синдһи
language-name-se = шимали сами
language-name-seh = сена
language-name-ses = којраборо сенни
language-name-sg = санго
language-name-shi = тачелит
language-name-shn = шан
language-name-si = синһала
language-name-sk = словак
language-name-sl = словен
language-name-sm = самоа
language-name-sma = ҹәнуби сами
language-name-smj = луле сами
language-name-smn = инари сами
language-name-sms = сколт сами
language-name-sn = шона
language-name-snk = сонинке
language-name-so = сомали
language-name-sq = албан
language-name-sr = серб
language-name-srn = сранан тонго
language-name-ss = свати
language-name-ssy = саһо
language-name-st = сесото
language-name-su = сундан
language-name-suk = сукума
language-name-sv = исвеч
language-name-sw = суаһили
language-name-sw_CD = Конго суаһилиҹәси
language-name-swb = комор
language-name-syr = сурија
language-name-ta = тамил
language-name-te = телугу
language-name-tem = тимне
language-name-teo = тесо
language-name-tet = тетум
language-name-tg = таҹик
language-name-th = тај
language-name-ti = тигрин
language-name-tig = тигре
language-name-tk = түркмән
language-name-tlh = клингон
language-name-tn = свана
language-name-to = тонган
language-name-tpi = ток писин
language-name-tr = түрк
language-name-trv = тароко
language-name-ts = сонга
language-name-tt = татар
language-name-tum = тумбука
language-name-tvl = тувалу
language-name-twq = тасаваг
language-name-ty = тахити
language-name-tyv = тувинјан
language-name-tzm = Мәркәзи Атлас тамазиҹәси
language-name-udm = удмурт
language-name-ug = ујғур
language-name-uk = украјна
language-name-umb = умбунду
language-name-und = намәлум дил
language-name-ur = урду
language-name-uz = өзбәк
language-name-vai = ваи
language-name-ve = венда
language-name-vi = вјетнам
language-name-vo = волапүк
language-name-vun = вунјо
language-name-wa = валун
language-name-wae = валлес
language-name-wal = валамо
language-name-war = варај
language-name-wo = волоф
language-name-xal = калмык
language-name-xh = хоса
language-name-xog = сога
language-name-yav = јангбен
language-name-ybb = јемба
language-name-yi = идиш
language-name-yo = јоруба
language-name-yue = кантон
language-name-zgh = тамази
language-name-zh = чин
language-name-zh_Hans = садәләшмиш чин
language-name-zh_Hant = әнәнәви чин
language-name-zu = зулу
language-name-zun = зуни
language-name-zxx = дил мәзмуну јохдур
language-name-zza = заза
