language-name-aa = afar
language-name-ab = abcázio
language-name-ace = achém
language-name-ach = acoli
language-name-ada = adangme
language-name-ady = adigue
language-name-ae = avéstico
language-name-af = africâner
language-name-afh = afrihili
language-name-agq = aghem
language-name-ain = ainu
language-name-ak = akan
language-name-akk = acadiano
language-name-ale = aleúte
language-name-alt = altai do sul
language-name-am = amárico
language-name-an = aragonês
language-name-ang = inglês arcaico
language-name-anp = angika
language-name-ar = árabe
language-name-ar_001 = árabe moderno
language-name-arc = aramaico
language-name-arn = mapudungun
language-name-arp = arapaho
language-name-ars = árabe - Négede
language-name-arw = arauaqui
language-name-as = assamês
language-name-asa = asu
language-name-ast = asturiano
language-name-av = avárico
language-name-awa = awadhi
language-name-ay = aimará
language-name-az = azerbaijano
language-name-az_Arab = azeri sul
language-name-ba = bashkir
language-name-bal = balúchi
language-name-ban = balinês
language-name-bas = basa
language-name-bax = bamum
language-name-bbj = ghomala’
language-name-be = bielorrusso
language-name-bej = beja
language-name-bem = bemba
language-name-bez = bena
language-name-bfd = bafut
language-name-bg = búlgaro
language-name-bgn = balúchi ocidental
language-name-bho = bhojpuri
language-name-bi = bislamá
language-name-bik = bikol
language-name-bin = bini
language-name-bkm = kom
language-name-bla = siksika
language-name-bm = bambara
language-name-bn = bengali
language-name-bo = tibetano
language-name-br = bretão
language-name-bra = braj
language-name-brx = bodo
language-name-bs = bósnio
language-name-bss = akoose
language-name-bua = buriato
language-name-bug = buginês
language-name-bum = bulu
language-name-byn = blin
language-name-byv = medumba
language-name-ca = catalão
language-name-cad = caddo
language-name-car = caribe
language-name-cay = cayuga
language-name-cch = atsam
language-name-ce = checheno
language-name-ceb = cebuano
language-name-cgg = chiga
language-name-ch = chamorro
language-name-chb = chibcha
language-name-chg = chagatai
language-name-chk = chuukese
language-name-chm = mari
language-name-chn = jargão Chinook
language-name-cho = choctaw
language-name-chp = chipewyan
language-name-chr = cherokee
language-name-chy = cheiene
language-name-ckb = curdo central
language-name-co = corso
language-name-cop = copta
language-name-cr = cree
language-name-crh = turco da Crimeia
language-name-crs = crioulo francês seichelense
language-name-cs = tcheco
language-name-csb = kashubian
language-name-cu = eslavo eclesiástico
language-name-cv = tchuvache
language-name-cy = galês
language-name-da = dinamarquês
language-name-dak = dacota
language-name-dar = dargwa
language-name-dav = taita
language-name-de = alemão
language-name-del = delaware
language-name-den = slave
language-name-dgr = dogrib
language-name-din = dinka
language-name-dje = zarma
language-name-doi = dogri
language-name-dsb = baixo sorábio
language-name-dua = duala
language-name-dum = holandês médio
language-name-dv = divehi
language-name-dyo = jola-fonyi
language-name-dyu = diúla
language-name-dz = dzonga
language-name-dzg = dazaga
language-name-ebu = embu
language-name-ee = eve
language-name-efi = efique
language-name-egy = egípcio arcaico
language-name-eka = ekajuk
language-name-el = grego
language-name-elx = elamite
language-name-en = inglês
language-name-enm = inglês médio
language-name-eo = esperanto
language-name-es = espanhol
language-name-et = estoniano
language-name-eu = basco
language-name-ewo = ewondo
language-name-fa = persa
language-name-fan = fangue
language-name-fat = fanti
language-name-ff = fula
language-name-fi = finlandês
language-name-fil = filipino
language-name-fj = fijiano
language-name-fo = feroês
language-name-fon = fom
language-name-fr = francês
language-name-frc = francês cajun
language-name-frm = francês médio
language-name-fro = francês arcaico
language-name-frr = frísio setentrional
language-name-frs = frisão oriental
language-name-fur = friulano
language-name-fy = frísio ocidental
language-name-ga = irlandês
language-name-gaa = ga
language-name-gag = gagauz
language-name-gan = gan
language-name-gay = gayo
language-name-gba = gbaia
language-name-gd = gaélico escocês
language-name-gez = geez
language-name-gil = gilbertês
language-name-gl = galego
language-name-gmh = alto alemão médio
language-name-gn = guarani
language-name-goh = alemão arcaico alto
language-name-gon = gondi
language-name-gor = gorontalo
language-name-got = gótico
language-name-grb = grebo
language-name-grc = grego arcaico
language-name-gu = guzerate
language-name-guz = gusii
language-name-gv = manx
language-name-gwi = gwichʼin
language-name-ha = hauçá
language-name-hai = haida
language-name-hak = hacá
language-name-haw = havaiano
language-name-he = hebraico
language-name-hi = híndi
language-name-hil = hiligaynon
language-name-hit = hitita
language-name-hmn = hmong
language-name-ho = hiri motu
language-name-hr = croata
language-name-hsb = alto sorábio
language-name-hsn = xiang
language-name-ht = haitiano
language-name-hu = húngaro
language-name-hup = hupa
language-name-hy = armênio
language-name-hz = herero
language-name-ia = interlíngua
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indonésio
language-name-ie = interlingue
language-name-ig = igbo
language-name-ii = sichuan yi
language-name-ik = inupiaque
language-name-ilo = ilocano
language-name-inh = inguche
language-name-io = ido
language-name-is = islandês
language-name-it = italiano
language-name-iu = inuktitut
language-name-ja = japonês
language-name-jbo = lojban
language-name-jgo = nguemba
language-name-jmc = machame
language-name-jpr = judaico-persa
language-name-jrb = judaico-arábico
language-name-jv = javanês
language-name-ka = georgiano
language-name-kaa = kara-kalpak
language-name-kab = kabyle
language-name-kac = kachin
language-name-kaj = jju
language-name-kam = kamba
language-name-kaw = kawi
language-name-kbd = kabardiano
language-name-kbl = kanembu
language-name-kcg = tyap
language-name-kde = maconde
language-name-kea = kabuverdianu
language-name-kfo = koro
language-name-kg = congolês
language-name-kha = khasi
language-name-kho = khotanês
language-name-khq = koyra chiini
language-name-ki = quicuio
language-name-kj = cuanhama
language-name-kk = cazaque
language-name-kkj = kako
language-name-kl = groenlandês
language-name-kln = kalenjin
language-name-km = khmer
language-name-kmb = quimbundo
language-name-kn = canarim
language-name-ko = coreano
language-name-koi = komi-permyak
language-name-kok = concani
language-name-kos = kosraean
language-name-kpe = kpelle
language-name-kr = canúri
language-name-krc = karachay-balkar
language-name-krl = carélio
language-name-kru = kurukh
language-name-ks = caxemira
language-name-ksb = shambala
language-name-ksf = bafia
language-name-ksh = kölsch
language-name-ku = curdo
language-name-kum = kumyk
language-name-kut = kutenai
language-name-kv = komi
language-name-kw = córnico
language-name-ky = quirguiz
language-name-la = latim
language-name-lad = ladino
language-name-lag = langi
language-name-lah = lahnda
language-name-lam = lamba
language-name-lb = luxemburguês
language-name-lez = lezgui
language-name-lg = luganda
language-name-li = limburguês
language-name-lkt = lacota
language-name-ln = lingala
language-name-lo = laosiano
language-name-lol = mongo
language-name-lou = crioulo da Louisiana
language-name-loz = lozi
language-name-lrc = luri setentrional
language-name-lt = lituano
language-name-lu = luba-catanga
language-name-lua = luba-lulua
language-name-lui = luiseno
language-name-lun = lunda
language-name-luo = luo
language-name-lus = lushai
language-name-luy = luyia
language-name-lv = letão
language-name-mad = madurês
language-name-maf = mafa
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = makasar
language-name-man = mandinga
language-name-mas = massai
language-name-mde = maba
language-name-mdf = mocsa
language-name-mdr = mandar
language-name-men = mende
language-name-mer = meru
language-name-mfe = morisyen
language-name-mg = malgaxe
language-name-mga = irlandês médio
language-name-mgh = macua
language-name-mgo = meta’
language-name-mh = marshalês
language-name-mi = maori
language-name-mic = miquemaque
language-name-min = minangkabau
language-name-mk = macedônio
language-name-ml = malaiala
language-name-mn = mongol
language-name-mnc = manchu
language-name-mni = manipuri
language-name-moh = moicano
language-name-mos = mossi
language-name-mr = marati
language-name-ms = malaio
language-name-mt = maltês
language-name-mua = mundang
language-name-mul = múltiplos idiomas
language-name-mus = creek
language-name-mwl = mirandês
language-name-mwr = marwari
language-name-my = birmanês
language-name-mye = myene
language-name-myv = erzya
language-name-mzn = mazandarani
language-name-na = nauruano
language-name-nan = min nan
language-name-nap = napolitano
language-name-naq = nama
language-name-nb = bokmål norueguês
language-name-nd = ndebele do norte
language-name-nds = baixo alemão
language-name-nds_NL = baixo saxão
language-name-ne = nepalês
language-name-new = newari
language-name-ng = dongo
language-name-nia = nias
language-name-niu = niueano
language-name-nl = holandês
language-name-nl_BE = flamengo
language-name-nmg = kwasio
language-name-nn = nynorsk norueguês
language-name-nnh = ngiemboon
language-name-no = norueguês
language-name-nog = nogai
language-name-non = nórdico arcaico
language-name-nqo = n’ko
language-name-nr = ndebele do sul
language-name-nso = soto setentrional
language-name-nus = nuer
language-name-nv = navajo
language-name-nwc = newari clássico
language-name-ny = nianja
language-name-nym = nyamwezi
language-name-nyn = nyankole
language-name-nyo = nyoro
language-name-nzi = nzima
language-name-oc = occitânico
language-name-oj = ojibwa
language-name-om = oromo
language-name-or = oriá
language-name-os = osseto
language-name-osa = osage
language-name-ota = turco otomano
language-name-pa = panjabi
language-name-pag = pangasinã
language-name-pal = pálavi
language-name-pam = pampanga
language-name-pap = papiamento
language-name-pau = palauano
language-name-pcm = pidgin nigeriano
language-name-peo = persa arcaico
language-name-phn = fenício
language-name-pi = páli
language-name-pl = polonês
language-name-pon = pohnpeiano
language-name-prg = prussiano
language-name-pro = provençal arcaico
language-name-ps = pashto
language-name-pt = português
language-name-qu = quíchua
language-name-quc = quiché
language-name-raj = rajastani
language-name-rap = rapanui
language-name-rar = rarotongano
language-name-rm = romanche
language-name-rn = rundi
language-name-ro = romeno
language-name-ro_MD = moldávio
language-name-rof = rombo
language-name-rom = romani
language-name-root = raiz
language-name-ru = russo
language-name-rup = aromeno
language-name-rw = quiniaruanda
language-name-rwk = rwa
language-name-sa = sânscrito
language-name-sad = sandawe
language-name-sah = sakha
language-name-sam = aramaico samaritano
language-name-saq = samburu
language-name-sas = sasak
language-name-sat = santali
language-name-sba = ngambay
language-name-sbp = sangu
language-name-sc = sardo
language-name-scn = siciliano
language-name-sco = scots
language-name-sd = sindi
language-name-sdh = curdo meridional
language-name-se = sami setentrional
language-name-see = seneca
language-name-seh = sena
language-name-sel = selkup
language-name-ses = koyraboro senni
language-name-sg = sango
language-name-sga = irlandês arcaico
language-name-sh = servo-croata
language-name-shi = tachelhit
language-name-shn = shan
language-name-shu = árabe chadiano
language-name-si = cingalês
language-name-sid = sidamo
language-name-sk = eslovaco
language-name-sl = esloveno
language-name-sm = samoano
language-name-sma = sami do sul
language-name-smj = sami de Lule
language-name-smn = sami de Inari
language-name-sms = sami de Skolt
language-name-sn = xona
language-name-snk = soninquê
language-name-so = somali
language-name-sog = sogdiano
language-name-sq = albanês
language-name-sr = sérvio
language-name-srn = surinamês
language-name-srr = serere
language-name-ss = suázi
language-name-ssy = saho
language-name-st = soto do sul
language-name-su = sundanês
language-name-suk = sukuma
language-name-sus = susu
language-name-sux = sumério
language-name-sv = sueco
language-name-sw = suaíli
language-name-sw_CD = suaíli do Congo
language-name-swb = comoriano
language-name-syc = siríaco clássico
language-name-syr = siríaco
language-name-ta = tâmil
language-name-te = télugo
language-name-tem = timne
language-name-teo = teso
language-name-ter = tereno
language-name-tet = tétum
language-name-tg = tadjique
language-name-th = tailandês
language-name-ti = tigrínia
language-name-tig = tigré
language-name-tiv = tiv
language-name-tk = turcomeno
language-name-tkl = toquelauano
language-name-tl = tagalo
language-name-tlh = klingon
language-name-tli = tlinguite
language-name-tmh = tamaxeque
language-name-tn = tswana
language-name-to = tonganês
language-name-tog = tonganês de Nyasa
language-name-tpi = tok pisin
language-name-tr = turco
language-name-trv = taroko
language-name-ts = tsonga
language-name-tsi = tsimshiano
language-name-tt = tártaro
language-name-tum = tumbuka
language-name-tvl = tuvaluano
language-name-tw = twi
language-name-twq = tasawaq
language-name-ty = taitiano
language-name-tyv = tuviniano
language-name-tzm = tamazirte do Atlas Central
language-name-udm = udmurte
language-name-ug = uigur
language-name-uga = ugarítico
language-name-uk = ucraniano
language-name-umb = umbundu
language-name-und = idioma desconhecido
language-name-ur = urdu
language-name-uz = uzbeque
language-name-vai = vai
language-name-ve = venda
language-name-vi = vietnamita
language-name-vo = volapuque
language-name-vot = vótico
language-name-vun = vunjo
language-name-wa = valão
language-name-wae = walser
language-name-wal = wolaytta
language-name-war = waray
language-name-was = washo
language-name-wbp = warlpiri
language-name-wo = uolofe
language-name-wuu = wu
language-name-xal = kalmyk
language-name-xh = xhosa
language-name-xog = lusoga
language-name-yao = yao
language-name-yap = yapese
language-name-yav = yangben
language-name-ybb = yemba
language-name-yi = iídiche
language-name-yo = iorubá
language-name-yue = cantonês
language-name-za = zhuang
language-name-zap = zapoteco
language-name-zbl = símbolos blis
language-name-zen = zenaga
language-name-zgh = tamazirte marroqino padrão
language-name-zh = chinês
language-name-zh_Hans = chinês simplificado
language-name-zh_Hant = chinês tradicional
language-name-zu = zulu
language-name-zun = zunhi
language-name-zxx = sem conteúdo linguístico
language-name-zza = zazaki
