language-name-ab = абхазаг
language-name-ady = адыгейаг
language-name-ae = авестӕ
language-name-af = африкаанс
language-name-ang = рагон англисаг
language-name-ar = араббаг
language-name-av = авайраг
language-name-az = тӕтӕйраг
language-name-ba = башкираг
language-name-bg = болгайраг
language-name-bs = босниаг
language-name-bua = бурятаг
language-name-ca = каталайнаг
language-name-ce = цӕцӕйнаг
language-name-cop = коптаг
language-name-cs = чехаг
language-name-cv = чувашаг
language-name-da = даниаг
language-name-de = немыцаг
language-name-de_AT = австралиаг немыцаг
language-name-de_CH = швйецариаг немыцаг
language-name-egy = рагон египтаг
language-name-el = бердзейнаг
language-name-en = англисаг
language-name-en_AU = австралиаг англисаг
language-name-en_CA = канадӕйаг англисаг
language-name-en_GB = бритайнаг англисаг
language-name-en_US = америкаг англисаг
language-name-eo = есперанто
language-name-es = испайнаг
language-name-es_419 = латинаг америкаг англисаг
language-name-es_ES = европӕйаг англисаг
language-name-et = естойнаг
language-name-eu = баскаг
language-name-fa = персайнаг
language-name-fi = финнаг
language-name-fil = филиппинаг
language-name-fj = фиджи
language-name-fo = фарераг
language-name-fr = францаг
language-name-fr_CA = канадӕйаг францаг
language-name-fr_CH = швейцариаг францаг
language-name-fro = рагон францаг
language-name-ga = ирландиаг
language-name-grc = рагон бердзейнаг
language-name-he = уираг
language-name-hr = хорватаг
language-name-hu = венгериаг
language-name-hy = сомихаг
language-name-inh = мӕхъӕлон
language-name-it = италиаг
language-name-ja = япойнаг
language-name-ka = гуырдзиаг
language-name-kbd = кӕсгон
language-name-krc = бӕлхъӕрон
language-name-ku = курдаг
language-name-kum = хъуымыхъхъаг
language-name-la = латинаг
language-name-lez = лекъаг
language-name-mk = мӕчъидон
language-name-os = ирон
language-name-pt = португалиаг
language-name-pt_BR = бразилиаг португалиаг
language-name-pt_PT = европӕйаг полтугалиаг
language-name-rom = цигайнаг
language-name-ru = уырыссаг
language-name-und = нӕзонгӕ ӕвзаг
language-name-zh = китайаг
language-name-zh_Hans = ӕнцонгонд китайаг
language-name-zh_Hant = традицион китайаг
