language-name-aa = afar
language-name-ab = abxaz
language-name-ace = akin
language-name-ach = akoli
language-name-ada = adanqme
language-name-ady = adıgey
language-name-ae = avestan
language-name-af = afrikaans
language-name-afh = afrihili
language-name-agq = aqhem
language-name-ain = aynu
language-name-ak = akan
language-name-akk = akkad
language-name-ale = aleut
language-name-alt = cənubi altay
language-name-am = amhar
language-name-an = araqon
language-name-ang = qədim ingilis
language-name-anp = angika
language-name-ar = ərəb
language-name-ar_001 = müasir standart ərəb
language-name-arc = aramik
language-name-arn = mapuçe
language-name-arp = arapaho
language-name-arw = aravak
language-name-as = assam
language-name-asa = asu
language-name-ast = asturiya
language-name-av = avar
language-name-awa = avadhi
language-name-ay = aymara
language-name-az = azərbaycan
language-name-az_Arab = cənubi azərbaycan
language-name-ba = başqırd
language-name-bal = baluc
language-name-ban = bali
language-name-bas = basa
language-name-be = belarus
language-name-bej = beja
language-name-bem = bemba
language-name-bez = bena
language-name-bg = bolqar
language-name-bgn = qərbi bəluc
language-name-bho = bxoçpuri
language-name-bi = bislama
language-name-bik = bikol
language-name-bin = bini
language-name-bla = siksikə
language-name-bm = bambara
language-name-bn = benqal
language-name-bo = tibet
language-name-br = breton
language-name-bra = braj
language-name-brx = bodo
language-name-bs = bosniya
language-name-bua = buryat
language-name-bug = bugin
language-name-byn = blin
language-name-ca = katalan
language-name-cad = keddo
language-name-car = karib
language-name-cch = atsam
language-name-ce = çeçen
language-name-ceb = sebuan
language-name-cgg = çiqa
language-name-ch = çamoro
language-name-chb = çibça
language-name-chg = çağatay
language-name-chk = çukiz
language-name-chm = mari
language-name-chn = çinuk ləhçəsi
language-name-cho = çoktau
language-name-chp = çipevyan
language-name-chr = çeroki
language-name-chy = çeyen
language-name-ckb = Mərkəzi kürdcə
language-name-co = korsika
language-name-cop = kopt
language-name-cr = kri
language-name-crh = krım türkcəsi
language-name-crs = Seyşel kreol fransızcası
language-name-cs = çex
language-name-csb = kaşubyan
language-name-cu = slavyan
language-name-cv = çuvaş
language-name-cy = uels
language-name-da = danimarka
language-name-dak = dakota
language-name-dar = darqva
language-name-dav = taita
language-name-de = alman
language-name-de_AT = Avstriya almancası
language-name-de_CH = İsveçrə yüksək almancası
language-name-del = delaver
language-name-den = slavey
language-name-dgr = doqrib
language-name-din = dinka
language-name-dje = zarma
language-name-doi = doqri
language-name-dsb = aşağı sorb
language-name-dua = duala
language-name-dum = orta holland
language-name-dv = maldiv
language-name-dyo = diola
language-name-dyu = dyula
language-name-dz = dzonqxa
language-name-dzg = dazaqa
language-name-ebu = embu
language-name-ee = eve
language-name-efi = efik
language-name-egy = qədim misir
language-name-eka = ekacuk
language-name-el = yunan
language-name-elx = elamit
language-name-en = ingilis
language-name-en_AU = Avstraliya ingiliscəsi
language-name-en_CA = Kanada ingiliscəsi
language-name-en_GB = Britaniya ingiliscəsi
language-name-en_US = Amerika ingiliscəsi
language-name-enm = orta ingilis
language-name-eo = esperanto
language-name-es = ispan
language-name-es_419 = Latın Amerikası ispancası
language-name-es_ES = Kastiliya ispancası
language-name-es_MX = Meksika ispancası
language-name-et = eston
language-name-eu = bask
language-name-ewo = evondo
language-name-fa = fars
language-name-fan = fang
language-name-fat = fanti
language-name-ff = fula
language-name-fi = fin
language-name-fil = filippin
language-name-fj = fici
language-name-fo = farer
language-name-fon = fon
language-name-fr = fransız
language-name-fr_CA = Kanada fransızcası
language-name-fr_CH = İsveçrə fransızcası
language-name-frm = orta fransız
language-name-fro = qədim fransız
language-name-frr = şimali fris
language-name-fur = friul
language-name-fy = qərbi friz
language-name-ga = irland
language-name-gaa = qa
language-name-gag = qaqauz
language-name-gan = qan
language-name-gay = qayo
language-name-gba = qabaya
language-name-gd = Şotlandiya keltcəsi
language-name-gez = qez
language-name-gil = qilbert
language-name-gl = qalisiya
language-name-gmh = orta yüksək alman
language-name-gn = quarani
language-name-goh = qədim alman
language-name-gon = qondi
language-name-gor = qorontalo
language-name-got = qotika
language-name-grb = qrebo
language-name-grc = qədim yunan
language-name-gsw = İsveçrə almancası
language-name-gu = qucarat
language-name-guz = qusi
language-name-gv = manks
language-name-gwi = qviçin
language-name-ha = hausa
language-name-hai = hayda
language-name-hak = hakka
language-name-haw = havay
language-name-he = ivrit
language-name-hi = hind
language-name-hil = hiliqaynon
language-name-hit = hittit
language-name-hmn = monq
language-name-ho = hiri motu
language-name-hr = xorvat
language-name-hsb = yuxarı sorb
language-name-hsn = syan
language-name-ht = haiti kreol
language-name-hu = macar
language-name-hup = hupa
language-name-hy = erməni
language-name-hz = herero
language-name-ia = interlinqua
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indoneziya
language-name-ie = interlinqve
language-name-ig = iqbo
language-name-ii = siçuan yi
language-name-ik = inupiaq
language-name-ilo = iloko
language-name-inh = inquş
language-name-io = ido
language-name-is = island
language-name-it = italyan
language-name-iu = inuktitut
language-name-ja = yapon
language-name-jbo = loğban
language-name-jgo = nqomba
language-name-jmc = maçam
language-name-jpr = ivrit-fars
language-name-jrb = ivrit-ərəb
language-name-jv = yava
language-name-ka = gürcü
language-name-kaa = qaraqalpaq
language-name-kab = kabile
language-name-kac = kaçin
language-name-kaj = ju
language-name-kam = kamba
language-name-kaw = kavi
language-name-kbd = kabarda-çərkəz
language-name-kcg = tiyap
language-name-kde = makond
language-name-kea = kabuverdian
language-name-kfo = koro
language-name-kg = konqo
language-name-kha = xazi
language-name-kho = xotan
language-name-khq = koyra çiini
language-name-ki = kikuyu
language-name-kj = kuanyama
language-name-kk = qazax
language-name-kkj = kako
language-name-kl = kalaallisut
language-name-kln = kalencin
language-name-km = kxmer
language-name-kmb = kimbundu
language-name-kn = kannada
language-name-ko = koreya
language-name-koi = komi-permyak
language-name-kok = konkani
language-name-kos = kosreyan
language-name-kpe = kpelle
language-name-kr = kanuri
language-name-krc = qaraçay-balkar
language-name-krl = karel
language-name-kru = kurux
language-name-ks = kəşmir
language-name-ksb = şambala
language-name-ksf = bafia
language-name-ksh = köln
language-name-ku = kürd
language-name-kum = kumık
language-name-kut = kutenay
language-name-kv = komi
language-name-kw = korn
language-name-ky = qırğız
language-name-la = latın
language-name-lad = sefard
language-name-lag = langi
language-name-lah = qərbi pəncab
language-name-lam = lamba
language-name-lb = lüksemburq
language-name-lez = ləzgi
language-name-lg = qanda
language-name-li = limburq
language-name-lkt = lakota
language-name-ln = linqala
language-name-lo = laos
language-name-lol = monqo
language-name-loz = lozi
language-name-lrc = şimali luri
language-name-lt = litva
language-name-lu = luba-katanqa
language-name-lua = luba-lulua
language-name-lui = luyseno
language-name-lun = lunda
language-name-luo = luo
language-name-lus = mizo
language-name-luy = luyia
language-name-lv = latış
language-name-mad = maduriz
language-name-mag = maqahi
language-name-mai = maitili
language-name-mak = makasar
language-name-man = məndinqo
language-name-mas = masay
language-name-mdf = mokşa
language-name-mdr = mandar
language-name-men = mende
language-name-mer = meru
language-name-mfe = morisien
language-name-mg = malaqas
language-name-mga = orta irland
language-name-mgh = maxuva-meetto
language-name-mgo = meta’
language-name-mh = marşal
language-name-mi = maori
language-name-mic = mikmak
language-name-min = minanqkaban
language-name-mk = makedon
language-name-ml = malayalam
language-name-mn = monqol
language-name-mnc = mançu
language-name-mni = manipüri
language-name-moh = mohavk
language-name-mos = mosi
language-name-mr = marathi
language-name-ms = malay
language-name-mt = malta
language-name-mua = mundanq
language-name-mul = çoxsaylı dillər
language-name-mus = krik
language-name-mwl = mirand
language-name-mwr = maruari
language-name-my = birman
language-name-myv = erzya
language-name-mzn = mazandaran
language-name-na = nauru
language-name-nan = Min Nan
language-name-nap = neapolitan
language-name-naq = nama
language-name-nb = bokmal norveç
language-name-nd = şimali ndebele
language-name-nds = aşağı alman
language-name-nds_NL = aşağı sakson
language-name-ne = nepal
language-name-new = nevari
language-name-ng = ndonqa
language-name-nia = nias
language-name-niu = niyuan
language-name-nl = holland
language-name-nl_BE = flamand
language-name-nmg = kvasio
language-name-nn = nünorsk norveç
language-name-nnh = ngiemboon
language-name-no = norveç
language-name-nog = noqay
language-name-non = qədim nors
language-name-nqo = nqo
language-name-nr = cənubi ndebele
language-name-nso = şimal soto
language-name-nus = nuer
language-name-nv = navayo
language-name-ny = nyanca
language-name-nym = nyamvezi
language-name-nyn = nyankol
language-name-nyo = nyoro
language-name-nzi = nzima
language-name-oc = oksitan
language-name-oj = ocibva
language-name-om = oromo
language-name-or = odiya
language-name-os = osetin
language-name-osa = osage
language-name-ota = osman
language-name-pa = pəncab
language-name-pag = panqasinan
language-name-pal = pəhləvi
language-name-pam = pampanqa
language-name-pap = papyamento
language-name-pau = palayan
language-name-pcm = niger kreol
language-name-peo = qədim fars
language-name-phn = foyenik
language-name-pi = pali
language-name-pl = polyak
language-name-pon = ponpey
language-name-prg = pruss
language-name-pro = qədim provansal
language-name-ps = puştu
language-name-pt = portuqal
language-name-pt_BR = Braziliya portuqalcası
language-name-pt_PT = Portuqaliya portuqalcası
language-name-qu = keçua
language-name-quc = kiçe
language-name-raj = racastani
language-name-rap = rapanui
language-name-rar = rarotonqan
language-name-rm = romanş
language-name-rn = rundi
language-name-ro = rumın
language-name-ro_MD = moldav
language-name-rof = rombo
language-name-rom = roman
language-name-root = rut
language-name-ru = rus
language-name-rup = aroman
language-name-rw = kinyarvanda
language-name-rwk = rua
language-name-sa = sanskrit
language-name-sad = sandave
language-name-sah = saxa
language-name-sam = samaritan
language-name-saq = samburu
language-name-sas = sasak
language-name-sat = santal
language-name-sba = nqambay
language-name-sbp = sanqu
language-name-sc = sardin
language-name-scn = siciliya
language-name-sco = skots
language-name-sd = sindhi
language-name-sdh = cənubi kürd
language-name-se = şimali sami
language-name-seh = sena
language-name-sel = selkup
language-name-ses = koyraboro senni
language-name-sg = sanqo
language-name-sga = qədim irland
language-name-sh = serb-xorvat
language-name-shi = taçelit
language-name-shn = şan
language-name-si = sinhala
language-name-sid = sidamo
language-name-sk = slovak
language-name-sl = sloven
language-name-sm = samoa
language-name-sma = cənubi sami
language-name-smj = lule sami
language-name-smn = inari sami
language-name-sms = skolt sami
language-name-sn = şona
language-name-snk = soninke
language-name-so = somali
language-name-sog = soqdiyen
language-name-sq = alban
language-name-sr = serb
language-name-srn = sranan tonqo
language-name-srr = serer
language-name-ss = svati
language-name-ssy = saho
language-name-st = sesoto
language-name-su = sundan
language-name-suk = sukuma
language-name-sus = susu
language-name-sux = sumeryan
language-name-sv = isveç
language-name-sw = suahili
language-name-sw_CD = Konqo suahilicəsi
language-name-swb = komor
language-name-syr = suriya
language-name-ta = tamil
language-name-te = teluqu
language-name-tem = timne
language-name-teo = teso
language-name-ter = tereno
language-name-tet = tetum
language-name-tg = tacik
language-name-th = tay
language-name-ti = tiqrin
language-name-tig = tiqre
language-name-tiv = tiv
language-name-tk = türkmən
language-name-tkl = tokelay
language-name-tl = taqaloq
language-name-tlh = klinqon
language-name-tli = tlinqit
language-name-tmh = tamaşek
language-name-tn = svana
language-name-to = tonqa
language-name-tog = nyasa tonqa
language-name-tpi = tok pisin
language-name-tr = türk
language-name-trv = taroko
language-name-ts = sonqa
language-name-tsi = simşyan
language-name-tt = tatar
language-name-tum = tumbuka
language-name-tvl = tuvalu
language-name-tw = tvi
language-name-twq = tasavaq
language-name-ty = taxiti
language-name-tyv = tuvinyan
language-name-tzm = Mərkəzi Atlas tamazicəsi
language-name-udm = udmurt
language-name-ug = uyğur
language-name-uga = uqarit
language-name-uk = ukrayna
language-name-umb = umbundu
language-name-und = naməlum dil
language-name-ur = urdu
language-name-uz = özbək
language-name-vai = vai
language-name-ve = venda
language-name-vi = vyetnam
language-name-vo = volapük
language-name-vot = votik
language-name-vun = vunyo
language-name-wa = valun
language-name-wae = valles
language-name-wal = valamo
language-name-war = varay
language-name-was = vaşo
language-name-wbp = valpiri
language-name-wo = volof
language-name-wuu = vu
language-name-xal = kalmık
language-name-xh = xosa
language-name-xog = soqa
language-name-yao = yao
language-name-yap = yapiz
language-name-yav = yanqben
language-name-ybb = yemba
language-name-yi = idiş
language-name-yo = yoruba
language-name-yue = kanton
language-name-za = çjuan
language-name-zap = zapotek
language-name-zbl = blisimbols
language-name-zen = zenaqa
language-name-zgh = tamazi
language-name-zh = çin
language-name-zh_Hans = sadələşmiş çin
language-name-zh_Hant = ənənəvi çin
language-name-zu = zulu
language-name-zun = zuni
language-name-zxx = dil məzmunu yoxdur
language-name-zza = zaza
