language-name-ak = Akan
language-name-am = Amharik
language-name-ar = Larabci
language-name-be = Belarusanci
language-name-bg = Bulgaranci
language-name-bn = Bengali
language-name-cs = Harshen Cak
language-name-de = Jamusanci
language-name-el = Girkanci
language-name-en = Turanci
language-name-es = Ispaniyanci
language-name-fa = Parisanci
language-name-fr = Faransanci
language-name-ha = Hausa
language-name-hi = Harshen Hindi
language-name-hu = Harshen Hungari
language-name-id = Harshen Indunusiya
language-name-ig = Inyamuranci
language-name-it = Italiyanci
language-name-ja = Japananci
language-name-jv = Jabananci
language-name-km = Harshen Kimar
language-name-ko = Harshen Koreya
language-name-ms = Harshen Malai
language-name-my = Burmanci
language-name-ne = Nepali
language-name-nl = Holanci
language-name-pa = Punjabi
language-name-pl = Harshen Polan
language-name-pt = Harshen Portugal
language-name-ro = Romaniyanci
language-name-ru = Rashanci
language-name-rw = Kiniyaruwanda
language-name-so = Somali
language-name-sv = Harshen Suwedan
language-name-ta = Tamil
language-name-th = Thai
language-name-tr = Harshen Turkiyya
language-name-uk = Harshen Yukuren
language-name-ur = Harshen Urdu
language-name-vi = Harshen Biyetinam
language-name-yo = Yarbanci
language-name-zh = Harshen Sin
language-name-zu = Harshen Zulu
