language-name-ab = अब्खाज़ियन्
language-name-ace = अचेहनी
language-name-ach = अकोली
language-name-ada = अडांगमे
language-name-ady = अडीगे
language-name-ae = अवस्तन्
language-name-af = अफ्रीकी
language-name-afh = अफ्रीहीली
language-name-ain = ऐनू
language-name-ak = अकन
language-name-akk = अकाडिनी
language-name-ale = अलुट
language-name-am = अम्हारिक्
language-name-an = आर्गोनी
language-name-ang = पुरानी अंग्रेज़ी
language-name-anp = अंगीका
language-name-ar = अरबी
language-name-arc = अरामाईक
language-name-arp = अरापाहो
language-name-arw = अरावाक
language-name-as = असामी
language-name-av = अवारिक्
language-name-awa = अवधी
language-name-ay = आयमारा
language-name-az = अज़रबैजानी
language-name-ba = बशख़िर्
language-name-bal = बलूची
language-name-ban = बालिनी
language-name-bas = बास्क़्
language-name-be = बैलोरूसियन्
language-name-bej = बेजा
language-name-bem = बेंबा
language-name-bg = बल्गैरियन्
language-name-bho = भोजपुरी
language-name-bi = बिस्लामा
language-name-bik = बिकोल्
language-name-bin = बिनी
language-name-bla = सीकसीका
language-name-bm = बांबारा
language-name-bn = बंगला
language-name-bo = तिब्बती
language-name-br = ब्रटों
language-name-bra = ब्रज
language-name-brx = बड़ो
language-name-bs = बोस्नियाई
language-name-bua = बुरियात
language-name-bug = बुगीनी
language-name-byn = ब्लीन
language-name-ca = कातालान्
language-name-cad = काद्दौ
language-name-car = कारीब्
language-name-cch = आत्सम
language-name-ce = चेचेन्
language-name-ceb = चेबुआनो
language-name-ch = चामोरो
language-name-chb = चीबचा
language-name-chg = चगताई
language-name-chk = चुकेसे
language-name-chm = मारी
language-name-chn = चीनूक् जार्गन्
language-name-cho = चौक्टो
language-name-chp = चिपेवियान्
language-name-chr = चीरोकी
language-name-chy = शायान्
language-name-co = कोर्सीकन्
language-name-cop = कॉप्टीक्
language-name-cr = क्री
language-name-crh = तुर्की क्रिमिया
language-name-cs = चेक्
language-name-csb = काशुबियान्
language-name-cu = चर्च स्लाविक्
language-name-cv = चुवाश्
language-name-cy = वैल्श्
language-name-da = डैनीश्
language-name-dak = डकौटा
language-name-dar = दर्गवा
language-name-de = ज़र्मन
language-name-de_CH = उच्च स्तरिय स्वीस जर्मन
language-name-del = दलावार्
language-name-den = स्लेव्
language-name-dgr = डोगरीब्
language-name-din = डींगका
language-name-doi = डोगरी
language-name-dsb = सोर्बियन्
language-name-dua = डुआला
language-name-dum = मध्य डच
language-name-dv = दीवेही
language-name-dyu = द्युआला
language-name-dz = भुटानी
language-name-ee = एवे
language-name-efi = एफीक्
language-name-egy = प्राचीन मिस्री
language-name-eka = एकाजुक
language-name-el = ग्रीक
language-name-elx = एलामी
language-name-en = अंग्रेज़ी
language-name-enm = मध्य अंग्रेज़ी
language-name-eo = एस्पेरान्तो
language-name-es = स्पैनिश
language-name-es_419 = लैटिन अमरिकी स्पैनिश
language-name-es_ES = ईवेरियाई स्पैनिश
language-name-et = ऐस्टोनियन्
language-name-eu = बास्क्
language-name-ewo = एवौंडो
language-name-fa = फार्सी
language-name-fan = फाँग्
language-name-fat = फाँटी
language-name-ff = फुलाह्
language-name-fi = फिनिश्
language-name-fil = फिलिपिनो
language-name-fj = फ़ीजी
language-name-fo = फिरोज़ी
language-name-fon = फोन
language-name-fr = फ्रांसीसी
language-name-frm = मध्य फ्रांसीसी
language-name-fro = पुरानी फ्रांसीसी
language-name-frr = उत्तरी फ्रीज़ियन्
language-name-frs = पूर्वी फ्रीज़ियन्
language-name-fur = फ्रीउलीअन्
language-name-fy = पश्चीमी फ्रीज़ियन्
language-name-ga = आईरिश
language-name-gaa = गा
language-name-gay = गायो
language-name-gba = ग्बाया
language-name-gd = स्कॉट्स् गैलिक्
language-name-gez = गीज़्
language-name-gil = गीलबर्टी
language-name-gl = गैलिशियन्
language-name-gmh = मध्य उच्चस्तरी जर्मन
language-name-gn = गुआरानी
language-name-goh = पुरानी उच्चस्तरी जर्मन
language-name-gon = गाँडी
language-name-gor = गोरंटालो
language-name-got = गॉथिक
language-name-grb = ग्रेबो
language-name-grc = प्राचीन यूनानी
language-name-gsw = स्वीस जर्मन
language-name-gu = गुजराती
language-name-gv = मैंक्स
language-name-gwi = ग्वीचलीन
language-name-ha = हउसा
language-name-hai = हईडा
language-name-haw = हवाईअन
language-name-he = हिब्रु
language-name-hi = हिंदी
language-name-hil = हीलीगैनोन
language-name-hit = हीत्ती
language-name-hmn = ह्मौंग
language-name-ho = हीरी मोटु
language-name-hr = क्रोएशन्
language-name-hsb = ऊपरी सौर्बियन
language-name-ht = हाईशीयन्
language-name-hu = हंगैरीयन्
language-name-hup = हूपा
language-name-hy = अरमेनियन्
language-name-hz = हेरेरो
language-name-ia = ईन्टरलिंग्वा
language-name-iba = ईबान्
language-name-id = इन्डोनेशियन्
language-name-ie = ईन्टरलिंग्वे
language-name-ig = ईग्बो
language-name-ii = सीचुआन् यी
language-name-ik = इनुपियाक़्
language-name-ilo = ईलोको
language-name-inh = ईंगुष
language-name-io = ईडो
language-name-is = आईस्लैंडिक्
language-name-it = ईटालियन्
language-name-iu = इनूक्टीटूत्
language-name-ja = जापानी
language-name-jbo = लोजबान
language-name-jpr = यहुदी फ़ारसी
language-name-jrb = यहुदी अरबी
language-name-jv = जावानीस
language-name-ka = जॉर्जियन्
language-name-kaa = कारा कलपक
language-name-kab = काबील्
language-name-kac = कचीन्
language-name-kaj = जु
language-name-kam = कंबा
language-name-kaw = कावी
language-name-kbd = कबार्डी भाषा
language-name-kcg = त्याप्
language-name-kfo = कोरो
language-name-kg = कॉंगो
language-name-kha = ख़ासी
language-name-kho = ख़ोतानी
language-name-ki = किकुयु
language-name-kj = कुआनयामा
language-name-kk = क़ज़ाख़्
language-name-kl = कलालीसुत
language-name-km = ख्मेर
language-name-kmb = कींबुंडु
language-name-kn = कन्नड्
language-name-ko = कोरीयन्
language-name-kok = कोंकणी
language-name-kos = कोस्राईयन्
language-name-kpe = क्पेले
language-name-kr = कनुरी
language-name-krc = कराचय् बलकार्
language-name-krl = करेलियन्
language-name-kru = कुरुख़्
language-name-ks = कश्मिरी
language-name-ku = कुर्दी
language-name-kum = कुमीक्
language-name-kut = कुतेनाई
language-name-kv = कोमी
language-name-kw = कौर्नवॉली
language-name-ky = किरग़ीज़्
language-name-la = लैटीन्
language-name-lad = लाड़ीनो
language-name-lah = लाह्डां
language-name-lam = लांबा
language-name-lb = लुक्समबुर्गी
language-name-lez = लेज़गीयान
language-name-lg = गांडा
language-name-li = लींबुर्गी
language-name-ln = लिंगाला
language-name-lo = लाओसीयन्
language-name-lol = मोंगो
language-name-loz = लोज़ी
language-name-lt = लिथुआनियन्
language-name-lu = लुबा कटांगा
language-name-lua = लुबा लुलुआ
language-name-lui = लुईसेनो
language-name-lun = लुंडा
language-name-luo = लुओ
language-name-lus = लुशाई
language-name-mad = मादुरी
language-name-mag = मघी
language-name-mai = मैथीली
language-name-mak = मक्सर
language-name-man = मांडींगो
language-name-mas = मसाई
language-name-mdf = मोक्षा
language-name-mdr = मंदार
language-name-men = मेंदे
language-name-mg = मालागासी
language-name-mga = मध्य आईरीश भाषा
language-name-mh = मार्शली
language-name-mi = माओरी
language-name-mic = मीकमाक
language-name-min = मिनंगकाबाउ
language-name-mk = मैसेडोनियन्
language-name-ml = मलयालम
language-name-mn = मोंगोलियन
language-name-mnc = मांचु
language-name-mni = मणीपुरी
language-name-moh = मोहोक
language-name-mos = मोस्सी
language-name-mr = मराठी
language-name-ms = मलाय
language-name-mt = मालटीज़्
language-name-mus = क्रीक
language-name-mwl = मीरांडी
language-name-mwr = मारवाड़ी
language-name-my = बर्मी
language-name-myv = ऐर्ज़िया
language-name-na = नाऊरू
language-name-nap = नेआपोलिटन
language-name-nb = नोर्वेगी बोकमाल
language-name-nd = उत्तर न्दबेले
language-name-nds = नीजी स्तरिय जर्मन
language-name-ne = नेपाली
language-name-new = नेवारी
language-name-ng = न्डोंगा
language-name-nia = नियास
language-name-niu = नियुइआन
language-name-nl = डच्
language-name-nl_BE = फ्लेमी
language-name-nn = नॉर्वेजियन् नीनॉर्स्क्
language-name-no = नॉर्वेजीयन्
language-name-nog = नोगाई
language-name-non = पुरानी नॉर्स्
language-name-nqo = न्गको
language-name-nr = दक्षिणी न्दबेले
language-name-nv = नावाहो
language-name-nwc = पुरानी नेवारी
language-name-ny = न्यानजा
language-name-nym = न्यामवेज़ी
language-name-nyn = न्यानकोले
language-name-nyo = न्यौरो
language-name-nzi = न्ज़ीमा
language-name-oc = ओक्सीतान
language-name-oj = ओहीबवा
language-name-or = उड़िया
language-name-os = ओस्सेटी
language-name-osa = ओसेज
language-name-ota = तुर्की ओटोमान
language-name-pa = पंजाबी
language-name-pag = पांगासीनन
language-name-pal = पहलवी
language-name-pam = पंपंगा
language-name-pap = पापीआमेन्तो
language-name-pau = पालाऊ
language-name-peo = पुरानी फ़ारसी
language-name-phn = फीनीसी
language-name-pi = पाली
language-name-pl = पोलिश
language-name-pon = पोहनपी
language-name-pro = पुरानी प्रोवाँसाल
language-name-ps = पख़्तु
language-name-pt = पुर्तगाली
language-name-qu = क्वेचुआ
language-name-raj = राजस्थानी
language-name-rap = रापानुई
language-name-rar = रारोटोंगा
language-name-rm = रेह्टो-रोमान्स
language-name-rn = किरून्दी
language-name-ro = रूमानीयन्
language-name-ro_MD = मोल्डेवियन्
language-name-rom = रुमानी
language-name-root = रुट
language-name-ru = रुसी
language-name-rup = आरोमानी
language-name-rw = किन्यारुआण्डा
language-name-sa = संस्कृत्
language-name-sad = संडावे
language-name-sah = यकुट्
language-name-sam = समारीती आरामाईक़
language-name-sas = सासक
language-name-sat = संताली
language-name-sc = सार्दीनी
language-name-scn = सीसीलीअन
language-name-sco = स्कॉट
language-name-sd = सिंधी
language-name-se = उत्तरी सामी
language-name-sel = सेलकुप
language-name-sg = सांग्रो
language-name-sga = पुरानी आईरीश
language-name-sh = सर्बो-क्रोएशन्
language-name-shn = शान
language-name-si = सींहाला
language-name-sid = सीदामो
language-name-sk = स्लोवाक्
language-name-sl = स्लोवेनियन्
language-name-sm = सामोअन
language-name-sma = पश्चीमी सामी
language-name-smj = लुले सामी
language-name-smn = ईनारी सामी
language-name-sms = स्कोल्ट् सामी
language-name-sn = शोना
language-name-snk = सोनिंगके
language-name-so = सोमाली
language-name-sog = सोगडीयन
language-name-sq = आल्बेनियन्
language-name-sr = सर्बियन्
language-name-srn = स्रनान् टॉंगो
language-name-srr = सेरेर
language-name-ss = स्वाटि
language-name-su = सुन्दानी
language-name-suk = सुकुमा
language-name-sus = सुसु
language-name-sux = सुमेरिअन
language-name-sv = स्वीडिश
language-name-sw = स्वाहिली
language-name-syc = पारंपरीक सिरिआक
language-name-syr = सिरिआक
language-name-ta = तमिळ
language-name-te = तेलुगु
language-name-tem = तीमने
language-name-ter = तेरेनो
language-name-tet = तेतुम
language-name-tg = ताजिक्
language-name-th = थाई
language-name-ti = तिग्रीन्या
language-name-tig = टीग्रे
language-name-tiv = टीव्
language-name-tk = तुर्कमेन
language-name-tkl = टोकेलौ
language-name-tl = तागालोग
language-name-tlh = क्लींगदन
language-name-tli = ट्लिंगीत
language-name-tmh = तमाशेक
language-name-tn = त्स्वाना
language-name-to = टॉंगा
language-name-tog = न्यासा टॉंगा
language-name-tpi = तोक पिसीन
language-name-tr = तुर्की
language-name-ts = सोंगा
language-name-tsi = त्सीमशीआन्
language-name-tt = टाटर्
language-name-tum = टुँबुका
language-name-tvl = टुवालु
language-name-tw = ट्वी
language-name-ty = टाहिटि
language-name-tyv = टुवी
language-name-udm = उड़मुर्त
language-name-ug = उईग़ुर
language-name-uga = उगारिती
language-name-uk = यूक्रेनियन्
language-name-umb = उंबुंडु
language-name-und = अज्ञात या अवैध भाषा
language-name-ur = ऊर्दु
language-name-uz = उज़बेक्
language-name-vai = वाई
language-name-ve = वेंडा
language-name-vi = वियेतनामी
language-name-vo = वोलापोक
language-name-vot = वोटीक
language-name-wa = वालुन
language-name-wal = वालामो
language-name-war = वारय
language-name-was = वाशो
language-name-wo = वोलोफ
language-name-xal = कालमीक
language-name-xh = ख़ोसा
language-name-yao = याओ
language-name-yap = यापीज़
language-name-yi = यीद्दीश
language-name-yo = योरूबा
language-name-za = ज़ुआंग
language-name-zap = ज़ापोतेक
language-name-zbl = ब्लीस चिन्ह
language-name-zen = ज़ेनागा
language-name-zh = चीनी
language-name-zu = ज़ुलू
language-name-zun = ज़ुनी
language-name-zxx = रिक्त
language-name-zza = ज़ाज़ा
