language-name-ak = akaŋ
language-name-am = amharik
language-name-ar = arabiya
language-name-be = belarussiya
language-name-bg = bulgaria
language-name-bn = bengalia
language-name-cs = syekya
language-name-de = germaŋ
language-name-el = grek
language-name-en = zah Anglofoŋ
language-name-es = Espaniya
language-name-fa = Persia
language-name-fr = zah sǝr Franssǝ
language-name-ha = haussa
language-name-hi = hindi
language-name-hu = hungariya
language-name-id = indonesiya
language-name-ig = igbo
language-name-it = italiya
language-name-ja = zah sǝr Japoŋ
language-name-jv = javaniya
language-name-km = kmer
language-name-ko = korea
language-name-ms = malasiya
language-name-mua = MUNDAŊ
language-name-my = birmania
language-name-ne = Nepaliya
language-name-nl = zah sǝr ma kasǝŋ
language-name-pa = Pǝnjabi
language-name-pl = Poloniya
language-name-pt = Zah sǝr Portugal
language-name-ro = Romaniya
language-name-ru = Russiya
language-name-rw = Zah sǝr Rwanda
language-name-so = Somaliya
language-name-sv = Swedia
language-name-ta = Tamul
language-name-th = th
language-name-tr = Turk
language-name-uk = Ukrainia
language-name-ur = Urdu
language-name-vi = Vietnamiya
language-name-yo = Yoruba
language-name-zh = zah Syiŋ
language-name-zu = Zulu
