language-name-aa = Afar
language-name-ab = Abchasais
language-name-ace = Basa Acèh
language-name-ach = Acoli
language-name-ada = Adangme
language-name-ady = Adyghe
language-name-ae = Avestanais
language-name-aeb = Arabais Thuiniseach
language-name-af = Afraganais
language-name-afh = Afrihili
language-name-agq = Aghem
language-name-ain = Ainu
language-name-ak = Akan
language-name-akk = Acadais
language-name-akz = Alabama
language-name-ale = Aleutais
language-name-aln = Albàinis Ghegeach
language-name-alt = Altais Dheasach
language-name-am = Amtharais
language-name-an = Aragonais
language-name-ang = Seann-Bheurla
language-name-anp = Angika
language-name-ar = Arabais
language-name-ar_001 = Nuadh-Arabais Stannardach
language-name-arc = Aramais
language-name-arn = Mapudungun
language-name-aro = Araona
language-name-arp = Arapaho
language-name-arq = Arabais Aildireach
language-name-arw = Arawak
language-name-ary = Arabais Mhorocach
language-name-arz = Arabais Èipheiteach
language-name-as = Asamais
language-name-asa = Asu
language-name-ase = Cainnt-shanais na h-Aimeireaga
language-name-ast = Astùrais
language-name-av = Avarais
language-name-avk = Kotava
language-name-awa = Awadhi
language-name-ay = Aymara
language-name-az = Asarbaideànais
language-name-ba = Bashkir
language-name-bal = Baluchì
language-name-ban = Cànan Bali
language-name-bas = Basaa
language-name-bax = Bamun
language-name-bbc = Batak Toba
language-name-bbj = Ghomala
language-name-be = Bealaruisis
language-name-bej = Beja
language-name-bem = Bemba
language-name-bew = Betawi
language-name-bez = Bena
language-name-bfd = Bafut
language-name-bfq = Badaga
language-name-bg = Bulgarais
language-name-bgn = Balochi Shiarach
language-name-bho = Bhojpuri
language-name-bi = Bislama
language-name-bik = Bikol
language-name-bin = Bini
language-name-bjn = Banjar
language-name-bkm = Kom
language-name-bla = Siksika
language-name-bm = Bambara
language-name-bn = Bangla
language-name-bo = Tibeitis
language-name-bpy = Bishnupriya
language-name-bqi = Bakhtiari
language-name-br = Breatnais
language-name-bra = Braj
language-name-brh = Brahui
language-name-brx = Bodo
language-name-bs = Bosnais
language-name-bss = Akoose
language-name-bua = Buriat
language-name-bug = Cànan nam Bugis
language-name-bum = Bulu
language-name-byn = Blin
language-name-byv = Medumba
language-name-ca = Catalanais
language-name-cad = Caddo
language-name-car = Carib
language-name-cay = Cayuga
language-name-cch = Atsam
language-name-ce = Deideanais
language-name-ceb = Cebuano
language-name-cgg = Chiga
language-name-ch = Chamorro
language-name-chb = Chibcha
language-name-chg = Chagatai
language-name-chk = Cànan Chuuk
language-name-chm = Mari
language-name-chn = Chinuk Wawa
language-name-cho = Choctaw
language-name-chp = Chipewyan
language-name-chr = Cherokee
language-name-chy = Cheyenne
language-name-ckb = Cùrdais Mheadhanach
language-name-co = Corsais
language-name-cop = Coptais
language-name-cps = Capiznon
language-name-cr = Cree
language-name-crh = Turcais Chriomach
language-name-crs = Seiseallais
language-name-cs = Seicis
language-name-csb = Caisiubais
language-name-cu = Slàbhais na h-Eaglaise
language-name-cv = Chuvash
language-name-cy = Cuimris
language-name-da = Danmhairgis
language-name-dak = Dakota
language-name-dar = Dargwa
language-name-dav = Taita
language-name-de = Gearmailtis
language-name-de_AT = Gearmailtis na h-Ostaire
language-name-de_CH = Àrd-Ghearmailtis na h-Eilbheise
language-name-del = Delaware
language-name-den = Slavey
language-name-dgr = Dogrib
language-name-din = Dinka
language-name-dje = Zarma
language-name-doi = Dogri
language-name-dsb = Sòrbais Ìochdarach
language-name-dtp = Dusun Mheadhanach
language-name-dua = Duala
language-name-dum = Meadhan-Dhuitsis
language-name-dv = Divehi
language-name-dyo = Jola-Fonyi
language-name-dyu = Dyula
language-name-dz = Dzongkha
language-name-dzg = Dazaga
language-name-ebu = Embu
language-name-ee = Ewe
language-name-efi = Efik
language-name-egy = Èipheitis Àrsaidh
language-name-eka = Ekajuk
language-name-el = Greugais
language-name-elx = Elamais
language-name-en = Beurla
language-name-en_AU = Beurla Astràilia
language-name-en_CA = Beurla Chanada
language-name-en_GB = Beurla Bhreatainn
language-name-en_US = Beurla na h-Aimeireaga
language-name-enm = Meadhan-Bheurla
language-name-eo = Esperanto
language-name-es = Spàinntis
language-name-es_419 = Spàinntis na h-Aimeireaga Laidinneach
language-name-es_ES = Spàinntis Eòrpach
language-name-es_MX = Spàinntis Mheagsagach
language-name-esu = Yupik Mheadhanach
language-name-et = Eastoinis
language-name-eu = Basgais
language-name-ewo = Ewondo
language-name-ext = Cànan na h-Extremadura
language-name-fa = Peirsis
language-name-fan = Fang
language-name-fat = Fanti
language-name-ff = Fulah
language-name-fi = Fionnlannais
language-name-fil = Filipinis
language-name-fit = Meänkieli
language-name-fj = Fìdis
language-name-fo = Fàrothais
language-name-fon = Fon
language-name-fr = Fraingis
language-name-fr_CA = Fraingis Chanada
language-name-fr_CH = Fraingis Eilbheiseach
language-name-frc = Fraingis nan Cajun
language-name-frm = Meadhan-Fhraingis
language-name-fro = Seann-Fhraingis
language-name-frp = Arpitan
language-name-frr = Frìoslannais Thuathach
language-name-frs = Frìoslannais Earach
language-name-fur = Friùilis
language-name-fy = Frìoslannais Shiarach
language-name-ga = Gaeilge
language-name-gaa = Ga
language-name-gag = Gagauz
language-name-gan = Gan
language-name-gay = Gayo
language-name-gba = Gbaya
language-name-gbz = Dari Zoroastrach
language-name-gd = Gàidhlig
language-name-gez = Ge’ez
language-name-gil = Ciribeasais
language-name-gl = Gailìsis
language-name-glk = Gilaki
language-name-gmh = Meadhan-Àrd-Gearmailtis
language-name-gn = Guaraní
language-name-goh = Seann-Àrd-Gearmailtis
language-name-gom = Konkani Goa
language-name-gon = Gondi
language-name-gor = Gorontalo
language-name-got = Gotais
language-name-grb = Grebo
language-name-grc = Greugais Àrsaidh
language-name-gsw = Gearmailtis Eilbheiseach
language-name-gu = Gujarati
language-name-guc = Wayuu
language-name-gur = Frafra
language-name-guz = Gusii
language-name-gv = Gaelg
language-name-gwi = Gwichʼin
language-name-ha = Hausa
language-name-hai = Haida
language-name-hak = Hakka
language-name-haw = Cànan Hawai’i
language-name-he = Eabhra
language-name-hi = Hindis
language-name-hif = Hindis Fhìditheach
language-name-hil = Hiligaynon
language-name-hit = Cànan Het
language-name-hmn = Hmong
language-name-ho = Hiri Motu
language-name-hr = Cròthaisis
language-name-hsb = Sòrbais Uachdarach
language-name-hsn = Xiang
language-name-ht = Crìtheol Haidhti
language-name-hu = Ungairis
language-name-hup = Hupa
language-name-hy = Airmeinis
language-name-hz = Herero
language-name-ia = Interlingua
language-name-iba = Iban
language-name-ibb = Ibibio
language-name-id = Innd-Innsis
language-name-ie = Interlingue
language-name-ig = Igbo
language-name-ii = Yi Sichuan
language-name-ik = Inupiaq
language-name-ilo = Iloko
language-name-inh = Ingush
language-name-io = Ido
language-name-is = Innis Tìlis
language-name-it = Eadailtis
language-name-iu = Inuktitut
language-name-ja = Seapanais
language-name-jam = Beurla Crìtheolach Diameuga
language-name-jbo = Lojban
language-name-jgo = Ngomba
language-name-jmc = Machame
language-name-jpr = Peirsis Iùdhach
language-name-jrb = Arabais Iùdhach
language-name-jv = Deàbhanais
language-name-ka = Cairtbheilis
language-name-kaa = Kara-Kalpak
language-name-kab = Kabyle
language-name-kac = Kachin
language-name-kaj = Jju
language-name-kam = Kamba
language-name-kaw = Kawi
language-name-kbd = Cabardais
language-name-kbl = Kanembu
language-name-kcg = Tyap
language-name-kde = Makonde
language-name-kea = Kabuverdianu
language-name-ken = Kenyang
language-name-kfo = Koro
language-name-kg = Kongo
language-name-kgp = Kaingang
language-name-kha = Khasi
language-name-kho = Cànan Khotan
language-name-khq = Koyra Chiini
language-name-khw = Khowar
language-name-ki = Kikuyu
language-name-kiu = Kirmanjki
language-name-kj = Kuanyama
language-name-kk = Casachais
language-name-kkj = Kako
language-name-kl = Kalaallisut
language-name-kln = Kalenjin
language-name-km = Cmèar
language-name-kmb = Kimbundu
language-name-kn = Kannada
language-name-ko = Coirèanais
language-name-koi = Komi-Permyak
language-name-kok = Konkani
language-name-kpe = Kpelle
language-name-kr = Kanuri
language-name-krc = Karachay-Balkar
language-name-kri = Krio
language-name-krj = Kinaray-a
language-name-krl = Cairealais
language-name-kru = Kurukh
language-name-ks = Caismiris
language-name-ksb = Shambala
language-name-ksf = Bafia
language-name-ksh = Gearmailtis Chologne
language-name-ku = Cùrdais
language-name-kum = Kumyk
language-name-kut = Kutenai
language-name-kv = Komi
language-name-kw = Còrnais
language-name-ky = Cìorgasais
language-name-la = Laideann
language-name-lad = Ladino
language-name-lag = Langi
language-name-lah = Lahnda
language-name-lam = Lamba
language-name-lb = Lugsamburgais
language-name-lez = Leasgais
language-name-lfn = Lingua Franca Nova
language-name-lg = Ganda
language-name-li = Cànan Limburg
language-name-lij = Liogùrais
language-name-lkt = Lakhóta
language-name-lmo = Lombardais
language-name-ln = Lingala
language-name-lo = Làtho
language-name-lol = Mongo
language-name-loz = Lozi
language-name-lrc = Luri Thuathach
language-name-lt = Liotuainis
language-name-lu = Luba-Katanga
language-name-lua = Luba-Lulua
language-name-lui = Luiseño
language-name-lun = Lunda
language-name-luo = Luo
language-name-lus = Mizo
language-name-luy = Luyia
language-name-lv = Laitbheis
language-name-lzh = Sìnis an Litreachais
language-name-lzz = Laz
language-name-mad = Cànan Madhura
language-name-maf = Mafa
language-name-mag = Magahi
language-name-mai = Maithili
language-name-mak = Makasar
language-name-man = Mandingo
language-name-mas = Maasai
language-name-mde = Maba
language-name-mdf = Moksha
language-name-mdr = Mandar
language-name-men = Mende
language-name-mer = Meru
language-name-mfe = Morisyen
language-name-mg = Malagasais
language-name-mga = Meadhan-Ghaeilge
language-name-mgh = Makhuwa-Meetto
language-name-mgo = Meta’
language-name-mh = Marshallais
language-name-mi = Māori
language-name-mic = Mi’kmaq
language-name-min = Minangkabau
language-name-mk = Masadonais
language-name-ml = Malayalam
language-name-mn = Mongolais
language-name-mnc = Manchu
language-name-mni = Manipuri
language-name-moh = Mohawk
language-name-mos = Mossi
language-name-mr = Marathi
language-name-mrj = Mari Shiarach
language-name-ms = Malaidhis
language-name-mt = Maltais
language-name-mua = Mundang
language-name-mul = Iomadh cànan
language-name-mus = Creek
language-name-mwl = Miorandais
language-name-mwr = Marwari
language-name-mwv = Mentawai
language-name-my = Burmais
language-name-mye = Myene
language-name-myv = Erzya
language-name-mzn = Mazanderani
language-name-na = Nabhru
language-name-nan = Min Nan
language-name-nap = Eadailtis Napoli
language-name-naq = Nama
language-name-nb = Bokmål na Nirribhidh
language-name-nd = Ndebele Thuathach
language-name-nds = Gearmailtis Ìochdarach
language-name-nds_NL = Sagsannais Ìochdarach
language-name-ne = Neapàlais
language-name-new = Newari
language-name-ng = Ndonga
language-name-nia = Nias
language-name-niu = Cànan Niue
language-name-njo = Ao Naga
language-name-nl = Duitsis
language-name-nl_BE = Flannrais
language-name-nmg = Kwasio
language-name-nn = Nynorsk na Nirribhidh
language-name-nnh = Ngiemboon
language-name-no = Nirribhis
language-name-nog = Nogai
language-name-non = Seann-Lochlannais
language-name-nov = Novial
language-name-nqo = N’Ko
language-name-nr = Ndebele Dheasach
language-name-nso = Sesotho sa Leboa
language-name-nus = Nuer
language-name-nv = Navajo
language-name-nwc = Newari Chlasaigeach
language-name-ny = Nyanja
language-name-nym = Nyamwezi
language-name-nyn = Nyankole
language-name-nyo = Nyoro
language-name-nzi = Nzima
language-name-oc = Ogsatanais
language-name-oj = Ojibwa
language-name-om = Oromo
language-name-or = Odia
language-name-os = Ossetic
language-name-osa = Osage
language-name-ota = Turcais Otomanach
language-name-pa = Panjabi
language-name-pag = Pangasinan
language-name-pal = Pahlavi
language-name-pam = Pampanga
language-name-pap = Papiamentu
language-name-pau = Palabhais
language-name-pcd = Picard
language-name-pcm = Beurla Nigèiriach
language-name-pdc = Gearmailtis Phennsylvania
language-name-pdt = Plautdietsch
language-name-peo = Seann-Pheirsis
language-name-phn = Phenicis
language-name-pi = Pali
language-name-pl = Pòlainnis
language-name-pms = Piedmontese
language-name-pon = Cànan Pohnpei
language-name-prg = Pruisis
language-name-pro = Seann-Phrovençal
language-name-ps = Pashto
language-name-pt = Portagailis
language-name-pt_BR = Portagailis Bhraisileach
language-name-pt_PT = Portagailis Eòrpach
language-name-qu = Quechua
language-name-quc = K’iche’
language-name-qug = Quichua Àrd-tìr Chimborazo
language-name-raj = Rajasthani
language-name-rap = Rapa Nui
language-name-rar = Cànan Rarotonga
language-name-rgn = Romagnol
language-name-rm = Rumains
language-name-rn = Kirundi
language-name-ro = Romàinis
language-name-ro_MD = Moldobhais
language-name-rof = Rombo
language-name-rom = Romanais
language-name-root = Root
language-name-ru = Ruisis
language-name-rue = Rusyn
language-name-rug = Roviana
language-name-rup = Aromanais
language-name-rw = Kinyarwanda
language-name-rwk = Rwa
language-name-sa = Sanskrit
language-name-sad = Sandawe
language-name-sah = Sakha
language-name-sam = Aramais Shamaritanach
language-name-saq = Samburu
language-name-sas = Sasak
language-name-sat = Santali
language-name-saz = Saurashtra
language-name-sba = Ngambay
language-name-sbp = Sangu
language-name-sc = Sàrdais
language-name-scn = Sisilis
language-name-sco = Albais
language-name-sd = Sindhi
language-name-sdc = Sassarese
language-name-sdh = Cùrdais Dheasach
language-name-se = Sàmais Thuathach
language-name-see = Seneca
language-name-seh = Sena
language-name-sei = Seri
language-name-sel = Selkup
language-name-ses = Koyraboro Senni
language-name-sg = Sango
language-name-sga = Seann-Ghaeilge
language-name-sh = Sèirb-Chròthaisis
language-name-shi = Tachelhit
language-name-shn = Shan
language-name-shu = Arabais Seàdach
language-name-si = Sinhala
language-name-sid = Sidamo
language-name-sk = Slòbhacais
language-name-sl = Slòbhainis
language-name-sly = Selayar
language-name-sm = Samothais
language-name-sma = Sàmais Dheasach
language-name-smj = Sàmais Lule
language-name-smn = Sàmais Inari
language-name-sms = Sàmais Skolt
language-name-sn = Shona
language-name-snk = Soninke
language-name-so = Somàilis
language-name-sq = Albàinis
language-name-sr = Sèirbis
language-name-srn = Sranan Tongo
language-name-srr = Serer
language-name-ss = Swati
language-name-ssy = Saho
language-name-st = Sesotho
language-name-su = Cànan Sunda
language-name-suk = Sukuma
language-name-sus = Susu
language-name-sux = Cànan Sumer
language-name-sv = Suainis
language-name-sw = Kiswahili
language-name-sw_CD = Kiswahili na Congo
language-name-swb = Comorais
language-name-syc = Suraidheac Chlasaigeach
language-name-syr = Suraidheac
language-name-ta = Taimilis
language-name-tcy = Tulu
language-name-te = Telugu
language-name-tem = Timne
language-name-teo = Teso
language-name-ter = Terêna
language-name-tet = Tetum
language-name-tg = Taidigis
language-name-th = Cànan nan Tàidh
language-name-ti = Tigrinya
language-name-tig = Tigre
language-name-tiv = Tiv
language-name-tk = Turcmanais
language-name-tkl = Tokelau
language-name-tkr = Tsakhur
language-name-tl = Tagalog
language-name-tlh = Klingon
language-name-tli = Tlingit
language-name-tly = Talysh
language-name-tmh = Tamashek
language-name-tn = Tswana
language-name-to = Tonga
language-name-tog = Nyasa Tonga
language-name-tpi = Tok Pisin
language-name-tr = Turcais
language-name-tru = Turoyo
language-name-trv = Taroko
language-name-ts = Tsonga
language-name-tsi = Tsimshian
language-name-tt = Tatarais
language-name-ttt = Tati
language-name-tum = Tumbuka
language-name-tvl = Tubhalu
language-name-tw = Twi
language-name-twq = Tasawaq
language-name-ty = Cànan Tahiti
language-name-tyv = Cànan Tuva
language-name-tzm = Tamazight an Atlais Mheadhanaich
language-name-udm = Udmurt
language-name-ug = Ùigiurais
language-name-uk = Ucràinis
language-name-umb = Umbundu
language-name-und = Cànan neo-aithnichte
language-name-ur = Ùrdu
language-name-uz = Usbagais
language-name-vai = Vai
language-name-ve = Venda
language-name-vep = Veps
language-name-vi = Bhiet-Namais
language-name-vls = Flannrais Siarach
language-name-vo = Volapük
language-name-vro = Võro
language-name-vun = Vunjo
language-name-wa = Walloon
language-name-wae = Gearmailtis Wallis
language-name-wal = Wolaytta
language-name-war = Waray
language-name-was = Washo
language-name-wbp = Warlpiri
language-name-wo = Wolof
language-name-wuu = Wu
language-name-xal = Kalmyk
language-name-xh = Xhosa
language-name-xog = Soga
language-name-yao = Yao
language-name-yap = Cànan Yap
language-name-yav = Yangben
language-name-ybb = Yemba
language-name-yi = Iùdhais
language-name-yo = Yoruba
language-name-yrl = Nheengatu
language-name-yue = Cantonais
language-name-za = Zhuang
language-name-zap = Zapotec
language-name-zbl = Comharran Bliss
language-name-zea = Cànan Zeeland
language-name-zen = Zenaga
language-name-zgh = Tamazight Stannardach Moroco
language-name-zh = Sìnis
language-name-zh_Hans = Sìnis Shimplichte
language-name-zh_Hant = Sìnis Thradaiseanta
language-name-zu = Zulu
language-name-zun = Zuñi
language-name-zxx = Susbaint nach eil ’na chànan
language-name-zza = Zazaki
