language-name-aa = àfar
language-name-ab = abkhaz
language-name-ace = atjeh
language-name-ach = acoli
language-name-ada = adangme
language-name-ady = adigué
language-name-ae = avèstic
language-name-af = afrikaans
language-name-afh = afrihili
language-name-agq = aghem
language-name-ain = ainu
language-name-ak = àkan
language-name-akk = accadi
language-name-akz = alabama
language-name-ale = aleuta
language-name-aln = albanès geg
language-name-alt = altaic meridional
language-name-am = amhàric
language-name-an = aragonès
language-name-ang = anglès antic
language-name-anp = angika
language-name-ar = àrab
language-name-ar_001 = àrab estàndard modern
language-name-arc = arameu
language-name-arn = mapudungu
language-name-aro = araona
language-name-arp = arapaho
language-name-ars = àrab najdi
language-name-arw = arauac
language-name-arz = àrab egipci
language-name-as = assamès
language-name-asa = pare
language-name-ase = llengua de signes americana
language-name-ast = asturià
language-name-av = àvar
language-name-awa = awadhi
language-name-ay = aimara
language-name-az = àzeri
language-name-ba = baixkir
language-name-bal = balutxi
language-name-ban = balinès
language-name-bar = bavarès
language-name-bas = basa
language-name-bax = bamum
language-name-bbj = ghomala
language-name-be = bielorús
language-name-bej = beja
language-name-bem = bemba
language-name-bez = bena
language-name-bfd = bafut
language-name-bfq = badaga
language-name-bg = búlgar
language-name-bgn = balutxi occidental
language-name-bho = bhojpuri
language-name-bi = bislama
language-name-bik = bicol
language-name-bin = bini
language-name-bkm = kom
language-name-bla = blackfoot
language-name-bm = bambara
language-name-bn = bengalí
language-name-bo = tibetà
language-name-br = bretó
language-name-bra = braj
language-name-brh = brahui
language-name-brx = bodo
language-name-bs = bosnià
language-name-bss = akoose
language-name-bua = buriat
language-name-bug = bugui
language-name-bum = seki
language-name-byn = bilin
language-name-byv = medumba
language-name-ca = català
language-name-cad = caddo
language-name-car = carib
language-name-cay = cayuga
language-name-cch = atsam
language-name-ce = txetxè
language-name-ceb = cebuano
language-name-cgg = chiga
language-name-ch = chamorro
language-name-chb = txibtxa
language-name-chg = txagatai
language-name-chk = chuuk
language-name-chm = mari
language-name-chn = pidgin chinook
language-name-cho = choctaw
language-name-chp = chipewyan
language-name-chr = cherokee
language-name-chy = xeiene
language-name-ckb = kurd central
language-name-co = cors
language-name-cop = copte
language-name-cr = cree
language-name-crh = tàtar de Crimea
language-name-crs = francès crioll de les Seychelles
language-name-cs = txec
language-name-csb = caixubi
language-name-cu = eslau eclesiàstic
language-name-cv = txuvaix
language-name-cy = gal·lès
language-name-da = danès
language-name-dak = dakota
language-name-dar = darguà
language-name-dav = taita
language-name-de = alemany
language-name-de_AT = alemany austríac
language-name-de_CH = alt alemany suís
language-name-del = delaware
language-name-den = slavi
language-name-dgr = dogrib
language-name-din = dinka
language-name-dje = zarma
language-name-doi = dogri
language-name-dsb = baix sòrab
language-name-dua = douala
language-name-dum = neerlandès mitjà
language-name-dv = divehi
language-name-dyo = diola
language-name-dyu = jula
language-name-dz = dzongka
language-name-dzg = dazaga
language-name-ebu = embu
language-name-ee = ewe
language-name-efi = efik
language-name-egl = emilià
language-name-egy = egipci antic
language-name-eka = ekajuk
language-name-el = grec
language-name-elx = elamita
language-name-en = anglès
language-name-en_AU = anglès australià
language-name-en_CA = anglès canadenc
language-name-en_GB = anglès britànic
language-name-en_US = anglès americà
language-name-enm = anglès mitjà
language-name-eo = esperanto
language-name-es = espanyol
language-name-es_419 = espanyol hispanoamericà
language-name-es_ES = espanyol europeu
language-name-es_MX = espanyol de Mèxic
language-name-et = estonià
language-name-eu = basc
language-name-ewo = ewondo
language-name-ext = extremeny
language-name-fa = persa
language-name-fan = fang
language-name-fat = fanti
language-name-ff = ful
language-name-fi = finès
language-name-fil = filipí
language-name-fj = fijià
language-name-fo = feroès
language-name-fon = fon
language-name-fr = francès
language-name-fr_CA = francès canadenc
language-name-fr_CH = francès suís
language-name-frc = francès cajun
language-name-frm = francès mitjà
language-name-fro = francès antic
language-name-frr = frisó septentrional
language-name-frs = frisó oriental
language-name-fur = friülà
language-name-fy = frisó occidental
language-name-ga = irlandès
language-name-gaa = ga
language-name-gag = gagaús
language-name-gan = xinès gan
language-name-gay = gayo
language-name-gba = gbaya
language-name-gd = gaèlic escocès
language-name-gez = gueez
language-name-gil = gilbertès
language-name-gl = gallec
language-name-glk = gilaki
language-name-gmh = alt alemany mitjà
language-name-gn = guaraní
language-name-goh = alt alemany antic
language-name-gom = concani de Goa
language-name-gon = gondi
language-name-gor = gorontalo
language-name-got = gòtic
language-name-grb = grebo
language-name-grc = grec antic
language-name-gsw = alemany suís
language-name-gu = gujarati
language-name-guc = wayú
language-name-guz = gusí
language-name-gv = manx
language-name-gwi = gwich’in
language-name-ha = haussa
language-name-hai = haida
language-name-hak = xinès hakka
language-name-haw = hawaià
language-name-he = hebreu
language-name-hi = hindi
language-name-hif = hindi de Fiji
language-name-hil = híligaynon
language-name-hit = hitita
language-name-hmn = hmong
language-name-ho = hiri motu
language-name-hr = croat
language-name-hsb = alt sòrab
language-name-hsn = xinès xiang
language-name-ht = crioll d’Haití
language-name-hu = hongarès
language-name-hup = hupa
language-name-hy = armeni
language-name-hz = herero
language-name-ia = interlingua
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indonesi
language-name-ie = interlingue
language-name-ig = igbo
language-name-ii = yi sichuan
language-name-ik = inupiak
language-name-ilo = ilocano
language-name-inh = ingúix
language-name-io = ido
language-name-is = islandès
language-name-it = italià
language-name-iu = inuktitut
language-name-ja = japonès
language-name-jam = crioll anglès de Jamaica
language-name-jbo = lojban
language-name-jgo = ngomba
language-name-jmc = machame
language-name-jpr = judeopersa
language-name-jrb = judeoàrab
language-name-jv = javanès
language-name-ka = georgià
language-name-kaa = karakalpak
language-name-kab = cabilenc
language-name-kac = katxin
language-name-kaj = jju
language-name-kam = kamba
language-name-kaw = kawi
language-name-kbd = kabardí
language-name-kbl = kanembu
language-name-kcg = tyap
language-name-kde = makonde
language-name-kea = crioll capverdià
language-name-ken = kenyang
language-name-kfo = koro
language-name-kg = kongo
language-name-kgp = kaingà
language-name-kha = khasi
language-name-kho = khotanès
language-name-khq = koyra chiini
language-name-ki = kikuiu
language-name-kj = kuanyama
language-name-kk = kazakh
language-name-kkj = kako
language-name-kl = grenlandès
language-name-kln = kalenjin
language-name-km = khmer
language-name-kmb = kimbundu
language-name-kn = kannada
language-name-ko = coreà
language-name-koi = komi-permiac
language-name-kok = concani
language-name-kos = kosraeà
language-name-kpe = kpelle
language-name-kr = kanuri
language-name-krc = karatxai-balkar
language-name-kri = krio
language-name-krl = carelià
language-name-kru = kurukh
language-name-ks = caixmiri
language-name-ksb = shambala
language-name-ksf = bafia
language-name-ksh = kölsch
language-name-ku = kurd
language-name-kum = kúmik
language-name-kut = kutenai
language-name-kv = komi
language-name-kw = còrnic
language-name-ky = kirguís
language-name-la = llatí
language-name-lad = judeocastellà
language-name-lag = langi
language-name-lah = panjabi occidental
language-name-lam = lamba
language-name-lb = luxemburguès
language-name-lez = lesguià
language-name-lg = ganda
language-name-li = limburguès
language-name-lij = lígur
language-name-lkt = lakota
language-name-lmo = llombard
language-name-ln = lingala
language-name-lo = laosià
language-name-lol = mongo
language-name-lou = crioll francès de Louisiana
language-name-loz = lozi
language-name-lrc = luri septentrional
language-name-lt = lituà
language-name-lu = luba katanga
language-name-lua = luba-lulua
language-name-lui = luisenyo
language-name-lun = lunda
language-name-luo = luo
language-name-lus = mizo
language-name-luy = luyia
language-name-lv = letó
language-name-lzh = xinès clàssic
language-name-lzz = laz
language-name-mad = madurès
language-name-maf = mafa
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = makassar
language-name-man = mandinga
language-name-mas = massai
language-name-mde = maba
language-name-mdf = mordovià moksa
language-name-mdr = mandar
language-name-men = mende
language-name-mer = meru
language-name-mfe = mauricià
language-name-mg = malgaix
language-name-mga = gaèlic irlandès mitjà
language-name-mgh = makhuwa-metto
language-name-mgo = meta’
language-name-mh = marshallès
language-name-mi = maori
language-name-mic = micmac
language-name-min = minangkabau
language-name-mk = macedoni
language-name-ml = malaialam
language-name-mn = mongol
language-name-mnc = manxú
language-name-mni = manipurí
language-name-moh = mohawk
language-name-mos = moré
language-name-mr = marathi
language-name-mrj = mari occidental
language-name-ms = malai
language-name-mt = maltès
language-name-mua = mundang
language-name-mul = llengües vàries
language-name-mus = creek
language-name-mwl = mirandès
language-name-mwr = marwari
language-name-my = birmà
language-name-mye = myene
language-name-myv = mordovià erza
language-name-mzn = mazanderani
language-name-na = nauruà
language-name-nan = xinès min del sud
language-name-nap = napolità
language-name-naq = nama
language-name-nb = noruec bokmål
language-name-nd = ndebele septentrional
language-name-nds = baix alemany
language-name-nds_NL = baix saxó
language-name-ne = nepalès
language-name-new = newari
language-name-ng = ndonga
language-name-nia = nias
language-name-niu = niueà
language-name-nl = neerlandès
language-name-nl_BE = flamenc
language-name-nmg = bissio
language-name-nn = noruec nynorsk
language-name-nnh = ngiemboon
language-name-no = noruec
language-name-nog = nogai
language-name-non = nòrdic antic
language-name-nov = novial
language-name-nqo = n’Ko
language-name-nr = ndebele meridional
language-name-nso = sotho septentrional
language-name-nus = nuer
language-name-nv = navaho
language-name-nwc = newari clàssic
language-name-ny = nyanja
language-name-nym = nyamwesi
language-name-nyn = nyankole
language-name-nyo = nyoro
language-name-nzi = nzema
language-name-oc = occità
language-name-oj = ojibwa
language-name-om = oromo
language-name-or = oriya
language-name-os = osseta
language-name-osa = osage
language-name-ota = turc otomà
language-name-pa = panjabi
language-name-pag = pangasi
language-name-pal = pahlavi
language-name-pam = pampanga
language-name-pap = papiamentu
language-name-pau = palauà
language-name-pcd = picard
language-name-pcm = pidgin de Nigèria
language-name-pdc = alemany pennsilvanià
language-name-peo = persa antic
language-name-pfl = alemany palatí
language-name-phn = fenici
language-name-pi = pali
language-name-pl = polonès
language-name-pms = piemontès
language-name-pnt = pòntic
language-name-pon = ponapeà
language-name-prg = prussià
language-name-pro = provençal antic
language-name-ps = paixtu
language-name-pt = portuguès
language-name-pt_BR = portuguès del Brasil
language-name-pt_PT = portuguès de Portugal
language-name-qu = quítxua
language-name-quc = k’iche’
language-name-raj = rajasthani
language-name-rap = rapanui
language-name-rar = rarotongà
language-name-rgn = romanyès
language-name-rm = retoromànic
language-name-rn = rundi
language-name-ro = romanès
language-name-ro_MD = moldau
language-name-rof = rombo
language-name-rom = romaní
language-name-root = arrel
language-name-ru = rus
language-name-rup = aromanès
language-name-rw = ruandès
language-name-rwk = rwo
language-name-sa = sànscrit
language-name-sad = sandawe
language-name-sah = iacut
language-name-sam = arameu samarità
language-name-saq = samburu
language-name-sas = sasak
language-name-sat = santali
language-name-sba = ngambay
language-name-sbp = sangu
language-name-sc = sard
language-name-scn = sicilià
language-name-sco = escocès
language-name-sd = sindi
language-name-sdc = sasserès
language-name-sdh = kurd meridional
language-name-se = sami septentrional
language-name-see = seneca
language-name-seh = sena
language-name-sel = selkup
language-name-ses = songhai oriental
language-name-sg = sango
language-name-sga = irlandès antic
language-name-sh = serbocroat
language-name-shi = taixelhit
language-name-shn = xan
language-name-shu = àrab txadià
language-name-si = singalès
language-name-sid = sidamo
language-name-sk = eslovac
language-name-sl = eslovè
language-name-sm = samoà
language-name-sma = sami meridional
language-name-smj = sami lule
language-name-smn = sami d’Inari
language-name-sms = sami skolt
language-name-sn = shona
language-name-snk = soninke
language-name-so = somali
language-name-sog = sogdià
language-name-sq = albanès
language-name-sr = serbi
language-name-srn = sranan
language-name-srr = serer
language-name-ss = swazi
language-name-ssy = saho
language-name-st = sotho meridional
language-name-su = sondanès
language-name-suk = sukuma
language-name-sus = susú
language-name-sux = sumeri
language-name-sv = suec
language-name-sw = suahili
language-name-sw_CD = suahili del Congo
language-name-swb = comorià
language-name-syc = siríac clàssic
language-name-syr = siríac
language-name-szl = silesià
language-name-ta = tàmil
language-name-te = telugu
language-name-tem = temne
language-name-teo = teso
language-name-ter = terena
language-name-tet = tètum
language-name-tg = tadjik
language-name-th = tai
language-name-ti = tigrinya
language-name-tig = tigre
language-name-tiv = tiv
language-name-tk = turcman
language-name-tkl = tokelauès
language-name-tkr = tsakhur
language-name-tl = tagal
language-name-tlh = klingonià
language-name-tli = tlingit
language-name-tly = talix
language-name-tmh = amazic
language-name-tn = setswana
language-name-to = tongalès
language-name-tog = tonga
language-name-tpi = tok pisin
language-name-tr = turc
language-name-trv = taroko
language-name-ts = tsonga
language-name-tsi = tsimshià
language-name-tt = tàtar
language-name-ttt = tat meridional
language-name-tum = tumbuka
language-name-tvl = tuvaluà
language-name-tw = twi
language-name-twq = tasawaq
language-name-ty = tahitià
language-name-tyv = tuvinià
language-name-tzm = amazic del Marroc central
language-name-udm = udmurt
language-name-ug = uigur
language-name-uga = ugarític
language-name-uk = ucraïnès
language-name-umb = umbundu
language-name-und = idioma desconegut
language-name-ur = urdú
language-name-uz = uzbek
language-name-vai = vai
language-name-ve = venda
language-name-vec = vènet
language-name-vep = vepse
language-name-vi = vietnamita
language-name-vls = flamenc occidental
language-name-vo = volapük
language-name-vot = vòtic
language-name-vun = vunjo
language-name-wa = való
language-name-wae = walser
language-name-wal = ameto
language-name-war = waray
language-name-was = washo
language-name-wbp = warlpiri
language-name-wo = wòlof
language-name-wuu = xinès wu
language-name-xal = calmuc
language-name-xh = xosa
language-name-xmf = mingrelià
language-name-xog = soga
language-name-yao = yao
language-name-yap = yapeà
language-name-yav = yangben
language-name-ybb = yemba
language-name-yi = jiddisch
language-name-yo = ioruba
language-name-yue = cantonès
language-name-za = zhuang
language-name-zap = zapoteca
language-name-zbl = símbols Bliss
language-name-zea = zelandès
language-name-zen = zenaga
language-name-zgh = amazic estàndard marroquí
language-name-zh = xinès
language-name-zh_Hans = xinès simplificat
language-name-zh_Hant = xinès tradicional
language-name-zu = zulu
language-name-zun = zuni
language-name-zxx = sense contingut lingüístic
language-name-zza = zaza
