language-name-aa = আফার
language-name-ab = আবখাজিয়ান
language-name-ace = অ্যাচাইনিজ
language-name-ach = আকোলি
language-name-ada = অদাগ্মে
language-name-ady = আদেগে
language-name-ae = আবেস্তীয়
language-name-af = আফ্রিকান
language-name-afh = আফ্রিহিলি
language-name-agq = এঘেম
language-name-ain = আইনু
language-name-ak = আকান
language-name-akk = আক্কাদিয়ান
language-name-ale = আলেউত
language-name-alt = দক্ষিন আলতাই
language-name-am = আমহারিক
language-name-an = আর্গোনিজ
language-name-ang = প্রাচীন ইংরেজী
language-name-anp = আঙ্গিকা
language-name-ar = আরবী
language-name-ar_001 = আধুনিক আদর্শ আরবী
language-name-arc = আরামাইক
language-name-arn = মাপুচি
language-name-arp = আরাপাহো
language-name-arw = আরাওয়াক
language-name-as = আসামি
language-name-asa = আসু
language-name-ast = আস্তুরিয়
language-name-av = আভেরিক
language-name-awa = আওয়াধি
language-name-ay = আয়মারা
language-name-az = আজারবাইজানী
language-name-ba = বাশকির
language-name-bal = বেলুচী
language-name-ban = বালিনীয়
language-name-bas = বাসা
language-name-be = বেলারুশিয়
language-name-bej = বেজা
language-name-bem = বেম্বা
language-name-bez = বেনা
language-name-bg = বুলগেরিয়
language-name-bgn = পশ্চিম বালোচি
language-name-bho = ভোজপুরি
language-name-bi = বিসলামা
language-name-bik = বিকোল
language-name-bin = বিনি
language-name-bla = সিকসিকা
language-name-bm = বামবারা
language-name-bn = বাংলা
language-name-bo = তিব্বতি
language-name-br = ব্রেটন
language-name-bra = ব্রাজ
language-name-brx = বোড়ো
language-name-bs = বসনীয়ান
language-name-bua = বুরিয়াত
language-name-bug = বুগিনি
language-name-byn = ব্লিন
language-name-ca = কাতালান
language-name-cad = ক্যাডো
language-name-car = ক্যারিব
language-name-cch = আত্সাম
language-name-ce = চেচেন
language-name-ceb = চেবুয়ানো
language-name-cgg = চিগা
language-name-ch = চামোরো
language-name-chb = চিবচা
language-name-chg = চাগাতাই
language-name-chk = চুকি
language-name-chm = মারি
language-name-chn = চিনুক জার্গন
language-name-cho = চকটোও
language-name-chp = চিপেওয়ান
language-name-chr = চেরোকী
language-name-chy = শাইয়েন
language-name-ckb = মধ্য কুর্দিশ
language-name-co = কর্সিকান
language-name-cop = কপটিক
language-name-cr = ক্রি
language-name-crh = ক্রিমিয়ান তুর্কি
language-name-crs = সেসেলওয়া ক্রেওল ফ্রেঞ্চ
language-name-cs = চেক
language-name-csb = কাশুবিয়ান
language-name-cu = চার্চ স্লাভিক
language-name-cv = চুবাস
language-name-cy = ওয়েলশ
language-name-da = ডেনিশ
language-name-dak = ডাকোটা
language-name-dar = দার্গওয়া
language-name-dav = তাইতা
language-name-de = জার্মান
language-name-de_AT = অস্ট্রিয়ান জার্মান
language-name-de_CH = সুইস হাই জার্মান
language-name-del = ডেলাওয়ের
language-name-den = স্ল্যাভ
language-name-dgr = দোগ্রীব
language-name-din = ডিংকা
language-name-dje = জার্মা
language-name-doi = ডোগরি
language-name-dsb = নিম্নতর সোর্বিয়ান
language-name-dua = দুয়ালা
language-name-dum = মধ্য ডাচ
language-name-dv = দিবেহি
language-name-dyo = জোলা-ফনী
language-name-dyu = ডিউলা
language-name-dz = জোঙ্গা
language-name-dzg = দাগাজা
language-name-ebu = এম্বু
language-name-ee = ইউয়ি
language-name-efi = এফিক
language-name-egy = প্রাচীন মিশরীয়
language-name-eka = ইকাজুক
language-name-el = গ্রিক
language-name-elx = এলামাইট
language-name-en = ইংরেজি
language-name-en_AU = অস্ট্রেলীয় ইংরেজি
language-name-en_CA = কানাডীয় ইংরেজি
language-name-en_GB = ব্রিটিশ ইংরেজি
language-name-en_US = আমেরিকার ইংরেজি
language-name-enm = মধ্য ইংরেজি
language-name-eo = এস্পেরান্তো
language-name-es = স্প্যানিশ
language-name-es_419 = ল্যাটিন আমেরিকান স্প্যানিশ
language-name-es_ES = ইউরোপীয় স্প্যানিশ
language-name-es_MX = ম্যাক্সিকান স্প্যানিশ
language-name-et = এস্তোনীয়
language-name-eu = বাস্ক
language-name-ewo = ইওন্ডো
language-name-fa = ফার্সি
language-name-fan = ফ্যাঙ্গ
language-name-fat = ফান্তি
language-name-ff = ফুলাহ্
language-name-fi = ফিনিশ
language-name-fil = ফিলিপিনো
language-name-fj = ফিজিআন
language-name-fo = ফারোস
language-name-fon = ফন
language-name-fr = ফরাসি
language-name-fr_CA = কানাডীয় ফরাসি
language-name-fr_CH = সুইস ফরাসি
language-name-frc = কাজুন ফরাসি
language-name-frm = মধ্য ফরাসি
language-name-fro = প্রাচীন ফরাসি
language-name-frr = উত্তরাঞ্চলীয় ফ্রিসিয়ান
language-name-frs = পূর্ব ফ্রিসিয়
language-name-fur = ফ্রিউলিয়ান
language-name-fy = পশ্চিম ফ্রিসিয়ান
language-name-ga = আইরিশ
language-name-gaa = গা
language-name-gag = গাগাউজ
language-name-gan = gan
language-name-gay = গায়ো
language-name-gba = বায়া
language-name-gd = স্কটস-গ্যেলিক
language-name-gez = গীজ
language-name-gil = গিলবার্টিজ
language-name-gl = গ্যালিশিয়
language-name-gmh = মধ্য-উচ্চ জার্মানি
language-name-gn = গুয়ারানি
language-name-goh = প্রাচীন উচ্চ জার্মানি
language-name-gon = গোন্ডি
language-name-gor = গোরোন্তালো
language-name-got = গথিক
language-name-grb = গ্রেবো
language-name-grc = প্রাচীন গ্রীক
language-name-gsw = সুইস জার্মান
language-name-gu = গুজরাটি
language-name-guz = গুসী
language-name-gv = ম্যাঙ্কস
language-name-gwi = গওইচ্’ইন
language-name-ha = হাউসা
language-name-hai = হাইডা
language-name-hak = hak
language-name-haw = হাওয়াইয়ান
language-name-he = হিব্রু
language-name-hi = হিন্দি
language-name-hil = হিলিগ্যায়নোন
language-name-hit = হিট্টিট
language-name-hmn = হ্‌মোঙ
language-name-ho = হিরি মোতু
language-name-hr = ক্রোয়েশীয়
language-name-hsb = উচ্চ সোর্বিয়ান
language-name-hsn = Xiang চীনা
language-name-ht = হাইতিয়ান ক্রেওল
language-name-hu = হাঙ্গেরীয়
language-name-hup = হুপা
language-name-hy = আর্মেনিয়
language-name-hz = হেরেরো
language-name-ia = ইন্টারলিঙ্গুয়া
language-name-iba = ইবান
language-name-ibb = ইবিবিও
language-name-id = ইন্দোনেশীয়
language-name-ie = ইন্টারলিঙ্গ
language-name-ig = ইগ্‌বো
language-name-ii = সিচুয়ান য়ি
language-name-ik = ইনুপিয়াক
language-name-ilo = ইলোকো
language-name-inh = ইঙ্গুশ
language-name-io = ইডো
language-name-is = আইসল্যান্ডীয়
language-name-it = ইতালিয়
language-name-iu = ইনুক্টিটুট
language-name-ja = জাপানি
language-name-jbo = লোজবান
language-name-jgo = গোম্বা
language-name-jmc = মাকামে
language-name-jpr = জুদেও ফার্সি
language-name-jrb = জুদেও আরবি
language-name-jv = জাভানিজ
language-name-ka = জর্জিয়ান
language-name-kaa = কারা-কাল্পাক
language-name-kab = কাবাইলে
language-name-kac = কাচিন
language-name-kaj = অজ্জু
language-name-kam = কাম্বা
language-name-kaw = কাউই
language-name-kbd = কাবার্ডিয়ান
language-name-kcg = টাইয়াপ
language-name-kde = মাকোন্দে
language-name-kea = কাবুভারদিয়ানু
language-name-kfo = কোরো
language-name-kg = কঙ্গো
language-name-kha = খাশি
language-name-kho = খোটানিজ
language-name-khq = কোয়রা চীনি
language-name-ki = কিকুয়ু
language-name-kj = কোয়ানিয়ামা
language-name-kk = কাজাখ
language-name-kkj = কাকো
language-name-kl = ক্যালাল্লিসুট
language-name-kln = কালেনজিন
language-name-km = খমের
language-name-kmb = কিম্বুন্দু
language-name-kn = কন্নড়
language-name-ko = কোরিয়ান
language-name-koi = কমি-পারমিআক
language-name-kok = কোঙ্কানি
language-name-kos = কোস্রাইন
language-name-kpe = ক্‌পেল্লে
language-name-kr = কানুরি
language-name-krc = কারচে-বাল্কার
language-name-krl = কারেলিয়ান
language-name-kru = কুরুখ
language-name-ks = কাশ্মীরি
language-name-ksb = শাম্বালা
language-name-ksf = বাফিয়া
language-name-ksh = কল্শ
language-name-ku = কুর্দিশ
language-name-kum = কুমিক
language-name-kut = কুটেনাই
language-name-kv = কোমি
language-name-kw = কর্ণিশ
language-name-ky = কির্গিজ
language-name-la = লাটিন
language-name-lad = লাডিনো
language-name-lag = লাঙ্গি
language-name-lah = লান্ডা
language-name-lam = লাম্বা
language-name-lb = লুক্সেমবার্গীয়
language-name-lez = লেজঘিয়ান
language-name-lg = গান্ডা
language-name-li = লিম্বুর্গিশ
language-name-lkt = লাকোটা
language-name-ln = লিঙ্গালা
language-name-lo = লাও
language-name-lol = মোঙ্গো
language-name-lou = লুইসিয়ানা ক্রেওল
language-name-loz = লোজি
language-name-lrc = উত্তর লুরি
language-name-lt = লিথুয়েনীয়
language-name-lu = লুবা-কাটাঙ্গা
language-name-lua = লুবা-লুলুয়া
language-name-lui = লুইসেনো
language-name-lun = লুন্ডা
language-name-luo = লুয়ো
language-name-lus = মিজো
language-name-luy = লুইয়া
language-name-lv = লাত্‌ভীয়
language-name-mad = মাদুরেসে
language-name-mag = মাগাহি
language-name-mai = মৈথিলি
language-name-mak = ম্যাকাসার
language-name-man = ম্যান্ডিঙ্গো
language-name-mas = মাসাই
language-name-mdf = মোকশা
language-name-mdr = ম্যাণ্ডার
language-name-men = মেন্ডে
language-name-mer = মেরু
language-name-mfe = মরিসিয়ান
language-name-mg = মালাগাসি
language-name-mga = মধ্য আইরিশ
language-name-mgh = মাখুয়া-মেত্তো
language-name-mgo = মেটা
language-name-mh = মার্শালিজ
language-name-mi = মাওরি
language-name-mic = মিকম্যাক
language-name-min = মিনাঙ্গ্‌কাবাউ
language-name-mk = ম্যাসিডোনীয়
language-name-ml = মালায়ালাম
language-name-mn = মঙ্গোলিয়
language-name-mnc = মাঞ্চু
language-name-mni = মণিপুরী
language-name-moh = মোহাওক
language-name-mos = মসি
language-name-mr = মারাঠি
language-name-ms = মালয়
language-name-mt = মল্টিয়
language-name-mua = মুদাঙ্গ
language-name-mul = একাধিক ভাষা
language-name-mus = ক্রিক
language-name-mwl = মিরান্ডিজ
language-name-mwr = মারোয়ারি
language-name-my = বর্মি
language-name-myv = এরজিয়া
language-name-mzn = মাজানদেরানি
language-name-na = নাউরু
language-name-nan = nan
language-name-nap = নেয়াপোলিটান
language-name-naq = নামা
language-name-nb = নরওয়েজিয়ান বোকমাল
language-name-nd = উত্তর এন্দেবিলি
language-name-nds = নিম্ন জার্মানি
language-name-nds_NL = লো স্যাক্সন
language-name-ne = নেপালী
language-name-new = নেওয়ারি
language-name-ng = এন্দোঙ্গা
language-name-nia = নিয়াস
language-name-niu = নিউয়ান
language-name-nl = ডাচ
language-name-nl_BE = ফ্লেমিশ
language-name-nmg = কোয়াসিও
language-name-nn = নরওয়েজীয়ান নিনর্স্ক
language-name-nnh = নিঙ্গেম্বুন
language-name-no = নরওয়েজীয়
language-name-nog = নোগাই
language-name-non = প্রাচীন নর্স
language-name-nqo = এন’কো
language-name-nr = দক্ষিণ এনডেবেলে
language-name-nso = উত্তরাঞ্চলীয় সোথো
language-name-nus = নুয়ার
language-name-nv = নাভাজো
language-name-nwc = প্রাচীন নেওয়ারী
language-name-ny = নায়াঞ্জা
language-name-nym = ন্যায়ামওয়েজি
language-name-nyn = ন্যায়াঙ্কোলে
language-name-nyo = ন্যোরো
language-name-nzi = এনজিমা
language-name-oc = অক্সিটান
language-name-oj = ওজিবওয়া
language-name-om = অরোমো
language-name-or = ওড়িয়া
language-name-os = ওসেটিক
language-name-osa = ওসেজ
language-name-ota = অটোমান তুর্কি
language-name-pa = পাঞ্জাবী
language-name-pag = পাঙ্গাসিনান
language-name-pal = পাহ্লাভি
language-name-pam = পাম্পাঙ্গা
language-name-pap = পাপিয়ামেন্টো
language-name-pau = পালায়ুয়ান
language-name-pcm = নাইজেরিয় পিজিন
language-name-peo = প্রাচীন ফার্সি
language-name-phn = ফোনিশীয়ান
language-name-pi = পালি
language-name-pl = পোলিশ
language-name-pon = পোহ্নপেইয়ান
language-name-prg = প্রুশিয়ান
language-name-pro = প্রাচীন প্রোভেনসাল
language-name-ps = পুশতু
language-name-pt = পর্তুগীজ
language-name-pt_BR = ব্রাজিলের পর্তুগীজ
language-name-pt_PT = ইউরোপের পর্তুগীজ
language-name-qu = কেচুয়া
language-name-quc = কি‘চে
language-name-raj = রাজস্থানী
language-name-rap = রাপানুই
language-name-rar = রারোটোংগান
language-name-rm = রোমান্স
language-name-rn = রুন্দি
language-name-ro = রোমানীয়
language-name-ro_MD = মলদাভিয়
language-name-rof = রম্বো
language-name-rom = রোমানি
language-name-root = মূল
language-name-ru = রুশ
language-name-rup = আরমেনিয়ান
language-name-rw = কিনয়ারোয়ান্ডা
language-name-rwk = রাওয়া
language-name-sa = সংস্কৃত
language-name-sad = স্যান্ডাওয়ে
language-name-sah = শাখা
language-name-sam = সামারিটান আরামিক
language-name-saq = সামবুরু
language-name-sas = সাসাক
language-name-sat = সাঁওতালি
language-name-sba = ন্যাগাম্বে
language-name-sbp = সাঙ্গু
language-name-sc = সার্ডিনিয়ান
language-name-scn = সিসিলিয়ান
language-name-sco = স্কটস
language-name-sd = সিন্ধি
language-name-sdh = দক্ষিণ কুর্দিশ
language-name-se = উত্তরাঞ্চলীয় সামি
language-name-seh = সেনা
language-name-sel = সেল্কুপ
language-name-ses = কোয়রাবেনো সেন্নী
language-name-sg = সাঙ্গো
language-name-sga = প্রাচীন আইরিশ
language-name-sh = সার্বো-ক্রোয়েশিয়
language-name-shi = তাচেলহিত
language-name-shn = শান
language-name-si = সিংহলী
language-name-sid = সিডামো
language-name-sk = স্লোভাক
language-name-sl = স্লোভেনীয়
language-name-sm = সামোয়ান
language-name-sma = দক্ষিণাঞ্চলীয় সামি
language-name-smj = লুলে সামি
language-name-smn = ইনারি সামি
language-name-sms = স্কোল্ট সামি
language-name-sn = শোনা
language-name-snk = সোনিঙ্কে
language-name-so = সোমালি
language-name-sog = সোগডিয়ান
language-name-sq = আলবেনীয়
language-name-sr = সার্বীয়
language-name-srn = স্রানান টোঙ্গো
language-name-srr = সেরের
language-name-ss = সোয়াতি
language-name-ssy = সাহো
language-name-st = দক্ষিন সোথো
language-name-su = সুদানী
language-name-suk = সুকুমা
language-name-sus = সুসু
language-name-sux = সুমেরীয়
language-name-sv = সুইডিশ
language-name-sw = সোয়াহিলি
language-name-sw_CD = কঙ্গো সোয়াহিলি
language-name-swb = কমোরিয়ান
language-name-syc = প্রাচীন সিরিও
language-name-syr = সিরিয়াক
language-name-ta = তামিল
language-name-te = তেলেগু
language-name-tem = টাইম্নে
language-name-teo = তেসো
language-name-ter = তেরেনো
language-name-tet = তেতুম
language-name-tg = তাজিক
language-name-th = থাই
language-name-ti = তিগরিনিয়া
language-name-tig = টাইগ্রে
language-name-tiv = টিভ
language-name-tk = তুর্কমেনী
language-name-tkl = টোকেলাউ
language-name-tl = তাগালগ
language-name-tlh = ক্লিঙ্গন
language-name-tli = ত্লিঙ্গিট
language-name-tmh = তামাশেক
language-name-tn = সোয়ানা
language-name-to = টোঙ্গান
language-name-tog = নায়াসা টোঙ্গা
language-name-tpi = টোক পিসিন
language-name-tr = তুর্কী
language-name-trv = তারোকো
language-name-ts = সঙ্গা
language-name-tsi = সিমশিয়ান
language-name-tt = তাতার
language-name-tum = তুম্বুকা
language-name-tvl = টুভালু
language-name-tw = টোয়াই
language-name-twq = তাসাওয়াক
language-name-ty = তাহিতিয়ান
language-name-tyv = টুভিনিয়ান
language-name-tzm = সেন্ট্রাল আটলাস তামাজিগাত
language-name-udm = উডমুর্ট
language-name-ug = উইঘুর
language-name-uga = উগারিটিক
language-name-uk = ইউক্রেনীয়
language-name-umb = উম্বুন্দু
language-name-und = অজানা ভাষা
language-name-ur = উর্দু
language-name-uz = উজবেকীয়
language-name-vai = ভাই
language-name-ve = ভেন্ডা
language-name-vi = ভিয়েতনামী
language-name-vo = ভোলাপুক
language-name-vot = ভোটিক
language-name-vun = ভুঞ্জো
language-name-wa = ওয়ালুন
language-name-wae = ওয়ালসের
language-name-wal = ওয়ালামো
language-name-war = ওয়ারে
language-name-was = ওয়াশো
language-name-wbp = ওয়ার্লপিরি
language-name-wo = উওলোফ
language-name-wuu = Wu চীনা
language-name-xal = কাল্মইক
language-name-xh = জোসা
language-name-xog = সোগা
language-name-yao = ইয়াও
language-name-yap = ইয়াপেসে
language-name-yav = ইয়াঙ্গবেন
language-name-ybb = ইয়েম্বা
language-name-yi = ইয়েদ্দিশ
language-name-yo = ইওরুবা
language-name-yue = ক্যানটোনীজ
language-name-za = ঝু্য়াঙ
language-name-zap = জাপোটেক
language-name-zbl = চিত্র ভাষা
language-name-zen = জেনাগা
language-name-zgh = আদর্শ মরক্কোন তামাজিগাত
language-name-zh = চীনা
language-name-zh_Hans = সরলীকৃত চীনা
language-name-zh_Hant = ঐতিহ্যবাহি চীনা
language-name-zu = জুলু
language-name-zun = জুনি
language-name-zxx = ভাষাভিত্তিক বিষয়বস্তু নেই
language-name-zza = জাজা
