language-name-bas = Shwóŋò pʉa mbasǎ
language-name-bax = Shwóŋò pamom
language-name-bbj = Shwóŋò pʉa nzsekàʼa
language-name-bfd = Shwóŋò pafud
language-name-bkm = Shwóŋò pʉ̀a njinikom
language-name-bss = Shwóŋò pakɔsi
language-name-bum = Shwóŋò mbulu
language-name-byv = Shwóŋò ngáŋtÿɔʼ
language-name-de = nzǎmɔ̂ɔn
language-name-en = ngilísè
language-name-ewo = Shwóŋò pʉa Yɔɔnmendi
language-name-ff = Shwóŋò menkesaŋ
language-name-fr = felaŋsée
language-name-kkj = Shwóŋò pʉa shÿó Bɛgtùa
language-name-nnh = Shwóŋò ngiembɔɔn
language-name-yav = Shwóŋò pʉa shÿó Mbafìa
language-name-ybb = Shwóŋò Tsaŋ
