language-name-aa = ਅਫ਼ਾਰ
language-name-ab = ਅਬਖਾਜ਼ੀਅਨ
language-name-ace = ਅਚੀਨੀ
language-name-ach = ਅਕੋਲੀ
language-name-ada = ਅਡਾਂਗਮੇ
language-name-ady = ਅਡਿਗੇ
language-name-af = ਅਫ਼ਰੀਕੀ
language-name-agq = ਅਗੇਮ
language-name-ain = ਆਇਨੂ
language-name-ak = ਅਕਾਨ
language-name-ale = ਅਲੇਉਟ
language-name-alt = ਦੱਖਣੀ ਅਲਤਾਈ
language-name-am = ਅਮਹਾਰਿਕ
language-name-an = ਅਰਾਗੋਨੀ
language-name-ang = ਪੁਰਾਣੀ ਅੰਗਰੇਜ਼ੀ
language-name-anp = ਅੰਗਿਕਾ
language-name-ar = ਅਰਬੀ
language-name-ar_001 = ਆਧੁਨਿਕ ਮਿਆਰੀ ਅਰਬੀ
language-name-arn = ਮਾਪੁਚੇ
language-name-arp = ਅਰਾਫਾਓ
language-name-as = ਅਸਾਮੀ
language-name-asa = ਅਸੂ
language-name-ast = ਅਸਤੂਰੀ
language-name-av = ਅਵਾਰਿਕ
language-name-awa = ਅਵਧੀ
language-name-ay = ਅਈਮਾਰਾ
language-name-az = ਅਜ਼ਰਬਾਈਜਾਨੀ
language-name-ba = ਬਸ਼ਕੀਰ
language-name-ban = ਬਾਲੀਨੀਜ਼
language-name-bas = ਬਾਸਾ
language-name-be = ਬੇਲਾਰੂਸੀ
language-name-bem = ਬੇਮਬਾ
language-name-bez = ਬੇਨਾ
language-name-bg = ਬੁਲਗਾਰੀਆਈ
language-name-bgn = ਪੱਛਮੀ ਬਲੂਚੀ
language-name-bho = ਭੋਜਪੁਰੀ
language-name-bi = ਬਿਸਲਾਮਾ
language-name-bin = ਬਿਨੀ
language-name-bla = ਸਿਕਸਿਕਾ
language-name-bm = ਬੰਬਾਰਾ
language-name-bn = ਬੰਗਾਲੀ
language-name-bo = ਤਿੱਬਤੀ
language-name-br = ਬਰੇਟਨ
language-name-brx = ਬੋਡੋ
language-name-bs = ਬੋਸਨੀਆਈ
language-name-bug = ਬਗਨੀਜ਼
language-name-byn = ਬਲਿਨ
language-name-ca = ਕੈਟਾਲਾਨ
language-name-ce = ਚੇਚਨ
language-name-ceb = ਸੀਬੂਆਨੋ
language-name-cgg = ਚੀਗਾ
language-name-ch = ਚਮੋਰੋ
language-name-chk = ਚੂਕੀਸ
language-name-chm = ਮਾਰੀ
language-name-cho = ਚੌਕਟੋ
language-name-chr = ਚੇਰੋਕੀ
language-name-chy = ਛਾਇਆਨ
language-name-ckb = ਕੇਂਦਰੀ ਕੁਰਦਿਸ਼
language-name-co = ਕੋਰਸੀਕਨ
language-name-crs = ਸੇਸੇਲਵਾ ਕ੍ਰਿਓਲ ਫ੍ਰੈਂਚ
language-name-cs = ਚੈੱਕ
language-name-cu = ਚਰਚ ਸਲਾਵੀ
language-name-cv = ਚੁਵਾਸ਼
language-name-cy = ਵੈਲਸ਼
language-name-da = ਡੈਨਿਸ਼
language-name-dak = ਡਕੋਟਾ
language-name-dar = ਦਾਰਗਵਾ
language-name-dav = ਟੇਟਾ
language-name-de = ਜਰਮਨ
language-name-dgr = ਡੋਗਰਿੱਬ
language-name-dje = ਜ਼ਾਰਮਾ
language-name-dsb = ਲੋਅਰ ਸੋਰਬੀਅਨ
language-name-dua = ਡੂਆਲਾ
language-name-dv = ਦਿਵੇਹੀ
language-name-dyo = ਜੋਲਾ-ਫੋਇਨੀ
language-name-dz = ਜ਼ੋਂਗਖਾ
language-name-dzg = ਡਜ਼ਾਗਾ
language-name-ebu = ਇੰਬੂ
language-name-ee = ਈਵਈ
language-name-efi = ਐਫਿਕ
language-name-egy = ਪੁਰਾਤਨ ਮਿਸਰੀ
language-name-eka = ਏਕਾਜੁਕ
language-name-el = ਯੂਨਾਨੀ
language-name-en = ਅੰਗਰੇਜ਼ੀ
language-name-eo = ਇਸਪੇਰਾਂਟੋ
language-name-es = ਸਪੇਨੀ
language-name-et = ਇਸਟੋਨੀਆਈ
language-name-eu = ਬਾਸਕ
language-name-ewo = ਇਵੋਂਡੋ
language-name-fa = ਫ਼ਾਰਸੀ
language-name-ff = ਫੁਲਾਹ
language-name-fi = ਫਿਨਿਸ਼
language-name-fil = ਫਿਲੀਪਿਨੋ
language-name-fj = ਫ਼ਿਜ਼ੀ
language-name-fo = ਫ਼ੇਰੋਸੇ
language-name-fon = ਫੌਨ
language-name-fr = ਫਰਾਂਸੀਸੀ
language-name-frc = ਕੇਜੁਨ ਫ੍ਰੇੰਚ
language-name-fur = ਫਰੀਉਲੀਅਨ
language-name-fy = ਪੱਛਮੀ ਫ੍ਰਿਸੀਅਨ
language-name-ga = ਆਇਰਸ਼
language-name-gaa = ਗਾ
language-name-gag = ਗਾਗੌਜ਼
language-name-gan = ਚੀਨੀ ਗਾਨ
language-name-gd = ਸਕਾਟਿਸ਼ ਗੇਲਿਕ
language-name-gez = ਜੀਜ਼
language-name-gil = ਗਿਲਬਰਤੀਜ਼
language-name-gl = ਗੈਲਿਸ਼ਿਅਨ
language-name-gn = ਗੁਆਰਾਨੀ
language-name-gor = ਗੋਰੋਂਤਾਲੋ
language-name-grc = ਪੁਰਾਤਨ ਯੂਨਾਨੀ
language-name-gu = ਗੁਜਰਾਤੀ
language-name-guz = ਗੁਸੀ
language-name-gv = ਮੈਂਕਸ
language-name-gwi = ਗਵਿਚ’ਇਨ
language-name-ha = ਹੌਸਾ
language-name-hak = ਚੀਨੀ ਹਾਕਾ
language-name-haw = ਹਵਾਈ
language-name-he = ਹਿਬਰੂ
language-name-hi = ਹਿੰਦੀ
language-name-hif = ਫਿਜੀ ਹਿੰਦੀ
language-name-hil = ਹਿਲੀਗੇਨਨ
language-name-hmn = ਹਮੋਂਗ
language-name-hr = ਕ੍ਰੋਏਸ਼ਿਆਈ
language-name-hsb = ਅੱਪਰ ਸੋਰਬੀਅਨ
language-name-hsn = ਚੀਨੀ ਜ਼ਿਆਂਗ
language-name-ht = ਹੈਤੀਆਈ
language-name-hu = ਹੰਗਰੀਆਈ
language-name-hup = ਹੂਪਾ
language-name-hy = ਅਰਮੀਨੀਆਈ
language-name-hz = ਹਰੇਰੋ
language-name-ia = ਇੰਟਰਲਿੰਗੁਆ
language-name-iba = ਇਬਾਨ
language-name-ibb = ਇਬੀਬੀਓ
language-name-id = ਇੰਡੋਨੇਸ਼ੀਆਈ
language-name-ig = ਇਗਬੋ
language-name-ii = ਸਿਚੁਆਨ ਯੀ
language-name-ilo = ਇਲੋਕੋ
language-name-inh = ਇੰਗੁਸ਼
language-name-io = ਇਡੂ
language-name-is = ਆਈਸਲੈਂਡਿਕ
language-name-it = ਇਤਾਲਵੀ
language-name-iu = ਇੰਕਟੀਟੂਤ
language-name-ja = ਜਪਾਨੀ
language-name-jbo = ਲੋਜਬਾਨ
language-name-jgo = ਨਗੋਂਬਾ
language-name-jmc = ਮਚਾਮੇ
language-name-jv = ਜਾਵਾਨੀਜ਼
language-name-ka = ਜਾਰਜੀਆਈ
language-name-kab = ਕਬਾਇਲ
language-name-kac = ਕਾਚਿਨ
language-name-kaj = ਜਜੂ
language-name-kam = ਕੰਬਾ
language-name-kbd = ਕਬਾਰਦੀ
language-name-kcg = ਟਾਇਪ
language-name-kde = ਮਕੋਂਡ
language-name-kea = ਕਾਬੁਵੇਰਦਿਆਨੂ
language-name-kfo = ਕੋਰੋ
language-name-kha = ਖਾਸੀ
language-name-khq = ਕੋਯਰਾ ਚੀਨੀ
language-name-ki = ਕਿਕੂਯੂ
language-name-kj = ਕੁਆਨਯਾਮਾ
language-name-kk = ਕਜ਼ਾਖ਼
language-name-kkj = ਕਾਕੋ
language-name-kl = ਕਲਾਅੱਲੀਸੁਟ
language-name-kln = ਕਲੇਜਿਨ
language-name-km = ਖਮੇਰ
language-name-kmb = ਕਿਮਬੁੰਦੂ
language-name-kn = ਕੰਨੜ
language-name-ko = ਕੋਰੀਆਈ
language-name-koi = ਕੋਮੀ-ਪੇਰਮਿਆਕ
language-name-kok = ਕੋਂਕਣੀ
language-name-kpe = ਕਪੇਲ
language-name-kr = ਕਨੂਰੀ
language-name-krc = ਕਰਾਚੇ ਬਲਕਾਰ
language-name-krl = ਕਰੀਲੀਅਨ
language-name-kru = ਕੁਰੁਖ
language-name-ks = ਕਸ਼ਮੀਰੀ
language-name-ksb = ਸ਼ੰਬਾਲਾ
language-name-ksf = ਬਫ਼ੀਆ
language-name-ksh = ਕਲੋਗਨੀਅਨ
language-name-ku = ਕੁਰਦ
language-name-kum = ਕੁਮੀਕ
language-name-kv = ਕੋਮੀ
language-name-kw = ਕੋਰਨਿਸ਼
language-name-ky = ਕਿਰਗੀਜ਼
language-name-la = ਲਾਤੀਨੀ
language-name-lad = ਲੈਡੀਨੋ
language-name-lag = ਲੰਗਾਈ
language-name-lb = ਲਕਜ਼ਮਬਰਗਿਸ਼
language-name-lez = ਲੈਜ਼ਗੀ
language-name-lg = ਗਾਂਡਾ
language-name-li = ਲਿਮਬੁਰਗੀ
language-name-lkt = ਲਕੋਟਾ
language-name-ln = ਲਿੰਗਾਲਾ
language-name-lo = ਲਾਓ
language-name-lou = ਲੇਉ
language-name-loz = ਲੋਜ਼ੀ
language-name-lrc = ਉੱਤਰੀ ਲੁਰੀ
language-name-lt = ਲਿਥੁਆਨੀਅਨ
language-name-lu = ਲੂਬਾ-ਕਾਟਾਂਗਾ
language-name-lua = ਲਿਊਬਾ-ਲਿਊਲਿਆ
language-name-lun = ਲੁੰਡਾ
language-name-luo = ਲੂਓ
language-name-lus = ਮਿਜ਼ੋ
language-name-luy = ਲੂਈਆ
language-name-lv = ਲਾਤੀਵੀ
language-name-mad = ਮਾਡੂਰੀਸ
language-name-mag = ਮਗਾਹੀ
language-name-mai = ਮੈਥਲੀ
language-name-mak = ਮਕਾਸਰ
language-name-mas = ਮਸਾਈ
language-name-mdf = ਮੋਕਸ਼ਾ
language-name-men = ਮੇਂਡੇ
language-name-mer = ਮੇਰੂ
language-name-mfe = ਮੋਰੀਸਿਅਨ
language-name-mg = ਮੇਲੇਗਸੀ
language-name-mgh = ਮਖੋਵਾ-ਮਿੱਟੋ
language-name-mgo = ਮੇਟਾ
language-name-mh = ਮਾਰਸ਼ਲੀਜ਼
language-name-mi = ਮਾਉਰੀ
language-name-mic = ਮਾਇਮੈਕ
language-name-min = ਮਿਨਾਂਗਕਾਬਾਓ
language-name-mk = ਮੈਕਡੋਨੀਆਈ
language-name-ml = ਮਲਿਆਲਮ
language-name-mn = ਮੰਗੋਲੀ
language-name-mni = ਮਨੀਪੁਰੀ
language-name-moh = ਮੋਹਆਕ
language-name-mos = ਮੋਸੀ
language-name-mr = ਮਰਾਠੀ
language-name-ms = ਮਲਯ
language-name-mt = ਮਾਲਟੀਜ਼
language-name-mua = ਮੁੰਡੇਂਗ
language-name-mul = ਬਹੁਤੀਆਂ ਬੋਲੀਆਂ
language-name-mus = ਕ੍ਰੀਕ
language-name-mwl = ਮਿਰਾਂਡੀ
language-name-my = ਬਰਮੀ
language-name-myv = ਇਰਜ਼ੀਆ
language-name-mzn = ਮੇਜ਼ੈਂਡਰਾਨੀ
language-name-na = ਨਾਉਰੂ
language-name-nan = ਚੀਨੀ ਮਿਨ ਨਾਨ
language-name-nap = ਨਿਆਪੋਲੀਟਨ
language-name-naq = ਨਾਮਾ
language-name-nb = ਨਾਰਵੇਜਿਆਈ ਬੋਕਮਲ
language-name-nd = ਉੱਤਰੀ ਨਡੇਬੇਲੇ
language-name-nds = ਲੋ ਜਰਮਨ
language-name-nds_NL = ਲੋ ਸੈਕਸਨ
language-name-ne = ਨੇਪਾਲੀ
language-name-new = ਨੇਵਾਰੀ
language-name-ng = ਐਂਡੋਂਗਾ
language-name-nia = ਨਿਆਸ
language-name-niu = ਨਿਊਏਈ
language-name-nl = ਡੱਚ
language-name-nl_BE = ਫਲੈਮਿਸ਼
language-name-nmg = ਕਵਾਸਿਓ
language-name-nn = ਨਾਰਵੇਜਿਆਈ ਨਿਓਨੌਰਸਕ
language-name-nnh = ਨਿਓਮਬੂਨ
language-name-no = ਨਾਰਵੇਜਿਆਈ
language-name-nog = ਨੋਗਾਈ
language-name-nqo = ਐਂਕੋ
language-name-nr = ਸਾਊਥ ਨਡੇਬੇਲੇ
language-name-nso = ਉੱਤਰੀ ਸੋਥੋ
language-name-nus = ਨੁਏਰ
language-name-nv = ਨਵਾਜੋ
language-name-ny = ਨਯਾਂਜਾ
language-name-nyn = ਨਿਆਂਕੋਲੇ
language-name-oc = ਓਕਸੀਟਾਨ
language-name-om = ਓਰੋਮੋ
language-name-or = ਉੜੀਆ
language-name-os = ਓਸੈਟਿਕ
language-name-pa = ਪੰਜਾਬੀ
language-name-pag = ਪੰਗਾਸੀਨਾਨ
language-name-pam = ਪੈਂਪਾਂਗਾ
language-name-pap = ਪਾਪਿਆਮੈਂਟੋ
language-name-pau = ਪਲਾਊਵੀ
language-name-pcm = ਨਾਇਜੀਰੀਆਈ ਪਿਡਗਿਨ
language-name-pi = ਪਾਲੀ
language-name-pl = ਪੋਲੈਂਡੀ
language-name-prg = ਪਰੂਸ਼ੀਆ
language-name-ps = ਪਸ਼ਤੋ
language-name-pt = ਪੁਰਤਗਾਲੀ
language-name-qu = ਕਕੇਸ਼ੁਆ
language-name-quc = ਕੇਸ਼
language-name-raj = ਰਾਜਸਥਾਨੀ
language-name-rap = ਰਾਪਾਨੁਈ
language-name-rar = ਰਾਰੋਤੋਂਗਨ
language-name-rm = ਰੋਮਾਂਸ਼
language-name-rn = ਰੁੰਡੀ
language-name-ro = ਰੋਮਾਨੀਆਈ
language-name-ro_MD = ਮੋਲਡਾਵੀਆਈ
language-name-rof = ਰੋਮਬੋ
language-name-root = ਰੂਟ
language-name-ru = ਰੂਸੀ
language-name-rup = ਅਰੋਮੀਨੀਆਈ
language-name-rw = ਕਿਨਿਆਰਵਾਂਡਾ
language-name-rwk = ਰਵਾ
language-name-sa = ਸੰਸਕ੍ਰਿਤ
language-name-sad = ਸਾਂਡੋ
language-name-sah = ਸਾਖਾ
language-name-saq = ਸਮਬੁਰੂ
language-name-sat = ਸੰਥਾਲੀ
language-name-sba = ਨਗਾਂਬੇ
language-name-sbp = ਸੇਂਗੋ
language-name-sc = ਸਾਰਡੀਨੀਆਈ
language-name-scn = ਸਿਸੀਲੀਅਨ
language-name-sco = ਸਕਾਟਸ
language-name-sd = ਸਿੰਧੀ
language-name-sdh = ਦੱਖਣੀ ਕੁਰਦਿਸ਼
language-name-se = ਉੱਤਰੀ ਸਾਮੀ
language-name-seh = ਸੇਨਾ
language-name-ses = ਕੋਇਰਾਬੋਰੋ ਸੇਂਨੀ
language-name-sg = ਸਾਂਗੋ
language-name-shi = ਟਚੇਲਹਿਟ
language-name-shn = ਸ਼ਾਨ
language-name-si = ਸਿੰਹਾਲਾ
language-name-sk = ਸਲੋਵਾਕ
language-name-sl = ਸਲੋਵੇਨੀਆਈ
language-name-sm = ਸਾਮੋਨ
language-name-sma = ਦੱਖਣੀ ਸਾਮੀ
language-name-smj = ਲਿਊਲ ਸਾਮੀ
language-name-smn = ਇਨਾਰੀ ਸਾਮੀ
language-name-sms = ਸਕੌਲਟ ਸਾਮੀ
language-name-sn = ਸ਼ੋਨਾ
language-name-snk = ਸੋਨਿੰਕੇ
language-name-so = ਸੋਮਾਲੀ
language-name-sq = ਅਲਬਾਨੀਆਈ
language-name-sr = ਸਰਬੀਆਈ
language-name-srn = ਸ੍ਰਾਨਾਨ ਟੋਂਗੋ
language-name-ss = ਸਵਾਤੀ
language-name-ssy = ਸਾਹੋ
language-name-st = ਦੱਖਣੀ ਸੋਥੋ
language-name-su = ਸੂੰਡਾਨੀ
language-name-suk = ਸੁਕੁਮਾ
language-name-sv = ਸਵੀਡਿਸ਼
language-name-sw = ਸਵਾਹਿਲੀ
language-name-sw_CD = ਕਾਂਗੋ ਸਵਾਇਲੀ
language-name-swb = ਕੋਮੋਰੀਅਨ
language-name-syr = ਸੀਰੀਆਈ
language-name-ta = ਤਮਿਲ
language-name-te = ਤੇਲਗੂ
language-name-tem = ਟਿਮਨੇ
language-name-teo = ਟੇਸੋ
language-name-tet = ਟੇਟਮ
language-name-tg = ਤਾਜਿਕ
language-name-th = ਥਾਈ
language-name-ti = ਤਿਗ੍ਰੀਨਿਆ
language-name-tig = ਟਿਗਰਾ
language-name-tk = ਤੁਰਕਮੇਨ
language-name-tlh = ਕਲਿੰਗਨ
language-name-tn = ਤਸਵਾਨਾ
language-name-to = ਟੌਂਗਨ
language-name-tpi = ਟੋਕ ਪਿਸਿਨ
language-name-tr = ਤੁਰਕੀ
language-name-trv = ਟਾਰੋਕੋ
language-name-ts = ਸੋਂਗਾ
language-name-tt = ਤਤਾਰ
language-name-tum = ਤੁੰਬੁਕਾ
language-name-tvl = ਟਿਊਵਾਲੂ
language-name-tw = ਤ੍ਵਿ
language-name-twq = ਤਾਸਾਵਿਕ
language-name-ty = ਤਾਹੀਟੀ
language-name-tyv = ਤੁਵੀਨੀਅਨ
language-name-tzm = ਮੱਧ ਐਟਲਸ ਤਮਾਜ਼ਿਤ
language-name-udm = ਉਦਮੁਰਤ
language-name-ug = ਉਇਗੁਰ
language-name-uk = ਯੂਕਰੇਨੀਆਈ
language-name-umb = ਉਮਬੁੰਡੂ
language-name-und = ਅਣਪਛਾਤੀ ਬੋਲੀ
language-name-ur = ਉੜਦੂ
language-name-uz = ਉਜ਼ਬੇਕ
language-name-vai = ਵਾਈ
language-name-ve = ਵੇਂਡਾ
language-name-vi = ਵੀਅਤਨਾਮੀ
language-name-vo = ਵੋਲਾਪੂਕ
language-name-vun = ਵੂੰਜੋ
language-name-wa = ਵਲੂਨ
language-name-wae = ਵਾਲਸਰ
language-name-wal = ਵੋਲਾਏਟਾ
language-name-war = ਵੈਰੇ
language-name-wbp = ਵਾਲਪੁਰੀ
language-name-wo = ਵੋਲੋਫ
language-name-wuu = ਚੀਨੀ ਵੂ
language-name-xal = ਕਾਲਮਿਕ
language-name-xh = ਖੋਸਾ
language-name-xog = ਸੋਗਾ
language-name-yav = ਯਾਂਗਬੇਨ
language-name-ybb = ਯੇਂਬਾ
language-name-yi = ਯਿਦਿਸ਼
language-name-yo = ਯੋਰੂਬਾ
language-name-yue = ਕੈਂਟੋਨੀਜ਼
language-name-zgh = ਮਿਆਰੀ ਮੋਰੋਕੇਨ ਟਾਮਾਜ਼ਿਕ
language-name-zu = ਜ਼ੁਲੂ
language-name-zun = ਜ਼ੂਨੀ
language-name-zxx = ਬੋਲੀ ਸੰਬੰਧੀ ਕੋਈ ਸਮੱਗਰੀ ਨਹੀਂ
language-name-zza = ਜ਼ਾਜ਼ਾ
