language-name-ar_001 = modernes Hocharabisch
language-name-car = karibische Sprache
language-name-chb = Chibcha-Sprache
language-name-del = Delawarisch
language-name-fur = Friulanisch
language-name-ha = Hausa
language-name-haw = Hawaiianisch
language-name-hmn = Miao-Sprache
language-name-mus = Muskogee-Sprache
language-name-niu = Niueanisch
language-name-pag = Pangasinensisch
language-name-sh = Serbokroatisch
language-name-szl = Schlesisch
