language-name-ady = adygué
language-name-ang = vieil anglais
language-name-az = azerbaïdjanais
language-name-bez = bena
language-name-bik = bicol
language-name-byn = bilen
language-name-byv = medumba
language-name-chg = tchagatay
language-name-chn = chinook
language-name-ckb = kurde central
language-name-cr = cri
language-name-den = slave
language-name-dgr = tlicho
language-name-esu = yupik central
language-name-ewo = ewondo
language-name-frc = cajun
language-name-goh = vieux haut-allemand
language-name-gu = gujarati
language-name-ii = yi de Sichuan
language-name-ilo = ilocano
language-name-kbd = kabarde
language-name-ken = kenyang
language-name-kj = kuanyama
language-name-kl = kalaallisut
language-name-ksh = kölsch
language-name-liv = live
language-name-luo = luo
language-name-lzh = chinois classique
language-name-mgo = meta’
language-name-mwr = marwari
language-name-mwv = mentawai
language-name-nds = bas allemand
language-name-nds_NL = bas saxon
language-name-njo = ao naga
language-name-nwc = newari classique
language-name-nyn = nkole
language-name-or = odia
language-name-pau = palauan
language-name-pdc = allemand de Pennsylvanie
language-name-pdt = bas allemand mennonite
language-name-peo = vieux perse
language-name-pfl = palatin
language-name-pro = ancien occitan
language-name-rar = rarotonga
language-name-rup = aroumain
language-name-sat = santali
language-name-sdh = kurde méridional
language-name-se = same du Nord
language-name-sei = seri
language-name-sg = sango
language-name-sga = vieil irlandais
language-name-sly = selayar
language-name-sma = same du Sud
language-name-smj = same de Lule
language-name-sms = same skolt
language-name-sw_CD = swahili congolais
language-name-tru = turoyo
language-name-tzm = tamazight
language-name-vo = volapük
