language-name-ab = آبخازی
language-name-af = آفریکانس
language-name-agq = آقم
language-name-ak = آکان
language-name-am = امهری
language-name-ar = عربی
language-name-ar_001 = مدرن استاندارد عربی
language-name-arn = ماپوچه
language-name-as = آسامی
language-name-asa = آسو
language-name-az = آذری ِترکی
language-name-az_Arab = جنوبی آذری ترکی
language-name-ba = باشقیری
language-name-be = بلاروسی
language-name-bem = بمبایی
language-name-bez = بنایی
language-name-bg = بلغاری
language-name-bgn = غربی بلوچی
language-name-bm = بامبارایی
language-name-bn = بنگالی
language-name-bo = تبتی
language-name-br = برِتونی
language-name-brx = بدویی
language-name-bs = بوسنیایی
language-name-ca = کاتالونی
language-name-ce = چچنی
language-name-cgg = چیگا
language-name-chr = چروکیایی
language-name-ckb = میونی کوردی
language-name-co = کورسیکان
language-name-cs = چکی
language-name-cv = چوواشی
language-name-cy = ولزی
language-name-da = دانمارکی
language-name-dav = تایتا
language-name-de = آلمانی
language-name-de_AT = اتریش ِآلمانی
language-name-de_CH = سوییس ِآلمانی
language-name-dje = زارمایی
language-name-dsb = پایین صربی
language-name-dua = دوئالایی
language-name-dyo = جولا-فونی
language-name-dz = دزونگخا
language-name-ebu = امبو
language-name-ee = اوه‌یی
language-name-el = یونانی
language-name-en = انگلیسی
language-name-en_AU = استرالیای ِانگلیسی
language-name-en_CA = کانادای ِانگلیسی
language-name-en_GB = بریتیش انگلیسی
language-name-en_US = امریکن انگلیسی
language-name-eo = اسپرانتو
language-name-es = ایسپانیولی
language-name-es_419 = جنوبی آمریکای ِایسپانیولی
language-name-es_ES = اروپای ِایسپانیولی
language-name-es_MX = مکزیک ِایسپانیولی
language-name-et = استونیایی
language-name-eu = باسکی
language-name-fa = فارسی
language-name-fi = فینیش
language-name-fil = فیلیپینو
language-name-fj = فیجیایی
language-name-fo = فارویی
language-name-fr = فرانسوی
language-name-fr_CA = کانادای ِفرانسوی
language-name-fr_CH = سوییس ِفرانسوی
language-name-fy = غربی فیریزی
language-name-ga = ایریش
language-name-gag = گاگائوزی
language-name-gl = گالیک
language-name-gn = گورانی
language-name-gsw = سوییس آلمانی
language-name-gu = گجراتی
language-name-guz = گوسی
language-name-gv = مانکس
language-name-ha = هوسا
language-name-haw = هاواییایی
language-name-he = عبری
language-name-hi = هندی
language-name-hr = کرواتی
language-name-hsb = بالایی صربی
language-name-ht = هائتیایی
language-name-hu = مجاری
language-name-hy = ارمنی
language-name-id = اندونزیایی
language-name-ig = ایگبو
language-name-ii = سیچوئان یی
language-name-is = ایسلندی
language-name-it = ایتالیایی
language-name-iu = انوکتیتوت
language-name-ja = جاپونی
language-name-jgo = نگومبا
language-name-jmc = ماچامه
language-name-jv = جاوایی
language-name-ka = گرجی
language-name-kab = قبایلی
language-name-kam = کامبایی
language-name-kde = ماکونده
language-name-kea = کیپ وُردی
language-name-khq = کویرا چیینی
language-name-ki = کیکویو
language-name-kk = قزاقی
language-name-kl = کالائلیسوت
language-name-kln = کالنجین
language-name-km = خمری
language-name-kn = کانّادا
language-name-ko = کُره‌یی
language-name-koi = کومی-پرمیاک
language-name-kok = کونکانی
language-name-ks = کشمیری
language-name-ksb = شامبالا
language-name-ksf = بافیایی
language-name-ku = کوردی
language-name-kw = کورنیش
language-name-ky = قرقیزی
language-name-la = لاتین
language-name-lag = لانگی
language-name-lb = لوکزامبورگی
language-name-lg = گاندا
language-name-lkt = لاکوتا
language-name-ln = لینگالا
language-name-lo = لائویی
language-name-lrc = شمالی لُری
language-name-lt = لتونیایی
language-name-lu = لوبا-کاتانگا
language-name-luo = لوئو
language-name-luy = لوییا
language-name-lv = لاتویایی
language-name-mas = ماسایی
language-name-mer = مِرویی
language-name-mfe = موریسین
language-name-mg = مالاگاسی
language-name-mgh = ماخوئا-میتو
language-name-mgo = مِتاء
language-name-mi = مائوری
language-name-mk = مقدونی
language-name-ml = مالایالام
language-name-mn = مغولی
language-name-moh = موهاک
language-name-mr = ماراتی
language-name-ms = مالایی
language-name-mt = مالتی
language-name-mua = موندانگ
language-name-my = برمه‌یی
language-name-mzn = مازرونی
language-name-naq = ناما
language-name-nb = نروژی بوکمال
language-name-nd = شمالی ندبله
language-name-nds = پایین آلمانی
language-name-nds_NL = پایین ساکسونی
language-name-ne = نپالی
language-name-nl = هلندی
language-name-nl_BE = فلمیش
language-name-nmg = کوئاسیو
language-name-nn = نروژی نینورسک
language-name-nqo = نئکو
language-name-nus = نوئر
language-name-nyn = نیانکوله
language-name-om = اورومو
language-name-or = اوریا
language-name-pa = پنجابی
language-name-pl = لهستونی
language-name-ps = پشتو
language-name-pt = پرتغالی
language-name-pt_BR = برزیل ِپرتغالی
language-name-pt_PT = اروپای ِپرتغالی
language-name-qu = قوئچوئا
language-name-quc = کئیچه‌ئی
language-name-rm = رومانش
language-name-rn = روندی
language-name-ro = رومانیایی
language-name-ro_MD = مولداوی
language-name-rof = رومبو
language-name-ru = روسی
language-name-rw = کنیاروآندایی
language-name-rwk = روآیی
language-name-sa = سانسکریت
language-name-saq = سامبورو
language-name-sbp = سانگوو
language-name-sd = سندی
language-name-sdh = جنوبی کردی
language-name-se = شمالی سامی
language-name-seh = سِنایی
language-name-ses = کویرابورا سنی
language-name-sg = سانگو
language-name-shi = تاچلهیت
language-name-si = سینهالا
language-name-sk = اسلواکی
language-name-sl = اسلوونیایی
language-name-sma = جنوبی سامی
language-name-smj = لوله سامی
language-name-smn = ایناری سامی
language-name-sms = سکولت سامی
language-name-sn = شونا
language-name-so = سومالیایی
language-name-sq = آلبانیایی
language-name-sr = صربی
language-name-su = سوندانسی
language-name-sv = سوئدی
language-name-sw = سواحیلی
language-name-sw_CD = کنگو سواحیلی
language-name-ta = تامیلی
language-name-te = تلوگویی
language-name-teo = تسویی
language-name-tg = تاجیکی
language-name-th = تایی
language-name-ti = تیگرینیایی
language-name-tk = ترکمونی
language-name-to = تونگانی
language-name-tr = ترکی
language-name-tt = تاتاری
language-name-twq = تاساواقی
language-name-tzm = میونی اطلس تامزیقی
language-name-ug = ئوغوری
language-name-uk = اوکراینی
language-name-und = نشناسی‌یه زوون
language-name-ur = اردو
language-name-uz = ازبکی
language-name-vai = وایی
language-name-vi = ویتنامی
language-name-vun = وونجویی
language-name-wbp = والرپیری
language-name-wo = وولفی
language-name-xh = خوسا
language-name-xog = سوگا
language-name-yo = یوروبا
language-name-zgh = مراکش ِاستاندارد ِتامازیقتی
language-name-zh = چینی
language-name-zh_Hans = ساده چینی
language-name-zh_Hant = سنتی چینی
language-name-zu = زولو
language-name-zxx = این زوون بشناسی‌یه نیّه
