language-name-aa = afarera
language-name-ab = abkhaziera
language-name-ace = acehnera
language-name-ach = acholiera
language-name-ada = adangmera
language-name-ady = adigera
language-name-af = afrikaansa
language-name-agq = aghemera
language-name-ain = ainuera
language-name-ak = akanera
language-name-ale = aleutera
language-name-alt = hegoaldeko altaiera
language-name-am = amharera
language-name-an = aragoiera
language-name-anp = angikera
language-name-ar = arabiera
language-name-ar_001 = arabiera moderno estandarra
language-name-arn = maputxea
language-name-arp = arapahoa
language-name-as = assamera
language-name-asa = asua
language-name-ast = asturiera
language-name-av = avarera
language-name-awa = awadhiera
language-name-ay = aimara
language-name-az = azerbaijanera
language-name-ba = bashkirrera
language-name-ban = baliera
language-name-bas = basaa
language-name-be = bielorrusiera
language-name-bem = bembera
language-name-bez = benera
language-name-bg = bulgariera
language-name-bho = bhojpurera
language-name-bi = bislama
language-name-bin = edoera
language-name-bla = siksikera
language-name-bm = bambarera
language-name-bn = bengalera
language-name-bo = tibetera
language-name-br = bretoiera
language-name-brx = bodoera
language-name-bs = bosniera
language-name-bug = buginera
language-name-byn = bilena
language-name-ca = katalana
language-name-ce = txetxeniera
language-name-ceb = cebuera
language-name-cgg = chigera
language-name-ch = chamorrera
language-name-chk = chuukera
language-name-chm = mariera
language-name-cho = choctaw
language-name-chr = txerokiera
language-name-chy = cheyennera
language-name-ckb = sorania
language-name-co = korsikera
language-name-crs = seselwa frantses-kreolera
language-name-cs = txekiera
language-name-cu = Elizako eslaviera
language-name-cv = chuvashera
language-name-cy = galesa
language-name-da = daniera
language-name-dak = dakotera
language-name-dar = dargvera
language-name-dav = taitera
language-name-de = alemana
language-name-de_AT = Austriako alemana
language-name-dgr = dogribera
language-name-dje = zarma
language-name-dsb = behe-sorabiera
language-name-dua = dualera
language-name-dv = divehiera
language-name-dyo = fonyi jolera
language-name-dz = dzongkha
language-name-dzg = dazaga
language-name-ebu = embua
language-name-ee = eweera
language-name-efi = efikera
language-name-eka = akajuka
language-name-el = greziera
language-name-en = ingelesa
language-name-en_AU = Australiako ingelesa
language-name-en_CA = Kanadako ingelesa
language-name-en_GB = Britainia Handiko ingelesa
language-name-en_US = AEBko ingelesa
language-name-eo = esperantoa
language-name-es = espainiera
language-name-es_419 = Latinoamerikako espainiera
language-name-es_MX = Mexikoko espainiera
language-name-et = estoniera
language-name-eu = euskara
language-name-ewo = ewondera
language-name-fa = persiera
language-name-ff = fula
language-name-fi = finlandiera
language-name-fil = filipinera
language-name-fj = fijiera
language-name-fo = faroera
language-name-fon = fona
language-name-fr = frantsesa
language-name-fr_CA = Kanadako frantsesa
language-name-fr_CH = Suitzako frantsesa
language-name-fur = friuliera
language-name-fy = frisiera
language-name-ga = gaelikoa
language-name-gaa = ga
language-name-gag = gagauzera
language-name-gd = Eskoziako gaelikoa
language-name-gez = ge’ez
language-name-gil = gilbertera
language-name-gl = galiziera
language-name-gn = guaraniera
language-name-gor = gorontaloa
language-name-gu = gujaratera
language-name-guz = gusiiera
language-name-gv = manxera
language-name-gwi = gwichʼin
language-name-ha = hausa
language-name-haw = hawaiiera
language-name-he = hebreera
language-name-hi = hindia
language-name-hil = hiligainona
language-name-hmn = hmong
language-name-hr = kroaziera
language-name-hsb = goi-sorabiera
language-name-ht = Haitiko kreolera
language-name-hu = hungariera
language-name-hup = hupera
language-name-hy = armeniera
language-name-hz = herera
language-name-ia = interlingua
language-name-iba = ibanera
language-name-ibb = ibibioera
language-name-id = indonesiera
language-name-ie = interlingue
language-name-ig = igboera
language-name-ii = Sichuango yiera
language-name-ilo = ilokanera
language-name-inh = ingushera
language-name-io = ido
language-name-is = islandiera
language-name-it = italiera
language-name-iu = inuitera
language-name-ja = japoniera
language-name-jbo = lojbanera
language-name-jgo = ngomba
language-name-jmc = machamera
language-name-jv = javera
language-name-ka = georgiera
language-name-kab = kabilera
language-name-kac = jingpoera
language-name-kaj = kaiji
language-name-kam = kambera
language-name-kbd = kabardiera
language-name-kcg = kataba
language-name-kde = makondera
language-name-kea = Cabo Verdeko kreola
language-name-kfo = koroa
language-name-kg = kikongoa
language-name-kha = kashia
language-name-khq = koyra chiiniera
language-name-ki = kikuyuera
language-name-kj = kuanyama
language-name-kk = kazakhera
language-name-kkj = kakoa
language-name-kl = groenlandiera
language-name-kln = kalenjinera
language-name-km = khemerera
language-name-kmb = kimbundua
language-name-kn = kannada
language-name-ko = koreera
language-name-koi = komi-permyakera
language-name-kok = konkanera
language-name-kpe = kpellea
language-name-kr = kanuriera
language-name-krc = karachayera-balkarera
language-name-krl = kareliera
language-name-kru = kurukhera
language-name-ks = kaxmirera
language-name-ksb = shambalera
language-name-ksf = bafiera
language-name-ksh = koloniera
language-name-ku = kurduera
language-name-kum = kumykera
language-name-kv = komiera
language-name-kw = kornubiera
language-name-ky = kirgizera
language-name-la = latina
language-name-lad = ladinera
language-name-lag = langiera
language-name-lb = luxenburgera
language-name-lez = lezgiera
language-name-lg = gandera
language-name-li = limburgera
language-name-lkt = lakotera
language-name-ln = lingala
language-name-lo = laosera
language-name-loz = loziera
language-name-lrc = iparraldeko lurera
language-name-lt = lituaniera
language-name-lu = luba-katangera
language-name-lua = txilubera
language-name-lun = lundera
language-name-luo = luoera
language-name-lus = mizoa
language-name-luy = luhyera
language-name-lv = letoniera
language-name-mad = madurera
language-name-mag = magahiera
language-name-mai = maithilera
language-name-mak = makasarera
language-name-mas = masaiera
language-name-mdf = mokxera
language-name-men = mendeera
language-name-mer = meruera
language-name-mfe = Mauritaniako kreolera
language-name-mg = malgaxea
language-name-mgh = makhuwa-meettoera
language-name-mgo = metera
language-name-mh = marshallera
language-name-mi = maoriera
language-name-mic = mikmakera
language-name-min = minangkabauera
language-name-mk = mazedoniera
language-name-ml = malabarera
language-name-mn = mongoliera
language-name-mni = manipurera
language-name-moh = mohawkera
language-name-mos = moreera
language-name-mr = marathera
language-name-ms = malaysiera
language-name-mt = maltera
language-name-mua = mudangera
language-name-mul = zenbait hizkuntza
language-name-mus = creera
language-name-mwl = mirandera
language-name-my = birmaniera
language-name-myv = erziera
language-name-mzn = mazandarandera
language-name-na = nauruera
language-name-nap = napoliera
language-name-naq = namera
language-name-nd = iparraldeko ndebeleera
language-name-nds_NL = behe-saxoiera
language-name-ne = nepalera
language-name-new = newarera
language-name-ng = ndongera
language-name-nia = niasa
language-name-niu = niuera
language-name-nl = nederlandera
language-name-nl_BE = flandriera
language-name-nmg = kwasiera
language-name-nn = nynorsk norvegiera
language-name-nnh = ngiemboonera
language-name-no = norvegiera
language-name-nog = nogaiera
language-name-nqo = n’koera
language-name-nr = hegoaldeko ndebelera
language-name-nso = pediera
language-name-nus = nuerera
language-name-nv = navahoera
language-name-ny = chewera
language-name-nyn = ankolera
language-name-oc = okzitaniera
language-name-om = oromoera
language-name-or = oriya
language-name-os = osetiera
language-name-pa = punjabera
language-name-pag = pangasinanera
language-name-pam = pampangera
language-name-pap = papiamentoa
language-name-pau = palauera
language-name-pcm = Nigeriako pidgina
language-name-pl = poloniera
language-name-prg = prusiera
language-name-ps = paxtuera
language-name-pt = portugesa
language-name-pt_BR = Brasilgo portugesa
language-name-qu = kitxua
language-name-quc = quicheera
language-name-rap = rapa nui
language-name-rar = rarotongera
language-name-rm = erretorromaniera
language-name-rn = rundiera
language-name-ro = errumaniera
language-name-ro_MD = moldaviera
language-name-rof = romboera
language-name-root = erroa
language-name-ru = errusiera
language-name-rup = aromania
language-name-rw = kinyaruanda
language-name-rwk = rwaera
language-name-sa = sanskritoa
language-name-sad = sandawea
language-name-sah = sakhera
language-name-saq = samburuera
language-name-sat = santalera
language-name-sba = ngambayera
language-name-sbp = sanguera
language-name-sc = sardiniera
language-name-scn = siziliera
language-name-sco = eskoziera
language-name-sd = sindhia
language-name-se = iparraldeko samiera
language-name-seh = senera
language-name-ses = koyraboro sennia
language-name-sg = sangoa
language-name-sh = serbokroaziera
language-name-shi = tachelhita
language-name-shn = shanera
language-name-si = sinhala
language-name-sk = eslovakiera
language-name-sl = esloveniera
language-name-sm = samoera
language-name-sma = hegoaldeko samiera
language-name-smj = lule samiera
language-name-smn = inari-samiera
language-name-sms = skolten samiera
language-name-sn = shonera
language-name-snk = soninkera
language-name-so = somaliera
language-name-sq = albaniera
language-name-sr = serbiera
language-name-srn = srananera
language-name-ss = swatiera
language-name-ssy = sahoa
language-name-st = hegoaldeko sothoera
language-name-su = sundanera
language-name-suk = sukumera
language-name-sv = suediera
language-name-sw = swahilia
language-name-sw_CD = Kongoko swahilia
language-name-swb = komoreera
language-name-syr = asiriera
language-name-ta = tamilera
language-name-te = telugua
language-name-tem = temnea
language-name-teo = tesoera
language-name-tet = tetuma
language-name-tg = tajikera
language-name-th = thailandiera
language-name-ti = tigriñera
language-name-tig = tigrea
language-name-tk = turkmenera
language-name-tl = tagalog
language-name-tlh = klingonera
language-name-tn = tswanera
language-name-to = tongera
language-name-tpi = tok pisina
language-name-tr = turkiera
language-name-trv = tarokoa
language-name-ts = tsongera
language-name-tt = tatarera
language-name-tum = tumbukera
language-name-tvl = tuvaluera
language-name-tw = twia
language-name-twq = tasawaqa
language-name-ty = tahitiera
language-name-tyv = tuvera
language-name-tzm = Erdialdeko Atlaseko amazigera
language-name-udm = udmurtera
language-name-ug = uigurrera
language-name-uk = ukrainera
language-name-umb = umbunduera
language-name-und = hizkuntza ezezaguna
language-name-ur = urdua
language-name-uz = uzbekera
language-name-vai = vaiera
language-name-ve = vendera
language-name-vi = vietnamera
language-name-vo = volapüka
language-name-vun = vunjoa
language-name-wa = waloiera
language-name-wae = walserera
language-name-wal = welayta
language-name-war = samerera
language-name-wo = wolofera
language-name-xal = kalmykera
language-name-xh = xhosera
language-name-xog = sogera
language-name-yav = jangbenera
language-name-ybb = yemba
language-name-yi = yiddisha
language-name-yo = jorubera
language-name-yue = kantonera
language-name-zgh = amazigera estandarra
language-name-zh = txinera
language-name-zh_Hans = txinera soildua
language-name-zh_Hant = txinera tradizionala
language-name-zu = zuluera
language-name-zun = zuñia
language-name-zxx = ez dago eduki linguistikorik
language-name-zza = zazakia
