language-name-aa = Afar
language-name-ab = Abkhaz
language-name-ace = Aceh
language-name-ach = Acoli
language-name-ada = Adangme
language-name-ady = Adygei
language-name-ae = Avesta
language-name-aeb = Arab Tunisia
language-name-af = Afrikaans
language-name-afh = Afrihili
language-name-agq = Aghem
language-name-ain = Ainu
language-name-ak = Akan
language-name-akk = Akkadia
language-name-akz = Alabama
language-name-ale = Aleut
language-name-alt = Altai Selatan
language-name-am = Amharik
language-name-an = Aragon
language-name-ang = Inggris Kuno
language-name-anp = Angika
language-name-ar = Arab
language-name-ar_001 = Arab Standar Modern
language-name-arc = Aram
language-name-arn = Mapuche
language-name-arp = Arapaho
language-name-arq = Arab Aljazair
language-name-ars = Arab Najdi
language-name-arw = Arawak
language-name-ary = Arab Maroko
language-name-arz = Arab Mesir
language-name-as = Assam
language-name-asa = Asu
language-name-ase = Bahasa Isyarat Amerika
language-name-ast = Asturia
language-name-av = Avar
language-name-awa = Awadhi
language-name-ay = Aymara
language-name-az = Azerbaijani
language-name-ba = Bashkir
language-name-bal = Baluchi
language-name-ban = Bali
language-name-bar = Bavaria
language-name-bas = Basa
language-name-bax = Bamun
language-name-bbc = Batak Toba
language-name-bbj = Ghomala
language-name-be = Belarusia
language-name-bej = Beja
language-name-bem = Bemba
language-name-bew = Betawi
language-name-bez = Bena
language-name-bfd = Bafut
language-name-bg = Bulgaria
language-name-bgn = Balochi Barat
language-name-bho = Bhojpuri
language-name-bi = Bislama
language-name-bik = Bikol
language-name-bin = Bini
language-name-bjn = Banjar
language-name-bkm = Kom
language-name-bla = Siksika
language-name-bm = Bambara
language-name-bn = Bengali
language-name-bo = Tibet
language-name-br = Breton
language-name-bra = Braj
language-name-brx = Bodo
language-name-bs = Bosnia
language-name-bss = Akoose
language-name-bua = Buriat
language-name-bug = Bugis
language-name-bum = Bulu
language-name-byn = Blin
language-name-byv = Medumba
language-name-ca = Katalan
language-name-cad = Kado
language-name-car = Karib
language-name-cay = Cayuga
language-name-cch = Atsam
language-name-ce = Chechen
language-name-ceb = Cebuano
language-name-cgg = Kiga
language-name-ch = Chamorro
language-name-chb = Chibcha
language-name-chg = Chagatai
language-name-chk = Chuuke
language-name-chm = Mari
language-name-chn = Jargon Chinook
language-name-cho = Koktaw
language-name-chp = Chipewyan
language-name-chr = Cherokee
language-name-chy = Cheyenne
language-name-ckb = Kurdi Sorani
language-name-co = Korsika
language-name-cop = Koptik
language-name-cr = Kree
language-name-crh = Tatar Krimea
language-name-crs = Seselwa Kreol Prancis
language-name-cs = Cheska
language-name-csb = Kashubia
language-name-cu = Bahasa Gereja Slavonia
language-name-cv = Chuvash
language-name-cy = Welsh
language-name-da = Dansk
language-name-dak = Dakota
language-name-dar = Dargwa
language-name-dav = Taita
language-name-de = Jerman
language-name-del = Delaware
language-name-den = Slave
language-name-dgr = Dogrib
language-name-din = Dinka
language-name-dje = Zarma
language-name-doi = Dogri
language-name-dsb = Sorbia Hilir
language-name-dua = Duala
language-name-dum = Belanda Abad Pertengahan
language-name-dv = Divehi
language-name-dyo = Jola-Fonyi
language-name-dyu = Dyula
language-name-dz = Dzongkha
language-name-dzg = Dazaga
language-name-ebu = Embu
language-name-ee = Ewe
language-name-efi = Efik
language-name-egy = Mesir Kuno
language-name-eka = Ekajuk
language-name-el = Yunani
language-name-elx = Elam
language-name-en = Inggris
language-name-enm = Inggris Abad Pertengahan
language-name-eo = Esperanto
language-name-es = Spanyol
language-name-et = Esti
language-name-eu = Basque
language-name-ewo = Ewondo
language-name-fa = Persia
language-name-fan = Fang
language-name-fat = Fanti
language-name-ff = Fula
language-name-fi = Suomi
language-name-fil = Filipino
language-name-fj = Fiji
language-name-fo = Faroe
language-name-fon = Fon
language-name-fr = Prancis
language-name-frc = Prancis Cajun
language-name-frm = Prancis Abad Pertengahan
language-name-fro = Prancis Kuno
language-name-frp = Arpitan
language-name-frr = Frisia Utara
language-name-frs = Frisia Timur
language-name-fur = Friuli
language-name-fy = Frisia Barat
language-name-ga = Irlandia
language-name-gaa = Ga
language-name-gag = Gagauz
language-name-gay = Gayo
language-name-gba = Gbaya
language-name-gd = Gaelik Skotlandia
language-name-gez = Geez
language-name-gil = Gilbert
language-name-gl = Galisia
language-name-glk = Gilaki
language-name-gmh = Jerman Abad Pertengahan
language-name-gn = Guarani
language-name-goh = Jerman Kuno
language-name-gon = Gondi
language-name-gor = Gorontalo
language-name-got = Gotik
language-name-grb = Grebo
language-name-grc = Yunani Kuno
language-name-gu = Gujarat
language-name-guz = Gusii
language-name-gv = Manx
language-name-gwi = Gwich’in
language-name-ha = Hausa
language-name-hai = Haida
language-name-haw = Hawaii
language-name-he = Ibrani
language-name-hi = Hindi
language-name-hif = Hindi Fiji
language-name-hil = Hiligaynon
language-name-hit = Hitit
language-name-hmn = Hmong
language-name-ho = Hiri Motu
language-name-hr = Kroasia
language-name-hsb = Sorbia Hulu
language-name-ht = Kreol Haiti
language-name-hu = Hungaria
language-name-hup = Hupa
language-name-hy = Armenia
language-name-hz = Herero
language-name-ia = Interlingua
language-name-iba = Iban
language-name-ibb = Ibibio
language-name-id = Indonesia
language-name-ie = Interlingue
language-name-ig = Igbo
language-name-ii = Sichuan Yi
language-name-ik = Inupiak
language-name-ilo = Iloko
language-name-inh = Ingushetia
language-name-io = Ido
language-name-is = Islandia
language-name-it = Italia
language-name-iu = Inuktitut
language-name-ja = Jepang
language-name-jbo = Lojban
language-name-jgo = Ngomba
language-name-jmc = Machame
language-name-jpr = Ibrani-Persia
language-name-jrb = Ibrani-Arab
language-name-jv = Jawa
language-name-ka = Georgia
language-name-kaa = Kara-Kalpak
language-name-kab = Kabyle
language-name-kac = Kachin
language-name-kaj = Jju
language-name-kam = Kamba
language-name-kaw = Kawi
language-name-kbd = Kabardi
language-name-kbl = Kanembu
language-name-kcg = Tyap
language-name-kde = Makonde
language-name-kea = Kabuverdianu
language-name-ken = Kenyang
language-name-kfo = Koro
language-name-kg = Kongo
language-name-kha = Khasi
language-name-kho = Khotan
language-name-khq = Koyra Chiini
language-name-ki = Kikuyu
language-name-kj = Kuanyama
language-name-kk = Kazakh
language-name-kkj = Kako
language-name-kl = Kalaallisut
language-name-kln = Kalenjin
language-name-km = Khmer
language-name-kmb = Kimbundu
language-name-kn = Kannada
language-name-ko = Korea
language-name-koi = Komi-Permyak
language-name-kok = Konkani
language-name-kos = Kosre
language-name-kpe = Kpelle
language-name-kr = Kanuri
language-name-krc = Karachai Balkar
language-name-kri = Krio
language-name-krl = Karelia
language-name-kru = Kuruk
language-name-ks = Kashmir
language-name-ksb = Shambala
language-name-ksf = Bafia
language-name-ksh = Dialek Kolsch
language-name-ku = Kurdi
language-name-kum = Kumyk
language-name-kut = Kutenai
language-name-kv = Komi
language-name-kw = Kornish
language-name-ky = Kirgiz
language-name-la = Latin
language-name-lad = Ladino
language-name-lag = Langi
language-name-lah = Lahnda
language-name-lam = Lamba
language-name-lb = Luksemburg
language-name-lez = Lezghia
language-name-lg = Ganda
language-name-li = Limburgia
language-name-lij = Liguria
language-name-lkt = Lakota
language-name-ln = Lingala
language-name-lo = Lao
language-name-lol = Mongo
language-name-lou = Kreol Louisiana
language-name-loz = Lozi
language-name-lrc = Luri Utara
language-name-lt = Lituavi
language-name-lu = Luba-Katanga
language-name-lua = Luba-Lulua
language-name-lui = Luiseno
language-name-lun = Lunda
language-name-luo = Luo
language-name-lus = Mizo
language-name-luy = Luyia
language-name-lv = Latvi
language-name-lzz = Laz
language-name-mad = Madura
language-name-maf = Mafa
language-name-mag = Magahi
language-name-mai = Maithili
language-name-mak = Makasar
language-name-man = Mandingo
language-name-mas = Masai
language-name-mde = Maba
language-name-mdf = Moksha
language-name-mdr = Mandar
language-name-men = Mende
language-name-mer = Meru
language-name-mfe = Morisien
language-name-mg = Malagasi
language-name-mga = Irlandia Abad Pertengahan
language-name-mgh = Makhuwa-Meetto
language-name-mgo = Meta’
language-name-mh = Marshall
language-name-mi = Maori
language-name-mic = Mikmak
language-name-min = Minangkabau
language-name-mk = Makedonia
language-name-ml = Malayalam
language-name-mn = Mongolia
language-name-mnc = Manchuria
language-name-mni = Manipuri
language-name-moh = Mohawk
language-name-mos = Mossi
language-name-mr = Marathi
language-name-ms = Melayu
language-name-mt = Malta
language-name-mua = Mundang
language-name-mul = Beberapa Bahasa
language-name-mus = Bahasa Muskogee
language-name-mwl = Miranda
language-name-mwr = Marwari
language-name-mwv = Mentawai
language-name-my = Burma
language-name-mye = Myene
language-name-myv = Eryza
language-name-mzn = Mazanderani
language-name-na = Nauru
language-name-nap = Neapolitan
language-name-naq = Nama
language-name-nb = Bokmål Norwegia
language-name-nd = Ndebele Utara
language-name-nds = Jerman Rendah
language-name-ne = Nepali
language-name-new = Newari
language-name-ng = Ndonga
language-name-nia = Nias
language-name-niu = Niuea
language-name-nl = Belanda
language-name-nmg = Kwasio
language-name-nn = Nynorsk Norwegia
language-name-nnh = Ngiemboon
language-name-no = Norwegia
language-name-nog = Nogai
language-name-non = Norse Kuno
language-name-nqo = N’Ko
language-name-nr = Ndebele Selatan
language-name-nso = Sotho Utara
language-name-nus = Nuer
language-name-nv = Navajo
language-name-nwc = Newari Klasik
language-name-ny = Nyanja
language-name-nym = Nyamwezi
language-name-nyn = Nyankole
language-name-nyo = Nyoro
language-name-nzi = Nzima
language-name-oc = Ositania
language-name-oj = Ojibwa
language-name-om = Oromo
language-name-or = Oriya
language-name-os = Ossetia
language-name-osa = Osage
language-name-ota = Turki Osmani
language-name-pa = Punjabi
language-name-pag = Pangasina
language-name-pal = Pahlevi
language-name-pam = Pampanga
language-name-pap = Papiamento
language-name-pau = Palau
language-name-pcm = Pidgin Nigeria
language-name-pdc = Jerman Pennsylvania
language-name-peo = Persia Kuno
language-name-phn = Funisia
language-name-pi = Pali
language-name-pl = Polski
language-name-pon = Pohnpeia
language-name-prg = Prusia
language-name-pro = Provencal Lama
language-name-ps = Pashto
language-name-pt = Portugis
language-name-qu = Quechua
language-name-quc = Kʼicheʼ
language-name-raj = Rajasthani
language-name-rap = Rapanui
language-name-rar = Rarotonga
language-name-rm = Reto-Roman
language-name-rn = Rundi
language-name-ro = Rumania
language-name-ro_MD = Moldavia
language-name-rof = Rombo
language-name-rom = Romani
language-name-root = Root
language-name-rtm = Rotuma
language-name-ru = Rusia
language-name-rup = Aromania
language-name-rw = Kinyarwanda
language-name-rwk = Rwa
language-name-sa = Sanskerta
language-name-sad = Sandawe
language-name-sah = Sakha
language-name-sam = Aram Samaria
language-name-saq = Samburu
language-name-sas = Sasak
language-name-sat = Santali
language-name-sba = Ngambai
language-name-sbp = Sangu
language-name-sc = Sardinia
language-name-scn = Sisilia
language-name-sco = Skotlandia
language-name-sd = Sindhi
language-name-sdh = Kurdi Selatan
language-name-se = Sami Utara
language-name-see = Seneca
language-name-seh = Sena
language-name-sei = Seri
language-name-sel = Selkup
language-name-ses = Koyraboro Senni
language-name-sg = Sango
language-name-sga = Irlandia Kuno
language-name-sh = Serbo-Kroasia
language-name-shi = Tachelhit
language-name-shn = Shan
language-name-shu = Arab Suwa
language-name-si = Sinhala
language-name-sid = Sidamo
language-name-sk = Slovak
language-name-sl = Sloven
language-name-sli = Silesia Rendah
language-name-sly = Selayar
language-name-sm = Samoa
language-name-sma = Sami Selatan
language-name-smj = Lule Sami
language-name-smn = Inari Sami
language-name-sms = Skolt Sami
language-name-sn = Shona
language-name-snk = Soninke
language-name-so = Somalia
language-name-sog = Sogdien
language-name-sq = Albania
language-name-sr = Serbia
language-name-srn = Sranan Tongo
language-name-srr = Serer
language-name-ss = Swati
language-name-ssy = Saho
language-name-st = Sotho Selatan
language-name-su = Sunda
language-name-suk = Sukuma
language-name-sus = Susu
language-name-sux = Sumeria
language-name-sv = Swedia
language-name-sw = Swahili
language-name-swb = Komoria
language-name-syc = Suriah Klasik
language-name-syr = Suriah
language-name-szl = Silesia
language-name-ta = Tamil
language-name-tcy = Tulu
language-name-te = Telugu
language-name-tem = Timne
language-name-teo = Teso
language-name-ter = Tereno
language-name-tet = Tetun
language-name-tg = Tajik
language-name-th = Thai
language-name-ti = Tigrinya
language-name-tig = Tigre
language-name-tiv = Tiv
language-name-tk = Turkmen
language-name-tkl = Tokelau
language-name-tl = Tagalog
language-name-tlh = Klingon
language-name-tli = Tlingit
language-name-tmh = Tamashek
language-name-tn = Tswana
language-name-to = Tonga
language-name-tog = Nyasa Tonga
language-name-tpi = Tok Pisin
language-name-tr = Turki
language-name-tru = Turoyo
language-name-trv = Taroko
language-name-ts = Tsonga
language-name-tsi = Tsimshia
language-name-tt = Tatar
language-name-ttt = Tat Muslim
language-name-tum = Tumbuka
language-name-tvl = Tuvalu
language-name-tw = Twi
language-name-twq = Tasawaq
language-name-ty = Tahiti
language-name-tyv = Tuvinia
language-name-tzm = Tamazight Maroko Tengah
language-name-udm = Udmurt
language-name-ug = Uyghur
language-name-uga = Ugarit
language-name-uk = Ukraina
language-name-umb = Umbundu
language-name-und = Bahasa Tidak Dikenal
language-name-ur = Urdu
language-name-uz = Uzbek
language-name-vai = Vai
language-name-ve = Venda
language-name-vec = Venesia
language-name-vi = Vietnam
language-name-vo = Volapuk
language-name-vot = Votia
language-name-vun = Vunjo
language-name-wa = Walloon
language-name-wae = Walser
language-name-wal = Walamo
language-name-war = Warai
language-name-was = Washo
language-name-wbp = Warlpiri
language-name-wo = Wolof
language-name-xal = Kalmuk
language-name-xh = Xhosa
language-name-xog = Soga
language-name-yao = Yao
language-name-yap = Yapois
language-name-yav = Yangben
language-name-ybb = Yemba
language-name-yi = Yiddish
language-name-yo = Yoruba
language-name-yue = Kanton
language-name-za = Zhuang
language-name-zap = Zapotek
language-name-zbl = Blissymbol
language-name-zen = Zenaga
language-name-zgh = Tamazight Maroko Standar
language-name-zh = Tionghoa
language-name-zu = Zulu
language-name-zun = Zuni
language-name-zxx = Tidak ada konten linguistik
language-name-zza = Zaza
