language-name-aa = አፋርኛ
language-name-ab = አብሐዚኛ
language-name-ace = አቻይንኛ
language-name-ach = አኮሊኛ
language-name-ada = አዳንግሜ
language-name-ady = አድይግሄ
language-name-ae = አቬስታን
language-name-af = አፍሪካንኛ
language-name-afh = አፍሪሂሊ
language-name-agq = አገም
language-name-ain = አይኑ
language-name-ak = አካንኛ
language-name-akk = አካዲያን
language-name-akz = አላባማ
language-name-ale = አልዩት
language-name-alt = ደቡባዊ አልታይ
language-name-am = አማርኛ
language-name-an = አራጎንስ
language-name-anp = አንጊካ
language-name-ar = ዓረብኛ
language-name-ar_001 = ዘመናዊ መደበኛ ዓረብኛ
language-name-arc = አራማይክ
language-name-arn = ማፑቼ
language-name-aro = አራኦና
language-name-arp = አራፓሆ
language-name-arq = የአልጄሪያ ዓረብኛ
language-name-arw = አራዋክ
language-name-as = አሳሜዛዊ
language-name-asa = አሱ
language-name-ase = የአሜሪካ የምልክት ቋንቋ
language-name-ast = አውስትሪያን
language-name-av = አቫሪክ
language-name-awa = አዋድሂ
language-name-ay = አያማርኛ
language-name-az = አዘርባጃንኛ
language-name-ba = ባስኪርኛ
language-name-bal = ባሉቺ
language-name-ban = ባሊኔስ
language-name-bar = ባቫሪያን
language-name-bas = ባሳ
language-name-bax = ባሙን
language-name-bbc = ባታካ ቶባ
language-name-be = ቤላራሻኛ
language-name-bej = ቤጃ
language-name-bem = ቤምባ
language-name-bew = ቤታዊ
language-name-bez = ቤና
language-name-bfd = ባፉት
language-name-bfq = ባዳጋ
language-name-bg = ቡልጋሪኛ
language-name-bgn = የምዕራብ ባሎቺ
language-name-bho = ቦጁሪ
language-name-bi = ቢስላምኛ
language-name-bik = ቢኮል
language-name-bin = ቢኒ
language-name-bjn = ባንጃር
language-name-bla = ሲክሲካ
language-name-bm = ባምባርኛ
language-name-bn = ቤንጋሊኛ
language-name-bo = ቲቤታንኛ
language-name-bpy = ቢሹንፑሪያ
language-name-bqi = ባክህቲያሪ
language-name-br = ብሬቶንኛ
language-name-bra = ብራጅ
language-name-brh = ብራሁዪ
language-name-brx = ቦዶ
language-name-bs = ቦስኒያንኛ
language-name-bss = አኮስ
language-name-bua = ቡሪያት
language-name-bug = ቡጊኔዝ
language-name-bum = ቡሉ
language-name-byn = ብሊን
language-name-ca = ካታላንኛ
language-name-cad = ካዶ
language-name-car = ካሪብ
language-name-cay = ካዩጋ
language-name-cch = አትሳም
language-name-ce = ችችን
language-name-ceb = ካቡዋኖ
language-name-cgg = ቺጋኛ
language-name-ch = ቻሞሮ
language-name-chb = ቺብቻ
language-name-chg = ቻጋታይ
language-name-chk = ቹክስ
language-name-chm = ማሪ
language-name-chn = ቺኑክ ጃርጎን
language-name-cho = ቾክታዋ
language-name-chp = ቺፔውያን
language-name-chr = ቼሮኬኛ
language-name-chy = ችዬኔ
language-name-ckb = የሶራኒ ኩርድኛ
language-name-co = ኮርሲካኛ
language-name-cop = ኮፕቲክ
language-name-cps = ካፒዝኖን
language-name-cr = ክሪ
language-name-crh = ክሪሚያን ተርኪሽ
language-name-crs = ሰሰላዊ ክሬኦሊ ፈረንሳይኛ
language-name-cs = ቼክኛ
language-name-cu = ቸርች ስላቪክ
language-name-cv = ቹቫሽ
language-name-cy = ወልሽ
language-name-da = ዴኒሽ
language-name-dak = ዳኮታ
language-name-dar = ዳርግዋ
language-name-dav = ታይታኛ
language-name-de = ጀርመን
language-name-de_AT = የኦስትሪያ ጀርመን
language-name-de_CH = የስዊዝ ከፍተኛ ጀርመንኛ
language-name-del = ዳላዌር
language-name-dgr = ዶግሪብ
language-name-din = ዲንካ
language-name-dje = ዛርማኛ
language-name-doi = ዶግሪ
language-name-dsb = የታችኛው ሰርቢያንኛ
language-name-dtp = ሴንተራል ዱሰን
language-name-dua = ዱዋላኛ
language-name-dv = ዲቬህ
language-name-dyo = ጆላ ፎንያኛ
language-name-dyu = ድዩላ
language-name-dz = ድዞንግኻኛ
language-name-dzg = ዳዛጋ
language-name-ebu = ኢቦኛ
language-name-ee = ኢዊ
language-name-efi = ኤፊክ
language-name-egy = የጥንታዊ ግብጽኛ
language-name-eka = ኤካጁክ
language-name-el = ግሪክኛ
language-name-en = እንግሊዝኛ
language-name-en_AU = የአውስትራሊያ እንግሊዝኛ
language-name-en_CA = የካናዳ እንግሊዝኛ
language-name-en_GB = የብሪቲሽ እንግሊዝኛ
language-name-en_US = የአሜሪካ እንግሊዝኛ
language-name-eo = ኤስፐራንቶ
language-name-es = ስፓንሽኛ
language-name-es_419 = የላቲን አሜሪካ ስፓኒሽ
language-name-es_ES = የአውሮፓ ስፓንሽኛ
language-name-es_MX = የሜክሲኮ ስፓንሽኛ
language-name-esu = ሴንተራል ዩፒክ
language-name-et = ኢስቶኒያንኛ
language-name-eu = ባስክኛ
language-name-ewo = ኤዎንዶ
language-name-fa = ፐርሺያኛ
language-name-ff = ፉላህ
language-name-fi = ፊኒሽ
language-name-fil = ፊሊፒንኛ
language-name-fj = ፊጂኛ
language-name-fo = ፋሮኛ
language-name-fon = ፎን
language-name-fr = ፈረንሳይኛ
language-name-fr_CA = የካናዳ ፈረንሳይኛ
language-name-fr_CH = የስዊዝ ፈረንሳይኛ
language-name-frc = ካጁን ፍሬንች
language-name-frp = አርፒታን
language-name-fur = ፍሩሊያን
language-name-fy = ምዕራባዊ ፍሪሲኛ
language-name-ga = አይሪሽ
language-name-gaa = ጋ
language-name-gag = ጋጉዝኛ
language-name-gan = ጋን ቻይንኛ
language-name-gd = የስኮቲሽ ጌልክኛ
language-name-gez = ግዕዝኛ
language-name-gil = ጅልበርትስ
language-name-gl = ጋሊሺያ
language-name-gn = ጓራኒኛ
language-name-gor = ጎሮንታሎ
language-name-grc = የጥንታዊ ግሪክ
language-name-gsw = የስዊዝ ጀርመን
language-name-gu = ጉጃርቲኛ
language-name-guz = ጉስሊኛ
language-name-gv = ማንክስኛ
language-name-gwi = ግዊቺን
language-name-ha = ሃውሳኛ
language-name-hak = ሃካ ቻይንኛ
language-name-haw = ሃዊያኛ
language-name-he = ዕብራይስጥ
language-name-hi = ሒንዱኛ
language-name-hil = ሂሊጋይኖን
language-name-hmn = ህሞንግ
language-name-hr = ክሮሽያንኛ
language-name-hsb = የላይኛው ሶርቢያንኛ
language-name-hsn = ዢያንግ ቻይንኛ
language-name-ht = ሃይትኛ
language-name-hu = ሀንጋሪኛ
language-name-hup = ሁፓ
language-name-hy = አርመናዊ
language-name-hz = ሄሬሮ
language-name-ia = ኢንቴርሊንጓ
language-name-iba = ኢባን
language-name-ibb = ኢቢቦ
language-name-id = ኢንዶኔዥኛ
language-name-ie = እንተርሊንግወ
language-name-ig = ኢግቦኛ
language-name-ii = ሲቹንዪኛ
language-name-ik = እኑፒያቅኛ
language-name-ilo = ኢሎኮ
language-name-inh = ኢንጉሽ
language-name-io = ኢዶ
language-name-is = አይስላንድኛ
language-name-it = ጣሊያንኛ
language-name-iu = እኑክቲቱትኛ
language-name-ja = ጃፓንኛ
language-name-jbo = ሎጅባን
language-name-jgo = ንጎባኛ
language-name-jmc = ማቻሜኛ
language-name-jv = ጃቫንኛ
language-name-ka = ጆርጂያን
language-name-kab = ካብይል
language-name-kac = ካቺን
language-name-kaj = ካጅ
language-name-kam = ካምባ
language-name-kbd = ካባርዲያን
language-name-kcg = ታያፕ
language-name-kde = ማኮንዴ
language-name-kea = ካቡቨርዲያኑ
language-name-kfo = ኮሮ
language-name-kg = ኮንጎኛ
language-name-kha = ክሃሲ
language-name-khq = ኮይራ ቺኒ
language-name-ki = ኪኩዩ
language-name-kj = ኩንያማ
language-name-kk = ካዛክኛ
language-name-kkj = ካኮ
language-name-kl = ካላሊሱትኛ
language-name-kln = ካለንጂን
language-name-km = ክህመርኛ
language-name-kmb = ኪምቡንዱ
language-name-kn = ካናዳኛ
language-name-ko = ኮሪያኛ
language-name-koi = ኮሚ ፔርምያክ
language-name-kok = ኮንካኒ
language-name-kpe = ክፔሌ
language-name-kr = ካኑሪ
language-name-krc = ካራቻይ-ባልካር
language-name-krl = ካረሊኛ
language-name-kru = ኩሩክ
language-name-ks = ካሽሚርኛ
language-name-ksb = ሻምባላ
language-name-ksf = ባፊያ
language-name-ksh = ኮሎኝያን
language-name-ku = ኩርድሽኛ
language-name-kum = ኩማይክ
language-name-kv = ኮሚ
language-name-kw = ኮርኒሽ
language-name-ky = ኪርጊዝኛ
language-name-la = ላቲንኛ
language-name-lad = ላዲኖ
language-name-lag = ላንጊ
language-name-lb = ሉክዘምበርኛ
language-name-lez = ሌዝጊያን
language-name-lg = ጋንዳኛ
language-name-li = ሊምቡርጊሽ
language-name-lkt = ላኮታ
language-name-ln = ሊንጋላኛ
language-name-lo = ላኦኛ
language-name-loz = ሎዚኛ
language-name-lrc = ሰሜናዊ ሉሪ
language-name-lt = ሉቴንያንኛ
language-name-lu = ሉባ ካታንጋ
language-name-lua = ሉባ-ሉሏ
language-name-lun = ሉንዳ
language-name-luo = ሉኦ
language-name-lus = ሚዞ
language-name-luy = ሉዪያ
language-name-lv = ላትቪያን
language-name-mad = ማዱረስ
language-name-mag = ማጋሂ
language-name-mai = ማይተሊ
language-name-mak = ማካሳር
language-name-mas = ማሳይ
language-name-mdf = ሞክሻ
language-name-men = ሜንዴ
language-name-mer = ሜሩ
language-name-mfe = ሞሪሲየኛ
language-name-mg = ማላጋስኛ
language-name-mgh = ማኩዋ ሜቶ
language-name-mgo = ሜታ
language-name-mh = ማርሻሌዝኛ
language-name-mi = ማኦሪኛ
language-name-mic = ሚክማክ
language-name-min = ሚናንግካባኡ
language-name-mk = ማሴዶንኛ
language-name-ml = ማላያላምኛ
language-name-mn = ሞንጎላዊኛ
language-name-mni = ማኒፑሪ
language-name-moh = ሞሃውክ
language-name-mos = ሞሲ
language-name-mr = ማራቲኛ
language-name-ms = ማላይኛ
language-name-mt = ማልቲስኛ
language-name-mua = ሙንዳንግ
language-name-mul = ባለብዙ ቋንቋዎች
language-name-mus = ክሪክ
language-name-mwl = ሚራንዴዝኛ
language-name-my = ቡርማኛ
language-name-myv = ኤርዝያ
language-name-mzn = ማዛንደራኒ
language-name-na = ናኡሩ
language-name-nan = ሚን ኛን ቻይንኛ
language-name-nap = ኒአፖሊታን
language-name-naq = ናማ
language-name-nb = የኖርዌይ ቦክማል
language-name-nd = ሰሜን ንዴብሌ
language-name-nds = የታችኛው ጀርመን
language-name-nds_NL = የታችኛው ሳክሰን
language-name-ne = ኔፓሊኛ
language-name-new = ነዋሪ
language-name-ng = ንዶንጋ
language-name-nia = ኒአስ
language-name-niu = ኒዩአንኛ
language-name-njo = ኦ ናጋ
language-name-nl = ደች
language-name-nl_BE = ፍሌሚሽ
language-name-nmg = ክዋሲዮ
language-name-nn = የኖርዌይ ናይኖርስክ
language-name-nnh = ኒጊምቡን
language-name-no = ኖርዌጂያን
language-name-nog = ኖጋይ
language-name-nqo = ንኮ
language-name-nr = ደቡብ ንደቤሌ
language-name-nso = ሰሜናዊ ሶቶ
language-name-nus = ኑዌር
language-name-nv = ናቫጆ
language-name-nwc = ክላሲክ ኔዋሪ
language-name-ny = ንያንጃ
language-name-nyn = ኒያንኮልኛ
language-name-oc = ኦኪታንኛ
language-name-om = ኦሮሞኛ
language-name-or = ኦዲያኛ
language-name-os = ኦሴቲክ
language-name-pa = ፑንጃብኛ
language-name-pag = ፓንጋሲናንኛ
language-name-pam = ፓምፓንጋ
language-name-pap = ፓፒአሜንቶ
language-name-pau = ፓላኡአን
language-name-pcm = የናይጄሪያ ፒጂን
language-name-pl = ፖሊሽኛ
language-name-prg = ፐሩሳንኛ
language-name-ps = ፓሽቶኛ
language-name-pt = ፖርቹጋልኛ
language-name-pt_BR = የብራዚል ፖርቹጋልኛ
language-name-pt_PT = የአውሮፓ ፖርቹጋልኛ
language-name-qu = ኵቿኛ
language-name-quc = ኪቼ
language-name-qug = ቺምቦራዞ ሃይላንድ ኩቹዋ
language-name-rap = ራፓኑኢ
language-name-rar = ራሮቶንጋ
language-name-rm = ሮማንሽ
language-name-rn = ሩንዲኛ
language-name-ro = ሮማኒያን
language-name-ro_MD = ሞልዳቪያንኛ
language-name-rof = ሮምቦ
language-name-root = ሩት
language-name-ru = ራሽያኛ
language-name-rup = አሮማንያን
language-name-rw = ኪንያርዋንድኛ
language-name-rwk = ርዋ
language-name-sa = ሳንስክሪትኛ
language-name-sad = ሳንዳዌ
language-name-sah = ሳክሃ
language-name-saq = ሳምቡሩ
language-name-sat = ሳንታሊ
language-name-sba = ንጋምባይ
language-name-sbp = ሳንጉ
language-name-sc = ሳርዲንያንኛ
language-name-scn = ሲሲሊያንኛ
language-name-sco = ስኮትስ
language-name-sd = ሲንድሂኛ
language-name-sdh = ደቡባዊ ኩርዲሽ
language-name-se = ሰሜናዊ ሳሚ
language-name-seh = ሴና
language-name-ses = ኮይራቦሮ ሴኒ
language-name-sg = ሳንጎኛ
language-name-sh = ሰርቦ-ክሮኤሽያኛ
language-name-shi = ታቼልሂት
language-name-shn = ሻን
language-name-shu = ቻዲያን ዓረብኛ
language-name-si = ሲንሃልኛ
language-name-sid = ሲዳምኛ
language-name-sk = ስሎቫክኛ
language-name-sl = ስሎቪኛ
language-name-sm = ሳሞአኛ
language-name-sma = ደቡባዊ ሳሚ
language-name-smj = ሉሌ ሳሚ
language-name-smn = ኢናሪ ሳሚ
language-name-sms = ስኮልት ሳሚ
language-name-sn = ሾናኛ
language-name-snk = ሶኒንኬ
language-name-so = ሱማልኛ
language-name-sq = አልባንያንኛ
language-name-sr = ሰርቢኛ
language-name-srn = ስራናን ቶንጎ
language-name-ss = ስዋቲኛ
language-name-ssy = ሳሆኛ
language-name-st = ደቡባዊ ሶቶ
language-name-su = ሱዳንኛ
language-name-suk = ሱኩማ
language-name-sv = ስዊድንኛ
language-name-sw = ስዋሂሊኛ
language-name-sw_CD = ኮንጎ ስዋሂሊ
language-name-swb = ኮሞሪያን
language-name-syc = ክላሲክ ኔይራ
language-name-syr = ሲሪያክ
language-name-ta = ታሚልኛ
language-name-te = ተሉጉኛ
language-name-tem = ቲምኔ
language-name-teo = ቴሶ
language-name-tet = ቴተም
language-name-tg = ታጂኪኛ
language-name-th = ታይኛ
language-name-ti = ትግርኛ
language-name-tig = ትግረ
language-name-tk = ቱርክሜንኛ
language-name-tl = ታጋሎገኛ
language-name-tlh = ክሊንጎንኛ
language-name-tn = ጽዋናዊኛ
language-name-to = ቶንጋኛ
language-name-tpi = ቶክ ፒሲን
language-name-tr = ቱርክኛ
language-name-trv = ታሮኮ
language-name-ts = ጾንጋኛ
language-name-tt = ታታርኛ
language-name-tum = ቱምቡካ
language-name-tvl = ቱቫሉ
language-name-tw = ትዊኛ
language-name-twq = ታሳዋቅ
language-name-ty = ታሂታንኛ
language-name-tyv = ቱቪንያንኛ
language-name-tzm = መካከለኛ አትላስ ታማዚግት
language-name-udm = ኡድሙርት
language-name-ug = ኡዊግሁርኛ
language-name-uk = ዩክሬንኛ
language-name-umb = ኡምቡንዱ
language-name-und = ያልታወቀ ቋንቋ
language-name-ur = ኡርዱኛ
language-name-uz = ኡዝቤክኛ
language-name-vai = ቫይ
language-name-ve = ቬንዳ
language-name-vi = ቪየትናምኛ
language-name-vo = ቮላፑክኛ
language-name-vun = ቩንጆ
language-name-wa = ዋሎን
language-name-wae = ዋልሰር
language-name-wal = ወላይትኛ
language-name-war = ዋራይ
language-name-wbp = ዋርልፒሪ
language-name-wo = ዎሎፍኛ
language-name-wuu = ዉ ቻይንኛ
language-name-xal = ካልማይክ
language-name-xh = ዞሳኛ
language-name-xog = ሶጋ
language-name-yav = ያንግቤንኛ
language-name-ybb = የምባ
language-name-yi = ይዲሽኛ
language-name-yo = ዮሩባዊኛ
language-name-yue = ካንቶኒዝ
language-name-za = ዡዋንግኛ
language-name-zbl = ብሊስይምቦልስ
language-name-zgh = መደበኛ የሞሮኮ ታማዚግት
language-name-zh = ቻይንኛ
language-name-zh_Hans = ቀለል ያለ ቻይንኛ
language-name-zh_Hant = ባህላዊ ቻይንኛ
language-name-zu = ዙሉኛ
language-name-zun = ዙኒ
language-name-zxx = ቋንቋዊ ይዘት አይደለም
language-name-zza = ዛዛ
