language-name-aa = աֆարերեն
language-name-ab = աբխազերեն
language-name-ace = աչեհերեն
language-name-ach = աչոլի
language-name-ada = ադանգմերեն
language-name-ady = ադիղերեն
language-name-aeb = թունիսական արաբերեն
language-name-af = աֆրիկաանս
language-name-agq = աղեմ
language-name-ain = այներեն
language-name-ak = աքան
language-name-akk = աքքադերեն
language-name-ale = ալեութերեն
language-name-alt = հարավային ալթայերեն
language-name-am = ամհարերեն
language-name-an = արագոներեն
language-name-ang = հին անգլերեն
language-name-anp = անգիկա
language-name-ar = արաբերեն
language-name-ar_001 = արդի ընդհանուր արաբերեն
language-name-arc = արամեերեն
language-name-arn = մապուչի
language-name-arp = արապահո
language-name-arq = ալժիրական արաբերեն
language-name-arz = եգիպտական արաբերեն
language-name-as = ասամերեն
language-name-asa = ասու
language-name-ase = ամերիկյան ժեստերի լեզու
language-name-ast = աստուրերեն
language-name-av = ավարերեն
language-name-awa = ավադհի
language-name-ay = այմարա
language-name-az = ադրբեջաներեն
language-name-ba = բաշկիրերեն
language-name-ban = բալիերեն
language-name-bas = բասաա
language-name-be = բելառուսերեն
language-name-bem = բեմբա
language-name-bez = բենա
language-name-bg = բուլղարերեն
language-name-bgn = արևմտաբելուջիերեն
language-name-bho = բհոպուրի
language-name-bi = բիսլամա
language-name-bin = բինի
language-name-bla = սիկսիկա
language-name-bm = բամբարա
language-name-bn = բենգալերեն
language-name-bo = տիբեթերեն
language-name-br = բրետոներեն
language-name-brx = բոդո
language-name-bs = բոսնիերեն
language-name-bss = աքուզ
language-name-bug = բուգիերեն
language-name-byn = բիլին
language-name-ca = կատալաներեն
language-name-ce = չեչեներեն
language-name-ceb = սեբուերեն
language-name-cgg = չիգա
language-name-ch = չամոռո
language-name-chk = տրուկերեն
language-name-chm = մարի
language-name-cho = չոկտո
language-name-chr = չերոկի
language-name-chy = շայեն
language-name-ckb = սորանի քրդերեն
language-name-co = կորսիկերեն
language-name-cop = ղպտերեն
language-name-crh = ղրիմյան թուրքերեն
language-name-crs = սեյշելյան խառնակերտ ֆրանսերեն
language-name-cs = չեխերեն
language-name-cu = եկեղեցական սլավոներեն
language-name-cv = չուվաշերեն
language-name-cy = ուելսերեն
language-name-da = դանիերեն
language-name-dak = դակոտա
language-name-dar = դարգիներեն
language-name-dav = թաիթա
language-name-de = գերմաներեն
language-name-de_AT = ավստրիական գերմաներեն
language-name-de_CH = շվեյցարական վերին գերմաներեն
language-name-dgr = դոգրիբ
language-name-dje = զարմա
language-name-dsb = ստորին սորբերեն
language-name-dua = դուալա
language-name-dv = մալդիվերեն
language-name-dyo = ջոլա-ֆոնյի
language-name-dz = ջոնգքհա
language-name-dzg = դազագա
language-name-ebu = էմբու
language-name-ee = էվե
language-name-efi = էֆիկ
language-name-egy = հին եգիպտերեն
language-name-eka = էկաջուկ
language-name-el = հունարեն
language-name-en = անգլերեն
language-name-en_AU = ավստրալիական անգլերեն
language-name-en_CA = կանադական անգլերեն
language-name-en_GB = բրիտանական անգլերեն
language-name-en_US = ամերիկյան անգլերեն
language-name-eo = էսպերանտո
language-name-es = իսպաներեն
language-name-es_419 = լատինամերիկյան իսպաներեն
language-name-es_ES = եվրոպական իսպաներեն
language-name-es_MX = մեքսիկական իսպաներեն
language-name-et = էստոներեն
language-name-eu = բասկերեն
language-name-ewo = էվոնդո
language-name-fa = պարսկերեն
language-name-ff = ֆուլահ
language-name-fi = ֆիններեն
language-name-fil = ֆիլիպիներեն
language-name-fit = տորնադելեն ֆիններեն
language-name-fj = ֆիջիերեն
language-name-fo = ֆարյորերեն
language-name-fon = ֆոն
language-name-fr = ֆրանսերեն
language-name-fr_CA = կանադական ֆրանսերեն
language-name-fr_CH = շվեյցարական ֆրանսերեն
language-name-fro = հին ֆրանսերեն
language-name-frs = արևելաֆրիզերեն
language-name-fur = ֆրիուլիերեն
language-name-fy = արևմտաֆրիզերեն
language-name-ga = իռլանդերեն
language-name-gaa = գայերեն
language-name-gag = գագաուզերեն
language-name-gbz = զրադաշտական դարի
language-name-gd = շոտլանդական գաելերեն
language-name-gez = գեեզ
language-name-gil = կիրիբատի
language-name-gl = գալիսերեն
language-name-gn = գուարանի
language-name-goh = հին վերին գերմաներեն
language-name-gor = գորոնտալո
language-name-got = գոթերեն
language-name-grc = հին հունարեն
language-name-gsw = շվեյցարական գերմաներեն
language-name-gu = գուջարաթի
language-name-guc = վայուու
language-name-guz = գուսի
language-name-gv = մեներեն
language-name-gwi = գվիչին
language-name-ha = հաուսա
language-name-haw = հավայիերեն
language-name-he = եբրայերեն
language-name-hi = հինդի
language-name-hil = հիլիգայնոն
language-name-hmn = հմոնգ
language-name-hr = խորվաթերեն
language-name-hsb = վերին սորբերեն
language-name-hsn = սյան չինարեն
language-name-ht = խառնակերտ հայիթերեն
language-name-hu = հունգարերեն
language-name-hup = հուպա
language-name-hy = հայերեն
language-name-hz = հերերո
language-name-ia = ինտերլինգուա
language-name-iba = իբաներեն
language-name-ibb = իբիբիո
language-name-id = ինդոնեզերեն
language-name-ie = ինտերլինգուե
language-name-ig = իգբո
language-name-ii = սիչուան
language-name-ilo = իլոկերեն
language-name-inh = ինգուշերեն
language-name-io = իդո
language-name-is = իսլանդերեն
language-name-it = իտալերեն
language-name-iu = ինուկտիտուտ
language-name-ja = ճապոներեն
language-name-jbo = լոժբան
language-name-jgo = նգոմբա
language-name-jmc = մաշամե
language-name-jv = ճավայերեն
language-name-ka = վրացերեն
language-name-kab = կաբիլերեն
language-name-kac = կաչիներեն
language-name-kaj = ջյու
language-name-kam = կամբա
language-name-kbd = կաբարդերեն
language-name-kcg = տիապ
language-name-kde = մակոնդե
language-name-kea = կաբուվերդերեն
language-name-kfo = կորո
language-name-kha = քասիերեն
language-name-khq = կոյրա չինի
language-name-ki = կիկույու
language-name-kj = կուանյամա
language-name-kk = ղազախերեն
language-name-kkj = կակո
language-name-kl = կալաալիսուտ
language-name-kln = կալենջին
language-name-km = քմերերեն
language-name-kmb = կիմբունդու
language-name-kn = կաննադա
language-name-ko = կորեերեն
language-name-koi = պերմյակ կոմիերեն
language-name-kok = կոնկանի
language-name-kpe = կպելլեերեն
language-name-kr = կանուրի
language-name-krc = կարաչայ-բալկարերեն
language-name-krl = կարելերեն
language-name-kru = կուրուխ
language-name-ks = քաշմիրերեն
language-name-ksb = շամբալա
language-name-ksf = բաֆիա
language-name-ksh = քյոլներեն
language-name-ku = քրդերեն
language-name-kum = կումիկերեն
language-name-kv = կոմիերեն
language-name-kw = կոռներեն
language-name-ky = ղրղզերեն
language-name-la = լատիներեն
language-name-lad = լադինո
language-name-lag = լանգի
language-name-lb = լյուքսեմբուրգերեն
language-name-lez = լեզգիերեն
language-name-lg = գանդա
language-name-li = լիմբուրգերեն
language-name-lkt = լակոտա
language-name-ln = լինգալա
language-name-lo = լաոսերեն
language-name-loz = լոզի
language-name-lrc = հյուսիսային լուրիերեն
language-name-lt = լիտվերեն
language-name-lu = լուբա-կատանգա
language-name-lua = լուբա-լուլուա
language-name-lun = լունդա
language-name-luo = լուո
language-name-lus = միզո
language-name-luy = լույա
language-name-lv = լատվիերեն
language-name-mad = մադուրերեն
language-name-mag = մագահի
language-name-mai = մայթիլի
language-name-mak = մակասարերեն
language-name-mas = մասաի
language-name-mdf = մոկշայերեն
language-name-men = մենդե
language-name-mer = մերու
language-name-mfe = մորիսյեն
language-name-mg = մալգաշերեն
language-name-mgh = մաքուա-մետտո
language-name-mgo = մետա
language-name-mh = մարշալերեն
language-name-mi = մաորի
language-name-mic = միկմակ
language-name-min = մինանգկաբաու
language-name-mk = մակեդոներեն
language-name-ml = մալայալամ
language-name-mn = մոնղոլերեն
language-name-mni = մանիպուրի
language-name-moh = մոհավք
language-name-mos = մոսսի
language-name-mr = մարաթի
language-name-mrj = արևմտամարիերեն
language-name-ms = մալայերեն
language-name-mt = մալթայերեն
language-name-mua = մունդանգ
language-name-mul = բազմալեզու
language-name-mus = կրիկ
language-name-mwl = միրանդերեն
language-name-my = բիրմայերեն
language-name-myv = էրզյա
language-name-mzn = մազանդարաներեն
language-name-na = նաուրու
language-name-nap = նեապոլերեն
language-name-naq = նամա
language-name-nb = գրքային նորվեգերեն
language-name-nd = հյուսիսային նդեբելե
language-name-nds_NL = ստորին սաքսոներեն
language-name-ne = նեպալերեն
language-name-new = նեվարերեն
language-name-ng = նդոնգա
language-name-nia = նիասերեն
language-name-niu = նիուերեն
language-name-nl = հոլանդերեն
language-name-nl_BE = ֆլամանդերեն
language-name-nmg = կվասիո
language-name-nn = նոր նորվեգերեն
language-name-nnh = նգիեմբուն
language-name-no = նորվեգերեն
language-name-nog = նոգայերեն
language-name-non = հին նորվեգերեն
language-name-nqo = նկո
language-name-nr = հարավային նդեբելե
language-name-nso = հյուսիսային սոթո
language-name-nus = նուեր
language-name-nv = նավախո
language-name-ny = նյանջա
language-name-nyn = նյանկոլե
language-name-oc = օքսիտաներեն
language-name-oj = օջիբվա
language-name-om = օրոմո
language-name-or = օրիյա
language-name-os = օսերեն
language-name-osa = օսեյջ
language-name-ota = օսմաներեն
language-name-pa = փենջաբերեն
language-name-pag = պանգասինաներեն
language-name-pal = պահլավերեն
language-name-pam = պամպանգաերեն
language-name-pap = պապյամենտո
language-name-pau = պալաուերեն
language-name-pcd = պիկարդերեն
language-name-pcm = նիգերյան կրեոլերեն
language-name-pdc = փենսիլվանական գերմաներեն
language-name-pdt = պլատագերմաներեն
language-name-peo = հին պարսկերեն
language-name-pfl = պալատինյան գերմաներեն
language-name-phn = փյունիկերեն
language-name-pi = պալի
language-name-pl = լեհերեն
language-name-pms = պիեմոնտերեն
language-name-pnt = պոնտերեն
language-name-pon = պոնպեերեն
language-name-prg = պրուսերեն
language-name-pro = հին պրովանսերեն
language-name-ps = փուշթու
language-name-pt = պորտուգալերեն
language-name-pt_BR = բրազիլական պորտուգալերեն
language-name-pt_PT = եվրոպական պորտուգալերեն
language-name-qu = կեչուա
language-name-quc = քիչե
language-name-raj = ռաջաստաներեն
language-name-rap = ռապանուի
language-name-rar = ռարոտոնգաներեն
language-name-rgn = ռոմանիոլերեն
language-name-rif = ռիֆերեն
language-name-rm = ռոմանշերեն
language-name-rn = ռունդի
language-name-ro = ռումիներեն
language-name-ro_MD = մոլդովերեն
language-name-rof = ռոմբո
language-name-rom = ռոմաներեն
language-name-root = ռուտերեն
language-name-rtm = ռոտուման
language-name-ru = ռուսերեն
language-name-rue = ռուսիներեն
language-name-rug = ռովիանա
language-name-rup = արոմաներեն
language-name-rw = կինյառուանդա
language-name-rwk = ռվա
language-name-sa = սանսկրիտ
language-name-sad = սանդավե
language-name-sah = յակուտերեն
language-name-saq = սամբուրու
language-name-sat = սանտալի
language-name-sba = նգամբայ
language-name-sbp = սանգու
language-name-sc = սարդիներեն
language-name-scn = սիցիլիերեն
language-name-sco = շոտլանդերեն
language-name-sd = սինդհի
language-name-sdh = հարավային քրդերեն
language-name-se = հյուսիսային սաամի
language-name-seh = սենա
language-name-ses = կոյրաբորո սեննի
language-name-sg = սանգո
language-name-sga = հին իռլանդերեն
language-name-sh = սերբա-խորվաթերեն
language-name-shi = տաշելհիթ
language-name-shn = շաներեն
language-name-si = սինհալերեն
language-name-sk = սլովակերեն
language-name-sl = սլովեներեն
language-name-sm = սամոաերեն
language-name-sma = հարավային սաամի
language-name-smj = լուլե սաամի
language-name-smn = ինարի սաամի
language-name-sms = սկոլտ սաամի
language-name-sn = շոնա
language-name-snk = սոնինկե
language-name-so = սոմալիերեն
language-name-sq = ալբաներեն
language-name-sr = սերբերեն
language-name-srn = սրանան տոնգո
language-name-ss = սվազերեն
language-name-ssy = սահոերեն
language-name-st = հարավային սոթո
language-name-su = սունդաներեն
language-name-suk = սուկումա
language-name-sv = շվեդերեն
language-name-sw = սուահիլի
language-name-sw_CD = կոնգոյի սուահիլի
language-name-swb = կոմորերեն
language-name-syr = ասորերեն
language-name-ta = թամիլերեն
language-name-tcy = տուլու
language-name-te = թելուգու
language-name-tem = տեմնե
language-name-teo = տեսո
language-name-ter = տերենո
language-name-tet = տետում
language-name-tg = տաջիկերեն
language-name-th = թայերեն
language-name-ti = տիգրինյա
language-name-tig = տիգրե
language-name-tiv = տիվերեն
language-name-tk = թուրքմեներեն
language-name-tkl = տոկելաու
language-name-tkr = ցախուր
language-name-tl = տագալերեն
language-name-tlh = կլինգոն
language-name-tli = տլինգիտ
language-name-tly = թալիշերեն
language-name-tmh = տամաշեկ
language-name-tn = ցվանա
language-name-to = տոնգերեն
language-name-tpi = տոկ փիսին
language-name-tr = թուրքերեն
language-name-tru = տուրոյո
language-name-trv = տարոկո
language-name-ts = ցոնգա
language-name-tsd = ցակոներեն
language-name-tsi = ցիմշյան
language-name-tt = թաթարերեն
language-name-tum = տումբուկա
language-name-tvl = թուվալուերեն
language-name-tw = տուի
language-name-twq = տասավաք
language-name-ty = թաիտերեն
language-name-tyv = տուվերեն
language-name-tzm = կենտրոնատլասյան թամազիղտ
language-name-udm = ուդմուրտերեն
language-name-ug = ույղուրերեն
language-name-uga = ուգարիտերեն
language-name-uk = ուկրաիներեն
language-name-umb = ումբունդու
language-name-und = անհայտ լեզու
language-name-ur = ուրդու
language-name-uz = ուզբեկերեն
language-name-vai = վաի
language-name-ve = վենդա
language-name-vec = վենետերեն
language-name-vep = վեպսերեն
language-name-vi = վիետնամերեն
language-name-vls = արևմտաֆլամանդերեն
language-name-vo = վոլապյուկ
language-name-vot = վոդերեն
language-name-vro = վորո
language-name-vun = վունջո
language-name-wa = վալոներեն
language-name-wae = վալսերեն
language-name-wal = վոլայտա
language-name-war = վարայերեն
language-name-was = վաշո
language-name-wbp = վարլպիրի
language-name-wo = վոլոֆ
language-name-wuu = վու չինարեն
language-name-xal = կալմիկերեն
language-name-xh = քոսա
language-name-xog = սոգա
language-name-yao = յաո
language-name-yap = յափերեն
language-name-yav = յանգբեն
language-name-ybb = եմբա
language-name-yi = իդիշ
language-name-yo = յորուբա
language-name-yue = կանտոներեն
language-name-za = ժուանգ
language-name-zap = սապոտեկերեն
language-name-zea = զեյլանդերեն
language-name-zen = զենագա
language-name-zgh = ընդհանուր մարոկյան թամազիղտ
language-name-zh = չինարեն
language-name-zh_Hans = պարզեցված չինարեն
language-name-zh_Hant = ավանդական չինարեն
language-name-zu = զուլուերեն
language-name-zun = զունիերեն
language-name-zxx = առանց լեզվային բովանդակության
language-name-zza = զազաերեն
