language-name-aa = isi-Afar
language-name-ab = isi-Abkhazian
language-name-ace = isi-Achinese
language-name-ach = isi-Acoli
language-name-ada = isi-Adangme
language-name-ady = isi-Adyghe
language-name-af = i-Afrikaans
language-name-agq = isi-Aghem
language-name-ain = isi-Ainu
language-name-ak = isi-Akan
language-name-ale = isi-Aleut
language-name-alt = i-Southern Altai
language-name-am = isi-Amharic
language-name-an = isi-Aragonese
language-name-anp = isi-Angika
language-name-ar = isi-Arabic
language-name-ar_001 = isi-Arabic esivamile sesimanje
language-name-arn = isi-Mapuche
language-name-arp = isi-Arapaho
language-name-as = isi-Assamese
language-name-asa = isi-Asu
language-name-ast = isi-Asturian
language-name-av = isi-Avaric
language-name-awa = isi-Awadhi
language-name-ay = isi-Aymara
language-name-az = isi-Azerbaijani
language-name-ba = isi-Bashkir
language-name-ban = isi-Balinese
language-name-bas = isi-Basaa
language-name-be = isi-Belarusian
language-name-bem = isi-Bemba
language-name-bez = isi-Bena
language-name-bg = isi-Bulgari
language-name-bgn = isi-Western Balochi
language-name-bho = isi-Bhojpuri
language-name-bi = i-Bislama
language-name-bin = i-Bini
language-name-bla = i-Siksika
language-name-bm = isi-Bambara
language-name-bn = isi-Bengali
language-name-bo = isi-Tibetan
language-name-br = isi-Breton
language-name-brx = isi-Bodo
language-name-bs = isi-Bosnian
language-name-bug = isi-Buginese
language-name-byn = i-Blin
language-name-ca = isi-Catalan
language-name-ce = isi-Chechen
language-name-ceb = isi-Cebuano
language-name-cgg = isi-Chiga
language-name-ch = isi-Chamorro
language-name-chk = isi-Chuukese
language-name-chm = isi-Mari
language-name-cho = isi-Choctaw
language-name-chr = isi-Cherokee
language-name-chy = isi-Cheyenne
language-name-ckb = isi-Central Kurdish
language-name-co = isi-Corsican
language-name-crs = i-Seselwa Creole French
language-name-cs = isi-Czech
language-name-cu = isi-Church Slavic
language-name-cv = isi-Chuvash
language-name-cy = isi-Welsh
language-name-da = isi-Danish
language-name-dak = isi-Dakota
language-name-dar = isi-Dargwa
language-name-dav = isi-Taita
language-name-de = isi-German
language-name-de_AT = isi-Austrian German
language-name-de_CH = i-Swiss High German
language-name-dgr = isi-Dogrib
language-name-dje = isi-Zarma
language-name-dsb = isi-Lower Sorbian
language-name-dua = isi-Duala
language-name-dv = isi-Divehi
language-name-dyo = isi-Jola-Fonyi
language-name-dz = isi-Dzongkha
language-name-dzg = isi-Dazaga
language-name-ebu = isi-Embu
language-name-ee = isi-Ewe
language-name-efi = isi-Efik
language-name-eka = isi-Ekajuk
language-name-el = isi-Greek
language-name-en = i-English
language-name-en_AU = isi-Austrillian English
language-name-en_CA = i-Canadian English
language-name-en_GB = i-British English
language-name-en_US = i-American English
language-name-eo = isi-Esperanto
language-name-es = isi-Spanish
language-name-es_419 = isi-Latin American Spanish
language-name-es_ES = i-European Spanish
language-name-es_MX = i-Mexican Spanish
language-name-et = isi-Estonia
language-name-eu = isi-Basque
language-name-ewo = isi-Ewondo
language-name-fa = isi-Persian
language-name-ff = isi-Fulah
language-name-fi = isi-Finnish
language-name-fil = isi-Filipino
language-name-fj = isi-Fijian
language-name-fo = isi-Faroese
language-name-fon = isi-Fon
language-name-fr = isi-French
language-name-fr_CA = i-Canadian French
language-name-fr_CH = i-Swiss French
language-name-fur = isi-Friulian
language-name-fy = isi-Western Frisian
language-name-ga = isi-Irish
language-name-gaa = isi-Ga
language-name-gag = isi-Gagauz
language-name-gan = isi-Gan Chinese
language-name-gd = i-Scottish Gaelic
language-name-gez = isi-Geez
language-name-gil = isi-Gilbertese
language-name-gl = isi-Galicia
language-name-gn = isi-Guarani
language-name-gor = isi-Gorontalo
language-name-gsw = isi-Swiss German
language-name-gu = isi-Gujarati
language-name-guz = isi-Gusli
language-name-gv = isi-Manx
language-name-gwi = isi-Gwichʼin
language-name-ha = isi-Hausa
language-name-hak = isi-Hakka Chinese
language-name-haw = isi-Hawaiian
language-name-he = isi-Hebrew
language-name-hi = isi-Hindi
language-name-hil = isi-Hiligaynon
language-name-hmn = isi-Hmong
language-name-hr = isi-Croatian
language-name-hsb = isi-Upper Sorbian
language-name-hsn = isi-Xiang Chinese
language-name-ht = isi-Haitian
language-name-hu = isi-Hungarian
language-name-hup = isi-Hupa
language-name-hy = isi-Armenia
language-name-hz = isi-Herero
language-name-ia = izilimi ezihlangene
language-name-iba = isi-Iban
language-name-ibb = isi-Ibibio
language-name-id = isi-Indonesian
language-name-ie = izimili
language-name-ig = isi-Igbo
language-name-ii = isi-Sichuan Yi
language-name-ilo = isi-Iloko
language-name-inh = isi-Ingush
language-name-io = isi-Ido
language-name-is = isi-Icelandic
language-name-it = isi-Italian
language-name-iu = isi-Inuktitut
language-name-ja = isi-Japanese
language-name-jbo = isi-Lojban
language-name-jgo = isi-Ngomba
language-name-jmc = isi-Machame
language-name-jv = isi-Javanese
language-name-ka = isi-Georgian
language-name-kab = isi-Kabyle
language-name-kac = isi-Kachin
language-name-kaj = isi-Jju
language-name-kam = isi-Kamba
language-name-kbd = isi-Kabardian
language-name-kcg = isi-Tyap
language-name-kde = isi-Makonde
language-name-kea = isi-Kabuverdianu
language-name-kfo = isi-Koro
language-name-kg = isi-Kongo
language-name-kha = isi-Khasi
language-name-khq = isi-Koyra Chiini
language-name-ki = isi-Kikuyu
language-name-kj = isi-Kuanyama
language-name-kk = isi-Kazakh
language-name-kkj = isi-Kako
language-name-kl = isi-Kalaallisut
language-name-kln = isi-Kalenjin
language-name-km = isi-Khmer
language-name-kmb = isi-Kimbundu
language-name-kn = isi-Kannada
language-name-ko = isi-Korean
language-name-koi = isi-Komi-Permyak
language-name-kok = isi-Konkani
language-name-kpe = isi-Kpelle
language-name-kr = isi-Kanuri
language-name-krc = isi-Karachay-Balkar
language-name-krl = isi-Karelian
language-name-kru = isi-Kurukh
language-name-ks = isi-Kashmiri
language-name-ksb = isiShambala
language-name-ksf = isi-Bafia
language-name-ksh = isi-Colognian
language-name-ku = isi-Kurdish
language-name-kum = isi-Kumyk
language-name-kv = isi-Komi
language-name-kw = isi-Cornish
language-name-ky = isi-Kyrgyz
language-name-la = isi-Latin
language-name-lad = isi-Ladino
language-name-lag = isi-Langi
language-name-lb = isi-Luxembourgish
language-name-lez = isi-Lezghian
language-name-lg = isi-Ganda
language-name-li = isi-Limburgish
language-name-lkt = isi-Lakota
language-name-ln = isi-Lingala
language-name-lo = i-Lao
language-name-loz = isi-Lozi
language-name-lrc = isi-Northern Luri
language-name-lt = isi-Lithuanian
language-name-lu = isi-Luba-Katanga
language-name-lua = isi-Luba-Lulua
language-name-lun = isi-Lunda
language-name-luo = isi-Luo
language-name-lus = isi-Mizo
language-name-luy = isi-Luyia
language-name-lv = isi-Latvian
language-name-mad = isi-Madurese
language-name-mag = isi-Magahi
language-name-mai = isi-Maithili
language-name-mak = isi-Makasar
language-name-mas = isi-Masai
language-name-mdf = isi-Moksha
language-name-men = isi-Mende
language-name-mer = isi-Meru
language-name-mfe = isi-Morisyen
language-name-mg = isi-Malagasy
language-name-mgh = isi-Makhuwa-Meetto
language-name-mgo = isi-Meta’
language-name-mh = isi-Marshallese
language-name-mi = isi-Maori
language-name-mic = isi-Micmac
language-name-min = isi-Minangkabau
language-name-mk = isi-Macedonian
language-name-ml = isi-Malayalam
language-name-mn = isi-Mongolian
language-name-mni = isi-Manipuri
language-name-moh = isi-Mohawk
language-name-mos = isi-Mossi
language-name-mr = isi-Marathi
language-name-ms = isi-Malay
language-name-mt = isi-Maltese
language-name-mua = isi-Mundang
language-name-mul = izilimi ezehlukene
language-name-mus = isi-Creek
language-name-mwl = isi-Mirandese
language-name-my = isi-Burmese
language-name-myv = isi-Erzya
language-name-mzn = isi-Mazanderani
language-name-na = isi-Nauru
language-name-nan = isi-Min Nan Chinese
language-name-nap = isi-Neapolitan
language-name-naq = isi-Nama
language-name-nb = isi-Norwegian Bokmål
language-name-nd = isi-North Ndebele
language-name-nds = isi-Low German
language-name-nds_NL = isi-Low Saxon
language-name-ne = isi-Nepali
language-name-new = isi-Newari
language-name-ng = isi-Ndonga
language-name-nia = isi-Nias
language-name-niu = isi-Niuean
language-name-nl = isi-Dutch
language-name-nl_BE = isi-Flemish
language-name-nmg = isi-Kwasio
language-name-nn = i-Norwegian Nynorsk
language-name-nnh = isi-Ngiemboon
language-name-no = isi-Norwegian
language-name-nog = isi-Nogai
language-name-nqo = isi-N’Ko
language-name-nr = i-South Ndebele
language-name-nso = isi-Northern Sotho
language-name-nus = isi-Nuer
language-name-nv = isi-Navajo
language-name-ny = isi-Nyanja
language-name-nyn = isi-Nyankole
language-name-oc = isi-Occitan
language-name-om = i-Oromo
language-name-or = isi-Odia
language-name-os = isi-Ossetic
language-name-pa = isi-Punjabi
language-name-pag = isi-Pangasinan
language-name-pam = isi-Pampanga
language-name-pap = isi-Papiamento
language-name-pau = isi-Palauan
language-name-pcm = isi-Nigerian Pidgin
language-name-pl = isi-Polish
language-name-prg = isi-Prussian
language-name-ps = isi-Pashto
language-name-pt = isi-Portuguese
language-name-pt_BR = isi-Brazillian Portuguese
language-name-pt_PT = isi-European Portuguese
language-name-qu = isi-Quechua
language-name-quc = isi-Kʼicheʼ
language-name-rap = i-Rapanui
language-name-rar = i-Rarotongan
language-name-rm = isi-Romansh
language-name-rn = isi-Rundi
language-name-ro = isi-Romanian
language-name-ro_MD = isi-Moldavian
language-name-rof = isi-Rombo
language-name-root = i-Root
language-name-ru = isi-Russian
language-name-rup = isi-Aromanian
language-name-rw = isi-Kinyarwanda
language-name-rwk = isi-Rwa
language-name-sa = isi-Sanskrit
language-name-sad = i-Sandawe
language-name-sah = i-Sakha
language-name-saq = isi-Samburu
language-name-sat = i-Santali
language-name-sba = isi-Ngambay
language-name-sbp = isi-Sangu
language-name-sc = i-Sardinian
language-name-scn = i-Sicilian
language-name-sco = i-Scots
language-name-sd = isi-Sindhi
language-name-sdh = i-Southern Kurdish
language-name-se = isi-Northern Sami
language-name-seh = isi-Sena
language-name-ses = isi-Koyraboro Senni
language-name-sg = isi-Sango
language-name-sh = isi-Serbo-Croatian
language-name-shi = isi-Tachelhit
language-name-shn = i-Shan
language-name-si = i-Sinhala
language-name-sk = isi-Slovak
language-name-sl = isi-Slovenian
language-name-sm = isi-Samoan
language-name-sma = i-Southern Sami
language-name-smj = isi-Lule Sami
language-name-smn = isi-Inari Sami
language-name-sms = isi-Skolt Sami
language-name-sn = isiShona
language-name-snk = i-Soninke
language-name-so = isi-Somali
language-name-sq = isi-Albania
language-name-sr = isi-Serbian
language-name-srn = i-Sranan Tongo
language-name-ss = isiSwati
language-name-ssy = i-Saho
language-name-st = isiSuthu
language-name-su = isi-Sundanese
language-name-suk = i-Sukuma
language-name-sv = isi-Swedish
language-name-sw = isiSwahili
language-name-sw_CD = isi-Congo Swahili
language-name-swb = isi-Comorian
language-name-syr = i-Syriac
language-name-ta = isi-Tamil
language-name-te = isi-Telugu
language-name-tem = isi-Timne
language-name-teo = isi-Teso
language-name-tet = isi-Tetum
language-name-tg = isi-Tajik
language-name-th = isi-Thai
language-name-ti = isi-Tigrinya
language-name-tig = isi-Tigre
language-name-tk = isi-Turkmen
language-name-tlh = isi-Klingon
language-name-tn = isi-Tswana
language-name-to = isi-Tongan
language-name-tpi = isi-Tok Pisin
language-name-tr = isi-Turkish
language-name-trv = isi-Taroko
language-name-ts = isi-Tsonga
language-name-tt = isi-Tatar
language-name-tum = isi-Tumbuka
language-name-tvl = isi-Tuvalu
language-name-tw = isi-Twi
language-name-twq = isi-Tasawaq
language-name-ty = isi-Tahitian
language-name-tyv = isi-Tuvinian
language-name-tzm = isi-Central Atlas Tamazight
language-name-udm = isi-Udmurt
language-name-ug = isi-Uighur
language-name-uk = isi-Ukrainian
language-name-umb = isi-Umbundu
language-name-und = ulimi olungaziwa
language-name-ur = isi-Urdu
language-name-uz = isi-Uzbek
language-name-vai = isi-Vai
language-name-ve = isi-Venda
language-name-vi = isi-Vietnamese
language-name-vo = isi-Volapük
language-name-vun = isiVunjo
language-name-wa = isi-Walloon
language-name-wae = isi-Walser
language-name-wal = isi-Wolaytta
language-name-war = isi-Waray
language-name-wbp = isi-Warlpiri
language-name-wo = isi-Wolof
language-name-wuu = isi-Wu Chinese
language-name-xal = isi-Kalmyk
language-name-xh = isiXhosa
language-name-xog = isi-Soga
language-name-yav = isi-Yangben
language-name-ybb = isi-Yemba
language-name-yi = isi-Yiddish
language-name-yo = isi-Yoruba
language-name-yue = isi-Cantonese
language-name-zgh = isi-Moroccan Tamazight esivamile
language-name-zh = isi-Chinese
language-name-zu = isiZulu
language-name-zun = isi-Zuni
language-name-zxx = akukho okuqukethwe kolimi
language-name-zza = isi-Zaza
