language-name-aa = ଅଫାର୍
language-name-ab = ଆବ୍ଖାଜିଆନ୍
language-name-ace = ଆଚାଇନୀଜ୍
language-name-ach = ଆକୋଲି
language-name-ada = ଆଦାଙ୍ଗେମ୍
language-name-ady = ଅଦ୍ୟଘେ
language-name-ae = ଅବେସ୍ତନ
language-name-af = ଆଫ୍ରିକୀୟ
language-name-afh = ଆଫ୍ରିହିଲି
language-name-agq = ଆଘେମ
language-name-ain = ଆଇନୁ
language-name-ak = ଅକନ୍
language-name-akk = ଆକାଡିଆନ୍
language-name-ale = ଆଲେଇଟୁ
language-name-alt = ଦକ୍ଷିଣ ଆଲ୍ଟାଇ
language-name-am = ଆମହାରକି
language-name-an = ଆର୍ଗୋନୀ
language-name-ang = ପୁରୁଣା ଇଁରାଜୀ
language-name-anp = ଅଁଗୀକା
language-name-ar = ଆରବିକ୍
language-name-ar_001 = ଆଧୁନିକ ମାନାଙ୍କ ଆରବୀୟ
language-name-arc = ଆରାମାଇକ୍
language-name-arn = ମାପୁଚେ
language-name-arp = ଆରାପାହୋ
language-name-arw = ଆରୱକ
language-name-as = ଆସାମୀୟ
language-name-asa = ଆସୁ
language-name-ast = ଆଷ୍ଟୁରିଆନ୍
language-name-av = ଆଭାରିକ୍
language-name-awa = ଆୱାଧି
language-name-ay = ଆୟମାରା
language-name-az = ଆଜେରବାଇଜାନି
language-name-ba = ବାଶକିର୍‌
language-name-bal = ବାଲୁଚି
language-name-ban = ବାଲିନୀଜ୍
language-name-bas = ବାସା
language-name-be = ବେଲାରୁଷିଆନ୍
language-name-bej = ବେଜା
language-name-bem = ବେମ୍ବା
language-name-bez = ବେନା
language-name-bg = ବୁଲଗେରିଆନ୍
language-name-bho = ଭୋଜପୁରୀ
language-name-bi = ବିସଲାମା
language-name-bik = ବିକୋଲ୍
language-name-bin = ବିନି
language-name-bla = ସିକସିକା
language-name-bm = ବାମ୍ବାରା
language-name-bn = ବଙ୍ଗାଳୀ
language-name-bo = ତିବ୍ବତୀୟ
language-name-br = ବ୍ରେଟନ୍
language-name-bra = ବ୍ରାଜ୍
language-name-brx = ବୋଡୋ
language-name-bs = କାଟଲାନ୍
language-name-bua = ବୁରିଆଟ୍
language-name-bug = ବୁଗୀନୀଜ୍
language-name-byn = ବ୍ଲିନ୍
language-name-ca = କାଟାଲାନ୍
language-name-cad = କାଡୋ
language-name-car = କାରିବ୍
language-name-cch = ଆତ୍ସମ୍
language-name-ce = ଚେଚନ୍
language-name-ceb = ସୀବୁଆନୋ
language-name-cgg = ଚିଗା
language-name-ch = ଚାମୋରୋ
language-name-chb = ଚିବ୍ଚା
language-name-chg = ଛଗତାଇ
language-name-chk = ଚୁକୀସେ
language-name-chm = ମାରୀ
language-name-chn = ଚିନୁକ୍ ଜାରଗାଁନ୍
language-name-cho = ଚୋଟୱା
language-name-chp = ଚିପେୱାନ୍
language-name-chr = ଚେରୋକୀ
language-name-chy = ଚେଚେନା
language-name-ckb = କେନ୍ଦ୍ରୀୟ କୁରଡିସ୍
language-name-co = କୋର୍ସିକାନ୍
language-name-cop = କପ୍ଟିକ୍
language-name-cr = କ୍ରୀ
language-name-crh = କ୍ରୀମିନ୍ ତୁର୍କୀସ୍
language-name-crs = ସେସେଲୱା କ୍ରେଓଲେ ଫ୍ରେଞ୍ଚ୍
language-name-cs = ଚେକ୍
language-name-csb = କାଶୁବିଆନ୍
language-name-cu = ଚର୍ଚ୍ଚ ସ୍ଲାଭିକ୍
language-name-cv = ଚୁଭାଶ୍
language-name-cy = ୱେଲ୍ସ
language-name-da = ଡାନ୍ନିସ୍
language-name-dak = ଡାକୋଟା
language-name-dar = ଡାରାଗ୍ୱା
language-name-dav = ତାଇତି
language-name-de = ଜର୍ମାନ
language-name-de_AT = ଅଷ୍ଟ୍ରିଆନ୍ ଜର୍ମାନ
language-name-de_CH = ସ୍ୱିସ୍‌ ହାଇ ଜର୍ମାନ
language-name-del = ଡେଲାୱେର୍
language-name-den = ସ୍ଲେଭ୍
language-name-dgr = ଡୋଗ୍ରିବ୍
language-name-din = ଦିଙ୍କା
language-name-dje = ଜର୍ମା
language-name-doi = ଡୋଗ୍ରୀ
language-name-dsb = ନିମ୍ନ ସର୍ବିଆନ୍‌
language-name-dua = ଡୁଆନା
language-name-dum = ମଧ୍ୟ ପର୍ତ୍ତୁଗାଲୀ
language-name-dv = ଡିଭେହୀ
language-name-dyo = ଜୋଲା-ଫୋନୟି
language-name-dyu = ଡୁଆଲା
language-name-dz = ଦଡଜୋଙ୍ଗଖା
language-name-dzg = ଡାଜାଗା
language-name-ebu = ଏମ୍ଵୁ
language-name-ee = ଇୱେ
language-name-efi = ଏଫିକ୍
language-name-egy = ପ୍ରାଚୀନ୍ ମିଶିରି
language-name-eka = ଏକାଜୁକ୍
language-name-el = ଗ୍ରୀକ୍
language-name-elx = ଏଲାମାଇଟ୍
language-name-en = ଇଂରାଜୀ
language-name-en_AU = ଅଷ୍ଟ୍ରେଲିୟ ଇଂରାଜୀ
language-name-en_CA = କାନାଡିୟ ଇଂରାଜୀ
language-name-en_GB = ବ୍ରିଟିଶ୍‌ ଇଂରାଜୀ
language-name-en_US = ଆମେରିକୀୟ ଇଂରାଜୀ
language-name-enm = ମଧ୍ୟ ଇଁରାଜୀ
language-name-eo = ଏସ୍ପାରେଣ୍ଟୋ
language-name-es = ସ୍ପେନିୟ
language-name-es_419 = ଲାଟିନ୍‌ ଆମେରିକୀୟ ସ୍ପାନିସ୍‌
language-name-es_ES = ୟୁରୋପୀୟ ସ୍ପାନିସ୍‌
language-name-es_MX = ମେକ୍ସିକାନ ସ୍ପାନିସ୍‌
language-name-et = ଏସ୍ତୋନିଆନ୍
language-name-eu = ବାସ୍କ୍ୱି
language-name-ewo = ଇୱୋଣ୍ଡୋ
language-name-fa = ପର୍ସିଆନ୍
language-name-fan = ଫାଙ୍ଗ
language-name-fat = ଫାଣ୍ଟି
language-name-ff = ଫୁଲାହ
language-name-fi = ଫିନ୍ନିସ୍
language-name-fil = ଫିଲିପିନୋ
language-name-fj = ଫିଜି
language-name-fo = ଫାରୋଏସେ
language-name-fon = ଫନ୍
language-name-fr = ଫରାସୀ
language-name-fr_CA = କାନାଡିୟ ଫ୍ରେଞ୍ଚ
language-name-fr_CH = ସ୍ୱିସ୍ ଫ୍ରେଞ୍ଚ
language-name-frm = ମଧ୍ୟ ଫ୍ରେଞ୍ଚ
language-name-fro = ପୁରୁଣା ଫ୍ରେଞ୍ଚ
language-name-frr = ଉତ୍ତର ଫ୍ରିସିୟାନ୍
language-name-frs = ପୂର୍ବ ଫ୍ରିସିୟାନ୍
language-name-fur = ଫ୍ରିୟୁଲୀୟାନ୍
language-name-fy = ପାଶ୍ଚାତ୍ୟ ଫ୍ରିସିଆନ୍
language-name-ga = ଇରିସ୍
language-name-gaa = ଗା
language-name-gay = ଗାୟୋ
language-name-gba = ଗବାୟା
language-name-gd = ସ୍କଟିସ୍ ଗାଏଲିକ୍
language-name-gez = ଗୀଜ୍
language-name-gil = ଜିବ୍ରାଟୀଜ୍
language-name-gl = ଗାଲସିଆନ୍
language-name-gmh = ମିଡିଲ୍ ହାଇ ଜର୍ମାନ୍
language-name-gn = ଗୁଆରାନୀ
language-name-goh = ପୁରୁଣା ହାଇ ଜର୍ମାନ୍
language-name-gon = ଗୋଣ୍ଡି
language-name-gor = ଗୋରୋଣ୍ଟାଲୋ
language-name-got = ଗୋଥିକ୍
language-name-grb = ଗ୍ରେବୋ
language-name-grc = ପ୍ରାଚୀନ୍ ୟୁନାନୀ
language-name-gsw = ସୁଇସ୍ ଜର୍ମାନ୍
language-name-gu = ଗୁଜୁରାଟୀ
language-name-guz = ଗୁସି
language-name-gv = ମାଁକ୍ସ
language-name-gwi = ଗୱିଚ’ଇନ୍
language-name-ha = ହୌସା
language-name-hai = ହାଇଡା
language-name-haw = ହାୱାଇନ୍
language-name-he = ହେବ୍ର୍ୟୁ
language-name-hi = ହିନ୍ଦୀ
language-name-hil = ହିଲିଗୈନନ୍
language-name-hit = ହିତୀତେ
language-name-hmn = ହଁଙ୍ଗ
language-name-ho = ହିରି ମୋଟୁ
language-name-hr = କ୍ରୋଆଟିଆନ୍
language-name-hsb = ଉପର ସର୍ବିଆନ୍
language-name-ht = ହୈତାୟିନ୍
language-name-hu = ହଙ୍ଗେରୀୟ
language-name-hup = ହୁପା
language-name-hy = ଆର୍ମେନିଆନ୍
language-name-hz = ହେରେରୋ
language-name-ia = ଇର୍ଣ୍ଟଲିଙ୍ଗୁଆ
language-name-iba = ଇବାନ୍
language-name-ibb = ଇବିବିଓ
language-name-id = ଇଣ୍ଡୋନେସୀୟ
language-name-ie = ଇର୍ଣ୍ଟରଲିଙ୍ଗୁଇ
language-name-ig = ଇଗବୋ
language-name-ii = ସିଚୁଆନ୍ ୟୀ
language-name-ik = ଇନୁପିୟାକ୍
language-name-ilo = ଇଲୋକୋ
language-name-inh = ଇଁଙ୍ଗୁଶ୍
language-name-io = ଇଡୋ
language-name-is = ଆଇସଲାଣ୍ଡିକ୍
language-name-it = ଇଟାଲୀୟ
language-name-iu = ଇନୁକଟୁତ୍‌
language-name-ja = ଜାପାନୀ
language-name-jbo = ଲୋଜବାନ୍
language-name-jgo = ନାଗୋମ୍ଵା
language-name-jmc = ମାଚେମେ
language-name-jpr = ଜୁଡେଓ-ପର୍ସିଆନ୍
language-name-jrb = ଜୁଡେଓ-ଆରବୀକ୍
language-name-jv = ଜାଭାନୀଜ୍
language-name-ka = ଜର୍ଜିୟ
language-name-kaa = କାରା-କଲ୍ପକ୍
language-name-kab = କବାଇଲ୍
language-name-kac = କଚିନ୍
language-name-kaj = ଜଜୁ
language-name-kam = କମ୍ବା
language-name-kaw = କାୱି
language-name-kbd = କାବାର୍ଡିଆନ୍
language-name-kcg = ତ୍ୟାପ୍
language-name-kde = ମାକୋଣ୍ଡେ
language-name-kea = କାବୁଭେରଡିଆନୁ
language-name-kfo = କୋରୋ
language-name-kg = କଙ୍ଗୋ
language-name-kha = ଖାସୀ
language-name-kho = ଖୋତାନୀଜ୍
language-name-khq = କୋୟରା ଚିନି
language-name-ki = କୀକୁୟୁ
language-name-kj = କ୍ୱାନ୍ୟାମ୍
language-name-kk = କାଜାକ୍
language-name-kkj = କାକୋ
language-name-kl = କାଲାଲିସୁଟ୍
language-name-kln = କାଲେନଜିନ୍
language-name-km = ଖାମେର୍
language-name-kmb = କିମ୍ବୁଣ୍ଡୁ
language-name-kn = କନ୍ନଡ
language-name-ko = କୋରିଆନ୍
language-name-kok = କୋଙ୍କଣି
language-name-kos = କୋସରୈନ୍
language-name-kpe = କୈପେଲେ
language-name-kr = କନୁରୀ
language-name-krc = କରାଚୟ-ବଲ୍କାର
language-name-krl = କାରେଲିୟାନ୍
language-name-kru = କୁରୁଖ
language-name-ks = କାଶ୍ମିରୀ
language-name-ksb = ଶାମବାଲା
language-name-ksf = ବାଫଲା
language-name-ksh = କୋଲୋବନିୟ
language-name-ku = କୁର୍ଦ୍ଦିଶ୍
language-name-kum = କୁମୀକ୍
language-name-kut = କୁତେନାଉ
language-name-kv = କୋମି
language-name-kw = କୋର୍ନିସ୍
language-name-ky = କୀରଗୀଜ୍
language-name-la = ଲାଟିନ୍
language-name-lad = ଲାଦିନୋ
language-name-lag = ଲାନଗି
language-name-lah = ଲାହାଣ୍ଡା
language-name-lam = ଲାମ୍ବା
language-name-lb = ଲକ୍ସେମବର୍ଗିସ୍
language-name-lez = ଲେଜଗିୟାନ୍
language-name-lg = ଗନ୍ଦା
language-name-li = ଲିମ୍ବୁର୍ଗିସ୍
language-name-lkt = ଲାକୋଟା
language-name-ln = ଲିଙ୍ଗାଲା
language-name-lo = ଲାଓ
language-name-lol = ମଙ୍ଗୋ
language-name-loz = ଲୋଜି
language-name-lrc = ଉତ୍ତର ଲୁରି
language-name-lt = ଲିଥୁଆନିଆନ୍
language-name-lu = ଲ୍ୟୁବା-କାଟାଙ୍ଗା
language-name-lua = ଲୁବା-ଲୁଲୁଆ
language-name-lui = ଲୁଇସେନୋ
language-name-lun = ଲୁଣ୍ଡା
language-name-luo = ଲୁଓ
language-name-lus = ମିଜୋ
language-name-luy = ଲୁୟିଆ
language-name-lv = ଲାଟଭିଆନ୍
language-name-mad = ମାଦୁରୀସ୍
language-name-mag = ମାଗାହୀ
language-name-mai = ମୈଥିଳୀ
language-name-mak = ମକାସର୍
language-name-man = ମାଣ୍ଡିଙ୍ଗୋ
language-name-mas = ମାସାଇ
language-name-mdf = ମୋକ୍ଷ
language-name-mdr = ମନ୍ଦାର
language-name-men = ମେନଡେ
language-name-mer = ମେରୁ
language-name-mfe = ମୋରିସୟେନ୍
language-name-mg = ମାଲାଗାସୀ
language-name-mga = ମଧ୍ୟ ଇରିଶ୍
language-name-mgh = ମଖୁୱା-ମେଟ୍ଟା
language-name-mgo = ମେଟା
language-name-mh = ମାର୍ଶାଲୀଜ୍
language-name-mi = ମାଓରୀ
language-name-mic = ମିକମୌକ୍
language-name-min = ମିନାଙ୍ଗାବାଉ
language-name-mk = ମାସେଡୋନିଆନ୍
language-name-ml = ମାଲାୟଲମ୍
language-name-mn = ମଙ୍ଗୋଳିୟ
language-name-mnc = ମାଞ୍ଚୁ
language-name-mni = ମଣିପୁରୀ
language-name-moh = ମୋହୌକ
language-name-mos = ମୋସି
language-name-mr = ମରାଠୀ
language-name-ms = ମାଲୟ
language-name-mt = ମାଲଟୀଜ୍
language-name-mua = ମୁନଡାଂ
language-name-mul = ବିବିଧ ଭାଷାମାନ
language-name-mus = କ୍ରୀକ୍
language-name-mwl = ମିରାଣ୍ଡିଜ୍
language-name-mwr = ମାରୱାରୀ
language-name-my = ବର୍ମୀଜ୍
language-name-myv = ଏର୍ଜୟା
language-name-mzn = ମାଜାନଡେରାନି
language-name-na = ନାଉରୁ
language-name-nap = ନୀପୋଲିଟାନ୍
language-name-naq = ନାମା
language-name-nb = ନରୱେଜିଆନ୍ ବୋକମଲ୍
language-name-nd = ଉତ୍ତର ନେଡବେଲେ
language-name-nds = ଲୋ ଜର୍ମାନ୍
language-name-ne = ନେପାଳୀ
language-name-new = ନେୱାରୀ
language-name-ng = ଡୋଙ୍ଗା
language-name-nia = ନୀୟାସ୍
language-name-niu = ନିୟୁଆନ୍
language-name-nl = ଡଚ୍
language-name-nl_BE = ଫ୍ଲେମିଶ୍
language-name-nmg = କୱାସିଓ
language-name-nn = ନରୱେଜିଆନ୍ ନିୟୋର୍ସ୍କ
language-name-nnh = ନାଗିମବୋନ୍
language-name-no = ନରୱେଜିଆନ୍
language-name-nog = ନୋଗାଇ
language-name-non = ପୁରୁଣା ନର୍ସ
language-name-nqo = ଏନକୋ
language-name-nr = ଦକ୍ଷିଣ ନେଡବେଲେ
language-name-nso = ଉତ୍ତରୀ ସୋଥୋ
language-name-nus = ନୁଏର
language-name-nv = ନାଭାଜୋ
language-name-nwc = ପାରମ୍ପରିକ ନେୱାରୀ
language-name-ny = ନିୟାଞ୍ଜ
language-name-nym = ନ୍ୟାମୱେଜୀ
language-name-nyn = ନ୍ୟାନକୋଲ୍
language-name-nyo = ନ୍ୟାରୋ
language-name-nzi = ଞ୍ଜିମା
language-name-oc = ଓସିଟାନ୍
language-name-oj = ଓଜିୱା
language-name-om = ଓରୋମୋ
language-name-or = ଓଡ଼ିଆ
language-name-os = ଓସେଟିକ୍
language-name-osa = ୱୌସେଜ୍
language-name-ota = ଓଟ୍ଟୋମନ୍ ତୁର୍କିସ୍
language-name-pa = ପଞ୍ଜାବୀ
language-name-pag = ପାଙ୍ଗାସିନିଆନ୍
language-name-pal = ପାହ୍ଲାଭି
language-name-pam = ପାମ୍ପାଙ୍ଗା
language-name-pap = ପାପିଆମେଣ୍ଟୋ
language-name-pau = ପାଲାଉଆନ୍
language-name-pcm = ନାଇଜେରୀୟ ପିଡଗିନ୍
language-name-peo = ପୁରୁଣା ପର୍ସିଆନ୍
language-name-phn = ଫୋନେସିଆନ୍
language-name-pi = ପାଲି
language-name-pl = ପୋଲିଶ୍
language-name-pon = ପୋହପିଏନ୍
language-name-prg = ପ୍ରୁସିୟ
language-name-pro = ପୁରୁଣା ପ୍ରେଭେନେସିଆଲ୍
language-name-ps = ପାସ୍ତୋ
language-name-pt = ପର୍ତ୍ତୁଗୀଜ୍‌
language-name-pt_BR = ବ୍ରାଜିଲିଆନ୍ ପର୍ତ୍ତୁଗୀଜ୍
language-name-pt_PT = ୟୁରୋପୀୟ ପର୍ତ୍ତୁଗୀଜ୍‌
language-name-qu = କ୍ୱେଚୁଆ
language-name-quc = କିଚେ
language-name-raj = ରାଜସ୍ଥାନୀ
language-name-rap = ରାପାନୁଇ
language-name-rar = ରାରୋତୋଙ୍ଗନ୍
language-name-rm = ରୋମାନଶ୍‌
language-name-rn = ରୁଣ୍ଡି
language-name-ro = ରୋମାନିଆନ୍
language-name-ro_MD = ମୋଲଡୋଭିଆନ୍
language-name-rof = ରୋମ୍ବୋ
language-name-rom = ରୋମାନି
language-name-root = ରୋଟ୍
language-name-ru = ରୁଷିୟ
language-name-rup = ଆରୋମାନିଆନ୍
language-name-rw = କିନ୍ୟାରୱାଣ୍ଡା
language-name-rwk = ଆରଡବ୍ୟୁଏ
language-name-sa = ସଂସ୍କୃତ
language-name-sad = ସଣ୍ଡାୱେ
language-name-sah = ସାଖା
language-name-sam = ସାମୌରିଟନ୍ ଆରମାଇକ୍
language-name-saq = ସମବୁରୁ
language-name-sas = ସାସାକ୍
language-name-sat = ସାନ୍ତାଳି
language-name-sba = ନଗାମବେ
language-name-sbp = ସାନଗୁ
language-name-sc = ସର୍ଦିନିଆନ୍
language-name-scn = ସିଶିଲିଆନ୍
language-name-sco = ସ୍କଟସ୍
language-name-sd = ସିନ୍ଧୀ
language-name-se = ଉତ୍ତର ସାମି
language-name-seh = ସେନା
language-name-sel = ସେଲ୍କପ୍
language-name-ses = କୋୟରା ସେନ୍ନି
language-name-sg = ସାଙ୍ଗୋ
language-name-sga = ପୁରୁଣା ଇରିଶ୍
language-name-sh = ସର୍ବୋ-କ୍ରୋଆଟିଆନ୍
language-name-shi = ତାଚେଲହିଟ୍
language-name-shn = ଶାନ୍
language-name-si = ସିଂହଳ
language-name-sid = ସିଦାମୋ
language-name-sk = ସ୍ଲୋଭାକ୍
language-name-sl = ସ୍ଲୋଭେନିଆନ୍
language-name-sm = ସାମୋଆନ୍
language-name-sma = ଦକ୍ଷିଣ ସାମି
language-name-smj = ଲୁଲେ ସାମି
language-name-smn = ଇନାରୀ ସାମି
language-name-sms = ସ୍କୋଲ୍ଟ ସାମୀ
language-name-sn = ଶୋନା
language-name-snk = ସୋନିଙ୍କେ
language-name-so = ସୋମାଲିଆ
language-name-sog = ସୋଗଡିଏନ୍
language-name-sq = ଆଲବାନିଆନ୍
language-name-sr = ସର୍ବିୟ
language-name-srn = ଶାରାନା ଟୋଙ୍ଗୋ
language-name-srr = ଶେରେର୍
language-name-ss = ସ୍ଵାତି
language-name-ssy = ସହୋ
language-name-st = ସେସୋଥୋ
language-name-su = ସୁଦାନୀଜ୍
language-name-suk = ସୁକୁମା
language-name-sus = ଶୁଶୁ
language-name-sux = ସୁମେରିଆନ୍
language-name-sv = ସ୍ୱେଡିସ୍
language-name-sw = ସ୍ୱାହିଲ୍
language-name-sw_CD = କଙ୍ଗୋ ସ୍ୱାହିଲି
language-name-swb = କୋମୋରିୟ
language-name-syc = କ୍ଲାସିକାଲ୍ ସିରିକ୍
language-name-syr = ସିରିକ୍
language-name-ta = ତାମିଲ୍
language-name-te = ତେଲୁଗୁ
language-name-tem = ତିମନେ
language-name-teo = ତେସା
language-name-ter = ତେରେନୋ
language-name-tet = ତେତୁମ୍
language-name-tg = ତାଜିକ୍
language-name-th = ଥାଇ
language-name-ti = ଟ୍ରିଗିନିଆ
language-name-tig = ଟାଇଗ୍ରେ
language-name-tiv = ତୀଭ୍
language-name-tk = ତୁର୍କମେନ୍
language-name-tkl = ଟୋକେଲାଉ
language-name-tl = ଟାଗାଲଗ୍
language-name-tlh = କ୍ଲିଙ୍ଗନ୍
language-name-tli = ତ୍ଲିଙ୍ଗିଟ୍
language-name-tmh = ତାମାଶେକ୍
language-name-tn = ସୱାନା
language-name-to = ଟୋଙ୍ଗା
language-name-tog = ନ୍ୟାସା ଟୋଙ୍ଗୋ
language-name-tpi = ଟୋକ୍ ପିସିନ୍
language-name-tr = ତୁର୍କିସ୍
language-name-trv = ତାରୋକୋ
language-name-ts = ସୋଙ୍ଗା
language-name-tsi = ତିସିମିସିଆନ୍
language-name-tt = ତାତାର୍
language-name-tum = ଟୁମ୍ବୁକା
language-name-tvl = ତୁଭାଲୁ
language-name-tw = ତ୍ୱି
language-name-twq = ତାସାୱାକ୍
language-name-ty = ତାହିତିଆନ୍
language-name-tyv = ତୁଭିନିଆନ୍
language-name-tzm = କେନ୍ଦ୍ରୀୟ ଆଟଲାସ୍ ଟାମାଜିଘାଟ୍
language-name-udm = ଉଦମୂର୍ତ୍ତ
language-name-ug = ୟୁଘୁର୍
language-name-uga = ୟୁଗୋରଟିକ୍
language-name-uk = ୟୁକ୍ରାନିଆନ୍
language-name-umb = ଉମ୍ବୁଣ୍ଡୁ
language-name-und = ଅଜଣା ଭାଷା
language-name-ur = ଉର୍ଦ୍ଦୁ
language-name-uz = ଉଜବେକ୍
language-name-vai = ଭାଇ
language-name-ve = ଭେଣ୍ଡା
language-name-vi = ଭିଏତନାମିଜ୍
language-name-vo = ବୋଲାପୁକ
language-name-vot = ଭୋଟିକ୍
language-name-vun = ଭୁନଜୋ
language-name-wa = ୱାଲୁନ୍
language-name-wae = ୱାଲସେର୍
language-name-wal = ୱାଲମୋ
language-name-war = ୱାରୈ
language-name-was = ୱାସୋ
language-name-wo = ୱୋଲଫ୍
language-name-xal = କାଲ୍ମୀକ୍
language-name-xh = ଖୋସା
language-name-xog = ସୋଗା
language-name-yao = ୟାଓ
language-name-yap = ୟାପୀସ୍
language-name-yav = ୟାଂବେନ୍
language-name-ybb = ୟେମବା
language-name-yi = ୟିଡିସ୍
language-name-yo = ୟୋରୁବା
language-name-yue = କାନଟୋନେସେ
language-name-za = ଜୁଆଙ୍ଗ
language-name-zap = ଜାପୋଟେକ୍
language-name-zbl = ବ୍ଲିସିମ୍ବଲସ୍
language-name-zen = ଜେନାଗା
language-name-zgh = ମାନାଙ୍କ ମରୋକିୟ ତାମାଜିଘାଟ୍
language-name-zh = ଚାଇନିଜ୍‌
language-name-zh_Hans = ସରଳୀକୃତ ଚାଇନିଜ୍‌
language-name-zh_Hant = ପାରମ୍ପରିକ ଚାଇନିଜ୍‌
language-name-zu = ଜୁଲୁ
language-name-zun = ଜୁନୀ
language-name-zxx = କୌଣସି ଲିଙ୍ଗୁଇଷ୍ଟ ସାମଗ୍ରୀ ନାହିଁ
language-name-zza = ଜାଜା
