language-name-aa = Kiafar
language-name-ab = Kiabkhazi
language-name-ace = Kiacheni
language-name-ach = Kiakoli
language-name-ada = Kiadangme
language-name-ady = Kiadyghe
language-name-af = Kiafrikana
language-name-agq = Kiaghem
language-name-ain = Kiainu
language-name-ak = Kiakani
language-name-ale = Kialeut
language-name-alt = Kialtai
language-name-am = Kiamhari
language-name-an = Kiaragoni
language-name-ang = Kiingereza cha Kale
language-name-anp = Kiangika
language-name-ar = Kiarabu
language-name-ar_001 = Kiarabu sanifu
language-name-arc = Kiaramu
language-name-arn = Kimapuche
language-name-arp = Kiarapaho
language-name-arq = Kiarabu cha Algeria
language-name-arz = Kiarabu cha Misri
language-name-as = Kiassam
language-name-asa = Kiasu
language-name-ast = Kiasturia
language-name-av = Kiavari
language-name-awa = Kiawadhi
language-name-ay = Kiaymara
language-name-az = Kiazerbaijani
language-name-ba = Kibashkir
language-name-ban = Kibali
language-name-bas = Kibasaa
language-name-bax = Kibamun
language-name-bbj = Kighomala
language-name-be = Kibelarusi
language-name-bej = Kibeja
language-name-bem = Kibemba
language-name-bez = Kibena
language-name-bfd = Kibafut
language-name-bg = Kibulgaria
language-name-bgn = Kibalochi cha Magharibi
language-name-bho = Kibhojpuri
language-name-bi = Kibislama
language-name-bin = Kibini
language-name-bkm = Kikom
language-name-bla = Kisiksika
language-name-bm = Kibambara
language-name-bn = Kibengali
language-name-bo = Kitibeti
language-name-br = Kibretoni
language-name-brx = Kibodo
language-name-bs = Kibosnia
language-name-bug = Lugha ya Buginese
language-name-bum = Kibulu
language-name-byn = Kiblin
language-name-byv = Kimedumba
language-name-ca = Kikatalani
language-name-ce = Kichechenia
language-name-ceb = Kichebuano
language-name-cgg = Kichiga
language-name-ch = Kichamorro
language-name-chk = Kichukisi
language-name-chm = Kimari
language-name-cho = Kichoktao
language-name-chr = Kicherokee
language-name-chy = Kicheyeni
language-name-ckb = Kikurdi cha Sorani
language-name-co = Kikosikani
language-name-cop = Kikhufti
language-name-crs = Krioli ya Shelisheli
language-name-cs = Kicheki
language-name-cu = Kislovakia cha Church
language-name-cv = Kichuvash
language-name-cy = Kiwelisi
language-name-da = Kidenmaki
language-name-dak = Kidakota
language-name-dar = Kidaragwa
language-name-dav = Kitaita
language-name-de = Kijerumani
language-name-dgr = Kidogrib
language-name-dje = Kizarma
language-name-dsb = Kidolnoserbski
language-name-dua = Kiduala
language-name-dv = Kidivehi
language-name-dyo = Kijola-Fonyi
language-name-dyu = Kijula
language-name-dz = Kizongkha
language-name-dzg = Kidazaga
language-name-ebu = Kiembu
language-name-ee = Kiewe
language-name-efi = Kiefik
language-name-egy = Kimisri
language-name-eka = Kiekajuk
language-name-el = Kigiriki
language-name-en = Kiingereza
language-name-eo = Kiesperanto
language-name-es = Kihispania
language-name-et = Kiestonia
language-name-eu = Kibasque
language-name-ewo = Kiewondo
language-name-fa = Kiajemi
language-name-ff = Kifula
language-name-fi = Kifini
language-name-fil = Kifilipino
language-name-fj = Kifiji
language-name-fo = Kifaroe
language-name-fon = Kifon
language-name-fr = Kifaransa
language-name-fro = Kifaransa cha Kale
language-name-frr = Kifrisia cha Kaskazini
language-name-frs = Kifrisia cha Mashariki
language-name-fur = Kifriulian
language-name-fy = Kifrisia cha Magharibi
language-name-ga = Kiayalandi
language-name-gaa = Ga
language-name-gag = Kigagauz
language-name-gba = Kigbaya
language-name-gd = Kigaeli cha Uskoti
language-name-gez = Kige’ez
language-name-gil = Kikiribati
language-name-gl = Kigalisi
language-name-gn = Kiguarani
language-name-gor = Kigorontalo
language-name-grc = Kiyunani
language-name-gsw = Kijerumani cha Uswisi
language-name-gu = Kigujarati
language-name-guz = Kikisii
language-name-gv = Kimanx
language-name-gwi = Gwichʼin
language-name-ha = Kihausa
language-name-haw = Kihawai
language-name-he = Kiebrania
language-name-hi = Kihindi
language-name-hil = Kihiligaynon
language-name-hit = Kihiti
language-name-hmn = Kihmong
language-name-hr = Kikroeshia
language-name-hsb = Kisobia cha Ukanda wa Juu
language-name-ht = Kihaiti
language-name-hu = Kihangari
language-name-hup = Hupa
language-name-hy = Kiarmenia
language-name-hz = Kiherero
language-name-ia = Kiintalingua
language-name-iba = Kiiban
language-name-ibb = Kiibibio
language-name-id = Kiindonesia
language-name-ig = Kiigbo
language-name-ii = Sichuan Yi
language-name-ilo = Kiilocano
language-name-inh = Kiingush
language-name-io = Kiido
language-name-is = Kiaisilandi
language-name-it = Kiitaliano
language-name-iu = Kiinuktitut
language-name-ja = Kijapani
language-name-jbo = Lojban
language-name-jgo = Kingomba
language-name-jmc = Kimachame
language-name-jv = Kijava
language-name-ka = Kijojia
language-name-kab = Kikabylia
language-name-kac = Kachin
language-name-kaj = Kijju
language-name-kam = Kikamba
language-name-kbd = Kikabardian
language-name-kbl = Kikanembu
language-name-kcg = Kityap
language-name-kde = Kimakonde
language-name-kea = Kikabuverdianu
language-name-kfo = Kikoro
language-name-kg = Kikongo
language-name-kha = Kikhasi
language-name-khq = Koyra Chiini
language-name-ki = Kikikuyu
language-name-kj = Kikwanyama
language-name-kk = Kikazakh
language-name-kkj = Lugha ya Kako
language-name-kl = Kikalaallisut
language-name-kln = Kikalenjin
language-name-km = Kikambodia
language-name-kmb = Kimbundu
language-name-kn = Kikannada
language-name-ko = Kikorea
language-name-koi = Kikomi-Permyak
language-name-kok = Kikonkani
language-name-kpe = Kikpelle
language-name-kr = Kikanuri
language-name-krc = Kikarachay-Balkar
language-name-krl = Karjala
language-name-kru = Kurukh
language-name-ks = Kikashmiri
language-name-ksb = Kisambaa
language-name-ksf = Kibafia
language-name-ksh = Kicologne
language-name-ku = Kikurdi
language-name-kum = Kumyk
language-name-kv = Kikomi
language-name-kw = Kikorni
language-name-ky = Kikyrgyz
language-name-la = Kilatini
language-name-lad = Kiladino
language-name-lag = Kirangi
language-name-lam = Lamba
language-name-lb = Kilasembagi
language-name-lez = Kilezighian
language-name-lg = Kiganda
language-name-li = Limburgish
language-name-lkt = Kilakota
language-name-ln = Kilingala
language-name-lo = Kilaosi
language-name-lol = Kimongo
language-name-loz = Kilozi
language-name-lrc = Kiluri cha Kaskazini
language-name-lt = Kilithuania
language-name-lu = Kiluba-Katanga
language-name-lua = Kiluba-Lulua
language-name-lun = Kilunda
language-name-luo = Kijaluo
language-name-lus = Kimizo
language-name-luy = Kiluhya
language-name-lv = Kilatvia
language-name-mad = Kimadura
language-name-maf = Kimafa
language-name-mag = Kimagahi
language-name-mai = Kimaithili
language-name-mak = Kimakasar
language-name-mas = Kimaasai
language-name-mde = Kimaba
language-name-mdf = Lugha ya Moksha
language-name-men = Kimende
language-name-mer = Kimeru
language-name-mfe = Kimoriseni
language-name-mg = Kimalagasi
language-name-mgh = Kimakhuwa-Meetto
language-name-mgo = Kimeta
language-name-mh = Kimashale
language-name-mi = Kimaori
language-name-mic = Mi’kmaq
language-name-min = Kiminangkabau
language-name-mk = Kimacedonia
language-name-ml = Kimalayalam
language-name-mn = Kimongolia
language-name-mni = Kimanipuri
language-name-moh = Lugha ya Mohawk
language-name-mos = Kimoore
language-name-mr = Kimarathi
language-name-ms = Kimalei
language-name-mt = Kimalta
language-name-mua = Kimundang
language-name-mul = Lugha Nyingi
language-name-mus = Kikriki
language-name-mwl = Kimirandi
language-name-my = Kiburma
language-name-myv = Kierzya
language-name-mzn = Kimazanderani
language-name-na = Kinauru
language-name-nap = Kinapoli
language-name-naq = Kinama
language-name-nb = Kinorwe cha Bokmal
language-name-nd = Kindebele cha Kaskazini
language-name-nds = Kisaksoni
language-name-ne = Kinepali
language-name-new = Kinewari
language-name-ng = Kindonga
language-name-nia = Kiniasi
language-name-niu = Kiniuea
language-name-nl = Kiholanzi
language-name-nl_BE = Kiflemi
language-name-nmg = Kikwasio
language-name-nn = Kinorwe cha Nynorsk
language-name-nnh = Lugha ya Ngiemboon
language-name-no = Kinorwe
language-name-nog = Kinogai
language-name-nqo = N’Ko
language-name-nr = Kindebele
language-name-nso = Kisotho cha Kaskazini
language-name-nus = Kinuer
language-name-nv = Kinavajo
language-name-nwc = Kinewari cha kale
language-name-ny = Kinyanja
language-name-nym = Kinyamwezi
language-name-nyn = Kinyankole
language-name-nyo = Kinyoro
language-name-nzi = Kinzema
language-name-oc = Kiokitani
language-name-om = Kioromo
language-name-or = Kioriya
language-name-os = Kiosetia
language-name-pa = Kipunjabi
language-name-pag = Kipangasinan
language-name-pam = Kipampanga
language-name-pap = Kipapiamento
language-name-pau = Kipalau
language-name-pcm = Pijini ya Nigeria
language-name-peo = Kiajemi cha Kale
language-name-pl = Kipolandi
language-name-prg = Kiprussia
language-name-ps = Kipashto
language-name-pt = Kireno
language-name-qu = Kiquechua
language-name-quc = Kʼicheʼ
language-name-rap = Kirapanui
language-name-rar = Kirarotonga
language-name-rm = Kiromanshi
language-name-rn = Kirundi
language-name-ro = Kiromania
language-name-rof = Kirombo
language-name-root = Root
language-name-ru = Kirusi
language-name-rup = Kiaromania
language-name-rw = Kinyarwanda
language-name-rwk = Lugha ya Rwa
language-name-sa = Kisanskriti
language-name-sad = Kisandawe
language-name-sah = Kisakha
language-name-sam = Kiaramu cha Wasamaria
language-name-saq = Kisamburu
language-name-sat = Kisantali
language-name-sba = Kingambay
language-name-sbp = Kisangu
language-name-sc = Kisardinia
language-name-scn = Kisicilia
language-name-sco = Kiskoti
language-name-sd = Kisindhi
language-name-sdh = Kikurdi cha Kusini
language-name-se = Kisami cha Kaskazini
language-name-seh = Kisena
language-name-ses = Koyraboro Senni
language-name-sg = Kisango
language-name-sh = Kiserbia-kroeshia
language-name-shi = Kitachelhit
language-name-shn = Kishan
language-name-si = Kisinhala
language-name-sk = Kislovakia
language-name-sl = Kislovenia
language-name-sm = Kisamoa
language-name-sma = Kisami cha Kusini
language-name-smj = Kisami cha Lule
language-name-smn = Kisami cha Inari
language-name-sms = Kisami cha Skolt
language-name-sn = Kishona
language-name-snk = Kisoninke
language-name-so = Kisomali
language-name-sq = Kialbania
language-name-sr = Kiserbia
language-name-srn = Lugha ya Sranan Tongo
language-name-ss = Kiswati
language-name-ssy = Kisaho
language-name-st = Kisotho
language-name-su = Kisunda
language-name-suk = Kisukuma
language-name-sus = Kisusu
language-name-sv = Kiswidi
language-name-sw = Kiswahili
language-name-sw_CD = Kingwana
language-name-swb = Shikomor
language-name-syr = Lugha ya Syriac
language-name-ta = Kitamil
language-name-te = Kitelugu
language-name-tem = Kitemne
language-name-teo = Kiteso
language-name-tet = Kitetum
language-name-tg = Kitajiki
language-name-th = Kitailandi
language-name-ti = Kitigrinya
language-name-tig = Kitigre
language-name-tk = Kiturukimeni
language-name-tlh = Kiklingoni
language-name-tn = Kitswana
language-name-to = Kitonga
language-name-tpi = Kitokpisin
language-name-tr = Kituruki
language-name-trv = Kitaroko
language-name-ts = Kitsonga
language-name-tt = Kitatari
language-name-tum = Kitumbuka
language-name-tvl = Kituvalu
language-name-tw = Twi
language-name-twq = Kitasawaq
language-name-ty = Kitahiti
language-name-tyv = Kituva
language-name-tzm = Central Atlas Tamazight
language-name-udm = Udmurt
language-name-ug = Kiuyghur
language-name-uk = Kiukraine
language-name-umb = Umbundu
language-name-und = Lugha Isiyojulikana
language-name-ur = Kiurdu
language-name-uz = Kiuzbeki
language-name-vai = Kivai
language-name-ve = Kivenda
language-name-vi = Kivietinamu
language-name-vo = Kivolapuk
language-name-vun = Kivunjo
language-name-wa = Walloon
language-name-wae = Walser
language-name-wal = Kiwolaytta
language-name-war = Kiwaray
language-name-wbp = Kiwarlpiri
language-name-wo = Lugha ya Wolof
language-name-xal = Kikalmyk
language-name-xh = Kixhosa
language-name-xog = Kisoga
language-name-yao = Kiyao
language-name-yav = Kiyangben
language-name-ybb = Kiyemba
language-name-yi = Kiyiddi
language-name-yo = Kiyoruba
language-name-yue = Kikantoni
language-name-zgh = Kiberber Sanifu cha Moroko
language-name-zh = Kichina
language-name-zh_Hant = Kichina cha Jadi
language-name-zu = Kizulu
language-name-zun = Kizuni
language-name-zxx = Hakuna maudhui ya lugha
language-name-zza = Kizaza
