language-name-ar_001 = جدید معیاری عربی
language-name-awa = اودھی
language-name-ckb = سورانی کردی
language-name-dje = زرمہ
language-name-hr = کروشین
language-name-jv = جاوانیز
language-name-ka = جارجيائى
language-name-kl = کلالیسٹ
language-name-kn = کنڑ
language-name-ku = کرد
language-name-mag = مگہی
language-name-zgh = معیاری مراقشی تمازیقی
language-name-zh_Hans = آسان چینی
