language-name-aa = افار
language-name-ab = ابقازیان
language-name-ace = اچائینیز
language-name-ach = اکولی
language-name-ada = ادانگمے
language-name-ady = ادیگھے
language-name-af = افریقی
language-name-agq = اغم
language-name-ain = اینو
language-name-ak = اکان
language-name-ale = الیوت
language-name-alt = جنوبی الٹائی
language-name-am = امہاری
language-name-an = اراگونیز
language-name-anp = انگیکا
language-name-ar = عربی
language-name-ar_001 = ماڈرن اسٹینڈرڈ عربی
language-name-arn = ماپوچے
language-name-arp = اراپاہو
language-name-as = آسامی
language-name-asa = آسو
language-name-ast = اسٹوریائی
language-name-av = اواری
language-name-awa = اوادھی
language-name-ay = ایمارا
language-name-az = آذربائیجانی
language-name-ba = باشکیر
language-name-ban = بالینیز
language-name-bas = باسا
language-name-be = بیلاروسی
language-name-bem = بیمبا
language-name-bez = بینا
language-name-bg = بلغاری
language-name-bgn = مغربی بلوچی
language-name-bho = بھوجپوری
language-name-bi = بسلاما
language-name-bin = بینی
language-name-bla = سکسیکا
language-name-bm = بمبارا
language-name-bn = بنگالی
language-name-bo = تبتی
language-name-br = بریٹن
language-name-brx = بوڈو
language-name-bs = بوسنی
language-name-bug = بگینیز
language-name-byn = بلین
language-name-ca = کیٹالان
language-name-ce = چیچن
language-name-ceb = سیبوآنو
language-name-cgg = چیگا
language-name-ch = چیمارو
language-name-chk = چوکیز
language-name-chm = ماری
language-name-cho = چاکٹاؤ
language-name-chr = چیروکی
language-name-chy = چینّے
language-name-ckb = سینٹرل کردش
language-name-co = کوراسیکن
language-name-crs = سیسلوا کریولے فرانسیسی
language-name-cs = چیک
language-name-cu = چرچ سلاوک
language-name-cv = چوواش
language-name-cy = ویلش
language-name-da = ڈینش
language-name-dak = ڈاکوٹا
language-name-dar = درگوا
language-name-dav = تائتا
language-name-de = جرمن
language-name-de_AT = آسٹریائی جرمن
language-name-de_CH = سوئس ہائی جرمن
language-name-dgr = دوگریب
language-name-dje = زرما
language-name-dsb = ذیلی سربیائی
language-name-dua = دوالا
language-name-dv = ڈیویہی
language-name-dyo = جولا فونيا
language-name-dz = ژونگکھا
language-name-dzg = دزاگا
language-name-ebu = امبو
language-name-ee = ایو
language-name-efi = ایفِک
language-name-eka = ایکاجوی
language-name-el = یونانی
language-name-en = انگریزی
language-name-en_AU = آسٹریلیائی انگریزی
language-name-en_CA = کینیڈین انگریزی
language-name-en_GB = برطانوی انگریزی
language-name-en_US = امریکی انگریزی
language-name-eo = ایسپرانٹو
language-name-es = ہسپانوی
language-name-es_419 = لاطینی امریکی ہسپانوی
language-name-es_ES = یورپی ہسپانوی
language-name-es_MX = میکسیکن ہسپانوی
language-name-et = اسٹونین
language-name-eu = باسکی
language-name-ewo = ایوانڈو
language-name-fa = فارسی
language-name-ff = فولہ
language-name-fi = فینیش
language-name-fil = فلیپینو
language-name-fj = فجی
language-name-fo = فیروئیز
language-name-fon = فون
language-name-fr = فرانسیسی
language-name-fr_CA = کینیڈین فرانسیسی
language-name-fr_CH = سوئس فرینچ
language-name-frc = کاجن فرانسیسی
language-name-fur = فریولیائی
language-name-fy = مغربی فریسیئن
language-name-ga = آئیرِش
language-name-gaa = گا
language-name-gag = غاغاوز
language-name-gan = gan
language-name-gd = سکاٹش گیلک
language-name-gez = گیز
language-name-gil = گلبرتیز
language-name-gl = گالیشیائی
language-name-gn = گُارانی
language-name-gor = گورانٹالو
language-name-gsw = سوئس جرمن
language-name-gu = گجراتی
language-name-guz = گسی
language-name-gv = مینکس
language-name-gwi = گوئچ ان
language-name-ha = ہؤسا
language-name-hak = hak
language-name-haw = ہوائی
language-name-he = عبرانی
language-name-hi = ہندی
language-name-hil = ہالیگینون
language-name-hmn = ہمانگ
language-name-hr = کراتی
language-name-hsb = اپر سربیائی
language-name-hsn = hsn
language-name-ht = ہیتی
language-name-hu = ہنگیرین
language-name-hup = ہیوپا
language-name-hy = آرمینیائی
language-name-hz = ہریرو
language-name-ia = بین لسانیات
language-name-iba = ایبان
language-name-ibb = ابی بیو
language-name-id = انڈونیثیائی
language-name-ig = اِگبو
language-name-ii = سچوان ای
language-name-ilo = ایلوکو
language-name-inh = انگوش
language-name-io = ایڈو
language-name-is = آئس لینڈک
language-name-it = اطالوی
language-name-iu = اینُکٹیٹٹ
language-name-ja = جاپانی
language-name-jbo = لوجبان
language-name-jgo = نگومبا
language-name-jmc = ماشیم
language-name-jv = جاوی
language-name-ka = جارجیائی
language-name-kab = قبائلی
language-name-kac = کاچن
language-name-kaj = جے جو
language-name-kam = کامبا
language-name-kbd = کبارڈین
language-name-kcg = تیاپ
language-name-kde = ماكونده
language-name-kea = كابويرديانو
language-name-kfo = کورو
language-name-kg = کانگو
language-name-kha = کھاسی
language-name-khq = كويرا شيني
language-name-ki = کیکویو
language-name-kj = کونیاما
language-name-kk = قزاخ
language-name-kkj = کاکو
language-name-kl = كالاليست
language-name-kln = كالينجين
language-name-km = خمیر
language-name-kmb = کیمبونڈو
language-name-kn = کنّاڈا
language-name-ko = کوریائی
language-name-koi = کومی پرمیاک
language-name-kok = کونکنی
language-name-kpe = کیپیلّے
language-name-kr = کنوری
language-name-krc = کراچے بالکر
language-name-krl = کیرلین
language-name-kru = کوروکھ
language-name-ks = کشمیری
language-name-ksb = شامبالا
language-name-ksf = بافيا
language-name-ksh = کولوگنیائی
language-name-ku = کردش
language-name-kum = کومیک
language-name-kv = کومی
language-name-kw = کورنش
language-name-ky = کرغیزی
language-name-la = لاطینی
language-name-lad = لیڈینو
language-name-lag = لانگی
language-name-lb = لکسمبرگیش
language-name-lez = لیزگیان
language-name-lg = گینڈا
language-name-li = لیمبرگش
language-name-lkt = لاکوٹا
language-name-ln = لِنگَلا
language-name-lo = لاؤ
language-name-lou = لوزیانا کریول
language-name-loz = لوزی
language-name-lrc = شمالی لری
language-name-lt = لیتھوینین
language-name-lu = لبا-كاتانجا
language-name-lua = لیوبا لولوآ
language-name-lun = لونڈا
language-name-luo = لو
language-name-lus = میزو
language-name-luy = لویا
language-name-lv = لیٹوین
language-name-mad = مدورسی
language-name-mag = مگاہی
language-name-mai = میتھیلی
language-name-mak = مکاسر
language-name-mas = مسائی
language-name-mdf = موکشا
language-name-men = میندے
language-name-mer = میرو
language-name-mfe = موریسیین
language-name-mg = ملاگاسی
language-name-mgh = ماخاوا-ميتو
language-name-mgo = میٹا
language-name-mh = مارشلیز
language-name-mi = ماؤری
language-name-mic = مکمیک
language-name-min = منانگکباؤ
language-name-mk = مقدونیائی
language-name-ml = مالایالم
language-name-mn = منگولین
language-name-mni = منی پوری
language-name-moh = موہاک
language-name-mos = موسی
language-name-mr = مراٹهی
language-name-ms = مالے
language-name-mt = مالٹی
language-name-mua = منڈانگ
language-name-mul = متعدد زبانیں
language-name-mus = کریک
language-name-mwl = میرانڈیز
language-name-my = برمی
language-name-myv = ارزیا
language-name-mzn = مزندرانی
language-name-na = ناؤرو
language-name-nan = nan
language-name-nap = نیاپولیٹن
language-name-naq = ناما
language-name-nb = نارویجین بوکمل
language-name-nd = شمالی دبیل
language-name-nds = ادنی جرمن
language-name-nds_NL = ادنی سیکسن
language-name-ne = نیپالی
language-name-new = نیواری
language-name-ng = نڈونگا
language-name-nia = نیاس
language-name-niu = نیویائی
language-name-nl = ڈچ
language-name-nl_BE = فلیمِش
language-name-nmg = كوايسو
language-name-nn = نارویجین نینورسک
language-name-nnh = نگیمبون
language-name-no = نارویجین
language-name-nog = نوگائی
language-name-nqo = اینکو
language-name-nr = جنوبی نڈیبیلی
language-name-nso = شمالی سوتھو
language-name-nus = نویر
language-name-nv = نواجو
language-name-ny = نیانجا
language-name-nyn = نینکول
language-name-oc = آكسیٹان
language-name-om = اورومو
language-name-or = اڑیہ
language-name-os = اوسیٹک
language-name-pa = پنجابی
language-name-pag = پنگاسنان
language-name-pam = پامپنگا
language-name-pap = پاپیامینٹو
language-name-pau = پالاون
language-name-pcm = نائجیریائی پڈگن
language-name-pl = پولش
language-name-prg = پارسی
language-name-ps = پشتو
language-name-pt = پُرتگالی
language-name-pt_BR = برازیلی پرتگالی
language-name-pt_PT = یورپی پرتگالی
language-name-qu = کویچوآ
language-name-quc = كيشی
language-name-rap = رپانوی
language-name-rar = راروتونگان
language-name-rm = رومانش
language-name-rn = رونڈی
language-name-ro = رومینین
language-name-ro_MD = مالدووا
language-name-rof = رومبو
language-name-root = روٹ
language-name-ru = روسی
language-name-rup = ارومانی
language-name-rw = کینیاروانڈا
language-name-rwk = روا
language-name-sa = سنسکرت
language-name-sad = سنڈاوے
language-name-sah = ساکھا
language-name-saq = سامبورو
language-name-sat = سنتالی
language-name-sba = نگامبے
language-name-sbp = سانگو
language-name-sc = سردینین
language-name-scn = سیسیلین
language-name-sco = سکاٹ
language-name-sd = سندھی
language-name-sdh = جنوبی کرد
language-name-se = شمالی سامی
language-name-seh = سینا
language-name-ses = كويرابورو سينی
language-name-sg = ساںغو
language-name-sh = سربو-کروئیشین
language-name-shi = تشلحيت
language-name-shn = شان
language-name-si = سنہالا
language-name-sk = سلوواک
language-name-sl = سلووینیائی
language-name-sm = ساموآن
language-name-sma = جنوبی سامی
language-name-smj = لول سامی
language-name-smn = اناری سامی
language-name-sms = سکولٹ سامی
language-name-sn = شونا
language-name-snk = سوننکے
language-name-so = صومالی
language-name-sq = البانی
language-name-sr = سربین
language-name-srn = سرانن ٹونگو
language-name-ss = سواتی
language-name-ssy = ساہو
language-name-st = جنوبی سوتھو
language-name-su = سنڈانیز
language-name-suk = سکوما
language-name-sv = سویڈش
language-name-sw = سواحلی
language-name-sw_CD = کانگو سواحلی
language-name-swb = کوموریائی
language-name-syr = سریانی
language-name-ta = تمل
language-name-te = تیلگو
language-name-tem = ٹمنے
language-name-teo = تیسو
language-name-tet = ٹیٹم
language-name-tg = تاجک
language-name-th = تھائی
language-name-ti = ٹگرینیا
language-name-tig = ٹگرے
language-name-tk = ترکمان
language-name-tl = ٹیگا لوگ
language-name-tlh = کلنگن
language-name-tn = سوانا
language-name-to = ٹونگن
language-name-tpi = ٹوک پِسِن
language-name-tr = ترکی
language-name-trv = ٹوروکو
language-name-ts = زونگا
language-name-tt = تاتار
language-name-tum = ٹمبوکا
language-name-tvl = تووالو
language-name-tw = توی
language-name-twq = تاساواق
language-name-ty = تاہیتی
language-name-tyv = تووینین
language-name-tzm = سینٹرل ایٹلس ٹمازائٹ
language-name-udm = ادمورت
language-name-ug = یوئگہر
language-name-uk = یوکرینیائی
language-name-umb = اومبوندو
language-name-und = نامعلوم زبان
language-name-ur = اردو
language-name-uz = ازبیک
language-name-vai = وائی
language-name-ve = وینڈا
language-name-vi = ویتنامی
language-name-vo = وولاپوک
language-name-vun = ونجو
language-name-wa = والون
language-name-wae = والسر
language-name-wal = وولایتا
language-name-war = وارے
language-name-wbp = وارلپیری
language-name-wo = وولوف
language-name-wuu = wuu
language-name-xal = کالمیک
language-name-xh = ژوسا
language-name-xog = سوگا
language-name-yav = یانگبین
language-name-ybb = یمبا
language-name-yi = یدش
language-name-yo = یوروبا
language-name-yue = کینٹونیز
language-name-zgh = اسٹینڈرڈ مراقشی تمازیقی
language-name-zh = چینی
language-name-zh_Hant = روایتی چینی
language-name-zu = زولو
language-name-zun = زونی
language-name-zxx = کوئی لسانی مواد نہیں
language-name-zza = زازا
