language-name-aa = 𑄃𑄜𑄢𑄴
language-name-ab = 𑄃𑄝𑄴𑄈𑄎𑄨𑄠𑄚𑄴
language-name-ace = 𑄃𑄳𑄃𑄌𑄳𑄆𑄚𑄨𑄎𑄴
language-name-ach = 𑄃𑄇𑄮𑄣𑄨
language-name-ada = 𑄃𑄧𑄘𑄟𑄳𑄉𑄬
language-name-ady = 𑄃𑄘𑄬𑄉𑄬
language-name-ae = 𑄃𑄝𑄬𑄌𑄴𑄖𑄩𑄠𑄧
language-name-af = 𑄃𑄜𑄳𑄢𑄨𑄇𑄚𑄴
language-name-afh = 𑄃𑄜𑄳𑄢𑄨𑄦𑄨𑄣𑄨
language-name-agq = 𑄃𑄬𑄊𑄟𑄴
language-name-ain = 𑄃𑄳𑄆𑄚𑄪
language-name-ak = 𑄃𑄇𑄚𑄴
language-name-akk = 𑄃𑄇𑄳𑄦𑄴𑄘𑄨𑄠𑄚𑄴
language-name-ale = 𑄃𑄣𑄬𑄅𑄖𑄴
language-name-alt = 𑄓𑄧𑄉𑄨𑄚𑄴 𑄃𑄣𑄴𑄖𑄭
language-name-am = 𑄃𑄟𑄴𑄦𑄢𑄨𑄇𑄴
language-name-an = 𑄃𑄢𑄴𑄉𑄮𑄚𑄨𑄎𑄴
language-name-ang = 𑄛𑄪𑄢𑄧𑄚𑄨 𑄃𑄟𑄧𑄣𑄧𑄢𑄴 𑄃𑄨𑄁𑄢𑄬𑄎𑄩
language-name-anp = 𑄃𑄋𑄳𑄉𑄨𑄇
language-name-ar = 𑄃𑄢𑄧𑄝𑄩
language-name-ar_001 = 𑄚𑄱 𑄉𑄧𑄟𑄴 𑄃𑄢𑄧𑄝𑄩
language-name-arc = 𑄃𑄢𑄟𑄳𑄆𑄇𑄴
language-name-arn = 𑄟𑄛𑄪𑄌𑄨
language-name-arp = 𑄃𑄢𑄛𑄦𑄮
language-name-arw = 𑄃𑄢𑄤𑄇𑄴
language-name-as = 𑄃𑄥𑄟𑄨
language-name-asa = 𑄃𑄥𑄪
language-name-ast = 𑄃𑄌𑄴𑄖𑄪𑄢𑄨𑄠𑄧
language-name-av = 𑄃𑄞𑄬𑄢𑄨𑄇𑄴
language-name-awa = 𑄃𑄤𑄙𑄨
language-name-ay = 𑄃𑄠𑄧𑄟𑄢
language-name-az = 𑄃𑄎𑄢𑄴𑄝𑄳𑄆𑄎𑄚𑄩
language-name-ba = 𑄝𑄌𑄴𑄇𑄨𑄢𑄴
language-name-bal = 𑄝𑄬𑄣𑄪𑄌𑄩
language-name-ban = 𑄝𑄣𑄨𑄚𑄩𑄠𑄧
language-name-bas = 𑄝𑄥
language-name-be = 𑄝𑄬𑄣𑄢𑄪𑄥𑄨𑄠𑄧
language-name-bej = 𑄝𑄬𑄎
language-name-bem = 𑄝𑄬𑄟𑄴𑄝
language-name-bez = 𑄝𑄬𑄚
language-name-bg = 𑄝𑄪𑄣𑄴𑄉𑄬𑄢𑄨𑄠𑄧
language-name-bgn = 𑄛𑄧𑄏𑄨𑄟𑄴 𑄝𑄣𑄮𑄌𑄨
language-name-bho = 𑄞𑄮𑄎𑄴𑄛𑄪𑄢𑄨
language-name-bi = 𑄝𑄨𑄥𑄴𑄣𑄟
language-name-bik = 𑄝𑄨𑄇𑄮𑄣𑄴
language-name-bin = 𑄝𑄨𑄚𑄨
language-name-bla = 𑄥𑄨𑄇𑄴𑄥𑄨𑄇
language-name-bm = 𑄝𑄟𑄴𑄝𑄢
language-name-bn = 𑄝𑄁𑄣
language-name-bo = 𑄖𑄨𑄛𑄴𑄝𑄧𑄖𑄨
language-name-br = 𑄝𑄳𑄢𑄬𑄑𑄧𑄚𑄴
language-name-bra = 𑄝𑄳𑄢𑄎𑄴
language-name-brx = 𑄝𑄮𑄢𑄮
language-name-bs = 𑄝𑄧𑄥𑄴𑄚𑄩𑄠𑄚𑄴
language-name-bua = 𑄝𑄪𑄢𑄨𑄠𑄖𑄴
language-name-bug = 𑄝𑄪𑄉𑄨𑄚𑄨
language-name-byn = 𑄝𑄳𑄣𑄨𑄚𑄴
language-name-ca = 𑄇𑄖𑄣𑄚𑄴
language-name-cad = 𑄇𑄳𑄠𑄓𑄮
language-name-car = 𑄝𑄳𑄠𑄢𑄨𑄛𑄴
language-name-cch = 𑄃𑄖𑄴𑄥𑄟𑄴
language-name-ccp = 𑄌𑄋𑄴𑄟𑄳𑄦
language-name-ce = 𑄌𑄬𑄌𑄬𑄚𑄴
language-name-ceb = 𑄌𑄬𑄝𑄪𑄠𑄚𑄮
language-name-cgg = 𑄌𑄨𑄉
language-name-ch = 𑄌𑄟𑄮𑄢𑄮
language-name-chb = 𑄌𑄨𑄛𑄴𑄌
language-name-chg = 𑄌𑄉𑄖𑄳𑄆
language-name-chk = 𑄌𑄪𑄇𑄨
language-name-chm = 𑄟𑄢𑄨
language-name-chn = 𑄌𑄨𑄚𑄪𑄇𑄴 𑄎𑄢𑄴𑄉𑄧𑄚𑄴
language-name-cho = 𑄌𑄧𑄇𑄴𑄑𑄳𑄅𑄧𑄠𑄧
language-name-chp = 𑄌𑄨𑄛𑄮𑄤𑄚𑄴
language-name-chr = 𑄌𑄬𑄢𑄮𑄇𑄩
language-name-chy = 𑄥𑄳𑄆𑄠𑄬𑄚𑄴
language-name-ckb = 𑄟𑄧𑄖𑄴𑄙𑄳𑄠𑄧 𑄇𑄪𑄢𑄴𑄘𑄨𑄌𑄴
language-name-co = 𑄇𑄧𑄢𑄴𑄥𑄨𑄇𑄚𑄴
language-name-cop = 𑄇𑄧𑄛𑄴𑄑𑄨𑄇𑄴
language-name-cr = 𑄇𑄳𑄢𑄨
language-name-crh = 𑄇𑄳𑄢𑄨𑄟𑄨𑄠𑄚𑄴 𑄖𑄪𑄢𑄴𑄇𑄨
language-name-crs = 𑄥𑄬𑄥𑄬𑄣𑄧𑄤 𑄇𑄳𑄢𑄬𑄃𑄮𑄣𑄴 𑄜𑄳𑄢𑄬𑄐𑄴𑄌𑄧
language-name-cs = 𑄌𑄬𑄇𑄴
language-name-csb = 𑄇𑄥𑄪𑄝𑄨𑄠𑄚𑄴
language-name-cu = 𑄌𑄢𑄴𑄌𑄴 𑄥𑄳𑄣𑄞𑄨𑄇𑄴
language-name-cv = 𑄌𑄪𑄝𑄥𑄴
language-name-cy = 𑄃𑄮𑄠𑄬𑄣𑄧𑄌𑄴
language-name-da = 𑄓𑄬𑄚𑄨𑄌𑄴
language-name-dak = 𑄓𑄇𑄮𑄑
language-name-dar = 𑄘𑄢𑄴𑄉𑄧𑄤
language-name-dav = 𑄖𑄳𑄆𑄖
language-name-de = 𑄎𑄢𑄴𑄟𑄚𑄴
language-name-de_AT = 𑄃𑄧𑄌𑄴𑄑𑄳𑄢𑄨𑄠𑄚𑄴 𑄎𑄢𑄴𑄟𑄚𑄴
language-name-de_CH = 𑄥𑄪𑄃𑄨𑄌𑄴 𑄦𑄭 𑄎𑄢𑄴𑄟𑄚𑄴
language-name-del = 𑄓𑄬𑄣𑄤𑄬𑄢𑄴
language-name-den = 𑄥𑄳𑄣𑄳𑄠𑄞𑄴
language-name-dgr = 𑄘𑄮𑄉𑄳𑄢𑄨𑄝𑄴
language-name-din = 𑄓𑄨𑄁𑄇
language-name-dje = 𑄎𑄢𑄴𑄟
language-name-doi = 𑄓𑄮𑄉𑄧𑄢𑄨
language-name-dsb = 𑄙𑄮𑄣𑄴𑄚𑄬𑄭𑄙𑄳𑄠𑄬 𑄥𑄮𑄢𑄴𑄝𑄨𑄠𑄚𑄴
language-name-dua = 𑄘𑄱𑄣
language-name-dum = 𑄟𑄧𑄖𑄴𑄙𑄳𑄠𑄧 𑄓𑄌𑄴
language-name-dv = 𑄘𑄨𑄝𑄬𑄦𑄨
language-name-dyo = 𑄎𑄧𑄣-𑄜𑄧𑄚𑄩
language-name-dyu = 𑄓𑄨𑄃𑄪𑄣
language-name-dz = 𑄎𑄮𑄋𑄴𑄉
language-name-dzg = 𑄘𑄉𑄎
language-name-ebu = 𑄃𑄬𑄟𑄳𑄝𑄪𑄪
language-name-ee = 𑄃𑄨𑄅𑄠𑄨
language-name-efi = 𑄆𑄜𑄨𑄇𑄴
language-name-egy = 𑄛𑄪𑄢𑄨𑄚𑄩 𑄟𑄨𑄥𑄧𑄢𑄩𑄠𑄧
language-name-eka = 𑄃𑄨𑄇𑄎𑄪𑄇𑄴
language-name-el = 𑄉𑄳𑄢𑄨𑄇𑄴
language-name-elx = 𑄆𑄣𑄟𑄭𑄖𑄴
language-name-en = 𑄃𑄨𑄁𑄢𑄨𑄎𑄨
language-name-en_AU = 𑄃𑄧𑄌𑄴𑄑𑄳𑄢𑄬𑄣𑄨𑄠𑄧 𑄃𑄨𑄁𑄢𑄬𑄎𑄨
language-name-en_CA = 𑄇𑄚𑄓𑄩𑄠𑄧 𑄃𑄨𑄁𑄢𑄬𑄎𑄨
language-name-en_GB = 𑄝𑄳𑄢𑄨𑄑𑄨𑄌𑄴 𑄃𑄨𑄁𑄢𑄬𑄎𑄨
language-name-en_US = 𑄃𑄟𑄬𑄢𑄨𑄇𑄢𑄴 𑄃𑄨𑄁𑄢𑄎𑄨
language-name-enm = 𑄟𑄧𑄖𑄴𑄙𑄳𑄠𑄧 𑄃𑄨𑄁𑄢𑄬𑄎𑄨
language-name-eo = 𑄆𑄥𑄴𑄛𑄬𑄢𑄚𑄴𑄖𑄮
language-name-es = 𑄥𑄳𑄛𑄳𑄠𑄚𑄨𑄌𑄴
language-name-es_419 = 𑄣𑄳𑄠𑄑𑄨𑄚𑄴 𑄃𑄟𑄬𑄢𑄨𑄇𑄚𑄴 𑄥𑄳𑄛𑄳𑄠𑄚𑄨𑄌𑄴
language-name-es_ES = 𑄄𑄅𑄢𑄮𑄛𑄩𑄠𑄧 𑄥𑄳𑄛𑄳𑄠𑄚𑄨𑄌𑄴
language-name-es_MX = 𑄟𑄳𑄠𑄇𑄴𑄥𑄨𑄇𑄚𑄴 𑄥𑄳𑄛𑄳𑄠𑄚𑄨𑄌𑄴
language-name-et = 𑄆𑄌𑄴𑄖𑄨𑄚𑄩𑄠𑄧
language-name-eu = 𑄝𑄌𑄴𑄇𑄧
language-name-ewo = 𑄄𑄃𑄮𑄚𑄴𑄓𑄮
language-name-fa = 𑄜𑄢𑄴𑄥𑄨
language-name-fan = 𑄜𑄳𑄠𑄋𑄴𑄉𑄧
language-name-fat = 𑄜𑄚𑄴𑄖𑄨
language-name-ff = 𑄜𑄪𑄣𑄳𑄦
language-name-fi = 𑄜𑄨𑄚𑄨𑄌𑄴
language-name-fil = 𑄜𑄨𑄣𑄨𑄛𑄨𑄚𑄮
language-name-fj = 𑄜𑄨𑄎𑄨𑄠𑄚𑄴
language-name-fo = 𑄜𑄢𑄮𑄌𑄴
language-name-fon = 𑄜𑄧𑄚𑄴
language-name-fr = 𑄜𑄧𑄢𑄥𑄨
language-name-fr_CA = 𑄇𑄚𑄓𑄩𑄠𑄧 𑄜𑄧𑄢𑄥𑄨
language-name-fr_CH = 𑄥𑄪𑄃𑄨𑄌𑄴 𑄜𑄧𑄢𑄥𑄨
language-name-frm = 𑄟𑄧𑄖𑄴𑄙𑄳𑄠𑄧 𑄜𑄧𑄢𑄥𑄨
language-name-fro = 𑄛𑄪𑄢𑄮𑄚𑄨 𑄜𑄧𑄢𑄥𑄨
language-name-frr = 𑄅𑄖𑄴𑄗𑄧𑄢𑄴 𑄎𑄬𑄌𑄴𑄎𑄮𑄢𑄴 𑄜𑄳𑄢𑄨𑄥𑄨𑄠𑄚𑄴
language-name-frs = 𑄛𑄪𑄉𑄮 𑄜𑄳𑄢𑄨𑄥𑄨𑄠𑄧
language-name-fur = 𑄜𑄳𑄢𑄨𑄃𑄪𑄣𑄨𑄠𑄚𑄴
language-name-fy = 𑄛𑄧𑄎𑄨𑄟𑄴 𑄜𑄳𑄢𑄨𑄥𑄨𑄠𑄚𑄴
language-name-ga = 𑄃𑄭𑄢𑄨𑄌𑄴
language-name-gaa = 𑄉𑄳𑄃
language-name-gag = 𑄉𑄉𑄃𑄪𑄌𑄴
language-name-gan = 𑄉𑄧𑄚𑄴
language-name-gay = 𑄉𑄧𑄠𑄮
language-name-gba = 𑄝𑄠
language-name-gd = 𑄃𑄨𑄌𑄴𑄇𑄧𑄖𑄴𑄥𑄧-𑄉𑄳𑄠𑄬𑄣𑄨𑄇𑄴
language-name-gez = 𑄉𑄩𑄎𑄴
language-name-gil = 𑄉𑄨𑄣𑄴𑄝𑄢𑄴𑄑𑄨𑄎𑄴
language-name-gl = 𑄉𑄳𑄠𑄣𑄨𑄥𑄨𑄠𑄧
language-name-gmh = 𑄟𑄧𑄖𑄴𑄙𑄳𑄠𑄧-𑄅𑄪𑄉𑄪𑄢𑄬 𑄎𑄢𑄴𑄟𑄚𑄩
language-name-gn = 𑄉𑄪𑄠𑄢𑄚𑄨
language-name-goh = 𑄛𑄪𑄢𑄮𑄚𑄴 𑄅𑄪𑄉𑄪𑄢𑄬 𑄎𑄢𑄴𑄟𑄚𑄩
language-name-gon = 𑄉𑄮𑄚𑄴𑄓𑄨
language-name-gor = 𑄉𑄢𑄮𑄚𑄴𑄖𑄣𑄮
language-name-got = 𑄉𑄧𑄗𑄨𑄇𑄴
language-name-grb = 𑄉𑄳𑄢𑄬𑄝𑄮
language-name-grc = 𑄛𑄪𑄢𑄮𑄚𑄴 𑄉𑄳𑄢𑄩𑄇𑄴
language-name-gsw = 𑄥𑄪𑄃𑄨𑄌𑄴 𑄥𑄢𑄴𑄟𑄚𑄴
language-name-gu = 𑄉𑄪𑄎𑄴𑄢𑄖𑄨
language-name-guz = 𑄉𑄪𑄥𑄩
language-name-gv = 𑄟𑄳𑄠𑄇𑄴𑄥𑄧
language-name-gwi = 𑄉𑄧𑄃𑄮𑄃𑄨𑄌𑄴𑄃𑄨𑄚𑄴
language-name-ha = 𑄦𑄃𑄪𑄥
language-name-hai = 𑄦𑄭𑄓
language-name-hak = 𑄦𑄧𑄇𑄴
language-name-haw = 𑄦𑄤𑄃𑄨𑄠𑄚𑄴
language-name-he = 𑄦𑄨𑄛𑄴𑄝𑄳𑄢𑄪
language-name-hi = 𑄦𑄨𑄚𑄴𑄓𑄨
language-name-hil = 𑄦𑄨𑄣𑄨𑄉𑄳𑄠𑄠𑄧𑄚𑄮𑄚𑄴
language-name-hit = 𑄦𑄨𑄖𑄨𑄨𑄖𑄴
language-name-hmn = 𑄦𑄳𑄦𑄟𑄮𑄋𑄴
language-name-ho = 𑄦𑄪𑄢𑄨 𑄟𑄮𑄖𑄪
language-name-hr = 𑄇𑄳𑄢𑄮𑄠𑄬𑄥𑄩𑄠𑄧
language-name-hsb = 𑄅𑄪𑄉𑄪𑄢𑄬 𑄥𑄮𑄢𑄴𑄥𑄨𑄠𑄚𑄴
language-name-hsn = Xiang 𑄌𑄨𑄚
language-name-ht = 𑄦𑄭𑄖𑄨𑄠𑄚𑄴
language-name-hu = 𑄦𑄁𑄉𑄬𑄢𑄩𑄠𑄧
language-name-hup = 𑄦𑄪𑄛
language-name-hy = 𑄃𑄢𑄴𑄟𑄬𑄚𑄨𑄠𑄧
language-name-hz = 𑄦𑄬𑄢𑄬𑄢𑄮
language-name-ia = 𑄃𑄨𑄚𑄴𑄑𑄢𑄴𑄣𑄨𑄁𑄉𑄪𑄠
language-name-iba = 𑄃𑄨𑄝𑄚𑄴
language-name-ibb = 𑄃𑄨𑄝𑄨𑄝𑄨𑄠𑄧
language-name-id = 𑄃𑄨𑄚𑄴𑄘𑄮𑄚𑄬𑄥𑄨𑄠𑄧
language-name-ie = 𑄃𑄨𑄚𑄴𑄑𑄢𑄴𑄣𑄨𑄁𑄉𑄧
language-name-ig = 𑄃𑄨𑄉𑄴𑄝𑄮
language-name-ii = 𑄥𑄨𑄥𑄪𑄠𑄚𑄴𑄠𑄨
language-name-ik = 𑄃𑄨𑄚𑄪𑄛𑄨𑄠𑄇𑄴
language-name-ilo = 𑄃𑄨𑄣𑄮𑄇𑄮
language-name-inh = 𑄃𑄨𑄁𑄉𑄪𑄌𑄴
language-name-io = 𑄃𑄨𑄓𑄮
language-name-is = 𑄃𑄭𑄌𑄴𑄣𑄳𑄠𑄚𑄴𑄓𑄨𑄠𑄧
language-name-it = 𑄃𑄨𑄖𑄣𑄩𑄠𑄧
language-name-iu = 𑄃𑄨𑄚𑄪𑄇𑄴𑄑𑄨𑄑𑄪𑄖𑄴
language-name-ja = 𑄎𑄛𑄚𑄨
language-name-jbo = 𑄣𑄮𑄌𑄴𑄝𑄚𑄴
language-name-jgo = 𑄉𑄮𑄟𑄴𑄝
language-name-jmc = 𑄟𑄇𑄟𑄬
language-name-jpr = 𑄎𑄪𑄘𑄬𑄃𑄮 𑄜𑄢𑄴𑄥𑄨
language-name-jrb = 𑄎𑄪𑄘𑄬𑄃𑄮 𑄃𑄢𑄧𑄝𑄨
language-name-jv = 𑄎𑄞𑄚𑄨𑄎𑄴
language-name-ka = 𑄎𑄧𑄢𑄴𑄎𑄨𑄠𑄚𑄴
language-name-kaa = 𑄇𑄢-𑄇𑄣𑄴𑄛𑄇𑄴
language-name-kab = 𑄇𑄝𑄭𑄣𑄬
language-name-kac = 𑄇𑄌𑄨𑄚𑄴
language-name-kaj = 𑄃𑄧𑄌𑄴𑄎𑄪
language-name-kam = 𑄇𑄟𑄴𑄝
language-name-kaw = 𑄇𑄃𑄪𑄃𑄨
language-name-kbd = 𑄇𑄝𑄢𑄴𑄓𑄨𑄠𑄚𑄴
language-name-kcg = 𑄑𑄃𑄨𑄠𑄛𑄴
language-name-kde = 𑄟𑄇𑄮𑄚𑄴𑄘𑄬
language-name-kea = 𑄇𑄝𑄪𑄞𑄢𑄴𑄘𑄨𑄠𑄚𑄪
language-name-kfo = 𑄇𑄮𑄢𑄮
language-name-kg = 𑄇𑄧𑄁𑄉𑄮
language-name-kha = 𑄈𑄥𑄨
language-name-kho = 𑄈𑄮𑄑𑄚𑄨𑄎𑄴
language-name-khq = 𑄇𑄮𑄠𑄧𑄢 𑄌𑄩𑄚𑄨
language-name-ki = 𑄇𑄨𑄇𑄪𑄠𑄪
language-name-kj = 𑄇𑄮𑄠𑄚𑄨𑄠𑄟
language-name-kk = 𑄇𑄎𑄇𑄴
language-name-kkj = 𑄇𑄇𑄮
language-name-kl = 𑄇𑄳𑄠𑄣𑄣𑄴𑄣𑄨𑄥𑄪𑄖𑄴
language-name-kln = 𑄇𑄣𑄬𑄚𑄴𑄎𑄨𑄚𑄴
language-name-km = 𑄈𑄧𑄟𑄬𑄢𑄴
language-name-kmb = 𑄇𑄨𑄟𑄴𑄝𑄪𑄚𑄴𑄘𑄪
language-name-kn = 𑄇𑄧𑄚𑄴𑄚𑄧𑄢𑄴
language-name-ko = 𑄇𑄮𑄢𑄨𑄠𑄚𑄴
language-name-koi = 𑄇𑄧𑄟𑄨-𑄛𑄢𑄧𑄟𑄨𑄃𑄇𑄴
language-name-kok = 𑄇𑄮𑄋𑄴𑄇𑄚𑄨
language-name-kos = 𑄇𑄮𑄥𑄳𑄢𑄭𑄚𑄴
language-name-kpe = 𑄇𑄴𑄛𑄬𑄣𑄳𑄣𑄬
language-name-kr = 𑄇𑄚𑄪𑄢𑄨
language-name-krc = 𑄇𑄢𑄴𑄌𑄮-𑄝𑄣𑄴𑄇𑄢𑄴
language-name-krl = 𑄇𑄢𑄬𑄣𑄨𑄠𑄚𑄴
language-name-kru = 𑄇𑄪𑄢𑄪𑄇𑄴
language-name-ks = 𑄇𑄌𑄴𑄟𑄨𑄢𑄨
language-name-ksb = 𑄥𑄟𑄴𑄝𑄣
language-name-ksf = 𑄝𑄜𑄨𑄠
language-name-ksh = 𑄇𑄣𑄴𑄥𑄧
language-name-ku = 𑄇𑄪𑄢𑄴𑄘𑄨𑄥𑄴
language-name-kum = 𑄇𑄪𑄟𑄨𑄇𑄴
language-name-kut = 𑄇𑄪𑄑𑄬𑄚𑄭
language-name-kv = 𑄇𑄮𑄟𑄨
language-name-kw = 𑄇𑄧𑄢𑄴𑄚𑄨𑄌𑄴
language-name-ky = 𑄇𑄨𑄢𑄴𑄉𑄨𑄌𑄴
language-name-la = 𑄣𑄑𑄨𑄚𑄴
language-name-lad = 𑄣𑄓𑄨𑄚𑄮
language-name-lag = 𑄣𑄋𑄴𑄉𑄨
language-name-lah = 𑄣𑄚𑄴𑄓
language-name-lam = 𑄣𑄟𑄴𑄝
language-name-lb = 𑄣𑄪𑄇𑄴𑄥𑄬𑄟𑄴𑄝𑄢𑄴𑄉𑄩𑄠𑄧
language-name-lez = 𑄣𑄬𑄎𑄴𑄊𑄨𑄠𑄚𑄴
language-name-lg = 𑄉𑄚𑄴𑄓
language-name-li = 𑄣𑄨𑄟𑄴𑄝𑄪𑄢𑄴𑄉𑄨𑄌𑄴
language-name-lkt = 𑄣𑄇𑄮𑄑
language-name-ln = 𑄣𑄨𑄋𑄴𑄉𑄣
language-name-lo = 𑄣𑄃𑄮
language-name-lol = 𑄟𑄮𑄋𑄴𑄉𑄮
language-name-loz = 𑄣𑄮𑄎𑄨
language-name-lrc = 𑄅𑄪𑄖𑄴𑄖𑄮𑄢𑄴 𑄣𑄪𑄢𑄨
language-name-lt = 𑄣𑄨𑄗𑄪𑄠𑄬𑄚𑄩𑄠𑄧
language-name-lu = 𑄣𑄪𑄝-𑄇𑄑𑄋𑄴𑄉
language-name-lua = 𑄣𑄪𑄝-𑄣𑄪𑄣𑄪𑄠
language-name-lui = 𑄣𑄭𑄪𑄥𑄬𑄚𑄮
language-name-lun = 𑄣𑄪𑄚𑄴𑄓
language-name-luo = 𑄣𑄪𑄠𑄮
language-name-lus = 𑄟𑄨𑄎𑄮
language-name-luy = 𑄣𑄭𑄪𑄠
language-name-lv = 𑄣𑄖𑄴𑄞𑄩𑄠𑄧
language-name-mad = 𑄟𑄘𑄪𑄢𑄬𑄥𑄬
language-name-mag = 𑄟𑄉𑄦𑄨
language-name-mai = 𑄟𑄳𑄆𑄧𑄗𑄨𑄣𑄨
language-name-mak = 𑄟𑄳𑄠𑄇𑄥𑄢𑄴
language-name-man = 𑄟𑄳𑄠𑄚𑄴𑄓𑄨𑄁𑄉𑄮
language-name-mas = 𑄟𑄥𑄭
language-name-mdf = 𑄟𑄮𑄇𑄴𑄥
language-name-mdr = 𑄟𑄳𑄠𑄚𑄴𑄓𑄢𑄴
language-name-men = 𑄟𑄬𑄚𑄴𑄓𑄬
language-name-mer = 𑄟𑄬𑄢𑄪
language-name-mfe = 𑄟𑄢𑄨𑄥𑄨𑄠𑄚𑄴
language-name-mg = 𑄟𑄣𑄉𑄥𑄨
language-name-mga = 𑄟𑄧𑄖𑄴𑄙𑄳𑄠 𑄃𑄭𑄢𑄨𑄌𑄴
language-name-mgh = 𑄟𑄈𑄪𑄠-𑄟𑄬𑄖𑄴𑄖𑄮
language-name-mgo = 𑄟𑄬𑄑
language-name-mh = 𑄟𑄢𑄴𑄥𑄣𑄨𑄎𑄴
language-name-mi = 𑄟𑄃𑄮𑄢𑄨
language-name-mic = 𑄟𑄨𑄇𑄟𑄳𑄠𑄇𑄴
language-name-min = 𑄟𑄨𑄚𑄋𑄴𑄇𑄝𑄃𑄪
language-name-mk = 𑄟𑄳𑄠𑄥𑄨𑄓𑄮𑄚𑄩𑄠𑄧
language-name-ml = 𑄟𑄣𑄠𑄣𑄟𑄴
language-name-mn = 𑄟𑄧𑄁𑄉𑄮𑄣𑄨𑄠𑄧
language-name-mnc = 𑄟𑄚𑄴𑄌𑄪
language-name-mni = 𑄟𑄚𑄨𑄛𑄪𑄢𑄩
language-name-moh = 𑄟𑄮𑄦𑄃𑄮𑄇𑄴
language-name-mos = 𑄟𑄧𑄥𑄨
language-name-mr = 𑄟𑄢𑄒𑄨
language-name-ms = 𑄟𑄣𑄧𑄠𑄴
language-name-mt = 𑄟𑄧𑄣𑄴𑄑𑄨𑄠𑄧
language-name-mua = 𑄟𑄪𑄘𑄋𑄴𑄉𑄧
language-name-mul = 𑄝𑄣𑄧𑄇𑄴𑄇𑄚𑄨 𑄞𑄌𑄴
language-name-mus = 𑄇𑄳𑄢𑄨𑄇𑄴
language-name-mwl = 𑄟𑄨𑄢𑄚𑄴𑄓𑄨𑄎𑄴
language-name-mwr = 𑄟𑄢𑄮𑄠𑄢𑄨
language-name-my = 𑄝𑄧𑄢𑄴𑄟𑄨
language-name-myv = 𑄆𑄢𑄧𑄎𑄨𑄠
language-name-mzn = 𑄟𑄎𑄚𑄴𑄘𑄬𑄢𑄚𑄨
language-name-na = 𑄚𑄃𑄪𑄢𑄪
language-name-nan = 𑄚𑄚𑄴
language-name-nap = 𑄚𑄬𑄠𑄛𑄮𑄣𑄨𑄑𑄚𑄴
language-name-naq = 𑄚𑄟
language-name-nb = 𑄚𑄧𑄢𑄴𑄃𑄮𑄠𑄬𑄎𑄨𑄠𑄚𑄴 𑄝𑄮𑄇𑄴𑄟𑄣𑄴
language-name-nd = 𑄅𑄖𑄴𑄖𑄧𑄢𑄴 𑄆𑄚𑄴𑄘𑄬𑄝𑄨𑄣𑄨
language-name-nds = 𑄖𑄧𑄣𑄬 𑄎𑄢𑄴𑄟𑄚𑄨
language-name-nds_NL = 𑄣𑄮𑄥𑄳𑄠𑄇𑄴𑄥𑄧𑄚𑄴
language-name-ne = 𑄚𑄬𑄛𑄣𑄨
language-name-new = 𑄚𑄬𑄃𑄮𑄠𑄢𑄨
language-name-ng = 𑄆𑄚𑄴𑄘𑄮𑄋𑄴𑄉
language-name-nia = 𑄚𑄨𑄠𑄌𑄴
language-name-niu = 𑄚𑄨𑄃𑄪𑄠𑄚𑄴
language-name-nl = 𑄓𑄌𑄴
language-name-nl_BE = 𑄜𑄳𑄣𑄬𑄟𑄨𑄌𑄴
language-name-nmg = 𑄇𑄱𑄥𑄨𑄃𑄮
language-name-nn = 𑄚𑄧𑄢𑄴𑄃𑄮𑄠𑄬𑄎𑄩𑄠𑄚𑄴 𑄚𑄨𑄚𑄧𑄢𑄴𑄥𑄳𑄇𑄴
language-name-nnh = 𑄚𑄨𑄋𑄴𑄉𑄬𑄟𑄴𑄝𑄪𑄚𑄴
language-name-no = 𑄚𑄧𑄢𑄴𑄃𑄮𑄠𑄬𑄎𑄩𑄠𑄧
language-name-nog = 𑄚𑄮𑄉𑄭
language-name-non = 𑄛𑄪𑄢𑄮𑄚𑄴 𑄚𑄧𑄢𑄴𑄥𑄧
language-name-nqo = 𑄆𑄚𑄴𑄇𑄮
language-name-nr = 𑄓𑄧𑄉𑄨𑄚𑄴 𑄆𑄚𑄴𑄓𑄬𑄝𑄬𑄣𑄬
language-name-nso = 𑄃𑄪𑄖𑄴𑄗𑄧𑄢𑄴 𑄢𑄬𑄌𑄴𑄎𑄮𑄢𑄴 𑄥𑄮𑄗𑄮
language-name-nus = 𑄚𑄪𑄠𑄢𑄴
language-name-nv = 𑄚𑄞𑄎𑄮
language-name-nwc = 𑄛𑄪𑄢𑄮𑄚𑄴 𑄚𑄬𑄃𑄮𑄠𑄢𑄩
language-name-ny = 𑄚𑄠𑄚𑄴𑄎
language-name-nym = 𑄚𑄳𑄠𑄠𑄟𑄴𑄃𑄮𑄠𑄬𑄎𑄨
language-name-nyn = 𑄚𑄳𑄠𑄠𑄋𑄴𑄇𑄮𑄣𑄬
language-name-nyo = 𑄚𑄧𑄱𑄢𑄮
language-name-nzi = 𑄆𑄚𑄴𑄎𑄨𑄟
language-name-oc = 𑄃𑄧𑄇𑄴𑄥𑄨𑄑𑄚𑄴
language-name-oj = 𑄃𑄮𑄎𑄨𑄝𑄧𑄤
language-name-om = 𑄃𑄧𑄢𑄮𑄟𑄮
language-name-or = 𑄃𑄮𑄢𑄨𑄠
language-name-os = 𑄃𑄮𑄥𑄬𑄑𑄨𑄇𑄴
language-name-osa = 𑄃𑄮𑄥𑄬𑄌𑄴
language-name-ota = 𑄃𑄧𑄑𑄮𑄟𑄚𑄴 𑄖𑄪𑄢𑄴𑄇𑄨
language-name-pa = 𑄛𑄚𑄴𑄎𑄝𑄩
language-name-pag = 𑄛𑄁𑄉𑄥𑄨𑄚𑄚𑄴
language-name-pal = 𑄛𑄦𑄳𑄣𑄞𑄨
language-name-pam = 𑄛𑄟𑄴𑄛𑄋𑄴𑄉
language-name-pap = 𑄛𑄛𑄨𑄠𑄟𑄬𑄚𑄴𑄖𑄮
language-name-pau = 𑄛𑄣𑄠𑄪𑄠𑄚𑄴
language-name-pcm = 𑄚𑄎𑄬𑄢𑄨𑄠𑄧 𑄛𑄨𑄎𑄨𑄚𑄴
language-name-peo = 𑄛𑄪𑄢𑄮𑄚𑄴 𑄜𑄢𑄴𑄥𑄨
language-name-phn = 𑄜𑄮𑄚𑄨𑄥𑄨𑄠𑄚𑄴
language-name-pi = 𑄛𑄣𑄨
language-name-pl = 𑄛𑄮𑄣𑄨𑄌𑄴
language-name-pon = 𑄛𑄮𑄚𑄴𑄦𑄧𑄛𑄳𑄆𑄬𑄠𑄚𑄴
language-name-prg = 𑄛𑄴𑄢𑄪𑄥𑄨𑄠𑄚𑄴
language-name-pro = 𑄛𑄪𑄢𑄮𑄚𑄴 𑄛𑄳𑄢𑄮𑄞𑄬𑄚𑄴𑄥𑄣𑄴
language-name-ps = 𑄛𑄌𑄴𑄑𑄪
language-name-pt = 𑄛𑄧𑄢𑄴𑄖𑄪𑄉𑄨𑄎𑄴
language-name-pt_BR = 𑄝𑄳𑄢𑄎𑄨𑄣𑄬𑄢𑄴 𑄛𑄧𑄢𑄴𑄖𑄪𑄉𑄨𑄎𑄴
language-name-pt_PT = 𑄃𑄨𑄃𑄪𑄢𑄮𑄛𑄬𑄢𑄴 𑄛𑄧𑄢𑄴𑄖𑄪𑄉𑄨𑄎𑄴
language-name-qu = 𑄇𑄬𑄌𑄪𑄠
language-name-quc = 𑄇𑄳𑄦𑄨𑄌𑄬
language-name-raj = 𑄢𑄎𑄴𑄥𑄳𑄦𑄚𑄨
language-name-rap = 𑄢𑄛𑄚𑄳𑄆𑄪
language-name-rar = 𑄢𑄢𑄮𑄑𑄮𑄁𑄉𑄚𑄴
language-name-rm = 𑄢𑄮𑄟𑄚𑄴𑄥𑄴
language-name-rn = 𑄢𑄪𑄚𑄴𑄘𑄨
language-name-ro = 𑄢𑄮𑄟𑄚𑄩𑄠𑄧
language-name-ro_MD = 𑄟𑄧𑄣𑄴𑄘𑄞𑄨𑄠𑄧
language-name-rof = 𑄢𑄧𑄟𑄴𑄝𑄮
language-name-rom = 𑄢𑄮𑄟𑄚𑄨
language-name-root = 𑄥𑄨𑄠𑄮𑄢𑄴
language-name-ru = 𑄢𑄪𑄌𑄴
language-name-rup = 𑄃𑄢𑄴𑄟𑄬𑄚𑄨𑄠𑄚𑄴
language-name-rw = 𑄇𑄨𑄚𑄴𑄠𑄢𑄮𑄠𑄚𑄴𑄓
language-name-rwk = 𑄢𑄤
language-name-sa = 𑄥𑄧𑄁𑄥𑄴𑄇𑄳𑄢𑄨𑄖𑄴
language-name-sad = 𑄥𑄳𑄠𑄚𑄴𑄓𑄃𑄮𑄠𑄬
language-name-sah = 𑄥𑄈
language-name-sam = 𑄥𑄟𑄢𑄨𑄑𑄚𑄴 𑄃𑄢𑄟𑄨𑄇𑄴
language-name-saq = 𑄥𑄟𑄴𑄝𑄪𑄢𑄪
language-name-sas = 𑄥𑄥𑄇𑄴
language-name-sat = 𑄥𑄀𑄃𑄮𑄖𑄣𑄨
language-name-sba = 𑄚𑄳𑄠𑄉𑄟𑄴𑄝𑄬
language-name-sbp = 𑄥𑄁𑄚𑄴𑄉𑄪
language-name-sc = 𑄥𑄢𑄴𑄓𑄨𑄚𑄨𑄠𑄚𑄴
language-name-scn = 𑄥𑄨𑄥𑄨𑄣𑄨𑄠𑄚𑄴
language-name-sco = 𑄆𑄌𑄴𑄇𑄧𑄖𑄴𑄥𑄴
language-name-sd = 𑄥𑄨𑄚𑄴𑄙𑄨
language-name-sdh = 𑄘𑄧𑄉𑄨𑄚𑄴 𑄇𑄪𑄢𑄴𑄘𑄨𑄌𑄴
language-name-se = 𑄅𑄖𑄴𑄖𑄧𑄢𑄴 𑄢𑄬𑄌𑄴𑄎𑄮𑄢𑄴 𑄥𑄟𑄨
language-name-seh = 𑄥𑄬𑄚
language-name-sel = 𑄥𑄬𑄣𑄴𑄇𑄪𑄛𑄴
language-name-ses = 𑄇𑄱𑄢𑄝𑄬𑄚𑄮 𑄥𑄬𑄚𑄳𑄚𑄨
language-name-sg = 𑄥𑄋𑄴𑄉𑄮
language-name-sga = 𑄛𑄪𑄢𑄮𑄚𑄴 𑄃𑄭𑄢𑄨𑄌𑄴
language-name-sh = 𑄥𑄢𑄴𑄝𑄮-𑄇𑄳𑄢𑄮𑄠𑄬𑄥𑄨𑄠𑄧
language-name-shi = 𑄖𑄌𑄬𑄣𑄴𑄦𑄨𑄖𑄴
language-name-shn = 𑄥𑄚𑄴
language-name-si = 𑄥𑄨𑄁𑄦𑄧𑄣𑄩
language-name-sid = 𑄥𑄨𑄓𑄟𑄮
language-name-sk = 𑄥𑄳𑄣𑄮𑄞𑄇𑄴
language-name-sl = 𑄥𑄳𑄣𑄮𑄞𑄬𑄚𑄩𑄠𑄧
language-name-sm = 𑄥𑄟𑄮𑄠𑄚𑄴
language-name-sma = 𑄘𑄧𑄉𑄨𑄚𑄴 𑄢𑄬𑄌𑄴𑄎𑄮𑄢𑄴 𑄥𑄟𑄨
language-name-smj = 𑄣𑄪𑄣𑄬 𑄥𑄟𑄨
language-name-smn = 𑄃𑄨𑄚𑄢𑄨 𑄥𑄟𑄨
language-name-sms = 𑄥𑄳𑄇𑄧𑄣𑄳𑄑𑄧 𑄥𑄟𑄨
language-name-sn = 𑄥𑄮𑄚
language-name-snk = 𑄥𑄮𑄚𑄨𑄋𑄴𑄇𑄬
language-name-so = 𑄥𑄮𑄟𑄣𑄨
language-name-sog = 𑄥𑄮𑄇𑄴𑄓𑄠𑄚𑄴
language-name-sq = 𑄃𑄣𑄴𑄝𑄬𑄚𑄩𑄠𑄧
language-name-sr = 𑄥𑄢𑄴𑄝𑄩𑄠𑄧
language-name-srn = 𑄥𑄳𑄢𑄚𑄚𑄴 𑄑𑄮𑄋𑄴𑄉𑄮
language-name-srr = 𑄥𑄬𑄢𑄬𑄢𑄴
language-name-ss = 𑄥𑄮𑄠𑄖𑄨
language-name-ssy = 𑄥𑄦𑄮
language-name-st = 𑄘𑄧𑄉𑄨𑄚𑄴 𑄥𑄮𑄗𑄮
language-name-su = 𑄥𑄪𑄘𑄚𑄩
language-name-suk = 𑄥𑄪𑄇𑄪𑄟
language-name-sus = 𑄥𑄪𑄥𑄪
language-name-sux = 𑄥𑄪𑄟𑄬𑄢𑄩𑄠𑄧
language-name-sv = 𑄥𑄭𑄪𑄓𑄨𑄥𑄴
language-name-sw = 𑄥𑄱𑄦𑄨𑄣𑄨
language-name-sw_CD = 𑄇𑄧𑄋𑄴𑄉𑄮 𑄥𑄱𑄦𑄨𑄣𑄨
language-name-swb = 𑄇𑄧𑄟𑄮𑄢𑄨𑄠𑄚𑄴
language-name-syc = 𑄛𑄪𑄢𑄮𑄚𑄴 𑄥𑄨𑄢𑄨𑄃𑄮
language-name-syr = 𑄥𑄨𑄢𑄨𑄠𑄇𑄴
language-name-ta = 𑄖𑄟𑄨𑄣𑄴
language-name-te = 𑄖𑄬𑄣𑄬𑄉𑄪
language-name-tem = 𑄑𑄭𑄟𑄴𑄚𑄬
language-name-teo = 𑄖𑄬𑄥𑄮
language-name-ter = 𑄖𑄬𑄢𑄬𑄚𑄮
language-name-tet = 𑄖𑄬𑄖𑄪𑄟𑄴
language-name-tg = 𑄖𑄎𑄨𑄇𑄴
language-name-th = 𑄗𑄭
language-name-ti = 𑄖𑄨𑄉𑄧𑄢𑄨𑄚𑄨𑄠
language-name-tig = 𑄑𑄭𑄉𑄳𑄢𑄬
language-name-tiv = 𑄑𑄨𑄞𑄴
language-name-tk = 𑄖𑄪𑄢𑄴𑄇𑄧𑄟𑄬𑄚𑄨
language-name-tkl = 𑄑𑄮𑄇𑄬𑄣𑄃𑄪
language-name-tl = 𑄖𑄉𑄣𑄧𑄇𑄴
language-name-tlh = 𑄇𑄳𑄣𑄨𑄋𑄴𑄉𑄧𑄚𑄴
language-name-tli = 𑄖𑄴𑄣𑄨𑄋𑄴𑄉𑄨𑄖𑄴
language-name-tmh = 𑄖𑄟𑄥𑄬𑄇𑄴
language-name-tn = 𑄥𑄱𑄚
language-name-to = 𑄑𑄮𑄋𑄴𑄉𑄚𑄴
language-name-tog = 𑄚𑄠𑄥𑄑𑄮𑄋𑄴𑄉
language-name-tpi = 𑄑𑄮𑄇𑄴 𑄛𑄨𑄥𑄨𑄚𑄴
language-name-tr = 𑄖𑄪𑄢𑄴𑄇𑄩
language-name-trv = 𑄖𑄢𑄮𑄇𑄮
language-name-ts = 𑄥𑄧𑄋𑄴𑄉
language-name-tsi = 𑄥𑄨𑄟𑄴𑄥𑄨𑄠𑄚𑄴
language-name-tt = 𑄖𑄖𑄢𑄴
language-name-tum = 𑄖𑄪𑄟𑄴𑄝𑄪𑄇
language-name-tvl = 𑄑𑄪𑄞𑄣𑄪
language-name-tw = 𑄑𑄮𑄠𑄭
language-name-twq = 𑄖𑄥𑄤𑄇𑄴
language-name-ty = 𑄖𑄦𑄨𑄖𑄨𑄠𑄚𑄴
language-name-tyv = 𑄑𑄪𑄞𑄨𑄚𑄨𑄠𑄚𑄴
language-name-tzm = 𑄥𑄬𑄚𑄴𑄑𑄳𑄢𑄣𑄴 𑄃𑄣𑄴𑄖𑄌𑄴 𑄖𑄟𑄎𑄨𑄉𑄖𑄴
language-name-udm = 𑄃𑄪𑄓𑄴𑄟𑄪𑄢𑄴𑄑𑄧
language-name-ug = 𑄃𑄪𑄃𑄨𑄊𑄪𑄢𑄴
language-name-uga = 𑄃𑄪𑄉𑄢𑄨𑄑𑄨𑄇𑄴
language-name-uk = 𑄃𑄨𑄃𑄪𑄇𑄳𑄢𑄬𑄚𑄩𑄠𑄧
language-name-umb = 𑄃𑄪𑄟𑄴𑄝𑄪𑄚𑄴𑄘𑄪
language-name-und = 𑄦𑄧𑄝𑄧𑄢𑄴 𑄚𑄧𑄛𑄬𑄠𑄬 𑄞𑄌𑄴
language-name-ur = 𑄃𑄪𑄢𑄴𑄘𑄪
language-name-uz = 𑄃𑄪𑄎𑄴𑄝𑄬𑄇𑄩𑄠𑄧
language-name-vai = 𑄞𑄭
language-name-ve = 𑄞𑄬𑄚𑄴𑄓
language-name-vi = 𑄞𑄨𑄠𑄬𑄖𑄴𑄚𑄟𑄩
language-name-vo = 𑄞𑄮𑄣𑄛𑄪𑄇𑄴
language-name-vot = 𑄞𑄮𑄑𑄨𑄇𑄴
language-name-vun = 𑄞𑄪𑄚𑄴𑄏𑄮
language-name-wa = 𑄤𑄣𑄪𑄚𑄴
language-name-wae = 𑄤𑄣𑄧𑄥𑄬𑄢𑄴
language-name-wal = 𑄤𑄣𑄟𑄮
language-name-war = 𑄤𑄢𑄬
language-name-was = 𑄤𑄥𑄮
language-name-wbp = 𑄤𑄢𑄴𑄣𑄴𑄛𑄨𑄢𑄨
language-name-wo = 𑄤𑄃𑄮𑄣𑄮𑄜𑄴
language-name-wuu = 𑄤𑄌𑄨𑄚
language-name-xal = 𑄇𑄣𑄴𑄟𑄳𑄆𑄧𑄇𑄴
language-name-xh = 𑄎𑄮𑄥
language-name-xog = 𑄥𑄮𑄉
language-name-yao = 𑄃𑄨𑄠𑄃𑄮
language-name-yap = 𑄃𑄨𑄠𑄛𑄬𑄥𑄬
language-name-yav = 𑄠𑄋𑄴𑄉𑄧𑄝𑄬𑄚𑄴
language-name-ybb = 𑄠𑄮𑄟𑄴𑄝
language-name-yi = 𑄠𑄨𑄖𑄴𑄘𑄨𑄥𑄴
language-name-yo = 𑄃𑄨𑄃𑄮𑄢𑄪𑄝
language-name-yue = 𑄇𑄳𑄠𑄚𑄴𑄑𑄮𑄚𑄩𑄎𑄴
language-name-za = 𑄏𑄪𑄠𑄋𑄴
language-name-zap = 𑄎𑄛𑄮𑄑𑄬𑄇𑄴
language-name-zbl = 𑄃𑄉𑄬𑄠 𑄞𑄌𑄴
language-name-zen = 𑄎𑄬𑄚𑄉
language-name-zgh = 𑄉𑄧𑄟𑄴𑄘𑄮𑄣𑄴 𑄟𑄧𑄢𑄧𑄇𑄧𑄧𑄱𑄚𑄴𑄖𑄟𑄎𑄨𑄉𑄖𑄴
language-name-zh = 𑄌𑄩𑄚
language-name-zh_Hans = 𑄅𑄪𑄎𑄪𑄅𑄪𑄏𑄫 𑄌𑄩𑄚
language-name-zh_Hant = 𑄢𑄨𑄘𑄨𑄥𑄪𑄘𑄮𑄟𑄴 𑄌𑄩𑄚
language-name-zu = 𑄎𑄪𑄣𑄪
language-name-zun = 𑄎𑄪𑄚𑄨
language-name-zxx = 𑄞𑄏𑄧𑄢𑄴𑄘𑄮𑄇𑄳𑄠𑄬 𑄝𑄨𑄥𑄧𑄠𑄴 𑄚𑄳𑄄𑄬
language-name-zza = 𑄎𑄎
