language-name-aa = Afar
language-name-ab = Abhazca
language-name-ace = Açece
language-name-ach = Acoli
language-name-ada = Adangme
language-name-ady = Adigece
language-name-ae = Avestçe
language-name-aeb = Tunus Arapçası
language-name-af = Afrikaanca
language-name-afh = Afrihili
language-name-agq = Aghem
language-name-ain = Ayni Dili
language-name-ak = Akan
language-name-akk = Akad Dili
language-name-akz = Alabamaca
language-name-ale = Aleut dili
language-name-aln = Gheg Arnavutçası
language-name-alt = Güney Altayca
language-name-am = Amharca
language-name-an = Aragonca
language-name-ang = Eski İngilizce
language-name-anp = Angika
language-name-ar = Arapça
language-name-ar_001 = Modern Standart Arapça
language-name-arc = Aramice
language-name-arn = Mapuçe dili
language-name-aro = Araona
language-name-arp = Arapaho Dili
language-name-arq = Cezayir Arapçası
language-name-ars = Necd Arapçası
language-name-arw = Arawak Dili
language-name-ary = Fas Arapçası
language-name-arz = Mısır Arapçası
language-name-as = Assamca
language-name-asa = Asu
language-name-ase = Amerikan İşaret Dili
language-name-ast = Asturyasca
language-name-av = Avar Dili
language-name-avk = Kotava
language-name-awa = Awadhi
language-name-ay = Aymara
language-name-az = Azerice
language-name-az_Arab = Güney Azerice
language-name-ba = Başkırtça
language-name-bal = Beluçça
language-name-ban = Bali dili
language-name-bar = Bavyera dili
language-name-bas = Basa Dili
language-name-bax = Bamun
language-name-bbc = Batak Toba
language-name-bbj = Ghomala
language-name-be = Belarusça
language-name-bej = Beja dili
language-name-bem = Bemba
language-name-bew = Betawi
language-name-bez = Bena
language-name-bfd = Bafut
language-name-bfq = Badaga
language-name-bg = Bulgarca
language-name-bgn = Batı Balochi
language-name-bho = Arayanice
language-name-bi = Bislama
language-name-bik = Bikol
language-name-bin = Bini
language-name-bjn = Banjar Dili
language-name-bkm = Kom
language-name-bla = Karaayak dili
language-name-bm = Bambara
language-name-bn = Bengalce
language-name-bo = Tibetçe
language-name-bpy = Bishnupriya
language-name-bqi = Bahtiyari
language-name-br = Bretonca
language-name-bra = Braj
language-name-brh = Brohice
language-name-brx = Bodo
language-name-bs = Boşnakça
language-name-bss = Akoose
language-name-bua = Buryatça
language-name-bug = Bugis
language-name-bum = Bulu
language-name-byn = Blin
language-name-byv = Medumba
language-name-ca = Katalanca
language-name-cad = Kado dili
language-name-car = Carib
language-name-cay = Kayuga dili
language-name-cch = Atsam
language-name-ce = Çeçence
language-name-ceb = Sebuano dili
language-name-cgg = Kigaca
language-name-ch = Çamorro dili
language-name-chb = Çibça dili
language-name-chg = Çağatayca
language-name-chk = Chuukese
language-name-chm = Mari dili
language-name-chn = Çinuk dili
language-name-cho = Çoktav dili
language-name-chp = Çipevya dili
language-name-chr = Çerokice
language-name-chy = Şayence
language-name-ckb = Orta Kürtçe
language-name-co = Korsikaca
language-name-cop = Kıptice
language-name-cps = Capiznon
language-name-cr = Krice
language-name-crh = Kırım Türkçesi
language-name-crs = Seselwa Kreole Fransızcası
language-name-cs = Çekçe
language-name-csb = Kashubian
language-name-cu = Kilise Slavcası
language-name-cv = Çuvaşça
language-name-cy = Galce
language-name-da = Danca
language-name-dak = Dakotaca
language-name-dar = Dargince
language-name-dav = Taita
language-name-de = Almanca
language-name-de_AT = Avusturya Almancası
language-name-de_CH = İsviçre Yüksek Almancası
language-name-del = Delaware
language-name-den = Slavey dili
language-name-dgr = Dogrib
language-name-din = Dinka dili
language-name-dje = Zarma
language-name-doi = Dogri
language-name-dsb = Aşağı Sorbça
language-name-dtp = Orta Kadazan
language-name-dua = Duala
language-name-dum = Ortaçağ Felemenkçesi
language-name-dv = Divehi dili
language-name-dyo = Jola-Fonyi
language-name-dyu = Dyula
language-name-dz = Dzongkha
language-name-dzg = Dazaga
language-name-ebu = Embu
language-name-ee = Ewe
language-name-efi = Efik
language-name-egl = Emilia Dili
language-name-egy = Eski Mısır Dili
language-name-eka = Ekajuk
language-name-el = Yunanca
language-name-elx = Elam
language-name-en = İngilizce
language-name-en_AU = Avustralya İngilizcesi
language-name-en_CA = Kanada İngilizcesi
language-name-en_GB = İngiliz İngilizcesi
language-name-en_US = Amerikan İngilizcesi
language-name-enm = Ortaçağ İngilizcesi
language-name-eo = Esperanto
language-name-es = İspanyolca
language-name-es_419 = Latin Amerika İspanyolcası
language-name-es_ES = Avrupa İspanyolcası
language-name-es_MX = Meksika İspanyolcası
language-name-esu = Merkezi Yupikçe
language-name-et = Estonca
language-name-eu = Baskça
language-name-ewo = Ewondo
language-name-ext = Ekstremadura Dili
language-name-fa = Farsça
language-name-fan = Fang
language-name-fat = Fanti
language-name-ff = Fula dili
language-name-fi = Fince
language-name-fil = Filipince
language-name-fit = Tornedalin Fincesi
language-name-fj = Fiji Dili
language-name-fo = Faroe Dili
language-name-fon = Fon
language-name-fr = Fransızca
language-name-fr_CA = Kanada Fransızcası
language-name-fr_CH = İsviçre Fransızcası
language-name-frc = Cajun Fransızcası
language-name-frm = Ortaçağ Fransızcası
language-name-fro = Eski Fransızca
language-name-frp = Arpitanca
language-name-frr = Kuzey Frizce
language-name-frs = Doğu Frizcesi
language-name-fur = Friuli dili
language-name-fy = Batı Frizcesi
language-name-ga = İrlandaca
language-name-gaa = Ga dili
language-name-gag = Gagavuzca
language-name-gan = Gan Çincesi
language-name-gay = Gayo dili
language-name-gba = Gbaya
language-name-gbz = Zerdüşt Daricesi
language-name-gd = İskoç Gaelcesi
language-name-gez = Geez
language-name-gil = Kiribatice
language-name-gl = Galiçyaca
language-name-glk = Gilanice
language-name-gmh = Ortaçağ Yüksek Almancası
language-name-gn = Guarani dili
language-name-goh = Eski Yüksek Almanca
language-name-gom = Goa Konkanicesi
language-name-gon = Gondi dili
language-name-gor = Gorontalo dili
language-name-got = Gotça
language-name-grb = Grebo dili
language-name-grc = Antik Yunanca
language-name-gsw = İsviçre Almancası
language-name-gu = Güceratça
language-name-guc = Wayuu dili
language-name-gur = Frafra
language-name-guz = Gusii
language-name-gv = Man dili
language-name-gwi = Guçince
language-name-ha = Hausa dili
language-name-hai = Haydaca
language-name-hak = Hakka Çincesi
language-name-haw = Hawaii dili
language-name-he = İbranice
language-name-hi = Hintçe
language-name-hif = Fiji Hintçesi
language-name-hil = Hiligaynon dili
language-name-hit = Hititçe
language-name-hmn = Hmong
language-name-ho = Hiri Motu
language-name-hr = Hırvatça
language-name-hsb = Yukarı Sorbça
language-name-hsn = Xiang Çincesi
language-name-ht = Haiti Kreyolu
language-name-hu = Macarca
language-name-hup = Hupaca
language-name-hy = Ermenice
language-name-hz = Herero dili
language-name-ia = Interlingua
language-name-iba = Iban
language-name-ibb = İbibio dili
language-name-id = Endonezce
language-name-ie = Interlingue
language-name-ig = İbo dili
language-name-ii = Sichuan Yi
language-name-ik = İnyupikçe
language-name-ilo = Iloko
language-name-inh = İnguşça
language-name-io = Ido
language-name-is = İzlandaca
language-name-it = İtalyanca
language-name-iu = İnuktitut dili
language-name-izh = İngriya Dili
language-name-ja = Japonca
language-name-jam = Jamaika Patois Dili
language-name-jbo = Lojban
language-name-jgo = Ngomba
language-name-jmc = Machame
language-name-jpr = Yahudi Farsçası
language-name-jrb = Yahudi Arapçası
language-name-jut = Yutland Dili
language-name-jv = Cava Dili
language-name-ka = Gürcüce
language-name-kaa = Karakalpakça
language-name-kab = Kabiliyece
language-name-kac = Kaçin dili
language-name-kaj = Jju
language-name-kam = Kamba
language-name-kaw = Kawi
language-name-kbd = Kabardeyce
language-name-kbl = Kanembu
language-name-kcg = Tyap
language-name-kde = Makonde
language-name-kea = Kabuverdianu
language-name-ken = Kenyang
language-name-kfo = Koro
language-name-kg = Kongo dili
language-name-kgp = Kaingang
language-name-kha = Khasi dili
language-name-kho = Hotanca
language-name-khq = Koyra Chiini
language-name-khw = Çitral Dili
language-name-ki = Kikuyu
language-name-kiu = Kırmançça
language-name-kj = Kuanyama
language-name-kk = Kazakça
language-name-kkj = Kako
language-name-kl = Grönland dili
language-name-kln = Kalenjin
language-name-km = Khmer dili
language-name-kmb = Kimbundu
language-name-kn = Kannada dili
language-name-ko = Korece
language-name-koi = Komi-Permyak
language-name-kok = Konkani dili
language-name-kos = Kosraean
language-name-kpe = Kpelle dili
language-name-kr = Kanuri dili
language-name-krc = Karaçay-Balkarca
language-name-kri = Krio
language-name-krj = Kinaray-a
language-name-krl = Karelyaca
language-name-kru = Kurukh dili
language-name-ks = Keşmir dili
language-name-ksb = Shambala
language-name-ksf = Bafia
language-name-ksh = Köln lehçesi
language-name-ku = Kürtçe
language-name-kum = Kumukça
language-name-kut = Kutenai dili
language-name-kv = Komi
language-name-kw = Kernevekçe
language-name-ky = Kırgızca
language-name-la = Latince
language-name-lad = Ladino
language-name-lag = Langi
language-name-lah = Lahnda
language-name-lam = Lamba dili
language-name-lb = Lüksemburgca
language-name-lez = Lezgice
language-name-lfn = Lingua Franca Nova
language-name-lg = Ganda
language-name-li = Limburgca
language-name-lij = Ligurca
language-name-liv = Livonca
language-name-lkt = Lakotaca
language-name-lmo = Lombardça
language-name-ln = Lingala
language-name-lo = Lao dili
language-name-lol = Mongo
language-name-lou = Louisiana Kreolcesi
language-name-loz = Lozi
language-name-lrc = Kuzey Luri
language-name-lt = Litvanca
language-name-ltg = Latgalian
language-name-lu = Luba-Katanga
language-name-lua = Luba-Lulua
language-name-lui = Luiseno
language-name-lun = Lunda
language-name-luo = Luo
language-name-lus = Lushai
language-name-luy = Luyia
language-name-lv = Letonca
language-name-lzh = Edebi Çince
language-name-lzz = Lazca
language-name-mad = Madura Dili
language-name-maf = Mafa
language-name-mag = Magahi
language-name-mai = Maithili
language-name-mak = Makasar
language-name-man = Mandingo
language-name-mas = Masai
language-name-mde = Maba
language-name-mdf = Mokşa dili
language-name-mdr = Mandar
language-name-men = Mende dili
language-name-mer = Meru
language-name-mfe = Morisyen
language-name-mg = Malgaşça
language-name-mga = Ortaçağ İrlandacası
language-name-mgh = Makhuwa-Meetto
language-name-mgo = Meta’
language-name-mh = Marshall Adaları dili
language-name-mi = Maori dili
language-name-mic = Micmac
language-name-min = Minangkabau
language-name-mk = Makedonca
language-name-ml = Malayalam dili
language-name-mn = Moğolca
language-name-mnc = Mançurya dili
language-name-mni = Manipuri dili
language-name-moh = Mohavk dili
language-name-mos = Mossi
language-name-mr = Marathi dili
language-name-mrj = Ova Çirmişçesi
language-name-ms = Malayca
language-name-mt = Maltaca
language-name-mua = Mundang
language-name-mul = Birden Fazla Dil
language-name-mus = Krikçe
language-name-mwl = Miranda dili
language-name-mwr = Marvari
language-name-mwv = Mentawai
language-name-my = Birman dili
language-name-mye = Myene
language-name-myv = Erzya
language-name-mzn = Mazenderanca
language-name-na = Nauru dili
language-name-nan = Min Nan Çincesi
language-name-nap = Napolice
language-name-naq = Nama
language-name-nb = Norveççe Bokmål
language-name-nd = Kuzey Ndebele
language-name-nds = Aşağı Almanca
language-name-nds_NL = Aşağı Saksonca
language-name-ne = Nepalce
language-name-new = Nevari
language-name-ng = Ndonga
language-name-nia = Nias
language-name-niu = Niue dili
language-name-njo = Ao Naga
language-name-nl = Felemenkçe
language-name-nl_BE = Flamanca
language-name-nmg = Kwasio
language-name-nn = Norveççe Nynorsk
language-name-nnh = Ngiemboon
language-name-no = Norveççe
language-name-nog = Nogayca
language-name-non = Eski Nors dili
language-name-nov = Novial
language-name-nqo = N’Ko
language-name-nr = Güney Ndebele
language-name-nso = Kuzey Sotho dili
language-name-nus = Nuer
language-name-nv = Navaho dili
language-name-nwc = Klasik Nevari
language-name-ny = Nyanja
language-name-nym = Nyamvezi
language-name-nyn = Nyankole
language-name-nyo = Nyoro
language-name-nzi = Nzima dili
language-name-oc = Oksitan dili
language-name-oj = Ojibva dili
language-name-om = Oromo dili
language-name-or = Oriya Dili
language-name-os = Osetçe
language-name-osa = Osage
language-name-ota = Osmanlı Türkçesi
language-name-pa = Pencapça
language-name-pag = Pangasinan dili
language-name-pal = Pehlevi Dili
language-name-pam = Pampanga
language-name-pap = Papiamento
language-name-pau = Palau dili
language-name-pcd = Picard Dili
language-name-pcm = Nijerya Pidgin dili
language-name-pdc = Pensilvanya Almancası
language-name-pdt = Plautdietsch
language-name-peo = Eski Farsça
language-name-pfl = Palatin Almancası
language-name-phn = Fenike dili
language-name-pi = Pali
language-name-pl = Lehçe
language-name-pms = Piyemontece
language-name-pnt = Kuzeybatı Kafkasya
language-name-pon = Pohnpeian
language-name-prg = Prusyaca
language-name-pro = Eski Provensal
language-name-ps = Peştuca
language-name-pt = Portekizce
language-name-pt_BR = Brezilya Portekizcesi
language-name-pt_PT = Avrupa Portekizcesi
language-name-qu = Keçuva dili
language-name-quc = Kiçece
language-name-qug = Chimborazo Highland Quichua
language-name-raj = Rajasthani
language-name-rap = Rapanui dili
language-name-rar = Rarotongan
language-name-rgn = Romanyolca
language-name-rif = Rif Berbericesi
language-name-rm = Romanşça
language-name-rn = Kirundi
language-name-ro = Rumence
language-name-ro_MD = Moldovaca
language-name-rof = Rombo
language-name-rom = Romanca
language-name-root = Köken
language-name-rtm = Rotuman
language-name-ru = Rusça
language-name-rue = Rusince
language-name-rug = Roviana
language-name-rup = Ulahça
language-name-rw = Kinyarwanda
language-name-rwk = Rwa
language-name-sa = Sanskrit
language-name-sad = Sandave
language-name-sah = Yakutça
language-name-sam = Samarit Aramcası
language-name-saq = Samburu
language-name-sas = Sasak
language-name-sat = Santali
language-name-saz = Saurashtra
language-name-sba = Ngambay
language-name-sbp = Sangu
language-name-sc = Sardunya dili
language-name-scn = Sicilyaca
language-name-sco = İskoçça
language-name-sd = Sindhi dili
language-name-sdc = Sassari Sarduca
language-name-sdh = Güney Kürtçesi
language-name-se = Kuzey Laponcası
language-name-see = Seneca dili
language-name-seh = Sena
language-name-sei = Seri
language-name-sel = Selkup dili
language-name-ses = Koyraboro Senni
language-name-sg = Sango
language-name-sga = Eski İrlandaca
language-name-sgs = Samogitçe
language-name-sh = Sırp-Hırvat Dili
language-name-shi = Taşelhit
language-name-shn = Shan dili
language-name-shu = Çad Arapçası
language-name-si = Sinhali dili
language-name-sid = Sidamo dili
language-name-sk = Slovakça
language-name-sl = Slovence
language-name-sli = Aşağı Silezyaca
language-name-sly = Selayar
language-name-sm = Samoa dili
language-name-sma = Güney Laponcası
language-name-smj = Lule Laponcası
language-name-smn = İnari Laponcası
language-name-sms = Skolt Laponcası
language-name-sn = Shona
language-name-snk = Soninke
language-name-so = Somalice
language-name-sog = Sogdiana Dili
language-name-sq = Arnavutça
language-name-sr = Sırpça
language-name-srn = Sranan Tongo
language-name-srr = Serer dili
language-name-ss = Sisvati
language-name-ssy = Saho
language-name-st = Güney Sotho dili
language-name-stq = Saterland Frizcesi
language-name-su = Sunda Dili
language-name-suk = Sukuma dili
language-name-sus = Susu
language-name-sux = Sümerce
language-name-sv = İsveççe
language-name-sw = Svahili dili
language-name-sw_CD = Kongo Svahili
language-name-swb = Komorca
language-name-syc = Klasik Süryanice
language-name-syr = Süryanice
language-name-szl = Silezyaca
language-name-ta = Tamilce
language-name-tcy = Tuluca
language-name-te = Telugu dili
language-name-tem = Timne
language-name-teo = Teso
language-name-ter = Tereno
language-name-tet = Tetum
language-name-tg = Tacikçe
language-name-th = Tayca
language-name-ti = Tigrinya dili
language-name-tig = Tigre
language-name-tiv = Tiv
language-name-tk = Türkmence
language-name-tkl = Tokelau dili
language-name-tkr = Sahurca
language-name-tl = Tagalogca
language-name-tlh = Klingonca
language-name-tli = Tlingit
language-name-tly = Talışça
language-name-tmh = Tamaşek
language-name-tn = Setsvana
language-name-to = Tonga dili
language-name-tog = Nyasa Tonga
language-name-tpi = Tok Pisin
language-name-tr = Türkçe
language-name-tru = Turoyo
language-name-trv = Taroko
language-name-ts = Tsonga
language-name-tsd = Tsakonca
language-name-tsi = Tsimshian
language-name-tt = Tatarca
language-name-ttt = Tatça
language-name-tum = Tumbuka
language-name-tvl = Tuvalyanca
language-name-tw = Tvi
language-name-twq = Tasawaq
language-name-ty = Tahiti dili
language-name-tyv = Tuvaca
language-name-tzm = Orta Atlas Tamazigti
language-name-udm = Udmurtça
language-name-ug = Uygurca
language-name-uga = Ugarit dili
language-name-uk = Ukraynaca
language-name-umb = Umbundu
language-name-und = Bilinmeyen Dil
language-name-ur = Urduca
language-name-uz = Özbekçe
language-name-vai = Vai
language-name-ve = Venda dili
language-name-vec = Venedikçe
language-name-vep = Veps dili
language-name-vi = Vietnamca
language-name-vls = Batı Flamanca
language-name-vmf = Main Frankonya Dili
language-name-vo = Volapük
language-name-vot = Votça
language-name-vro = Võro
language-name-vun = Vunjo
language-name-wa = Valonca
language-name-wae = Walser
language-name-wal = Valamo
language-name-war = Varay
language-name-was = Vaşo
language-name-wbp = Warlpiri
language-name-wo = Volofça
language-name-wuu = Wu Çincesi
language-name-xal = Kalmıkça
language-name-xh = Zosa dili
language-name-xmf = Megrelce
language-name-xog = Soga
language-name-yao = Yao
language-name-yap = Yapça
language-name-yav = Yangben
language-name-ybb = Yemba
language-name-yi = Yidiş
language-name-yo = Yorubaca
language-name-yrl = Nheengatu
language-name-yue = Kantonca
language-name-za = Zhuangca
language-name-zap = Zapotek dili
language-name-zbl = Blis Sembolleri
language-name-zea = Zelandaca
language-name-zen = Zenaga dili
language-name-zgh = Standart Fas Tamazigti
language-name-zh = Çince
language-name-zh_Hans = Basitleştirilmiş Çince
language-name-zh_Hant = Geleneksel Çince
language-name-zu = Zuluca
language-name-zun = Zunice
language-name-zxx = Dilbilim içeriği yok
language-name-zza = Zazaca
