language-name-ab = Abčasiš
language-name-af = Afrikáns
language-name-am = Amhariš
language-name-ar = Arabiš
language-name-as = Assamesiš
language-name-ay = Aymara
language-name-az = Serbaidšaniš
language-name-be = Wísrussiš
language-name-bg = Bulgariš
language-name-bn = Bengališ
language-name-bo = Tibetiš
language-name-bs = Bosniš
language-name-ca = Katalaniš
language-name-cs = Tšečiš
language-name-cy = Walisiš
language-name-da = Däniš
language-name-de = Titš
language-name-de_AT = Öštričišes Titš
language-name-de_CH = Schwizer Hočtitš
language-name-dv = Malediwiš
language-name-dz = Butaniš
language-name-efi = Efik
language-name-el = Gričiš
language-name-en = Engliš
language-name-en_AU = Auštrališes Engliš
language-name-en_CA = Kanadišes Engliš
language-name-en_GB = Britišes Engliš
language-name-en_US = Amerikanišes Engliš
language-name-es = Schpaniš
language-name-es_419 = Latiamerikanišes Schpaniš
language-name-es_ES = Iberišes Schpaniš
language-name-et = Estniš
language-name-eu = Baskiš
language-name-fa = Persiš
language-name-fi = Finiš
language-name-fil = Filipiniš
language-name-fj = Fidšianiš
language-name-fr = Wälš
language-name-fr_CA = Kanadišes Wälš
language-name-fr_CH = Schwizer Wälš
language-name-ga = Iriš
language-name-gl = Galiziš
language-name-gn = Guarani
language-name-gu = Gujarati
language-name-ha = Hausa
language-name-haw = Hawaíaniš
language-name-he = Hebräiš
language-name-hi = Hindi
language-name-hr = Kroatiš
language-name-ht = Haitianiš
language-name-hu = Ungariš
language-name-hy = Armeniš
language-name-id = Indonesiš
language-name-ig = Igbo
language-name-is = Iisländiš
language-name-it = Italieniš
language-name-ja = Japaniš
language-name-ka = Georgiš
language-name-kk = Kazačiš
language-name-km = Kambodšaniš
language-name-kn = Kannada
language-name-ko = Koreaniš
language-name-ks = Kašmiriš
language-name-ku = Kurdiš
language-name-ky = Kirgisiš
language-name-la = Latiniš
language-name-lb = Luxemburgiš
language-name-ln = Lingala
language-name-lo = Laotiš
language-name-lt = Litauiš
language-name-lv = Lettiš
language-name-mg = Malagási
language-name-mi = Maori
language-name-mk = Mazedoniš
language-name-ml = Malayalam
language-name-mn = Mongoliš
language-name-mr = Marathi
language-name-ms = Malaíš
language-name-mt = Maltesiš
language-name-my = Burmesiš
language-name-nb = Norwegiš Bokmål
language-name-nd = Nordndebele
language-name-ne = Nepalesiš
language-name-nl = Holändiš
language-name-nl_BE = Flämiš
language-name-nn = Norwegiš Nynorsk
language-name-nso = Nordsotho
language-name-ny = Nyanja
language-name-or = Oriya
language-name-os = Osétiš
language-name-pa = Pandšabiš
language-name-pl = Polniš
language-name-ps = Paštu
language-name-pt = Portugisiš
language-name-pt_BR = Brasilianišes Portugisiš
language-name-pt_PT = Iberišes Portugisiš
language-name-qu = Quečua
language-name-rm = Rätromaniš
language-name-rn = Rundi
language-name-ro = Rumäniš
language-name-ru = Rusiš
language-name-rw = Ruandiš
language-name-sa = Sanskrit
language-name-sah = Jakutiš
language-name-sd = Sindhi
language-name-se = Nordsamiš
language-name-sg = Sango
language-name-si = Singalesiš
language-name-sk = Slowakiš
language-name-sl = Sloweniš
language-name-sm = Samoaniš
language-name-sn = Shona
language-name-so = Somališ
language-name-sq = Albaniš
language-name-sr = Serbiš
language-name-ss = Swazi
language-name-st = Südsotho
language-name-su = Sundanesiš
language-name-sv = Schwediš
language-name-sw = Suaheliš
language-name-ta = Tamiliš
language-name-te = Telugu
language-name-tet = Tetum
language-name-tg = Tadšikiš
language-name-th = Thailändiš
language-name-ti = Tigrinja
language-name-tk = Turkmeniš
language-name-tn = Tswana
language-name-to = Tonga
language-name-tpi = Niwmelanesiš
language-name-tr = Türkiš
language-name-ts = Tsonga
language-name-ty = Taitiš
language-name-ug = Uiguriš
language-name-uk = Ukrainiš
language-name-und = Unbekannti Schprač
language-name-ur = Urdu
language-name-uz = Usbekiš
language-name-ve = Venda
language-name-vi = Vietnamesiš
language-name-wae = Walser
language-name-wo = Wolof
language-name-xh = Xhosa
language-name-yo = Yoruba
language-name-zh = Chinesiš
language-name-zh_Hans = Vereifačts Chinesiš
language-name-zh_Hant = Traditionells Chinesiš
language-name-zu = Zulu
