language-name-aa = ಅಫಾರ್
language-name-ab = ಅಬ್ಖಾಜಿಯನ್
language-name-ace = ಅಛಿನೀಸ್
language-name-ach = ಅಕೋಲಿ
language-name-ada = ಅಡಂಗ್ಮೆ
language-name-ady = ಅಡೈಘೆ
language-name-ae = ಅವೆಸ್ಟನ್
language-name-af = ಆಫ್ರಿಕಾನ್ಸ್
language-name-afh = ಆಫ್ರಿಹಿಲಿ
language-name-agq = ಅಘೆಮ್
language-name-ain = ಐನು
language-name-ak = ಅಕಾನ್
language-name-akk = ಅಕ್ಕಾಡಿಯನ್
language-name-ale = ಅಲೆಯುಟ್
language-name-alt = ದಕ್ಷಿಣ ಅಲ್ಟಾಯ್
language-name-am = ಅಂಹರಿಕ್
language-name-an = ಅರಗೊನೀಸ್
language-name-ang = ಪ್ರಾಚೀನ ಇಂಗ್ಲೀಷ್
language-name-anp = ಆಂಗಿಕಾ
language-name-ar = ಅರೇಬಿಕ್
language-name-ar_001 = ಆಧುನಿಕ ಪ್ರಮಾಣಿತ ಅರೇಬಿಕ್
language-name-arc = ಅರಾಮಿಕ್
language-name-arn = ಮಪುಚೆ
language-name-arp = ಅರಪಾಹೋ
language-name-arw = ಅರಾವಾಕ್
language-name-as = ಅಸ್ಸಾಮೀಸ್
language-name-asa = ಅಸು
language-name-ast = ಆಸ್ಟುರಿಯನ್
language-name-av = ಅವರಿಕ್
language-name-awa = ಅವಧಿ
language-name-ay = ಅಯ್ಮಾರಾ
language-name-az = ಅಜೆರ್ಬೈಜಾನಿ
language-name-ba = ಬಶ್ಕಿರ್
language-name-bal = ಬಲೂಚಿ
language-name-ban = ಬಲಿನೀಸ್
language-name-bas = ಬಸಾ
language-name-be = ಬೆಲರೂಸಿಯನ್
language-name-bej = ಬೇಜಾ
language-name-bem = ಬೆಂಬಾ
language-name-bez = ಬೆನ
language-name-bg = ಬಲ್ಗೇರಿಯನ್
language-name-bgn = ಪಶ್ಚಿಮ ಬಲೊಚಿ
language-name-bho = ಭೋಜಪುರಿ
language-name-bi = ಬಿಸ್ಲಾಮಾ
language-name-bik = ಬಿಕೊಲ್
language-name-bin = ಬಿನಿ
language-name-bla = ಸಿಕ್ಸಿಕಾ
language-name-bm = ಬಂಬಾರಾ
language-name-bn = ಬಾಂಗ್ಲಾ
language-name-bo = ಟಿಬೇಟಿಯನ್
language-name-br = ಬ್ರೆಟನ್
language-name-bra = ಬ್ರಜ್
language-name-brx = ಬೋಡೊ
language-name-bs = ಬೋಸ್ನಿಯನ್
language-name-bua = ಬುರಿಯಟ್
language-name-bug = ಬುಗಿನೀಸ್
language-name-byn = ಬ್ಲಿನ್
language-name-ca = ಕೆಟಲಾನ್
language-name-cad = ಕ್ಯಾಡ್ಡೋ
language-name-car = ಕಾರಿಬ್
language-name-cch = ಅಟ್ಸಮ್
language-name-ce = ಚೆಚನ್
language-name-ceb = ಸೆಬುವಾನೊ
language-name-cgg = ಚಿಗಾ
language-name-ch = ಕಮೊರೊ
language-name-chb = ಚಿಬ್ಚಾ
language-name-chg = ಚಗಟಾಯ್
language-name-chk = ಚೂಕಿಸೆ
language-name-chm = ಮಾರಿ
language-name-chn = ಚಿನೂಕ್ ಜಾರ್ಗೋನ್
language-name-cho = ಚೋಕ್ಟಾವ್
language-name-chp = ಚಿಪೆವ್ಯಾನ್
language-name-chr = ಚೆರೋಕಿ
language-name-chy = ಚೀಯೆನ್ನೇ
language-name-ckb = ಮಧ್ಯ ಕುರ್ದಿಶ್
language-name-co = ಕೋರ್ಸಿಕನ್
language-name-cop = ಕೊಪ್ಟಿಕ್
language-name-cr = ಕ್ರೀ
language-name-crh = ಕ್ರಿಮೀಯನ್ ಟರ್ಕಿಷ್
language-name-crs = ಸೆಸೆಲ್ವಾ ಕ್ರಯೋಲ್ ಫ್ರೆಂಚ್
language-name-cs = ಜೆಕ್
language-name-csb = ಕಶುಬಿಯನ್
language-name-cu = ಚರ್ಚ್ ಸ್ಲಾವಿಕ್
language-name-cv = ಚುವಾಶ್
language-name-cy = ವೆಲ್ಶ್
language-name-da = ಡ್ಯಾನಿಶ್
language-name-dak = ಡಕೋಟಾ
language-name-dar = ದರ್ಗ್ವಾ
language-name-dav = ಟೈಟ
language-name-de = ಜರ್ಮನ್
language-name-de_AT = ಆಸ್ಟ್ರಿಯನ್ ಜರ್ಮನ್
language-name-de_CH = ಸ್ವಿಸ್ ಹೈ ಜರ್ಮನ್
language-name-del = ಡೆಲಾವೇರ್
language-name-den = ಸ್ಲೇವ್
language-name-dgr = ಡೋಗ್ರಿಬ್
language-name-din = ಡಿಂಕಾ
language-name-dje = ಜರ್ಮಾ
language-name-doi = ಡೋಗ್ರಿ
language-name-dsb = ಲೋವರ್ ಸೋರ್ಬಿಯನ್
language-name-dua = ಡುವಾಲಾ
language-name-dum = ಮಧ್ಯ ಡಚ್
language-name-dv = ದಿವೆಹಿ
language-name-dyo = ಜೊಲ-ಫೊನ್ಯಿ
language-name-dyu = ಡ್ಯೂಲಾ
language-name-dz = ಜೋಂಗ್‌ಖಾ
language-name-dzg = ಡಜಾಗ
language-name-ebu = ಎಂಬು
language-name-ee = ಈವ್
language-name-efi = ಎಫಿಕ್
language-name-egy = ಪ್ರಾಚೀನ ಈಜಿಪ್ಟಿಯನ್
language-name-eka = ಎಕಾಜುಕ್
language-name-el = ಗ್ರೀಕ್
language-name-elx = ಎಲಾಮೈಟ್
language-name-en = ಇಂಗ್ಲಿಷ್
language-name-en_AU = ಆಸ್ಟ್ರೇಲಿಯನ್ ಇಂಗ್ಲಿಷ್
language-name-en_CA = ಕೆನೆಡಿಯನ್ ಇಂಗ್ಲಿಷ್
language-name-en_GB = ಬ್ರಿಟಿಷ್ ಇಂಗ್ಲಿಷ್
language-name-en_US = ಅಮೆರಿಕನ್ ಇಂಗ್ಲಿಷ್
language-name-enm = ಮಧ್ಯ ಇಂಗ್ಲೀಷ್
language-name-eo = ಎಸ್ಪೆರಾಂಟೊ
language-name-es = ಸ್ಪ್ಯಾನಿಷ್
language-name-es_419 = ಲ್ಯಾಟಿನ್ ಅಮೇರಿಕನ್ ಸ್ಪ್ಯಾನಿಷ್
language-name-es_ES = ಯುರೋಪಿಯನ್ ಸ್ಪ್ಯಾನಿಷ್
language-name-es_MX = ಮೆಕ್ಸಿಕನ್ ಸ್ಪ್ಯಾನಿಷ್
language-name-et = ಎಸ್ಟೊನಿಯನ್
language-name-eu = ಬಾಸ್ಕ್
language-name-ewo = ಇವಾಂಡೋ
language-name-fa = ಪರ್ಶಿಯನ್
language-name-fan = ಫಾಂಗ್
language-name-fat = ಫಾಂಟಿ
language-name-ff = ಫುಲಾ
language-name-fi = ಫಿನ್ನಿಶ್
language-name-fil = ಫಿಲಿಪಿನೊ
language-name-fj = ಫಿಜಿಯನ್
language-name-fo = ಫರೋಸಿ
language-name-fon = ಫೋನ್
language-name-fr = ಫ್ರೆಂಚ್
language-name-fr_CA = ಕೆನೆಡಿಯನ್ ಫ್ರೆಂಚ್
language-name-fr_CH = ಸ್ವಿಸ್ ಫ್ರೆಂಚ್
language-name-frc = ಕಾಜುನ್ ಫ್ರೆಂಚ್
language-name-frm = ಮಧ್ಯ ಫ್ರೆಂಚ್
language-name-fro = ಪ್ರಾಚೀನ ಫ್ರೆಂಚ್
language-name-frr = ಉತ್ತರ ಫ್ರಿಸಿಯನ್
language-name-frs = ಪೂರ್ವ ಫ್ರಿಸಿಯನ್
language-name-fur = ಫ್ರಿಯುಲಿಯನ್
language-name-fy = ಪಶ್ಚಿಮ ಫ್ರಿಸಿಯನ್
language-name-ga = ಐರಿಷ್
language-name-gaa = ಗ
language-name-gag = ಗಗೌಜ್
language-name-gan = ಗಾನ್ ಚೀನೀಸ್
language-name-gay = ಗಾಯೋ
language-name-gba = ಗ್ಬಾಯಾ
language-name-gd = ಸ್ಕಾಟಿಶ್ ಗೆಲಿಕ್
language-name-gez = ಗೀಝ್
language-name-gil = ಗಿಲ್ಬರ್ಟೀಸ್
language-name-gl = ಗ್ಯಾಲಿಶಿಯನ್
language-name-gmh = ಮಧ್ಯ ಹೈ ಜರ್ಮನ್
language-name-gn = ಗೌರಾನಿ
language-name-goh = ಪ್ರಾಚೀನ ಹೈ ಜರ್ಮನ್
language-name-gon = ಗೊಂಡಿ
language-name-gor = ಗೊರೊಂಟಾಲೋ
language-name-got = ಗೋಥಿಕ್
language-name-grb = ಗ್ರೇಬೋ
language-name-grc = ಪ್ರಾಚೀನ ಗ್ರೀಕ್
language-name-gsw = ಸ್ವಿಸ್ ಜರ್ಮನ್
language-name-gu = ಗುಜರಾತಿ
language-name-guz = ಗುಸಿ
language-name-gv = ಮ್ಯಾಂಕ್ಸ್
language-name-gwi = ಗ್ವಿಚ್‌ಇನ್
language-name-ha = ಹೌಸಾ
language-name-hai = ಹೈಡಾ
language-name-hak = ಹಕ್
language-name-haw = ಹವಾಯಿಯನ್
language-name-he = ಹೀಬ್ರೂ
language-name-hi = ಹಿಂದಿ
language-name-hil = ಹಿಲಿಗೇನನ್
language-name-hit = ಹಿಟ್ಟಿಟೆ
language-name-hmn = ಮೋಂಗ್
language-name-ho = ಹಿರಿ ಮೊಟು
language-name-hr = ಕ್ರೊಯೇಶಿಯನ್
language-name-hsb = ಅಪ್ಪರ್ ಸರ್ಬಿಯನ್
language-name-hsn = ಶಯಾಂಗ್ ಚೀನೀಸೇ
language-name-ht = ಹೈಟಿಯನ್ ಕ್ರಿಯೋಲಿ
language-name-hu = ಹಂಗೇರಿಯನ್
language-name-hup = ಹೂಪಾ
language-name-hy = ಅರ್ಮೇನಿಯನ್
language-name-hz = ಹೆರೆರೊ
language-name-ia = ಇಂಟರ್‌ಲಿಂಗ್ವಾ
language-name-iba = ಇಬಾನ್
language-name-ibb = ಇಬಿಬಿಯೋ
language-name-id = ಇಂಡೋನೇಶಿಯನ್
language-name-ie = ಇಂಟರ್ಲಿಂಗ್
language-name-ig = ಇಗ್ಬೊ
language-name-ii = ಸಿಚುಅನ್ ಯಿ
language-name-ik = ಇನುಪಿಯಾಕ್
language-name-ilo = ಇಲ್ಲಿಕೋ
language-name-inh = ಇಂಗುಷ್
language-name-io = ಇಡೊ
language-name-is = ಐಸ್‌ಲ್ಯಾಂಡಿಕ್
language-name-it = ಇಟಾಲಿಯನ್
language-name-iu = ಇನುಕ್ಟಿಟುಟ್
language-name-ja = ಜಾಪನೀಸ್
language-name-jbo = ಲೊಜ್ಬಾನ್
language-name-jgo = ನೊಂಬಾ
language-name-jmc = ಮ್ಯಕಮೆ
language-name-jpr = ಜೂಡಿಯೋ-ಪರ್ಶಿಯನ್
language-name-jrb = ಜೂಡಿಯೋ-ಅರೇಬಿಕ್
language-name-jv = ಜಾವಾನೀಸ್
language-name-ka = ಜಾರ್ಜಿಯನ್
language-name-kaa = ಕಾರಾ-ಕಲ್ಪಾಕ್
language-name-kab = ಕಬೈಲ್
language-name-kac = ಕಚಿನ್
language-name-kaj = ಜ್ಜು
language-name-kam = ಕಂಬಾ
language-name-kaw = ಕಾವಿ
language-name-kbd = ಕಬರ್ಡಿಯನ್
language-name-kcg = ಟ್ಯಾಪ್
language-name-kde = ಮ್ಯಾಕೊಂಡ್
language-name-kea = ಕಬುವೆರ್ಡಿಯನು
language-name-kfo = ಕೋರೋ
language-name-kg = ಕಾಂಗೋ
language-name-kha = ಖಾಸಿ
language-name-kho = ಖೋಟಾನೀಸ್
language-name-khq = ಕೊಯ್ರ ಚೀನಿ
language-name-ki = ಕಿಕುಯು
language-name-kj = ಕ್ವಾನ್‌ಯಾಮಾ
language-name-kk = ಕಝಕ್
language-name-kkj = ಕಾಕೊ
language-name-kl = ಕಲಾಲ್ಲಿಸುಟ್
language-name-kln = ಕಲೆಂಜಿನ್
language-name-km = ಖಮೇರ್
language-name-kmb = ಕಿಂಬುಂಡು
language-name-kn = ಕನ್ನಡ
language-name-ko = ಕೊರಿಯನ್
language-name-koi = ಕೋಮಿ-ಪರ್ಮ್ಯಕ್
language-name-kok = ಕೊಂಕಣಿ
language-name-kos = ಕೊಸರಿಯನ್
language-name-kpe = ಕಪೆಲ್ಲೆ
language-name-kr = ಕನುರಿ
language-name-krc = ಕರಚಯ್-ಬಲ್ಕಾರ್
language-name-krl = ಕರೇಲಿಯನ್
language-name-kru = ಕುರುಖ್
language-name-ks = ಕಾಶ್ಮೀರಿ
language-name-ksb = ಶಂಬಲ
language-name-ksf = ಬಫಿಯ
language-name-ksh = ಕಲೊಗ್ನಿಯನ್
language-name-ku = ಕುರ್ದಿಷ್
language-name-kum = ಕುಮೈಕ್
language-name-kut = ಕುಟೇನಾಯ್
language-name-kv = ಕೋಮಿ
language-name-kw = ಕಾರ್ನಿಷ್
language-name-ky = ಕಿರ್ಗಿಜ್
language-name-la = ಲ್ಯಾಟಿನ್
language-name-lad = ಲ್ಯಾಡಿನೋ
language-name-lag = ಲಾಂಗಿ
language-name-lah = ಲಹಂಡಾ
language-name-lam = ಲಂಬಾ
language-name-lb = ಲಕ್ಸಂಬರ್ಗಿಷ್
language-name-lez = ಲೆಜ್ಘಿಯನ್
language-name-lg = ಗಾಂಡಾ
language-name-li = ಲಿಂಬರ್ಗಿಶ್
language-name-lkt = ಲಕೊಟ
language-name-ln = ಲಿಂಗಾಲ
language-name-lo = ಲಾವೋ
language-name-lol = ಮೊಂಗೋ
language-name-lou = ಲೂಯಿಸಿಯಾನ ಕ್ರಿಯೋಲ್
language-name-loz = ಲೋಝಿ
language-name-lrc = ಉತ್ತರ ಲೂರಿ
language-name-lt = ಲಿಥುವೇನಿಯನ್
language-name-lu = ಲೂಬಾ-ಕಟಾಂಗಾ
language-name-lua = ಲುಬ-ಲುಲಾ
language-name-lui = ಲೂಯಿಸೆನೋ
language-name-lun = ಲುಂಡಾ
language-name-luo = ಲುವೋ
language-name-lus = ಮಿಝೋ
language-name-luy = ಲುಯಿಯ
language-name-lv = ಲಾಟ್ವಿಯನ್
language-name-mad = ಮದುರೀಸ್
language-name-mag = ಮಗಾಹಿ
language-name-mai = ಮೈಥಿಲಿ
language-name-mak = ಮಕಾಸರ್
language-name-man = ಮಂಡಿಂಗೊ
language-name-mas = ಮಸಾಯ್
language-name-mdf = ಮೋಕ್ಷ
language-name-mdr = ಮಂದಾರ್
language-name-men = ಮೆಂಡೆ
language-name-mer = ಮೆರು
language-name-mfe = ಮೊರಿಸನ್
language-name-mg = ಮಲಗಾಸಿ
language-name-mga = ಮಧ್ಯ ಐರಿಷ್
language-name-mgh = ಮ್ಯಖುವಾ- ಮೀಟ್ಟೊ
language-name-mgo = ಮೆಟಾ
language-name-mh = ಮಾರ್ಶಲ್ಲೀಸ್
language-name-mi = ಮಾವೋರಿ
language-name-mic = ಮಿಕ್‌ಮ್ಯಾಕ್
language-name-min = ಮಿನಂಗ್‌ಕಬಾವು
language-name-mk = ಮೆಸಿಡೋನಿಯನ್
language-name-ml = ಮಲಯಾಳಂ
language-name-mn = ಮಂಗೋಲಿಯನ್
language-name-mnc = ಮಂಚು
language-name-mni = ಮಣಿಪುರಿ
language-name-moh = ಮೊಹಾವ್ಕ್
language-name-mos = ಮೊಸ್ಸಿ
language-name-mr = ಮರಾಠಿ
language-name-ms = ಮಲಯ್
language-name-mt = ಮಾಲ್ಟೀಸ್
language-name-mua = ಮುಂಡಂಗ್
language-name-mul = ಬಹುಸಂಖ್ಯೆಯ ಭಾಷೆಗಳು
language-name-mus = ಕ್ರೀಕ್
language-name-mwl = ಮಿರಾಂಡೀಸ್
language-name-mwr = ಮಾರ್ವಾಡಿ
language-name-my = ಬರ್ಮೀಸ್
language-name-myv = ಎರ್ಝ್ಯಾ
language-name-mzn = ಮಜಂದೆರಾನಿ
language-name-na = ನೌರು
language-name-nan = ನಾನ್
language-name-nap = ನಿಯಾಪೊಲಿಟನ್
language-name-naq = ನಮ
language-name-nb = ನಾರ್ವೆಜಿಯನ್ ಬೊಕ್ಮಲ್
language-name-nd = ಉತ್ತರ ದೆಬೆಲೆ
language-name-nds = ಲೋ ಜರ್ಮನ್
language-name-nds_NL = ಲೋ ಸ್ಯಾಕ್ಸನ್
language-name-ne = ನೇಪಾಳಿ
language-name-new = ನೇವಾರೀ
language-name-ng = ಡೋಂಗಾ
language-name-nia = ನಿಯಾಸ್
language-name-niu = ನಿಯುವನ್
language-name-nl = ಡಚ್
language-name-nl_BE = ಫ್ಲೆಮಿಷ್
language-name-nmg = ಖ್ವಾಸಿಯೊ
language-name-nn = ನಾರ್ವೇಜಿಯನ್ ನೈನಾರ್ಸ್ಕ್
language-name-nnh = ನಿಂಬೂನ್
language-name-no = ನಾರ್ವೇಜಿಯನ್
language-name-nog = ನೊಗಾಯ್
language-name-non = ಪ್ರಾಚೀನ ನೋರ್ಸ್
language-name-nqo = ಎನ್‌ಕೋ
language-name-nr = ದಕ್ಷಿಣ ದೆಬೆಲೆ
language-name-nso = ಉತ್ತರ ಸೋಥೋ
language-name-nus = ನೂಯರ್
language-name-nv = ನವಾಜೊ
language-name-nwc = ಶಾಸ್ತ್ರೀಯ ನೇವಾರಿ
language-name-ny = ನ್ಯಾಂಜಾ
language-name-nym = ನ್ಯಾಮ್‌ವೆಂಜಿ
language-name-nyn = ನ್ಯಾನ್‌ಕೋಲೆ
language-name-nyo = ನ್ಯೋರೋ
language-name-nzi = ಜೀಮಾ
language-name-oc = ಒಸಿಟನ್
language-name-oj = ಒಜಿಬ್ವಾ
language-name-om = ಒರೊಮೊ
language-name-or = ಒಡಿಯ
language-name-os = ಒಸ್ಸೆಟಿಕ್
language-name-osa = ಓಸಾಜ್
language-name-ota = ಒಟ್ಟೋಮನ್ ತುರ್ಕಿಷ್
language-name-pa = ಪಂಜಾಬಿ
language-name-pag = ಪಂಗಾಸಿನನ್
language-name-pal = ಪಹ್ಲವಿ
language-name-pam = ಪಂಪಾಂಗಾ
language-name-pap = ಪಪಿಯಾಮೆಂಟೊ
language-name-pau = ಪಲುಆನ್
language-name-pcm = ನೈಜೀರಿಯನ್ ಪಿಡ್ಗಿನ್
language-name-peo = ಪ್ರಾಚೀನ ಪರ್ಶಿಯನ್
language-name-phn = ಫೀನಿಷಿಯನ್
language-name-pi = ಪಾಲಿ
language-name-pl = ಪೊಲಿಶ್
language-name-pon = ಪೋನ್‌‌ಪಿಯನ್
language-name-prg = ಪ್ರಶಿಯನ್
language-name-pro = ಪ್ರಾಚೀನ ಪ್ರೊವೆನ್ಶಿಯಲ್
language-name-ps = ಪಾಷ್ಟೋ
language-name-pt = ಪೋರ್ಚುಗೀಸ್
language-name-pt_BR = ಬ್ರೆಜಿಲಿಯನ್ ಪೋರ್ಚುಗೀಸ್
language-name-pt_PT = ಯೂರೋಪಿಯನ್ ಪೋರ್ಚುಗೀಸ್
language-name-qu = ಕ್ವೆಚುವಾ
language-name-quc = ಕಿಷೆ
language-name-raj = ರಾಜಸ್ಥಾನಿ
language-name-rap = ರಾಪಾನುಯಿ
language-name-rar = ರಾರೋಟೊಂಗನ್
language-name-rm = ರೊಮಾನ್ಶ್
language-name-rn = ರುಂಡಿ
language-name-ro = ರೊಮೇನಿಯನ್
language-name-ro_MD = ಮಾಲ್ಡೇವಿಯನ್
language-name-rof = ರೊಂಬೊ
language-name-rom = ರೋಮಾನಿ
language-name-root = ರೂಟ್
language-name-ru = ರಷ್ಯನ್
language-name-rup = ಅರೋಮಾನಿಯನ್
language-name-rw = ಕಿನ್ಯಾರ್‌ವಾಂಡಾ
language-name-rwk = ರುವ
language-name-sa = ಸಂಸ್ಕೃತ
language-name-sad = ಸಂಡಾವೇ
language-name-sah = ಸಖಾ
language-name-sam = ಸಮರಿಟನ್ ಅರಾಮಿಕ್
language-name-saq = ಸಂಬುರು
language-name-sas = ಸಸಾಕ್
language-name-sat = ಸಂತಾಲಿ
language-name-sba = ನಂಬೇ
language-name-sbp = ಸಂಗು
language-name-sc = ಸರ್ಡೀನಿಯನ್
language-name-scn = ಸಿಸಿಲಿಯನ್
language-name-sco = ಸ್ಕೋಟ್ಸ್
language-name-sd = ಸಿಂಧಿ
language-name-sdh = ದಕ್ಷಿಣ ಕುರ್ದಿಶ್
language-name-se = ಉತ್ತರ ಸಾಮಿ
language-name-seh = ಸೆನ
language-name-sel = ಸೆಲ್ಕಪ್
language-name-ses = ಕೊಯ್ರಬೊರೊ ಸೆನ್ನಿ
language-name-sg = ಸಾಂಗೋ
language-name-sga = ಪ್ರಾಚೀನ ಐರಿಷ್
language-name-sh = ಸರ್ಬೋ-ಕ್ರೊಯೇಶಿಯನ್
language-name-shi = ಟಷೆಲ್‍ಹಿಟ್
language-name-shn = ಶಾನ್
language-name-si = ಸಿಂಹಳ
language-name-sid = ಸಿಡಾಮೋ
language-name-sk = ಸ್ಲೋವಾಕ್
language-name-sl = ಸ್ಲೋವೇನಿಯನ್
language-name-sm = ಸಮೋವನ್
language-name-sma = ದಕ್ಷಿಣ ಸಾಮಿ
language-name-smj = ಲೂಲ್ ಸಾಮಿ
language-name-smn = ಇನಾರಿ ಸಮೀ
language-name-sms = ಸ್ಕೋಟ್ ಸಾಮಿ
language-name-sn = ಶೋನಾ
language-name-snk = ಸೋನಿಂಕೆ
language-name-so = ಸೊಮಾಲಿ
language-name-sog = ಸೋಗ್ಡಿಯನ್
language-name-sq = ಅಲ್ಬೇನಿಯನ್
language-name-sr = ಸೆರ್ಬಿಯನ್
language-name-srn = ಸ್ರಾನನ್ ಟೋಂಗೋ
language-name-srr = ಸೇರೇರ್
language-name-ss = ಸ್ವಾತಿ
language-name-ssy = ಸಹೊ
language-name-st = ದಕ್ಷಿಣ ಸೋಥೋ
language-name-su = ಸುಂಡಾನೀಸ್
language-name-suk = ಸುಕುಮಾ
language-name-sus = ಸುಸು
language-name-sux = ಸುಮೇರಿಯನ್
language-name-sv = ಸ್ವೀಡಿಷ್
language-name-sw = ಸ್ವಹಿಲಿ
language-name-sw_CD = ಕಾಂಗೊ ಸ್ವಹಿಲಿ
language-name-swb = ಕೊಮೊರಿಯನ್
language-name-syc = ಶಾಸ್ತ್ರೀಯ ಸಿರಿಯಕ್
language-name-syr = ಸಿರಿಯಾಕ್
language-name-ta = ತಮಿಳು
language-name-te = ತೆಲುಗು
language-name-tem = ಟಿಮ್ನೆ
language-name-teo = ಟೆಸೊ
language-name-ter = ಟೆರೆನೋ
language-name-tet = ಟೇಟಮ್
language-name-tg = ತಾಜಿಕ್
language-name-th = ಥಾಯ್
language-name-ti = ಟಿಗ್ರಿನ್ಯಾ
language-name-tig = ಟೈಗ್ರೆ
language-name-tiv = ಟಿವ್
language-name-tk = ಟರ್ಕ್‌ಮೆನ್
language-name-tkl = ಟೊಕೆಲಾವ್
language-name-tl = ಟ್ಯಾಗಲೋಗ್
language-name-tlh = ಕ್ಲಿಂಗನ್
language-name-tli = ಟ್ಲಿಂಗಿಟ್
language-name-tmh = ಟಮಾಷೆಕ್
language-name-tn = ಸ್ವಾನಾ
language-name-to = ಟೋಂಗನ್
language-name-tog = ನ್ಯಾಸಾ ಟೋಂಗಾ
language-name-tpi = ಟೋಕ್ ಪಿಸಿನ್
language-name-tr = ಟರ್ಕಿಶ್
language-name-trv = ಟರೊಕೊ
language-name-ts = ಸೋಂಗಾ
language-name-tsi = ಸಿಂಶಿಯನ್
language-name-tt = ಟಾಟರ್
language-name-tum = ತುಂಬುಕಾ
language-name-tvl = ಟುವಾಲು
language-name-tw = ಟ್ವಿ
language-name-twq = ಟಸವಕ್
language-name-ty = ಟಹೀಟಿಯನ್
language-name-tyv = ಟುವಿನಿಯನ್
language-name-tzm = ಮಧ್ಯ ಅಟ್ಲಾಸ್ ಟಮಜೈಟ್
language-name-udm = ಉಡ್‌ಮುರ್ಟ್
language-name-ug = ಉಯಿಘರ್
language-name-uga = ಉಗಾರಿಟಿಕ್
language-name-uk = ಉಕ್ರೇನಿಯನ್
language-name-umb = ಉಂಬುಂಡು
language-name-und = ಅಪರಿಚಿತ ಭಾಷೆ
language-name-ur = ಉರ್ದು
language-name-uz = ಉಜ್ಬೇಕ್
language-name-vai = ವಾಯಿ
language-name-ve = ವೆಂಡಾ
language-name-vi = ವಿಯೆಟ್ನಾಮೀಸ್
language-name-vo = ವೋಲಾಪುಕ್
language-name-vot = ವೋಟಿಕ್
language-name-vun = ವುಂಜೊ
language-name-wa = ವಾಲೂನ್
language-name-wae = ವಾಲ್ಸರ್
language-name-wal = ವಲಾಯ್ತಾ
language-name-war = ವರಾಯ್
language-name-was = ವಾಷೋ
language-name-wbp = ವಾರ್ಲ್‌ಪಿರಿ
language-name-wo = ವೋಲೋಫ್
language-name-wuu = ವು
language-name-xal = ಕಲ್ಮೈಕ್
language-name-xh = ಕ್ಸೋಸ
language-name-xog = ಸೊಗ
language-name-yao = ಯಾವೊ
language-name-yap = ಯಪೀಸೆ
language-name-yav = ಯಾಂಗ್ಬೆನ್
language-name-ybb = ಯೆಂಬಾ
language-name-yi = ಯಿಡ್ಡಿಶ್
language-name-yo = ಯೊರುಬಾ
language-name-yue = ಕ್ಯಾಂಟನೀಸ್
language-name-za = ಝೂವಾಂಗ್
language-name-zap = ಝೋಪೊಟೆಕ್
language-name-zbl = ಬ್ಲಿಸ್ಸಿಂಬಲ್ಸ್
language-name-zen = ಝೆನಾಗಾ
language-name-zgh = ಸ್ಟ್ಯಾಂಡರ್ಡ್ ಮೊರೊಕ್ಕನ್ ಟಮಜೈಟ್
language-name-zh = ಚೈನೀಸ್
language-name-zh_Hans = ಸರಳೀಕೃತ ಚೈನೀಸ್
language-name-zh_Hant = ಸಾಂಪ್ರದಾಯಿಕ ಚೈನೀಸ್
language-name-zu = ಜುಲು
language-name-zun = ಝೂನಿ
language-name-zxx = ಯಾವುದೇ ಭಾಷಾಸಂಬಂಧಿ ವಿಷಯವಿಲ್ಲ
language-name-zza = ಜಾಝಾ
