language-name-aa = Afar
language-name-ab = Abkhazian
language-name-ace = Achinese
language-name-ach = Acoli
language-name-ada = Adangme
language-name-ady = Adyghe
language-name-ae = Avestan
language-name-aeb = Tunisian Arabic
language-name-af = Afrikaans
language-name-afh = Afrihili
language-name-agq = Aghem
language-name-ain = Ainu
language-name-ak = Akan
language-name-akk = Akkadian
language-name-akz = Alabama
language-name-ale = Aleut
language-name-aln = Gheg Albanian
language-name-alt = Southern Altai
language-name-am = Amharic
language-name-an = Aragonese
language-name-ang = Old English
language-name-anp = Angika
language-name-ar = Arabic
language-name-ar_001 = Modern Standard Arabic
language-name-arc = Aramaic
language-name-arn = Mapuche
language-name-aro = Araona
language-name-arp = Arapaho
language-name-arq = Algerian Arabic
language-name-ars = Najdi Arabic
language-name-arw = Arawak
language-name-ary = Moroccan Arabic
language-name-arz = Egyptian Arabic
language-name-as = Assamese
language-name-asa = Asu
language-name-ase = American Sign Language
language-name-ast = Asturian
language-name-av = Avaric
language-name-avk = Kotava
language-name-awa = Awadhi
language-name-ay = Aymara
language-name-az = Azerbaijani
language-name-ba = Bashkir
language-name-bal = Baluchi
language-name-ban = Balinese
language-name-bar = Bavarian
language-name-bas = Basaa
language-name-bax = Bamun
language-name-bbc = Batak Toba
language-name-bbj = Ghomala
language-name-be = Belarusian
language-name-bej = Beja
language-name-bem = Bemba
language-name-bew = Betawi
language-name-bez = Bena
language-name-bfd = Bafut
language-name-bfq = Badaga
language-name-bg = Bulgarian
language-name-bgn = Western Balochi
language-name-bho = Bhojpuri
language-name-bi = Bislama
language-name-bik = Bikol
language-name-bin = Bini
language-name-bjn = Banjar
language-name-bkm = Kom
language-name-bla = Siksika
language-name-bm = Bambara
language-name-bn = Bangla
language-name-bo = Tibetan
language-name-bpy = Bishnupriya
language-name-bqi = Bakhtiari
language-name-br = Breton
language-name-bra = Braj
language-name-brh = Brahui
language-name-brx = Bodo
language-name-bs = Bosnian
language-name-bss = Akoose
language-name-bua = Buriat
language-name-bug = Buginese
language-name-bum = Bulu
language-name-byn = Blin
language-name-byv = Medumba
language-name-ca = Catalan
language-name-cad = Caddo
language-name-car = Carib
language-name-cay = Cayuga
language-name-cch = Atsam
language-name-ccp = Chakma
language-name-ce = Chechen
language-name-ceb = Cebuano
language-name-cgg = Chiga
language-name-ch = Chamorro
language-name-chb = Chibcha
language-name-chg = Chagatai
language-name-chk = Chuukese
language-name-chm = Mari
language-name-chn = Chinook Jargon
language-name-cho = Choctaw
language-name-chp = Chipewyan
language-name-chr = Cherokee
language-name-chy = Cheyenne
language-name-ckb = Central Kurdish
language-name-co = Corsican
language-name-cop = Coptic
language-name-cps = Capiznon
language-name-cr = Cree
language-name-crh = Crimean Turkish
language-name-crs = Seselwa Creole French
language-name-cs = Czech
language-name-csb = Kashubian
language-name-cu = Church Slavic
language-name-cv = Chuvash
language-name-cy = Welsh
language-name-da = Danish
language-name-dak = Dakota
language-name-dar = Dargwa
language-name-dav = Taita
language-name-de = German
language-name-de_AT = Austrian German
language-name-de_CH = Swiss High German
language-name-del = Delaware
language-name-den = Slave
language-name-dgr = Dogrib
language-name-din = Dinka
language-name-dje = Zarma
language-name-doi = Dogri
language-name-dsb = Lower Sorbian
language-name-dtp = Central Dusun
language-name-dua = Duala
language-name-dum = Middle Dutch
language-name-dv = Divehi
language-name-dyo = Jola-Fonyi
language-name-dyu = Dyula
language-name-dz = Dzongkha
language-name-dzg = Dazaga
language-name-ebu = Embu
language-name-ee = Ewe
language-name-efi = Efik
language-name-egl = Emilian
language-name-egy = Ancient Egyptian
language-name-eka = Ekajuk
language-name-el = Greek
language-name-elx = Elamite
language-name-en = English
language-name-en_AU = Australian English
language-name-en_CA = Canadian English
language-name-en_GB = British English
language-name-en_US = American English
language-name-enm = Middle English
language-name-eo = Esperanto
language-name-es = Spanish
language-name-es_419 = Latin American Spanish
language-name-es_ES = European Spanish
language-name-es_MX = Mexican Spanish
language-name-esu = Central Yupik
language-name-et = Estonian
language-name-eu = Basque
language-name-ewo = Ewondo
language-name-ext = Extremaduran
language-name-fa = Persian
language-name-fa_AF = Dari
language-name-fan = Fang
language-name-fat = Fanti
language-name-ff = Fulah
language-name-fi = Finnish
language-name-fil = Filipino
language-name-fit = Tornedalen Finnish
language-name-fj = Fijian
language-name-fo = Faroese
language-name-fon = Fon
language-name-fr = French
language-name-fr_CA = Canadian French
language-name-fr_CH = Swiss French
language-name-frc = Cajun French
language-name-frm = Middle French
language-name-fro = Old French
language-name-frp = Arpitan
language-name-frr = Northern Frisian
language-name-frs = Eastern Frisian
language-name-fur = Friulian
language-name-fy = Western Frisian
language-name-ga = Irish
language-name-gaa = Ga
language-name-gag = Gagauz
language-name-gan = Gan Chinese
language-name-gay = Gayo
language-name-gba = Gbaya
language-name-gbz = Zoroastrian Dari
language-name-gd = Scottish Gaelic
language-name-gez = Geez
language-name-gil = Gilbertese
language-name-gl = Galician
language-name-glk = Gilaki
language-name-gmh = Middle High German
language-name-gn = Guarani
language-name-goh = Old High German
language-name-gom = Goan Konkani
language-name-gon = Gondi
language-name-gor = Gorontalo
language-name-got = Gothic
language-name-grb = Grebo
language-name-grc = Ancient Greek
language-name-gsw = Swiss German
language-name-gu = Gujarati
language-name-guc = Wayuu
language-name-gur = Frafra
language-name-guz = Gusii
language-name-gv = Manx
language-name-gwi = Gwichʼin
language-name-ha = Hausa
language-name-hai = Haida
language-name-hak = Hakka Chinese
language-name-haw = Hawaiian
language-name-he = Hebrew
language-name-hi = Hindi
language-name-hif = Fiji Hindi
language-name-hil = Hiligaynon
language-name-hit = Hittite
language-name-hmn = Hmong
language-name-ho = Hiri Motu
language-name-hr = Croatian
language-name-hsb = Upper Sorbian
language-name-hsn = Xiang Chinese
language-name-ht = Haitian Creole
language-name-hu = Hungarian
language-name-hup = Hupa
language-name-hy = Armenian
language-name-hz = Herero
language-name-ia = Interlingua
language-name-iba = Iban
language-name-ibb = Ibibio
language-name-id = Indonesian
language-name-ie = Interlingue
language-name-ig = Igbo
language-name-ii = Sichuan Yi
language-name-ik = Inupiaq
language-name-ilo = Iloko
language-name-inh = Ingush
language-name-io = Ido
language-name-is = Icelandic
language-name-it = Italian
language-name-iu = Inuktitut
language-name-izh = Ingrian
language-name-ja = Japanese
language-name-jam = Jamaican Creole English
language-name-jbo = Lojban
language-name-jgo = Ngomba
language-name-jmc = Machame
language-name-jpr = Judeo-Persian
language-name-jrb = Judeo-Arabic
language-name-jut = Jutish
language-name-jv = Javanese
language-name-ka = Georgian
language-name-kaa = Kara-Kalpak
language-name-kab = Kabyle
language-name-kac = Kachin
language-name-kaj = Jju
language-name-kam = Kamba
language-name-kaw = Kawi
language-name-kbd = Kabardian
language-name-kbl = Kanembu
language-name-kcg = Tyap
language-name-kde = Makonde
language-name-kea = Kabuverdianu
language-name-ken = Kenyang
language-name-kfo = Koro
language-name-kg = Kongo
language-name-kgp = Kaingang
language-name-kha = Khasi
language-name-kho = Khotanese
language-name-khq = Koyra Chiini
language-name-khw = Khowar
language-name-ki = Kikuyu
language-name-kiu = Kirmanjki
language-name-kj = Kuanyama
language-name-kk = Kazakh
language-name-kkj = Kako
language-name-kl = Kalaallisut
language-name-kln = Kalenjin
language-name-km = Khmer
language-name-kmb = Kimbundu
language-name-kn = Kannada
language-name-ko = Korean
language-name-koi = Komi-Permyak
language-name-kok = Konkani
language-name-kos = Kosraean
language-name-kpe = Kpelle
language-name-kr = Kanuri
language-name-krc = Karachay-Balkar
language-name-kri = Krio
language-name-krj = Kinaray-a
language-name-krl = Karelian
language-name-kru = Kurukh
language-name-ks = Kashmiri
language-name-ksb = Shambala
language-name-ksf = Bafia
language-name-ksh = Colognian
language-name-ku = Kurdish
language-name-kum = Kumyk
language-name-kut = Kutenai
language-name-kv = Komi
language-name-kw = Cornish
language-name-ky = Kyrgyz
language-name-la = Latin
language-name-lad = Ladino
language-name-lag = Langi
language-name-lah = Lahnda
language-name-lam = Lamba
language-name-lb = Luxembourgish
language-name-lez = Lezghian
language-name-lfn = Lingua Franca Nova
language-name-lg = Ganda
language-name-li = Limburgish
language-name-lij = Ligurian
language-name-liv = Livonian
language-name-lkt = Lakota
language-name-lmo = Lombard
language-name-ln = Lingala
language-name-lo = Lao
language-name-lol = Mongo
language-name-lou = Louisiana Creole
language-name-loz = Lozi
language-name-lrc = Northern Luri
language-name-lt = Lithuanian
language-name-ltg = Latgalian
language-name-lu = Luba-Katanga
language-name-lua = Luba-Lulua
language-name-lui = Luiseno
language-name-lun = Lunda
language-name-luo = Luo
language-name-lus = Mizo
language-name-luy = Luyia
language-name-lv = Latvian
language-name-lzh = Literary Chinese
language-name-lzz = Laz
language-name-mad = Madurese
language-name-maf = Mafa
language-name-mag = Magahi
language-name-mai = Maithili
language-name-mak = Makasar
language-name-man = Mandingo
language-name-mas = Masai
language-name-mde = Maba
language-name-mdf = Moksha
language-name-mdr = Mandar
language-name-men = Mende
language-name-mer = Meru
language-name-mfe = Morisyen
language-name-mg = Malagasy
language-name-mga = Middle Irish
language-name-mgh = Makhuwa-Meetto
language-name-mgo = Metaʼ
language-name-mh = Marshallese
language-name-mi = Maori
language-name-mic = Mi'kmaq
language-name-min = Minangkabau
language-name-mk = Macedonian
language-name-ml = Malayalam
language-name-mn = Mongolian
language-name-mnc = Manchu
language-name-mni = Manipuri
language-name-moh = Mohawk
language-name-mos = Mossi
language-name-mr = Marathi
language-name-mrj = Western Mari
language-name-ms = Malay
language-name-mt = Maltese
language-name-mua = Mundang
language-name-mul = Multiple languages
language-name-mus = Creek
language-name-mwl = Mirandese
language-name-mwr = Marwari
language-name-mwv = Mentawai
language-name-my = Burmese
language-name-mye = Myene
language-name-myv = Erzya
language-name-mzn = Mazanderani
language-name-na = Nauru
language-name-nan = Min Nan Chinese
language-name-nap = Neapolitan
language-name-naq = Nama
language-name-nb = Norwegian Bokmål
language-name-nd = North Ndebele
language-name-nds = Low German
language-name-nds_NL = Low Saxon
language-name-ne = Nepali
language-name-new = Newari
language-name-ng = Ndonga
language-name-nia = Nias
language-name-niu = Niuean
language-name-njo = Ao Naga
language-name-nl = Dutch
language-name-nl_BE = Flemish
language-name-nmg = Kwasio
language-name-nn = Norwegian Nynorsk
language-name-nnh = Ngiemboon
language-name-no = Norwegian
language-name-nog = Nogai
language-name-non = Old Norse
language-name-nov = Novial
language-name-nqo = N’Ko
language-name-nr = South Ndebele
language-name-nso = Northern Sotho
language-name-nus = Nuer
language-name-nv = Navajo
language-name-nwc = Classical Newari
language-name-ny = Nyanja
language-name-nym = Nyamwezi
language-name-nyn = Nyankole
language-name-nyo = Nyoro
language-name-nzi = Nzima
language-name-oc = Occitan
language-name-oj = Ojibwa
language-name-om = Oromo
language-name-or = Odia
language-name-os = Ossetic
language-name-osa = Osage
language-name-ota = Ottoman Turkish
language-name-pa = Punjabi
language-name-pag = Pangasinan
language-name-pal = Pahlavi
language-name-pam = Pampanga
language-name-pap = Papiamento
language-name-pau = Palauan
language-name-pcd = Picard
language-name-pcm = Nigerian Pidgin
language-name-pdc = Pennsylvania German
language-name-pdt = Plautdietsch
language-name-peo = Old Persian
language-name-pfl = Palatine German
language-name-phn = Phoenician
language-name-pi = Pali
language-name-pl = Polish
language-name-pms = Piedmontese
language-name-pnt = Pontic
language-name-pon = Pohnpeian
language-name-prg = Prussian
language-name-pro = Old Provençal
language-name-ps = Pashto
language-name-pt = Portuguese
language-name-pt_BR = Brazilian Portuguese
language-name-pt_PT = European Portuguese
language-name-qu = Quechua
language-name-quc = Kʼicheʼ
language-name-qug = Chimborazo Highland Quichua
language-name-raj = Rajasthani
language-name-rap = Rapanui
language-name-rar = Rarotongan
language-name-rgn = Romagnol
language-name-rif = Riffian
language-name-rm = Romansh
language-name-rn = Rundi
language-name-ro = Romanian
language-name-ro_MD = Moldavian
language-name-rof = Rombo
language-name-rom = Romany
language-name-root = Root
language-name-rtm = Rotuman
language-name-ru = Russian
language-name-rue = Rusyn
language-name-rug = Roviana
language-name-rup = Aromanian
language-name-rw = Kinyarwanda
language-name-rwk = Rwa
language-name-sa = Sanskrit
language-name-sad = Sandawe
language-name-sah = Sakha
language-name-sam = Samaritan Aramaic
language-name-saq = Samburu
language-name-sas = Sasak
language-name-sat = Santali
language-name-saz = Saurashtra
language-name-sba = Ngambay
language-name-sbp = Sangu
language-name-sc = Sardinian
language-name-scn = Sicilian
language-name-sco = Scots
language-name-sd = Sindhi
language-name-sdc = Sassarese Sardinian
language-name-sdh = Southern Kurdish
language-name-se = Northern Sami
language-name-see = Seneca
language-name-seh = Sena
language-name-sei = Seri
language-name-sel = Selkup
language-name-ses = Koyraboro Senni
language-name-sg = Sango
language-name-sga = Old Irish
language-name-sgs = Samogitian
language-name-sh = Serbo-Croatian
language-name-shi = Tachelhit
language-name-shn = Shan
language-name-shu = Chadian Arabic
language-name-si = Sinhala
language-name-sid = Sidamo
language-name-sk = Slovak
language-name-sl = Slovenian
language-name-sli = Lower Silesian
language-name-sly = Selayar
language-name-sm = Samoan
language-name-sma = Southern Sami
language-name-smj = Lule Sami
language-name-smn = Inari Sami
language-name-sms = Skolt Sami
language-name-sn = Shona
language-name-snk = Soninke
language-name-so = Somali
language-name-sog = Sogdien
language-name-sq = Albanian
language-name-sr = Serbian
language-name-sr_ME = Montenegrin
language-name-srn = Sranan Tongo
language-name-srr = Serer
language-name-ss = Swati
language-name-ssy = Saho
language-name-st = Southern Sotho
language-name-stq = Saterland Frisian
language-name-su = Sundanese
language-name-suk = Sukuma
language-name-sus = Susu
language-name-sux = Sumerian
language-name-sv = Swedish
language-name-sw = Swahili
language-name-sw_CD = Congo Swahili
language-name-swb = Comorian
language-name-syc = Classical Syriac
language-name-syr = Syriac
language-name-szl = Silesian
language-name-ta = Tamil
language-name-tcy = Tulu
language-name-te = Telugu
language-name-tem = Timne
language-name-teo = Teso
language-name-ter = Tereno
language-name-tet = Tetum
language-name-tg = Tajik
language-name-th = Thai
language-name-ti = Tigrinya
language-name-tig = Tigre
language-name-tiv = Tiv
language-name-tk = Turkmen
language-name-tkl = Tokelau
language-name-tkr = Tsakhur
language-name-tl = Tagalog
language-name-tlh = Klingon
language-name-tli = Tlingit
language-name-tly = Talysh
language-name-tmh = Tamashek
language-name-tn = Tswana
language-name-to = Tongan
language-name-tog = Nyasa Tonga
language-name-tpi = Tok Pisin
language-name-tr = Turkish
language-name-tru = Turoyo
language-name-trv = Taroko
language-name-ts = Tsonga
language-name-tsd = Tsakonian
language-name-tsi = Tsimshian
language-name-tt = Tatar
language-name-ttt = Muslim Tat
language-name-tum = Tumbuka
language-name-tvl = Tuvalu
language-name-tw = Twi
language-name-twq = Tasawaq
language-name-ty = Tahitian
language-name-tyv = Tuvinian
language-name-tzm = Central Atlas Tamazight
language-name-udm = Udmurt
language-name-ug = Uyghur
language-name-uga = Ugaritic
language-name-uk = Ukrainian
language-name-umb = Umbundu
language-name-und = Unknown language
language-name-ur = Urdu
language-name-uz = Uzbek
language-name-vai = Vai
language-name-ve = Venda
language-name-vec = Venetian
language-name-vep = Veps
language-name-vi = Vietnamese
language-name-vls = West Flemish
language-name-vmf = Main-Franconian
language-name-vo = Volapük
language-name-vot = Votic
language-name-vro = Võro
language-name-vun = Vunjo
language-name-wa = Walloon
language-name-wae = Walser
language-name-wal = Wolaytta
language-name-war = Waray
language-name-was = Washo
language-name-wbp = Warlpiri
language-name-wo = Wolof
language-name-wuu = Wu Chinese
language-name-xal = Kalmyk
language-name-xh = Xhosa
language-name-xmf = Mingrelian
language-name-xog = Soga
language-name-yao = Yao
language-name-yap = Yapese
language-name-yav = Yangben
language-name-ybb = Yemba
language-name-yi = Yiddish
language-name-yo = Yoruba
language-name-yrl = Nheengatu
language-name-yue = Cantonese
language-name-za = Zhuang
language-name-zap = Zapotec
language-name-zbl = Blissymbols
language-name-zea = Zeelandic
language-name-zen = Zenaga
language-name-zgh = Standard Moroccan Tamazight
language-name-zh = Chinese
language-name-zh_Hans = Simplified Chinese
language-name-zh_Hant = Traditional Chinese
language-name-zu = Zulu
language-name-zun = Zuni
language-name-zxx = No linguistic content
language-name-zza = Zaza
