language-name-aa = afar
language-name-ab = abkhazianu
language-name-ace = achinés
language-name-ach = acoli
language-name-ada = adangme
language-name-ady = adyghe
language-name-ae = avestanín
language-name-aeb = árabe de Túnez
language-name-af = afrikaans
language-name-afh = afrihili
language-name-agq = aghem
language-name-ain = ainu
language-name-ak = akan
language-name-akk = acadianu
language-name-akz = alabama
language-name-ale = aleut
language-name-aln = gheg d’Albania
language-name-alt = altai del sur
language-name-am = amháricu
language-name-an = aragonés
language-name-ang = inglés antiguu
language-name-anp = angika
language-name-ar = árabe
language-name-ar_001 = árabe estándar modernu
language-name-arc = araméu
language-name-arn = mapuche
language-name-aro = araona
language-name-arp = arapaho
language-name-arq = árabe d’Arxelia
language-name-arw = arawak
language-name-ary = árabe de Marruecos
language-name-arz = árabe d’Exiptu
language-name-as = asamés
language-name-asa = asu
language-name-ase = llingua de signos americana
language-name-ast = asturianu
language-name-av = aváricu
language-name-avk = kotava
language-name-awa = awadhi
language-name-ay = aymara
language-name-az = azerbaixanu
language-name-ba = bashkir
language-name-bal = baluchi
language-name-ban = balinés
language-name-bar = bávaru
language-name-bas = basaa
language-name-bax = bamun
language-name-bbc = batak toba
language-name-bbj = ghomala
language-name-be = bielorrusu
language-name-bej = beja
language-name-bem = bemba
language-name-bew = betawi
language-name-bez = bena
language-name-bfd = bafut
language-name-bfq = badaga
language-name-bg = búlgaru
language-name-bgn = balochi occidental
language-name-bho = bhojpuri
language-name-bi = bislama
language-name-bik = bikol
language-name-bin = bini
language-name-bjn = banjar
language-name-bkm = kom
language-name-bla = siksika
language-name-bm = bambara
language-name-bn = bengalín
language-name-bo = tibetanu
language-name-bpy = bishnupriya
language-name-bqi = bakhtiari
language-name-br = bretón
language-name-bra = braj
language-name-brh = brahui
language-name-brx = bodo
language-name-bs = bosniu
language-name-bss = akoose
language-name-bua = buriat
language-name-bug = buginés
language-name-bum = bulu
language-name-byn = blin
language-name-byv = medumba
language-name-ca = catalán
language-name-cad = caddo
language-name-car = caribe
language-name-cay = cayuga
language-name-cch = atsam
language-name-ce = chechenu
language-name-ceb = cebuanu
language-name-cgg = chiga
language-name-ch = chamorro
language-name-chb = chibcha
language-name-chg = chagatai
language-name-chk = chuukés
language-name-chm = mari
language-name-chn = xíriga chinook
language-name-cho = choctaw
language-name-chp = chipewyanu
language-name-chr = cheroqui
language-name-chy = cheyenne
language-name-ckb = kurdu central
language-name-co = corsu
language-name-cop = cópticu
language-name-cps = capiznon
language-name-cr = cree
language-name-crh = turcu de Crimea
language-name-crs = francés criollu seselwa
language-name-cs = checu
language-name-csb = kashubianu
language-name-cu = eslávicu eclesiásticu
language-name-cv = chuvash
language-name-cy = galés
language-name-da = danés
language-name-dak = dakota
language-name-dar = dargwa
language-name-dav = taita
language-name-de = alemán
language-name-de_AT = alemán d’Austria
language-name-de_CH = altualemán de Suiza
language-name-del = delaware
language-name-den = slave
language-name-dgr = dogrib
language-name-din = dinka
language-name-dje = zarma
language-name-doi = dogri
language-name-dsb = baxu sorbiu
language-name-dtp = dusun central
language-name-dua = duala
language-name-dum = neerlandés mediu
language-name-dv = divehi
language-name-dyo = jola-fonyi
language-name-dyu = dyula
language-name-dz = dzongkha
language-name-dzg = dazaga
language-name-ebu = embú
language-name-ee = ewe
language-name-efi = efik
language-name-egl = emilianu
language-name-egy = exipciu antiguu
language-name-eka = ekajuk
language-name-el = griegu
language-name-elx = elamita
language-name-en = inglés
language-name-en_AU = inglés d’Australia
language-name-en_CA = inglés de Canadá
language-name-en_GB = inglés de Gran Bretaña
language-name-en_US = inglés d’Estaos Xuníos
language-name-enm = inglés mediu
language-name-eo = esperanto
language-name-es = español
language-name-es_419 = español d’América Llatina
language-name-es_ES = español européu
language-name-es_MX = español de Méxicu
language-name-esu = yupik central
language-name-et = estoniu
language-name-eu = vascu
language-name-ewo = ewondo
language-name-ext = estremeñu
language-name-fa = persa
language-name-fan = fang
language-name-fat = fanti
language-name-ff = fulah
language-name-fi = finlandés
language-name-fil = filipín
language-name-fit = finlandés de Tornedalen
language-name-fj = fixanu
language-name-fo = feroés
language-name-fon = fon
language-name-fr = francés
language-name-fr_CA = francés de Canadá
language-name-fr_CH = francés de Suiza
language-name-frc = francés cajun
language-name-frm = francés mediu
language-name-fro = francés antiguu
language-name-frp = arpitanu
language-name-frr = frisón del norte
language-name-frs = frisón oriental
language-name-fur = friulianu
language-name-fy = frisón occidental
language-name-ga = irlandés
language-name-gaa = ga
language-name-gag = gagauz
language-name-gan = chinu gan
language-name-gay = gayo
language-name-gba = gbaya
language-name-gbz = dari zoroastrianu
language-name-gd = gaélicu escocés
language-name-gez = geez
language-name-gil = gilbertés
language-name-gl = gallegu
language-name-glk = gilaki
language-name-gmh = altualemán mediu
language-name-gn = guaraní
language-name-goh = altualemán antiguu
language-name-gom = goan konkani
language-name-gon = gondi
language-name-gor = gorontalo
language-name-got = góticu
language-name-grb = grebo
language-name-grc = griegu antiguu
language-name-gsw = alemán de Suiza
language-name-gu = guyaratí
language-name-guc = wayuu
language-name-gur = frafra
language-name-guz = gusii
language-name-gv = manés
language-name-gwi = gwichʼin
language-name-ha = ḥausa
language-name-hai = haida
language-name-hak = chinu hakka
language-name-haw = hawaianu
language-name-he = hebréu
language-name-hi = hindi
language-name-hif = hindi de Fiji
language-name-hil = hiligaynon
language-name-hit = hitita
language-name-hmn = hmong
language-name-ho = hiri motu
language-name-hr = croata
language-name-hsb = altu sorbiu
language-name-hsn = chinu xiang
language-name-ht = haitianu
language-name-hu = húngaru
language-name-hup = hupa
language-name-hy = armeniu
language-name-hz = herero
language-name-ia = interlingua
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indonesiu
language-name-ie = interlingue
language-name-ig = igbo
language-name-ii = yi de Sichuán
language-name-ik = inupiaq
language-name-ilo = iloko
language-name-inh = ingush
language-name-io = ido
language-name-is = islandés
language-name-it = italianu
language-name-iu = inuktitut
language-name-izh = ingrianu
language-name-ja = xaponés
language-name-jam = inglés criollu xamaicanu
language-name-jbo = lojban
language-name-jgo = ngomba
language-name-jmc = machame
language-name-jpr = xudeo-persa
language-name-jrb = xudeo-árabe
language-name-jut = jutlandés
language-name-jv = xavanés
language-name-ka = xeorxanu
language-name-kaa = kara-kalpak
language-name-kab = kabileñu
language-name-kac = kachin
language-name-kaj = jju
language-name-kam = kamba
language-name-kaw = kawi
language-name-kbd = kabardianu
language-name-kbl = kanembu
language-name-kcg = tyap
language-name-kde = makonde
language-name-kea = cabuverdianu
language-name-ken = kenyang
language-name-kfo = koro
language-name-kg = kongo
language-name-kgp = kaingang
language-name-kha = khasi
language-name-kho = khotanés
language-name-khq = koyra chiini
language-name-khw = khowar
language-name-ki = kikuyu
language-name-kiu = kirmanjki
language-name-kj = kuanyama
language-name-kk = kazaquistanín
language-name-kkj = kako
language-name-kl = kalaallisut
language-name-kln = kalenjin
language-name-km = ḥemer
language-name-kmb = kimbundu
language-name-kn = canarés
language-name-ko = coreanu
language-name-koi = komi-permyak
language-name-kok = konkani
language-name-kos = kosraeanu
language-name-kpe = kpelle
language-name-kr = kanuri
language-name-krc = karachay-balkar
language-name-kri = krio
language-name-krj = kinaray-a
language-name-krl = karelianu
language-name-kru = kurukh
language-name-ks = cachemirés
language-name-ksb = shambala
language-name-ksf = bafia
language-name-ksh = colonianu
language-name-ku = curdu
language-name-kum = kumyk
language-name-kut = kutenai
language-name-kv = komi
language-name-kw = córnicu
language-name-ky = kirguistanín
language-name-la = llatín
language-name-lad = ladino
language-name-lag = langi
language-name-lah = lahnda
language-name-lam = lamba
language-name-lb = luxemburgués
language-name-lez = lezghianu
language-name-lfn = lingua franca nova
language-name-lg = ganda
language-name-li = limburgués
language-name-lij = ligurianu
language-name-liv = livonianu
language-name-lkt = lakota
language-name-lmo = lombardu
language-name-ln = lingala
language-name-lo = laosianu
language-name-lol = mongo
language-name-loz = lozi
language-name-lrc = luri del norte
language-name-lt = lituanu
language-name-ltg = latgalianu
language-name-lu = luba-katanga
language-name-lua = luba-lulua
language-name-lui = luiseno
language-name-lun = lunda
language-name-luo = luo
language-name-lus = mizo
language-name-luy = luyia
language-name-lv = letón
language-name-lzh = chinu lliterariu
language-name-lzz = laz
language-name-mad = madurés
language-name-maf = mafa
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = makasar
language-name-man = mandingo
language-name-mas = masái
language-name-mde = maba
language-name-mdf = moksha
language-name-mdr = mandar
language-name-men = mende
language-name-mer = meru
language-name-mfe = morisyen
language-name-mg = malgaxe
language-name-mga = írlandés mediu
language-name-mgh = makhuwa-meetto
language-name-mgo = meta’
language-name-mh = marshallés
language-name-mi = maorí
language-name-mic = micmac
language-name-min = minangkabau
language-name-mk = macedoniu
language-name-ml = malayalam
language-name-mn = mongol
language-name-mnc = manchú
language-name-mni = manipuri
language-name-moh = mohawk
language-name-mos = mossi
language-name-mr = marathi
language-name-mrj = mari occidental
language-name-ms = malayu
language-name-mt = maltés
language-name-mua = mundang
language-name-mul = múltiples llingües
language-name-mus = creek
language-name-mwl = mirandés
language-name-mwr = marwari
language-name-mwv = mentawai
language-name-my = birmanu
language-name-mye = myene
language-name-myv = erzya
language-name-mzn = mazanderani
language-name-na = nauru
language-name-nan = chinu min nan
language-name-nap = napolitanu
language-name-naq = nama
language-name-nb = noruegu Bokmål
language-name-nd = ndebele del norte
language-name-nds = baxu alemán
language-name-nds_NL = baxu saxón
language-name-ne = nepalés
language-name-new = newari
language-name-ng = ndonga
language-name-nia = nias
language-name-niu = niueanu
language-name-njo = ao naga
language-name-nl = neerlandés
language-name-nl_BE = flamencu
language-name-nmg = kwasio
language-name-nn = noruegu Nynorsk
language-name-nnh = ngiemboon
language-name-no = noruegu
language-name-nog = nogai
language-name-non = noruegu antiguu
language-name-nov = novial
language-name-nqo = n’ko
language-name-nr = ndebele del sur
language-name-nso = sotho del norte
language-name-nus = nuer
language-name-nv = navajo
language-name-nwc = newari clásicu
language-name-ny = nyanja
language-name-nym = nyamwezi
language-name-nyn = nyankole
language-name-nyo = nyoro
language-name-nzi = nzima
language-name-oc = occitanu
language-name-oj = ojibwa
language-name-om = oromo
language-name-or = oriya
language-name-os = oséticu
language-name-osa = osage
language-name-ota = turcu otomanu
language-name-pa = punyabí
language-name-pag = pangasinan
language-name-pal = pahlavi
language-name-pam = pampanga
language-name-pap = papiamento
language-name-pau = palauanu
language-name-pcd = pícaru
language-name-pcm = nixerianu simplificáu
language-name-pdc = alemán de Pennsylvania
language-name-pdt = plautdietsch
language-name-peo = persa antiguu
language-name-pfl = alemán palatinu
language-name-phn = feniciu
language-name-pi = pali
language-name-pl = polacu
language-name-pms = piamontés
language-name-pnt = pónticu
language-name-pon = pohnpeianu
language-name-prg = prusianu
language-name-pro = provenzal antiguu
language-name-ps = pashtu
language-name-pt = portugués
language-name-pt_BR = portugués del Brasil
language-name-pt_PT = portugués européu
language-name-qu = quechua
language-name-quc = kʼicheʼ
language-name-qug = quichua del altiplanu de Chimborazo
language-name-raj = rajasthanín
language-name-rap = rapanui
language-name-rar = rarotonganu
language-name-rgn = romañol
language-name-rif = rifianu
language-name-rm = romanche
language-name-rn = rundi
language-name-ro = rumanu
language-name-ro_MD = moldavu
language-name-rof = rombo
language-name-rom = romaní
language-name-root = root
language-name-rtm = rotumanu
language-name-ru = rusu
language-name-rue = rusyn
language-name-rug = roviana
language-name-rup = aromanianu
language-name-rw = kinyarwanda
language-name-rwk = rwa
language-name-sa = sánscritu
language-name-sad = sandavés
language-name-sah = sakha
language-name-sam = araméu samaritanu
language-name-saq = samburu
language-name-sas = sasak
language-name-sat = santali
language-name-saz = saurashtra
language-name-sba = ngambay
language-name-sbp = sangu
language-name-sc = sardu
language-name-scn = sicilianu
language-name-sco = scots
language-name-sd = sindhi
language-name-sdc = sardu sassarés
language-name-sdh = kurdu del sur
language-name-se = sami del norte
language-name-see = séneca
language-name-seh = sena
language-name-sei = seri
language-name-sel = selkup
language-name-ses = koyraboro senni
language-name-sg = sango
language-name-sga = irlandés antiguu
language-name-sgs = samogitianu
language-name-sh = serbo-croata
language-name-shi = tachelhit
language-name-shn = shan
language-name-shu = árabe chadianu
language-name-si = cingalés
language-name-sid = sidamo
language-name-sk = eslovacu
language-name-sl = eslovenu
language-name-sli = baxu silesianu
language-name-sly = selayarés
language-name-sm = samoanu
language-name-sma = sami del sur
language-name-smj = lule sami
language-name-smn = inari sami
language-name-sms = skolt sami
language-name-sn = shona
language-name-snk = soninke
language-name-so = somalín
language-name-sog = sogdianu
language-name-sq = albanu
language-name-sr = serbiu
language-name-srn = sranan tongo
language-name-srr = serer
language-name-ss = swati
language-name-ssy = saho
language-name-st = sotho del sur
language-name-stq = frisón de Saterland
language-name-su = sondanés
language-name-suk = sukuma
language-name-sus = susu
language-name-sux = sumeriu
language-name-sv = suecu
language-name-sw = suaḥili
language-name-sw_CD = suaḥili del Congu
language-name-swb = comorianu
language-name-syc = siriacu clásicu
language-name-syr = siriacu
language-name-szl = silesianu
language-name-ta = tamil
language-name-tcy = tulu
language-name-te = telugu
language-name-tem = timne
language-name-teo = teso
language-name-ter = terena
language-name-tet = tetum
language-name-tg = taxiquistanín
language-name-th = tailandés
language-name-ti = tigrinya
language-name-tig = tigre
language-name-tiv = tiv
language-name-tk = turcomanu
language-name-tkl = tokelau
language-name-tkr = tsakhur
language-name-tl = tagalog
language-name-tlh = klingon
language-name-tli = tlingit
language-name-tly = talixín
language-name-tmh = tamashek
language-name-tn = tswana
language-name-to = tonganu
language-name-tog = tonga nyasa
language-name-tpi = tok pisin
language-name-tr = turcu
language-name-tru = turoyo
language-name-trv = taroko
language-name-ts = tsonga
language-name-tsd = tsakoniu
language-name-tsi = tsimshian
language-name-tt = tártaru
language-name-ttt = tati musulmán
language-name-tum = tumbuka
language-name-tvl = tuvalu
language-name-tw = twi
language-name-twq = tasawaq
language-name-ty = tahitianu
language-name-tyv = tuvinianu
language-name-tzm = tamazight del Atles central
language-name-udm = udmurt
language-name-ug = uigur
language-name-uga = ugaríticu
language-name-uk = ucraín
language-name-umb = umbundu
language-name-und = llingua desconocida
language-name-ur = urdu
language-name-uz = uzbequistanín
language-name-vai = vai
language-name-ve = venda
language-name-vec = venecianu
language-name-vep = vepsiu
language-name-vi = vietnamín
language-name-vls = flamencu occidental
language-name-vmf = franconianu del Main
language-name-vo = volapük
language-name-vot = vóticu
language-name-vro = voro
language-name-vun = vunjo
language-name-wa = valón
language-name-wae = walser
language-name-wal = wolaytta
language-name-war = waray
language-name-was = washo
language-name-wbp = warlpiri
language-name-wo = wolof
language-name-wuu = chinu wu
language-name-xal = calmuco
language-name-xh = xhosa
language-name-xmf = mingrelianu
language-name-xog = soga
language-name-yao = yao
language-name-yap = yapés
language-name-yav = yangben
language-name-ybb = yemba
language-name-yi = yiddish
language-name-yo = yoruba
language-name-yrl = nheengatu
language-name-yue = cantonés
language-name-za = zhuang
language-name-zap = zapoteca
language-name-zbl = simbólicu Bliss
language-name-zea = zeelandés
language-name-zen = zenaga
language-name-zgh = tamazight estándar de Marruecos
language-name-zh = chinu
language-name-zh_Hans = chinu simplificáu
language-name-zh_Hant = chinu tradicional
language-name-zu = zulú
language-name-zun = zuni
language-name-zxx = ensin conteníu llingüísticu
language-name-zza = zaza
