language-name-ab = آذأربایئجانی
language-name-af = آفریکانس
language-name-agq = آقئم
language-name-ak = آکان
language-name-am = أمھأری
language-name-ar = أرأڤی
language-name-ar_001 = عروی مدرن
language-name-arn = ماپوٙچئ
language-name-as = آسامی
language-name-asa = آسوٙ
language-name-az = آذأربایئجانی ھارگە
language-name-az_Arab = آذأری ھارگە
language-name-ba = باشکیری
language-name-be = بئلاروٙسی
language-name-bem = بیما
language-name-bez = بئنا
language-name-bg = بولغاری
language-name-bgn = بألوٙچی أقتوٙنئشین
language-name-bm = بامبارا
language-name-bn = بأنگالی
language-name-bo = تأبأتی
language-name-br = بئرئتون
language-name-brx = بودو
language-name-bs = بوسنیایی
language-name-ca = کاتالان
language-name-ce = چئچئنی
language-name-cgg = چیگا
language-name-chr = چوروٙکی
language-name-ckb = کوردی سوٙرانی
language-name-co = کوریسکان
language-name-cv = چواشی
language-name-cy = ڤئلزی
language-name-da = دانمارکی
language-name-dav = تایتا
language-name-de = آلمانی
language-name-de_AT = آلمانی ئوتریشی
language-name-de_CH = آلمانی سوٙییسی
language-name-dje = زارما
language-name-dsb = سوربی ھاری
language-name-dua = دوٙالا
language-name-dyo = جولا فوٙنیی
language-name-dz = زوٙنگخا
language-name-ebu = ئمبو
language-name-ee = ئڤئ
language-name-el = یوٙنانی
language-name-en = ئینگیلیسی
language-name-en_AU = ئینگیلیسی ئوستارالیایی
language-name-en_CA = ئینگیلیسی کانادایی
language-name-en_GB = ئینگیلیسی بئریتانیایی
language-name-en_US = ئینگیلیسی ئمریکایی
language-name-eo = ئسپئرانتو
language-name-es = ئسپانیایی
language-name-es_419 = ئسپانیایی ئمریکا لاتین
language-name-es_ES = ئسپانیایی ئوروٙپا
language-name-es_MX = ئسپانیایی مئکزیک
language-name-et = ئستونیایی
language-name-eu = باسکی
language-name-fa = فارسی
language-name-fi = فأنلاندی
language-name-fil = فیلیپینی
language-name-fj = فیجی
language-name-fo = فاروٙسی
language-name-fr = فآرانسئ ئی
language-name-fr_CA = فآرانسئ ئی کانادا
language-name-fr_CH = فآرانسئ ئی سوٙییس
language-name-fy = فئریسی أفتونئشین
language-name-ga = ئیرلأندی
language-name-gag = گاگائوز
language-name-gl = گالیسی
language-name-gn = گوٙآرانی
language-name-gsw = آلمانی سوٙئیسی
language-name-gu = گوجأراتی
language-name-guz = گوٙسی
language-name-gv = مانکس
language-name-ha = ھائوسا
language-name-haw = ھاڤایی
language-name-he = عئبری
language-name-hi = ھئنی
language-name-hr = کوروڤاتی
language-name-hsb = سوربی ڤارو
language-name-ht = ھاییتی
language-name-hu = مأجاری
language-name-hy = أرمأنی
language-name-id = أندونئزیایی
language-name-ig = ئیگبو
language-name-ii = سی چوان یی
language-name-is = ئیسلأندی
language-name-it = ئیتالیایی
language-name-iu = ئینوکتیتوٙت
language-name-ja = جاپوٙنی
language-name-jgo = نئگوٙمبا
language-name-jmc = ماچامئ
language-name-jv = جاڤئ یی
language-name-ka = گورجی
language-name-kab = کابیلئ
language-name-kam = کامبا
language-name-kde = ماکوٙندئ
language-name-kea = کاباردینو
language-name-khq = کی یورا چینی
language-name-ki = کیکیوٙ
language-name-kk = قأزاق
language-name-kl = کالالیسوٙت
language-name-kln = کالئجین
language-name-km = خئمئر
language-name-kn = کاناد
language-name-ko = کورئ یی
language-name-koi = کومی پئرمیاک
language-name-kok = کوٙنکانی
language-name-ks = کأشمیری
language-name-ksb = شامبالا
language-name-ksf = بافیا
language-name-ku = کوردی کورمانجی
language-name-kw = کورنیش
language-name-ky = قئرقیزی
language-name-la = لاتین
language-name-lag = لانگی
language-name-lb = لوٙکزامبوٙرگی
language-name-lg = گاندا
language-name-lkt = لاکوٙتا
language-name-ln = لینگالا
language-name-lo = لاو
language-name-lrc = لۊری شومالی
language-name-lt = لیتوڤانیایی
language-name-lu = لوٙبا کاتانگا
language-name-luo = لوٙ
language-name-luy = لوٙئیا
language-name-lv = لاتوڤیایی
language-name-mas = ماسایی
language-name-mer = مئرو
language-name-mfe = موٙریسی
language-name-mg = مالاگاشی
language-name-mgh = ماخوڤا میتو
language-name-mgo = مئتاٛ
language-name-mi = مائوری
language-name-mk = مأقدوٙنی
language-name-ml = مالایام
language-name-mn = موغولی
language-name-moh = موٙھاڤک
language-name-mr = مأراتی
language-name-ms = مالایی
language-name-mt = مالتی
language-name-mua = موٙندانگ
language-name-my = بئرمئ یی
language-name-mzn = مازأندأرانی
language-name-naq = ناما
language-name-nb = نورڤئجی بوٙکمال
language-name-nd = نئدئبئلئ شومالی
language-name-nds = آلمانی ھاری
language-name-nds_NL = آلمانی ھارگە جا
language-name-ne = نئپالی
language-name-nl = ھولأندی
language-name-nl_BE = فئلاماندی
language-name-nmg = کئڤاسیوٙ
language-name-nn = نورڤئجی نینورسک
language-name-nqo = نئکوٙ
language-name-nus = نیوٙئر
language-name-nyn = نیان کوٙلئ
language-name-om = ئوروموٙ
language-name-or = ئوریا
language-name-pa = پأنجابی
language-name-pl = لأھئستانی
language-name-ps = پأشتوٙ
language-name-pt = پورتئغالی
language-name-pt_BR = پورتئغالی بئرئزیل
language-name-pt_PT = پورتئغالی ئوروٙپایی
language-name-qu = کوچوٙا
language-name-quc = کیچی
language-name-rm = رومانش
language-name-rn = راندی
language-name-ro = رومانیایی
language-name-ro_MD = رومانیایی مولداڤی
language-name-rof = رومبو
language-name-ru = روٙسی
language-name-rw = کینیاروآندا
language-name-rwk = رئڤا
language-name-sa = سانسکئریت
language-name-saq = سامبوٙروٙ
language-name-sbp = سانگوٙ
language-name-sd = سئندی
language-name-sdh = کوردی ھارگە
language-name-se = سامی شومالی
language-name-seh = سئنا
language-name-ses = کیارابورو سئنی
language-name-sg = سانگو
language-name-shi = تاچئلھیت
language-name-si = سینھالا
language-name-sk = ئسلوڤاکی
language-name-sl = ئسلوڤئنیایی
language-name-sma = سامی ھارگە
language-name-smj = لۉلئ سامی
language-name-smn = ئیناری سامی
language-name-sms = ئسکولت سامی
language-name-sn = شونا
language-name-so = سوٙمالی
language-name-sq = آلبانی
language-name-sr = سئربی
language-name-su = سوٙدانی
language-name-sv = سوٙئدی
language-name-sw = سأڤاحیلی
language-name-sw_CD = سأڤاحیلی کونگو
language-name-ta = تامیل
language-name-te = تئلئگو
language-name-teo = تئسو
language-name-tg = تاجیکی
language-name-th = تایلأندی
language-name-ti = تیگرینیا
language-name-tk = تورکأمأنی
language-name-to = توٙنگان
language-name-tr = تورکی
language-name-tt = تاتار
language-name-twq = تاساڤاق
language-name-tzm = تامازیغ مینجایی
language-name-ug = ئویغوٙر
language-name-uk = ئوکراینی
language-name-und = زوٙن نادیار
language-name-ur = ئوردوٙ
language-name-uz = ئوزبأکی
language-name-vai = ڤای
language-name-vi = ڤییئتنامی
language-name-vun = ڤوٙنجوٙ
language-name-wbp = ڤارلپیری
language-name-wo = ڤولوف
language-name-xh = خوٙسا
language-name-xog = سوٙگا
language-name-yo = یوروبا
language-name-zgh = تامازیغ مأراکئشی
language-name-zh = چینی
language-name-zh_Hans = چینی سادە بیە
language-name-zh_Hant = چینی سونأتی
language-name-zu = زولو
language-name-zxx = بی نئشوٙ
