language-name-aa = Afar
language-name-ab = Abkażjan
language-name-ace = Aċiniż
language-name-ach = Akoli
language-name-ada = Adangme
language-name-ady = Adyghe
language-name-ae = Avestan
language-name-af = Afrikans
language-name-afh = Afriħili
language-name-agq = Aghem
language-name-ain = Ajnu
language-name-ak = Akan
language-name-akk = Akkadjen
language-name-ale = Aleut
language-name-alt = Altai tan-Nofsinhar
language-name-am = Amhariku
language-name-an = Aragoniż
language-name-ang = Ingliż Antik
language-name-anp = Angika
language-name-ar = Għarbi
language-name-ar_001 = Għarbi Standard Modern
language-name-arc = Aramajk
language-name-arn = Mapuche
language-name-arp = Arapaho
language-name-arw = Arawak
language-name-as = Assamiż
language-name-asa = Asu
language-name-ast = Asturian
language-name-av = Avarik
language-name-awa = Awadhi
language-name-ay = Aymara
language-name-az = Ażerbajġani
language-name-ba = Bashkir
language-name-bal = Baluċi
language-name-ban = Baliniż
language-name-bas = Basa
language-name-be = Belarussu
language-name-bej = Beja
language-name-bem = Bemba
language-name-bez = Bena
language-name-bg = Bulgaru
language-name-bho = Bhojpuri
language-name-bi = Bislama
language-name-bik = Bikol
language-name-bin = Bini
language-name-bla = Siksika
language-name-bm = Bambara
language-name-bn = Bengali
language-name-bo = Tibetjan
language-name-br = Breton
language-name-bra = Braj
language-name-brx = Bodo
language-name-bs = Bożnijaku
language-name-bua = Burjat
language-name-bug = Buginese
language-name-byn = Blin
language-name-ca = Katalan
language-name-cad = Kaddo
language-name-car = Karib
language-name-cch = Atsam
language-name-ce = Chechen
language-name-ceb = Cebuano
language-name-cgg = Chiga
language-name-ch = Chamorro
language-name-chb = Chibcha
language-name-chg = Chagatai
language-name-chk = Ċukiż
language-name-chm = Mari
language-name-chn = Chinook Jargon
language-name-cho = Choctaw
language-name-chp = Ċipewjan
language-name-chr = Cherokee
language-name-chy = Cheyenne
language-name-ckb = Kurd Ċentrali
language-name-co = Korsiku
language-name-cop = Koptiku
language-name-cr = Cree
language-name-crh = Tork tal-Krimea
language-name-crs = Franċiż tas-Seselwa Creole
language-name-cs = Ċek
language-name-csb = Kashubian
language-name-cu = Slaviku tal-Knisja
language-name-cv = Chuvash
language-name-cy = Welsh
language-name-da = Daniż
language-name-dak = Dakota
language-name-dar = Dargwa
language-name-dav = Taita
language-name-de = Ġermaniż
language-name-de_AT = Ġermaniż Awstrijak
language-name-de_CH = Ġermaniż Żvizzeru
language-name-del = Delawerjan
language-name-den = Slav
language-name-dgr = Dogrib
language-name-din = Dinka
language-name-dje = Zarma
language-name-doi = Dogri
language-name-dsb = Sorbjan Komuni
language-name-dua = Dwala
language-name-dum = Olandiż Medjevali
language-name-dv = Divehi
language-name-dyo = Jola-Fonyi
language-name-dyu = Dyula
language-name-dz = Dzongkha
language-name-dzg = Dazaga
language-name-ebu = Embu
language-name-ee = Ewe
language-name-efi = Efik
language-name-eka = Ekajuk
language-name-el = Grieg
language-name-elx = Elamit
language-name-en = Ingliż
language-name-en_AU = Ingliż Awstraljan
language-name-en_CA = Ingliż Kanadiż
language-name-en_GB = Ingliż Brittaniku
language-name-en_US = Ingliż Amerikan
language-name-enm = Ingliż Medjevali
language-name-eo = Esperanto
language-name-es = Spanjol
language-name-es_419 = Spanjol Latin Amerikan
language-name-es_ES = Spanjol Ewropew
language-name-es_MX = Spanjol tal-Messiku
language-name-et = Estonjan
language-name-eu = Bask
language-name-ewo = Ewondo
language-name-fa = Persjan
language-name-fan = Fang
language-name-fat = Fanti
language-name-ff = Fulah
language-name-fi = Finlandiż
language-name-fil = Filippin
language-name-fj = Fiġjan
language-name-fo = Faroese
language-name-fon = Fon
language-name-fr = Franċiż
language-name-fr_CA = Franċiż Kanadiż
language-name-fr_CH = Franċiż Żvizzeru
language-name-frm = Franċiż Medjevali
language-name-fro = Franċiż Antik
language-name-fur = Frijuljan
language-name-fy = Frisian tal-Punent
language-name-ga = Irlandiż
language-name-gaa = Ga
language-name-gay = Gayo
language-name-gba = Gbaya
language-name-gd = Galliku Skoċċiż
language-name-gez = Geez
language-name-gil = Gilbertjan
language-name-gl = Galiċjan
language-name-gmh = Ġermaniż Medjevali Pulit
language-name-gn = Guarani
language-name-goh = Ġermaniż Antik, Pulit
language-name-gon = Gondi
language-name-gor = Gorontalo
language-name-got = Gotiku
language-name-grb = Grebo
language-name-grc = Grieg, Antik
language-name-gsw = Ġermaniż tal-Iżvizzera
language-name-gu = Gujarati
language-name-guz = Gusii
language-name-gv = Manx
language-name-gwi = Gwiċin
language-name-ha = Hausa
language-name-hai = Haida
language-name-haw = Ħawajjan
language-name-he = Ebrajk
language-name-hi = Hindi
language-name-hil = Hiligaynon
language-name-hit = Hittite
language-name-hmn = Hmong
language-name-ho = Hiri Motu
language-name-hr = Kroat
language-name-hsb = Sorbjan ta’ Fuq
language-name-ht = Creole ta’ Haiti
language-name-hu = Ungeriż
language-name-hup = Hupa
language-name-hy = Armen
language-name-hz = Herero
language-name-ia = Interlingua
language-name-iba = Iban
language-name-ibb = Ibibio
language-name-id = Indoneżjan
language-name-ie = Interlingue
language-name-ig = Igbo
language-name-ii = Sichuan Yi
language-name-ik = Inupjak
language-name-ilo = Iloko
language-name-inh = Ingush
language-name-io = Ido
language-name-is = Iżlandiż
language-name-it = Taljan
language-name-iu = Inuktitut
language-name-ja = Ġappuniż
language-name-jbo = Lojban
language-name-jgo = Ngomba
language-name-jmc = Machame
language-name-jpr = Lhudi-Persjan
language-name-jrb = Lhudi-Għarbi
language-name-jv = Ġavaniż
language-name-ka = Ġorġjan
language-name-kaa = Kara-Kalpak
language-name-kab = Kabuljan
language-name-kac = Kachin
language-name-kaj = Jju
language-name-kam = Kamba
language-name-kaw = Kawi
language-name-kbd = Kabardian
language-name-kcg = Tyap
language-name-kde = Makonde
language-name-kea = Cape Verdjan
language-name-kfo = Koro
language-name-kg = Kongo
language-name-kha = Khasi
language-name-kho = Kotaniż
language-name-khq = Koyra Chiini
language-name-ki = Kikuju
language-name-kj = Kuanyama
language-name-kk = Każak
language-name-kkj = Kako
language-name-kl = Kalallisut
language-name-kln = Kalenjin
language-name-km = Khmer
language-name-kmb = Kimbundu
language-name-kn = Kannada
language-name-ko = Korean
language-name-kok = Konkani
language-name-kos = Kosrejan
language-name-kpe = Kpelle
language-name-kr = Kanuri
language-name-krc = Karachay-Balkar
language-name-krl = Kareljan
language-name-kru = Kurux
language-name-ks = Kashmiri
language-name-ksb = Shambala
language-name-ksf = Bafia
language-name-ksh = Kolonjan
language-name-ku = Kurd
language-name-kum = Kumyk
language-name-kut = Kutenaj
language-name-kv = Komi
language-name-kw = Korniku
language-name-ky = Kirgiż
language-name-la = Latin
language-name-lad = Ladino
language-name-lag = Langi
language-name-lah = Lahnda
language-name-lam = Lamba
language-name-lb = Lussemburgiż
language-name-lez = Leżgjan
language-name-lg = Ganda
language-name-li = Limburgish
language-name-lkt = Lakota
language-name-ln = Lingaljan
language-name-lo = Laosjan
language-name-lol = Mongo
language-name-loz = Lożi
language-name-lrc = Luri tat-Tramuntana
language-name-lt = Litwan
language-name-lu = Luba-Katanga
language-name-lua = Luba-Luluwa
language-name-lui = Luiseno
language-name-lun = Lunda
language-name-luo = Luo
language-name-lus = Mizo
language-name-luy = Luyia
language-name-lv = Latvjan
language-name-mad = Maduriż
language-name-mag = Magahi
language-name-mai = Maithili
language-name-mak = Makasar
language-name-man = Mandingo
language-name-mas = Masai
language-name-mdf = Moksha
language-name-mdr = Mandar
language-name-men = Mende
language-name-mer = Meru
language-name-mfe = Morisyen
language-name-mg = Malagasy
language-name-mga = Irlandiż Medjevali
language-name-mgh = Makhuwa-Meetto
language-name-mgo = Metà
language-name-mh = Marshalljaniż
language-name-mi = Maori
language-name-mic = Micmac
language-name-min = Minangkabau
language-name-mk = Maċedonjan
language-name-ml = Malayalam
language-name-mn = Mongoljan
language-name-mnc = Manchu
language-name-mni = Manipuri
language-name-moh = Mohawk
language-name-mos = Mossi
language-name-mr = Marathi
language-name-ms = Malay
language-name-mt = Malti
language-name-mua = Mundang
language-name-mul = Lingwi Diversi
language-name-mus = Kriek
language-name-mwl = Mirandiż
language-name-mwr = Marwari
language-name-my = Burmiż
language-name-myv = Erzya
language-name-mzn = Mazanderani
language-name-na = Naurujan
language-name-nap = Naplitan
language-name-naq = Nama
language-name-nb = Bokmal Norveġiż
language-name-nd = Ndebeli tat-Tramuntana
language-name-nds = Ġermaniż Komuni
language-name-nds_NL = Sassonu Komuni
language-name-ne = Nepaliż
language-name-new = Newari
language-name-ng = Ndonga
language-name-nia = Nijas
language-name-niu = Niuean
language-name-nl = Olandiż
language-name-nl_BE = Fjamming
language-name-nmg = Kwasio
language-name-nn = Ninorsk Norveġiż
language-name-nnh = Ngiemboon
language-name-no = Norveġiż
language-name-nog = Nogai
language-name-non = Nors Antik
language-name-nqo = N’Ko
language-name-nr = Ndebele tan-Nofsinhar
language-name-nso = Soto tat-Tramuntana
language-name-nus = Nuer
language-name-nv = Navajo
language-name-nwc = Newari Klassiku
language-name-ny = Nyanja
language-name-nym = Njamweżi
language-name-nyn = Nyankole
language-name-nyo = Nyoro
language-name-nzi = Nzima
language-name-oc = Oċċitan
language-name-oj = Oġibwa
language-name-om = Oromo
language-name-or = Odia
language-name-os = Ossettiku
language-name-osa = Osaġjan
language-name-ota = Tork Ottoman
language-name-pa = Punjabi
language-name-pag = Pangasinjan
language-name-pal = Pahlavi
language-name-pam = Pampanga
language-name-pap = Papiamento
language-name-pau = Palawjan
language-name-pcm = Pidgin Niġerjan
language-name-peo = Persjan Antik
language-name-phn = Feniċju
language-name-pi = Pali
language-name-pl = Pollakk
language-name-pon = Ponpejan
language-name-prg = Prussu
language-name-pro = Provenzal Antik
language-name-ps = Pashto
language-name-pt = Portugiż
language-name-pt_BR = Portugiż tal-Brażil
language-name-pt_PT = Portugiż Ewropew
language-name-qu = Quechua
language-name-quc = K’iche’
language-name-raj = Raġastani
language-name-rap = Rapanwi
language-name-rar = Rarotongani
language-name-rm = Romanz
language-name-rn = Rundi
language-name-ro = Rumen
language-name-ro_MD = Moldovan
language-name-rof = Rombo
language-name-rom = Romanesk
language-name-root = Root
language-name-ru = Russu
language-name-rup = Aromanjan
language-name-rw = Kinjarwanda
language-name-rwk = Rwa
language-name-sa = Sanskrit
language-name-sad = Sandawe
language-name-sah = Sakha
language-name-sam = Samaritan Aramajk
language-name-saq = Samburu
language-name-sas = Sasak
language-name-sat = Santali
language-name-sba = Ngambay
language-name-sbp = Sangu
language-name-sc = Sardinjan
language-name-scn = Sqalli
language-name-sco = Skoċċiż
language-name-sd = Sindhi
language-name-se = Sami tat-Tramuntana
language-name-seh = Sena
language-name-sel = Selkup
language-name-ses = Koyraboro Senni
language-name-sg = Sango
language-name-sga = Irlandiż Antik
language-name-sh = Serbo-Kroat
language-name-shi = Tachelhit
language-name-shn = Shan
language-name-si = Sinhala
language-name-sid = Sidamo
language-name-sk = Slovakk
language-name-sl = Sloven
language-name-sm = Samoan
language-name-sma = Sami tan-Nofsinhar
language-name-smj = Lule Sami
language-name-smn = Inari Sami
language-name-sms = Skolt Sami
language-name-sn = Shona
language-name-snk = Soninke
language-name-so = Somali
language-name-sog = Sogdien
language-name-sq = Albaniż
language-name-sr = Serb
language-name-srn = Sranan Tongo
language-name-srr = Serer
language-name-ss = Swati
language-name-ssy = Saho
language-name-st = Soto tan-Nofsinhar
language-name-su = Sundaniż
language-name-suk = Sukuma
language-name-sus = Susu
language-name-sux = Sumerjan
language-name-sv = Żvediż
language-name-sw = Swahili
language-name-sw_CD = Swahili tar-Repubblika Demokratika tal-Kongo
language-name-swb = Komorjan
language-name-syr = Sirjan
language-name-ta = Tamil
language-name-te = Telugu
language-name-tem = Timne
language-name-teo = Teso
language-name-ter = Tereno
language-name-tet = Tetum
language-name-tg = Tajik
language-name-th = Tajlandiż
language-name-ti = Tigrinya
language-name-tig = Tigre
language-name-tiv = Tiv
language-name-tk = Turkmeni
language-name-tkl = Tokelau
language-name-tl = Tagalog
language-name-tlh = Klingon
language-name-tli = Tlingit
language-name-tmh = Tamashek
language-name-tn = Tswana
language-name-to = Tongan
language-name-tog = Nyasa Tonga
language-name-tpi = Tok Pisin
language-name-tr = Tork
language-name-trv = Taroko
language-name-ts = Tsonga
language-name-tsi = Tsimshian
language-name-tt = Tatar
language-name-tum = Tumbuka
language-name-tvl = Tuvalu
language-name-tw = Twi
language-name-twq = Tasawaq
language-name-ty = Taħitjan
language-name-tyv = Tuvinjan
language-name-tzm = Tamazight tal-Atlas Ċentrali
language-name-udm = Udmurt
language-name-ug = Uyghur
language-name-uga = Ugaritiku
language-name-uk = Ukren
language-name-umb = Umbundu
language-name-und = Lingwa Mhix Magħrufa
language-name-ur = Urdu
language-name-uz = Uzbek
language-name-vai = Vai
language-name-ve = Venda
language-name-vi = Vjetnamiż
language-name-vo = Volapuk
language-name-vot = Votik
language-name-vun = Vunjo
language-name-wa = Walloon
language-name-wae = Walser
language-name-wal = Walamo
language-name-war = Waray
language-name-was = Washo
language-name-wo = Wolof
language-name-xal = Kalmyk
language-name-xh = Xhosa
language-name-xog = Soga
language-name-yao = Yao
language-name-yap = Yapese
language-name-yav = Yangben
language-name-ybb = Yemba
language-name-yi = Yiddish
language-name-yo = Yoruba
language-name-yue = Kantoniż
language-name-za = Zhuang
language-name-zap = Zapotec
language-name-zen = Zenaga
language-name-zgh = Tamazight Standard tal-Marokk
language-name-zh = Ċiniż
language-name-zh_Hans = Ċiniż Simplifikat
language-name-zh_Hant = Ċiniż Tradizzjonali
language-name-zu = Zulu
language-name-zun = Zuni
language-name-zxx = Bla kontenut lingwistiku
language-name-zza = Zaza
