language-name-aa = అఫార్
language-name-ab = అబ్ఖాజియన్
language-name-ace = ఆఖినీస్
language-name-ach = అకోలి
language-name-ada = అడాంగ్మే
language-name-ady = అడిగాబ్జే
language-name-ae = అవేస్టాన్
language-name-aeb = టునీషియా అరబిక్
language-name-af = ఆఫ్రికాన్స్
language-name-afh = అఫ్రిహిలి
language-name-agq = అగేమ్
language-name-ain = ఐను
language-name-ak = అకాన్
language-name-akk = అక్కాడియాన్
language-name-ale = అలియుట్
language-name-alt = దక్షిణ ఆల్టై
language-name-am = అమ్హారిక్
language-name-an = అరగోనిస్
language-name-ang = ప్రాచీన ఆంగ్లం
language-name-anp = ఆంగిక
language-name-ar = అరబిక్
language-name-ar_001 = ఆధునిక ప్రామాణిక అరబిక్
language-name-arc = అరామేక్
language-name-arn = మపుచే
language-name-arp = అరాపాహో
language-name-arw = అరావాక్
language-name-arz = ఈజిప్షియన్ అరబిక్
language-name-as = అస్సామీస్
language-name-asa = అసు
language-name-ast = ఆస్టూరియన్
language-name-av = అవారిక్
language-name-awa = అవధి
language-name-ay = ఐమారా
language-name-az = అజర్బైజాని
language-name-ba = బష్కిర్
language-name-bal = బాలుచి
language-name-ban = బాలినీస్
language-name-bas = బసా
language-name-be = బెలరుషియన్
language-name-bej = బేజా
language-name-bem = బెంబా
language-name-bez = బెనా
language-name-bg = బల్గేరియన్
language-name-bgn = పశ్చిమ బలూచీ
language-name-bho = భోజ్‌పురి
language-name-bi = బిస్లామా
language-name-bik = బికోల్
language-name-bin = బిని
language-name-bla = సిక్సికా
language-name-bm = బంబారా
language-name-bn = బాంగ్లా
language-name-bo = టిబెటన్
language-name-bpy = బిష్ణుప్రియ
language-name-br = బ్రెటన్
language-name-bra = బ్రాజ్
language-name-brx = బోడో
language-name-bs = బోస్నియన్
language-name-bua = బురియట్
language-name-bug = బుగినీస్
language-name-byn = బ్లిన్
language-name-ca = కాటలాన్
language-name-cad = కేడ్డో
language-name-car = కేరిబ్
language-name-cch = అట్సామ్
language-name-ce = చెచెన్
language-name-ceb = సెబుయానో
language-name-cgg = ఛిగా
language-name-ch = చమర్రో
language-name-chb = చిబ్చా
language-name-chg = చాగటై
language-name-chk = చూకీస్
language-name-chm = మారి
language-name-chn = చినూక్ జార్గన్
language-name-cho = చక్టా
language-name-chp = చిపెవ్యాన్
language-name-chr = చెరోకీ
language-name-chy = చేయేన్
language-name-ckb = సెంట్రల్ కర్డిష్
language-name-co = కోర్సికన్
language-name-cop = కోప్టిక్
language-name-cr = క్రి
language-name-crh = క్రిమియన్ టర్కిష్
language-name-crs = సెసేల్వా క్రియోల్ ఫ్రెంచ్
language-name-cs = చెక్
language-name-csb = కషుబియన్
language-name-cu = చర్చ్ స్లావిక్
language-name-cv = చువాష్
language-name-cy = వెల్ష్
language-name-da = డానిష్
language-name-dak = డకోటా
language-name-dar = డార్గ్వా
language-name-dav = టైటా
language-name-de = జర్మన్
language-name-de_AT = ఆస్ట్రియన్ జర్మన్
language-name-de_CH = స్విస్ హై జర్మన్
language-name-del = డెలావేర్
language-name-den = స్లేవ్
language-name-dgr = డోగ్రిబ్
language-name-din = డింకా
language-name-dje = జార్మా
language-name-doi = డోగ్రి
language-name-dsb = లోయర్ సోర్బియన్
language-name-dua = డ్యూలా
language-name-dum = మధ్యమ డచ్
language-name-dv = దివేహి
language-name-dyo = జోలా-ఫోనయి
language-name-dyu = డ్యులా
language-name-dz = జోంఖా
language-name-dzg = డాజాగా
language-name-ebu = ఇంబు
language-name-ee = యూ
language-name-efi = ఎఫిక్
language-name-egy = ప్రాచీన ఈజిప్షియన్
language-name-eka = ఏకాజక్
language-name-el = గ్రీక్
language-name-elx = ఎలామైట్
language-name-en = ఆంగ్లం
language-name-en_AU = ఆస్ట్రేలియన్ ఇంగ్లీష్
language-name-en_CA = కెనడియన్ ఇంగ్లీష్
language-name-en_GB = బ్రిటిష్ ఇంగ్లీష్
language-name-en_US = అమెరికన్ ఇంగ్లీష్
language-name-enm = మధ్యమ ఆంగ్లం
language-name-eo = ఎస్పెరాంటో
language-name-es = స్పానిష్
language-name-es_419 = లాటిన్ అమెరికన్ స్పానిష్
language-name-es_ES = యూరోపియన్ స్పానిష్
language-name-es_MX = మెక్సికన్ స్పానిష్
language-name-et = ఎస్టోనియన్
language-name-eu = బాస్క్యూ
language-name-ewo = ఎవోండొ
language-name-fa = పర్షియన్
language-name-fan = ఫాంగ్
language-name-fat = ఫాంటి
language-name-ff = ఫ్యుల
language-name-fi = ఫిన్నిష్
language-name-fil = ఫిలిపినో
language-name-fj = ఫిజియన్
language-name-fo = ఫారోయీజ్
language-name-fon = ఫాన్
language-name-fr = ఫ్రెంచ్
language-name-fr_CA = కెనడియెన్ ఫ్రెంచ్
language-name-fr_CH = స్విస్ ఫ్రెంచ్
language-name-frc = కాజున్ ఫ్రెంచ్
language-name-frm = మధ్యమ ప్రెంచ్
language-name-fro = ప్రాచీన ఫ్రెంచ్
language-name-frr = ఉత్తర ఫ్రిసియన్
language-name-frs = తూర్పు ఫ్రిసియన్
language-name-fur = ఫ్రియులియన్
language-name-fy = పశ్చిమ ఫ్రిసియన్
language-name-ga = ఐరిష్
language-name-gaa = గా
language-name-gag = గాగౌజ్
language-name-gan = గాన్ చైనీస్
language-name-gay = గాయో
language-name-gba = గ్బాయా
language-name-gd = స్కాటిష్ గేలిక్
language-name-gez = జీజ్
language-name-gil = గిల్బర్టీస్
language-name-gl = గాలిషియన్
language-name-gmh = మధ్యమ హై జర్మన్
language-name-gn = గ్వారనీ
language-name-goh = ప్రాచీన హై జర్మన్
language-name-gon = గోండి
language-name-gor = గోరోంటలా
language-name-got = గోథిక్
language-name-grb = గ్రేబో
language-name-grc = ప్రాచీన గ్రీక్
language-name-gsw = స్విస్ జర్మన్
language-name-gu = గుజరాతి
language-name-guz = గుస్సీ
language-name-gv = మాంక్స్
language-name-gwi = గ్విచిన్
language-name-ha = హౌసా
language-name-hai = హైడా
language-name-hak = హక్కా చైనీస్
language-name-haw = హవాయియన్
language-name-he = హీబ్రూ
language-name-hi = హిందీ
language-name-hil = హిలిగేయినోన్
language-name-hit = హిట్టిటే
language-name-hmn = మోంగ్
language-name-ho = హిరి మోటు
language-name-hr = క్రోయేషియన్
language-name-hsb = అప్పర్ సోర్బియన్
language-name-hsn = జియాంగ్ చైనీస్
language-name-ht = హైటియన్ క్రియోల్
language-name-hu = హంగేరియన్
language-name-hup = హుపా
language-name-hy = ఆర్మేనియన్
language-name-hz = హిరేరో
language-name-ia = ఇంటర్లింగ్వా
language-name-iba = ఐబాన్
language-name-ibb = ఇబిబియో
language-name-id = ఇండోనేషియన్
language-name-ie = ఇంటర్లింగ్
language-name-ig = ఇగ్బో
language-name-ii = శిషువన్ ఈ
language-name-ik = ఇనుపైయాక్
language-name-ilo = ఐలోకో
language-name-inh = ఇంగుష్
language-name-io = ఈడో
language-name-is = ఐస్లాండిక్
language-name-it = ఇటాలియన్
language-name-iu = ఇనుక్టిటుట్
language-name-ja = జపనీస్
language-name-jbo = లోజ్బాన్
language-name-jgo = గోంబా
language-name-jmc = మకొమ్
language-name-jpr = జ్యుడియో-పర్షియన్
language-name-jrb = జ్యుడియో-అరబిక్
language-name-jv = జావనీస్
language-name-ka = జార్జియన్
language-name-kaa = కారా-కల్పాక్
language-name-kab = కాబిల్
language-name-kac = కాచిన్
language-name-kaj = జ్యూ
language-name-kam = కంబా
language-name-kaw = కావి
language-name-kbd = కబార్డియన్
language-name-kcg = ట్యాప్
language-name-kde = మకొండే
language-name-kea = కాబువేర్దియను
language-name-kfo = కోరో
language-name-kg = కోంగో
language-name-kha = ఖాసి
language-name-kho = ఖటోనీస్
language-name-khq = కొయరా చీన్నీ
language-name-ki = కికుయు
language-name-kj = క్వాన్యామ
language-name-kk = కజఖ్
language-name-kkj = కాకో
language-name-kl = కలాల్లిసూట్
language-name-kln = కలెంజిన్
language-name-km = ఖ్మేర్
language-name-kmb = కిమ్బుండు
language-name-kn = కన్నడ
language-name-ko = కొరియన్
language-name-koi = కోమి-పర్మాక్
language-name-kok = కొంకణి
language-name-kos = కోస్రేయన్
language-name-kpe = పెల్లే
language-name-kr = కానురి
language-name-krc = కరచే-బల్కార్
language-name-krl = కరేలియన్
language-name-kru = కూరుఖ్
language-name-ks = కాశ్మీరి
language-name-ksb = శంబాలా
language-name-ksf = బాఫియ
language-name-ksh = కొలోనియన్
language-name-ku = కుర్దిష్
language-name-kum = కుమ్యిక్
language-name-kut = కుటేనై
language-name-kv = కోమి
language-name-kw = కోర్నిష్
language-name-ky = కిర్గిజ్
language-name-la = లాటిన్
language-name-lad = లాడినో
language-name-lag = లాంగీ
language-name-lah = లాహండా
language-name-lam = లాంబా
language-name-lb = లక్సెంబర్గిష్
language-name-lez = లేజ్ఘియన్
language-name-lg = గాండా
language-name-li = లిమ్బర్గిష్
language-name-lkt = లకొటా
language-name-ln = లింగాల
language-name-lo = లావో
language-name-lol = మొంగో
language-name-lou = లూసియానా క్రియోల్
language-name-loz = లోజి
language-name-lrc = ఉత్తర లూరీ
language-name-lt = లిథువేనియన్
language-name-lu = లూబ-కటాంగ
language-name-lua = లుబా-లులువ
language-name-lui = లుయిసెనో
language-name-lun = లుండా
language-name-luo = లువో
language-name-lus = మిజో
language-name-luy = లుయియ
language-name-lv = లాట్వియన్
language-name-mad = మాదురీస్
language-name-mag = మగాహి
language-name-mai = మైథిలి
language-name-mak = మకాసార్
language-name-man = మండింగో
language-name-mas = మాసై
language-name-mdf = మోక్ష
language-name-mdr = మండార్
language-name-men = మెండే
language-name-mer = మెరు
language-name-mfe = మొరిస్యేన్
language-name-mg = మాలాగసి
language-name-mga = మధ్యమ ఐరిష్
language-name-mgh = మక్వా-మిట్టో
language-name-mgo = మెటా
language-name-mh = మార్షలీస్
language-name-mi = మయోరి
language-name-mic = మికమాక్
language-name-min = మినాంగ్‌కాబో
language-name-mk = మసడోనియన్
language-name-ml = మలయాళం
language-name-mn = మంగోలియన్
language-name-mnc = మంచు
language-name-mni = మణిపురి
language-name-moh = మోహాక్
language-name-mos = మోస్సి
language-name-mr = మరాఠీ
language-name-ms = మలాయ్
language-name-mt = మాల్టీస్
language-name-mua = మండాంగ్
language-name-mul = బహుళ భాషలు
language-name-mus = క్రీక్
language-name-mwl = మిరాండిస్
language-name-mwr = మార్వాడి
language-name-my = బర్మీస్
language-name-myv = ఎర్జియా
language-name-mzn = మాసన్‌దెరాని
language-name-na = నౌరు
language-name-nan = మిన్ నాన్ చైనీస్
language-name-nap = నియాపోలిటన్
language-name-naq = నమ
language-name-nb = నార్వేజియన్ బొక్మాల్
language-name-nd = ఉత్తర దెబెలె
language-name-nds = లో జర్మన్
language-name-nds_NL = లో సాక్సన్
language-name-ne = నేపాలి
language-name-new = నెవారి
language-name-ng = డోంగా
language-name-nia = నియాస్
language-name-niu = నాయియన్
language-name-nl = డచ్
language-name-nl_BE = ఫ్లెమిష్
language-name-nmg = క్వాసియె
language-name-nn = నార్వేజియాన్ న్యోర్స్క్
language-name-nnh = గింబూన్
language-name-no = నార్వేజియన్
language-name-nog = నోగై
language-name-non = ప్రాచిన నోర్స్
language-name-nqo = న్కో
language-name-nr = దక్షిణ దెబెలె
language-name-nso = ఉత్తర సోతో
language-name-nus = న్యుర్
language-name-nv = నవాజొ
language-name-nwc = సాంప్రదాయ న్యూయారీ
language-name-ny = న్యాన్జా
language-name-nym = న్యంవేజి
language-name-nyn = న్యాన్కోలె
language-name-nyo = నేయోరో
language-name-nzi = జీమా
language-name-oc = ఆక్సిటన్
language-name-oj = చేవా
language-name-om = ఒరోమో
language-name-or = ఒడియా
language-name-os = ఒసేటిక్
language-name-osa = ఒసాజ్
language-name-ota = ఒట్టోమన్ టర్కిష్
language-name-pa = పంజాబీ
language-name-pag = పంగాసినాన్
language-name-pal = పహ్లావి
language-name-pam = పంపన్గా
language-name-pap = పపియమేంటో
language-name-pau = పలావెన్
language-name-pcm = నైజీరియా పిడ్గిన్
language-name-peo = ప్రాచీన పర్షియన్
language-name-phn = ఫోనికన్
language-name-pi = పాలీ
language-name-pl = పోలిష్
language-name-pon = పోహ్న్పెయన్
language-name-prg = ప్రష్యన్
language-name-pro = ప్రాచీన ప్రోవెంసాల్
language-name-ps = పాష్టో
language-name-pt = పోర్చుగీస్
language-name-pt_BR = బ్రెజీలియన్ పోర్చుగీస్
language-name-pt_PT = యూరోపియన్ పోర్చుగీస్
language-name-qu = కెచువా
language-name-quc = కిచే
language-name-raj = రాజస్తానీ
language-name-rap = రాపన్యుయి
language-name-rar = రారోటొంగాన్
language-name-rm = రోమన్ష్
language-name-rn = రుండి
language-name-ro = రోమానియన్
language-name-ro_MD = మొల్డావియన్
language-name-rof = రోంబో
language-name-rom = రోమానీ
language-name-root = రూట్
language-name-ru = రష్యన్
language-name-rup = ఆరోమేనియన్
language-name-rw = కిన్యర్వాండా
language-name-rwk = ర్వా
language-name-sa = సంస్కృతం
language-name-sad = సండావి
language-name-sah = సఖా
language-name-sam = సమారిటన్ అరమేక్
language-name-saq = సంబురు
language-name-sas = ససక్
language-name-sat = సంటాలి
language-name-sba = గాంబే
language-name-sbp = సాంగు
language-name-sc = సార్డీనియన్
language-name-scn = సిసిలియన్
language-name-sco = స్కాట్స్
language-name-sd = సింధీ
language-name-sdh = దక్షిణ కుర్దిష్
language-name-se = ఉత్తర సామి
language-name-seh = సెనా
language-name-sel = సేల్కప్
language-name-ses = కోయోరాబోరో సెన్నీ
language-name-sg = సాంగో
language-name-sga = ప్రాచీన ఐరిష్
language-name-sh = సేర్బో-క్రొయేషియన్
language-name-shi = టాచెల్‌హిట్
language-name-shn = షాన్
language-name-si = సింహళం
language-name-sid = సిడామో
language-name-sk = స్లోవాక్
language-name-sl = స్లోవేనియన్
language-name-sm = సమోవన్
language-name-sma = దక్షిణ సామి
language-name-smj = లులే సామి
language-name-smn = ఇనారి సామి
language-name-sms = స్కోల్ట్ సామి
language-name-sn = షోన
language-name-snk = సోనింకి
language-name-so = సోమాలి
language-name-sog = సోగ్డియన్
language-name-sq = అల్బేనియన్
language-name-sr = సెర్బియన్
language-name-srn = స్రానన్ టోంగో
language-name-srr = సెరేర్
language-name-ss = స్వాతి
language-name-ssy = సాహో
language-name-st = దక్షిణ సోతో
language-name-su = సండానీస్
language-name-suk = సుకుమా
language-name-sus = సుసు
language-name-sux = సుమేరియాన్
language-name-sv = స్వీడిష్
language-name-sw = స్వాహిలి
language-name-sw_CD = కాంగో స్వాహిలి
language-name-swb = కొమొరియన్
language-name-syc = సాంప్రదాయ సిరియాక్
language-name-syr = సిరియాక్
language-name-ta = తమిళము
language-name-tcy = తుళు
language-name-te = తెలుగు
language-name-tem = టిమ్నే
language-name-teo = టెసో
language-name-ter = టెరెనో
language-name-tet = టేటం
language-name-tg = తజిక్
language-name-th = థాయ్
language-name-ti = తిగ్రిన్యా
language-name-tig = టీగ్రె
language-name-tiv = టివ్
language-name-tk = తుర్క్‌మెన్
language-name-tkl = టోకెలావ్
language-name-tl = టగలాగ్
language-name-tlh = క్లింగాన్
language-name-tli = ట్లింగిట్
language-name-tmh = టామషేక్
language-name-tn = స్వానా
language-name-to = టాంగాన్
language-name-tog = న్యాసా టోన్గా
language-name-tpi = టోక్ పిసిన్
language-name-tr = టర్కిష్
language-name-trv = తరోకో
language-name-ts = సోంగా
language-name-tsi = శింషీయన్
language-name-tt = టాటర్
language-name-tum = టుంబుకా
language-name-tvl = టువాలు
language-name-tw = ట్వి
language-name-twq = టసావాఖ్
language-name-ty = తహితియన్
language-name-tyv = టువినియన్
language-name-tzm = సెంట్రల్ అట్లాస్ టామాజైట్
language-name-udm = ఉడ్ముర్ట్
language-name-ug = ఉయ్‌ఘర్
language-name-uga = ఉగారిటిక్
language-name-uk = ఉక్రేనియన్
language-name-umb = ఉమ్బుండు
language-name-und = తెలియని భాష
language-name-ur = ఉర్దూ
language-name-uz = ఉజ్బెక్
language-name-vai = వాయి
language-name-ve = వెండా
language-name-vi = వియత్నామీస్
language-name-vo = వోలాపుక్
language-name-vot = వోటిక్
language-name-vun = వుంజొ
language-name-wa = వాలూన్
language-name-wae = వాల్సర్
language-name-wal = వాలేట్టా
language-name-war = వారే
language-name-was = వాషో
language-name-wbp = వార్లపిరి
language-name-wo = వొలాఫ్
language-name-wuu = వు చైనీస్
language-name-xal = కల్మిక్
language-name-xh = షోసా
language-name-xog = సొగా
language-name-yao = యాయే
language-name-yap = యాపిస్
language-name-yav = యాంగ్‌బెన్
language-name-ybb = యెంబా
language-name-yi = ఇడ్డిష్
language-name-yo = యోరుబా
language-name-yue = కాంటనీస్
language-name-za = జువాన్
language-name-zap = జపోటెక్
language-name-zbl = బ్లిసింబల్స్
language-name-zen = జెనాగా
language-name-zgh = ప్రామాణిక మొరొకన్ టామజైట్
language-name-zh = చైనీస్
language-name-zh_Hans = సరళీకృత చైనీస్
language-name-zh_Hant = సాంప్రదాయక చైనీస్
language-name-zu = జూలూ
language-name-zun = జుని
language-name-zxx = లిపి లేదు
language-name-zza = జాజా
