aa = afaršćina
ab = abchazšćina
af = afrikans
agq = aghem
ak = akanšćina
am = amharšćina
an = aragonšćina
ang = anglosaksojšćina
ar = arabšćina
ar_001 = moderna wusokoarabšćina
arn = arawkašćina
as = asamšćina
asa = pare
ast = asturšćina
av = awaršćina
ay = aymaršćina
az = azerbajdžanšćina
ba = baškiršćina
be = běłorušćina
bem = bemba
bez = bena
bg = bulgaršćina
bi = bislamšćina
bm = bambara
bn = bengalšćina
bo = tibetšćina
br = bretonšćina
brx = bodo
bs = bosnišćina
bug = bugišćina
ca = katanlanšćina
cgg = chiga
ch = čamoršćina
cho = choctawšćina
chr = cherokee
ckb = sorani
co = korsišćina
cr = kri
cs = češćina
cy = walizišćina
da = danšćina
dav = taita
de = nimšćina
de_AT = awstriska nimšćina
de_CH = šwicarska wusokonimšćina
dje = zarma
dsb = dolnoserbšćina
dua = duala
dv = divehi
dyo = jola-fonyi
dz = dzongkha
ebu = embu
ee = ewe
el = grichišćina
en = engelšćina
en_AU = awstralska engelšćina
en_CA = kanadiska engelšćina
en_GB = britiska engelšćina
en_US = ameriska engelšćina
eo = esperanto
es = špańšćina
es_419 = łatyńskoamerikańska špańšćina
es_ES = europejska špańšćina
es_MX = mexikańska špańšćina
et = estišćina
eu = baskišćina
fa = persišćina
fi = finšćina
fil = filipinšćina
fj = fidžišćina
fo = ferejšćina
fr = francojšćina
fr_CA = kanadiska francojšćina
fr_CH = šwicarska francojšćina
fy = frizišćina
ga = iršćina
gag = gagauzšćina
gd = šotišćina
gl = galicišćina
gn = guarani
got = gotišćina
gsw = šwicarska nimšćina
gu = gudžaratšćina
guz = gusii
gv = manšćina
ha = hausa
haw = hawaiišćina
he = hebrejšćina
hi = hindišćina
hr = chorwatšćina
hsb = górnoserbšćina
ht = haitišćina
hu = hungoršćina
hy = armeńšćina
ia = interlingua
id = indonešćina
ig = igbo
ii = sichuan yi
ik = inupiak
io = ido
is = islandšćina
it = italšćina
iu = inuitšćina
ja = japańšćina
jgo = ngomba
jmc = machame
jv = javašćina
ka = georgišćina
kab = kabylšćina
kam = kamba
kde = makonde
kea = kapverdšćina
khq = koyra chiini
ki = kikuyu
kk = kazachšćina
kl = grönlandšćina
kln = kalenjin
km = kambodžanšćina
kn = kannadšćina
ko = korejańšćina
koi = komi-permyak
kok = konkani
ks = kašmiršćina
ksb = šambala
ksf = bafia
ku = kurdišćina
kw = kornišćina
ky = kirgišćina
la = łatyńšćina
lag = langi
lb = luxemburgšćina
lg = gandšćina
li = limburšćina
lkt = lakotšćina
ln = lingala
lo = laošćina
lt = litawšćina
lu = luba-katanga
luo = luo
luy = luhya
lv = letišćina
mas = masaišćina
mer = meru
mfe = mauriciska kreolšćina
mg = malgašćina
mgh = makhuwa-meetto
mgo = meta’
mi = maorišćina
mk = makedońšćina
ml = malajamšćina
mn = mongolšćina
moh = mohawkšćina
mr = maratišćina
ms = malajšćina
mt = maltašćina
mua = mundang
mus = krik
my = burmašćina
na = naurušćina
naq = nama
nb = norwegske bokmål
nd = pódpołnocne ndebele
nds = dolnonimšćina
ne = nepalšćina
nl = nižozemšćina
nl_BE = flamšćina
nmg = kwasio
nn = norwegske nynorsk
no = norwegšćina
nqo = n’ko
nus = nuer
nv = navaho
nyn = nyankole
oc = okcitanšćina
om = oromo
or = orojišćina
pa = pandžabšćina
pl = pólšćina
prg = prusčina
ps = paštunšćina
pt = portugalšćina
pt_BR = brazilska portugalšćina
pt_PT = europejska portugalšćina
qu = kečua
quc = kʼicheʼ
rm = retoromańšćina
rn = kirundišćina
ro = rumunšćina
ro_MD = moldawišćina
rof = rombo
ru = rušćina
rw = kinjarwanda
rwk = rwa
sa = sanskrit
saq = samburu
sbp = sangu
sc = sardinšćina
scn = sicilianišćina
sd = sindšćina
se = lapšćina
seh = sena
ses = koyra senni
sg = sango
sh = serbochorwatšćina
shi = tašelhit
si = singalšćina
sk = słowakšćina
sl = słowjeńšćina
sm = samošćina
sma = pódpołdnjowa samišćina
smj = lule-samišćina
smn = inari-samišćina
sms = skolt-samišćina
sn = šonšćina
so = somališćina
sq = albanšćina
sr = serbišćina
ss = siswati
stq = saterfrizišćina
su = sundanšćina
sv = šwedšćina
sw = swahilišćina
sw_CD = kongojska swahilišćina
ta = tamilšćina
te = telugšćina
teo = teso
tg = tadžikišćina
th = thailandšćina
ti = tigrinja
tk = turkmeńšćina
tl = tagalog
tn = tswana
to = tonganšćina
tr = turkojšćina
ts = tsonga
tt = tataršćina
tw = twi
twq = tasawaq
ty = tahitišćina
tzm = centralnoatlaski tamazight
ug = ujguršćina
uk = ukrainšćina
und = njeznata rěc
ur = urdušćina
uz = usbekšćina
vai = vai
vi = vietnamšćina
vo = volapük
vun = vunjo
wa = walonšćina
wo = wolof
xh = xhosa
xog = soga
yi = jidišćina
yo = jorubšćina
za = zhuang
zgh = standardny marokkański tamazight
zh = chinšćina
zu = zulu
zxx = žedno rěcne wopśimjeśe
