ace = achenés
ady = adigeo
alt = altái del sur
arp = arapajó
bla = siksiká
eu = vasco
fon = fon
goh = alemán de la alta edad antigua
grc = griego clásico
gu = gujarati
ht = haitiano
kbd = cabardiano
lo = laosiano
luo = luo
nr = ndebele del sur
prg = prusiano antiguo
rm = retorrománico
sma = sami del sur
st = sesotho del sur
sw = swahili
syr = siríaco
tet = tetun
tzm = tamazight del Marruecos Central
vai = vai
wal = walamo
wuu = wu
zun = zuni
