ace = acehnés
arp = arapaho
bas = basa
bax = bamun
bho = bhojpuri
bla = siksika
dum = neerlandés medieval
enm = inglés medieval
eu = euskera
frm = francés medieval
gmh = alemán de la alta edad media
grc = griego antiguo
kbd = kabardiano
krc = karachay-balkar
lo = lao
lus = lushai
mga = irlandés medieval
nr = ndebele meridional
nso = sotho septentrional
pa = punyabí
pcm = pcm
rn = kiroundi
shu = árabe chadiano
ss = siswati
st = sesotho meridional
sw = suajili
sw_CD = suajili del Congo
syr = siriaco
tet = tetún
tn = setswana
tyv = tuviniano
wo = wolof
wuu = wuu
xal = kalmyk
zgh = tamazight marroquí estándar
