aa = Afahresch
ab = Abchahsesch
ace = Aschenehsesch
ada = Adangmesch
ady = Adygehjsch
ae = Avästahnesch
aeb = Tonehsesch Arahbesch
af = Afrikaans
afh = Afrehihlesch
agq = Aghehmesch
ain = Aijnu
ak = Akahnesch
akk = Akahdesch
ale = Ale’uhtesch
am = Amhahresch
an = Arrajonehsesch
ang = Ahl Änglesch
anp = Anjikahnesch
ar = Arahbesch
ar_001 = Schtandatt Arahbesch
arp = Arrappaho
arq = Aljehresch Arahbesch
ary = Marokahnesch Arahbesch
arz = Äjiptesch Arahbesch
as = Aßamehsesch
asa = Pare
ase = Amärrekahnesche Blendeschprohch
ast = Astuhrejahnesch
av = Avahresch
awa = Awahdesch
ay = Aimahresch
az = Asserbaidschahnesch
az_Arab = Södasserbaidschahnesch
ba = Baschkihresch
bal = Beluhtschesch
ban = Balinehsesch
bar = Bairesch
bas = Basaa-Schprohche
be = Wiißrußesch
bem = Bemba
bez = Bena
bg = Bulljahresch
bho = Bhohdschpuresch
bi = Bislahmesch
bin = Edo
bm = Bambara
bn = Bängjahlesch
bo = Tibehtesch
bpy = Bischnuprejahnesch
br = Bettohnesch
bra = Brahjesch
brh = Brahuijesch
brx = Boddo
bs = Boßnesch
bua = Burejahtesch
bug = Bujinehsesch
byn = Bilihnesch
ca = Kattalahnesch
ce = Tschätschehnesch
ceb = Zebuwahnesch
cgg = Kihja-Schprohch
ch = Chamorru
chk = Trukehsesch
chm = Mahresch
cho = Tschoktoh
chr = Tschärrokeh
chy = Tschäjänn
ckb = Zäntrahl-Kurrdesch
co = Korsesch
cop = Koptesch
cs = Tschäschesch
csb = Kaschuhbesch
cu = Kerscheßlahwesch
cv = Tschowaschesch
cy = Wallihsesch
da = Dähnesch
dak = Dakohtesch
dar = Darjihnesch
dav = Dawedahnesch
de = Deutsch
de_AT = Deutsch uß Öhßterich
de_CH = Deutsch uß de Schweijz
dgr = Dohjribesch
dje = Djerma
dsb = Niddersorbesch
dua = Du’ala
dum = Meddelnehderlängsch
dv = Divehjesch
dyo = Jola-Fonyisch
dz = Butahnesch
dzg = Dassajahnesch
ebu = Kîembu
ee = Ewe
efi = Äffiksch
egl = Emilijahnesch
egy = Ahl Äjiptesch
eka = Ekajukesch
el = Jrihschesch
en = Änglesch
en_AU = Änglesch uß Außtrahlije
en_CA = Änglesch uß Kanada
en_GB = Änglesch uß Jruhßbrettannije
en_US = Amärrekahnesch Änglesch
enm = Meddelänglesch
eo = Esperanto
es = Schpahnesch
es_419 = Schpahnesch uß Latting-Ammärrika
es_ES = Schpahnesch en Schpahneje
es_MX = Schpahnesch en Mäxikoh
esu = Zäntrahl-Juppik
et = Äßnesch
eu = Baskesch
ewo = Ewonndo
fa = Pärsesch
ff = Fulfulde
fi = Finnesch
fil = Fillipihnesch
fj = Fihdschesch
fo = Färröhresch
fon = Fohnesch
fr = Franzühsesch
fr_CA = Franzühsesch uß Kanada
fr_CH = Franzühsesch uß de Schweijz
fur = Frijauhlesch
fy = Wäßfrihsesch
ga = Ihresch
gaa = Jah
gez = Ji’is-Ahl-Ättejohpesch
gil = Jillbättehsesch
gl = Jallihzesch
gn = Juwarahnesch
gor = Jorontalohsch
gsw = Schwitzerdütsch
gu = Gutscharatesch
gv = Mangx
ha = Haußa
haw = Hauajahnesch
he = Hebrähjesch
hi = Hinndi
hil = Hiligaynon
hmn = Hmong
hr = Krowatesch
hsb = Bovversorrbesch
ht = Ha’iihtesch
hu = Unnjarresch
hup = Hupa
hy = Armehnesch
hz = Herrehro
ia = de Interlingua
iba = Ibahnesch
ibb = Ibibio
id = Indonehsesch
ig = Igbo
ilo = Ilokahnesch
inh = Engjuschesch
io = Ihdo
is = Ißlänndesch
it = Etalljähnesch
iu = Inuktitut
izh = Ingjrijahnesch
ja = Japahnesch
jam = Jamaikahnesch-Änglesch
jbo = Lodschbahn
jgo = Njomba
jpr = Jühdesch-Pärsesch
jut = Jüttesch
jv = Javahnesch
ka = Je’orjesch
kab = Kabyhlesch
kam = Kamba vun Kehnija
kbd = Kabadihnesch
kde = Chimakonde
kea = Kapvärdesch
kfo = Koro vun de Älfebeijnköß
kha = Khasi
khq = Kojra Tschihni
ki = Rekohjo
kj = Oschivambo
kk = Kassakkesch
kkj = Kako
kl = Jröhnländesch
kln = Kaländjihnesch
km = Khmer
kmb = Kimbundu
kn = Kannada
ko = Korrejaanesch
kok = Kon’kahnesch
kpe = Kpäle
kr = Kanuhresch
krc = Karatschaj-Balkahresch-Törkesch
krl = Karehlesch
kru = Korochesch
ks = Kaschmihresch
ksf = Bafijahnesch
ksh = Kölsch
ku = Kurrdesch
kum = Kumykesch
kv = Kohmesch
kw = Kornesch
ky = Kirjihsesch
la = Lateijnesch
lad = Ladihnesch
lag = Lango
lah = de Landa-Schprooche
lb = Luxemborjesch
lez = Lesjesch
lg = Lugannda
li = Lemburjesch
lkt = Lakota
ln = Lingjalla
lo = Lahootesch
loz = Silohzi
lrc = Nood-Luhresch
lt = Littouesch
lu = Kiluba
lua = Tschiluba
lun = Schilunnda
luo = Luo
luy = Luhjesch
lv = Lättesch
mdf = Mokschah
mg = Madajaßkesch
mh = Maschallehsesch
mi = Ma’ohresch
mk = Mazedohnesch
ml = Mallajalam
mn = Mongjohlesch
mni = Meitei-Manipuhresch
mr = Marrahtesch
ms = Mallaijesch
mt = Maltehsesch
mua = Mundang
mul = -ongerscheidlijje Schprohche-
mus = Krihk
mwl = Mirandehsesch
my = Burmehsesch
myv = Ärsjahnesch
na = Nauruhesch
nap = Napolletahnesch
nb = Norrwehjesch Bokmål
nd = Nood-Ndebele
nds_NL = Nehdersaksesch en de Nederläng
ne = Nepallehsesch
new = Newahresch
ng = Ndongjahnesch
nl = Holländesch
nl_BE = Flähmesch
nmg = Gyele
nn = Neu Norrwehjesch
nnh = Njijembohn
no = Norrwehjesch
nog = Nojal
nso = Nood-Sohto
nv = Navvacho
ny = Schi-Schewa
or = Oriija
os = Oßeetesch
pa = Panschaabesch
pl = Pollnesch
ps = Paschtuunesch
pt = Pochtojesesch
pt_BR = Brasilljaanesch Pochtojesesch
pt_PT = Pochtojesesch uß Pochtojall
qu = Kättschowa
quc = K’ische’
rm = Rätoromaanesch
rn = K-Rundesch
ro = Rumänesch
rof = Kirombo
ru = Rußßesch
rup = Arromahnesch
rw = Kinja-Ruandesch
sa = Sanskrit
sah = Jackutesch
sba = Njambaij
sd = Sinndi
se = Nood-Lappländesch
ses = Kojraboro Senni
sg = Sangjo
sh = Särbokowatesch
shi = Taschelhittesch
si = Singjaleesesch
sk = ẞlovakesch
sl = ẞloveenesch
sm = Sammohanesch
smj = Lule-Läppländesch
smn = Inahri Lappländesch
sn = Schi-Schona
so = Somahlesch
sq = Albahnesch
sr = Särbesch
ss = Si-Swatesch
st = Söd-Sooto
su = Sindanehsesch
sv = Schwehdesch
sw = Suahehlesch
swb = Kommohresch
syr = Sührejakkesch
ta = Tamihlesch
te = Telluhju
tet = Tetumsch
tg = Tadschihkesch
th = Tailändesch
ti = Tijrenejahnesch
tig = Tigre
tk = Törkmehnesch
tl = Tajalloch
tlh = Klingjohnesch
tn = Se-Zwahnesch
to = Tongjahnesch
tpi = Tok Pisin
tr = Törkesch
ts = Xi-Zongjahnesch
tt = Tattahresch
twq = Tasawaq
ty = Tahihtesch
tyv = Tuvinijahnesch
tzm = Tamasicht ussem meddlere Atlas
udm = Udmuchtesch
ug = Uj’juhresch
uk = Ukrainesch
umb = Umbundesch
und = -onbikannte-Schprooch-
uz = Ußbehkesch
ve = Wenda
vi = Vijätnammehsesch
vo = Volapük
wa = Walohnesch
wae = Walserdütsch
wal = Welahmo
war = Waray-Waray
wo = Woloff
xal = Kalmükkesch
xh = Isi-Khohsa
ybb = Jämmbah
yi = Jiddesch
yo = Joruhba
yue = Kanton-Schinehsesch
zu = Suhlu
zun = Suhñi
zxx = kein Schprooch
zza = Sahsajesch
