language-name-aa = अफार
language-name-ab = अब्खाजियाली
language-name-ace = अचाइनिज
language-name-ach = अकोली
language-name-ada = अदाङमे
language-name-ady = अदिघे
language-name-ae = अवेस्तान
language-name-af = अफ्रिकान्स
language-name-afh = अफ्रिहिली
language-name-agq = आघेम
language-name-ain = अइनु
language-name-ak = आकान
language-name-akk = अक्कादियाली
language-name-akz = अलाबामा
language-name-ale = अलेउट
language-name-aln = घेग अल्बानियाली
language-name-alt = दक्षिणी आल्टाइ
language-name-am = अम्हारिक
language-name-an = अरागोनी
language-name-ang = पुरातन अङ्ग्रेजी
language-name-anp = अङ्गिका
language-name-ar = अरबी
language-name-ar_001 = आधुनिक मानक अरबी
language-name-arc = अरामाइक
language-name-arn = मापुचे
language-name-aro = अराओना
language-name-arp = अरापाहो
language-name-arq = अल्जेरियाली अरबी
language-name-arw = अरावाक
language-name-ary = मोरोक्कोली अरबी
language-name-arz = इजिप्ट अरबी
language-name-as = आसामी
language-name-asa = आसु
language-name-ase = अमेरिकी साङ्केतिक भाषा
language-name-ast = अस्टुरियाली
language-name-av = अवारिक
language-name-avk = कोटावा
language-name-awa = अवधी
language-name-ay = ऐमारा
language-name-az = अजरबैजानी
language-name-ba = बास्किर
language-name-bal = बालुची
language-name-ban = बाली
language-name-bar = बाभारियाली
language-name-bas = बासा
language-name-bax = बामुन
language-name-bbc = बाताक तोबा
language-name-bbj = घोमाला
language-name-be = बेलारुसी
language-name-bej = बेजा
language-name-bem = बेम्बा
language-name-bew = बेटावी
language-name-bez = बेना
language-name-bfd = बाफुट
language-name-bfq = बडागा
language-name-bg = बुल्गेरियाली
language-name-bgn = पश्चिम बालोची
language-name-bho = भोजपुरी
language-name-bi = बिस्लाम
language-name-bik = बिकोल
language-name-bin = बिनी
language-name-bjn = बन्जार
language-name-bkm = कोम
language-name-bla = सिक्सिका
language-name-bm = बाम्बारा
language-name-bn = बंगाली
language-name-bo = तिब्बती
language-name-bpy = विष्णुप्रिया
language-name-bqi = बाख्तिआरी
language-name-br = ब्रेटन
language-name-bra = ब्रज
language-name-brh = ब्राहुइ
language-name-brx = बोडो
language-name-bs = बोस्नियाली
language-name-bss = अकुज
language-name-bua = बुरिआत
language-name-bug = बुगिनियाली
language-name-bum = बुलु
language-name-byn = ब्लिन
language-name-byv = मेडुम्बा
language-name-ca = क्याटालन
language-name-cad = काड्डो
language-name-car = क्यारिब
language-name-cay = कायुगा
language-name-cch = अट्साम
language-name-ce = चेचेन
language-name-ceb = सेबुआनो
language-name-cgg = चिगा
language-name-ch = चामोर्रो
language-name-chb = चिब्चा
language-name-chg = चागाटाई
language-name-chk = चुकेसे
language-name-chm = मारी
language-name-chn = चिनुक जार्गन
language-name-cho = चोक्टाव
language-name-chp = चिपेव्यान
language-name-chr = चेरोकी
language-name-chy = चेयेन्ने
language-name-ckb = केन्द्रीय कुर्दी
language-name-co = कोर्सिकन
language-name-cop = कोप्टिक
language-name-cps = कापिज्नोन
language-name-cr = क्री
language-name-crh = क्रिमियाली तुर्क
language-name-crs = सेसेल्वा क्रिओल फ्रान्सेली
language-name-cs = चेक
language-name-csb = कासुवियन
language-name-cu = चर्च स्लाभिक
language-name-cv = चुभास
language-name-cy = वेल्श
language-name-da = डेनिस
language-name-dak = डाकोटा
language-name-dar = दार्ग्वा
language-name-dav = ताइता
language-name-de = जर्मन
language-name-de_AT = अस्ट्रिएन जर्मन
language-name-de_CH = स्वीस हाई जर्मन
language-name-del = देलावर
language-name-dgr = दोग्रिब
language-name-din = दिन्का
language-name-dje = जर्मा
language-name-doi = डोगरी
language-name-dsb = तल्लो सोर्बियन
language-name-dtp = केन्द्रीय दुसुन
language-name-dua = दुवाला
language-name-dum = मध्य डच
language-name-dv = दिबेही
language-name-dyo = जोला-फोनिल
language-name-dyu = द्युला
language-name-dz = जोङ्खा
language-name-dzg = दाजागा
language-name-ebu = एम्बु
language-name-ee = इवी
language-name-efi = एफिक
language-name-egl = एमिलियाली
language-name-egy = पुरातन इजिप्टी
language-name-eka = एकाजुक
language-name-el = ग्रीक
language-name-elx = एलामाइट
language-name-en = अङ्ग्रेजी
language-name-en_AU = अस्ट्रेलियाली अङ्ग्रेजी
language-name-en_CA = क्यानाडेली अङ्ग्रेजी
language-name-en_GB = बेलायती अङ्ग्रेजी
language-name-en_US = अमेरिकी अङ्ग्रेजी
language-name-enm = मध्य अङ्ग्रेजी
language-name-eo = एस्पेरान्तो
language-name-es = स्पेनी
language-name-es_419 = ल्याटिन अमेरिकी स्पेनी
language-name-es_ES = युरोपेली स्पेनी
language-name-es_MX = मेक्सिकन स्पेनी
language-name-esu = केन्द्रीय युपिक
language-name-et = इस्टोनियन
language-name-eu = बास्क
language-name-ewo = इवोन्डो
language-name-ext = एक्सट्रेमादुराली
language-name-fa = फारसी
language-name-fan = फाङ
language-name-fat = फान्टी
language-name-ff = फुलाह
language-name-fi = फिनिस
language-name-fil = फिलिपिनी
language-name-fj = फिजियन
language-name-fo = फारोज
language-name-fon = फोन
language-name-fr = फ्रान्सेली
language-name-fr_CA = क्यानेडाली फ्रान्सेली
language-name-fr_CH = स्विस फ्रेन्च
language-name-frc = काहुन फ्रान्सेली
language-name-frm = मध्य फ्रान्सेली
language-name-fro = पुरातन फ्रान्सेली
language-name-frp = अर्पितान
language-name-frr = उत्तरी फ्रिजी
language-name-frs = पूर्वी फ्रिसियाली
language-name-fur = फ्रिउलियाली
language-name-fy = पश्चिमी फ्रिसियन
language-name-ga = आइरिस
language-name-gaa = गा
language-name-gag = गगाउज
language-name-gan = गान चिनियाँ
language-name-gay = गायो
language-name-gba = ग्बाया
language-name-gd = स्कटिस गाएलिक
language-name-gez = गिज
language-name-gil = गिल्बर्टी
language-name-gl = गलिसियाली
language-name-glk = गिलाकी
language-name-gmh = मध्य उच्च जर्मन
language-name-gn = गुवारानी
language-name-goh = पुरातन उच्च जर्मन
language-name-gom = गोवा कोन्कानी
language-name-gon = गोन्डी
language-name-gor = गोरोन्टालो
language-name-got = गोथिक
language-name-grb = ग्रेबो
language-name-grc = पुरातन ग्रिक
language-name-gsw = स्वीस जर्मन
language-name-gu = गुजराती
language-name-gur = फ्राफ्रा
language-name-guz = गुसी
language-name-gv = मान्क्स
language-name-gwi = गुइचिन
language-name-ha = हाउसा
language-name-hai = हाइदा
language-name-hak = हक्का चिनियाँ
language-name-haw = हवाइयन
language-name-he = हिब्रु
language-name-hi = हिन्दी
language-name-hif = फिजी हिन्दी
language-name-hil = हिलिगायनोन
language-name-hit = हिट्टिटे
language-name-hmn = हमोङ
language-name-ho = हिरी मोटु
language-name-hr = क्रोयसियाली
language-name-hsb = माथिल्लो सोर्बियन
language-name-ht = हैटियाली क्रियोल
language-name-hu = हङ्गेरियाली
language-name-hup = हुपा
language-name-hy = आर्मेनियाली
language-name-hz = हेरेरो
language-name-ia = इन्टर्लिङ्गुआ
language-name-iba = इबान
language-name-ibb = इबिबियो
language-name-id = इन्डोनेसियाली
language-name-ie = इन्टरलिङ्ग्वे
language-name-ig = इग्बो
language-name-ii = सिचुआन यि
language-name-ik = इनुपिआक्
language-name-ilo = इयोको
language-name-inh = इन्गस
language-name-io = इडो
language-name-is = आइसल्यान्डियाली
language-name-it = इटालेली
language-name-iu = इनुक्टिटुट
language-name-izh = इन्ग्रियाली
language-name-ja = जापानी
language-name-jam = जमैकाली क्रेओले अङ्ग्रेजी
language-name-jbo = लोज्बान
language-name-jgo = न्गोम्बा
language-name-jmc = माचामे
language-name-jpr = जुडियो-फारसी
language-name-jrb = जुडियो-अरबी
language-name-jut = जुटिस
language-name-jv = जाभानी
language-name-ka = जर्जियाली
language-name-kaa = कारा-काल्पाक
language-name-kab = काबिल
language-name-kac = काचिन
language-name-kaj = ज्जु
language-name-kam = काम्बा
language-name-kaw = कावी
language-name-kbd = काबार्दियाली
language-name-kbl = कानेम्बु
language-name-kcg = टुआप
language-name-kde = माकोन्डे
language-name-kea = काबुभेर्डियानु
language-name-ken = केनयाङ
language-name-kfo = कोरो
language-name-kg = कोङ्गो
language-name-kgp = काइनगाङ
language-name-kha = खासी
language-name-kho = खोटानी
language-name-khq = कोयरा चिनी
language-name-khw = खोवार
language-name-ki = किकुयु
language-name-kiu = किर्मान्जकी
language-name-kj = कुआन्यामा
language-name-kk = काजाख
language-name-kkj = काको
language-name-kl = कालालिसुट
language-name-kln = कालेन्जिन
language-name-km = खमेर
language-name-kmb = किम्बुन्डु
language-name-kn = कन्नाडा
language-name-ko = कोरियाली
language-name-koi = कोमी-पर्म्याक
language-name-kok = कोन्कानी
language-name-kos = कोस्राली
language-name-kpe = क्पेल्ले
language-name-kr = कानुरी
language-name-krc = काराचाय-बाल्कर
language-name-kri = क्रिओ
language-name-krj = किनाराय-ए
language-name-krl = करेलियन
language-name-kru = कुरुख
language-name-ks = कास्मिरी
language-name-ksb = शाम्बाला
language-name-ksf = बाफिया
language-name-ksh = कोलोग्नियाली
language-name-ku = कुर्दी
language-name-kum = कुमिक
language-name-kut = कुतेनाइ
language-name-kv = कोमी
language-name-kw = कोर्निस
language-name-ky = किर्गिज
language-name-la = ल्याटिन
language-name-lad = लाडिनो
language-name-lag = लाङ्गी
language-name-lah = लाहन्डा
language-name-lam = लाम्बा
language-name-lb = लक्जेम्बर्गी
language-name-lez = लाज्घियाली
language-name-lfn = लिङ्गुवा फ्राङ्का नोभा
language-name-lg = गान्डा
language-name-li = लिम्बुर्गी
language-name-lij = लिगुरियाली
language-name-liv = लिभोनियाली
language-name-lkt = लाकोता
language-name-lmo = लोम्बार्ड
language-name-ln = लिङ्गाला
language-name-lo = लाओ
language-name-lol = मोङ्गो
language-name-loz = लोजी
language-name-lrc = उत्तरी लुरी
language-name-lt = लिथुआनियाली
language-name-ltg = लाट्गाली
language-name-lu = लुबा-काताङ्गा
language-name-lua = लुबा-लुलुआ
language-name-lui = लुइसेनो
language-name-lun = लुन्डा
language-name-luo = लुओ
language-name-lus = मिजो
language-name-luy = लुइया
language-name-lv = लात्भियाली
language-name-lzh = साहित्यिक चिनियाँ
language-name-lzz = लाज
language-name-mad = मादुरेसे
language-name-maf = माफा
language-name-mag = मगधी
language-name-mai = मैथिली
language-name-mak = माकासार
language-name-man = मान्दिङो
language-name-mas = मसाई
language-name-mde = माबा
language-name-mdf = मोक्ष
language-name-mdr = मन्दर
language-name-men = मेन्डे
language-name-mer = मेरू
language-name-mfe = मोरिसेन
language-name-mg = मलागासी
language-name-mga = मध्य आयरिस
language-name-mgh = माखुवा-मिट्टो
language-name-mgo = मेटा
language-name-mh = मार्साली
language-name-mi = माओरी
language-name-mic = मिकमाक
language-name-min = मिनाङकाबाउ
language-name-mk = म्यासेडोनियन
language-name-ml = मलयालम
language-name-mn = मङ्गोलियाली
language-name-mnc = मान्चु
language-name-mni = मनिपुरी
language-name-moh = मोहक
language-name-mos = मोस्सी
language-name-mr = मराठी
language-name-ms = मलाय
language-name-mt = माल्टिज
language-name-mua = मुन्डाङ
language-name-mul = बहुभाषा
language-name-mus = क्रिक
language-name-mwl = मिरान्डी
language-name-mwr = माडवारी
language-name-mwv = मेन्टावाई
language-name-my = बर्मेली
language-name-mye = म्येने
language-name-myv = इर्ज्या
language-name-mzn = मजानडेरानी
language-name-na = नाउरू
language-name-nan = मिन नान चिनियाँ
language-name-nap = नेपोलिटान
language-name-naq = नामा
language-name-nb = नर्वेली बोकमाल
language-name-nd = उत्तरी न्डेबेले
language-name-nds = तल्लो जर्मन
language-name-nds_NL = तल्लो साक्सन
language-name-ne = नेपाली
language-name-new = नेवारी
language-name-ng = न्दोन्गा
language-name-nia = नियास
language-name-niu = निउएन
language-name-njo = अओ नागा
language-name-nl = डच
language-name-nl_BE = फ्लेमिस
language-name-nmg = क्वासियो
language-name-nn = नर्वेली नाइनोर्स्क
language-name-nnh = न्गिएम्बुन
language-name-no = नर्वेली
language-name-nog = नोगाइ
language-name-non = पुरानो नोर्से
language-name-nov = नोभियल
language-name-nqo = नको
language-name-nr = दक्षिण न्देबेले
language-name-nso = उत्तरी सोथो
language-name-nus = नुएर
language-name-nv = नाभाजो
language-name-nwc = परम्परागत नेवारी
language-name-ny = न्यान्जा
language-name-nym = न्यामवेजी
language-name-nyn = न्यान्कोल
language-name-nyo = न्योरो
language-name-nzi = नजिमा
language-name-oc = अक्सिटन
language-name-oj = ओजिब्वा
language-name-om = ओरोमो
language-name-or = उडिया
language-name-os = अोस्सेटिक
language-name-osa = ओसागे
language-name-ota = अटोमन तुर्की
language-name-pa = पंजाबी
language-name-pag = पाङ्गासिनान
language-name-pal = पाहलावी
language-name-pam = पामपाङ्गा
language-name-pap = पापियामेन्तो
language-name-pau = पालाउवाली
language-name-pcd = पिकार्ड
language-name-pcm = नाइजेरियाली पिड्जिन
language-name-pdc = पेन्सिलभानियाली जर्मन
language-name-peo = पुरातन फारसी
language-name-pfl = पालाटिन जर्मन
language-name-phn = फोनिसियाली
language-name-pi = पाली
language-name-pl = पोलिस
language-name-pms = पिएडमोन्तेसे
language-name-pnt = पोन्टिक
language-name-prg = प्रसियाली
language-name-pro = पुरातन प्रोभेन्काल
language-name-ps = पास्तो
language-name-pt = पोर्तुगी
language-name-pt_BR = ब्राजिली पोर्तुगी
language-name-pt_PT = युरोपेली पोर्तुगी
language-name-qu = क्वेचुवा
language-name-quc = किचे
language-name-qug = चिम्बोराजो उच्चस्थान किचुआ
language-name-raj = राजस्थानी
language-name-rap = रापानुई
language-name-rar = रारोटोङ्गान
language-name-rm = रोमानिस
language-name-rn = रुन्डी
language-name-ro = रोमानियाली
language-name-ro_MD = मोल्डाभियाली
language-name-rof = रोम्बो
language-name-root = रुट
language-name-ru = रसियाली
language-name-rup = अरोमानीयाली
language-name-rw = किन्यारवान्डा
language-name-rwk = र्‌वा
language-name-sa = संस्कृत
language-name-sad = सान्डेअ
language-name-sah = साखा
language-name-saq = साम्बुरू
language-name-sat = सान्ताली
language-name-sba = न्गामबाय
language-name-sbp = साङ्गु
language-name-sc = सार्डिनियाली
language-name-scn = सिसिलियाली
language-name-sco = स्कट्स
language-name-sd = सिन्धी
language-name-sdh = दक्षिणी कुर्दिश
language-name-se = उत्तरी सामी
language-name-seh = सेना
language-name-ses = कोयराबोरो सेन्नी
language-name-sg = साङ्गो
language-name-sga = पुरातन आयरीस
language-name-shi = टाचेल्हिट
language-name-shn = शान
language-name-shu = चाड अरबी
language-name-si = सिन्हाली
language-name-sk = स्लोभाकियाली
language-name-sl = स्लोभेनियाली
language-name-sli = तल्लो सिलेसियाली
language-name-sm = सामोआ
language-name-sma = दक्षिणी सामी
language-name-smj = लुले सामी
language-name-smn = इनारी सामी
language-name-sms = स्कोइट सामी
language-name-sn = शोना
language-name-snk = सोनिन्के
language-name-so = सोमाली
language-name-sq = अल्बानियाली
language-name-sr = सर्बियाली
language-name-srn = स्रानान टोङ्गो
language-name-ss = स्वाती
language-name-ssy = साहो
language-name-st = दक्षिणी सोथो
language-name-su = सुडानी
language-name-suk = सुकुमा
language-name-sus = सुसू
language-name-sux = सुमेरियाली
language-name-sv = स्विडिस
language-name-sw = स्वाहिली
language-name-sw_CD = कङ्गो स्वाहिली
language-name-swb = कोमोरी
language-name-syc = परम्परागत सिरियाक
language-name-syr = सिरियाक
language-name-ta = तामिल
language-name-te = तेलुगु
language-name-tem = टिम्ने
language-name-teo = टेसो
language-name-tet = टेटुम
language-name-tg = ताजिक
language-name-th = थाई
language-name-ti = टिग्रिन्या
language-name-tig = टिग्रे
language-name-tk = टर्कमेन
language-name-tlh = क्लिङ्गन
language-name-tn = ट्स्वाना
language-name-to = टोङ्गन
language-name-tog = न्यास टोङ्गा
language-name-tpi = टोक पिसिन
language-name-tr = टर्किश
language-name-trv = टारोको
language-name-ts = ट्सोङ्गा
language-name-tt = तातार
language-name-ttt = मुस्लिम टाट
language-name-tum = टुम्बुका
language-name-tvl = टुभालु
language-name-twq = तासावाक
language-name-ty = टाहिटियन
language-name-tyv = टुभिनियाली
language-name-tzm = केन्द्रीय एट्लास टामाजिघट
language-name-udm = उड्मुर्ट
language-name-ug = उइघुर
language-name-uk = युक्रेनी
language-name-umb = उम्बुन्डी
language-name-und = अज्ञात भाषा
language-name-ur = उर्दु
language-name-uz = उज्बेकी
language-name-vai = भाइ
language-name-ve = भेन्डा
language-name-vi = भियतनामी
language-name-vmf = मुख्य-फ्राङ्कोनियाली
language-name-vo = भोलापिक
language-name-vun = भुन्जो
language-name-wa = वाल्लुन
language-name-wae = वाल्सर
language-name-wal = वोलेट्टा
language-name-war = वारे
language-name-wbp = वार्ल्पिरी
language-name-wo = वुलुफ
language-name-xal = काल्मिक
language-name-xh = खोसा
language-name-xmf = मिनग्रेलियाली
language-name-xog = सोगा
language-name-yav = याङ्बेन
language-name-ybb = येम्बा
language-name-yi = यिद्दिस
language-name-yo = योरूवा
language-name-yrl = न्हिनगातु
language-name-yue = क्यान्टोनिज
language-name-zbl = ब्लिससिम्बोल्स
language-name-zgh = मानक मोरोक्कोन तामाजिघट
language-name-zh = चिनियाँ
language-name-zh_Hans = सरलिकृत चिनियाँ
language-name-zh_Hant = परम्परागत चिनियाँ
language-name-zu = जुलु
language-name-zun = जुनी
language-name-zxx = भाषिक सामग्री छैन
language-name-zza = जाजा
