language-name-aa = Αφάρ
language-name-ab = Αμπχαζικά
language-name-ace = Αχινίζ
language-name-ach = Ακολί
language-name-ada = Αντάνγκμε
language-name-ady = Αντιγκέα
language-name-ae = Αβεστάν
language-name-af = Αφρικάανς
language-name-afh = Αφριχίλι
language-name-agq = Αγκέμ
language-name-ain = Αϊνού
language-name-ak = Ακάν
language-name-akk = Ακάντιαν
language-name-ale = Αλεούτ
language-name-alt = Νότια Αλτάι
language-name-am = Αμχαρικά
language-name-an = Αραγονικά
language-name-ang = Παλαιά Αγγλικά
language-name-anp = Ανγκικά
language-name-ar = Αραβικά
language-name-ar_001 = Σύγχρονα Τυπικά Αραβικά
language-name-arc = Αραμαϊκά
language-name-arn = Αραουκανικά
language-name-arp = Αραπάχο
language-name-ars = Αραβικά Νάτζντι
language-name-arw = Αραγουάκ
language-name-as = Ασαμικά
language-name-asa = Άσου
language-name-ast = Αστουριανά
language-name-av = Αβαρικά
language-name-awa = Αγουαντί
language-name-ay = Αϊμάρα
language-name-az = Αζερμπαϊτζανικά
language-name-ba = Μπασκίρ
language-name-bal = Μπαλούτσι
language-name-ban = Μπαλινίζ
language-name-bas = Μπάσα
language-name-bax = Μπαμούν
language-name-bbj = Γκομάλα
language-name-be = Λευκορωσικά
language-name-bej = Μπέζα
language-name-bem = Μπέμπα
language-name-bez = Μπένα
language-name-bfd = Μπαφούτ
language-name-bg = Βουλγαρικά
language-name-bgn = Δυτικά Μπαλοχικά
language-name-bho = Μποζπούρι
language-name-bi = Μπισλάμα
language-name-bik = Μπικόλ
language-name-bin = Μπίνι
language-name-bkm = Κομ
language-name-bla = Σικσίκα
language-name-bm = Μπαμπάρα
language-name-bn = Βεγγαλικά
language-name-bo = Θιβετιανά
language-name-br = Βρετονικά
language-name-bra = Μπρατζ
language-name-brx = Μπόντο
language-name-bs = Βοσνιακά
language-name-bss = Ακόσι
language-name-bua = Μπουριάτ
language-name-bug = Μπουγκίζ
language-name-bum = Μπουλού
language-name-byn = Μπλιν
language-name-byv = Μεντούμπα
language-name-ca = Καταλανικά
language-name-cad = Κάντο
language-name-car = Καρίμπ
language-name-cay = Καγιούγκα
language-name-cch = Ατσάμ
language-name-ce = Τσετσενικά
language-name-ceb = Σεμπουάνο
language-name-cgg = Τσίγκα
language-name-ch = Τσαμόρο
language-name-chb = Τσίμπτσα
language-name-chg = Τσαγκατάι
language-name-chk = Τσουκίζι
language-name-chm = Μάρι
language-name-chn = Ιδιωματικά Σινούκ
language-name-cho = Τσοκτάου
language-name-chp = Τσίπιουαν
language-name-chr = Τσερόκι
language-name-chy = Σεγιέν
language-name-ckb = Κουρδικά Σοράνι
language-name-co = Κορσικανικά
language-name-cop = Κοπτικά
language-name-cr = Κρι
language-name-crh = Τουρκικά Κριμαίας
language-name-crs = Κρεολικά Γαλλικά Σεϋχελλών
language-name-cs = Τσεχικά
language-name-csb = Κασούμπιαν
language-name-cu = Εκκλησιαστικά Σλαβικά
language-name-cv = Τσουβασικά
language-name-cy = Ουαλικά
language-name-da = Δανικά
language-name-dak = Ντακότα
language-name-dar = Ντάργκουα
language-name-dav = Τάιτα
language-name-de = Γερμανικά
language-name-de_AT = Γερμανικά Αυστρίας
language-name-de_CH = Υψηλά Γερμανικά Ελβετίας
language-name-del = Ντέλαγουερ
language-name-den = Σλαβικά
language-name-dgr = Ντόγκριμπ
language-name-din = Ντίνκα
language-name-dje = Ζάρμα
language-name-doi = Ντόγκρι
language-name-dsb = Κάτω Σορβικά
language-name-dua = Ντουάλα
language-name-dum = Μέσα Ολλανδικά
language-name-dv = Ντιβέχι
language-name-dyo = Τζόλα-Φόνι
language-name-dyu = Ντογιούλα
language-name-dz = Ντζόνγκχα
language-name-dzg = Νταζάγκα
language-name-ebu = Έμπου
language-name-ee = Έουε
language-name-efi = Εφίκ
language-name-egy = Αρχαία Αιγυπτιακά
language-name-eka = Εκατζούκ
language-name-el = Ελληνικά
language-name-elx = Ελαμάιτ
language-name-en = Αγγλικά
language-name-en_AU = Αγγλικά Αυστραλίας
language-name-en_CA = Αγγλικά Καναδά
language-name-en_GB = Αγγλικά Βρετανίας
language-name-en_US = Αγγλικά Αμερικής
language-name-enm = Μέσα Αγγλικά
language-name-eo = Εσπεράντο
language-name-es = Ισπανικά
language-name-es_419 = Ισπανικά Λατινικής Αμερικής
language-name-es_ES = Ισπανικά Ευρώπης
language-name-es_MX = Ισπανικά Μεξικού
language-name-et = Εσθονικά
language-name-eu = Βασκικά
language-name-ewo = Εγουόντο
language-name-fa = Περσικά
language-name-fan = Φανγκ
language-name-fat = Φάντι
language-name-ff = Φουλά
language-name-fi = Φινλανδικά
language-name-fil = Φιλιππινικά
language-name-fj = Φίτζι
language-name-fo = Φεροϊκά
language-name-fon = Φον
language-name-fr = Γαλλικά
language-name-fr_CA = Γαλλικά Καναδά
language-name-fr_CH = Γαλλικά Ελβετίας
language-name-frm = Μέσα Γαλλικά
language-name-fro = Παλαιά Γαλλικά
language-name-frr = Βόρεια Φριζιανά
language-name-frs = Ανατολικά Φριζιανά
language-name-fur = Φριουλανικά
language-name-fy = Δυτικά Φριζικά
language-name-ga = Ιρλανδικά
language-name-gaa = Γκα
language-name-gag = Γκαγκάουζ
language-name-gay = Γκάγιο
language-name-gba = Γκμπάγια
language-name-gd = Σκωτικά Κελτικά
language-name-gez = Γκιζ
language-name-gil = Γκιλμπερτίζ
language-name-gl = Γαλικιανά
language-name-gmh = Μέσα Άνω Γερμανικά
language-name-gn = Γκουαρανί
language-name-goh = Παλαιά Άνω Γερμανικά
language-name-gon = Γκόντι
language-name-gor = Γκοροντάλο
language-name-got = Γοτθικά
language-name-grb = Γκρίμπο
language-name-grc = Αρχαία Ελληνικά
language-name-gsw = Γερμανικά Ελβετίας
language-name-gu = Γκουγιαράτι
language-name-guz = Γκούσι
language-name-gv = Μανξ
language-name-gwi = Γκουίτσιν
language-name-ha = Χάουσα
language-name-hai = Χάιντα
language-name-haw = Χαβαϊκά
language-name-he = Εβραϊκά
language-name-hi = Χίντι
language-name-hil = Χιλιγκαϊνόν
language-name-hit = Χιτίτε
language-name-hmn = Χμονγκ
language-name-ho = Χίρι Μότου
language-name-hr = Κροατικά
language-name-hsb = Άνω Σορβικά
language-name-ht = Αϊτιανά
language-name-hu = Ουγγρικά
language-name-hup = Χούπα
language-name-hy = Αρμενικά
language-name-hz = Χερέρο
language-name-ia = Ιντερλίνγκουα
language-name-iba = Ιμπάν
language-name-ibb = Ιμπίμπιο
language-name-id = Ινδονησιακά
language-name-ie = Ιντερλίνγκουε
language-name-ig = Ίγκμπο
language-name-ii = Σίτσουαν Γι
language-name-ik = Ινουπιάκ
language-name-ilo = Ιλόκο
language-name-inh = Ινγκούς
language-name-io = Ίντο
language-name-is = Ισλανδικά
language-name-it = Ιταλικά
language-name-iu = Ινούκτιτουτ
language-name-ja = Ιαπωνικά
language-name-jbo = Λόζμπαν
language-name-jgo = Νγκόμπα
language-name-jmc = Ματσάμε
language-name-jpr = Ιουδαϊκά-Περσικά
language-name-jrb = Ιουδαϊκά-Αραβικά
language-name-jv = Ιαβανικά
language-name-ka = Γεωργιανά
language-name-kaa = Κάρα-Καλπάκ
language-name-kab = Καμπίλε
language-name-kac = Κατσίν
language-name-kaj = Τζου
language-name-kam = Κάμπα
language-name-kaw = Κάουι
language-name-kbd = Καμπαρντιανά
language-name-kbl = Κανέμπου
language-name-kcg = Τιάπ
language-name-kde = Μακόντε
language-name-kea = Γλώσσα του Πράσινου Ακρωτηρίου
language-name-kfo = Κόρο
language-name-kg = Κονγκό
language-name-kha = Κάσι
language-name-kho = Κοτανικά
language-name-khq = Κόιρα Τσίνι
language-name-ki = Κικούγιου
language-name-kj = Κουανιάμα
language-name-kk = Καζακικά
language-name-kkj = Κάκο
language-name-kl = Καλαάλισουτ
language-name-kln = Καλεντζίν
language-name-km = Χμερ
language-name-kmb = Κιμπούντου
language-name-kn = Κανάντα
language-name-ko = Κορεατικά
language-name-koi = Κόμι-Περμιάκ
language-name-kok = Κονκανικά
language-name-kos = Κοσραενικά
language-name-kpe = Κπέλε
language-name-kr = Κανούρι
language-name-krc = Καρατσάι-Μπαλκάρ
language-name-krl = Καρελικά
language-name-kru = Κουρούχ
language-name-ks = Κασμιρικά
language-name-ksb = Σαμπάλα
language-name-ksf = Μπάφια
language-name-ksh = Κολωνικά
language-name-ku = Κουρδικά
language-name-kum = Κουμγιούκ
language-name-kut = Κουτενάι
language-name-kv = Κόμι
language-name-kw = Κορνουαλικά
language-name-ky = Κιργιζικά
language-name-la = Λατινικά
language-name-lad = Λαδίνο
language-name-lag = Λάνγκι
language-name-lah = Λάχδα
language-name-lam = Λάμπα
language-name-lb = Λουξεμβουργιανά
language-name-lez = Λεζγκικά
language-name-lg = Γκάντα
language-name-li = Λιμβουργιανά
language-name-lkt = Λακότα
language-name-ln = Λινγκάλα
language-name-lo = Λαοτινά
language-name-lol = Μόνγκο
language-name-loz = Λόζι
language-name-lrc = Βόρεια Λούρι
language-name-lt = Λιθουανικά
language-name-lu = Λούμπα-Κατάνγκα
language-name-lua = Λούμπα-Λουλούα
language-name-lui = Λουισένο
language-name-lun = Λούντα
language-name-luo = Λούο
language-name-lus = Μίζο
language-name-luy = Λουχία
language-name-lv = Λετονικά
language-name-mad = Μαντουρίζ
language-name-maf = Μάφα
language-name-mag = Μαγκάχι
language-name-mai = Μαϊτχίλι
language-name-mak = Μακασάρ
language-name-man = Μαντίνγκο
language-name-mas = Μασάι
language-name-mde = Μάμπα
language-name-mdf = Μόκσα
language-name-mdr = Μανδάρ
language-name-men = Μέντε
language-name-mer = Μέρου
language-name-mfe = Μορισιέν
language-name-mg = Μαλγασικά
language-name-mga = Μέσα Ιρλανδικά
language-name-mgh = Μακούβα-Μέτο
language-name-mgo = Μέτα
language-name-mh = Μαρσαλέζικα
language-name-mi = Μαορί
language-name-mic = Μικμάκ
language-name-min = Μινανγκαμπάου
language-name-mk = Σλαβομακεδονικά
language-name-ml = Μαλαγιαλαμικά
language-name-mn = Μογγολικά
language-name-mnc = Μαντσού
language-name-mni = Μανιπούρι
language-name-moh = Μοχόκ
language-name-mos = Μόσι
language-name-mr = Μαραθικά
language-name-ms = Μαλαισιανά
language-name-mt = Μαλτεζικά
language-name-mua = Μουντάνγκ
language-name-mul = Πολλαπλές γλώσσες
language-name-mus = Κρικ
language-name-mwl = Μιραντεζικά
language-name-mwr = Μαργουάρι
language-name-my = Βιρμανικά
language-name-mye = Μιένε
language-name-myv = Έρζυα
language-name-mzn = Μαζαντεράνι
language-name-na = Ναούρου
language-name-nap = Ναπολιτανικά
language-name-naq = Νάμα
language-name-nb = Νορβηγικά Μποκμάλ
language-name-nd = Βόρεια Ντεμπέλε
language-name-nds = Κάτω Γερμανικά
language-name-nds_NL = Κάτω Γερμανικά Ολλανδίας
language-name-ne = Νεπαλικά
language-name-new = Νεγουάρι
language-name-ng = Ντόνγκα
language-name-nia = Νίας
language-name-niu = Νιούε
language-name-nl = Ολλανδικά
language-name-nl_BE = Φλαμανδικά
language-name-nmg = Κβάσιο
language-name-nn = Νορβηγικά Νινόρσκ
language-name-nnh = Νγκιεμπούν
language-name-no = Νορβηγικά
language-name-nog = Νογκάι
language-name-non = Παλαιά Νορβηγικά
language-name-nqo = Ν’Κο
language-name-nr = Νότια Ντεμπέλε
language-name-nso = Βόρεια Σόθο
language-name-nus = Νούερ
language-name-nv = Νάβαχο
language-name-nwc = Κλασικά Νεουάρι
language-name-ny = Νιάντζα
language-name-nym = Νιαμγουέζι
language-name-nyn = Νιανκόλε
language-name-nyo = Νιόρο
language-name-nzi = Νζίμα
language-name-oc = Οξιτανικά
language-name-oj = Οζιβίγουα
language-name-om = Ορόμο
language-name-or = Όντια
language-name-os = Οσετικά
language-name-osa = Οσάζ
language-name-ota = Οθωμανικά Τουρκικά
language-name-pa = Παντζαπικά
language-name-pag = Πανγκασινάν
language-name-pal = Παχλάβι
language-name-pam = Παμπάνγκα
language-name-pap = Παπιαμέντο
language-name-pau = Παλάουαν
language-name-pcm = Πίτζιν Νιγηρίας
language-name-peo = Αρχαία Περσικά
language-name-phn = Φοινικικά
language-name-pi = Πάλι
language-name-pl = Πολωνικά
language-name-pon = Πομπηικά
language-name-prg = Πρωσικά
language-name-pro = Παλαιά Προβανσάλ
language-name-ps = Πάστο
language-name-pt = Πορτογαλικά
language-name-pt_BR = Πορτογαλικά Βραζιλίας
language-name-pt_PT = Πορτογαλικά Ευρώπης
language-name-qu = Κέτσουα
language-name-quc = Κιτσέ
language-name-raj = Ραζασθάνι
language-name-rap = Ραπανούι
language-name-rar = Ραροτονγκάν
language-name-rm = Ρομανικά
language-name-rn = Ρούντι
language-name-ro = Ρουμανικά
language-name-ro_MD = Μολδαβικά
language-name-rof = Ρόμπο
language-name-rom = Ρομανί
language-name-root = Ρίζα
language-name-ru = Ρωσικά
language-name-rup = Αρομανικά
language-name-rw = Κινιαρουάντα
language-name-rwk = Ρουά
language-name-sa = Σανσκριτικά
language-name-sad = Σαντάγουε
language-name-sah = Σαχά
language-name-sam = Σαμαρίτικα Αραμαϊκά
language-name-saq = Σαμπούρου
language-name-sas = Σασάκ
language-name-sat = Σαντάλι
language-name-sba = Νγκαμπέι
language-name-sbp = Σάνγκου
language-name-sc = Σαρδηνιακά
language-name-scn = Σικελικά
language-name-sco = Σκωτικά
language-name-sd = Σίντι
language-name-sdh = Νότια Κουρδικά
language-name-se = Βόρεια Σάμι
language-name-see = Σένεκα
language-name-seh = Σένα
language-name-sel = Σελκούπ
language-name-ses = Κοϊραμπόρο Σένι
language-name-sg = Σάνγκο
language-name-sga = Παλαιά Ιρλανδικά
language-name-sh = Σερβοκροατικά
language-name-shi = Τασελχίτ
language-name-shn = Σαν
language-name-shu = Αραβικά του Τσαντ
language-name-si = Σινχαλεζικά
language-name-sid = Σιντάμο
language-name-sk = Σλοβακικά
language-name-sl = Σλοβενικά
language-name-sm = Σαμοανά
language-name-sma = Νότια Σάμι
language-name-smj = Λούλε Σάμι
language-name-smn = Ινάρι Σάμι
language-name-sms = Σκολτ Σάμι
language-name-sn = Σόνα
language-name-snk = Σονίνκε
language-name-so = Σομαλικά
language-name-sog = Σογκντιέν
language-name-sq = Αλβανικά
language-name-sr = Σερβικά
language-name-srn = Σρανάν Τόνγκο
language-name-srr = Σερέρ
language-name-ss = Σουάτι
language-name-ssy = Σάχο
language-name-st = Νότια Σόθο
language-name-su = Σουνδανικά
language-name-suk = Σουκούμα
language-name-sus = Σούσου
language-name-sux = Σουμερικά
language-name-sv = Σουηδικά
language-name-sw = Σουαχίλι
language-name-sw_CD = Κονγκό Σουαχίλι
language-name-swb = Κομοριανά
language-name-syc = Κλασικά Συριακά
language-name-syr = Συριακά
language-name-ta = Ταμιλικά
language-name-te = Τελούγκου
language-name-tem = Τίμνε
language-name-teo = Τέσο
language-name-ter = Τερένο
language-name-tet = Τέτουμ
language-name-tg = Τατζικικά
language-name-th = Ταϊλανδικά
language-name-ti = Τιγκρινικά
language-name-tig = Τίγκρε
language-name-tiv = Τιβ
language-name-tk = Τουρκμενικά
language-name-tkl = Τοκελάου
language-name-tl = Τάγκαλογκ
language-name-tlh = Κλίνγκον
language-name-tli = Τλίνγκιτ
language-name-tmh = Ταμασέκ
language-name-tn = Τσουάνα
language-name-to = Τονγκανικά
language-name-tog = Νιάσα Τόνγκα
language-name-tpi = Τοκ Πισίν
language-name-tr = Τουρκικά
language-name-trv = Ταρόκο
language-name-ts = Τσόνγκα
language-name-tsi = Τσίμσιαν
language-name-tt = Ταταρικά
language-name-tum = Τουμπούκα
language-name-tvl = Τουβαλού
language-name-tw = Τούι
language-name-twq = Τασαβάκ
language-name-ty = Ταϊτιανά
language-name-tyv = Τουβινικά
language-name-tzm = Ταμαζίτ Κεντρικού Μαρόκο
language-name-udm = Ουντμούρτ
language-name-ug = Ουιγκουρικά
language-name-uga = Ουγκαριτικά
language-name-uk = Ουκρανικά
language-name-umb = Ουμπούντου
language-name-und = Άγνωστη γλώσσα
language-name-ur = Ουρντού
language-name-uz = Ουζμπεκικά
language-name-vai = Βάι
language-name-ve = Βέντα
language-name-vi = Βιετναμικά
language-name-vo = Βολαπιούκ
language-name-vot = Βότικ
language-name-vun = Βούντζο
language-name-wa = Βαλλωνικά
language-name-wae = Βάλσερ
language-name-wal = Γουολάιτα
language-name-war = Γουάραϊ
language-name-was = Γουασό
language-name-wbp = Γουαρλπίρι
language-name-wo = Γουόλοφ
language-name-wuu = Κινεζικά Γου
language-name-xal = Καλμίκ
language-name-xh = Κόσα
language-name-xog = Σόγκα
language-name-yao = Γιάο
language-name-yap = Γιαπίζ
language-name-yav = Γιανγκμπέν
language-name-ybb = Γιέμπα
language-name-yi = Γίντις
language-name-yo = Γιορούμπα
language-name-yue = Καντονέζικα
language-name-za = Ζουάνγκ
language-name-zap = Ζάποτεκ
language-name-zbl = Σύμβολα Bliss
language-name-zen = Ζενάγκα
language-name-zgh = Τυπικά Ταμαζίτ Μαρόκου
language-name-zh = Κινεζικά
language-name-zh_Hans = Απλοποιημένα Κινεζικά
language-name-zh_Hant = Παραδοσιακά Κινεζικά
language-name-zu = Ζουλού
language-name-zun = Ζούνι
language-name-zxx = Χωρίς γλωσσολογικό περιεχόμενο
language-name-zza = Ζάζα
