language-name-aa = afar
language-name-ab = abhază
language-name-ace = aceh
language-name-ach = acoli
language-name-ada = adangme
language-name-ady = adyghe
language-name-ae = avestană
language-name-af = afrikaans
language-name-afh = afrihili
language-name-agq = aghem
language-name-ain = ainu
language-name-ak = akan
language-name-akk = akkadiană
language-name-ale = aleută
language-name-alt = altaică meridională
language-name-am = amharică
language-name-an = aragoneză
language-name-ang = engleză veche
language-name-anp = angika
language-name-ar = arabă
language-name-ar_001 = arabă standard modernă
language-name-arc = aramaică
language-name-arn = mapuche
language-name-arp = arapaho
language-name-ars = arabă najdi
language-name-arw = arawak
language-name-as = asameză
language-name-asa = asu
language-name-ast = asturiană
language-name-av = avară
language-name-awa = awadhi
language-name-ay = aymara
language-name-az = azeră
language-name-ba = bașkiră
language-name-bal = baluchi
language-name-ban = balineză
language-name-bas = basaa
language-name-bax = bamun
language-name-bbj = ghomala
language-name-be = bielorusă
language-name-bej = beja
language-name-bem = bemba
language-name-bez = bena
language-name-bfd = bafut
language-name-bg = bulgară
language-name-bgn = baluchi occidentală
language-name-bho = bhojpuri
language-name-bi = bislama
language-name-bik = bikol
language-name-bin = bini
language-name-bkm = kom
language-name-bla = siksika
language-name-bm = bambara
language-name-bn = bengaleză
language-name-bo = tibetană
language-name-br = bretonă
language-name-bra = braj
language-name-brx = bodo
language-name-bs = bosniacă
language-name-bss = akoose
language-name-bua = buriat
language-name-bug = bugineză
language-name-bum = bulu
language-name-byn = blin
language-name-byv = medumba
language-name-ca = catalană
language-name-cad = caddo
language-name-car = carib
language-name-cay = cayuga
language-name-cch = atsam
language-name-ce = cecenă
language-name-ceb = cebuană
language-name-cgg = chiga
language-name-ch = chamorro
language-name-chb = chibcha
language-name-chg = chagatai
language-name-chk = chuukese
language-name-chm = mari
language-name-chn = jargon chinook
language-name-cho = choctaw
language-name-chp = chipewyan
language-name-chr = cherokee
language-name-chy = cheyenne
language-name-ckb = kurdă centrală
language-name-co = corsicană
language-name-cop = coptă
language-name-cr = cree
language-name-crh = turcă crimeeană
language-name-crs = creolă franceză seselwa
language-name-cs = cehă
language-name-csb = cașubiană
language-name-cu = slavonă
language-name-cv = ciuvașă
language-name-cy = galeză
language-name-da = daneză
language-name-dak = dakota
language-name-dar = dargwa
language-name-dav = taita
language-name-de = germană
language-name-del = delaware
language-name-den = slave
language-name-dgr = dogrib
language-name-din = dinka
language-name-dje = zarma
language-name-doi = dogri
language-name-dsb = sorabă de jos
language-name-dua = duala
language-name-dum = neerlandeză medie
language-name-dv = divehi
language-name-dyo = jola-fonyi
language-name-dyu = dyula
language-name-dz = dzongkha
language-name-dzg = dazaga
language-name-ebu = embu
language-name-ee = ewe
language-name-efi = efik
language-name-egy = egipteană veche
language-name-eka = ekajuk
language-name-el = greacă
language-name-elx = elamită
language-name-en = engleză
language-name-enm = engleză medie
language-name-eo = esperanto
language-name-es = spaniolă
language-name-et = estonă
language-name-eu = bască
language-name-ewo = ewondo
language-name-fa = persană
language-name-fan = fang
language-name-fat = fanti
language-name-ff = fulah
language-name-fi = finlandeză
language-name-fil = filipineză
language-name-fj = fijiană
language-name-fo = faroeză
language-name-fon = fon
language-name-fr = franceză
language-name-frc = franceză cajun
language-name-frm = franceză medie
language-name-fro = franceză veche
language-name-frr = frizonă nordică
language-name-frs = frizonă orientală
language-name-fur = friulană
language-name-fy = frizonă occidentală
language-name-ga = irlandeză
language-name-gaa = ga
language-name-gag = găgăuză
language-name-gan = chineză gan
language-name-gay = gayo
language-name-gba = gbaya
language-name-gd = gaelică scoțiană
language-name-gez = geez
language-name-gil = gilbertină
language-name-gl = galiciană
language-name-gmh = germană înaltă medie
language-name-gn = guarani
language-name-goh = germană înaltă veche
language-name-gon = gondi
language-name-gor = gorontalo
language-name-got = gotică
language-name-grb = grebo
language-name-grc = greacă veche
language-name-gu = gujarati
language-name-guz = gusii
language-name-gv = manx
language-name-gwi = gwichʼin
language-name-ha = hausa
language-name-hai = haida
language-name-hak = chineză hakka
language-name-haw = hawaiiană
language-name-he = ebraică
language-name-hi = hindi
language-name-hil = hiligaynon
language-name-hit = hitită
language-name-hmn = hmong
language-name-ho = hiri motu
language-name-hr = croată
language-name-hsb = sorabă de sus
language-name-hsn = chineză xiang
language-name-ht = haitiană
language-name-hu = maghiară
language-name-hup = hupa
language-name-hy = armeană
language-name-hz = herero
language-name-ia = interlingua
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indoneziană
language-name-ie = interlingue
language-name-ig = igbo
language-name-ii = sichuan yi
language-name-ik = inupiak
language-name-ilo = iloko
language-name-inh = ingușă
language-name-io = ido
language-name-is = islandeză
language-name-it = italiană
language-name-iu = inuktitut
language-name-ja = japoneză
language-name-jbo = lojban
language-name-jgo = ngomba
language-name-jmc = machame
language-name-jpr = iudeo-persană
language-name-jrb = iudeo-arabă
language-name-jv = javaneză
language-name-ka = georgiană
language-name-kaa = karakalpak
language-name-kab = kabyle
language-name-kac = kachin
language-name-kaj = jju
language-name-kam = kamba
language-name-kaw = kawi
language-name-kbd = kabardian
language-name-kbl = kanembu
language-name-kcg = tyap
language-name-kde = makonde
language-name-kea = kabuverdianu
language-name-kfo = koro
language-name-kg = congoleză
language-name-kha = khasi
language-name-kho = khotaneză
language-name-khq = koyra chiini
language-name-ki = kikuyu
language-name-kj = kuanyama
language-name-kk = kazahă
language-name-kkj = kako
language-name-kl = kalaallisut
language-name-kln = kalenjin
language-name-km = khmeră
language-name-kmb = kimbundu
language-name-kn = kannada
language-name-ko = coreeană
language-name-koi = komi-permiak
language-name-kok = konkani
language-name-kos = kosrae
language-name-kpe = kpelle
language-name-kr = kanuri
language-name-krc = karaceai-balkar
language-name-krl = kareliană
language-name-kru = kurukh
language-name-ks = cașmiră
language-name-ksb = shambala
language-name-ksf = bafia
language-name-ksh = kölsch
language-name-ku = kurdă
language-name-kum = kumyk
language-name-kut = kutenai
language-name-kv = komi
language-name-kw = cornică
language-name-ky = kârgâză
language-name-la = latină
language-name-lad = ladino
language-name-lag = langi
language-name-lah = lahnda
language-name-lam = lamba
language-name-lb = luxemburgheză
language-name-lez = lezghian
language-name-lg = ganda
language-name-li = limburgheză
language-name-lkt = lakota
language-name-ln = lingala
language-name-lo = laoțiană
language-name-lol = mongo
language-name-lou = creolă louisianeză
language-name-loz = lozi
language-name-lrc = luri de nord
language-name-lt = lituaniană
language-name-lu = luba-katanga
language-name-lua = luba-lulua
language-name-lui = luiseno
language-name-lun = lunda
language-name-luo = luo
language-name-lus = mizo
language-name-luy = luyia
language-name-lv = letonă
language-name-mad = madureză
language-name-maf = mafa
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = makasar
language-name-man = mandingo
language-name-mas = masai
language-name-mde = maba
language-name-mdf = moksha
language-name-mdr = mandar
language-name-men = mende
language-name-mer = meru
language-name-mfe = morisyen
language-name-mg = malgașă
language-name-mga = irlandeză medie
language-name-mgh = makhuwa-meetto
language-name-mgo = meta’
language-name-mh = marshalleză
language-name-mi = maori
language-name-mic = micmac
language-name-min = minangkabau
language-name-mk = macedoneană
language-name-ml = malayalam
language-name-mn = mongolă
language-name-mnc = manciuriană
language-name-mni = manipuri
language-name-moh = mohawk
language-name-mos = mossi
language-name-mr = marathi
language-name-ms = malaeză
language-name-mt = malteză
language-name-mua = mundang
language-name-mul = mai multe limbi
language-name-mus = creek
language-name-mwl = mirandeză
language-name-mwr = marwari
language-name-my = birmană
language-name-mye = myene
language-name-myv = erzya
language-name-mzn = mazanderani
language-name-na = nauru
language-name-nan = chineză min nan
language-name-nap = napolitană
language-name-naq = nama
language-name-nb = norvegiană bokmål
language-name-nd = ndebele de nord
language-name-nds = germana de jos
language-name-nds_NL = saxona de jos
language-name-ne = nepaleză
language-name-new = newari
language-name-ng = ndonga
language-name-nia = nias
language-name-niu = niueană
language-name-nl = neerlandeză
language-name-nl_BE = flamandă
language-name-nmg = kwasio
language-name-nn = norvegiană nynorsk
language-name-nnh = ngiemboon
language-name-no = norvegiană
language-name-nog = nogai
language-name-non = nordică veche
language-name-nqo = n’ko
language-name-nr = ndebele de sud
language-name-nso = sotho de nord
language-name-nus = nuer
language-name-nv = navajo
language-name-nwc = newari clasică
language-name-ny = nyanja
language-name-nym = nyamwezi
language-name-nyn = nyankole
language-name-nyo = nyoro
language-name-nzi = nzima
language-name-oc = occitană
language-name-oj = ojibwa
language-name-om = oromo
language-name-or = odia
language-name-os = osetă
language-name-osa = osage
language-name-ota = turcă otomană
language-name-pa = punjabi
language-name-pag = pangasinan
language-name-pal = pahlavi
language-name-pam = pampanga
language-name-pap = papiamento
language-name-pau = palauană
language-name-pcm = pidgin nigerian
language-name-peo = persană veche
language-name-phn = feniciană
language-name-pi = pali
language-name-pl = poloneză
language-name-pon = pohnpeiană
language-name-prg = prusacă
language-name-pro = provensală veche
language-name-ps = paștună
language-name-pt = portugheză
language-name-qu = quechua
language-name-quc = quiché
language-name-raj = rajasthani
language-name-rap = rapanui
language-name-rar = rarotongan
language-name-rm = romanșă
language-name-rn = kirundi
language-name-ro = română
language-name-rof = rombo
language-name-rom = romani
language-name-root = root
language-name-ru = rusă
language-name-rup = aromână
language-name-rw = kinyarwanda
language-name-rwk = rwa
language-name-sa = sanscrită
language-name-sad = sandawe
language-name-sah = sakha
language-name-sam = aramaică samariteană
language-name-saq = samburu
language-name-sas = sasak
language-name-sat = santali
language-name-sba = ngambay
language-name-sbp = sangu
language-name-sc = sardiniană
language-name-scn = siciliană
language-name-sco = scots
language-name-sd = sindhi
language-name-sdh = kurdă de sud
language-name-se = sami de nord
language-name-see = seneca
language-name-seh = sena
language-name-sel = selkup
language-name-ses = koyraboro Senni
language-name-sg = sango
language-name-sga = irlandeză veche
language-name-sh = sârbo-croată
language-name-shi = tachelhit
language-name-shn = shan
language-name-shu = arabă ciadiană
language-name-si = singhaleză
language-name-sid = sidamo
language-name-sk = slovacă
language-name-sl = slovenă
language-name-sm = samoană
language-name-sma = sami de sud
language-name-smj = lule sami
language-name-smn = inari sami
language-name-sms = skolt sami
language-name-sn = shona
language-name-snk = soninke
language-name-so = somaleză
language-name-sog = sogdien
language-name-sq = albaneză
language-name-sr = sârbă
language-name-srn = sranan tongo
language-name-srr = serer
language-name-ss = swati
language-name-ssy = saho
language-name-st = sesotho
language-name-su = sundaneză
language-name-suk = sukuma
language-name-sus = susu
language-name-sux = sumeriană
language-name-sv = suedeză
language-name-sw = swahili
language-name-swb = comoreză
language-name-syc = siriacă clasică
language-name-syr = siriacă
language-name-ta = tamilă
language-name-te = telugu
language-name-tem = timne
language-name-teo = teso
language-name-ter = tereno
language-name-tet = tetum
language-name-tg = tadjică
language-name-th = thailandeză
language-name-ti = tigrină
language-name-tig = tigre
language-name-tiv = tiv
language-name-tk = turkmenă
language-name-tkl = tokelau
language-name-tl = tagalog
language-name-tlh = klingoniană
language-name-tli = tlingit
language-name-tmh = tamashek
language-name-tn = setswana
language-name-to = tongană
language-name-tog = nyasa tonga
language-name-tpi = tok pisin
language-name-tr = turcă
language-name-trv = taroko
language-name-ts = tsonga
language-name-tsi = tsimshian
language-name-tt = tătară
language-name-tum = tumbuka
language-name-tvl = tuvalu
language-name-tw = twi
language-name-twq = tasawaq
language-name-ty = tahitiană
language-name-tyv = tuvană
language-name-tzm = tamazight central marocană
language-name-udm = udmurt
language-name-ug = uigură
language-name-uga = ugaritică
language-name-uk = ucraineană
language-name-umb = umbundu
language-name-und = limbă necunoscută
language-name-ur = urdu
language-name-uz = uzbecă
language-name-vai = vai
language-name-ve = venda
language-name-vi = vietnameză
language-name-vo = volapuk
language-name-vot = votică
language-name-vun = vunjo
language-name-wa = valonă
language-name-wae = walser
language-name-wal = wolaita
language-name-war = waray
language-name-was = washo
language-name-wbp = warlpiri
language-name-wo = wolof
language-name-wuu = chineză wu
language-name-xal = calmucă
language-name-xh = xhosa
language-name-xog = soga
language-name-yao = yao
language-name-yap = yapeză
language-name-yav = yangben
language-name-ybb = yemba
language-name-yi = idiș
language-name-yo = yoruba
language-name-yue = cantoneză
language-name-za = zhuang
language-name-zap = zapotecă
language-name-zbl = simboluri Bilss
language-name-zen = zenaga
language-name-zgh = tamazight standard marocană
language-name-zh = chineză
language-name-zh_Hant = chineză tradițională
language-name-zu = zulu
language-name-zun = zuni
language-name-zxx = fară conținut lingvistic
language-name-zza = zaza
