language-name-aa = afarų
language-name-ab = abchazų
language-name-ace = ačinezų
language-name-ach = akolių
language-name-ada = adangmų
language-name-ady = adygėjų
language-name-ae = avestų
language-name-aeb = Tuniso arabų
language-name-af = afrikanų
language-name-afh = afrihili
language-name-agq = aghemų
language-name-ain = ainų
language-name-ak = akanų
language-name-akk = akadianų
language-name-akz = alabamiečių
language-name-ale = aleutų
language-name-aln = albanų kalbos gegų tarmė
language-name-alt = pietų Altajaus
language-name-am = amharų
language-name-an = aragonesų
language-name-ang = senoji anglų
language-name-anp = angikų
language-name-ar = arabų
language-name-ar_001 = šiuolaikinė standartinė arabų
language-name-arc = aramaikų
language-name-arn = mapudungunų
language-name-aro = araonų
language-name-arp = arapahų
language-name-arq = Alžyro arabų
language-name-arw = aravakų
language-name-ary = Maroko arabų
language-name-arz = Egipto arabų
language-name-as = asamų
language-name-asa = asu
language-name-ase = Amerikos ženklų kalba
language-name-ast = asturianų
language-name-av = avarikų
language-name-avk = kotava
language-name-awa = avadhi
language-name-ay = aimarų
language-name-az = azerbaidžaniečių
language-name-ba = baškirų
language-name-bal = baluči
language-name-ban = baliečių
language-name-bar = bavarų
language-name-bas = basų
language-name-bax = bamunų
language-name-bbc = batak toba
language-name-bbj = ghomalų
language-name-be = baltarusių
language-name-bej = bėjų
language-name-bem = bembų
language-name-bew = betavi
language-name-bez = benų
language-name-bfd = bafutų
language-name-bfq = badaga
language-name-bg = bulgarų
language-name-bgn = vakarų beludžių
language-name-bho = baučpuri
language-name-bi = bislama
language-name-bik = bikolų
language-name-bin = bini
language-name-bjn = bandžarų
language-name-bkm = komų
language-name-bla = siksikų
language-name-bm = bambarų
language-name-bn = bengalų
language-name-bo = tibetiečių
language-name-bpy = bišnuprijos
language-name-bqi = bakhtiari
language-name-br = bretonų
language-name-bra = brajų
language-name-brh = brahujų
language-name-brx = bodo
language-name-bs = bosnių
language-name-bss = akūsų
language-name-bua = buriatų
language-name-bug = buginezų
language-name-bum = bulu
language-name-byn = blin
language-name-byv = medumbų
language-name-ca = katalonų
language-name-cad = kado
language-name-car = karibų
language-name-cay = kaijūgų
language-name-cch = atsamų
language-name-ce = čečėnų
language-name-ceb = sebuanų
language-name-cgg = čigų
language-name-ch = čamorų
language-name-chb = čibčų
language-name-chg = čagatų
language-name-chk = čukesų
language-name-chm = marių
language-name-chn = činuk žargonas
language-name-cho = čoktau
language-name-chp = čipvėjų
language-name-chr = čerokių
language-name-chy = čajenų
language-name-ckb = soranių kurdų
language-name-co = korsikiečių
language-name-cop = koptų
language-name-cps = capiznon
language-name-cr = kry
language-name-crh = Krymo turkų
language-name-crs = Seišelių kreolų ir prancūzų
language-name-cs = čekų
language-name-csb = kašubų
language-name-cu = bažnytinė slavų
language-name-cv = čiuvašų
language-name-cy = valų
language-name-da = danų
language-name-dak = dakotų
language-name-dar = dargva
language-name-dav = taitų
language-name-de = vokiečių
language-name-de_AT = Austrijos vokiečių
language-name-de_CH = Šveicarijos aukštutinė vokiečių
language-name-del = delavero
language-name-den = slave
language-name-dgr = dogribų
language-name-din = dinkų
language-name-dje = zarmų
language-name-doi = dogri
language-name-dsb = žemutinių sorbų
language-name-dtp = centrinio Dusuno
language-name-dua = dualų
language-name-dum = Vidurio Vokietijos
language-name-dv = divehų
language-name-dyo = džiola-foni
language-name-dyu = dyulų
language-name-dz = botijų
language-name-dzg = dazagų
language-name-ebu = embu
language-name-ee = evių
language-name-efi = efik
language-name-egl = italų kalbos Emilijos tarmė
language-name-egy = senovės egiptiečių
language-name-eka = ekajuk
language-name-el = graikų
language-name-elx = elamitų
language-name-en = anglų
language-name-en_AU = Australijos anglų
language-name-en_CA = Kanados anglų
language-name-en_GB = Didžiosios Britanijos anglų
language-name-en_US = Jungtinių Valstijų anglų
language-name-enm = Vidurio Anglijos
language-name-eo = esperanto
language-name-es = ispanų
language-name-es_419 = Lotynų Amerikos ispanų
language-name-es_ES = Europos ispanų
language-name-es_MX = Meksikos ispanų
language-name-esu = centrinės Aliaskos jupikų
language-name-et = estų
language-name-eu = baskų
language-name-ewo = evondo
language-name-ext = ispanų kalbos Ekstremadūros tarmė
language-name-fa = persų
language-name-fan = fangų
language-name-fat = fanti
language-name-ff = fulahų
language-name-fi = suomių
language-name-fil = filipiniečių
language-name-fit = suomių kalbos Tornedalio tarmė
language-name-fj = fidžių
language-name-fo = farerų
language-name-fon = fon
language-name-fr = prancūzų
language-name-fr_CA = Kanados prancūzų
language-name-fr_CH = Šveicarijos prancūzų
language-name-frc = kadžunų prancūzų
language-name-frm = Vidurio Prancūzijos
language-name-fro = senoji prancūzų
language-name-frp = arpitano
language-name-frr = šiaurinių fryzų
language-name-frs = rytų fryzų
language-name-fur = friulių
language-name-fy = vakarų fryzų
language-name-ga = airių
language-name-gaa = ga
language-name-gag = gagaūzų
language-name-gan = kinų kalbos dziangsi tarmė
language-name-gay = gajo
language-name-gba = gbaja
language-name-gbz = zoroastrų dari
language-name-gez = gyz
language-name-gil = kiribati
language-name-gl = galisų
language-name-glk = gilaki
language-name-gmh = Vidurio Aukštosios Vokietijos
language-name-gn = gvaranių
language-name-goh = senoji Aukštosios Vokietijos
language-name-gom = Goa konkanių
language-name-gon = gondi
language-name-gor = gorontalo
language-name-got = gotų
language-name-grb = grebo
language-name-grc = senovės graikų
language-name-gsw = Šveicarijos vokiečių
language-name-gu = gudžaratų
language-name-guc = vajų
language-name-gur = frafra
language-name-guz = gusi
language-name-gv = meniečių
language-name-gwi = gvičino
language-name-ha = hausų
language-name-hai = haido
language-name-hak = kinų kalbos hakų tarmė
language-name-haw = havajiečių
language-name-he = hebrajų
language-name-hi = hindi
language-name-hif = Fidžio hindi
language-name-hil = hiligainonų
language-name-hit = hititų
language-name-hmn = hmong
language-name-ho = hiri motu
language-name-hr = kroatų
language-name-hsb = aukštutinių sorbų
language-name-hsn = kinų kalbos hunano tarmė
language-name-ht = Haičio
language-name-hu = vengrų
language-name-hup = hupa
language-name-hy = armėnų
language-name-hz = hererų
language-name-ia = tarpinė
language-name-iba = iban
language-name-ibb = ibibijų
language-name-id = indoneziečių
language-name-ie = interkalba
language-name-ig = igbų
language-name-ii = sičuan ji
language-name-ik = inupiakų
language-name-ilo = ilokų
language-name-inh = ingušų
language-name-io = ido
language-name-is = islandų
language-name-it = italų
language-name-iu = inukitut
language-name-izh = ingrų
language-name-ja = japonų
language-name-jam = Jamaikos kreolų anglų
language-name-jbo = loiban
language-name-jgo = ngombų
language-name-jmc = mačamų
language-name-jpr = judėjų persų
language-name-jrb = judėjų arabų
language-name-jut = danų kalbos jutų tarmė
language-name-jv = javiečių
language-name-ka = gruzinų
language-name-kaa = karakalpakų
language-name-kab = kebailų
language-name-kac = kačinų
language-name-kaj = ju
language-name-kam = kembų
language-name-kaw = kavių
language-name-kbd = kabardinų
language-name-kbl = kanembų
language-name-kcg = tyap
language-name-kde = makondų
language-name-kea = Žaliojo Kyšulio kreolų
language-name-ken = kenyang
language-name-kfo = koro
language-name-kg = Kongo
language-name-kgp = kaingang
language-name-kha = kasi
language-name-kho = kotanezų
language-name-khq = kojra čini
language-name-khw = khovarų
language-name-ki = kikujų
language-name-kiu = kirmanjki
language-name-kj = kuaniama
language-name-kk = kazachų
language-name-kkj = kako
language-name-kl = kalalisut
language-name-kln = kalenjinų
language-name-km = khmerų
language-name-kmb = kimbundu
language-name-kn = kanadų
language-name-ko = korėjiečių
language-name-koi = komių-permių
language-name-kok = konkanių
language-name-kos = kosreanų
language-name-kpe = kpelių
language-name-kr = kanurių
language-name-krc = karačiajų balkarijos
language-name-kri = krio
language-name-krj = kinaray-a
language-name-krl = karelų
language-name-kru = kuruk
language-name-ks = kašmyrų
language-name-ksb = šambalų
language-name-ksf = bafų
language-name-ksh = kolognų
language-name-ku = kurdų
language-name-kum = kumikų
language-name-kut = kutenai
language-name-kv = komi
language-name-kw = kornų
language-name-ky = kirgizų
language-name-la = lotynų
language-name-lad = ladino
language-name-lag = langi
language-name-lah = landa
language-name-lam = lamba
language-name-lb = liuksemburgiečių
language-name-lez = lezginų
language-name-lfn = naujoji frankų kalba
language-name-lg = ganda
language-name-li = limburgiečių
language-name-lij = ligūrų
language-name-liv = lyvių
language-name-lkt = lakotų
language-name-lmo = lombardų
language-name-ln = ngalų
language-name-lo = laosiečių
language-name-lol = mongų
language-name-lou = Luizianos kreolų
language-name-loz = lozių
language-name-lrc = šiaurės luri
language-name-lt = lietuvių
language-name-ltg = latgalių
language-name-lu = luba katanga
language-name-lua = luba lulua
language-name-lui = luiseno
language-name-lun = Lundos
language-name-luo = luo
language-name-lus = mizo
language-name-luy = luja
language-name-lv = latvių
language-name-lzh = klasikinė kinų
language-name-lzz = laz
language-name-mad = madurezų
language-name-maf = mafų
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = Makasaro
language-name-man = mandingų
language-name-mas = masajų
language-name-mde = mabų
language-name-mdf = mokša
language-name-mdr = mandarų
language-name-men = mende
language-name-mer = merų
language-name-mfe = morisijų
language-name-mg = malagasų
language-name-mga = Vidurio Airijos
language-name-mgh = makua-maeto
language-name-mgo = meta
language-name-mh = Maršalo Salų
language-name-mi = maorių
language-name-mic = mikmakų
language-name-min = minangkabau
language-name-mk = makedonų
language-name-ml = malajalių
language-name-mn = mongolų
language-name-mnc = manču
language-name-mni = manipurių
language-name-moh = mohok
language-name-mos = mosi
language-name-mr = maratų
language-name-mrj = vakarų mari
language-name-ms = malajiečių
language-name-mt = maltiečių
language-name-mua = mundangų
language-name-mul = kelios kalbos
language-name-mus = krykų
language-name-mwl = mirandezų
language-name-mwr = marvari
language-name-mwv = mentavai
language-name-my = birmiečių
language-name-mye = mjenų
language-name-myv = erzyjų
language-name-mzn = mazenderanių
language-name-na = naurų
language-name-nan = kinų kalbos pietų minų tarmė
language-name-nap = neapoliečių
language-name-naq = nama
language-name-nb = norvegų bukmolas
language-name-nd = šiaurės ndebelų
language-name-nds = Žemutinės Vokietijos
language-name-ne = nepaliečių
language-name-new = nevari
language-name-ng = ndongų
language-name-nia = nias
language-name-niu = niujiečių
language-name-njo = ao naga
language-name-nl = olandų
language-name-nl_BE = flamandų
language-name-nmg = kvasių
language-name-nn = naujoji norvegų
language-name-nnh = ngiembūnų
language-name-no = norvegų
language-name-nog = nogų
language-name-non = senoji norsų
language-name-nov = novial
language-name-nqo = enko
language-name-nr = pietų ndebele
language-name-nso = šiaurės Soto
language-name-nus = nuerų
language-name-nv = navajų
language-name-nwc = klasikinė nevari
language-name-ny = nianjų
language-name-nym = niamvezi
language-name-nyn = niankolų
language-name-nyo = niorų
language-name-nzi = nzima
language-name-oc = očitarų
language-name-oj = ojibva
language-name-om = oromų
language-name-or = odijų
language-name-os = osetinų
language-name-osa = osage
language-name-ota = osmanų turkų
language-name-pa = pendžabų
language-name-pag = pangasinanų
language-name-pal = vidurinė persų kalba
language-name-pam = pampangų
language-name-pap = papiamento
language-name-pau = palauliečių
language-name-pcd = pikardų
language-name-pcm = Nigerijos pidžinų
language-name-pdc = Pensilvanijos vokiečių
language-name-pdt = vokiečių kalbos žemaičių tarmė
language-name-peo = senoji persų
language-name-pfl = vokiečių kalbos Pfalco tarmė
language-name-phn = finikiečių
language-name-pi = pali
language-name-pl = lenkų
language-name-pms = italų kalbos Pjemonto tarmė
language-name-pnt = Ponto
language-name-pon = Ponapės
language-name-prg = prūsų
language-name-pro = senovės provansalų
language-name-ps = puštūnų
language-name-pt = portugalų
language-name-pt_BR = Brazilijos portugalų
language-name-pt_PT = Europos portugalų
language-name-qu = kečujų
language-name-quc = kičių
language-name-qug = Čimboraso aukštumų kečujų
language-name-raj = Radžastano
language-name-rap = rapanui
language-name-rar = rarotonganų
language-name-rgn = italų kalbos Romanijos tarmė
language-name-rif = rifų
language-name-rm = retoromanų
language-name-rn = rundi
language-name-ro = rumunų
language-name-ro_MD = moldavų
language-name-rof = rombo
language-name-rom = romų
language-name-root = rūt
language-name-rtm = rotumanų
language-name-ru = rusų
language-name-rue = rusinų
language-name-rug = Rovianos
language-name-rup = aromanių
language-name-rw = kinjaruandų
language-name-rwk = rua
language-name-sa = sanskritas
language-name-sad = sandavių
language-name-sah = jakutų
language-name-sam = samarėjų aramių
language-name-saq = sambūrų
language-name-sas = sasak
language-name-sat = santalių
language-name-saz = sauraštrų
language-name-sba = ngambajų
language-name-sbp = sangų
language-name-sc = sardiniečių
language-name-scn = siciliečių
language-name-sco = škotų
language-name-sd = sindų
language-name-sdc = sasaresų sardinų
language-name-sdh = pietų kurdų
language-name-se = šiaurės samių
language-name-see = senecų
language-name-seh = senų
language-name-sei = seri
language-name-sel = selkup
language-name-ses = kojraboro seni
language-name-sg = sango
language-name-sga = senoji airių
language-name-sgs = žemaičių
language-name-sh = serbų-kroatų
language-name-shi = tachelhitų
language-name-shn = šan
language-name-shu = chadian arabų
language-name-si = sinhalų
language-name-sid = sidamų
language-name-sk = slovakų
language-name-sl = slovėnų
language-name-sli = sileziečių žemaičių
language-name-sly = selajarų
language-name-sm = Samoa
language-name-sma = pietų samių
language-name-smj = Liuleo samių
language-name-smn = Inario samių
language-name-sms = Skolto samių
language-name-sn = šonų
language-name-snk = soninke
language-name-so = somaliečių
language-name-sog = sogdien
language-name-sq = albanų
language-name-sr = serbų
language-name-srn = sranan tongo
language-name-srr = sererų
language-name-ss = svatų
language-name-ssy = saho
language-name-st = pietų Soto
language-name-stq = Saterlendo fryzų
language-name-su = sundų
language-name-suk = sukuma
language-name-sus = susu
language-name-sux = šumerų
language-name-sv = švedų
language-name-sw = suahilių
language-name-sw_CD = Kongo suahilių
language-name-swb = Komorų
language-name-syc = klasikinė sirų
language-name-syr = sirų
language-name-szl = sileziečių
language-name-ta = tamilų
language-name-tcy = tulų
language-name-te = telugų
language-name-tem = timne
language-name-teo = teso
language-name-ter = Tereno
language-name-tet = tetum
language-name-tg = tadžikų
language-name-th = tajų
language-name-ti = tigrajų
language-name-tig = tigre
language-name-tiv = tiv
language-name-tk = turkmėnų
language-name-tkl = Tokelau
language-name-tkr = tsakurų
language-name-tl = tagalogų
language-name-tlh = klingonų
language-name-tli = tlingitų
language-name-tly = talyšų
language-name-tmh = tamašek
language-name-tn = tsvanų
language-name-to = tonganų
language-name-tog = niasa tongų
language-name-tpi = Papua pidžinų
language-name-tr = turkų
language-name-tru = turoyo
language-name-trv = Taroko
language-name-ts = tsongų
language-name-tsd = tsakonų
language-name-tsi = tsimšian
language-name-tt = totorių
language-name-ttt = musulmonų tatų
language-name-tum = tumbukų
language-name-tvl = Tuvalu
language-name-tw = tvi
language-name-twq = tasavakų
language-name-ty = taitiečių
language-name-tyv = tuvių
language-name-tzm = Centrinio Maroko tamazitų
language-name-udm = udmurtų
language-name-ug = uigūrų
language-name-uga = ugaritų
language-name-uk = ukrainiečių
language-name-umb = umbundu
language-name-und = nežinoma kalba
language-name-ur = urdų
language-name-uz = uzbekų
language-name-vai = vai
language-name-ve = vendų
language-name-vec = venetų
language-name-vep = vepsų
language-name-vi = vietnamiečių
language-name-vls = vakarų flamandų
language-name-vmf = pagrindinė frankonų
language-name-vo = volapiuko
language-name-vot = Votik
language-name-vro = veru
language-name-vun = vunjo
language-name-wa = valonų
language-name-wae = valserų
language-name-wal = valamo
language-name-war = varai
language-name-was = Vašo
language-name-wbp = valrpiri
language-name-wo = volofų
language-name-wuu = kinų kalbos vu tarmė
language-name-xal = kalmukų
language-name-xh = kosų
language-name-xmf = megrelų
language-name-xog = sogų
language-name-yao = jao
language-name-yap = japezų
language-name-yav = jangbenų
language-name-ybb = jembų
language-name-yi = jidiš
language-name-yo = jorubų
language-name-yrl = njengatu
language-name-yue = kinų kalbos Kantono tarmė
language-name-za = chuang
language-name-zap = zapotekų
language-name-zbl = BLISS simbolių
language-name-zea = zelandų
language-name-zen = zenaga
language-name-zgh = standartinė Maroko tamazigtų
language-name-zh = kinų
language-name-zh_Hans = supaprastintoji kinų
language-name-zh_Hant = tradicinė kinų
language-name-zu = zulų
language-name-zun = Zuni
language-name-zxx = nėra kalbinio turinio
language-name-zza = zaza
