language-name-aa = الأفارية
language-name-ab = الأبخازية
language-name-ace = الأتشينيزية
language-name-ach = الأكولية
language-name-ada = الأدانجمية
language-name-ady = الأديغة
language-name-ae = الأفستية
language-name-af = الأفريقانية
language-name-afh = الأفريهيلية
language-name-agq = الأغم
language-name-ain = الآينوية
language-name-ak = الأكانية
language-name-akk = الأكادية
language-name-ale = الأليوتية
language-name-alt = الألطائية الجنوبية
language-name-am = الأمهرية
language-name-an = الأراغونية
language-name-ang = الإنجليزية القديمة
language-name-anp = الأنجيكا
language-name-ar = العربية
language-name-ar_001 = العربية الرسمية الحديثة
language-name-arc = الآرامية
language-name-arn = المابودونغونية
language-name-arp = الأراباهو
language-name-ars = اللهجة النجدية
language-name-arw = الأراواكية
language-name-as = الأسامية
language-name-asa = الآسو
language-name-ast = الأسترية
language-name-av = الأوارية
language-name-awa = الأوادية
language-name-ay = الأيمارا
language-name-az = الأذربيجانية
language-name-ba = الباشكيرية
language-name-bal = البلوشية
language-name-ban = البالينية
language-name-bas = الباسا
language-name-bax = بامن
language-name-bbj = لغة الغومالا
language-name-be = البيلاروسية
language-name-bej = البيجا
language-name-bem = البيمبا
language-name-bez = بينا
language-name-bfd = لغة البافوت
language-name-bg = البلغارية
language-name-bgn = البلوشية الغربية
language-name-bho = البهوجبورية
language-name-bi = البيسلامية
language-name-bik = البيكولية
language-name-bin = البينية
language-name-bkm = لغة الكوم
language-name-bla = السيكسيكية
language-name-bm = البامبارا
language-name-bn = البنغالية
language-name-bo = التبتية
language-name-br = البريتونية
language-name-bra = البراجية
language-name-brx = البودو
language-name-bs = البوسنية
language-name-bss = أكوس
language-name-bua = البرياتية
language-name-bug = البجينيزية
language-name-bum = لغة البولو
language-name-byn = البلينية
language-name-byv = لغة الميدومبا
language-name-ca = الكتالانية
language-name-cad = الكادو
language-name-car = الكاريبية
language-name-cay = الكايوجية
language-name-cch = الأتسام
language-name-ce = الشيشانية
language-name-ceb = السيبونية
language-name-cgg = تشيغا
language-name-ch = التشامورو
language-name-chb = التشيبشا
language-name-chg = التشاجاتاي
language-name-chk = التشكيزية
language-name-chm = الماري
language-name-chn = الشينوك جارجون
language-name-cho = الشوكتو
language-name-chp = الشيباوايان
language-name-chr = الشيروكي
language-name-chy = الشايان
language-name-ckb = السورانية الكردية
language-name-co = الكورسيكية
language-name-cop = القبطية
language-name-cr = الكرى
language-name-crh = لغة تتار القرم
language-name-crs = الفرنسية الكريولية السيشيلية
language-name-cs = التشيكية
language-name-csb = الكاشبايان
language-name-cu = سلافية كنسية
language-name-cv = التشوفاشي
language-name-cy = الويلزية
language-name-da = الدانمركية
language-name-dak = الداكوتا
language-name-dar = الدارجوا
language-name-dav = تيتا
language-name-de = الألمانية
language-name-de_AT = الألمانية النمساوية
language-name-de_CH = الألمانية العليا السويسرية
language-name-del = الديلوير
language-name-den = السلافية
language-name-dgr = الدوجريب
language-name-din = الدنكا
language-name-dje = الزارمية
language-name-doi = الدوجرية
language-name-dsb = صوربيا السفلى
language-name-dua = الديولا
language-name-dum = الهولندية الوسطى
language-name-dv = المالديفية
language-name-dyo = جولا فونيا
language-name-dyu = الدايلا
language-name-dz = الزونخاية
language-name-dzg = القرعانية
language-name-ebu = إمبو
language-name-ee = الإيوي
language-name-efi = الإفيك
language-name-egy = المصرية القديمة
language-name-eka = الإكاجك
language-name-el = اليونانية
language-name-elx = الإمايت
language-name-en = الإنجليزية
language-name-en_AU = الإنجليزية الأسترالية
language-name-en_CA = الإنجليزية الكندية
language-name-en_GB = الإنجليزية البريطانية
language-name-en_US = الإنجليزية الأمريكية
language-name-enm = الإنجليزية الوسطى
language-name-eo = الإسبرانتو
language-name-es = الإسبانية
language-name-es_419 = الإسبانية أمريكا اللاتينية
language-name-es_ES = الإسبانية الأوروبية
language-name-es_MX = الإسبانية المكسيكية
language-name-et = الإستونية
language-name-eu = الباسكية
language-name-ewo = الإيوندو
language-name-fa = الفارسية
language-name-fan = الفانج
language-name-fat = الفانتي
language-name-ff = الفولانية
language-name-fi = الفنلندية
language-name-fil = الفلبينية
language-name-fj = الفيجية
language-name-fo = الفاروية
language-name-fon = الفون
language-name-fr = الفرنسية
language-name-fr_CA = الفرنسية الكندية
language-name-fr_CH = الفرنسية السويسرية
language-name-frc = الفرنسية الكاجونية
language-name-frm = الفرنسية الوسطى
language-name-fro = الفرنسية القديمة
language-name-frr = الفريزينية الشمالية
language-name-frs = الفريزينية الشرقية
language-name-fur = الفريلايان
language-name-fy = الفريزيان
language-name-ga = الأيرلندية
language-name-gaa = الجا
language-name-gag = الغاغوز
language-name-gan = الغان الصينية
language-name-gay = الجايو
language-name-gba = الجبيا
language-name-gd = الغيلية الأسكتلندية
language-name-gez = الجعزية
language-name-gil = لغة أهل جبل طارق
language-name-gl = الجاليكية
language-name-gmh = الألمانية العليا الوسطى
language-name-gn = الغوارانية
language-name-goh = الألمانية العليا القديمة
language-name-gon = الجندي
language-name-gor = الجورونتالو
language-name-got = القوطية
language-name-grb = الجريبو
language-name-grc = اليونانية القديمة
language-name-gsw = الألمانية السويسرية
language-name-gu = الغوجاراتية
language-name-guz = الغيزية
language-name-gv = المنكية
language-name-gwi = غوتشن
language-name-ha = الهوسا
language-name-hai = الهيدا
language-name-hak = الهاكا الصينية
language-name-haw = لغة أهل الهاواي
language-name-he = العبرية
language-name-hi = الهندية
language-name-hil = الهيليجينون
language-name-hit = الحثية
language-name-hmn = الهمونجية
language-name-ho = الهيري موتو
language-name-hr = الكرواتية
language-name-hsb = الصوربية العليا
language-name-hsn = شيانغ الصينية
language-name-ht = الكريولية الهايتية
language-name-hu = الهنغارية
language-name-hup = الهبا
language-name-hy = الأرمنية
language-name-hz = الهيريرو
language-name-ia = اللّغة الوسيطة
language-name-iba = الإيبان
language-name-ibb = الإيبيبيو
language-name-id = الإندونيسية
language-name-ie = الإنترلينج
language-name-ig = الإيجبو
language-name-ii = السيتشيون يي
language-name-ik = الإينبياك
language-name-ilo = الإيلوكو
language-name-inh = الإنجوشية
language-name-io = الإيدو
language-name-is = الأيسلندية
language-name-it = الإيطالية
language-name-iu = الإينكتيتت
language-name-ja = اليابانية
language-name-jbo = اللوجبان
language-name-jgo = نغومبا
language-name-jmc = الماتشامية
language-name-jpr = الفارسية اليهودية
language-name-jrb = العربية اليهودية
language-name-jv = الجاوية
language-name-ka = الجورجية
language-name-kaa = الكارا-كالباك
language-name-kab = القبيلية
language-name-kac = الكاتشين
language-name-kaj = الجو
language-name-kam = الكامبا
language-name-kaw = الكوي
language-name-kbd = الكاباردايان
language-name-kbl = كانمبو
language-name-kcg = التايابية
language-name-kde = ماكونده
language-name-kea = كابوفيرديانو
language-name-kfo = الكورو
language-name-kg = الكونغو
language-name-kha = الكازية
language-name-kho = الخوتانيز
language-name-khq = كويرا تشيني
language-name-ki = الكيكيو
language-name-kj = الكيونياما
language-name-kk = الكازاخستانية
language-name-kkj = لغة الكاكو
language-name-kl = الكالاليست
language-name-kln = كالينجين
language-name-km = الخميرية
language-name-kmb = الكيمبندو
language-name-kn = الكانادا
language-name-ko = الكورية
language-name-koi = كومي-بيرماياك
language-name-kok = الكونكانية
language-name-kos = الكوسراين
language-name-kpe = الكبيل
language-name-kr = الكانوري
language-name-krc = الكاراتشاي-بالكار
language-name-krl = الكاريلية
language-name-kru = الكوروخ
language-name-ks = الكشميرية
language-name-ksb = شامبالا
language-name-ksf = لغة البافيا
language-name-ksh = لغة الكولونيان
language-name-ku = الكردية
language-name-kum = القموقية
language-name-kut = الكتيناي
language-name-kv = الكومي
language-name-kw = الكورنية
language-name-ky = القيرغيزية
language-name-la = اللاتينية
language-name-lad = اللادينو
language-name-lag = لانجي
language-name-lah = اللاهندا
language-name-lam = اللامبا
language-name-lb = اللكسمبورغية
language-name-lez = الليزجية
language-name-lg = الغاندا
language-name-li = الليمبورغية
language-name-lkt = لاكوتا
language-name-ln = اللينجالا
language-name-lo = اللاوية
language-name-lol = منغولى
language-name-lou = الكريولية اللويزيانية
language-name-loz = اللوزي
language-name-lrc = اللرية الشمالية
language-name-lt = الليتوانية
language-name-lu = اللوبا كاتانغا
language-name-lua = اللبا-لؤلؤ
language-name-lui = اللوسينو
language-name-lun = اللوندا
language-name-luo = اللو
language-name-lus = الميزو
language-name-luy = لغة اللويا
language-name-lv = اللاتفية
language-name-mad = المادريز
language-name-mag = الماجا
language-name-mai = المايثيلي
language-name-mak = الماكاسار
language-name-man = الماندينغ
language-name-mas = الماساي
language-name-mde = مابا
language-name-mdf = الموكشا
language-name-mdr = الماندار
language-name-men = الميند
language-name-mer = الميرو
language-name-mfe = المورسيانية
language-name-mg = المالاغاشية
language-name-mga = الأيرلندية الوسطى
language-name-mgh = ماخاوا-ميتو
language-name-mgo = ميتا
language-name-mh = المارشالية
language-name-mi = الماورية
language-name-mic = الميكماكيونية
language-name-min = المينانجكاباو
language-name-mk = المقدونية
language-name-ml = المالايالامية
language-name-mn = المنغولية
language-name-mnc = المانشو
language-name-mni = المانيبورية
language-name-moh = الموهوك
language-name-mos = الموسي
language-name-mr = الماراثية
language-name-ms = الماليزية
language-name-mt = المالطية
language-name-mua = مندنج
language-name-mul = لغات متعددة
language-name-mus = الكريك
language-name-mwl = الميرانديز
language-name-mwr = الماروارية
language-name-my = البورمية
language-name-myv = الأرزية
language-name-mzn = المازندرانية
language-name-na = النورو
language-name-nan = مين-نان الصينية
language-name-nap = النابولية
language-name-naq = لغة الناما
language-name-nb = بوكمول النرويجية
language-name-nd = النديبيل الشمالية
language-name-nds = الألمانية السفلى
language-name-nds_NL = السكسونية السفلى
language-name-ne = النيبالية
language-name-new = النوارية
language-name-ng = الندونجا
language-name-nia = النياس
language-name-niu = النيوي
language-name-nl = الهولندية
language-name-nl_BE = الفلمنكية
language-name-nmg = كواسيو
language-name-nn = النرويجية نينورسك
language-name-nnh = لغة النجيمبون
language-name-no = النرويجية
language-name-nog = النوجاي
language-name-non = النورس القديم
language-name-nqo = أنكو
language-name-nr = النديبيل الجنوبي
language-name-nso = السوتو الشمالية
language-name-nus = النوير
language-name-nv = النافاجو
language-name-nwc = النوارية التقليدية
language-name-ny = النيانجا
language-name-nym = النيامويزي
language-name-nyn = النيانكول
language-name-nyo = النيورو
language-name-nzi = النزيما
language-name-oc = الأوكيتانية
language-name-oj = الأوجيبوا
language-name-om = الأورومية
language-name-or = الأورية
language-name-os = الأوسيتيك
language-name-osa = الأوساج
language-name-ota = التركية العثمانية
language-name-pa = البنجابية
language-name-pag = البانجاسينان
language-name-pal = البهلوية
language-name-pam = البامبانجا
language-name-pap = البابيامينتو
language-name-pau = البالوان
language-name-pcm = البدجنية النيجيرية
language-name-peo = الفارسية القديمة
language-name-phn = الفينيقية
language-name-pi = البالية
language-name-pl = البولندية
language-name-pon = البوهنبيايان
language-name-prg = البروسياوية
language-name-pro = البروفانسية القديمة
language-name-ps = البشتو
language-name-pt = البرتغالية
language-name-pt_BR = البرتغالية البرازيلية
language-name-pt_PT = البرتغالية الأوروبية
language-name-qu = الكويتشوا
language-name-quc = كيشي
language-name-raj = الراجاسثانية
language-name-rap = الراباني
language-name-rar = الراروتونجاني
language-name-rm = الرومانشية
language-name-rn = الرندي
language-name-ro = الرومانية
language-name-ro_MD = المولدوفية
language-name-rof = الرومبو
language-name-rom = الغجرية
language-name-root = الجذر
language-name-ru = الروسية
language-name-rup = الأرومانيان
language-name-rw = الكينيارواندا
language-name-rwk = الروا
language-name-sa = السنسكريتية
language-name-sad = السانداوي
language-name-sah = الساخية
language-name-sam = الآرامية السامرية
language-name-saq = سامبورو
language-name-sas = الساساك
language-name-sat = السانتالي
language-name-sba = نامبي
language-name-sbp = سانغو
language-name-sc = السردينية
language-name-scn = الصقلية
language-name-sco = الأسكتلندية
language-name-sd = السندية
language-name-sdh = الكردية الجنوبية
language-name-se = سامي الشمالية
language-name-see = السنيكا
language-name-seh = سينا
language-name-sel = السيلكب
language-name-ses = كويرابورو سيني
language-name-sg = السانجو
language-name-sga = الأيرلندية القديمة
language-name-sh = صربية-كرواتية
language-name-shi = تشلحيت
language-name-shn = الشان
language-name-shu = العربية التشادية
language-name-si = السنهالية
language-name-sid = السيدامو
language-name-sk = السلوفاكية
language-name-sl = السلوفانية
language-name-sm = الساموائية
language-name-sma = السامي الجنوبي
language-name-smj = اللول سامي
language-name-smn = الإيناري سامي
language-name-sms = السكولت سامي
language-name-sn = الشونا
language-name-snk = السونينك
language-name-so = الصومالية
language-name-sog = السوجدين
language-name-sq = الألبانية
language-name-sr = الصربية
language-name-srn = السرانان تونجو
language-name-srr = السرر
language-name-ss = السواتي
language-name-ssy = لغة الساهو
language-name-st = السوتو الجنوبية
language-name-su = السوندانية
language-name-suk = السوكوما
language-name-sus = السوسو
language-name-sux = السومارية
language-name-sv = السويدية
language-name-sw = السواحلية
language-name-sw_CD = الكونغو السواحلية
language-name-swb = القمرية
language-name-syc = سريانية تقليدية
language-name-syr = السريانية
language-name-ta = التاميلية
language-name-te = التيلوغوية
language-name-tem = التيمن
language-name-teo = تيسو
language-name-ter = التيرينو
language-name-tet = التيتم
language-name-tg = الطاجيكية
language-name-th = التايلاندية
language-name-ti = التغرينية
language-name-tig = التيغرية
language-name-tiv = التيف
language-name-tk = التركمانية
language-name-tkl = التوكيلاو
language-name-tl = التاغالوغية
language-name-tlh = الكلينجون
language-name-tli = التلينغيتية
language-name-tmh = التاماشيك
language-name-tn = التسوانية
language-name-to = التونغية
language-name-tog = تونجا - نياسا
language-name-tpi = التوك بيسين
language-name-tr = التركية
language-name-trv = لغة التاروكو
language-name-ts = السونجا
language-name-tsi = التسيمشيان
language-name-tt = التترية
language-name-tum = التامبوكا
language-name-tvl = التوفالو
language-name-tw = التوي
language-name-twq = تاساواق
language-name-ty = التاهيتية
language-name-tyv = التوفية
language-name-tzm = الأمازيغية وسط الأطلس
language-name-udm = الأدمرت
language-name-ug = الأويغورية
language-name-uga = اليجاريتيك
language-name-uk = الأوكرانية
language-name-umb = الأمبندو
language-name-und = لغة غير معروفة
language-name-ur = الأوردية
language-name-uz = الأوزبكية
language-name-vai = الفاي
language-name-ve = الفيندا
language-name-vi = الفيتنامية
language-name-vo = لغة الفولابوك
language-name-vot = الفوتيك
language-name-vun = الفونجو
language-name-wa = الولونية
language-name-wae = الوالسر
language-name-wal = الولاياتا
language-name-war = الواراي
language-name-was = الواشو
language-name-wbp = وارلبيري
language-name-wo = الولوفية
language-name-wuu = الوو الصينية
language-name-xal = الكالميك
language-name-xh = الخوسا
language-name-xog = السوغا
language-name-yao = الياو
language-name-yap = اليابيز
language-name-yav = يانجبن
language-name-ybb = يمبا
language-name-yi = اليديشية
language-name-yo = اليوروبا
language-name-yue = الكَنْتُونية
language-name-za = الزهيونج
language-name-zap = الزابوتيك
language-name-zbl = رموز المعايير الأساسية
language-name-zen = الزيناجا
language-name-zgh = التمازيغية المغربية القياسية
language-name-zh = الصينية
language-name-zh_Hans = الصينية المبسطة
language-name-zh_Hant = الصينية التقليدية
language-name-zu = الزولو
language-name-zun = الزونية
language-name-zxx = بدون محتوى لغوي
language-name-zza = زازا
