language-name-aa = अफार
language-name-ab = अबखेजियन
language-name-ace = अचीनी
language-name-ach = अकोली
language-name-ada = अडांग्मे
language-name-ady = अडिघे
language-name-ae = अवेस्तन
language-name-af = अफ्रिकान्स
language-name-afh = अफ्रिहिली
language-name-agq = अघेम
language-name-ain = ऐनू
language-name-ak = अकान
language-name-akk = अक्केडियन
language-name-ale = अलेउत
language-name-alt = दक्षिणात्य अल्ताई
language-name-am = अम्हारिक
language-name-an = अर्गोनीज
language-name-ang = पुरातन इंग्रजी
language-name-anp = अंगिका
language-name-ar = अरबी
language-name-ar_001 = आधुनिक प्रमाणित अरबी
language-name-arc = अ‍ॅरेमाइक
language-name-arn = मापुची
language-name-arp = आरापाहो
language-name-arw = आरावाक
language-name-as = आसामी
language-name-asa = असु
language-name-ast = अस्तुरियन
language-name-av = अ‍ॅव्हेरिक
language-name-awa = अवधी
language-name-ay = ऐमरा
language-name-az = अझरबैजानी
language-name-ba = बष्किर
language-name-bal = बलुची
language-name-ban = बालिनीज
language-name-bas = बसा
language-name-be = बेलारुशियन
language-name-bej = बेजा
language-name-bem = बेम्बा
language-name-bez = बेना
language-name-bg = बल्गेरियन
language-name-bgn = पश्चिमी बालोची
language-name-bho = भोजपुरी
language-name-bi = बिस्लामा
language-name-bik = बिकोल
language-name-bin = बिनी
language-name-bla = सिक्सिका
language-name-bm = बाम्बारा
language-name-bn = बंगाली
language-name-bo = तिबेटी
language-name-br = ब्रेतॉन
language-name-bra = ब्रज
language-name-brx = बोडो
language-name-bs = बोस्नियन
language-name-bua = बुरियात
language-name-bug = बगिनीस
language-name-byn = ब्लिन
language-name-ca = कातालान
language-name-cad = कॅड्डो
language-name-car = कॅरिब
language-name-cch = अत्सम
language-name-ce = चेचेन
language-name-ceb = सिबुआनो
language-name-cgg = किगा
language-name-ch = कॅमोरो
language-name-chb = चिब्चा
language-name-chg = छागाताइ
language-name-chk = चूकीसे
language-name-chm = मारी
language-name-chn = चिनूक जारगॉन
language-name-cho = चोक्तौ
language-name-chp = शिपेव्यान
language-name-chr = चेरोकी
language-name-chy = शेयेन्न
language-name-ckb = मध्य कुर्दिश
language-name-co = कॉर्सिकन
language-name-cop = कॉप्टिक
language-name-cr = क्री
language-name-crh = क्राइमीन तुर्की
language-name-crs = सेसेल्वा क्रिओल फ्रेंच
language-name-cs = झेक
language-name-csb = काशुबियन
language-name-cu = चर्च स्लाव्हिक
language-name-cv = चूवाश
language-name-cy = वेल्श
language-name-da = डॅनिश
language-name-dak = डाकोटा
language-name-dar = दार्गवा
language-name-dav = तायता
language-name-de = जर्मन
language-name-de_AT = ऑस्ट्रियन जर्मन
language-name-de_CH = स्विस हाय जर्मन
language-name-del = डेलावेयर
language-name-den = स्लाव्ह
language-name-dgr = डोग्रिब
language-name-din = डिन्का
language-name-dje = झार्मा
language-name-doi = डोगरी
language-name-dsb = लोअर सोर्बियन
language-name-dua = दुआला
language-name-dum = मिडल डच
language-name-dv = दिवेही
language-name-dyo = जोला-फोंयी
language-name-dyu = ड्युला
language-name-dz = झोंगखा
language-name-dzg = दाझागा
language-name-ebu = एम्बू
language-name-ee = एवे
language-name-efi = एफिक
language-name-egy = प्राचीन इजिप्शियन
language-name-eka = एकाजुक
language-name-el = ग्रीक
language-name-elx = एलामाइट
language-name-en = इंग्रजी
language-name-en_AU = ऑस्ट्रेलियन इंग्रजी
language-name-en_CA = कॅनडियन इंग्रजी
language-name-en_GB = ब्रिटिश इंग्रजी
language-name-en_US = अमेरिकन इंग्रजी
language-name-enm = मिडल इंग्रजी
language-name-eo = एस्परान्टो
language-name-es = स्पॅनिश
language-name-es_419 = लॅटिन अमेरिकन स्पॅनिश
language-name-es_ES = युरोपियन स्पॅनिश
language-name-es_MX = मेक्सिकन स्पॅनिश
language-name-et = इस्टोनियन
language-name-eu = बास्क
language-name-ewo = इवोन्डो
language-name-fa = फारसी
language-name-fan = फँग
language-name-fat = फन्टी
language-name-ff = फुलाह
language-name-fi = फिन्निश
language-name-fil = फिलिपिनो
language-name-fj = फिजियन
language-name-fo = फरोइज
language-name-fon = फॉन
language-name-fr = फ्रेंच
language-name-fr_CA = कॅनडियन फ्रेंच
language-name-fr_CH = स्विस फ्रेंच
language-name-frc = केजॉन फ्रेंच
language-name-frm = मिडल फ्रेंच
language-name-fro = पुरातन फ्रेंच
language-name-frr = उत्तरी फ्रिशियन
language-name-frs = पौर्वात्य फ्रिशियन
language-name-fur = फ्रियुलियान
language-name-fy = पश्चिमी फ्रिशियन
language-name-ga = आयरिश
language-name-gaa = गा
language-name-gag = गागाउझ
language-name-gan = गॅन चिनी
language-name-gay = गायो
language-name-gba = बाया
language-name-gd = स्कॉट्स गेलिक
language-name-gez = गीझ
language-name-gil = जिल्बरटीज
language-name-gl = गॅलिशियन
language-name-gmh = मिडल हाय जर्मन
language-name-gn = गुआरनी
language-name-goh = पुरातन हाइ जर्मन
language-name-gon = गाँडी
language-name-gor = गोरोन्तालो
language-name-got = गॉथिक
language-name-grb = ग्रेबो
language-name-grc = प्राचीन ग्रीक
language-name-gsw = स्विस जर्मन
language-name-gu = गुजराती
language-name-guz = गसी
language-name-gv = मांक्स
language-name-gwi = ग्विच’इन
language-name-ha = हौसा
language-name-hai = हैडा
language-name-hak = हाक्का चिनी
language-name-haw = हवाईयन
language-name-he = हिब्रू
language-name-hi = हिंदी
language-name-hil = हिलीगेनॉन
language-name-hit = हिट्टिते
language-name-hmn = माँग
language-name-ho = हिरी मॉटू
language-name-hr = क्रोएशियन
language-name-hsb = अप्पर सॉर्बियन
language-name-hsn = शियांग चिनी
language-name-ht = हैतीयन
language-name-hu = हंगेरियन
language-name-hup = हूपा
language-name-hy = आर्मेनियन
language-name-hz = हरेरो
language-name-ia = इंटरलिंग्वा
language-name-iba = इबान
language-name-ibb = इबिबिओ
language-name-id = इंडोनेशियन
language-name-ie = इन्टरलिंग
language-name-ig = ईग्बो
language-name-ii = सिचुआन यी
language-name-ik = इनूपियाक
language-name-ilo = इलोको
language-name-inh = इंगुश
language-name-io = इडौ
language-name-is = आईसलँडिक
language-name-it = इटालियन
language-name-iu = इनुक्तीटुट
language-name-ja = जपानी
language-name-jbo = लोज्बान
language-name-jgo = गोम्बा
language-name-jmc = मशामे
language-name-jpr = जुदेओ-फारसी
language-name-jrb = जुदेओ-अरबी
language-name-jv = जावानीज
language-name-ka = जॉर्जियन
language-name-kaa = कारा-कल्पक
language-name-kab = कबाइल
language-name-kac = काचिन
language-name-kaj = ज्जु
language-name-kam = काम्बा
language-name-kaw = कावी
language-name-kbd = कबार्डियन
language-name-kcg = त्याप
language-name-kde = माकोन्दे
language-name-kea = काबवर्दियानु
language-name-kfo = कोरो
language-name-kg = काँगो
language-name-kha = खासी
language-name-kho = खोतानीस
language-name-khq = कोयरा चीनी
language-name-ki = किकुयू
language-name-kj = क्वान्यामा
language-name-kk = कझाक
language-name-kkj = काको
language-name-kl = कलाल्लिसत
language-name-kln = कालेंजीन
language-name-km = ख्मेर
language-name-kmb = किम्बन्दु
language-name-kn = कन्नड
language-name-ko = कोरियन
language-name-koi = कोमी-परम्याक
language-name-kok = कोंकणी
language-name-kos = कोसरियन
language-name-kpe = क्पेल्ले
language-name-kr = कनुरी
language-name-krc = कराचय-बाल्कर
language-name-krl = करेलियन
language-name-kru = कुरूख
language-name-ks = काश्मीरी
language-name-ksb = शांबाला
language-name-ksf = बाफिया
language-name-ksh = कोलोग्नियन
language-name-ku = कुर्दिश
language-name-kum = कुमीक
language-name-kut = कुतेनाई
language-name-kv = कोमी
language-name-kw = कोर्निश
language-name-ky = किरगीझ
language-name-la = लॅटिन
language-name-lad = लादीनो
language-name-lag = लांगी
language-name-lah = लाह्न्डा
language-name-lam = लाम्बा
language-name-lb = लक्झेंबर्गिश
language-name-lez = लेझ्घीयन
language-name-lg = गांडा
language-name-li = लिंबूर्गिश
language-name-lkt = लाकोटा
language-name-ln = लिंगाला
language-name-lo = लाओ
language-name-lol = मोंगो
language-name-lou = ल्युसियाना क्रिओल
language-name-loz = लोझि
language-name-lrc = उत्तरी ल्युरी
language-name-lt = लिथुआनियन
language-name-lu = ल्यूबा-कटांगा
language-name-lua = लुबा-लुलुआ
language-name-lui = लुइसेनो
language-name-lun = लुन्डा
language-name-luo = ल्युओ
language-name-lus = मिझो
language-name-luy = ल्युइया
language-name-lv = लात्व्हियन
language-name-mad = मादुरीस
language-name-mag = मगही
language-name-mai = मैथिली
language-name-mak = मकस्सर
language-name-man = मन्डिन्गो
language-name-mas = मसाई
language-name-mdf = मोक्ष
language-name-mdr = मंडार
language-name-men = मेन्डे
language-name-mer = मेरू
language-name-mfe = मोरिस्येन
language-name-mg = मलागसी
language-name-mga = मिडल आयरिश
language-name-mgh = माखुव्हा-मीट्टो
language-name-mgo = मीटा
language-name-mh = मार्शलीज
language-name-mi = माओरी
language-name-mic = मिकमॅक
language-name-min = मिनांग्काबाउ
language-name-mk = मॅसेडोनियन
language-name-ml = मल्याळम
language-name-mn = मंगोलियन
language-name-mnc = मान्चु
language-name-mni = मणिपुरी
language-name-moh = मोहॉक
language-name-mos = मोस्सी
language-name-mr = मराठी
language-name-ms = मलय
language-name-mt = माल्टिज्
language-name-mua = मुंडांग
language-name-mul = एकाधिक भाषा
language-name-mus = क्रीक
language-name-mwl = मिरांडिज्
language-name-mwr = मारवाडी
language-name-my = बर्मी
language-name-myv = एर्झ्या
language-name-mzn = माझानदेरानी
language-name-na = नउरू
language-name-nan = मिन नान चिनी
language-name-nap = नेपोलिटान
language-name-naq = नामा
language-name-nb = नॉर्वेजियन बोकमाल
language-name-nd = उत्तर देबेली
language-name-nds = लो जर्मन
language-name-nds_NL = लो सॅक्सन
language-name-ne = नेपाळी
language-name-new = नेवारी
language-name-ng = डोंगा
language-name-nia = नियास
language-name-niu = नियुआन
language-name-nl = डच
language-name-nl_BE = फ्लेमिश
language-name-nmg = क्वासिओ
language-name-nn = नॉर्वेजियन न्योर्स्क
language-name-nnh = जिएम्बून
language-name-no = नोर्वेजियन
language-name-nog = नोगाई
language-name-non = पुरातन नॉर्स
language-name-nqo = एन्को
language-name-nr = दक्षिणात्य देबेली
language-name-nso = उत्तरी सोथो
language-name-nus = नुएर
language-name-nv = नावाजो
language-name-nwc = अभिजात नेवारी
language-name-ny = न्यान्जा
language-name-nym = न्यामवेझी
language-name-nyn = न्यानकोल
language-name-nyo = न्योरो
language-name-nzi = न्झिमा
language-name-oc = ऑक्सितान
language-name-oj = ओजिब्वा
language-name-om = ओरोमो
language-name-or = उडिया
language-name-os = ओस्सेटिक
language-name-osa = ओसेज
language-name-ota = ओटोमान तुर्किश
language-name-pa = पंजाबी
language-name-pag = पंगासीनान
language-name-pal = पहलवी
language-name-pam = पाम्पान्गा
language-name-pap = पापियामेन्टो
language-name-pau = पालाउआन
language-name-pcm = नायजिरिअन पिजिन
language-name-peo = पुरातन फारसी
language-name-phn = फोनिशियन
language-name-pi = पाली
language-name-pl = पोलिश
language-name-pon = पोह्नपियन
language-name-prg = प्रुशियन
language-name-pro = पुरातन प्रोव्हेन्सल
language-name-ps = पश्तो
language-name-pt = पोर्तुगीज
language-name-pt_BR = ब्राझिलियन पोर्तुगीज
language-name-pt_PT = युरोपियन पोर्तुगीज
language-name-qu = क्वेचुआ
language-name-quc = कीशेइ
language-name-raj = राजस्थानी
language-name-rap = रापानुई
language-name-rar = रारोटोंगन
language-name-rm = रोमान्श
language-name-rn = रुन्दी
language-name-ro = रोमानियन
language-name-ro_MD = मोल्डाव्हियन
language-name-rof = रोम्बो
language-name-rom = रोमानी
language-name-root = रूट
language-name-ru = रशियन
language-name-rup = अरोमानियन
language-name-rw = किन्यार्वान्डा
language-name-rwk = रव्हा
language-name-sa = संस्कृत
language-name-sad = सँडवे
language-name-sah = साखा
language-name-sam = सामरिटान अरॅमिक
language-name-saq = सांबुरू
language-name-sas = सासाक
language-name-sat = संताली
language-name-sba = गाम्बे
language-name-sbp = सांगु
language-name-sc = सर्दिनियन
language-name-scn = सिसिलियन
language-name-sco = स्कॉट्स
language-name-sd = सिंधी
language-name-sdh = दक्षिणी कुर्दिश
language-name-se = उत्तरी सामी
language-name-seh = सेना
language-name-sel = सेल्कप
language-name-ses = कोयराबोरो सेन्नी
language-name-sg = सांगो
language-name-sga = पुरातन आयरिश
language-name-sh = सर्बो-क्रोएशियन
language-name-shi = ताशेल्हिट
language-name-shn = शॅन
language-name-si = सिंहला
language-name-sid = सिदामो
language-name-sk = स्लोव्हाक
language-name-sl = स्लोव्हेनियन
language-name-sm = सामोअन
language-name-sma = दक्षिणात्य सामी
language-name-smj = ल्युल सामी
language-name-smn = इनारी सामी
language-name-sms = स्कोल्ट सामी
language-name-sn = शोना
language-name-snk = सोनिन्के
language-name-so = सोमाली
language-name-sog = सोग्डिएन
language-name-sq = अल्बानियन
language-name-sr = सर्बियन
language-name-srn = स्रानान टॉन्गो
language-name-srr = सेरेर
language-name-ss = स्वाती
language-name-ssy = साहो
language-name-st = सेसोथो
language-name-su = सुंदानीज
language-name-suk = सुकुमा
language-name-sus = सुसु
language-name-sux = सुमेरियन
language-name-sv = स्वीडिश
language-name-sw = स्वाहिली
language-name-sw_CD = काँगो स्वाहिली
language-name-swb = कोमोरियन
language-name-syc = अभिजात सिरियाक
language-name-syr = सिरियाक
language-name-ta = तामिळ
language-name-te = तेलगू
language-name-tem = टिम्ने
language-name-teo = तेसो
language-name-ter = तेरेनो
language-name-tet = तेतुम
language-name-tg = ताजिक
language-name-th = थाई
language-name-ti = तिग्रिन्या
language-name-tig = टाइग्रे
language-name-tiv = तिव
language-name-tk = तुर्कमेन
language-name-tkl = टोकेलाऊ
language-name-tl = टागालोग
language-name-tlh = क्लिंगोन
language-name-tli = लिंगित
language-name-tmh = तामाशेक
language-name-tn = त्स्वाना
language-name-to = टोंगन
language-name-tog = न्यासा टोन्गा
language-name-tpi = टोक पिसिन
language-name-tr = तुर्की
language-name-trv = तारोको
language-name-ts = सोंगा
language-name-tsi = सिम्शियन
language-name-tt = तातर
language-name-tum = तुम्बुका
language-name-tvl = टुवालु
language-name-tw = ट्वी
language-name-twq = तासाव्हाक
language-name-ty = ताहितीयन
language-name-tyv = टुवीनियन
language-name-tzm = मध्य ऍटलास तॅमॅझायट
language-name-udm = उदमुर्त
language-name-ug = उइगुर
language-name-uga = युगॅरिटिक
language-name-uk = युक्रेनियन
language-name-umb = उम्बुन्डु
language-name-und = अज्ञात भाषा
language-name-ur = उर्दू
language-name-uz = उझ्बेक
language-name-vai = वाई
language-name-ve = व्हेंदा
language-name-vi = व्हिएतनामी
language-name-vo = ओलापुक
language-name-vot = वॉटिक
language-name-vun = वुंजो
language-name-wa = वालून
language-name-wae = वालसेर
language-name-wal = वोलायता
language-name-war = वारे
language-name-was = वाशो
language-name-wbp = वार्लपिरी
language-name-wo = वोलोफ
language-name-wuu = व्हू चिनी
language-name-xal = काल्मिक
language-name-xh = खोसा
language-name-xog = सोगा
language-name-yao = याओ
language-name-yap = यापीस
language-name-yav = यांगबेन
language-name-ybb = येमबा
language-name-yi = यिद्दिश
language-name-yo = योरुबा
language-name-yue = कँटोनीज
language-name-za = झुआंग
language-name-zap = झेपोटेक
language-name-zbl = ब्लिसिम्बॉल्स
language-name-zen = झेनान्गा
language-name-zgh = प्रमाण मोरोक्कन तॅमॅझायट
language-name-zh = चीनी
language-name-zh_Hans = सरलीकृत चीनी
language-name-zh_Hant = पारंपारिक चीनी
language-name-zu = झुलू
language-name-zun = झुनी
language-name-zxx = भाषावैज्ञानिक सामग्री नाही
language-name-zza = झाझा
