language-name-ace = ačehgiella
language-name-ar_001 = standárda arábagiella
language-name-be = vilgesruoššagiella
language-name-bn = bengalagiella
language-name-de_AT = nuortariikkalaš duiskkagiella
language-name-de_CH = šveicalaš duiskkagiella
language-name-en_AU = austrálialaš eaŋgalsgiella
language-name-en_CA = kanádalaš eaŋgalsgiella
language-name-en_GB = brihttalaš eaŋgalsgiella
language-name-en_US = amerihkálaš eaŋgalsgiella
language-name-es_419 = latiinna-amerihkalaš spánskkagiella
language-name-es_ES = espánjalaš spánskkagiella
language-name-es_MX = meksikolaš spánskkagiella
language-name-fj = fižigiella
language-name-fr_CA = kanádalaš fránskkagiella
language-name-fr_CH = šveicalaš fránskkagiella
language-name-hy = armenagiella
language-name-kk = kazakhgiella
language-name-km = kambožagiella
language-name-ne = nepalagiella
language-name-nl_BE = belgialaš hollánddagiella
language-name-pa = panjabagiella
language-name-pt_BR = brasilialaš portugálagiella
language-name-pt_PT = portugálalaš portugálagiella
language-name-ro_MD = moldávialaš romániagiella
language-name-swb = komoragiella
language-name-th = thaigiella
language-name-vi = vietnamagiella
language-name-zh_Hans = álkes kiinnágiella
