language-name-aa = afar
language-name-ab = abkhaze
language-name-ace = aceh
language-name-ach = acoli
language-name-ada = adangme
language-name-ady = adyghéen
language-name-ae = avestique
language-name-aeb = arabe tunisien
language-name-af = afrikaans
language-name-afh = afrihili
language-name-agq = aghem
language-name-ain = aïnou
language-name-ak = akan
language-name-akk = akkadien
language-name-akz = alabama
language-name-ale = aléoute
language-name-aln = guègue
language-name-alt = altaï du Sud
language-name-am = amharique
language-name-an = aragonais
language-name-ang = ancien anglais
language-name-anp = angika
language-name-ar = arabe
language-name-ar_001 = arabe standard moderne
language-name-arc = araméen
language-name-arn = mapuche
language-name-aro = araona
language-name-arp = arapaho
language-name-arq = arabe algérien
language-name-ars = arabe najdi
language-name-arw = arawak
language-name-ary = arabe marocain
language-name-arz = arabe égyptien
language-name-as = assamais
language-name-asa = assou
language-name-ase = langue des signes américaine
language-name-ast = asturien
language-name-av = avar
language-name-avk = kotava
language-name-awa = awadhi
language-name-ay = aymara
language-name-az = azéri
language-name-ba = bachkir
language-name-bal = baloutchi
language-name-ban = balinais
language-name-bar = bavarois
language-name-bas = bassa
language-name-bax = bamoun
language-name-bbc = batak toba
language-name-bbj = ghomala
language-name-be = biélorusse
language-name-bej = bedja
language-name-bem = bemba
language-name-bew = betawi
language-name-bez = béna
language-name-bfd = bafut
language-name-bfq = badaga
language-name-bg = bulgare
language-name-bgn = baloutchi occidental
language-name-bho = bhojpuri
language-name-bi = bichelamar
language-name-bik = bikol
language-name-bin = bini
language-name-bjn = banjar
language-name-bkm = kom
language-name-bla = siksika
language-name-bm = bambara
language-name-bn = bengali
language-name-bo = tibétain
language-name-bpy = bishnupriya
language-name-bqi = bakhtiari
language-name-br = breton
language-name-bra = braj
language-name-brh = brahoui
language-name-brx = bodo
language-name-bs = bosniaque
language-name-bss = akoose
language-name-bua = bouriate
language-name-bug = bugi
language-name-bum = boulou
language-name-byn = blin
language-name-byv = médumba
language-name-ca = catalan
language-name-cad = caddo
language-name-car = caribe
language-name-cay = cayuga
language-name-cch = atsam
language-name-ce = tchétchène
language-name-ceb = cebuano
language-name-cgg = kiga
language-name-ch = chamorro
language-name-chb = chibcha
language-name-chg = tchaghataï
language-name-chk = chuuk
language-name-chm = mari
language-name-chn = jargon chinook
language-name-cho = choctaw
language-name-chp = chipewyan
language-name-chr = cherokee
language-name-chy = cheyenne
language-name-ckb = sorani
language-name-co = corse
language-name-cop = copte
language-name-cps = capiznon
language-name-cr = cree
language-name-crh = turc de Crimée
language-name-crs = créole seychellois
language-name-cs = tchèque
language-name-csb = kachoube
language-name-cu = slavon d’église
language-name-cv = tchouvache
language-name-cy = gallois
language-name-da = danois
language-name-dak = dakota
language-name-dar = dargwa
language-name-dav = taita
language-name-de = allemand
language-name-de_AT = allemand autrichien
language-name-de_CH = allemand suisse
language-name-del = delaware
language-name-den = esclave
language-name-dgr = dogrib
language-name-din = dinka
language-name-dje = zarma
language-name-doi = dogri
language-name-dsb = bas-sorabe
language-name-dtp = dusun central
language-name-dua = douala
language-name-dum = moyen néerlandais
language-name-dv = maldivien
language-name-dyo = diola-fogny
language-name-dyu = dioula
language-name-dz = dzongkha
language-name-dzg = dazaga
language-name-ebu = embou
language-name-ee = éwé
language-name-efi = éfik
language-name-egl = émilien
language-name-egy = égyptien ancien
language-name-eka = ékadjouk
language-name-el = grec
language-name-elx = élamite
language-name-en = anglais
language-name-en_AU = anglais australien
language-name-en_CA = anglais canadien
language-name-en_GB = anglais britannique
language-name-en_US = anglais américain
language-name-enm = moyen anglais
language-name-eo = espéranto
language-name-es = espagnol
language-name-esu = youpik central
language-name-et = estonien
language-name-eu = basque
language-name-ewo = éwondo
language-name-ext = estrémègne
language-name-fa = persan
language-name-fan = fang
language-name-fat = fanti
language-name-ff = peul
language-name-fi = finnois
language-name-fil = filipino
language-name-fit = finnois tornédalien
language-name-fj = fidjien
language-name-fo = féroïen
language-name-fon = fon
language-name-fr = français
language-name-fr_CA = français canadien
language-name-fr_CH = français suisse
language-name-frc = français cadien
language-name-frm = moyen français
language-name-fro = ancien français
language-name-frp = francoprovençal
language-name-frr = frison du Nord
language-name-frs = frison oriental
language-name-fur = frioulan
language-name-fy = frison occidental
language-name-ga = irlandais
language-name-gaa = ga
language-name-gag = gagaouze
language-name-gan = gan
language-name-gay = gayo
language-name-gba = gbaya
language-name-gbz = dari zoroastrien
language-name-gd = gaélique écossais
language-name-gez = guèze
language-name-gil = gilbertin
language-name-gl = galicien
language-name-glk = gilaki
language-name-gmh = moyen haut-allemand
language-name-gn = guarani
language-name-goh = ancien haut allemand
language-name-gom = konkani de Goa
language-name-gon = gondi
language-name-gor = gorontalo
language-name-got = gothique
language-name-grb = grebo
language-name-grc = grec ancien
language-name-gsw = suisse allemand
language-name-gu = goudjerati
language-name-guc = wayuu
language-name-gur = gurenne
language-name-guz = gusii
language-name-gv = mannois
language-name-gwi = gwichʼin
language-name-ha = haoussa
language-name-hai = haida
language-name-hak = hakka
language-name-haw = hawaïen
language-name-he = hébreu
language-name-hi = hindi
language-name-hif = hindi fidjien
language-name-hil = hiligaynon
language-name-hit = hittite
language-name-hmn = hmong
language-name-ho = hiri motu
language-name-hr = croate
language-name-hsb = haut-sorabe
language-name-hsn = xiang
language-name-ht = créole haïtien
language-name-hu = hongrois
language-name-hup = hupa
language-name-hy = arménien
language-name-hz = héréro
language-name-ia = interlingua
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indonésien
language-name-ie = interlingue
language-name-ig = igbo
language-name-ii = yi du Sichuan
language-name-ik = inupiaq
language-name-ilo = ilokano
language-name-inh = ingouche
language-name-io = ido
language-name-is = islandais
language-name-it = italien
language-name-iu = inuktitut
language-name-izh = ingrien
language-name-ja = japonais
language-name-jam = créole jamaïcain
language-name-jbo = lojban
language-name-jgo = ngomba
language-name-jmc = matchamé
language-name-jpr = judéo-persan
language-name-jrb = judéo-arabe
language-name-jut = jute
language-name-jv = javanais
language-name-ka = géorgien
language-name-kaa = karakalpak
language-name-kab = kabyle
language-name-kac = kachin
language-name-kaj = jju
language-name-kam = kamba
language-name-kaw = kawi
language-name-kbd = kabardin
language-name-kbl = kanembou
language-name-kcg = tyap
language-name-kde = makondé
language-name-kea = capverdien
language-name-ken = kényang
language-name-kfo = koro
language-name-kg = kongo
language-name-kgp = caingangue
language-name-kha = khasi
language-name-kho = khotanais
language-name-khq = koyra chiini
language-name-khw = khowar
language-name-ki = kikuyu
language-name-kiu = kirmanjki
language-name-kj = kouanyama
language-name-kk = kazakh
language-name-kkj = kako
language-name-kl = groenlandais
language-name-kln = kalendjin
language-name-km = khmer
language-name-kmb = kimboundou
language-name-kn = kannada
language-name-ko = coréen
language-name-koi = komi-permiak
language-name-kok = konkani
language-name-kos = kosraéen
language-name-kpe = kpellé
language-name-kr = kanouri
language-name-krc = karatchaï balkar
language-name-kri = krio
language-name-krj = kinaray-a
language-name-krl = carélien
language-name-kru = kouroukh
language-name-ks = kashmiri
language-name-ksb = chambala
language-name-ksf = bafia
language-name-ksh = francique ripuaire
language-name-ku = kurde
language-name-kum = koumyk
language-name-kut = kutenai
language-name-kv = komi
language-name-kw = cornique
language-name-ky = kirghize
language-name-la = latin
language-name-lad = ladino
language-name-lag = langi
language-name-lah = lahnda
language-name-lam = lamba
language-name-lb = luxembourgeois
language-name-lez = lezghien
language-name-lfn = lingua franca nova
language-name-lg = ganda
language-name-li = limbourgeois
language-name-lij = ligure
language-name-liv = livonien
language-name-lkt = lakota
language-name-lmo = lombard
language-name-ln = lingala
language-name-lo = lao
language-name-lol = mongo
language-name-lou = créole louisianais
language-name-loz = lozi
language-name-lrc = lori du Nord
language-name-lt = lituanien
language-name-ltg = latgalien
language-name-lu = luba-katanga
language-name-lua = luba-lulua
language-name-lui = luiseño
language-name-lun = lunda
language-name-luo = luo
language-name-lus = lushaï
language-name-luy = luhya
language-name-lv = letton
language-name-lzh = chinois littéraire
language-name-lzz = laze
language-name-mad = madourais
language-name-maf = mafa
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = makassar
language-name-man = mandingue
language-name-mas = massaï
language-name-mde = maba
language-name-mdf = moksa
language-name-mdr = mandar
language-name-men = mendé
language-name-mer = mérou
language-name-mfe = créole mauricien
language-name-mg = malgache
language-name-mga = moyen irlandais
language-name-mgh = makhuwa-meetto
language-name-mgo = méta’
language-name-mh = marshallais
language-name-mi = maori
language-name-mic = micmac
language-name-min = minangkabau
language-name-mk = macédonien
language-name-ml = malayalam
language-name-mn = mongol
language-name-mnc = mandchou
language-name-mni = manipuri
language-name-moh = mohawk
language-name-mos = moré
language-name-mr = marathe
language-name-mrj = mari occidental
language-name-ms = malais
language-name-mt = maltais
language-name-mua = moundang
language-name-mul = multilingue
language-name-mus = creek
language-name-mwl = mirandais
language-name-mwr = marwarî
language-name-mwv = mentawaï
language-name-my = birman
language-name-mye = myènè
language-name-myv = erzya
language-name-mzn = mazandérani
language-name-na = nauruan
language-name-nan = minnan
language-name-nap = napolitain
language-name-naq = nama
language-name-nb = norvégien bokmål
language-name-nd = ndébélé du Nord
language-name-nds = bas-allemand
language-name-nds_NL = bas-saxon néerlandais
language-name-ne = népalais
language-name-new = newari
language-name-ng = ndonga
language-name-nia = nias
language-name-niu = niuéen
language-name-njo = Ao
language-name-nl = néerlandais
language-name-nl_BE = flamand
language-name-nmg = kwasio
language-name-nn = norvégien nynorsk
language-name-nnh = ngiemboon
language-name-no = norvégien
language-name-nog = nogaï
language-name-non = vieux norrois
language-name-nov = novial
language-name-nqo = n’ko
language-name-nr = ndébélé du Sud
language-name-nso = sotho du Nord
language-name-nus = nuer
language-name-nv = navaho
language-name-nwc = newarî classique
language-name-ny = nyanja
language-name-nym = nyamwezi
language-name-nyn = nyankolé
language-name-nyo = nyoro
language-name-nzi = nzema
language-name-oc = occitan
language-name-oj = ojibwa
language-name-om = oromo
language-name-or = oriya
language-name-os = ossète
language-name-osa = osage
language-name-ota = turc ottoman
language-name-pa = pendjabi
language-name-pag = pangasinan
language-name-pal = pahlavi
language-name-pam = pampangan
language-name-pap = papiamento
language-name-pau = palau
language-name-pcd = picard
language-name-pcm = pidgin nigérian
language-name-pdc = pennsilfaanisch
language-name-pdt = bas-prussien
language-name-peo = persan ancien
language-name-pfl = allemand palatin
language-name-phn = phénicien
language-name-pi = pali
language-name-pl = polonais
language-name-pms = piémontais
language-name-pnt = pontique
language-name-pon = pohnpei
language-name-prg = prussien
language-name-pro = provençal ancien
language-name-ps = pachto
language-name-pt = portugais
language-name-pt_BR = portugais brésilien
language-name-pt_PT = portugais européen
language-name-qu = quechua
language-name-quc = k’iche’
language-name-qug = quichua du Haut-Chimborazo
language-name-raj = rajasthani
language-name-rap = rapanui
language-name-rar = rarotongien
language-name-rgn = romagnol
language-name-rif = rifain
language-name-rm = romanche
language-name-rn = roundi
language-name-ro = roumain
language-name-ro_MD = moldave
language-name-rof = rombo
language-name-rom = romani
language-name-root = racine
language-name-rtm = rotuman
language-name-ru = russe
language-name-rue = ruthène
language-name-rug = roviana
language-name-rup = valaque
language-name-rw = rwanda
language-name-rwk = rwa
language-name-sa = sanskrit
language-name-sad = sandawe
language-name-sah = iakoute
language-name-sam = araméen samaritain
language-name-saq = sambourou
language-name-sas = sasak
language-name-sat = santal
language-name-saz = saurashtra
language-name-sba = ngambay
language-name-sbp = sangu
language-name-sc = sarde
language-name-scn = sicilien
language-name-sco = écossais
language-name-sd = sindhi
language-name-sdc = sarde sassarais
language-name-sdh = kurde du Sud
language-name-se = sami du Nord
language-name-see = seneca
language-name-seh = cisena
language-name-sei = séri
language-name-sel = selkoupe
language-name-ses = koyraboro senni
language-name-sg = sangho
language-name-sga = ancien irlandais
language-name-sgs = samogitien
language-name-sh = serbo-croate
language-name-shi = chleuh
language-name-shn = shan
language-name-shu = arabe tchadien
language-name-si = cinghalais
language-name-sid = sidamo
language-name-sk = slovaque
language-name-sl = slovène
language-name-sli = bas-silésien
language-name-sly = sélayar
language-name-sm = samoan
language-name-sma = sami du Sud
language-name-smj = sami de Lule
language-name-smn = sami d’Inari
language-name-sms = sami skolt
language-name-sn = shona
language-name-snk = soninké
language-name-so = somali
language-name-sog = sogdien
language-name-sq = albanais
language-name-sr = serbe
language-name-srn = sranan tongo
language-name-srr = sérère
language-name-ss = swati
language-name-ssy = saho
language-name-st = sotho du Sud
language-name-stq = saterlandais
language-name-su = soundanais
language-name-suk = soukouma
language-name-sus = soussou
language-name-sux = sumérien
language-name-sv = suédois
language-name-sw = swahili
language-name-sw_CD = swahili du Congo
language-name-swb = comorien
language-name-syc = syriaque classique
language-name-syr = syriaque
language-name-szl = silésien
language-name-ta = tamoul
language-name-tcy = toulou
language-name-te = télougou
language-name-tem = temne
language-name-teo = teso
language-name-ter = tereno
language-name-tet = tetum
language-name-tg = tadjik
language-name-th = thaï
language-name-ti = tigrigna
language-name-tig = tigré
language-name-tiv = tiv
language-name-tk = turkmène
language-name-tkl = tokelau
language-name-tkr = tsakhour
language-name-tl = tagalog
language-name-tlh = klingon
language-name-tli = tlingit
language-name-tly = talysh
language-name-tmh = tamacheq
language-name-tn = tswana
language-name-to = tonguien
language-name-tog = tonga nyasa
language-name-tpi = tok pisin
language-name-tr = turc
language-name-tru = touroyo
language-name-trv = taroko
language-name-ts = tsonga
language-name-tsd = tsakonien
language-name-tsi = tsimshian
language-name-tt = tatar
language-name-ttt = tati caucasien
language-name-tum = toumbouka
language-name-tvl = tuvalu
language-name-tw = twi
language-name-twq = tasawaq
language-name-ty = tahitien
language-name-tyv = touvain
language-name-tzm = amazighe de l’Atlas central
language-name-udm = oudmourte
language-name-ug = ouïghour
language-name-uga = ougaritique
language-name-uk = ukrainien
language-name-umb = oumboundou
language-name-und = langue indéterminée
language-name-ur = ourdou
language-name-uz = ouzbek
language-name-vai = vaï
language-name-ve = venda
language-name-vec = vénitien
language-name-vep = vepse
language-name-vi = vietnamien
language-name-vls = flamand occidental
language-name-vmf = franconien du Main
language-name-vo = volapuk
language-name-vot = vote
language-name-vro = võro
language-name-vun = vunjo
language-name-wa = wallon
language-name-wae = walser
language-name-wal = walamo
language-name-war = waray
language-name-was = washo
language-name-wbp = warlpiri
language-name-wo = wolof
language-name-wuu = wu
language-name-xal = kalmouk
language-name-xh = xhosa
language-name-xmf = mingrélien
language-name-xog = soga
language-name-yao = yao
language-name-yap = yapois
language-name-yav = yangben
language-name-ybb = yemba
language-name-yi = yiddish
language-name-yo = yoruba
language-name-yrl = nheengatou
language-name-yue = cantonais
language-name-za = zhuang
language-name-zap = zapotèque
language-name-zbl = symboles Bliss
language-name-zea = zélandais
language-name-zen = zenaga
language-name-zgh = amazighe standard marocain
language-name-zh = chinois
language-name-zh_Hans = chinois simplifié
language-name-zh_Hant = chinois traditionnel
language-name-zu = zoulou
language-name-zun = zuñi
language-name-zxx = sans contenu linguistique
language-name-zza = zazaki
