language-name-af = Afrikaans Simi
language-name-am = Amarico Simi
language-name-ar = Arabe Simi
language-name-arn = Mapuche Simi
language-name-as = Asames Simi
language-name-az = Azerbaiyano Simi
language-name-ba = Baskir Simi
language-name-be = Bielorruso Simi
language-name-bg = Bulgaro Simi
language-name-bn = Bangla Simi
language-name-bo = Tibetano Simi
language-name-br = Breton Simi
language-name-bs = Bosnio Simi
language-name-ca = Catalan Simi
language-name-chr = Cheroqui Simi
language-name-ckb = Chawpi Kurdo Simi
language-name-co = Corso Simi
language-name-cs = Checo Simi
language-name-cy = Gales Simi
language-name-da = Danes Simi
language-name-de = Aleman Simi
language-name-dsb = Bajo Sorbio Simi
language-name-dv = Divehi Simi
language-name-el = Griego Simi
language-name-en = Ingles Simi
language-name-es = Español Simi
language-name-et = Estonio Simi
language-name-eu = Euskera Simi
language-name-fa = Persa Simi
language-name-ff = Fulah Simi
language-name-fi = Fines Simi
language-name-fil = Filipino Simi
language-name-fo = Feroes Simi
language-name-fr = Frances Simi
language-name-fy = Frison Simi
language-name-ga = Irlandes Simi
language-name-gd = Gaelico Escoces Simi
language-name-gl = Gallego Simi
language-name-gsw = Alsaciano Simi
language-name-gu = Gujarati Simi
language-name-ha = Hausa Simi
language-name-he = Hebreo Simi
language-name-hi = Hindi Simi
language-name-hmn = Hmong Daw Simi
language-name-hr = Croata Simi
language-name-hsb = Alto Sorbio Simi
language-name-ht = Haitiano Criollo Simi
language-name-hu = Hungaro Simi
language-name-hy = Armenio Simi
language-name-id = Indonesio Simi
language-name-ig = Igbo Simi
language-name-ii = Yi Simi
language-name-is = Islandes Simi
language-name-it = Italiano Simi
language-name-iu = Inuktitut Simi
language-name-ja = Japones Simi
language-name-ka = Georgiano Simi
language-name-kk = Kazajo Simi
language-name-kl = Groenlandes Simi
language-name-km = Khmer Simi
language-name-kn = Kannada Simi
language-name-ko = Coreano Simi
language-name-kok = Konkani Simi
language-name-ky = Kirghiz Simi
language-name-lb = Luxemburgues Simi
language-name-lo = Lao Simi
language-name-lt = Lituano Simi
language-name-lv = Leton Simi
language-name-mi = Maori Simi
language-name-mk = Macedonio Simi
language-name-ml = Malayalam Simi
language-name-mn = Mongol Simi
language-name-moh = Mohawk Simi
language-name-mr = Marathi Simi
language-name-ms = Malayo Simi
language-name-mt = Maltes Simi
language-name-ne = Nepali Simi
language-name-nl = Neerlandes Simi
language-name-no = Noruego Simi
language-name-nso = Sesotho Sa Leboa Simi
language-name-oc = Occitano Simi
language-name-or = Odia Simi
language-name-pa = Punyabi Simi
language-name-pap = Papiamento Simi
language-name-pl = Polaco Simi
language-name-ps = Pashto Simi
language-name-pt = Portugues Simi
language-name-qu = Runasimi
language-name-quc = Kʼicheʼ Simi
language-name-rm = Romanche Simi
language-name-ro = Rumano Simi
language-name-ru = Ruso Simi
language-name-rw = Kinyarwanda Simi
language-name-sa = Sanscrito Simi
language-name-sah = Sakha Simi
language-name-sd = Sindhi Simi
language-name-se = Chincha Sami Simi
language-name-si = Cingales Simi
language-name-sk = Eslovaco Simi
language-name-sl = Esloveno Simi
language-name-sma = Qulla Sami Simi
language-name-smj = Sami Lule Simi
language-name-smn = Sami Inari Simi
language-name-sms = Sami Skolt Simi
language-name-sq = Albanes Simi
language-name-sr = Serbio Simi
language-name-sv = Sueco Simi
language-name-sw = Suajili Simi
language-name-syr = Siriaco Simi
language-name-ta = Tamil Simi
language-name-te = Telugu Simi
language-name-tg = Tayiko Simi
language-name-th = Tailandes Simi
language-name-ti = Tigriña Simi
language-name-tk = Turcomano Simi
language-name-tn = Setsuana Simi
language-name-tr = Turco Simi
language-name-tt = Tartaro Simi
language-name-ug = Uigur Simi
language-name-uk = Ucraniano Simi
language-name-ur = Urdu Simi
language-name-uz = Uzbeko Simi
language-name-vi = Vietnamita Simi
language-name-wo = Wolof Simi
language-name-xh = Isixhosa Simi
language-name-yo = Yoruba Simi
language-name-zh = Chino Simi
language-name-zu = Isizulu Simi
