language-name-aa = Afar
language-name-ab = Abkhazia
language-name-ace = Aceh
language-name-ach = Akoli
language-name-ada = Adangme
language-name-ady = Adyghe
language-name-ae = Avestan
language-name-aeb = Arab Tunisia
language-name-af = Afrikaans
language-name-agq = Aghem
language-name-ain = Ainu
language-name-ak = Akan
language-name-ale = Aleut
language-name-alt = Altai Selatan
language-name-am = Amharic
language-name-an = Aragon
language-name-anp = Angika
language-name-ar = Arab
language-name-ar_001 = Arab Standard Moden
language-name-arn = Mapuche
language-name-arp = Arapaho
language-name-arq = Arab Algeria
language-name-ars = Arab Najdi
language-name-ary = Arab Maghribi
language-name-arz = Arab Mesir
language-name-as = Assam
language-name-asa = Asu
language-name-ast = Asturia
language-name-av = Avaric
language-name-awa = Awadhi
language-name-ay = Aymara
language-name-az = Azerbaijan
language-name-ba = Bashkir
language-name-bal = Baluchi
language-name-ban = Bali
language-name-bas = Basaa
language-name-bax = Bamun
language-name-bbj = Ghomala
language-name-be = Belarus
language-name-bej = Beja
language-name-bem = Bemba
language-name-bez = Bena
language-name-bfd = Bafut
language-name-bg = Bulgaria
language-name-bgn = Balochi Barat
language-name-bho = Bhojpuri
language-name-bi = Bislama
language-name-bin = Bini
language-name-bkm = Kom
language-name-bla = Siksika
language-name-bm = Bambara
language-name-bn = Benggala
language-name-bo = Tibet
language-name-bpy = Bishnupriya
language-name-br = Breton
language-name-brh = Brahui
language-name-brx = Bodo
language-name-bs = Bosnia
language-name-bss = Akoose
language-name-bua = Buriat
language-name-bug = Bugis
language-name-bum = Bulu
language-name-byn = Blin
language-name-byv = Medumba
language-name-ca = Catalonia
language-name-cay = Cayuga
language-name-ce = Chechen
language-name-ceb = Cebuano
language-name-cgg = Chiga
language-name-ch = Chamorro
language-name-chk = Chukese
language-name-chm = Mari
language-name-cho = Choctaw
language-name-chr = Cherokee
language-name-chy = Cheyenne
language-name-ckb = Kurdi Sorani
language-name-co = Corsica
language-name-cop = Coptic
language-name-crh = Turki Krimea
language-name-crs = Perancis Seselwa Creole
language-name-cs = Czech
language-name-cu = Slavik Gereja
language-name-cv = Chuvash
language-name-cy = Wales
language-name-da = Denmark
language-name-dak = Dakota
language-name-dar = Dargwa
language-name-dav = Taita
language-name-de = Jerman
language-name-de_AT = Jerman Austria
language-name-de_CH = Jerman Halus Switzerland
language-name-dgr = Dogrib
language-name-dje = Zarma
language-name-doi = Dogri
language-name-dsb = Sorbian Rendah
language-name-dua = Duala
language-name-dv = Divehi
language-name-dyo = Jola-Fonyi
language-name-dz = Dzongkha
language-name-dzg = Dazaga
language-name-ebu = Embu
language-name-ee = Ewe
language-name-efi = Efik
language-name-eka = Ekajuk
language-name-el = Greek
language-name-en = Inggeris
language-name-en_AU = Inggeris Australia
language-name-en_CA = Inggeris Kanada
language-name-en_GB = Inggeris British
language-name-en_US = Inggeris AS
language-name-eo = Esperanto
language-name-es = Sepanyol
language-name-es_419 = Sepanyol Amerika Latin
language-name-es_ES = Sepanyol Eropah
language-name-es_MX = Sepanyol Mexico
language-name-et = Estonia
language-name-eu = Basque
language-name-ewo = Ewondo
language-name-fa = Parsi
language-name-ff = Fulah
language-name-fi = Finland
language-name-fil = Filipina
language-name-fj = Fiji
language-name-fo = Faroe
language-name-fon = Fon
language-name-fr = Perancis
language-name-fr_CA = Perancis Kanada
language-name-fr_CH = Perancis Switzerland
language-name-frc = Perancis Cajun
language-name-fur = Friulian
language-name-fy = Frisian Barat
language-name-ga = Ireland
language-name-gaa = Ga
language-name-gag = Gagauz
language-name-gan = Cina Gan
language-name-gba = Gbaya
language-name-gbz = Zoroastrian Dari
language-name-gd = Scots Gaelic
language-name-gez = Geez
language-name-gil = Kiribati
language-name-gl = Galicia
language-name-glk = Gilaki
language-name-gn = Guarani
language-name-gor = Gorontalo
language-name-grc = Greek Purba
language-name-gsw = Jerman Switzerland
language-name-gu = Gujerat
language-name-guz = Gusii
language-name-gv = Manx
language-name-gwi = Gwichʼin
language-name-ha = Hausa
language-name-hak = Cina Hakka
language-name-haw = Hawaii
language-name-he = Ibrani
language-name-hi = Hindi
language-name-hil = Hiligaynon
language-name-hmn = Hmong
language-name-hr = Croatia
language-name-hsb = Sorbian Atas
language-name-hsn = Cina Xiang
language-name-ht = Haiti
language-name-hu = Hungary
language-name-hup = Hupa
language-name-hy = Armenia
language-name-hz = Herero
language-name-ia = Interlingua
language-name-iba = Iban
language-name-ibb = Ibibio
language-name-id = Indonesia
language-name-ie = Interlingue
language-name-ig = Igbo
language-name-ii = Sichuan Yi
language-name-ilo = Iloko
language-name-inh = Ingush
language-name-io = Ido
language-name-is = Iceland
language-name-it = Itali
language-name-iu = Inuktitut
language-name-ja = Jepun
language-name-jbo = Lojban
language-name-jgo = Ngomba
language-name-jmc = Machame
language-name-jv = Jawa
language-name-ka = Georgia
language-name-kab = Kabyle
language-name-kac = Kachin
language-name-kaj = Jju
language-name-kam = Kamba
language-name-kbd = Kabardia
language-name-kbl = Kanembu
language-name-kcg = Tyap
language-name-kde = Makonde
language-name-kea = Kabuverdianu
language-name-kfo = Koro
language-name-kg = Kongo
language-name-kha = Khasi
language-name-khq = Koyra Chiini
language-name-khw = Khowar
language-name-ki = Kikuya
language-name-kj = Kuanyama
language-name-kk = Kazakhstan
language-name-kkj = Kako
language-name-kl = Kalaallisut
language-name-kln = Kalenjin
language-name-km = Khmer
language-name-kmb = Kimbundu
language-name-kn = Kannada
language-name-ko = Korea
language-name-koi = Komi-Permyak
language-name-kok = Konkani
language-name-kpe = Kpelle
language-name-kr = Kanuri
language-name-krc = Karachay-Balkar
language-name-krl = Karelian
language-name-kru = Kurukh
language-name-ks = Kashmir
language-name-ksb = Shambala
language-name-ksf = Bafia
language-name-ksh = Colognian
language-name-ku = Kurdish
language-name-kum = Kumyk
language-name-kv = Komi
language-name-kw = Cornish
language-name-ky = Kirghiz
language-name-la = Latin
language-name-lad = Ladino
language-name-lag = Langi
language-name-lah = Lahnda
language-name-lb = Luxembourg
language-name-lez = Lezghian
language-name-lg = Ganda
language-name-li = Limburgish
language-name-lkt = Lakota
language-name-ln = Lingala
language-name-lo = Laos
language-name-lou = Kreol Louisiana
language-name-loz = Lozi
language-name-lrc = Luri Utara
language-name-lt = Lithuania
language-name-lu = Luba-Katanga
language-name-lua = Luba-Lulua
language-name-lun = Lunda
language-name-luo = Luo
language-name-lus = Mizo
language-name-luy = Luyia
language-name-lv = Latvia
language-name-mad = Madura
language-name-maf = Mafa
language-name-mag = Magahi
language-name-mai = Maithili
language-name-mak = Makasar
language-name-mas = Masai
language-name-mde = Maba
language-name-mdf = Moksha
language-name-men = Mende
language-name-mer = Meru
language-name-mfe = Morisyen
language-name-mg = Malagasy
language-name-mgh = Makhuwa-Meetto
language-name-mgo = Meta’
language-name-mh = Marshall
language-name-mi = Maori
language-name-mic = Micmac
language-name-min = Minangkabau
language-name-mk = Macedonia
language-name-ml = Malayalam
language-name-mn = Mongolia
language-name-mni = Manipuri
language-name-moh = Mohawk
language-name-mos = Mossi
language-name-mr = Marathi
language-name-ms = Melayu
language-name-mt = Malta
language-name-mua = Mundang
language-name-mul = Pelbagai Bahasa
language-name-mus = Creek
language-name-mwl = Mirandese
language-name-my = Burma
language-name-mye = Myene
language-name-myv = Erzya
language-name-mzn = Mazanderani
language-name-na = Nauru
language-name-nan = Cina Min Nan
language-name-nap = Neapolitan
language-name-naq = Nama
language-name-nb = Bokmål Norway
language-name-nd = Ndebele Utara
language-name-nds = Jerman Rendah
language-name-nds_NL = Saxon Rendah
language-name-ne = Nepal
language-name-new = Newari
language-name-ng = Ndonga
language-name-nia = Nias
language-name-niu = Niu
language-name-nl = Belanda
language-name-nl_BE = Flemish
language-name-nmg = Kwasio
language-name-nn = Nynorsk Norway
language-name-nnh = Ngiemboon
language-name-no = Norway
language-name-nog = Nogai
language-name-nqo = N’ko
language-name-nr = Ndebele Selatan
language-name-nso = Sotho Utara
language-name-nus = Nuer
language-name-nv = Navajo
language-name-ny = Nyanja
language-name-nyn = Nyankole
language-name-oc = Occitania
language-name-om = Oromo
language-name-or = Odia
language-name-os = Ossete
language-name-pa = Punjabi
language-name-pag = Pangasinan
language-name-pam = Pampanga
language-name-pap = Papiamento
language-name-pau = Palauan
language-name-pcm = Nigerian Pidgin
language-name-pl = Poland
language-name-prg = Prusia
language-name-ps = Pashto
language-name-pt = Portugis
language-name-pt_BR = Portugis Brazil
language-name-pt_PT = Portugis Eropah
language-name-qu = Quechua
language-name-quc = Kʼicheʼ
language-name-rap = Rapanui
language-name-rar = Rarotonga
language-name-rm = Romansh
language-name-rn = Rundi
language-name-ro = Romania
language-name-ro_MD = Moldavia
language-name-rof = Rombo
language-name-root = Root
language-name-ru = Rusia
language-name-rup = Aromanian
language-name-rw = Kinyarwanda
language-name-rwk = Rwa
language-name-sa = Sanskrit
language-name-sad = Sandawe
language-name-sah = Sakha
language-name-saq = Samburu
language-name-sat = Santali
language-name-sba = Ngambay
language-name-sbp = Sangu
language-name-sc = Sardinia
language-name-scn = Sicili
language-name-sco = Scots
language-name-sd = Sindhi
language-name-sdh = Kurdish Selatan
language-name-se = Sami Utara
language-name-see = Seneca
language-name-seh = Sena
language-name-ses = Koyraboro Senni
language-name-sg = Sango
language-name-sh = SerboCroatia
language-name-shi = Tachelhit
language-name-shn = Shan
language-name-shu = Arab Chadian
language-name-si = Sinhala
language-name-sk = Slovak
language-name-sl = Slovenia
language-name-sm = Samoa
language-name-sma = Sami Selatan
language-name-smj = Lule Sami
language-name-smn = Inari Sami
language-name-sms = Skolt Sami
language-name-sn = Shona
language-name-snk = Soninke
language-name-so = Somali
language-name-sq = Albania
language-name-sr = Serbia
language-name-srn = Sranan Tongo
language-name-ss = Swati
language-name-ssy = Saho
language-name-st = Sotho Selatan
language-name-su = Sunda
language-name-suk = Sukuma
language-name-sv = Sweden
language-name-sw = Swahili
language-name-sw_CD = Congo Swahili
language-name-swb = Comoria
language-name-syr = Syriac
language-name-ta = Tamil
language-name-te = Telugu
language-name-tem = Timne
language-name-teo = Teso
language-name-tet = Tetum
language-name-tg = Tajik
language-name-th = Thai
language-name-ti = Tigrinya
language-name-tig = Tigre
language-name-tk = Turkmen
language-name-tlh = Klingon
language-name-tly = Talysh
language-name-tn = Tswana
language-name-to = Tonga
language-name-tpi = Tok Pisin
language-name-tr = Turki
language-name-trv = Taroko
language-name-ts = Tsonga
language-name-tt = Tatar
language-name-tum = Tumbuka
language-name-tvl = Tuvalu
language-name-tw = Twi
language-name-twq = Tasawaq
language-name-ty = Tahiti
language-name-tyv = Tuvinian
language-name-tzm = Tamazight Atlas Tengah
language-name-udm = Udmurt
language-name-ug = Uyghur
language-name-uk = Ukraine
language-name-umb = Umbundu
language-name-und = Bahasa Tidak Diketahui
language-name-ur = Urdu
language-name-uz = Uzbekistan
language-name-vai = Vai
language-name-ve = Venda
language-name-vi = Vietnam
language-name-vo = Volapük
language-name-vun = Vunjo
language-name-wa = Walloon
language-name-wae = Walser
language-name-wal = Wolaytta
language-name-war = Waray
language-name-wbp = Warlpiri
language-name-wo = Wolof
language-name-wuu = Cina Wu
language-name-xal = Kalmyk
language-name-xh = Xhosa
language-name-xog = Soga
language-name-yav = Yangben
language-name-ybb = Yemba
language-name-yi = Yiddish
language-name-yo = Yoruba
language-name-yue = Kantonis
language-name-zgh = Tamazight Maghribi Standard
language-name-zh = Cina
language-name-zh_Hans = Cina Ringkas
language-name-zh_Hant = Cina Tradisional
language-name-zu = Zulu
language-name-zun = Zuni
language-name-zxx = Tiada kandungan linguistik
language-name-zza = Zaza
