language-name-aa = افري
language-name-ab = ابخازي
language-name-ace = اچيني
language-name-ada = ادانگمي
language-name-ady = اديغي
language-name-af = افریکانسي
language-name-agq = اغیمي
language-name-ain = اينويي
language-name-ak = اکاني
language-name-ale = اليوتي
language-name-alt = سویل الټای
language-name-am = امهاري
language-name-an = اراگونېسي
language-name-anp = انگيکي
language-name-ar = عربي
language-name-ar_001 = نوې معياري عربي
language-name-arn = ماپوچه
language-name-arp = اراپاهوي
language-name-as = اسامي
language-name-asa = اسويي
language-name-ast = استورياني
language-name-av = اواري
language-name-awa = اوادي
language-name-ay = ایماري
language-name-az = اذربایجاني
language-name-ba = باشکير
language-name-bal = بلوڅي
language-name-ban = بالنی
language-name-bas = باسا
language-name-be = بېلاروسي
language-name-bem = بیبا
language-name-bez = بينا
language-name-bg = بلغاري
language-name-bho = بهوجپوري
language-name-bi = بسلاما
language-name-bin = بینی
language-name-bla = سکسيکا
language-name-bm = بامره
language-name-bn = بنگالي
language-name-bo = تبتي
language-name-br = برېتون
language-name-brx = بودو
language-name-bs = بوسني
language-name-bug = بگنيايي
language-name-byn = بلین
language-name-ca = کټلاني
language-name-ce = چيچيني
language-name-ceb = سیبوانوي
language-name-cgg = چيگايي
language-name-ch = چمورو
language-name-chk = چواوکي
language-name-chm = ماري
language-name-cho = چوکټاوي
language-name-chr = چېروکي
language-name-chy = شيني
language-name-ckb = منځنۍ کوردي
language-name-co = کورسيکاني
language-name-crs = سسيلوا ڪروئل فرانسوي
language-name-cs = چېکي
language-name-cu = د کليسا سلاوي
language-name-cv = چوواشي
language-name-cy = ويلشي
language-name-da = دانمارکي
language-name-dak = داکوتا
language-name-dar = درگوا
language-name-dav = ټایټا
language-name-de = الماني
language-name-de_AT = آسترالیا آلمان
language-name-de_CH = سوئس لوی جرمن
language-name-dgr = داگرب
language-name-dje = زرما
language-name-dsb = لوړې سربي
language-name-dua = دوالا
language-name-dv = ديویهی
language-name-dyo = جولا فوني
language-name-dz = ژونگکه
language-name-dzg = ډزاګا
language-name-ebu = ایمو
language-name-ee = ايو
language-name-efi = افک
language-name-eka = اکجک
language-name-el = یوناني
language-name-en = انګریزي
language-name-en_CA = کاناډايي انګلیسي
language-name-en_GB = برتانوی انګلیسي
language-name-eo = اسپرانتو
language-name-es = هسپانوي
language-name-es_419 = لاتیني امریکایي اسپانوی
language-name-es_ES = اروپایی اسپانوی
language-name-es_MX = مکسیکو اسپانوی
language-name-et = حبشي
language-name-eu = باسکي
language-name-ewo = اوونڊو
language-name-fa = فارسي
language-name-ff = فلاحہ
language-name-fi = فینلنډي
language-name-fil = فلیپیني
language-name-fj = فجیان
language-name-fo = فاروئې
language-name-fon = فان
language-name-fr = فرانسوي
language-name-fr_CA = کاناډا فرانسي
language-name-fr_CH = سویس فرانسي
language-name-fur = فرائیلیین
language-name-fy = فريزي
language-name-ga = ائيرلېنډي
language-name-gaa = gaa
language-name-gd = سکاټلېنډي ګېلک
language-name-gez = ګیز
language-name-gil = گلبرتي
language-name-gl = ګلېشيايي
language-name-gn = ګوراني
language-name-gor = ګورن ټالو
language-name-gsw = سویس جرمن
language-name-gu = ګجراتي
language-name-guz = ګوسي
language-name-gv = مینکس
language-name-gwi = ګیچین
language-name-ha = هوسا
language-name-haw = هوایی
language-name-he = عبري
language-name-hi = هندي
language-name-hil = ھلیګینون
language-name-hmn = همونګ
language-name-hr = کروواسي
language-name-hsb = پورته صربي
language-name-ht = هيٽي کرولي
language-name-hu = هنگري
language-name-hup = ھوپا
language-name-hy = ارمني
language-name-hz = هیرورو
language-name-iba = ابن
language-name-ibb = ابیبیو
language-name-id = انډونېزي
language-name-ig = اګبو
language-name-ii = سیچیان یی
language-name-ilo = الوکو
language-name-inh = انگش
language-name-io = اڊو
language-name-is = ايسلنډي
language-name-it = ایټالوي
language-name-iu = انوکتیتوت
language-name-ja = جاپاني
language-name-jbo = لوجبان
language-name-jgo = نګبا
language-name-jmc = ماچمی
language-name-jv = جاوايي
language-name-ka = جورجيائي
language-name-kab = کیبیل
language-name-kac = کاچین
language-name-kaj = ججو
language-name-kam = کامبا
language-name-kbd = کابیرین
language-name-kcg = تایپ
language-name-kde = ماکډون
language-name-kea = کابوورډیانو
language-name-kfo = کورو
language-name-kha = خاسې
language-name-khq = کویرا چینی
language-name-ki = ککوؤو
language-name-kj = کواناما
language-name-kk = قازق
language-name-kkj = کاکو
language-name-kl = کلالیسٹ
language-name-kln = کلینجن
language-name-km = خمر
language-name-kmb = کیمبوندو
language-name-kn = کنأډه
language-name-ko = کوریایی
language-name-kok = کنکني
language-name-kpe = کیلي
language-name-kr = کنوری
language-name-krc = کراچی بالکر
language-name-krl = کاریلین
language-name-kru = کورخ
language-name-ks = کشمیري
language-name-ksb = شمبلا
language-name-ksf = بفیا
language-name-ksh = کولوگنيسي
language-name-ku = کردي
language-name-kum = کومک
language-name-kv = کومی
language-name-kw = کرونيشي
language-name-ky = کرګيز
language-name-la = لاتیني
language-name-lad = لاډینو
language-name-lag = لنګی
language-name-lb = لوګزامبورګي
language-name-lez = لیګغیان
language-name-lg = ګانده
language-name-li = لمبرگیانی
language-name-lkt = لکټو
language-name-ln = لنگلا
language-name-lo = لاو
language-name-loz = لوزی
language-name-lrc = شمالي لوری
language-name-lt = ليتواني
language-name-lu = لوبا-کټنګا
language-name-lua = لبا لولوا
language-name-lun = لندا
language-name-luo = لو
language-name-lus = ميزو
language-name-luy = لویا
language-name-lv = لېټواني
language-name-mad = مدراسی
language-name-mag = مګهي
language-name-mai = مایتھلي
language-name-mak = مکاسار
language-name-mas = ماسائي
language-name-mdf = موکشا
language-name-men = مینڊي
language-name-mer = ميرو
language-name-mfe = ماریسیسن
language-name-mg = ملغاسي
language-name-mgh = مکھوامیتو
language-name-mgo = ميټا
language-name-mh = مارشلیز
language-name-mi = ماوري
language-name-mic = ممکق
language-name-min = مينيگاباو
language-name-mk = مقدوني
language-name-ml = مالايالم
language-name-mn = منګولیایی
language-name-mni = مانی پوری
language-name-moh = محاواک
language-name-mos = ماسي
language-name-mr = مراټهي
language-name-ms = ملایا
language-name-mt = مالټايي
language-name-mua = مندانګ
language-name-mul = څو ژبو
language-name-mus = کريکي
language-name-mwl = مرانديز
language-name-my = برمایی
language-name-myv = ارزيا
language-name-mzn = مزاندراني
language-name-na = نایرو
language-name-nap = نيپالين
language-name-naq = ناما
language-name-nb = ناروې بوکمال
language-name-nd = شمالي نديبل
language-name-ne = نېپالي
language-name-new = نيواري
language-name-ng = ندونگا
language-name-nia = نياس
language-name-niu = نیان
language-name-nl = هالېنډي
language-name-nl_BE = فلېمېشي
language-name-nmg = کواسیو
language-name-nnh = نایجیمون
language-name-nog = نوګی
language-name-nqo = نکو
language-name-nr = سويلي نديبيل
language-name-nso = شمالي سوتو
language-name-nus = نویر
language-name-nv = نواجو
language-name-ny = نیانجا
language-name-nyn = نینکول
language-name-oc = اوکسيټاني
language-name-om = اورومو
language-name-or = اوڊيا
language-name-os = اوسیٹک
language-name-pa = پنجابي
language-name-pag = پانګاسین
language-name-pam = پمپانگا
language-name-pap = پاپيامينتو
language-name-pau = پالان
language-name-pcm = نائجیریا پیدجن
language-name-pl = پولنډي
language-name-prg = پروشين
language-name-ps = پښتو
language-name-pt = پورتګالي
language-name-pt_BR = برازیلي پرتګالي
language-name-pt_PT = اروپايي پرتګالي
language-name-qu = کېچوا
language-name-quc = کچی
language-name-rap = رپانوئي
language-name-rar = راروټانګان
language-name-rm = رومانیش
language-name-rn = رونډی
language-name-ro = رومانیایی
language-name-ro_MD = مولداویایی
language-name-rof = رومبو
language-name-root = روټ
language-name-ru = روسي
language-name-rup = اروماني
language-name-rw = کینیارونډا
language-name-rwk = Rwa
language-name-sa = سنسکریټ
language-name-sad = سنډاوی
language-name-sah = سخا
language-name-saq = سمبورو
language-name-sat = سنتالي
language-name-sba = نګبای
language-name-sbp = سانګوو
language-name-sc = سارڊيني
language-name-scn = سیلیسي
language-name-sco = سکاټس
language-name-sd = سندهي
language-name-se = شمالي سامي
language-name-seh = سینا
language-name-ses = کوییرابورو سینی
language-name-sg = سانګو
language-name-shi = تاکلهیټ
language-name-shn = شان
language-name-si = سينهالي
language-name-sk = سلوواکي
language-name-sl = سلوواني
language-name-sm = ساموآن
language-name-sma = سویلي سامی
language-name-smj = لول سامي
language-name-smn = اناري سميع
language-name-sms = سکولټ سمیع
language-name-sn = شونا
language-name-snk = سونینګ
language-name-so = سومالي
language-name-sq = الباني
language-name-sr = سربيائي
language-name-srn = سوران ټونګو
language-name-ss = سواتی
language-name-ssy = سهو
language-name-st = سيسوتو
language-name-su = سوډاني
language-name-suk = سکوما
language-name-sv = سویډنی
language-name-sw = سواهېلي
language-name-sw_CD = کانګو سواهلی
language-name-swb = کومورياني
language-name-syr = سوریاني
language-name-ta = تامیل
language-name-te = تېليګو
language-name-tem = تیمني
language-name-teo = تیسو
language-name-tet = تتوم
language-name-tg = تاجکي
language-name-th = تايلېنډي
language-name-ti = تيګريني
language-name-tig = تیګر
language-name-tk = ترکمني
language-name-tlh = کلينګاني
language-name-tn = سووانا
language-name-to = تونګان
language-name-tpi = توک پیسین
language-name-tr = ترکي
language-name-trv = تاروکو
language-name-ts = سونګا
language-name-tt = تاتار
language-name-tum = تامبوکا
language-name-tvl = تووالو
language-name-twq = تساواق
language-name-ty = تاهیتي
language-name-tyv = توینیان
language-name-tzm = مرکزی اطلس تمازائيٹ
language-name-udm = ادمورت
language-name-ug = اويغوري
language-name-uk = اوکرانايي
language-name-umb = امبوندو
language-name-und = نامعلومه ژبه
language-name-uz = اوزبکي
language-name-vai = وای
language-name-ve = ویندا
language-name-vi = وېتنامي
language-name-vo = والاپوک
language-name-vun = وونجو
language-name-wa = والون
language-name-wae = ولسیر
language-name-wal = ولایټا
language-name-war = وارۍ
language-name-wo = ولوف
language-name-xal = کالمک
language-name-xh = خوسا
language-name-xog = سوګا
language-name-yav = ینګبین
language-name-ybb = یمبا
language-name-yi = يديش
language-name-yo = یوروبا
language-name-yue = کانټوني
language-name-zgh = معياري مراکش تمازټیټ
language-name-zh = چیني
language-name-zh_Hans = ساده چيني
language-name-zh_Hant = دوديزه چيني
language-name-zu = زولو
language-name-zun = زوني
language-name-zxx = نه ژبني منځپانګه
language-name-zza = زازا
