language-name-aa = afar
language-name-ab = abkhazeg
language-name-ace = achineg
language-name-ach = acoli
language-name-ada = adangme
language-name-ady = adygeieg
language-name-ae = avesteg
language-name-aeb = arabeg Tunizia
language-name-af = afrikaans
language-name-afh = afrihili
language-name-agq = aghem
language-name-ain = ainoueg
language-name-ak = akan
language-name-akk = akadeg
language-name-akz = alabamaeg
language-name-ale = aleouteg
language-name-aln = gegeg
language-name-alt = altaieg ar Su
language-name-am = amhareg
language-name-an = aragoneg
language-name-ang = hensaozneg
language-name-anp = angika
language-name-ar = arabeg
language-name-ar_001 = arabeg modern
language-name-arc = arameeg
language-name-arn = araoukaneg
language-name-aro = araona
language-name-arp = arapaho
language-name-arq = arabeg Aljeria
language-name-arw = arawakeg
language-name-ary = arabeg Maroko
language-name-arz = arabeg Egipt
language-name-as = asameg
language-name-asa = asu
language-name-ase = yezh sinoù Amerika
language-name-ast = asturianeg
language-name-av = avar
language-name-awa = awadhi
language-name-ay = aymara
language-name-az = azerbaidjaneg
language-name-ba = bachkir
language-name-bal = baloutchi
language-name-ban = balineg
language-name-bar = bavarieg
language-name-bas = basaa
language-name-be = belaruseg
language-name-bej = bedawieg
language-name-bem = bemba
language-name-bez = bena
language-name-bg = bulgareg
language-name-bgn = baloutchi ar Cʼhornôg
language-name-bho = bhojpuri
language-name-bi = bislama
language-name-bik = bikol
language-name-bin = bini
language-name-bla = siksika
language-name-bm = bambara
language-name-bn = bengali
language-name-bo = tibetaneg
language-name-br = brezhoneg
language-name-bra = braj
language-name-brh = brahweg
language-name-brx = bodo
language-name-bs = bosneg
language-name-bss = akoose
language-name-bua = bouriat
language-name-bug = bugi
language-name-byn = blin
language-name-ca = katalaneg
language-name-cad = caddo
language-name-car = karibeg
language-name-cch = atsam
language-name-ce = tchetcheneg
language-name-ceb = cebuano
language-name-cgg = chigaeg
language-name-ch = chamorru
language-name-chb = chibcha
language-name-chk = chuuk
language-name-chm = marieg
language-name-cho = choktaw
language-name-chp = chipewyan
language-name-chr = cherokee
language-name-chy = cheyenne
language-name-ckb = kurdeg sorani
language-name-co = korseg
language-name-cop = kopteg
language-name-cr = kri
language-name-crh = turkeg Krimea
language-name-crs = kreoleg Sechelez
language-name-cs = tchekeg
language-name-csb = kachoubeg
language-name-cu = slavoneg iliz
language-name-cv = tchouvatch
language-name-cy = kembraeg
language-name-da = daneg
language-name-dak = dakota
language-name-dar = dargwa
language-name-dav = taita
language-name-de = alamaneg
language-name-de_AT = alamaneg Aostria
language-name-de_CH = alamaneg uhel Suis
language-name-del = delaware
language-name-dgr = dogrib
language-name-din = dinka
language-name-dje = zarma
language-name-doi = dogri
language-name-dsb = izelsorabeg
language-name-dua = douala
language-name-dum = nederlandeg krenn
language-name-dv = divehi
language-name-dyo = diola
language-name-dyu = dyula
language-name-dz = dzongkha
language-name-dzg = dazagaeg
language-name-ebu = embu
language-name-ee = ewe
language-name-efi = efik
language-name-egy = henegipteg
language-name-eka = ekajuk
language-name-el = gresianeg
language-name-elx = elameg
language-name-en = saozneg
language-name-en_AU = saozneg Aostralia
language-name-en_CA = saozneg Kanada
language-name-en_GB = saozneg Breizh-Veur
language-name-en_US = saozneg Amerika
language-name-enm = krennsaozneg
language-name-eo = esperanteg
language-name-es = spagnoleg
language-name-es_419 = spagnoleg Amerika latin
language-name-es_ES = spagnoleg Europa
language-name-es_MX = spagnoleg Mecʼhiko
language-name-et = estoneg
language-name-eu = euskareg
language-name-ewo = ewondo
language-name-fa = perseg
language-name-fan = fang
language-name-fat = fanti
language-name-ff = fula
language-name-fi = finneg
language-name-fil = filipineg
language-name-fit = finneg traoñienn an Torne
language-name-fj = fidjieg
language-name-fo = faeroeg
language-name-fon = fon
language-name-fr = galleg
language-name-fr_CA = galleg Kanada
language-name-fr_CH = galleg Suis
language-name-frc = galleg cajun
language-name-frm = krenncʼhalleg
language-name-fro = hencʼhalleg
language-name-frp = arpitaneg
language-name-frr = frizeg an Norzh
language-name-frs = frizeg ar Reter
language-name-fur = frioulaneg
language-name-fy = frizeg ar Cʼhornôg
language-name-ga = iwerzhoneg
language-name-gaa = ga
language-name-gag = gagaouzeg
language-name-gan = sinaeg Gan
language-name-gay = gayo
language-name-gba = gbaya
language-name-gd = skoseg
language-name-gez = gezeg
language-name-gil = gilberteg
language-name-gl = galizeg
language-name-gmh = krennalamaneg uhel
language-name-gn = guarani
language-name-goh = henalamaneg uhel
language-name-gor = gorontalo
language-name-got = goteg
language-name-grb = grebo
language-name-grc = hencʼhresianeg
language-name-gsw = alamaneg Suis
language-name-gu = gujarati
language-name-guz = gusiieg
language-name-gv = manaveg
language-name-gwi = gwich’in
language-name-ha = haousa
language-name-hai = haida
language-name-hak = sinaeg Hakka
language-name-haw = hawaieg
language-name-he = hebraeg
language-name-hi = hindi
language-name-hil = hiligaynon
language-name-hmn = hmong
language-name-ho = hiri motu
language-name-hr = kroateg
language-name-hsb = uhelsorabeg
language-name-hsn = sinaeg Xian
language-name-ht = haitieg
language-name-hu = hungareg
language-name-hup = hupa
language-name-hy = armenianeg
language-name-hz = herero
language-name-ia = interlingua
language-name-iba = iban
language-name-ibb = ibibio
language-name-id = indonezeg
language-name-ie = interlingue
language-name-ig = igbo
language-name-ii = yieg Sichuan
language-name-ik = inupiaq
language-name-ilo = ilokanoeg
language-name-inh = ingoucheg
language-name-io = ido
language-name-is = islandeg
language-name-it = italianeg
language-name-iu = inuktitut
language-name-ja = japaneg
language-name-jam = kreoleg Jamaika
language-name-jbo = lojban
language-name-jgo = ngomba
language-name-jmc = machame
language-name-jpr = yuzev-perseg
language-name-jrb = yuzev-arabeg
language-name-jv = javaneg
language-name-ka = jorjianeg
language-name-kaa = karakalpak
language-name-kab = kabileg
language-name-kac = kachin
language-name-kaj = jju
language-name-kam = kamba
language-name-kbd = kabardeg
language-name-kcg = tyap
language-name-kde = makonde
language-name-kea = kabuverdianu
language-name-kfo = koroeg
language-name-kg = kongo
language-name-kha = khasi
language-name-kho = khotaneg
language-name-khq = koyra chiini
language-name-ki = kikuyu
language-name-kj = kwanyama
language-name-kk = kazak
language-name-kkj = kakoeg
language-name-kl = greunlandeg
language-name-kln = kalendjineg
language-name-km = khmer
language-name-kmb = kimbundu
language-name-kn = kanareg
language-name-ko = koreaneg
language-name-kok = konkani
language-name-kos = kosrae
language-name-kpe = kpelle
language-name-kr = kanouri
language-name-krc = karatchay-balkar
language-name-kri = krio
language-name-krl = karelieg
language-name-kru = kurukh
language-name-ks = kashmiri
language-name-ksb = shambala
language-name-ksf = bafiaeg
language-name-ksh = koluneg
language-name-ku = kurdeg
language-name-kum = koumikeg
language-name-kut = kutenai
language-name-kv = komieg
language-name-kw = kerneveureg
language-name-ky = kirgiz
language-name-la = latin
language-name-lad = ladino
language-name-lag = langi
language-name-lah = lahnda
language-name-lam = lamba
language-name-lb = luksembourgeg
language-name-lez = lezgi
language-name-lfn = lingua franca nova
language-name-lg = ganda
language-name-li = limbourgeg
language-name-lij = ligurieg
language-name-lkt = lakota
language-name-ln = lingala
language-name-lo = laoseg
language-name-lol = mongo
language-name-lou = kreoleg Louiziana
language-name-loz = lozi
language-name-lrc = loureg an Norzh
language-name-lt = lituaneg
language-name-lu = luba-katanga
language-name-lua = luba-lulua
language-name-lui = luiseno
language-name-lun = lunda
language-name-luo = luo
language-name-lus = lushai
language-name-luy = luyia
language-name-lv = latvieg
language-name-lzh = sinaeg lennegel
language-name-mad = madoureg
language-name-mag = magahi
language-name-mai = maithili
language-name-mak = makasar
language-name-mas = masai
language-name-mdf = moksha
language-name-mdr = mandar
language-name-men = mende
language-name-mer = meru
language-name-mfe = moriseg
language-name-mg = malgacheg
language-name-mga = krenniwerzhoneg
language-name-mgh = makhuwa-meetto
language-name-mgo = metaʼ
language-name-mh = marshall
language-name-mi = maori
language-name-mic = mikmakeg
language-name-min = minangkabau
language-name-mk = makedoneg
language-name-ml = malayalam
language-name-mn = mongoleg
language-name-mnc = manchou
language-name-mni = manipuri
language-name-moh = mohawk
language-name-mos = more
language-name-mr = marathi
language-name-mrj = marieg ar Cʼhornôg
language-name-ms = malayseg
language-name-mt = malteg
language-name-mua = moundangeg
language-name-mul = yezhoù lies
language-name-mus = muskogi
language-name-mwl = mirandeg
language-name-my = birmaneg
language-name-myv = erza
language-name-mzn = mazanderaneg
language-name-na = naurueg
language-name-nan = sinaeg Min Nan
language-name-nap = napolitaneg
language-name-naq = nama
language-name-nb = norvegeg bokmål
language-name-nd = ndebele an Norzh
language-name-nds = alamaneg izel
language-name-nds_NL = saksoneg izel
language-name-ne = nepaleg
language-name-new = newari
language-name-ng = ndonga
language-name-nia = nias
language-name-niu = niue
language-name-njo = aoeg
language-name-nl = nederlandeg
language-name-nl_BE = flandrezeg
language-name-nmg = ngoumbeg
language-name-nn = norvegeg nynorsk
language-name-nnh = ngiemboon
language-name-no = norvegeg
language-name-nog = nogay
language-name-non = hennorseg
language-name-nov = novial
language-name-nqo = nkoeg
language-name-nr = ndebele ar Su
language-name-nso = sotho an Norzh
language-name-nus = nouereg
language-name-nv = navacʼho
language-name-nwc = newari klasel
language-name-ny = nyanja
language-name-nym = nyamwezi
language-name-nyn = nyankole
language-name-nyo = nyoro
language-name-oc = okitaneg
language-name-oj = ojibwa
language-name-om = oromoeg
language-name-or = oriya
language-name-os = oseteg
language-name-osa = osage
language-name-ota = turkeg otoman
language-name-pa = punjabi
language-name-pag = pangasinan
language-name-pal = pahlavi
language-name-pam = pampanga
language-name-pap = papiamento
language-name-pau = palau
language-name-pcd = pikardeg
language-name-pcm = pidjin Nigeria
language-name-pdc = alamaneg Pennsylvania
language-name-peo = henberseg
language-name-phn = fenikianeg
language-name-pi = pali
language-name-pl = poloneg
language-name-pms = piemonteg
language-name-pnt = ponteg
language-name-pon = pohnpei
language-name-prg = henbruseg
language-name-pro = henbrovañseg
language-name-ps = pachto
language-name-pt = portugaleg
language-name-pt_BR = portugaleg Brazil
language-name-pt_PT = portugaleg Europa
language-name-qu = kechuaeg
language-name-quc = kʼicheʼ
language-name-qug = kichuaeg Chimborazo
language-name-raj = rajasthani
language-name-rap = rapanui
language-name-rar = rarotonga
language-name-rgn = romagnoleg
language-name-rm = romañcheg
language-name-rn = rundi
language-name-ro = roumaneg
language-name-ro_MD = moldoveg
language-name-rof = rombo
language-name-rom = romanieg
language-name-root = gwrizienn
language-name-ru = rusianeg
language-name-rup = aroumaneg
language-name-rw = kinyarwanda
language-name-rwk = rwa
language-name-sa = sanskriteg
language-name-sad = sandawe
language-name-sah = yakouteg
language-name-sam = arameeg ar Samaritaned
language-name-saq = samburu
language-name-sas = sasak
language-name-sat = santali
language-name-sba = ngambayeg
language-name-sbp = sangu
language-name-sc = sardeg
language-name-scn = sikilieg
language-name-sco = skoteg
language-name-sd = sindhi
language-name-sdc = sasareseg
language-name-se = sámi an Norzh
language-name-seh = sena
language-name-ses = koyraboro senni
language-name-sg = sango
language-name-sga = heniwerzhoneg
language-name-sh = serb-kroateg
language-name-shi = tacheliteg
language-name-shn = shan
language-name-shu = arabeg Tchad
language-name-si = singhaleg
language-name-sid = sidamo
language-name-sk = slovakeg
language-name-sl = sloveneg
language-name-sm = samoan
language-name-sma = sámi ar Su
language-name-smj = sámi Luleå
language-name-smn = sámi Inari
language-name-sms = sámi Skolt
language-name-sn = shona
language-name-snk = soninke
language-name-so = somali
language-name-sog = sogdieg
language-name-sq = albaneg
language-name-sr = serbeg
language-name-srn = sranan tongo
language-name-srr = serer
language-name-ss = swati
language-name-ssy = sahoeg
language-name-st = sotho ar Su
language-name-su = sundaneg
language-name-suk = sukuma
language-name-sux = sumereg
language-name-sv = svedeg
language-name-sw = swahili
language-name-sw_CD = swahili Kongo
language-name-swb = komoreg
language-name-syc = sirieg klasel
language-name-syr = sirieg
language-name-szl = silezieg
language-name-ta = tamileg
language-name-tcy = touloueg
language-name-te = telougou
language-name-tem = temne
language-name-teo = tesoeg
language-name-ter = tereno
language-name-tet = tetum
language-name-tg = tadjik
language-name-th = thai
language-name-ti = tigrigna
language-name-tig = tigreaneg
language-name-tiv = tiv
language-name-tk = turkmeneg
language-name-tkl = tokelau
language-name-tl = tagalog
language-name-tlh = klingon
language-name-tli = tinglit
language-name-tmh = tamacheg
language-name-tn = tswana
language-name-to = tonga
language-name-tog = nyasa tonga
language-name-tpi = tok pisin
language-name-tr = turkeg
language-name-tru = turoyoeg
language-name-trv = taroko
language-name-ts = tsonga
language-name-tsi = tsimshian
language-name-tt = tatar
language-name-tum = tumbuka
language-name-tvl = tuvalu
language-name-tw = twi
language-name-twq = tasawakeg
language-name-ty = tahitianeg
language-name-tyv = touva
language-name-tzm = tamazigteg Kreizatlas
language-name-udm = oudmourteg
language-name-ug = ouigoureg
language-name-uga = ougariteg
language-name-uk = ukraineg
language-name-umb = umbundu
language-name-und = yezh dianav
language-name-ur = ourdou
language-name-uz = ouzbekeg
language-name-vai = vai
language-name-ve = venda
language-name-vec = venezieg
language-name-vep = vepseg
language-name-vi = vietnameg
language-name-vls = flandrezeg ar c’hornôg
language-name-vo = volapük
language-name-vot = votyakeg
language-name-vro = voroeg
language-name-vun = vunjo
language-name-wa = walloneg
language-name-wae = walser
language-name-wal = walamo
language-name-war = waray
language-name-was = washo
language-name-wo = wolof
language-name-wuu = sinaeg Wu
language-name-xal = kalmouk
language-name-xh = xhosa
language-name-xmf = megreleg
language-name-xog = sogaeg
language-name-yao = yao
language-name-yap = yapeg
language-name-yav = yangben
language-name-ybb = yemba
language-name-yi = yiddish
language-name-yo = yorouba
language-name-yue = kantoneg
language-name-za = zhuang
language-name-zap = zapoteg
language-name-zbl = Bliss
language-name-zea = zelandeg
language-name-zen = zenaga
language-name-zgh = tamacheg Maroko standart
language-name-zh = sinaeg
language-name-zh_Hans = sinaeg eeunaet
language-name-zh_Hant = sinaeg hengounel
language-name-zu = zouloueg
language-name-zun = zuni
language-name-zxx = diyezh
language-name-zza = zazakeg
