language-name-aa = Affareg
language-name-ab = Abchaseg
language-name-ace = Acehneg
language-name-ach = Acoli
language-name-ada = Adangmeg
language-name-ady = Circaseg Gorllewinol
language-name-ae = Afestaneg
language-name-aeb = Arabeg Tunisia
language-name-af = Affricâneg
language-name-afh = Affrihili
language-name-agq = Aghemeg
language-name-ain = Ainŵeg
language-name-ak = Acaneg
language-name-akk = Acadeg
language-name-akz = Alabamäeg
language-name-ale = Alewteg
language-name-aln = Ghegeg Albania
language-name-alt = Altäeg Deheuol
language-name-am = Amhareg
language-name-an = Aragoneg
language-name-ang = Hen Saesneg
language-name-anp = Angika
language-name-ar = Arabeg
language-name-ar_001 = Arabeg Modern Safonol
language-name-arc = Aramaeg
language-name-arn = Arawcaneg
language-name-aro = Araonaeg
language-name-arp = Arapaho
language-name-arq = Arabeg Algeria
language-name-arw = Arawaceg
language-name-ary = Arabeg Moroco
language-name-arz = Arabeg yr Aifft
language-name-as = Asameg
language-name-asa = Asw
language-name-ase = Iaith Arwyddion America
language-name-ast = Astwrianeg
language-name-av = Afareg
language-name-awa = Awadhi
language-name-ay = Aymareg
language-name-az = Aserbaijaneg
language-name-az_Arab = Aserbaijaneg Deheuol
language-name-ba = Bashcorteg
language-name-bal = Balwtsi
language-name-ban = Balïeg
language-name-bas = Basâeg
language-name-bax = Bamwmeg
language-name-be = Belarwseg
language-name-bej = Bejäeg
language-name-bem = Bembeg
language-name-bez = Bena
language-name-bfd = Baffwteg
language-name-bfq = Badaga
language-name-bg = Bwlgareg
language-name-bgn = Balochi Gorllewinol
language-name-bho = Bhojpuri
language-name-bi = Bislama
language-name-bin = Bini
language-name-bkm = Comeg
language-name-bla = Siksika
language-name-bm = Bambareg
language-name-bn = Bengaleg
language-name-bo = Tibeteg
language-name-br = Llydaweg
language-name-brh = Brahui
language-name-brx = Bodo
language-name-bs = Bosnieg
language-name-bss = Acwseg
language-name-bua = Bwriateg
language-name-bug = Bwginaeg
language-name-bum = Bwlw
language-name-byn = Blin
language-name-ca = Catalaneg
language-name-cad = Cado
language-name-car = Caribeg
language-name-cch = Atsameg
language-name-ce = Tsietsieneg
language-name-ceb = Cebuano
language-name-cgg = Tsiga
language-name-ch = Tsiamorro
language-name-chk = Chuukaeg
language-name-chm = Marieg
language-name-cho = Siocto
language-name-chr = Tsierocî
language-name-chy = Cheyenne
language-name-ckb = Cwrdeg Sorani
language-name-co = Corseg
language-name-cop = Copteg
language-name-cr = Cri
language-name-crh = Tyrceg y Crimea
language-name-crs = Ffrangeg Seselwa Creole
language-name-cs = Tsieceg
language-name-cu = Hen Slafoneg
language-name-cv = Tshwfasheg
language-name-cy = Cymraeg
language-name-da = Daneg
language-name-dak = Dacotaeg
language-name-dar = Dargwa
language-name-dav = Taita
language-name-de = Almaeneg
language-name-de_AT = Almaeneg Awstria
language-name-de_CH = Almaeneg Safonol y Swistir
language-name-dgr = Dogrib
language-name-din = Dinca
language-name-dje = Sarmaeg
language-name-doi = Dogri
language-name-dsb = Sorbeg Isaf
language-name-dua = Diwaleg
language-name-dum = Iseldireg Canol
language-name-dv = Difehi
language-name-dyo = Jola-Fonyi
language-name-dz = Dzongkha
language-name-dzg = Dazaga
language-name-ebu = Embw
language-name-ee = Ewe
language-name-efi = Efik
language-name-egy = Hen Eiffteg
language-name-eka = Ekajuk
language-name-el = Groeg
language-name-elx = Elameg
language-name-en = Saesneg
language-name-en_AU = Saesneg Awstralia
language-name-en_CA = Saesneg Canada
language-name-en_GB = Saesneg Prydain
language-name-en_US = Saesneg America
language-name-enm = Saesneg Canol
language-name-eo = Esperanto
language-name-es = Sbaeneg
language-name-es_419 = Sbaeneg America Ladin
language-name-es_ES = Sbaeneg Ewrop
language-name-es_MX = Sbaeneg Mecsico
language-name-et = Estoneg
language-name-eu = Basgeg
language-name-ewo = Ewondo
language-name-ext = Extremadureg
language-name-fa = Perseg
language-name-fat = Ffanti
language-name-ff = Ffwla
language-name-fi = Ffinneg
language-name-fil = Ffilipineg
language-name-fit = Ffinneg Tornedal
language-name-fj = Ffijïeg
language-name-fo = Ffaröeg
language-name-fon = Fon
language-name-fr = Ffrangeg
language-name-fr_CA = Ffrangeg Canada
language-name-fr_CH = Ffrangeg y Swistir
language-name-frc = Ffrangeg Cajwn
language-name-frm = Ffrangeg Canol
language-name-fro = Hen Ffrangeg
language-name-frp = Arpitaneg
language-name-frr = Ffriseg Gogleddol
language-name-frs = Ffriseg y Dwyrain
language-name-fur = Ffriwleg
language-name-fy = Ffriseg y Gorllewin
language-name-ga = Gwyddeleg
language-name-gaa = Ga
language-name-gag = Gagauz
language-name-gay = Gaio
language-name-gba = Gbaia
language-name-gbz = Dareg y Zoroastriaid
language-name-gd = Gaeleg yr Alban
language-name-gez = Geez
language-name-gil = Gilberteg
language-name-gl = Galisieg
language-name-gmh = Almaeneg Uchel Canol
language-name-gn = Guaraní
language-name-goh = Hen Almaeneg Uchel
language-name-gor = Gorontalo
language-name-got = Gotheg
language-name-grc = Hen Roeg
language-name-gsw = Almaeneg y Swistir
language-name-gu = Gwjarati
language-name-guz = Gusii
language-name-gv = Manaweg
language-name-gwi = Gwichʼin
language-name-ha = Hawsa
language-name-hai = Haida
language-name-haw = Hawäieg
language-name-he = Hebraeg
language-name-hi = Hindi
language-name-hil = Hiligaynon
language-name-hit = Hetheg
language-name-hmn = Hmongeg
language-name-hr = Croateg
language-name-hsb = Sorbeg Uchaf
language-name-ht = Creol Haiti
language-name-hu = Hwngareg
language-name-hup = Hupa
language-name-hy = Armeneg
language-name-hz = Herero
language-name-ia = Interlingua
language-name-iba = Ibaneg
language-name-ibb = Ibibio
language-name-id = Indoneseg
language-name-ie = Interlingue
language-name-ig = Igbo
language-name-ii = Nwosw
language-name-ik = Inwpiaceg
language-name-ilo = Ilocaneg
language-name-inh = Ingwsieg
language-name-io = Ido
language-name-is = Islandeg
language-name-it = Eidaleg
language-name-iu = Inwctitwt
language-name-ja = Japaneeg
language-name-jbo = Lojban
language-name-jgo = Ngomba
language-name-jmc = Matsiame
language-name-jpr = Iddew-Bersieg
language-name-jrb = Iddew-Arabeg
language-name-jv = Jafanaeg
language-name-ka = Georgeg
language-name-kaa = Cara-Calpaceg
language-name-kab = Cabileg
language-name-kac = Kachin
language-name-kaj = Jju
language-name-kam = Camba
language-name-kbd = Cabardieg
language-name-kcg = Tyapeg
language-name-kde = Macondeg
language-name-kea = Caboferdianeg
language-name-kfo = Koro
language-name-kg = Congo
language-name-kha = Càseg
language-name-khq = Koyra Chiini
language-name-khw = Chowareg
language-name-ki = Kikuyu
language-name-kj = Kuanyama
language-name-kk = Casacheg
language-name-kkj = Kako
language-name-kl = Kalaallisut
language-name-kln = Kalenjin
language-name-km = Chmereg
language-name-kmb = Kimbundu
language-name-kn = Kannada
language-name-ko = Coreeg
language-name-koi = Komi-Permyak
language-name-kok = Concani
language-name-kpe = Kpelle
language-name-kr = Canwri
language-name-krc = Karachay-Balkar
language-name-krl = Careleg
language-name-kru = Kurukh
language-name-ks = Cashmireg
language-name-ksb = Shambala
language-name-ksf = Baffia
language-name-ksh = Cwleneg
language-name-ku = Cwrdeg
language-name-kum = Cwmiceg
language-name-kv = Comi
language-name-kw = Cernyweg
language-name-ky = Cirgiseg
language-name-la = Lladin
language-name-lad = Iddew-Sbaeneg
language-name-lag = Langi
language-name-lah = Lahnda
language-name-lam = Lamba
language-name-lb = Lwcsembwrgeg
language-name-lez = Lezgheg
language-name-lg = Ganda
language-name-li = Limbwrgeg
language-name-lkt = Lakota
language-name-lmo = Lombardeg
language-name-ln = Lingala
language-name-lo = Laoeg
language-name-lol = Mongo
language-name-loz = Lozi
language-name-lrc = Luri Gogleddol
language-name-lt = Lithwaneg
language-name-ltg = Latgaleg
language-name-lu = Luba-Katanga
language-name-lua = Luba-Lulua
language-name-lun = Lwnda
language-name-luo = Lŵo
language-name-lus = Lwshaieg
language-name-luy = Lwyia
language-name-lv = Latfieg
language-name-mad = Madwreg
language-name-mag = Magahi
language-name-mai = Maithili
language-name-mak = Macasareg
language-name-man = Mandingo
language-name-mas = Masai
language-name-mdf = Mocsia
language-name-mdr = Mandareg
language-name-men = Mendeg
language-name-mer = Mêrw
language-name-mfe = Morisyen
language-name-mg = Malagaseg
language-name-mga = Gwyddeleg Canol
language-name-mgh = Makhuwa-Meetto
language-name-mgo = Meta
language-name-mh = Marsialeg
language-name-mi = Maori
language-name-mic = Micmaceg
language-name-min = Minangkabau
language-name-mk = Macedoneg
language-name-ml = Malayalam
language-name-mn = Mongoleg
language-name-mnc = Manshw
language-name-mni = Manipwri
language-name-moh = Mohoceg
language-name-mos = Mosi
language-name-mr = Marathi
language-name-mrj = Mari Gorllewinol
language-name-ms = Maleieg
language-name-mt = Malteg
language-name-mua = Mundang
language-name-mul = Mwy nag un iaith
language-name-mus = Creek
language-name-mwl = Mirandeg
language-name-mwr = Marwari
language-name-my = Byrmaneg
language-name-myv = Erzya
language-name-mzn = Masanderani
language-name-na = Nawrŵeg
language-name-nap = Naplieg
language-name-naq = Nama
language-name-nb = Norwyeg Bokmål
language-name-nd = Ndebele Gogleddol
language-name-nds = Almaeneg Isel
language-name-nds_NL = Sacsoneg Isel
language-name-ne = Nepaleg
language-name-new = Newaeg
language-name-ng = Ndonga
language-name-nia = Nias
language-name-niu = Niuean
language-name-njo = Ao Naga
language-name-nl = Iseldireg
language-name-nl_BE = Fflemeg
language-name-nmg = Kwasio
language-name-nn = Norwyeg Nynorsk
language-name-nnh = Ngiemboon
language-name-no = Norwyeg
language-name-nog = Nogai
language-name-non = Hen Norseg
language-name-nqo = N’Ko
language-name-nr = Ndebele Deheuol
language-name-nso = Sotho Gogleddol
language-name-nus = Nŵereg
language-name-nv = Nafaho
language-name-nwc = Hen Newari
language-name-ny = Nianja
language-name-nym = Niamwezi
language-name-nyn = Niancole
language-name-nyo = Nioro
language-name-nzi = Nzimeg
language-name-oc = Ocsitaneg
language-name-oj = Ojibwa
language-name-om = Oromo
language-name-or = Odia
language-name-os = Oseteg
language-name-osa = Osageg
language-name-ota = Tyrceg Otoman
language-name-pa = Pwnjabeg
language-name-pag = Pangasineg
language-name-pal = Pahlafi
language-name-pam = Pampanga
language-name-pap = Papiamento
language-name-pau = Palawan
language-name-pcd = Picardeg
language-name-pcm = Pidgin Nigeria
language-name-pdc = Almaeneg Pensylfania
language-name-peo = Hen Bersieg
language-name-pfl = Almaeneg Palatin
language-name-phn = Phoeniceg
language-name-pi = Pali
language-name-pl = Pwyleg
language-name-pms = Piedmonteg
language-name-pnt = Ponteg
language-name-pon = Pohnpeianeg
language-name-prg = Prwseg
language-name-pro = Hen Brofensaleg
language-name-ps = Pashto
language-name-pt = Portiwgeeg
language-name-pt_BR = Portiwgeeg Brasil
language-name-pt_PT = Portiwgeeg Ewrop
language-name-qu = Quechua
language-name-quc = K’iche’
language-name-raj = Rajasthaneg
language-name-rap = Rapanŵi
language-name-rar = Raratongeg
language-name-rm = Románsh
language-name-rn = Rwndi
language-name-ro = Rwmaneg
language-name-ro_MD = Moldofeg
language-name-rof = Rombo
language-name-rom = Romani
language-name-root = Y Gwraidd
language-name-rtm = Rotumaneg
language-name-ru = Rwseg
language-name-rup = Aromaneg
language-name-rw = Ciniarŵandeg
language-name-rwk = Rwa
language-name-sa = Sansgrit
language-name-sad = Sandäweg
language-name-sah = Sakha
language-name-sam = Aramaeg Samaria
language-name-saq = Sambŵrw
language-name-sas = Sasaceg
language-name-sat = Santali
language-name-sba = Ngambeieg
language-name-sbp = Sangw
language-name-sc = Sardeg
language-name-scn = Sisileg
language-name-sco = Sgoteg
language-name-sd = Sindhi
language-name-sdc = Sasareseg Sardinia
language-name-sdh = Cwrdeg Deheuol
language-name-se = Sami Gogleddol
language-name-see = Seneca
language-name-seh = Sena
language-name-sei = Seri
language-name-sel = Selcypeg
language-name-ses = Koyraboro Senni
language-name-sg = Sango
language-name-sga = Hen Wyddeleg
language-name-sgs = Samogiteg
language-name-sh = Serbo-Croateg
language-name-shi = Tachelhit
language-name-shn = Shan
language-name-shu = Arabeg Chad
language-name-si = Sinhaleg
language-name-sid = Sidamo
language-name-sk = Slofaceg
language-name-sl = Slofeneg
language-name-sli = Is-silesieg
language-name-sm = Samöeg
language-name-sma = Sami Deheuol
language-name-smj = Sami Lwle
language-name-smn = Sami Inari
language-name-sms = Sami Scolt
language-name-sn = Shona
language-name-snk = Soninceg
language-name-so = Somaleg
language-name-sog = Sogdeg
language-name-sq = Albaneg
language-name-sr = Serbeg
language-name-srn = Sranan Tongo
language-name-srr = Serereg
language-name-ss = Swati
language-name-ssy = Saho
language-name-st = Sesotheg Deheuol
language-name-stq = Ffriseg Saterland
language-name-su = Swndaneg
language-name-suk = Swcwma
language-name-sus = Swsŵeg
language-name-sux = Swmereg
language-name-sv = Swedeg
language-name-sw = Swahili
language-name-sw_CD = Swahili’r Congo
language-name-swb = Comoreg
language-name-syc = Hen Syrieg
language-name-syr = Syrieg
language-name-szl = Silesieg
language-name-ta = Tamileg
language-name-tcy = Tulu
language-name-te = Telugu
language-name-tem = Timneg
language-name-teo = Teso
language-name-ter = Terena
language-name-tet = Tetumeg
language-name-tg = Tajiceg
language-name-th = Thai
language-name-ti = Tigrinya
language-name-tig = Tigreg
language-name-tiv = Tifeg
language-name-tk = Twrcmeneg
language-name-tkl = Tocelaweg
language-name-tkr = Tsakhureg
language-name-tl = Tagalog
language-name-tlh = Klingon
language-name-tli = Llingit
language-name-tly = Talysheg
language-name-tmh = Tamasheceg
language-name-tn = Tswana
language-name-to = Tongeg
language-name-tpi = Tok Pisin
language-name-tr = Tyrceg
language-name-trv = Taroko
language-name-ts = Tsongaeg
language-name-tsd = Tsaconeg
language-name-tt = Tatareg
language-name-tum = Twmbwca
language-name-tvl = Twfalweg
language-name-tw = Twi
language-name-twq = Tasawaq
language-name-ty = Tahitïeg
language-name-tyv = Twfwnieg
language-name-tzm = Tamaseit Canolbarth Moroco
language-name-udm = Fotiaceg
language-name-ug = Uighur
language-name-uga = Wgariteg
language-name-uk = Wcreineg
language-name-umb = Umbundu
language-name-und = Iaith anhysbys
language-name-ur = Wrdw
language-name-uz = Wsbeceg
language-name-vai = Faieg
language-name-ve = Fendeg
language-name-vec = Feniseg
language-name-vep = Feps
language-name-vi = Fietnameg
language-name-vls = Fflemeg Gorllewinol
language-name-vo = Folapük
language-name-vot = Foteg
language-name-vun = Funjo
language-name-wa = Walwneg
language-name-wae = Walsereg
language-name-wal = Walamo
language-name-war = Winarayeg
language-name-was = Washo
language-name-wbp = Warlpiri
language-name-wo = Woloff
language-name-xal = Calmyceg
language-name-xh = Xhosa
language-name-xog = Soga
language-name-yav = Iangben
language-name-ybb = Iembaeg
language-name-yi = Iddew-Almaeneg
language-name-yo = Iorwba
language-name-yue = Cantoneeg
language-name-zap = Zapoteceg
language-name-zbl = Blisssymbols
language-name-zea = Zêlandeg
language-name-zgh = Tamaseit Safonol
language-name-zh = Tsieineeg
language-name-zh_Hans = Tsieineeg Symledig
language-name-zh_Hant = Tsieineeg Traddodiadol
language-name-zu = Swlw
language-name-zun = Swni
language-name-zxx = Dim cynnwys ieithyddol
language-name-zza = Sasäeg
