language-name-aa = အာဖာ
language-name-ab = အဘ်ခါဇီရာ
language-name-ace = အာချေး
language-name-ada = ဒန်မဲ
language-name-ady = အဒိုင်ဂီ
language-name-af = တောင်အာဖရိက
language-name-agq = အာဂ်ဟိန်း
language-name-ain = အိန်နု
language-name-ak = အာကန်
language-name-ale = အာလီယု
language-name-alt = တောင် အာလ်တိုင်း
language-name-am = အမ်ဟာရစ်ခ်
language-name-an = အာရာဂွန်
language-name-ang = အင်ဂလို ဆက္ကစွန်
language-name-anp = အန်ဂီကာ
language-name-ar = အာရဗီ
language-name-arn = မာပုချီ
language-name-arp = အာရာပါဟို
language-name-as = အာသံ
language-name-asa = အာစု
language-name-ast = အက်စတူရီယန်း
language-name-av = အာဗာရစ်ခ်
language-name-awa = အာဝါဒီ
language-name-ay = အိုင်မာရ
language-name-az = အဇာဘိုင်ဂျန်
language-name-ba = ဘက်ရှ်ကာ
language-name-ban = ဘာလီ
language-name-bas = ဘာဆာ
language-name-be = ဘီလာရုစ်
language-name-bem = ဘိန်ဘာ
language-name-bez = ဘီနာ
language-name-bg = ဘူလ်ဂေးရီးယား
language-name-bgn = အနောက် ဘဲလိုချီ
language-name-bho = ဘို့ဂျ်ပူရီ
language-name-bi = ဘစ်စ်လာမာ
language-name-bin = ဘီနီ
language-name-bla = စစ္စီကာ
language-name-bm = ဘန်ဘာရာ
language-name-bn = ဘင်္ဂါလီ
language-name-bo = တိဘက်
language-name-br = ဘရီတွန်
language-name-brx = ဗိုဒို
language-name-bs = ဘော့စ်နီးယား
language-name-bug = ဘူဂစ်စ်
language-name-byn = ဘလင်
language-name-ca = ကတ်တလန်
language-name-ce = ချက်ချန်း
language-name-ceb = စီဗူအာနို
language-name-cgg = ချီဂါ
language-name-ch = ချမိုရို
language-name-chk = ချူကီးစ်
language-name-chm = မာရီ
language-name-cho = ချော့တို
language-name-chr = ချာရိုကီ
language-name-chy = ချေယန်း
language-name-ckb = ဆိုရာနီ
language-name-co = ခိုစီကန်
language-name-cr = ခရီး
language-name-crs = ခရီအိုလီ
language-name-cs = ချက်
language-name-cu = ချပ်ချ် စလာဗစ်
language-name-cv = ချူဗက်ရှ်
language-name-cy = ဝေလ
language-name-da = ဒိန်းမတ်
language-name-dak = ဒါကိုတာ
language-name-dar = ဒါဂ်ဝါ
language-name-dav = တိုင်တာ
language-name-de = ဂျာမန်
language-name-de_AT = ဩစတြီးယား ဂျာမန်
language-name-de_CH = အလီမဲန်နစ် ဂျာမန်
language-name-del = ဒယ်လာဝဲလ်
language-name-dgr = ဒေါ့ဂ်ရစ်ဘ်
language-name-dje = ဇာမာ
language-name-dsb = အနိမ့် ဆိုဘီယန်း
language-name-dua = ဒူအလာ
language-name-dum = အလယ်ပိုင်း ဒတ်ချ်
language-name-dv = ဒီဗာဟီ
language-name-dyo = ဂျိုလာ-ဖွန်ရီ
language-name-dz = ဒဇွန်ကာ
language-name-dzg = ဒဇာဂါ
language-name-ebu = အမ်ဘူ
language-name-ee = အီဝီ
language-name-efi = အာဖိခ်
language-name-egy = ရှေးဟောင်း အီဂျစ်
language-name-eka = အီကာဂျုခ်
language-name-el = ဂရိ
language-name-en = အင်္ဂလိပ်
language-name-en_AU = ဩစတြေးလျှ အင်္ဂလိပ်
language-name-en_CA = ကနေဒါ အင်္ဂလိပ်
language-name-en_GB = ဗြိတိသျှ အင်္ဂလိပ်
language-name-en_US = အမေရိကန် အင်္ဂလိပ်
language-name-enm = အလယ်ပိုင်း အင်္ဂလိပ်
language-name-eo = အက်စ်ပရန်တို
language-name-es = စပိန်
language-name-et = အက်စ်တိုးနီးယား
language-name-eu = ဘာစ်ခ်
language-name-ewo = အီဝန်ဒို
language-name-fa = ပါရှန်
language-name-ff = ဖူလာ
language-name-fi = ဖင်လန်
language-name-fil = ဖိလစ်ပိုင်
language-name-fj = ဖီဂျီ
language-name-fo = ဖာရို
language-name-fon = ဖော်န်
language-name-fr = ပြင်သစ်
language-name-fr_CA = ကနေဒါ ပြင်သစ်
language-name-fr_CH = ဆွစ် ပြင်သစ်
language-name-frm = အလယ်ပိုင်း ပြင်သစ်
language-name-fro = ဖရန်စီစ်
language-name-frr = မြောက် ဖရီစီရန်
language-name-frs = အရှေ့ ဖရီစီရန်
language-name-fur = ဖရူလီယန်း
language-name-fy = အနောက် ဖရီစီရန်
language-name-ga = အိုင်းရစ်ရှ်
language-name-gaa = ဂါ
language-name-gag = ဂါဂုဇ်
language-name-gd = စကော့တစ်ရှ် ဂေးလစ်ခ်
language-name-gez = ဂီးဇ်
language-name-gil = ကာရီဗာတီ
language-name-gl = ဂါလီစီယာ
language-name-gmh = အလယ်ပိုင်း အမြင့် ဂျာမန်
language-name-gn = ဂူအာရာနီ
language-name-gor = ဂိုရိုတာလို
language-name-grc = ရှေးဟောင်း ဂရိ
language-name-gsw = ဆွစ် ဂျာမန်
language-name-gu = ဂူဂျာရသီ
language-name-guz = ဂူစီး
language-name-gv = မန်းဇ်
language-name-gwi = ဂွစ်ချင်
language-name-ha = ဟာဥစာ
language-name-haw = ဟာဝိုင်ယီ
language-name-he = ဟီးဘရူး
language-name-hi = ဟိန္ဒူ
language-name-hil = ဟီလီဂေနွန်
language-name-hmn = မုံ
language-name-hr = ခရိုအေးရှား
language-name-hsb = ဆက္ကဆိုနီ
language-name-ht = ဟေတီ
language-name-hu = ဟန်ဂေရီ
language-name-hup = ဟူပါ
language-name-hy = အာမေးနီးယား
language-name-hz = ဟီရဲရို
language-name-ia = အင်တာလင်ဂွါ
language-name-iba = အီဗန်
language-name-ibb = အီဘီဘီယို
language-name-id = အင်ဒိုနီးရှား
language-name-ig = အစ္ဂဘို
language-name-ii = စီချွမ် ရီ
language-name-ilo = အီလိုကို
language-name-inh = အင်ဂုရှ်
language-name-io = အီဒို
language-name-is = အိုက်စ်လန်
language-name-it = အီတလီ
language-name-iu = အီနုခ်တီတု
language-name-ja = ဂျပန်
language-name-jbo = လိုဂျ်ဘန်
language-name-jgo = ဂွမ်ဘာ
language-name-jmc = မချာမီ
language-name-jpr = ဂျူဒီယို-ပါရှန်
language-name-jrb = ဂျူဒီယို-အာရဗီ
language-name-jv = ဂျာဗား
language-name-ka = ဂျော်ဂျီယာ
language-name-kab = ကဘိုင်လ်
language-name-kac = ကချင်
language-name-kaj = ဂျူအူ
language-name-kam = ကမ်ဘာ
language-name-kbd = ကဘာဒင်
language-name-kcg = တိုင်အပ်
language-name-kde = မာခွန်ဒီ
language-name-kea = ကဘူဗာဒီအာနူ
language-name-kfo = ကိုရို
language-name-kg = ကွန်ဂို
language-name-kha = ခါစီ
language-name-khq = ကိုရာ ချီအီနီ
language-name-ki = ကီကူယူ
language-name-kj = ကွန်းယာမာ
language-name-kk = ကာဇာခ်
language-name-kkj = ကကို
language-name-kl = ကလာအ်လီဆပ်
language-name-kln = ကလန်ဂျင်
language-name-km = ခမာ
language-name-kmb = ကင်ဘွန်ဒူ
language-name-kn = ကန္နာဒါ
language-name-ko = ကိုရီးယား
language-name-koi = ကိုမီ-ပါမြက်
language-name-kok = ကွန်ကနီ
language-name-kpe = ကပ်ပဲလ်
language-name-kr = ကနူရီ
language-name-krc = ကရာချေး-ဘာကာ
language-name-krl = ကာရီလီယန်
language-name-kru = ကူရုပ်ခ်
language-name-ks = ကက်ရှ်မီးယား
language-name-ksb = ရှန်ဘာလာ
language-name-ksf = ဘာဖီအာ
language-name-ksh = ကိုလိုနီယန်း
language-name-ku = ကဒ်
language-name-kum = ကွမ်မိုက်
language-name-kv = ကိုမီ
language-name-kw = ခိုနီရှ်
language-name-ky = ကာဂျစ်
language-name-la = လက်တင်
language-name-lad = လာဒီနို
language-name-lag = လန်ဂီ
language-name-lb = လူဇင်ဘတ်
language-name-lez = လက်ဇ်ဂီးယား
language-name-lg = ဂန်ဒါ
language-name-li = လင်ဘာဂစ်ရှ်
language-name-lkt = လာကိုတာ
language-name-ln = လင်ဂါလာ
language-name-lo = လာအို
language-name-loz = လိုဇီ
language-name-lrc = မြောက်လူရီ
language-name-lt = လစ်သူဝေးနီးယား
language-name-lu = လူဘာ-ကတန်ဂါ
language-name-lua = လူဘာ-လူလူအာ
language-name-lun = လွန်ဒါ
language-name-luo = လူအို
language-name-lus = မီဇို
language-name-luy = လူရီအာ
language-name-lv = လတ်ဗီးယား
language-name-mad = မဒူရာ
language-name-mag = မဂါဟီ
language-name-mai = မိုင်သီလီ
language-name-mak = မကာဆာ
language-name-mas = မာဆိုင်
language-name-mdf = မို့ခ်ရှာ
language-name-men = မန်ဒဲ
language-name-mer = မီရု
language-name-mfe = မောရစ်ရှ
language-name-mg = မာလဂက်စီ
language-name-mga = အလယ်ပိုင်း အိုင်းရစ်ရှ်
language-name-mgh = မာခူဝါ-မီအီတို
language-name-mgo = မီတာ
language-name-mh = မာရှယ်လိဇ်
language-name-mi = မာအိုရီ
language-name-mic = မစ်ခ်မက်ခ်
language-name-min = စူကူမီနန်
language-name-mk = မက်ဆီဒိုးနီးယား
language-name-ml = မလေယာလမ်
language-name-mn = မွန်ဂိုလီးယား
language-name-mnc = မန်ချူး
language-name-mni = မနိပူရ
language-name-moh = မိုဟော့ခ်
language-name-mos = မိုစီ
language-name-mr = မာရသီ
language-name-ms = မလေး
language-name-mt = မော်လ်တာ
language-name-mua = မွန်ဒန်း
language-name-mul = ဘာသာစကား အမျိုးမျိုး
language-name-mus = ခရိခ်
language-name-mwl = မီရန်ဒီးဇ်
language-name-my = မြန်မာ
language-name-myv = အီဇယာ
language-name-mzn = မာဇန်ဒါရန်နီ
language-name-na = နော်ရူး
language-name-nap = နပိုလီတန်
language-name-naq = နာမာ
language-name-nb = နော်ဝေ ဘွတ်ခ်မော်လ်
language-name-nd = မြောက် အွန်န်ဒီဘီလီ
language-name-nds = အနိမ့် ဂျာမန်
language-name-ne = နီပေါ
language-name-new = နီဝါရီ
language-name-ng = အွန်ဒွန်ဂါ
language-name-nia = နီးရပ်စ်
language-name-niu = နူအဲယန်း
language-name-nl = ဒတ်ခ်ျ
language-name-nl_BE = ဖလီမစ်ရှ်
language-name-nmg = ကွာစီအို
language-name-nn = နော်ဝေ နီးနောစ်
language-name-nnh = အွန်ရဲဘွန်း
language-name-no = နော်ဝေး
language-name-nog = နိုဂိုင်
language-name-nqo = အွန်ကို
language-name-nr = တောင် အွန်န်ဘီလီ
language-name-nso = မြောက် ဆိုသို
language-name-nus = နူအာ
language-name-nv = နာဗာဟို
language-name-ny = နရန်ဂျာ
language-name-nyn = နရန်ကိုလီ
language-name-oc = အိုစီတန်
language-name-om = အိုရိုမို
language-name-or = အိုရီရာ
language-name-os = အိုဆဲတစ်ခ်
language-name-pa = ပန်ချာပီ
language-name-pag = ပန်ဂါစီနန်
language-name-pam = ပမ်ပန်ညာ
language-name-pap = ပါပီမင်တို
language-name-pau = ပလာအို
language-name-pcm = နိုင်ဂျီးရီးယား ပစ်ဂျင်
language-name-peo = ပါရှန် အဟောင်း
language-name-pi = ပါဠိ
language-name-pl = ပိုလန်
language-name-prg = ပရူရှန်
language-name-ps = ပက်ရှ်တွန်း
language-name-pt = ပေါ်တူဂီ
language-name-pt_BR = ဘရာဇီး ပေါ်တူဂီ
language-name-pt_PT = ဥရောပ ပေါ်တူဂီ
language-name-qu = ခီချူဝါအိုဝါ
language-name-quc = ကီခ်အီချီ
language-name-rap = ရပန်နူအီ
language-name-rar = ရရိုတွန်ဂန်
language-name-rm = ရောမ
language-name-rn = ရွန်ဒီ
language-name-ro = ရိုမေနီယား
language-name-ro_MD = မော်လဒိုဗာ
language-name-rof = ရွမ်ဘို
language-name-root = မူလရင်းမြစ်
language-name-ru = ရုရှ
language-name-rup = အာရိုမန်းနီးယန်း
language-name-rw = ကင်ရာဝန်ဒါ
language-name-rwk = ရူဝမ်
language-name-sa = သင်္သကရိုက်
language-name-sad = ဆန်ဒါဝီ
language-name-sah = ဆခါ
language-name-saq = ဆမ်ဘူရူ
language-name-sat = ဆန်တာလီ
language-name-sba = အွန်ဂမ်းဘေး
language-name-sbp = ဆန်ဂု
language-name-sc = ဆာဒီနီးယား
language-name-scn = စစ္စလီ
language-name-sco = စကော့တ်
language-name-sd = စင်ဒီ
language-name-se = မြောက် ဆာမိ
language-name-seh = စီနာ
language-name-ses = ကိုရာဘိုရို ဆမ်နီ
language-name-sg = ဆန်ဂို
language-name-sga = အိုင်းရစ် ဟောင်း
language-name-shi = တာချယ်လ်ဟစ်
language-name-shn = ရှမ်း
language-name-si = စင်ဟာလာ
language-name-sk = ဆလိုဗက်
language-name-sl = ဆလိုဗေးနီးယား
language-name-sm = ဆမိုအာ
language-name-sma = တောင် ဆာမိ
language-name-smj = လူလီ ဆာမိ
language-name-smn = အီနာရီ ဆာမိ
language-name-sms = စခိုးလ် ဆမ်မီ
language-name-sn = ရှိုနာ
language-name-snk = ဆိုနင်ကေး
language-name-so = ဆိုမာလီ
language-name-sq = အယ်လ်ဘေးနီးယား
language-name-sr = ဆားဘီးယား
language-name-srn = ဆရာနန် တွန်ဂို
language-name-ss = ဆွာဇီလန်
language-name-ssy = ဆာဟို
language-name-st = တောင်ပိုင်း ဆိုသို
language-name-su = ဆူဒန်
language-name-suk = ဆူကူမာ
language-name-sv = ဆွီဒင်
language-name-sw = ဆွာဟီလီ
language-name-sw_CD = ကွန်ဂို ဆွာဟီလီ
language-name-swb = ကိုမိုရီးယန်း
language-name-syr = ဆီးရီးယား
language-name-ta = တမီးလ်
language-name-te = တီလီဂူ
language-name-tem = တင်မ်နဲ
language-name-teo = တီဆို
language-name-tet = တီတွမ်
language-name-tg = တာဂျစ်
language-name-th = ထိုင်း
language-name-ti = တီဂ်ရင်ယာ
language-name-tig = တီဂရီ
language-name-tk = တာ့ခ်မင်နစ္စတန်
language-name-tlh = ကလင်ဂွန်
language-name-tn = တီဆဝါနာ
language-name-to = တွန်ဂါ
language-name-tpi = တော့ခ် ပိစင်
language-name-tr = တူရကီ
language-name-trv = တရိုကို
language-name-ts = ဆွန်ဂါ
language-name-tt = တာတာ
language-name-tum = တမ်ဘူကာ
language-name-tvl = တူဗာလူ
language-name-twq = တာဆာဝါခ်
language-name-ty = တဟီတီ
language-name-tyv = တူဗန်
language-name-tzm = အလယ်အာ့တလာစ် တာမာဇိုက်
language-name-udm = အူမူရတ်
language-name-ug = ဝီဂါ
language-name-uk = ယူကရိန်း
language-name-umb = အူဘန်ဒူ
language-name-und = မသိသော ဘာသာ
language-name-ur = အူရ်ဒူ
language-name-uz = ဥဇဘတ်
language-name-vai = ဗိုင်
language-name-ve = ဗင်န်ဒါ
language-name-vi = ဗီယက်နမ်
language-name-vo = ဗိုလာပိုက်
language-name-vun = ဗွန်ဂျို
language-name-wa = ဝါလူးန်
language-name-wae = ဝေါလ်ဆာ
language-name-wal = ဝိုလက်တာ
language-name-war = ဝါရေး
language-name-wbp = ဝေါလ်ပီရီ
language-name-wo = ဝူလိုဖ်
language-name-xal = ကာလ်မိုက်
language-name-xh = ဇိုစာ
language-name-xog = ဆိုဂါ
language-name-yav = ရန်ဘဲန်
language-name-ybb = ရမ်ဘာ
language-name-yi = ဂျူး
language-name-yo = ယိုရူဘာ
language-name-yue = ကွမ်တုံ
language-name-zgh = မိုရိုကို တမဇိုက်
language-name-zh = တရုတ်
language-name-zu = ဇူးလူး
language-name-zun = ဇူနီ
language-name-zxx = ဘာသာစကားနှင့် ပတ်သက်သောအရာ မရှိပါ
language-name-zza = ဇာဇာ
