language-name-am = ئەمهەرینجی
language-name-ar = عەرەبی
language-name-as = ئاسامی
language-name-az = ئازەربایجانی
language-name-az_Arab = ئازەربایجانی باشووری
language-name-be = بیلاڕووسی
language-name-bg = بۆلگاری
language-name-bn = بەنگلادێشی
language-name-br = برێتونی
language-name-bs = بۆسنی
language-name-ca = كاتالۆنی
language-name-ckb = کوردیی ناوەندی
language-name-cs = چەكی
language-name-cy = وێلزی
language-name-da = دانماركی
language-name-de = ئاڵمانی
language-name-el = یۆنانی
language-name-en = ئینگلیزی
language-name-en_AU = ئینگلیزیی ئۆسترالیایی
language-name-en_CA = ئینگلیزیی کەنەدایی
language-name-en_GB = ئینگلیزیی بریتانیایی
language-name-en_US = ئینگلیزیی ئەمەریکایی
language-name-eo = ئێسپیرانتۆ
language-name-es = ئیسپانی
language-name-et = ئیستۆنی
language-name-eu = باسکی
language-name-fa = فارسی
language-name-fi = فینلەندی
language-name-fr = فەرانسی
language-name-fy = فریسیی ڕۆژاوا
language-name-ga = ئیرلەندی
language-name-gl = گالیسی
language-name-gn = گووارانی
language-name-gu = گوجاراتی
language-name-he = هیبرێ
language-name-hi = هیندی
language-name-hr = كرواتی
language-name-hy = ئەرمەنی
language-name-id = ئێەندونیزی
language-name-is = ئیسلەندی
language-name-it = ئیتالی
language-name-ja = ژاپۆنی
language-name-jv = جاڤانی
language-name-ka = گۆرجستانی
language-name-kk = کازاخی
language-name-ku = کوردی
language-name-ky = كرگیزی
language-name-la = لاتینی
language-name-ln = لينگالا
language-name-lo = لاوی
language-name-lt = لیتوانی
language-name-lv = لێتۆنی
language-name-mk = ماكێدۆنی
language-name-mn = مەنگۆلی
language-name-mr = ماراتی
language-name-mzn = مازەندەرانی
language-name-ne = نیپالی
language-name-nl = هۆڵەندی
language-name-no = نۆروێژی
language-name-or = ئۆرییا
language-name-pa = پەنجابی
language-name-ps = پەشتوو
language-name-pt = پورتوگالی
language-name-ro = ڕۆمانی
language-name-ru = ڕووسی
language-name-sa = سانسکريت
language-name-sd = سيندی
language-name-sdh = کوردیی باشووری
language-name-si = سینهەلی
language-name-sk = سلۆڤاكی
language-name-sl = سلۆڤێنی
language-name-sma = سامی باشووری
language-name-so = سۆمالی
language-name-sq = ئەڵبانی
language-name-sr = سەربی
language-name-st = سێسۆتۆ
language-name-su = سودانی
language-name-sv = سویدی
language-name-ta = تامیلی
language-name-te = تەلۆگوی
language-name-tg = تاجیکی
language-name-th = تایلەندی
language-name-ti = تیگرینیای
language-name-tk = تورکمانی
language-name-tr = تورکی
language-name-ug = ئويخووری
language-name-uk = ئۆكراینی
language-name-und = زمانی نەناسراو
language-name-ur = ئۆردوو
language-name-uz = ئوزبەکی
language-name-vi = ڤیەتنامی
language-name-zh = چینی
language-name-zu = زولو
